- src/Tasks/Microsoft.Common.CurrentVersion.targets
A much more targeted change for the same issue #2650 solves. Thanks @cdmihai 
Preserve the ItemSpec value after we get target frameworks from project
references.
Closes #2649
> Preserve ItemSpec after GetTargetFrameworks call

- ref/net46/Microsoft.Build/Microsoft.Build.cs
- ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs
- src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs
- src/Build/Evaluation/ItemSpec.cs
- src/Build/Globbing/MSBuildGlob.cs
GetAllGlobs has become part of the VS solution load critical path. This PR does a couple of optimizations:
- makes MsBuildGlob computation lazy, so VS computes it on the first use, not when the solution opens
- reduces allocations
Numbers from GetAllGlobs when simulating the Roslyn.sln solution load:
Not including the lazy glob change:
Including the lazy glob change:
Closes #2647
> GetAllGlobs optimizations

- src/Shared/AssemblyNameExtension.cs
Reduces overall allocations during a build by 4.4%. Measured on building `dotnet new mvc`.
All the accesses of the field were already protected by a call to the lazy instantiation method.
> Reduce allocations of HashSet<AssemblyNameExtension>

- dir.props
- src/Shared/AssemblyUtilities.cs
This is causing 11% of all allocations building Roslyn.sln.
> Avoid cloning AssemblyName

- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
- src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
- src/Shared/XmlUtilities.cs
We don't use ToolsVersion and getting the attibute from XML is costly.  It has to allocate a streeam, a byte[] to read the BOM, and then read elements and attributes.
Fixes #2604
> Stop reading the ToolsVersion from project XML during build

- src/Tasks/Microsoft.Common.CrossTargeting.targets
This case was missed and is failing CI for https://github.com/dotnet/cli/pull/7914
When doing a CrossTargeting build, we need to import NuGet for Restore. This was done by importing the file that used to be dropped with the CLI which would import the real NuGet.targets.
> Import NuGet.targets in CrossTargeting build

- src/Tasks/NativeMethods.cs
Fixes #2673
On non-Windows, MSBuild assumes that the GAC path is the location of the assembly containing `System.String` plus `"/gac"`. This works fine on a standard Mono layout. However, on a non-standard Mono layout (such as the one used by OmniSharp), this throws a `System.IO.DirectoryNotFoundException` when trying enumerate the GAC directories.
This PR fixes the issue by checking with the GAC path exists before enumerating directories within it. If it doesn't, it is assumed that there are no GAC directories to search.
> Don't enumerate GAC directories if the GAC path doesn't exist

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Workaround might be needed until a better solution is found.
* Some scenarios may not have NuGet.targets (e.g. C++ only workload in VS)
> Only import NuGet.targets when it exists

- src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
- src/Build/BackEnd/Components/Logging/LoggingService.cs
- src/Shared/UnitTests/TestEnvironment.cs
When building two or more projects in the same build episode, the list of warnings to treat as errors or warnings to treat as messages is parsed multiple times.
This fixes the issue by checking if the list is already populated for a given project instance.
Fixes #2667
> Fix issue with list of warnings or errors to treat differently can be added to the list multiple times

- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
- src/Tasks/SystemState.cs
The cache is local to one RAR execution, just like the file existence cache.
(times below are relative to all RAR invocations on a Roslyn build)
Before:
After:
Second commit is a code cleanup change that makes everything hard to read.
> Cache directory exists in rar

- src/Tasks/SystemState.cs
Closes #2687
Cause of the issue: 
- RAR uses two caches: a process wide cache and a project specific cache
- The project specific cache is serialized and reused between processes, whereas the process wide cache is not serialized. The process wide cache aggregates the project specific caches as projects are built.
- On every RAR execution, the project specific cache is loaded from disk, and compared against the value process wide cache: https://github.com/Microsoft/msbuild/blob/99d4c838624293725bfbfd1ae75405ec1bb99c4a/src/Tasks/SystemState.cs#L343-L351
- since the project wide cache is deserialized each time, its entries' are different instances from the entries in the process wide cache. This makes the reference equality check fail, and leads to dirtying the cache.
Fix: I chose to reuse …
> RAR does not write to cache file on rebuilds

- dir.props
- src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs
- src/Shared/AssemblyNameExtension.cs
- src/Shared/AssemblyUtilities.cs
- src/Shared/BuildEnvironmentHelper.cs
- src/Shared/InternalErrorException.cs
- src/Shared/Traits.cs
- src/Tasks/AppConfig/DependentAssembly.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
In mvc rebuild (133mb total allocations), reduces AssemblyName allocations 18.3% ->  0.5% and AssemblyNameExtensions 4.5% -> 0.3%. In a Roslyn rebuild (3.2gb total allocations), it reduces AssemblyName 2.3% -> 0.2% and AsssemblyNameExtension 0.6% -> 0.1%.
Commit [#1](https://github.com/Microsoft/msbuild/commit/8d5b139b9fabe58d288a65d4c34fe887fe812ae5) is safe to do, because the AssemblyName was double cloned ...
Commit [#2](https://github.com/Microsoft/msbuild/pull/2676/commits/b292563136731a53858defbac2fda9b1d056d7af) replaces calls to [AssemblyNameExtension.EqualsImpl](https://github.com/Microsoft/msbuild/blob/0a47f62a138b32cb406d058fe7f49c0494aa6c84/src/Shared/AssemblyNameExtension.cs#L670-L733) and [AssemblyNameExtension.CompareBaseNameToImpl](https://github.com/Microsoft/msbuild/blob/ …
> Reduce AssemblyName allocations

- PublishToBlob.proj
- dir.props
- src/.nuget/project.json
- src/UpdateLocalizedResources.targets
SignType=public is functionally equivalent to SignType=oss.  It is what will be passed through the orchestrated build.
Here it implies that oss signing doesn't mean anything without delay signing.  Does this go the other way?
Does this also mean that delay signing is only useful for oss signing?  If so, can I change this to enable delay signing under public/oss?
> Allow SignType=public

- build/NuGetPackages/Microsoft.Build.Framework.nuspec
- ref/net46/Microsoft.Build/Microsoft.Build.cs
- ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs
- src/Build.OM.UnitTests/Definition/Project_Tests.cs
- src/Build/Definition/ProjectLoadSettings.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Resources/Strings.resx
Add `ProjectLoadSettings.IgnoreFaultedImports` flag, behaving like `ProjectLoadSettings.IgnoreEmptyImports`, where an import that throws `InvalidProjectFileException`  will be logged and removed from that evaluation.
This change is to help improve CPS auto-reload of imports. Right now there is no common point for CPS to handle exceptions thrown from evaluation. With auto-reload of imports, it is not uncommon for an invalid project file to be saved, and attempted to reload. Our current design is to validate the file before reloading it, but this is expensive as it requires validating the XML as well as seeing if any project configuration would throw. Even then it is not a perfect system as we can only validate imports we know exist. For example, a conditioned import that goes from false to …
> Add flag to ignore faulted imports

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Currently the `GenerateSatelliteAssemblies` target handles generating satellite assemblies, _unless_ we're using the .NET Core version of MSBuild. In this case we skip `GenerateSatelliteAssemblies` and this is instead handled by the `CoreGenerateSatelliteAssemblies` target in the .NET SDK. This is because `GenerateSatelliteAssemblies` utilizes alink (al.exe) which has no counterpart for .NET Core. Instead, `CoreGenerateSatelliteAssemblies` uses csc.exe to create the assembly.
There are times where it would be helpful to use the .NET Core approach, even when we aren't using the .NET Core MSBuild. For example, al.exe has some key limitations. For example, it has [no support for public-signing](https://github.com/dotnet/roslyn/issues/23191) and [poor handling of …
> Make it easier to opt into "Core" satellite assembly gen

- ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- src/Build.OM.UnitTests/Definition/Project_Tests.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Logging/BinaryLogger/BinaryLogger.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
- src/Build/Resources/Strings.resx
- src/Framework/ProjectImportedEventArgs.cs
Improves logging when an import is ignored.
1. Sets the `ImportedProjectFile` property
2. ~Adds `ProjectImportedEventArgs.ImportException` when an import is ignored. Had to be type `Exception` because `Microsoft.Build.Framework` does not reference `Microsoft.Build`, where that exception lives.~ Exception fails to serialize for .netcore, using `bool ImportIgnored` instead.
3. Logs for `IgnoreMissingImports`
> Skipped import logging

- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
Just a little something I've noticed a while back and never had a chance to correct.
> Set the timestamp and BuildEventContext on unrecognized event args.

- src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
- src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
This allows for backwards compatibility, when a newer version of MSBuild is still able to replay .binlog files created with an older version of MSBuild.
> Add ability to replay .binlogs of older versions.

- src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs
This avoids a possible File Access exception when reading the binlog from a network share where you don't have write access.
> Open the .binlog file as read-only during playback.

- ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
- ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs
- src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
- src/Tasks/AssemblyDependency/Reference.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
SDK half: https://github.com/dotnet/sdk/pull/1725
See there for perf numbers
> Allow references to specify metadata to skip finding dependencies in RAR

- ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs
- src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs
- src/Build.UnitTests/BackEnd/MockLoggingService.cs
- src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs
- src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
- src/Build/BackEnd/Components/Logging/ILoggingService.cs
- src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
- src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
- src/Build/BackEnd/Components/Logging/TargetLoggingContext.cs
- src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
- src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
- src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
- src/Build/Logging/BinaryLogger/BinaryLogger.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
- src/Framework.UnitTests/CustomEventArgSerialization_Tests.cs
- src/Framework.UnitTests/TargetStartedEventArgs_Tests.cs
- src/Framework/Microsoft.Build.Framework.csproj
- src/Framework/TargetBuiltReason.cs
- src/Framework/TargetSkippedEventArgs.cs
- src/Framework/TargetStartedEventArgs.cs
- src/Shared/ResourceUtilities.cs
This adds:
* SkippedTargetEventArgs which provides additional logging information about targets skipped during build.
* BuildReason for both SkippedTargetEventArgs and TargetStartedEventArgs that indicates whether the target was built because of its parent's BeforeTarget, DependsOn, or AfterTarget.
This fixes #2751. It also bumps the version of binlog.
cc: @AndyGerlicher @KirillOsenkov
> Add SkippedTargetEventArgs and BuildReason

- src/MSBuild/XMake.cs
The logic was broken because the `found` variable is not set to true when switches are read from the Directory.Build.rsp.  If `found` is `false`, then the method is not called recursively and the switches from the response file are not added to the list of parameters used.
> Fix issue with processing Directory.Build.rsp

- ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
- src/Build.UnitTests/EvaluationProfiler_Tests.cs
- src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
- src/Build/Evaluation/Profiler/EvaluationProfiler.cs
- src/Build/Evaluation/Profiler/ProfilerResultPrettyPrinter.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
- src/Build/Logging/ProfilerLogger.cs
- src/Framework.UnitTests/ProjectEvaluationFinishedEventArgs_Tests.cs
- src/Framework/Profiler/EvaluationLocation.cs
- src/Shared/NodePacketTranslator.cs
Adds glob-specific profiling under /prof. Every top-level glob call will have an entry in the profiler report, plus a single entry with an aggregated item representing the overall evaluation time spent in glob calls.
> Add globbing information to the profiler

- ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
- ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/XmlPeek_Tests.cs
- src/Tasks/XmlPeek.cs
Added property DisallowDtd in case the user wants to prohibit loading XML
with a DTD clause for additional security reasons. DTD is ignored by
default, but does not prevent loading the XML.
Closes #2141
> Allow XmlPeek into XML containing DTD

- src/Shared/FileMatcher.cs
- src/Shared/UnitTests/FileMatcher_Tests.cs
Pull request is created based on issue #2815
Performance optimization #2392 led to a breaking change in FileMatcher logic. Let's examine the following example with a single web.config file in working directory:
```
<MyFiles Include="**\*" Exclude="web.*.config">
</MyFiles>
```
Before the change @(MyFiles) included web.config because exclude pattern didn't match it. However after the change web.config was excluded from the item group. This is because implementation of FileMatcher.IsMatch() doesn't consider a situation when tail after wildcard (*) is longer than the remaining part of the input during "tail check". This is a pretty common scenario when several file extensions are used.
To be more specific FileMatcher.IsMatch("aba", "ab*ba") should return false instead of true.
I suggest a …
> Breaking Change in FileMatcher: ab*ba pattern matches aba by mistake

- src/Tasks/Microsoft.Common.CurrentVersion.targets
VS design time builds have BuildingProject=false. This makes them not use RAR caching.
By enabling DTB RAR caching, DTB RAR time gets cut down in half on warm caches, and remains mostly unchanged on cold caches.
Times (measured design time builds via the Project System Tools extension 3 times and averaged, on an mvc project):
- no cache: 210ms
- cold cache: 211ms
- warm cache: 108ms
#closes https://github.com/dotnet/project-system/issues/3022
> Do not condition RAR cache on BuildingProject=false

- src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
- src/MSBuild/CommandLineSwitches.cs
- src/MSBuild/Resources/Strings.resx
- src/MSBuild/XMake.cs
If a user does not specify any /restoreProperty arguments, the global properties specified by /property arguments will be used
If a user specifies any /restoreProperty arguments, only those properties will be set during restore
Usage looks like this:
```
/restoreProperty:<n>=<v>
Set or override these project-level properties only
during restore and do not use properties specified
with the /property argument. <n> is the property
name, and <v> is the property value. Use a
semicolon or a comma to separate multiple properties,
or specify each property separately.
(Short form: /rp)
Example:
/restoreProperty:IsRestore=true;MyProperty=value
```
> Implement a /restoreProperty command-line argument for specifying global properties

- src/Build/Definition/Toolset.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Microsoft.Build.csproj
- src/Build/Resources/Constants.cs
- src/Build/Resources/MSBuildAssemblyFileVersion.cs
`MSBuildVersion` will be major.minor.build version of MSBuild according to the `[assembly:AssemblyFileVersion]` attribute (currently `15.6.X`).  This allows build owners to implement errors if a user is using an older version of MSBuild that might not be able to build their source code.
I've implemented an `MSBuildAssemblyFileVersion` class which gets the assembly attribute with a Lazy singleton.  This should create very little overhead and not add any perf cost.
Closes #2350
> Add new MSBuildVersion property

- src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs
- src/Shared/BuildEnvironmentHelper.cs
Some tests caused the test run to hang under mono/osx. This is because
of an `InternalErrorException` being thrown and msbuild trying to launch
and connect to a debugger. We do try to avoid the debugger code path
(`ConsiderDebuggerLaunch`), but it depends on
`BuildEnvironmentHelper.RunningTests` which incorrectly gets set to
`false`.
When running a test runner under mono, the process name is not helpful
to determine if we are running tests as that would be `mono`. Getting
command line arguments, OTOH, do help with this.
So, we use GetCommandLineArgs, also, to check for test runners. We bring
back the old `GetProcessFromCommandLine()` method. And also, add this as
a parameter to the `ResetInstance_ForUnitTestsOnly(..)` method.
Example test that triggered this: …
> [mono][osx] Fix test hangs

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
This avoids first-chance MissingMethodExceptions when evaluating most solutions, such as Roslyn, MonoDevelop and a few other ones I tested.
This is a tactical fix to get the exception out of the way for now. We can think of a proper fix to the binder later. This should also slightly improve evaluation performance - each binder call that throws costs ~1.5 ms on my machine, whereas this method brings it down to ~0.05 ms, so about 30x improvement.
I'm just including the functions I ran into during testing that are in the wild. This list is not exhaustive, because for rare cases we can still fallback to the old behavior, it's just going to be way less common now. I've verified that using this MSBuild in a certain test environment is able to load large solutions without seeing any of the …
> In Expander.cs add a shortcut for some common string methods to bypass binding

- .gitignore
This file is created during cibuilds and may persist if MSBuild is
aborted abnormally. It's a build output like other logs and shouldn't be
checked in.
> 👷 Ignore temporary ProjectImports zip file

- src/Tasks/RedistList.cs
Clickonce tooling relies on IsFrameworkAssembly method in Microsoft.Build.Tasks.Core.dll to determine if the assembly is part of .net framework redist. If so, Clickonce tooling won't publish that assembly. However, IsFraemworkAssembly method doesn't check the assembly version which causes assembly loading failure at runtime.
**Example**
If a project references System.Runtime nupkg 4.3, ClickOnce publish doesn’t include System.Runtime.dll into the publish file list.
> Need to check assembly version when doing IsFrameworkAssembly check

- src/Build.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build/Construction/Solution/ProjectInSolution.cs
Note this doesn't fix the `.dwproj` case. I need to figure out something slightly different for that, but I wanted to send this out because I need to move on for now.
* Check that the schema matches either empty or the MSBuild default schema
when building a solution file.
* Special case .rptproj files. This file format looks like a standard
MSBuild file but specifies ToolsVersion=2.0 and a default XML schema.
Since the XML parser treats that schema as equivalent to empty and empty
is now allowed, there's no good way to determine if it's an MSBuild file
until we try to parse. This results in an error in MSBuild 15 rather
than a warning in MSBuild 14 for solutions with a .rptproj file. To
solve this, the sln build will now allow projects where the schema is
the default MSBuild schema or …
> Check schema when performing a sln build.

- ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
- src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
- src/Framework/Sdk/SdkResolverContext.cs
SDK resolvers can get and set the `State` property on the `SdkResolverContext` they receive.  This state is preserved for the same resolver during the same build submission.  When there is no build submission, the state is not preserved.  Resolvers will need to take account for these considerations.
This will allow the NuGet-based SDK resolver to only look for and parse `global.json` once per build.
Address item 2 in #2803
> Allow SDK resolvers to preserve state

- src/Shared/CoreCLRAssemblyLoader.cs
While debugging something else, I noticed that CoreClrAssemblyLoader.TryGetWellKnownAssembly is being passed an AssemblyLoadContext but is not using it.
The AssemblyResolve event receives an AssemblyLoadContext but we won't end up respecting it and instead will load it into the default context.
> Fix potential issue in CoreClrAssemblyLoader

- build/NuGetPackages/Microsoft.Build.Localization.nuspec
- src/MSBuild.sln
Default "buildAction" is "compile" and default "copyToOutput" is "false"
:cry:
> Fix NuGet.MSBuildSdkResolver content files in localization package

- targets/BootStrapMSBuild.proj
One too many Ctrl+D in VS Code :(
Our CI doesn't catch this and it only happens on a clean enlistment. Our official build did catch it because we package it up for the CoreXT package.
> Undo Newtonsoft.Json bootstrapper change

- src/Shared/NativeMethodsShared.cs
This ensure we won't hit the filesystem a few million times
during project evaluation.
Fixes https://github.com/mono/mono/issues/6530
> [osx] Cache the IsOSX check

- src/Tasks/Microsoft.Common.CurrentVersion.targets
The @(CopyUpToDateMarker) file is not added to @(FileWrites), so it gets
left behind after a Clean.
https://bugzilla.xamarin.com/show_bug.cgi?id=58174
- This is a Xamarin.Android bug, but the same issue is reproducible with
regular .net projects too
> Ensure *.CopyComplete file gets removed on Clean

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Allows having a `ProjectReference` pointing to a project with an incompatible TF, as long as you don't reference the output of that project.
This is common, for example, if you have a netcoreapp1.0 code generator that you want to run in a later project's build.
When we introduced multitargeting support in 15.x, we started doing complicated dances to figure out the "most compatible" TF of the referenced project, given the referencing project's current TF. But that's only relevant if there's going to be a direct reference.
This was especially annoying because adding a solution-level build dependency secretly creates `ProjectReference` items with `ReferenceOutputAssembly=false`, _even though they're not in the project file_.
Fixes #2661 / dotnet/sdk#939.
> Skip TF-compat checks for P2Ps that don't reference output

- src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs
- src/Build/Evaluation/Preprocessor.cs
This issue was similar to https://github.com/Microsoft/msbuild/issues/491, but applied when the path specified in an `Import`'s `Project` attribute itself included `--`.
This was caught now because as part of the toolset update, the temp path is now under the repo root, which has `--` in it in Jenkins.
> Fix preprocessed output when project path specified in import includes `--`

- src/Build.UnitTests/BackEnd/SdkResolverLoader_Tests.cs
- src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
- src/Build/Resources/Strings.resx
A few minor improvements:
1. Make SdkResolverLoader easier to mock by splitting functionality into more virtual methods
2. Add a different error message if the SDK resolver assembly itself cannot be loaded
3. Fix issue where if one resolver failed to load, the remaining ones would not be loaded
4. More unit tests
> Minor improvements to SDK resolver end-user experience

- src/Tasks/Microsoft.Common.CurrentVersion.targets
In The Old Days, binding redirect generation was set to off-by-default.
That has caused a great deal of confusion because it's usually the right
thing to do but it's not obvious when you need to do it.
Unfortunately, we currently think we can't change the default for all
projects, because a user could have been avoiding binding redirects
intentionally, making creating them a breaking change.
Since no projects currently target .NET Framework 4.7.2 (since it's not
released), it is not a breaking change to turn on binding redirects by
default for this (and higher) versions--a user must explicitly opt into
targeting the framework and thus into this new behavior.
A user can still specify
```xml
<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
```
to explicitly opt out of …
> Generate binding redirects for .NET 4.7.2+

- src/Build.OM.UnitTests/Construction/ProjectSdkImplicitImport_Tests.cs
- src/Build/Evaluation/ProjectParser.cs
All the code was here but the attribute was not allowed on the Import
element at project parse time for Version or MinimumVersion. This change
allows those attributes and rest of the code worked as expected. Added
tests for the scenario and a few others.
> Allow SDK Version in explicit project imports

- src/Build.UnitTests/BackEnd/MockLoggingService.cs
- src/Build.UnitTests/Evaluation/EvaluationLogging_Tests.cs
- src/Build/BackEnd/Components/Logging/EvaluationLoggingContext.cs
- src/Build/BackEnd/Components/Logging/ILoggingService.cs
- src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
- src/Build/Evaluation/Evaluator.cs
- src/Shared/UnitTests/MockLogger.cs
CPS expects Project.LastEvaluationId to reflect the id of the ongoing, not yet finished evaluation.
This invariant regressed in #2748
LoggingService now creates an evaluation build event context separate from sending project started events. This allows the Evaluator to set the evaluation Id on Project before the first evaluation event gets fired.
> Project.LastEvaluationId should be valid during logging

- setup/MsBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
This doesn't appear to be used and is not copied by the build. No idea
how this worked before, sync to the last successful build also does not
produce this file. This is failing our official build.
MSBuild only references System.Diagnostics.Process for netstandard, not
for net46 so appears to have been added by mistake.
> Remove System.Diagnostics.Process from CoreXT pkg

- src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs
- src/Build/Evaluation/Preprocessor.cs
Implicit imports for imported projects are shown in the preprocessor at the top and bottom of the top level project rather than the imported project.
To fix this, I've created a mapping of which documents contain the implicit imports.  Before processing a document, the imports are then added to that document rather than the top level one.
> Fix preprocessor when imported documents specify Sdk

- src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs
- src/Build/Evaluation/Preprocessor.cs
* Fix preprocessor when imported documents specify Sdk
Implicit imports for imported projects are shown in the preprocessor at the top and bottom of the top level project rather than the imported project.
To fix this, I've created a mapping of which documents contain the implicit imports.  Before processing a document, the imports are then added to that document rather than the top level one.
* Add unit test
> RI vs15.6 to master

- Directory.Build.rsp
- src/Package/ReferenceAssemblies/Directory.Build.props
- src/Samples/PortableTask/PortableTask.csproj
- src/Shared/UnitTests/FileMatcher_Tests.cs
- src/Tasks.UnitTests/PortableTasks_Tests.cs
Also fixed up `FileMatcher_Tests` as I was getting some random failures about directories already being there or not being there.
And added a `Directory.Build.rsp` to set `/verbosity:minimal /m /clp:Summary`
> Remove netstandard1.3 reference source

- build/build.ps1
- build/cibuild.cmd
- src/Directory.Build.targets
I fix some problem with paths include spaces.
I now one more problem but can't fix it:
```
Packaging ...
MSBUILD : error MSB1008: Only one project can be specified. [C:\Users\mikha\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62512-02\tools\Build.proj]
Switch: folder\msbuild\
For switch syntax, type "MSBuild /help"
C:\Users\mikha\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62512-02\tools\Build.proj(191,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\MSBuild.exe" /nodeReuse:fal
se "D:\Work\space folder\msbuild\MSBuild.sln" /nologo /m /v:minimal /t:Pack /p:NoBuild=true /bl:"D:\Work\space folder\msbuild\artifacts\Debug\log\Pack.binlog" /p:Configuration=Debug /p:CIBuild=True /p:RepoRoot=D:\Work\space folder\msbui …
```
> Fix some spaces problem

- build/build.ps1
- src/Build.OM.UnitTests/Instance/ProjectInstance_Tests.cs
- src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
- src/Build.UnitTests/EvaluationProfiler_Tests.cs
- src/Build.UnitTests/ExpressionTree_Tests.cs
- src/Build.UnitTests/FixPathOnUnix_Tests.cs
- src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
- src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
- src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
- src/MSBuild.UnitTests/XMake_Tests.cs
- src/Shared/UnitTests/AssemblyResources.cs
- src/Shared/UnitTests/EngineTestEnvironment.cs
- src/Shared/UnitTests/FileMatcher_Tests.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
- src/Shared/UnitTests/TestAssemblyInfo.cs
- src/Shared/UnitTests/TestEnvironment.cs
- src/Tasks.UnitTests/Exec_Tests.cs
- src/Tasks.UnitTests/FileStateTests.cs
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
- src/Tasks.UnitTests/PortableTasks_Tests.cs
- src/Tasks.UnitTests/ProjectExtensionsImportTestBase.cs
- src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
- src/Utilities.UnitTests/ToolTask_Tests.cs
- src/Utilities/Microsoft.Build.Utilities.csproj
- Unique temp for each test assembly. With the new tooling, tests run in parallel across test assemblies, and sequential within one assembly. [TestAssemblyInfo](https://github.com/Microsoft/msbuild/blob/exp/update-toolset/src/Shared/UnitTests/TestAssemblyInfo.cs) ensures that each test assembly gets its own temp directory. On !windows it failed to do this right, so I made it use TestEnvironment to ensure proper setup / cleanup of the temp dir. This meant doing some surgery on the TestEnvironment:
- Separate generic invariants / variants from build specific ones. This enables all test assemblies to reference TestEnvironment without having to also depend on Microsoft.Build.dll
- Make Microsoft.Build.Framework.UnitTests depend on TestEnvironment
- Make some temp paths unique
I'll also try …
> Reduce test flakiness

- THIRDPARTYNOTICES.txt
This is for the [Assembly Fixture support](https://github.com/Microsoft/msbuild/tree/master/src/Xunit.NetCore.Extensions/AssemblyFixtureSupport), which was originally copied from https://github.com/xunit/samples.xunit/tree/master/AssemblyFixtureExample
XUnit doesn't have built-in capability to have assembly-level test startup / shutdown code (without annotating each test as being part of a collection).  If you want to do that, you need to take the sample code and adapt it as necessary.
> Update third party notice to include Samples for xUnit.net notice

- src/Tasks/ManifestUtil/mansign2.cs
This is to fix the regression caused by adding support of CNG cert signing. When VS(msbuild) running on .net 4.6.1 and SHA256 cert being used in signing manifest file, we need to update the RSA provider type to PROV_RSA_AES which is the only provider that supporst SHA2 operations.
> fix signing issue with sha256 cert on 4.6.1

- src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
- src/MSBuild/MSBuild.csproj
- src/Package/GetBinPaths.targets
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
Workaround #2922.  This was fixed in https://github.com/Microsoft/msbuild/commit/afccbb11e11e9d60af474821a38882156a0354b4 and #2935, but if your stage 0 MSBuild has the bug, you will still fail to build.  This PR works around it.
Once the fix makes it into Preview releases of VS, we can revert this.
> Workaround #2922

- src/Package/ReferenceAssemblies/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
Enables the GetAssemblyIdentity task on the new ns2.0 build.
> Include GetAssemblyIdentity task in netstandard2.0 build.

- src/NuGetSdkResolver/NuGetSdkResolver.cs
Since some non-Windows file systems are case sensitive, SDK authors will need to know that the "Sdk" folder is supposed to be capitalized.
This change makes it so that SDK package owners can use "Sdk" or "sdk".  See relevant discuss here: https://github.com/Microsoft/msbuild/issues/2803#issuecomment-360617172
There will be a little overhead to check directory existence.
> Support folder name "Sdk" or "sdk" in NuGet SDK resolver

- src/NuGetSdkResolver.UnitTests/NuGetSdkResolver_Tests.cs
- src/NuGetSdkResolver/NuGetSdkResolver.cs
- src/NuGetSdkResolver/NuGetSdkResolverBase.cs
My original intent was to wire up the AssemblyResolve event as soon as possible.  Later I moved all NuGet type references to private classes instead which means that NuGet assemblies are not loaded until these private classes are accessed.  The private classes are not accessed unless the user specified a version.
So wiring up AssemblyResolve in a static constructor means that in Visual Studio all AssemblyResolve events are sent through the NuGet SDK resolver which is not ideal.  Instead, it can be wired up prior to resolving an SDK and then removed.
I also added a unit test to ensure that NuGet assemblies are not loaded when no version is specified.
> Stop using static constructor to wire up AssemblyResolve event handler in NuGetSdkResolver

- src/Tasks/Microsoft.Common.CurrentVersion.targets
This reverts commit 91c86a746b312fce1aba31f8fb8540e949c11a01.
Fixes #2922 but undoes the fix for #2661.
Details as to why in https://github.com/Microsoft/msbuild/pull/2923#issuecomment-361999701 and https://github.com/Microsoft/msbuild/pull/2867#issuecomment-361998280.
> Do not avoid best-match TF checks for ReferenceOutputAssembly=false

- documentation/ProjectReference-Protocol.md
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Closes #2877 and fixes #2922 by ensuring that projects that do not
define `GetNativeManifest` and `GetNativeManifest` targets (such as the
"outer" build of a multitargeting SDK project) are referencable with
`ReferenceOutputAssembly=false` (or other means of avoiding the
TargetFramework-compatibility check).
Includes updates to the ProjectReference Protocol documentation.
> Mark P2P-protocol targets as optional

- src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverResponse.cs
In a multi-proc build when an SDK could not be found, a NullReferenceException would occur which would crash the thread on the main node responsible for responding to SDK resolution requests.  The out-of-proc node would then hang waiting for a response and MSBuild's main thread would be waiting for the out-of-proc node to finish.
The code is more resilient now by catching all exceptions and sending the response in a finally.  Any errors that occur in the request handler thread are sent back to the out-of-proc node to be logged.
> Fix node task crash in SDK resolution which hangs MSBuild.exe

- netci.groovy
Before, we were archiving a slightly different pattern from what the Jenkins plugin was scraping test results from, which could have led to confusion.
> Use same pattern for test results as artifacts

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Shared/NativeMethodsShared.cs
Avoids a handle leak when spawning worker nodes.
Fixes #2974.
> Close handles returned from CreateProcess

- src/Shared/BuildEnvironmentHelper.cs
Fixes the problem where a program using the MSBuild API and
containing the string "MSBuild" in its name was incorrectly detected as
running in MSBuild.exe in standalone mode.
Fixes #2194.
Note that the concerns in https://github.com/Microsoft/msbuild/issues/2194#issuecomment-307151488 about test detection no longer applies after b8d01363.
> Check exact match for "running msbuild.exe"

- build/build.ps1
- build/build.sh
Often, the MSBuild version is a bit noisy. But in our own repo, it's extremely helpful to know which version of MSBuild is running the build: an LKG? the just-built one?
So drop all instance of /nologo from MSBuild invocations here.
> Emit logo in MSBuild repo builds

- build/SignToolData.json
- build/build.ps1
- build/build.sh
- src/Directory.Build.props
- src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
- src/Package/Localization/Localization.csproj
This resolves issues debugging when using types that are available only in 2.1 runtime. Regardless of this change, CLI will be on 2.1 so this change should be safe.
> Upgrade to netcoreapp2.1

- src/Build.OM.UnitTests/Construction/ProjectSdkImplicitImport_Tests.cs
- src/Build/Evaluation/Evaluator.cs
InvalidProjectFileExceptions cause modal dialogs in Visual Studio which so we should respect `ProjectLoadSettings`.
Related to https://github.com/dotnet/project-system/issues/3240
> Do not throw an InvalidProjectFileException if ProjectLoadSettings.IgnoreMissingImports is specified

- build/SignToolData.json
- src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
Condition on including the `ProducesNoOutput` props file was inverted and that import clears all the content items so nothing gets produced.
> Build and sign VSIX VS insertion project.

- src/Build.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build/Construction/Solution/ProjectInSolution.cs
Add a test that will fail on forward-slash OSes when reading a
backslash-containing relative path from a solution file.
Regression test for #2022.
> Support backslashes in solution paths

- setup/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
This is required to switch internal VS build processes off of the (obsolete) fork of MSBuild that's still checked into the VS repo. These projects are referenced but weren't available in the ExternalAPIs package.
> Include obsolete assemblies in ExternalAPIs

- build/SetMicrobuildVersion/SetMicrobuildVersion.csproj
We'll call this project first in Microbuild to set the version, before the swix plugin gets installed
> Add dummy project to set GitBuildVersion

- src/Shared/Resources/Strings.shared.resx
- src/Shared/Resources/xlf/Strings.shared.cs.xlf
- src/Shared/Resources/xlf/Strings.shared.de.xlf
- src/Shared/Resources/xlf/Strings.shared.en.xlf
- src/Shared/Resources/xlf/Strings.shared.es.xlf
- src/Shared/Resources/xlf/Strings.shared.fr.xlf
- src/Shared/Resources/xlf/Strings.shared.it.xlf
- src/Shared/Resources/xlf/Strings.shared.ja.xlf
- src/Shared/Resources/xlf/Strings.shared.ko.xlf
- src/Shared/Resources/xlf/Strings.shared.pl.xlf
- src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
- src/Shared/Resources/xlf/Strings.shared.ru.xlf
- src/Shared/Resources/xlf/Strings.shared.tr.xlf
- src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
- src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf
- src/Utilities/ToolTask.cs
Fixes #3028
I can't really test this. I do see from inspection of the Process code that ProcessName getter will only throw in the situation where the process has exited.
> Fix unhandled exception when tooltask process exits at a certain moment during cancelation

- src/MSBuild/MSBuild.csproj
Not all files in the package were marked as "Content" because they are in a different item group.
1. Disable AddAppConfigToBuildOutputs otherwise we end up with an app.config in the netstandard2.0 folder
2. Copy _BuildOutputInPackage to _PackageFiles with metadata so that all files in the package are content files
3. Clear _BuildOutputInPackage since we don't want any files in the package to NOT be content
> Fix some content files in Microsoft.Build.Runtime

- src/MSBuild/MSBuild.csproj
For some reason the official build is including MSBuild.dll which causes errors when consuming the package
> Exclude MSBuild.pdb from Microsoft.Build.Runtime

- src/Tasks.UnitTests/RemoveDuplicates_Tests.cs
The RemoveDuplicates task can be made more useful to consumers if its
contract is strengthened to say that the Filtered output is guaranteed
to be in the same order as its Inputs. It's current implementation has
this behavior, so additional unit tests have been added to ensure this
does not regress.
Related: https://github.com/MicrosoftDocs/visualstudio-docs/issues/622
> Add test that RemoveDuplicates preserves order

- src/Directory.Build.props
- src/Directory.Build.targets
Repotoolset's mechanism is mysterious and does not magically work for our repo, so we're manually importing the microbuild plugin for PGO.
> Enable PGO in microbuild

- netci.groovy
Avoid red CI tests by just disabling Mac testing until https://github.com/dotnet/core-eng/issues/2808 gets fixed.
> Disable macOS CI

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/MSBuild/Microsoft.Build.CommonTypes.xsd
- src/Tasks.UnitTests/RemoveDuplicates_Tests.cs
- src/Tasks/ListOperators/RemoveDuplicates.cs
Three different commits here. Copy/pasting their summaries to make them more readable.
- - -
Add HadAnyDuplicates output to RemoveDuplicates task
The `HadAnyDuplicates` output indicates whether the input list contained
any duplicates. This makes it easier to implement checks that Items
don't contain any duplicates (e.g., to error if duplicate compilation
would occur).
Fixes #1541
- - -
Refactor RemoveDuplicates task to use C# 6 auto properties
Also, minor refactoring to use var to reduce duplication of type names.
- - -
Refactor RemoveDuplicates: use HashSet and List
The RemoveDuplicates task has been refactored to use `HashSet<string>` and
`List<ITaskItem>` from `System.Collections.Generic` over the previous
non-generic `Hashtable` and `ArrayList` implementation.
Recent versions of …
> Add HadAnyDuplicates to RemoveDuplicates task

- build/Versions.props
- src/Directory.Build.props
The new toolset includes fixes required by Orchestrated and Source builds.
> Update to RepoToolset 1.0.0-beta-62705-01

- src/Directory.Build.targets
1. Make it possible to get verbose output from tlbexp. This is useful for debugging issues with .tlb generation.
2. Slightly simplify how we generate the `/asmpath` argument.
What I *really* wanted to do was explicitly specify the type lib references using the `/tlbrefpath` and `/tlbreference` arguments rather than letting tlbexp find them magically. Unfortunately this quickly devolves into specifying the location of things like mscorlib.tlb and stdole2.tlb, which aren't part of an SDK or reference assemblies (at least, not that I can find). The VS repo solves this by having copies of these files checked-in. I don't want to go down that path, so I've given up and just let tlbexp find the referenced type libs on its own. This is probably fine for the purposes of MSBuild--it's not like …
> Minor changes to CreateTypeLib

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
- src/Shared/CommunicationsUtilities.cs
The current handshake for task host communication uses only the assembly
major version portion. This causes issue if the protocol is changed for
any '15' release. Changed the FileVersionHash to hash the full assembly
informational version (which includes the commit hash, e.g.
'15.7.79-preview+g60af12df92').
> Update FileVersionHash used in node communications

- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
- src/Build/Logging/LoggerDescription.cs
- src/Build/Microsoft.Build.csproj
- src/Directory.BeforeCommon.targets
- src/Framework.UnitTests/CustomEventArgSerialization_Tests.cs
- src/Framework/BuildErrorEventArgs.cs
- src/Framework/BuildEventArgs.cs
- src/Framework/BuildMessageEventArgs.cs
- src/Framework/BuildWarningEventArgs.cs
- src/Framework/LazyFormattedBuildEventArgs.cs
- src/Framework/Microsoft.Build.Framework.csproj
- src/Framework/ProjectFinishedEventArgs.cs
- src/Framework/ProjectStartedEventArgs.cs
- src/Framework/TargetFinishedEventArgs.cs
- src/Framework/TargetStartedEventArgs.cs
- src/Framework/TaskFinishedEventArgs.cs
- src/Framework/TaskStartedEventArgs.cs
- src/Shared/AssemblyNameExtension.cs
- src/Shared/BinaryWriterExtensions.cs
- src/Shared/TaskHostConfiguration.cs
- src/Shared/UnitTests/TestEnvironment.cs
- src/Shared/UnitTests/xunit.runner.json
- src/Tasks.UnitTests/GenerateResource_Tests.cs
- src/Tasks/GenerateResource.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/StateFileBase.cs
- src/Tasks/SystemState.cs
Preliminary numbers on a basic netcoreapp2.0 -> netstandard2.0 library sln:
Tip of `exp/update-toolset` branch rebuild:
```
439 ms  ResolveAssemblyReferences                  2 calls
437 ms  ResolveAssemblyReference                   2 calls
```
This branch with RAR *.Core.cache file:
```
238 ms  ResolveAssemblyReferences                  2 calls
237 ms  ResolveAssemblyReference                   2 calls
```
This branch after deleting *.Core.cache:
```
312 ms  ResolveAssemblyReferences                  2 calls
311 ms  ResolveAssemblyReference                   2 calls
```
So even without the cache file it's still after with binary serialization turned on. Not sure why (there's a lot of code that differs). Also haven't done anything other than manual testing.
> Enable cache for RAR

- build/build.ps1
- build/build.sh
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/Shared/ExceptionHandling.cs
Currently trying to figure out why the build is failing inside an Alpine Linux docker container, but I can't get the log files because the container file system is automatically cleaned up.
This supports setting MSBUILDDEBUGPATH to control where MSBuild dump files are written.
cref https://github.com/Microsoft/msbuild/issues/1038
cc @cdmihai
> Honor MSBUILDDEBUGPATH when dumping exception information to file

- build/Versions.props
- src/Shared/FileMatcher.cs
- src/Shared/UnitTests/FileMatcher_Tests.cs
Update .NET CLI from 2.1.300-preview2-008046 to 2.1.300-preview2-008293
This pulls in changes to corefx where non-Windows will now have more consistent behavior with Windows in regards to file pattern matching.  Unfortunately, the behavior in Windows is incorrect for our needs so we now need to manually correct matches on all platforms.
https://github.com/dotnet/corefx/issues/27779
Tracking updating the behavior later here: https://github.com/Microsoft/msbuild/issues/3060
> Update .NET CLI and fix change in file pattern match behavior on non-Windows

- src/Build/BackEnd/BuildManager/BuildManager.cs
We have crash reports of a race condition in the AddNewConfiguration
method. Adding a lock to the only entry to that method currently without
a lock.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/548385
>  Fix race adding configuration in BuildManager

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
The child process will instead inherit the setting from its parent.
> Removed the forced normal priority when creating a new node.

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Adds a few extensibility points to common targets that enable source control and SourceLink package features and fully deterministic compilation.
See https://github.com/tmat/repository-info/blob/master/docs/Readme.md for details.
TODO:
Supersedes https://github.com/Microsoft/msbuild/pull/2960
> Add source control information extensibility point

- src/Directory.BeforeCommon.targets
- src/Shared/AssemblyNameComparer.cs
- src/Shared/AssemblyNameExtension.cs
- src/Shared/UnitTests/AssemblyNameEx_Tests.cs
- src/Tasks/StateFileBase.cs
There were some subtle issues with AssemblyNameExtension serialization:
* Added hasAN and hasCI to indicate whether an AssemblyName or CultureInfo was serialized (and used them correctly).
* Switched from CultureInfo Name -> LCID. The default invariant culture has no Name, but has an LCID.
* Serialized the remappedFrom HashSet field.
* Added unit tests to verify serialization is correct.
It wasn't trivial to repro (originally) so I verified a lot of this manually and did some cleanup on the way. Verified it fixes the issue in the repro. I removed `FEATURE_ASSEMBLYNAME_CULTUREINFO` since it was only used in AssemblyNameExtension and no longer needed for `netstandard2.0`
>  Fix serialization issue with AssemblyNameExtension

- src/Tasks.UnitTests/ProjectExtensionsImportTestBase.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/Microsoft.Common.props
- src/Tasks/Resources/Strings.resx
If `MSBuildProjectExtensionsPath` is set in a project like this:
```xml
<MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory)</MSBuildProjectExtensionsPath>
</Project>
```
The value used by the top implicit import is different then the value used by the bottom implicit import.  Since the `MSBuildProjectExtensionsPath` contains imports generated by NuGet, this behavior can cause some obscure build errors.  
This change stores the value used by `Microsoft.Common.props` and logs an error if it changed later on.  
1. The error message is not localized, should I make this a task?  Or log it as an error in the evaluator?
> Log an error if MSBuildProjectExtensionsPath is modified after it is used

- scripts/EnumerateMSBuild.ps1
If the file didn't exist Get-ChildItem (what was using to expand the
full path) fail and logFile would be null. Moving that to the end.
> Expand logFile at the end of the script

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/GetReferencePaths_Tests.cs
- src/Tasks/GetReferenceAssemblyPaths.cs
This should allow the .NET SDK to check if a given targeting pack is installed, and if not, fall back to referencing a NuGet package with the reference assemblies.
The full proposal is here: https://github.com/dotnet/designs/pull/33
> Add property to suppress error from GetReferenceAssemblyPaths when the path can't be found

- build/SignToolData.json
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build.UnitTests/EvaluationProfiler_Tests.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Build/Microsoft.Build.csproj
- src/Directory.BeforeCommon.targets
- src/Directory.Build.targets
- src/Shared/NodeEndpointOutOfProcBase.cs
- src/Shared/UnitTests/TestAssemblyInfo.cs
- src/Shared/UnitTests/TestEnvironment.cs
Enable node reuse for .NET Core (runtime 2.1+).
Interesting features:
* Attempts to connect to _every_ `dotnet` process, with no attempt to find only ones that are running MSBuild.
* There's an absolute length limit on the named pipe path of 108 chars on Linux. Tests setting custom temp dirs in deep paths ran afoul of this, so I changed the temp-path allocation strategy, which also required test-infrastructure changes that Mihai helped me figure out.
* I'm using the new `PipeOptions.CurrentUserOnly` as the only security mechanism on 2.1 and not running the old Windows-only validation code even on Windows.
* Long-lived worker nodes exposed #3091, which also manifested as a test hang. I fixed this in two ways:
* Avoid `/nodereuse:true` in tests by explicitly setting it to `false` …
> .NET Core node reuse redux

- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
- src/Build/BackEnd/Node/OutOfProcNode.cs
- src/MSBuild/OutOfProcTaskHostNode.cs
Full-framework MSBuild was resetting the current directory at the end of build requests and at node idle, which helps avoid holding handles to project directories that the user may wish to delete while a worker node is still alive in the background. That wasn't done on .NET Core because at the time of the original port, there wasn't an `Environment.SystemDirectory` to use.
That property is now available, but returns the empty string on Linux, which fails `Directory.SetCurrentDirectory()`. So I'm avoiding it by using the current MSBuild tools directory, which should exist as long as the MSBuild process keeps running.
Fixes #2977.
> Reset current directory on Core

- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/Microsoft.Build.csproj
It's harder for projects to depend on us if we're netcoreapp2.0, because
they must themselves be .NET Core specific rather than netstandard.
We only need to be netcoreapp2.1, though--in 2.0 mode we can be
netstandard.
> Microsoft.Build: netstandard2.0 instead of netcoreapp2.0

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Shared/Traits.cs
The VSTest runner emits log messages to its stdout. So far, in .NET
Core, that has resulted in them getting piped all the way up through
the worker MSBuild that launched the task, the entry-point MSBuild
coordinating the build, and the `dotnet test` invocation that started
it all.
The introduction of node reuse for .NET Core makes this untenable:
worker nodes should not share stdout with the process that happened to
launch them, because they will be long-lived and may do entirely
unrelated builds.
But for now, this breaks the `dotnet test` scenario. This commit creates
an escape hatch environment variable
`MSBUILDENSURESTDOUTFORTASKPROCESSES` that can be used in combination
with `/nodereuse:false` to create a cone of MSBuild processes that all
share std handles.
Enables workaround for …
> Escape hatch: share stdout with node children

- src/Directory.BeforeCommon.targets
This is much closer to our insertion point than the VS master branch, so it has many fewer "I don't know how to correlate this old trace with these new codepaths" problems.
It looks very good. Starred is a build from the experimental branch here, everything else is current builds of d15.7stg:
> Get PGO data from the vs15.7 release branch

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
`CreateProcess()` takes an argument that is the program to execute and
another argument that's the entire command line, including the program.
MSBuild parses the full command line to read its arguments.
The combination of these behaviors caused problems when creating MSBuild
worker nodes on Windows via CreateProcess if the path to MSBuild.dll
contains a space. The process gets created fine (the space in
`lpApplicationName` doesn't cause a problem) but the command line is
split in a confusing way, because we think, say, `C:\Program` and
`Files\dotnet\dotnet.exe` are separate arguments.
To avoid this, quote `exeName` when adding it to the command line, just
as we quoted `msbuildLocation`.
Fixes #3142.
> Quote path to MSBuild when using CreateProcess

- src/Shared/BuildEnvironmentHelper.cs
TryFromVisualStudioProcess only looks for Windows specific paths. It seems to incur a 1.77s penalty, mostly in Process.GetModules inside Mono.
Thus skip this probe path on Mono.
> [Mono] Optimize MSBuild environment initialization

- src/Build.UnitTests/Construction/ElementLocation_Tests.cs
- src/Build.UnitTests/Construction/ProjectRootElement_Tests.cs
- src/Build/ElementLocation/XmlDocumentWithLocation.cs
- src/Build/Xml/XmlReaderExtension.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
XmlDocumentWithLocation class has the ability to openXML documents in the read-only mode (comments and whitespace is replaced with an empty string). Currently this functionaly is not available, because the XML file location is not passed to the XML reader constructor and thus not available for the XmlDocumentWithLocation for further verification.
Additionally, the IsReadOnly property is now overriden, to correctly inform callers about the read mode of the document.
Added unit tests that cover these scenarios.
> Fix XmlDocument reader to allow opening files in read-only mode

- src/Tasks.UnitTests/GenerateBindingRedirects_Tests.cs
- src/Tasks/AssemblyDependency/GenerateBindingRedirects.cs
We compare what we're going to write to what is already there if
present. If the contents are already there, then don't bother.
Note: This is rather naive, as any difference will cause the file to be
written. For example if, for some reason, the order of the binding
redirects changes.
This fixes #3008
> Only write the generated app.config if needed

- src/MSBuildTaskHost/MSBuildTaskHost.csproj
- src/MSBuildTaskHost/OutOfProcTaskHost.cs
- src/Shared/BuildEnvironmentHelper.cs
- version.json
* Extend MSBUILDDEBUGONSTART support for TaskHost
* 32BITREQ for MSBuildTaskHost
* Find MSBuild environment in TaskHost
This hasn't worked since the build upgrade :(
TODO:
> Fix MSBuildTaskHost

- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/MSBuild/XMake.cs
- src/Shared/CommunicationsUtilities.cs
There were two problems leading to #3161. I reverted the only-on-Windows mitigation for that and fixed the problems.
First, dotnet/corefx#28791 means that the named pipe connection behavior we'd been relying on on Windows didn't work on UNIXy platforms, because the pipe could be connected and it would just go nowhere. I fixed that by wrapping a timeout around the wait-for-handshake-reply code to give up if it isn't speedy.
Then, tests (in other repos) that ran `MSBuild /m /nr:true` (by default) were hanging for a very long time, because they were waiting for any newly-spawned worker nodes to hit their idle timeout. See 
the commit message of e604f5f for details.
> Avoid hangs with node reuse on non-Windows

- build/Toolset.proj
- build/Versions.props
- build/build.sh
- src/MSBuild/MSBuild.csproj
- Update build script to not kill on source-build
- source-build restore sources for Toolset proj
- source-build restore sources and repotools version update
Contains the patches from dotnet/source-build#410
This commit will also get cherry picked in 15.7
> Sourcebuild support

- build/SignToolData.json
- build/Versions.props
- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Directory.BeforeCommon.targets
- src/Directory.Build.props
- src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
- src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
- src/MSBuild/XMake.cs
- src/MSBuildTaskHost/MSBuildTaskHost.csproj
- src/MSBuildTaskHost/OutOfProcTaskHost.cs
- src/NuGetSdkResolver/NuGet.MSBuildSdkResolver.csproj
- src/Shared/BuildEnvironmentHelper.cs
- src/Shared/CommunicationsUtilities.cs
- src/Shared/UnitTests/FileUtilities_Tests.cs
- src/Tasks.UnitTests/Copy_Tests.cs
- src/Tasks.UnitTests/Exec_Tests.cs
- src/Tasks.UnitTests/FileStateTests.cs
- src/Tasks.UnitTests/FindUnderPath_Tests.cs
- src/Tasks.UnitTests/GenerateResource_Tests.cs
- src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
- version.json
This builds on https://github.com/Microsoft/msbuild/pull/3185 and additionally restructures dependencies so that prodcon can ensure a coherent version of everything.
That required:
* Nothing for net46 (irrelevant to prodcon)
* Nothing for netstandard2.0/netcoreapp2.0 (depends on released bits, no coherency needed)
* Separating the 2.1 toolset we use to build from the 2.1 packages we reference for netcoreapp2.1.
* Specifying dependencies for things that get overridden with the right naming convention
* Since we use repo-toolset, this is _not_ the normal prodcon convention
> Prodcon dependency uptake

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Shared/CommunicationsUtilities.cs
- src/Shared/NodeEndpointOutOfProcBase.cs
The old version of this code didn't have a timeout when reading the
handshake packet, and appeared to be reliable. The timeout was required
to work around a cross-platform design limitation: the pipe always
connects on *nix systems, even when nothing is listening to it.
This caused failures on Windows (#3214), because the timeout was
exceeded there. For maximum robustness, avoid the timeout entirely on
Windows.
> Avoid handshake timeout on Windows

- src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
- src/Shared/Modifiers.cs
I found a problem with slashes in metadata evaluation. I created repro test for this problem. But I'm not sure where I should fix it. Please help me find the right place.
> Add test for reproduce Filename metadata problem on Unix.

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Project System telemetry indicates a significant number of failures that
report
```
The expression "[System.IO.Path]::Combine(D:\Temp\, .NETFramework,Version=v4.5,Profile=
.AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
```
This seems to be because the XML entity for a carriage return gets
embedded in the file. We don't currently know what would cause that.
This is a tactical fix: instead of comparing against '', explicitly
use `String.IsNullOrWhitespace` which knows about all kinds of
whitespace, even bare \r.
Closes #3197.
> Avoid error when TargetFrameworkProfile is \r

- src/Tasks/Microsoft.NETFramework.CurrentVersion.props
The check that turned this on for "new enough" runtimes predated .NET
Standard and .NET Core, but anything that targets them is by definition
new enough to have it by default, since .NET Core is new and .NET
Standard 1.0 is .NET 4.5.
Fixes #2912.
> HighEntropyVA by default for .NET Standard/Core

- src/Build.UnitTests/Definition/Project_Internal_Tests.cs
- src/Build.UnitTests/Instance/ProjectInstance_Internal_Tests.cs
- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
- src/Build/Definition/Project.cs
- src/Build/Definition/ProjectCollection.cs
- src/Build/Instance/ProjectInstance.cs
- src/Build/Utilities/Utilities.cs
A log message is generated when the toolsversion specified in the project differs from the one msbuild chooses. Now that toolsversion is not required anymore, suppress this message when there is no explicit toolsversion reference in the project file.
> No toolsversion message when one is not mentioned in the project

- src/Tasks/Microsoft.Common.CurrentVersion.targets
GetReferenceAssemblyPaths references
`@(_CombinedTargetFrameworkDirectoriesItem)` and other properties/items
that get defined (for .NET projects) in `GetFrameworkPaths`, but did
not depend on it. Dependencies were enforced by listing
GetFrameworkPaths first whenever dependencies existed, but that is hard
to enforce, and when missed caused dotnet/sdk#1730.
I'm adding this explicitly rather than appending to the already-existent
but undefined `$(GetReferenceAssemblyPathsDependsOn)` because a GitHub
search found a few projects (mostly Mono-related) that _override_ rather
than append to GetReferenceAssemblyPathsDependsOn. That was safe because
no released MSBuild ever defined anything in that property, but could
introduce problems if we started defining it.
Fixes #3196.
> GetReferenceAssemblyPaths needs GetFrameworkPaths

- src/Tasks.UnitTests/Exec_Tests.cs
It is working around a difference in behavior in .netcore/HighSierra,
but isn't required for Mono.
> [mono][test] Fix Exec timeout test

- src/Directory.Build.props
Prepping this in case we need it.
This dependency should not leak into our NuGet packages. This was added as the result of a bug (see https://github.com/dotnet/sdk/issues/2204) and causes issues like the ones listed in #3228.
> Remove package dependency on Microsoft.NETCore.App (vs15.7)

- src/Build/Evaluation/Conditionals/AndExpressionNode.cs
- src/Build/Evaluation/Conditionals/EqualExpressionNode.cs
- src/Build/Evaluation/Conditionals/GenericExpressionNode.cs
- src/Build/Evaluation/Conditionals/GreaterThanExpressionNode.cs
- src/Build/Evaluation/Conditionals/GreaterThanOrEqualExpressionNode.cs
- src/Build/Evaluation/Conditionals/LessThanExpressionNode.cs
- src/Build/Evaluation/Conditionals/LessThanOrEqualExpressionNode.cs
- src/Build/Evaluation/Conditionals/NotEqualExpressionNode.cs
- src/Build/Evaluation/Conditionals/NotExpressionNode.cs
- src/Build/Evaluation/Conditionals/NumericExpressionNode.cs
- src/Build/Evaluation/Conditionals/OperatorExpressionNode.cs
- src/Build/Evaluation/Conditionals/OrExpressionNode.cs
- src/Build/Evaluation/Conditionals/StringExpressionNode.cs
When trying to explain how the parser worked for dotnet/project-system#3510 I was annoyed at what it took to step through and understand the parse.
With this change, the debugger now shows pretty values.
> DebuggerDisplay parsed conditional expressions

- src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
- src/Build/Logging/BinaryLogger/BinaryLogger.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
The lack of this meant that some operations done by a logger (like figuring out why a project was built multiple times) weren't possible with only the binary log, but worked fine directly attached to a real build.
> Preserve ProjectStarted GlobalProperties in binary log

- build/Versions.props
- src/Directory.BeforeCommon.targets
- src/Directory.Build.props
- src/Directory.Build.targets
Removes the machinery required to fix the version of our `Microsoft.NETCore.App` dependency and returns to the implicit reference.
Works around dotnet/sdk#2204 by updating the implicit reference with `PrivateAssets="All"`.
> Avoid netcoreapp package dependency

- build/BootStrapMSBuild.targets
- build/build.sh
- netci.groovy
- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
- src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
- src/Build.UnitTests/Utilities_Tests.cs
- src/Build/Definition/ToolsetReader.cs
- src/Build/Microsoft.Build.csproj
- src/Directory.Build.props
- src/Directory.Build.targets
- src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
- src/MSBuild/MSBuild.csproj
- src/MSBuild/XMake.cs
- src/MSBuildTaskHost/MSBuildTaskHost.csproj
- src/Package/Localization/Localization.csproj
- src/Shared/UnitTests/FileMatcher_Tests.cs
- src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
To build for mono:
`$ ./build.sh -host mono`
This will download a bootstrap msbuild/mono and use the system (in $PATH) mono to build.
You can use `-useSystemMSBuild` argument to skip the bootstrap msbuild/mono and just
use the system msbuild.
> Add support for building on and targeting Mono

- netci.groovy
We're intentionally skipping tests for these Mono jobs (for now) but then CI was failing anyway:
```
Build succeeded.
0 Warning(s)
0 Error(s)
Time Elapsed 00:05:01.68
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing xUnit.Net-v2 (default)
[xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern 'artifacts/**/TestResults/*.xml' relative to '/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_Mono_prtest' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'artifacts/**/TestResults/*.xml'. Configuration …
```
> Allow skipped tests for Mono CI jobs

- build/build.sh
For source-build 2.1 RC this was a patch for msbuild to enable source-build to supply the version of repotoolset that was source-built.  This moves the changes into msbuild so the patch can be removed.
cc @cdmihai
> Initialize repotoolset so source-build can supply a built version.

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #3069.
There are a number of places where we need to get the set of items produced by a project's references and needed for packaging purposes or just running the code on the target platform. These may well be different from the reference passed to the compiler (e.g., a NuGet package may have a single `ref` assembly for compiling but multiple `lib` assemblies for different runtimes) and may not be code at all (e.g. PDBs or resource assemblies). As noted in #3069 a number of individual project types have implemented their own targets to collect this information, with varying levels of correctness.
This change adds a new `ReferenceCopyLocalPathsOutputGroup` to Microsoft.Common.CurrentVersion.targets to make this functionality centrally available to anyone who needs it. It also does …
> Add a ReferenceCopyLocalOutputGroup

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/ExcludeAPIList.txt
This property is public, but only exists in debug builds, which are
never "official" builds (not distributed in NuGet packages or in VS).
This also caused a builds run with `-configuration Release` to edit the
API files, removing WaitForDebugger.
Remove it from the API permananently and tell GenAPI to stop adding it.
> Remove WaitForDebugger from our "public" API

- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
- src/Shared/AwaitExtensions.cs
RequestBuilder queues tasks with `TaskCreationOptions.LongRunning` which means their threads don't interfere with the threadpool. However it also means a new thread is created for every task and it is unbounded.
This means a Nuget restore of Rosyln creates 3274 short-lived Request Builder threads
This change introduces a TaskScheduler which caps the number of created threads (at processor count); and reuses them when they have stopped doing work rather than creating a new thread.
This means the same Nuget restore creates only 3 threads (on an 8 core machine, so upper bound 8)
I *believe* this change is safe as there is also a STA TaskScheduler which only allows one thread; so on the assumption that works; this should also work.
/cc @stephentoub
> Reuse RequestBuilder threads

- src/Build/Construction/Solution/ProjectInSolution.cs
We started (transitively) requiring
System.Runtime.InteropServices.RuntimeInformation when using
`SolutionFile.Parse` after #2963. The assembly-level dependency is
longstanding. But since it wasn't needed in NuGet's calling pattern,
many versions of NuGet are broken on older (pre-4.7.1) .NET Frameworks.
Work around the assembly load by avoiding the adjustment filepath on
full-Framework MSBuild (where it's not necessary anyway).
Closes #3282.
> Avoid RuntimeInformation on full sln parse

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
- src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs
- src/Build.UnitTests/Evaluation/ProjectSdkImplicitImport_Tests.cs
- src/Build.UnitTests/InternalEngineHelpers.cs
- src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/ISdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverCachingWrapper.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResult.cs
- src/Build/Construction/ProjectImportElement.cs
- src/Build/Construction/ProjectRootElement.cs
- src/Build/Definition/Project.cs
- src/Build/Definition/ResolvedImport.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Evaluation/IEvaluatorData.cs
- src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs
- src/Build/Instance/ProjectInstance.cs
- src/Framework/Sdk/SdkResult.cs
- `ProjectImportElement.OriginalElement` points to the original `ProjectElement` which generated implicit imports (`ProjectRootElement` or `ProjectSdkElement`).
- `ResolvedImport.SdkResult` points to sdk resolution results.
`Project.Imports.Where(i -> i.SdkResult != null)` retrieves all `ResolvedImports` that came from sdks, with pointers to the `SdkResult` and the import element. This should allow VS to display the sdks a Project imports, and to navigate to the real elements which generated those imports.
Closes #3203
> Expose sdk resolution in Project

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/BackEnd/BuildManager/BuildRequestData.cs
- src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
- src/Build/Instance/ProjectInstance.cs
- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/XMake.cs
Some shipped SDKs have imports that are property based but are missing conditions.  This makes it impossible to retrofit them with a NuGet package since NuGet restore won't succeed because an import is missing.  This change makes it so that during Restore, projects are loaded with the ProjectLoadSettings that ignore missing, empty, and invalid imports.  This is what Visual Studio uses so that it can load projects that haven't been restored yet.  The build would still fail if there are missing imports.
Treat `/Target:Restore` the same as `/Restore` without a build
> Ignore missing imports during restore

- src/Tasks/ResolveProjectBase.cs
Explicitly opts synthetic project references injected by solution
dependencies out of the TargetFramework-compatibility/find-best-match
dance instituted in 15.x for .NET Standard support.
Fixes #1915 and the most common cause of #2661.
Note: I proposed this in https://github.com/Microsoft/msbuild/pull/2867, but we decided not to take it, as it seemed redundant with the change to ignore TF compat when `ReferenceOutputAssembly=false`. But that had to be rolled back, because several repos depended on TF checks in that case. This is more scoped: it affects only solution build order dependencies. Hopefully that means that it only unblocks people and doesn't create new breaks.
> Skip tf-compat checks for solution dependencies

- build/build.ps1
I'm not sure if this should go against master.
The windows build script was missing the DotNetBuildFromSource and DotNetCoreSdkDir parameters in order to build msbuild on source-build as we do for non-Windows.
cc: @rainersigwald @weshaggard
> Add source build switches in order to be able to build source-build on windows

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/MSBuild/Microsoft.Build.CommonTypes.xsd
- src/Shared/UnitTests/TestEnvironment.cs
- src/Tasks.UnitTests/Unzip_Tests.cs
- src/Tasks.UnitTests/ZipDirectory_Tests.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Microsoft.Common.tasks
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
- src/Tasks/Unzip.cs
- src/Tasks/ZipDirectory.cs
`ZipDirectory` task zips up a whole directory.  It will fail if the destination file already exists.  Zipping individual files is a lot harder because you have to calculated a base path for all files and make zip entries relative to that.  The code in the CLR that does this is very efficient by reusing string buffers and I didn't want to have to replicate the code.  So for now there's only `ZipDirectory` instead of a more generic `Zip`.
`Unzip` unzips files from an archive to a directory.
* Defaults to skip unzipping files that are already up-to-date
* Logs every file that was unzipped
* Supports cancellation
* Supports overwriting read-only files
* Supports unzipping multiple files to the same directory
Fixes #1781
> Add ZipDirectory and Unzip tasks

- build/build.sh
.. signed nugets. Without this the CI builds failed with:
```
/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_MonoTest_prtest/artifacts/mono-msbuild/NuGet.targets(104,5): error : Value cannot be null. [/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_MonoTest_prtest/src/Build/Microsoft.Build.csproj]
/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_MonoTest_prtest/artifacts/mono-msbuild/NuGet.targets(104,5): error : Parameter name: keyValue [/Users/dotnet-bot/j/w/Microsoft_msbuild/master/innerloop_OSX10.13_MonoTest_prtest/src/Build/Microsoft.Build.csproj]
```
> [mono] Update bootstrap msbuild/mono used to get the fix for handling

- src/Build/Microsoft.Build.csproj
This is now included by default in Microsoft.NETCore.App, so it
doesn't need to be referenced explicitly.
> Drop explicit System.IO.Pipes.AccessControl ref

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/ResolveComReference_Tests.cs
- src/Tasks/Dependencies.cs
- src/Tasks/RCWForCurrentContext.cs
- src/Tasks/RedistList.cs
- src/Tasks/RegisterAssembly.cs
- src/Tasks/RemoveDir.cs
- src/Tasks/RequiresFramework35SP1Assembly.cs
- src/Tasks/ResGen.cs
- src/Tasks/ResGenDependencies.cs
- src/Tasks/ResolveCodeAnalysisRuleSet.cs
- src/Tasks/ResolveComReference.cs
- src/Tasks/ResolveComReferenceCache.cs
- src/Tasks/ResolveKeySource.cs
- src/Tasks/ResolveManifestFiles.cs
- src/Tasks/ResolveNativeReference.cs
- src/Tasks/ResolveNonMSBuildProjectOutput.cs
- src/Tasks/ResolveProjectBase.cs
- src/Tasks/ResolveSDKReference.cs
- src/Tasks/XslTransformation.cs
For #3320
- ReSharper, nameof()
- Converted some .NET 1.1 data structures to generics to avoid up and down casts
- Sized some allocations
> Code cleanup in Tasks\R*.cs

- src/Shared/Traits.cs
- src/Shared/UnitTests/MockEngine.cs
- src/Shared/UnitTests/MockLogger.cs
- src/Tasks.UnitTests/Copy_Tests.cs
- src/Tasks/Copy.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Utilities.UnitTests/Logger_Tests.cs
- src/Utilities/Logger.cs
For #3330 
- Kept original single-thread copy task for single-thread operation and added new TPL ActionBlock based parallel implementation.
- All UTs pass with old and new implementations
- See empirical time comparison numbers in table in Copy.cs. ~2X faster for SSD and ~3x for spinny disk.
> Speed up Copy task by 2-3X

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes a case where RAR was called early in the build before project
references were resolved. As far as I know this only happened in
design-time builds, but this makes the dependency explicit (if
ResolveProjectReferences has not run all project dependencies will not
be correctly resolved in RAR).
Fixes #2591
> Ensure ResolveProjectReferences runs before RAR

- src/Tasks/AssemblyFolder.cs
.. as assembly search folders mapped to registry keys. This breaks
projects like Xamarin.Android/iOS as sometimes common assemblies like
System.dll get incorrectly resolved to regular .net assemblies rather
than being resolved to the custom built assemblies for that particular
target framework.
This is incorrect anyway, since it adds unexpected sources for resolving
assemblies and breaks expectations.
> AssemblyFolder: Don't add all directories under framework base path ..

- src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
.. since they contain relative paths with windows style path separators
and that breaks on non-windows platforms.
```
/Users/foo/.nuget/packages/roslyntools.repotoolset/1.0.0-beta2-62901-01/tools/Tools.proj : error MSB4247: Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. Manifest file path '/Users/foo/dev/msbuild/artifacts/Debug-MONO/bootstrap/net461/MSBuild/15.0/Bin/SdkResolvers/Microsoft.Build.NuGetSdkResolver/Microsoft.Build.NuGetSdkResolver.xml'. SDK resolver path: /Users/foo/dev/msbuild/artifacts/Debug-MONO/bootstrap/net461/MSBuild/15.0/Bin/SdkResolvers/Microsoft.Build.NuGetSdkResolver/..\..\Microsoft.Build.NuGetSdkResolver.dll
```
> Fix paths for sdk resolver assemblies constructed from manifest files.

- src/Shared/AssemblyNameExtension.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
If RAR find a dependency without PE metadata an
InvalidOperationException is thrown. Detect this case and implement the
Full Framework behavior (BadImageFormatException) expected by RAR.
Fixes #3386
> Fix 'PE image does not have metadata' exception

- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
xunit logs `[FAIL]` for errors, so searching in our test `.log` files is made harder by these messages.
> Do not use `[fail]` in tests

- src/Build/Construction/ProjectItemElement.cs
- src/Build/Construction/ProjectMetadataElement.cs
- src/Build/Construction/ProjectPropertyElement.cs
- src/Build/Construction/ProjectTargetElement.cs
- src/Build/Definition/ProjectItem.cs
- src/Build/Definition/ProjectItemDefinition.cs
- src/Build/Definition/ProjectProperty.cs
- src/Build/Evaluation/ProjectParser.cs
- src/Build/Instance/ProjectInstance.cs
- src/Build/Instance/ProjectItemInstance.cs
- src/Build/Instance/ProjectMetadataInstance.cs
- src/Build/Instance/ProjectPropertyInstance.cs
- src/Build/Resources/Constants.cs
- src/Build/Utilities/Utilities.cs
- src/Build/Xml/ProjectXmlUtilities.cs
- src/Shared/EscapingUtilities.cs
- src/Shared/XMakeAttributes.cs
- src/Shared/XMakeElements.cs
* Use HashSet<string> instead of string[]
* Remove small single use methods
* Add ReservedItemNames
> Optimize and clean up ProjectParser

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
- ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
- src/Tasks.UnitTests/GetReferencePaths_Tests.cs
- src/Tasks/GetReferenceAssemblyPaths.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
- src/Utilities/ToolLocationHelper.cs
When running on Mono, target frameworks are searched for in
$mono_prefix/lib/mono/xbuild-frameworks, which becomes
/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks.
This works, but has a problem when upgrading the Mono.framework package:
a new /Library/Frameworks/Mono.framework/Versions/@VERSION@ directory
is created, so anything installed into the previous directory will be
"lost" (For example, installed by Xamarin.Android). The file is still there, but msbuild
will no longer find it.
To address this upgrade scenario, we can add a fallback path:
`/Library/Frameworks/Mono.framework/External/xbuild-frameworks`
This location is not within a versioned framework directory, and thus files
installed into it will survive Mono.framework package upgrades. …
> Add support for fallback search paths for Target frameworks

- src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
For the mono build we have a dependency on
`Microsoft.Extensions.DependencyModel`, and so we get the assembly in
the binDir.
When building a netstandard project, the MSBuild sdk resolver resolves
to the installed dotnet (2.1 RC in this case).
`Microsoft.NET.Build.Tasks` is loaded from there but it's dependency is
available in msbuild's(entry assembly) binDir itself, so it gets loaded
from there.  And because the one from dotnet has a new
class `Microsoft.Extensions.DependencyModel.RuntimeFile`,
this fails at runtime with:
`System.TypeLoadException: Could not resolve type with token 01000030 from typeref (expected class 'Microsoft.Extensions.DependencyModel.RuntimeFile' in assembly 'Microsoft.Extensions.DependencyModel, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')` …
> [mono] Fix VSMac build with .netcore 2.1 installed (#61)

- src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactoryCompilers.cs
When using RoslynCodeTaskFactory with the dotnet host and csc.dll, the order in which the command line is constructed means /nostdlib+ is appended before the path to csc.dll. This causes the executed command to look like 
```
C:\Program Files\dotnet\dotnet.exe /nostdlib+ "C:\Program Files\dotnet\sdk\2.2.100-preview1-009013\Roslyn\bincore\csc.dll" /noconfig ...
```
This fails, as dotnet.exe tries to execute a program call 'dotnet-/nostdlib+' rather that csc.dll
This fix flips the order in which the base.AddCommandLineCommands is called, ensuring the dll is passed as the first argument, and /nostdlib+ is appended to end of the arguments instead.
The same fix is applied for the VB version.
> Flip base call order in RoslynCodeTaskFactoryCompilers

- .gitattributes
- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Shared/ConversionUtilities.cs
- src/Tasks.UnitTests/GetFileHash_Tests.cs
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
- src/Tasks.UnitTests/TestResources/TestBinary.cs
- src/Tasks.UnitTests/TestResources/lorem.bin
- src/Tasks.UnitTests/VerifyFileHash_Tests.cs
- src/Tasks/FileIO/GetFileHash.cs
- src/Tasks/FileIO/HashEncoding.cs
- src/Tasks/FileIO/VerifyFileHash.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Microsoft.Common.tasks
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Add tasks for computing the file hash and verifying an expected file hash using SHA256, SHA384, or SHA512. These tasks were originally part of aspnet/buildtools, then moved to dotnet/arcade. I've polished them up and added better tests/logging. I'm not set on the API names so let me know if there is a better MSBuild convention for the task and property names.
Resolves https://github.com/Microsoft/msbuild/issues/3369
cc @jeffkl
> Add GetFileHash and VerifyFileHash tasks

- src/Directory.Build.props
- src/Tasks/Microsoft.Build.Tasks.csproj
dotnet/sdk enabled net46 builds in source-build, which requires repos that sdk depends on to also bring back net46 builds.  This change enables the net46 builds and adds the TargetingPack reference to make the build work.  See also: https://github.com/dotnet/source-build/issues/592, https://github.com/dotnet/sdk/pull/2309, https://github.com/dotnet/source-build/pull/588.
> Add TargetingPack and enable net46 builds for source-build.

- src/Framework/BuildEventArgs.cs
- src/Framework/ProjectStartedEventArgs.cs
Use our singleton `BuildEventContext.Invalid` instead.
> Avoid allocations when deserializing build event args

- src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
Remove the workaround done for #2069 now that immutable collections got updated in #3376.
> Remove workaround for bug in immutable collections

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes Clickonce part in issue #3069.
> use ReferenceCopyLocalPaths to resolve _DeploymentReferencePaths

- src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
Reverts the portion of #3390 which changed `eulaAttribute.Value` to `eulaAttribute.ToString()`.
> Revert incorrect ToString() on XAttribute usage

- src/Tasks.UnitTests/SGen_Tests.cs
- src/Tasks/SGen.cs
shorten sgen reference parameter line to avoid too long string on GenerateSerializationAssemblies
> shorten sgen reference parameter line

- src/Build.OM.UnitTests/Construction/WhiteSpacePreservation_Tests.cs
- src/Build.UnitTests/BackEnd/Scheduler_Tests.cs
- src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
- src/Build.UnitTests/EscapingInProjects_Tests.cs
- src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs
- src/Build.UnitTests/Instance/HostServices_Tests.cs
- src/Build.UnitTests/Instance/TaskItem_Tests.cs
- src/Build/Xml/XmlReaderExtension.cs
- src/Directory.BeforeCommon.targets
This API wasn't in .NET Core when we originally ported but is now available in
all of our .NET Core targets. Using it everywhere improves programmatic editing
of MSBuild files.
Closes #1401.
> Use XmlTextReader everywhere

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
- src/Build/Definition/Project.cs
- src/Build/Definition/ProjectOptions.cs
- src/Build/Evaluation/Context/EvaluationContext.cs
- src/Shared/FileSystem/CachingFileSystemWrapper.cs
- src/Shared/FileSystem/IFileSystem.cs
- src/Shared/FileSystem/MSBuildOnWindowsFileSystem.cs
- src/Shared/FileSystem/ManagedFileSystem.cs
- src/Shared/FileSystem/WindowsFileSystem.cs
- src/Shared/UnitTests/FileMatcher_Tests.cs
This greatly simplifies things. The only way users should "reset" caches by sending in a different / new context. Turned out it's quite hard to reset caches atomically and in a readers / writers fashion with respect to ongoing evaluations because the context does not keep a record of which evaluations use it.
> Project does not remember last context and caches cannot be reset

- build/Versions.props
- src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
- src/Build/Microsoft.Build.csproj
- src/Directory.BeforeCommon.targets
- src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
- src/MSBuild/MSBuild.csproj
- src/MSBuildTaskHost/MSBuildTaskHost.csproj
- src/Shared/FileUtilities.cs
- src/Shared/NativeMethodsShared.cs
- src/Shared/Resources/Strings.shared.resx
- src/Shared/Resources/xlf/Strings.shared.cs.xlf
- src/Shared/Resources/xlf/Strings.shared.de.xlf
- src/Shared/Resources/xlf/Strings.shared.en.xlf
- src/Shared/Resources/xlf/Strings.shared.es.xlf
- src/Shared/Resources/xlf/Strings.shared.fr.xlf
- src/Shared/Resources/xlf/Strings.shared.it.xlf
- src/Shared/Resources/xlf/Strings.shared.ja.xlf
- src/Shared/Resources/xlf/Strings.shared.ko.xlf
- src/Shared/Resources/xlf/Strings.shared.pl.xlf
- src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
- src/Shared/Resources/xlf/Strings.shared.ru.xlf
- src/Shared/Resources/xlf/Strings.shared.tr.xlf
- src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
- src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/UnitTests.Shared/Microsoft.Build.UnitTests.Shared.csproj
- src/Utilities/Microsoft.Build.Utilities.csproj
Made the necessary changes to enable builds of long path projects if the OS supports it. A second PR will toggle on the necessary config switches so it's clearer if any regressions occur from turning the functionality on. #53
> Add infastructure for long path support

- src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs
- src/Shared/BuildEnvironmentHelper.cs
If the user points MSBUILD_EXE_PATH to an msbuild inside Visual Studio, then the BuildEnvironment should be configured to the Visual Studio file layout.
> Finding MSBuild via environment variable supports Visual Studio detection

- src/Shared/FileUtilities.cs
Removed unnecessary MAX_PATH assertion before the managed ```Path.GetFullPath()``` call. On net46 ```Path.GetFullPath()``` throws anyways if the path is too long, and on netcore it continues, which is the expected behavior.
> Maintain long path behavior in NormalizePath() on .NET Core

- src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
- src/Build/Utilities/FileSpecMatchTester.cs
- src/Shared/FileMatcher.cs
Out of cone globs do not depend on the project directory, so do not include the project directory in the out of cone glob key. Noticed this while debugging stepping my way through some vcxproj builds.
> Fix cache misses for out of cone globs

- build.cmd
- build/build.ps1
`build -bootstraponly -skiptests` becomes `build`. I do this many many times a day.
`build -bootstraponly` becomes `build -test`
I do the bootstrap build so rarely (once every two months?), that I might as well call the ps script at that point.
> Adjust build.cmd for common dev usage

- src/Tasks.UnitTests/Unzip_Tests.cs
The `root` user has special permission to ignore the read-only bit, and
does so silently and without error. That caused this test to fail,
because we weren't erroring when attempting to overwrite a readonly
file.
Skip the test when running as root.
> Skip overwrite test when root

- src/Directory.BeforeCommon.targets
The publish directory was reused between TFs of the MSBuild.Bootstrap
project, resulting in occasional errors like
```
error MSB3026: Could not copy "/mnt/j/w/Microsoft_msbuild/master/innerloop_Ubuntu16.04_CoreCLR_prtest/artifacts/Debug/bin/MSBuild.Bootstrap/publish/fr/Microsoft.Build.Tasks.Core.resources.dll" to "/mnt/j/w/Microsoft_msbuild/master/innerloop_Ubuntu16.04_CoreCLR_prtest/artifacts/Debug/bootstrap/netcoreapp2.1/MSBuild/fr/Microsoft.Build.Tasks.Core.resources.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/mnt/j/w/Microsoft_msbuild/master/innerloop_Ubuntu16.04_CoreCLR_prtest/artifacts/Debug/bin/MSBuild.Bootstrap/publish/fr/Microsoft.Build.Tasks.Core.resources.dll' because it is being used by another process. …
```
> Avoid bootstrap publish collision

- src/Tasks.UnitTests/GetSDKReference_Tests.cs
- src/Tasks/GetSDKReferenceFiles.cs
This test failed on one of my PRs with the message
```
ERROR MSB3795: There was a problem in the GetSDKReferenceFiles task. Could not find a part of the path 'D:\j\w\innerloop_Win---325d1729\artifacts\Debug\tmp\ewftoebr.ukg\GetSDKReferenceFiles'.
```
That directory _should_ have been created by the test fixture. Added
logging to ensure that it is in the future, and refactored the test
itself to hopefully produce a clearer error.
> PassReferenceWithNoReferenceDirectory diagnosability

- src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs
- src/Build/Evaluation/Expander.cs
- src/Build/Evaluation/LazyItemEvaluator.cs
The lazy item evaluator does some discovery to find the items referenced in the metadata. This causes property expansion to happen on unexpanded metadata which can lead to unexpected exceptions (see referenced issue).
Fixes: #3460
> Ignore errors during lazy evaluation referenced item discovery

- .vsts-dotnet.yml
After #3480 simplified the dev-inner-loop invocation of `build.cmd`, the
official build broke because it passed `-skiptests -bootstraponly`
twice.
I made this change in the non-YAML build which isn't tracked;
making it here in YAML as well.
> Stop passing redundant params in official build

- src/Tasks/GenerateManifestBase.cs
The value is produced via enum string parsing even though it is not used in the MSBuild codebase directly
> Restore private enum value ResourceType.Prerequisite

- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/SolutionProjectGenerator.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/Directory.BeforeCommon.targets
- src/Shared/FrameworkLocationHelper.cs
Found this while debugging tests on #3459 
When generating the metaproject for a web project, if targeting a framework version >= 4.0 and aspnet_compiler.exe 4.0 is not found, ```ToolPath``` is silently set to null and ```ProjectInstance``` will end up failing elsewhere with a ```NullReferenceException```. Not a problem if targeting < 4.0 since the method already used a ```VerifyThrow``` check.
> Fix silent failure when attempting to build web projects outside of .NET Framework

- build/Versions.props
This was causing an issue with the internal build signing our vsix package.
> Specify explicit MicroBuildPluginsSwixBuildVersion

- src/MSBuild/MSBuild.exe.manifest
- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
Should be safe now that we're on Dev16.
> Add long path switches to config

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs
- src/MSBuild/XMake.cs
I was looking at an issue where I issued an incorrect replay command and tried to cancel it, but it didn't work.
So . . . now it works.
I think we could improve some of the existing cancellation logic by plumbing the same CTS down, but I didn't do that here.
> Support ctrl-c cancellation when replaying a binary log

- version.json
Note this does not change the `ToolsVersion` or the file assembly version (what you would use in binding redirects).
> Bump version to 16.0

- src/Utilities/ToolLocationHelper.cs
Fixes #3036.  Modifying the `dotNetFrameworkReferenceAssemblies` collection after publishing it bumps its version and breaks the `foreach` loop in the `GetPathToStandardLibraries` method.
> Fix a race condition in ToolLocationHelper

- src/Build.UnitTests/ConsoleLogger_Tests.cs
A lot of the VSTS PR builds were spuriously failing because VSTS set an environment variable to the contents of the commit message of `HEAD`, which often contained newline characters. That failed several of the are-we-logging-the-environment-correctly tests because the logger emitted `\r\n` newlines, while `Environment.GetEnvironmentVariables()` returned `\n` newlines, and a simple string match didn't.
Fixed that by normalizing newlines in the search string.
While I was in there, reduced `Console.WriteLine` usage in favor of the associated-with-the-test `ITestOutputHelper`.
> Test robustness and diagnosability improvements

- src/Directory.Build.props
Shouldly walks the stack trace and extracts source expressions from the
source file identified in the PDB when an assertion fails to provide
nice, contextual error messages. But that broke when we took a
repo-toolset update that opted all projects into deterministic source
paths.
cc @jeffkl
> Disable deterministic source paths for tests

- Directory.Build.props
- src/Directory.Build.targets
This brings us in line with the [Arcade standard](https://github.com/dotnet/arcade/blob/master/Documentation/Versioning.md#net-core-ecosystem-v2---versioning), while preserving the wildcard-ability of referring to `major.minor.0-prerelease*`.
Produces a package name like `Microsoft.Build.Framework.16.0.0-preview.12.nupkg`.
fyi @natemcmaster
> Semver2 version for NuGet packages

- build/build.ps1
The build (correctly) fails when files have been updated and need to be checked in, but it was kinda hard to figure out exactly what was wrong. This prefixes the diff with VSTS magic that promotes it to build errors.
> Improve VSTS error on updated files

- src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs
I didn't know this existed, but it's a better default than creating a new token.
Followup for #3518.
> Use single-instance CancellationToken.None

- build/build.ps1
- build/build.sh
Because repo-toolset builds using a shell script and not the built-in VSTS MSBuild tasks, it doesn't promote errors to the VSTS log.
This commit does so by creating a text-only error log and printing its contents with the [VSTS logging error command](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md).
> VSTS errors on failures

- netci.groovy
Replaced by VSTS jobs.
Leaves the source build simulation on RHEL7.2 until VSTS gets RHEL images.
> Remove jenkins jobs

- src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Resources/Constants.cs
- src/Shared/UnitTests/EngineTestEnvironment.cs
- src/Tasks.UnitTests/DirectoryBuildProjectImportTestBase.cs
- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
- src/Tasks/Microsoft.Common.CrossTargeting.targets
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/Microsoft.Common.props
- src/Tasks/Microsoft.Common.targets
- src/Tasks/Microsoft.NETFramework.CurrentVersion.props
- src/Tasks/Microsoft.NETFramework.CurrentVersion.targets
- src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
During evaluation, keep track of the last modified project in the import graph.
Prepend the path to the last modified project to `MSBuildAllProjects`
Stop setting `MSBuildAllProjects` in our targets
Add unit tests
Closes #1299
> Prepend the last modified project to MSBuildAllProjects

- Directory.Build.targets
- NuGet.Config
- build/Packages.props
- build/Versions.props
- global.json
- src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
- src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
- src/Build/Microsoft.Build.csproj
- src/Directory.Build.props
- src/Directory.Build.targets
- src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
- src/Framework/Microsoft.Build.Framework.csproj
- src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
- src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
- src/MSBuild/MSBuild.csproj
- src/MSBuildTaskHost/MSBuildTaskHost.csproj
- src/Samples/Directory.Build.props
- src/Samples/Directory.Build.targets
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/UnitTests.Shared/Microsoft.Build.UnitTests.Shared.csproj
- src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
- src/Utilities/Microsoft.Build.Utilities.csproj
- src/Xunit.NetCore.Extensions/Xunit.NetCore.Extensions.csproj
Uses SDK from https://github.com/Microsoft/MSBuildSdks
Versions for `PackageReference` can only be specified in `build/Packages.props` file. If you add a `Version=` attribute to any other `PackageReference` in our tree you get an error that you must specify it in the Packages.props file (it gives the path to it in the error message).
> Use Central Package Versioning SDK

- src/Tasks/AssemblyDependency/AssemblyInformation.cs
While looking at switching all assembly-information extraction over to `System.Reflection.Metadata` (away from desktop-only COM APIs even on desktop), I noticed some extension and simplification I could make in that codepath.
Manually validated that the `AssemblyFiles` extracted via this mechanism match the COM results--the first assembly I found that had any was `C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll`.
While I was in here, I made things more consistent--moving to all loops, no LINQ.
> Get AssemblyFiles in .NET Core

- src/Directory.Build.targets
src\Package\MSBuild.VSSetup\MSBuild.VSSetup.csproj has an assembly name
that matches a shipped assembly, so the IBCMerge targets attempt to
apply PGO data to it, but it does not have any matching methods because
it's not a real project.
Respect the preexisting `$(MicroBuild_EnablePGO)` when deciding whether
to include the IBCMerge targets.
> Stop IBCMerge for VSSetup project

- src/Directory.Build.targets
src\Package\MSBuild.VSSetup\MSBuild.VSSetup.csproj has an assembly name
that matches a shipped assembly, so the IBCMerge targets attempt to
apply PGO data to it, but it does not have any matching methods because
it's not a real project.
Respect the preexisting `$(MicroBuild_EnablePGO)` when deciding whether
to include the IBCMerge targets.
> Stop IBCMerge for VSSetup project (#3611)

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- src/Build.UnitTests/BackEnd/MockSdkResolverService.cs
- src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
- src/Build.UnitTests/InternalEngineHelpers.cs
- src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/HostedSdkResolverServiceBase.cs
- src/Build/BackEnd/Components/SdkResolution/ISdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverContext.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverRequest.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
- src/Build/Evaluation/Evaluator.cs
- src/Framework/Sdk/SdkResolverContext.cs
Defaults to false.  Currently only set to `true` if the global property `NuGetInteractive` is set to "true".
In 16.0, we should add an `/interactive` command-line argument which sets this instead.
> Add Interactive property to SdkResolverContext

- src/Tasks/Microsoft.Build.Tasks.csproj
MSBuild's unit tests depend on a functional MSBuild deployment,
including Roslyn tasks and targets. These weren't getting copied on the
initial build because the NuGet package that contained them (for full
framework) wasn't guaranteed to be restored. Relax the conditions on
the PackageReference that attempted to ensure that.
> Refer to Compilers package unconditionally

- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/Shared/ExceptionHandling.cs
Fix https://github.com/Microsoft/msbuild/issues/1038
When terminating due to a child node crash, we invite the user to look for diagnostic files in %temp%. This is problematic on a CI system, because unless configured especially to understand MSBuild dump files, the user will likely not be able to access them. (Occasionally we encounter this problem in the CoreFX CI for one reason or another.)
* Dump the contents of those dump files to the console, if we are rudely terminating.
* Only do this for files that were written to since the BuildManager was instantiated - so we don't show any stale ones. We could further filter by PID's of our child nodes but wiring this through is messy and does not seem to add anything useful.
* Correct parameter misordering I noticed
I tested this by adding …
> Log debug dumps

- src/Shared/NativeMethodsShared.cs
Somehow we've been getting away with an invalid definition here for 5+ years.
```C
//
// Basic and Extended Basic Process Information
//  NtQueryInformationProcess using ProcessBasicInformation
//
typedef struct _PROCESS_BASIC_INFORMATION {
NTSTATUS ExitStatus;
PPEB PebBaseAddress;
ULONG_PTR AffinityMask;
KPRIORITY BasePriority;
ULONG_PTR UniqueProcessId;
ULONG_PTR InheritedFromUniqueProcessId;
} PROCESS_BASIC_INFORMATION,*PPROCESS_BASIC_INFORMATION;
```
Fixes #3638.
Co-Authored-By: Jeremy Kuhne <jeremy.kuhne@microsoft.com>
> PROCESS_BASIC_INFORMATION struct definition

- src/Tasks/ResolveProjectBase.cs
Fixes #3626
Since the synthetic p2p won't re-negotiate a `TargetFramework` value to set due to the `SkipGetTargetFrameworkProperties` metadata, remove the the global property from moving across the reference by setting it as `GlobalPropertiesToRemove` metadata.
cc @rainersigwald @AndyGerlicher @jeffkl @nguerrera @natemcmaster
> Unset global TargetFramework properties for synthetic project references

- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/Microsoft.Build.csproj
This was disabled for .NET Standard 2.1, because the .NET Standard 2.0
interface was strictly smaller, so it was a better reference target.
But we now generate only .NET Standard 2.1, so it needs to be enabled
again.
> Generate Microsoft.Build reference source

- README.md
The CI account recently moved to dnceng.visualstudio.com rather than
dotnet.visualstudio.com.
I also updated the webhooks in settings so PR builds should be happening again as of a few minutes ago.
fyi @chcosta
> Update VSTS badge URI

- documentation/wiki/Contributing-Code.md
- documentation/wiki/Home.md
Hi! I am new to this repo, and as I was going through the docs I found some links in the paragraphs point to the github wiki pages, where they show another url to the markdown files.
I have updated the following:
`Home.md`
- The links for each platform under `Building Testing and Debugging` from wiki pages to md files
`Contributing-Code.md`
- The link for `.Net Foundation Coding Guidelines` from [wiki page](https://github.com/dotnet/corefx/wiki/Contributing#c-coding-style) to [corefx contribution.md](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md)
- Replace the wording for `[[build|Building Testing and Debugging]]` with `build` which links to [Home.md](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Home.md) (with tooltip to …
> Update reference links in wiki documentation markdown files

- src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
- src/Tasks/SystemState.cs
Split from #3660 
```FileExists()``` calls are cached separately from ```GetLastWriteTime()``` calls even though file existence can be determined from the return value. Within ```ReferenceTable.ComputeClosure()```, this effectively doubles IO on Windows since ```AssemblyInformation.IsWinMDFile()``` results in a duplicate check for last write time on files already checked for existence.
Below are just copypasta perf measurements before splitting from the previous PR, however I should still run this on it's own to get a more accurate measurement of changes.
-------------------------------
Locally goes from master hovering around
```
5221 ms  ResolveAssemblyReferences                129 calls
16113 ms  Build                                    130 calls
```
to
```
4326 ms …
```
> Reduce IO calls in SystemState

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Instance/ProjectInstance.cs
- src/Build/Resources/Constants.cs
- src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/CommandLineSwitches.cs
- src/MSBuild/Resources/Strings.resx
- src/MSBuild/Resources/xlf/Strings.cs.xlf
- src/MSBuild/Resources/xlf/Strings.de.xlf
- src/MSBuild/Resources/xlf/Strings.en.xlf
- src/MSBuild/Resources/xlf/Strings.es.xlf
- src/MSBuild/Resources/xlf/Strings.fr.xlf
- src/MSBuild/Resources/xlf/Strings.it.xlf
- src/MSBuild/Resources/xlf/Strings.ja.xlf
- src/MSBuild/Resources/xlf/Strings.ko.xlf
- src/MSBuild/Resources/xlf/Strings.pl.xlf
- src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
- src/MSBuild/Resources/xlf/Strings.ru.xlf
- src/MSBuild/Resources/xlf/Strings.tr.xlf
- src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
- src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
- src/MSBuild/XMake.cs
Sets built-in property `MSBuildInteractive` and is passed to SDK resolvers
Keeps back compat with existing `NuGetInteractive` global property
> Add /interactive switch

- src/Shared/AssemblyNameExtension.cs
There was a case missed in ac2d03c that caused the S.R.M error to be
worse than the equivalent full-framework error: when
`PEReader.HasMetadata` itself throws because the file is _really_ not
a PE file (for example, it has no content at all).
Related to #3560.
Output from the simple repro there on .net core now:
```
s:\work\zero-byte-ref>dotnet s:\msbuild2\artifacts\Debug\bootstrap\netcoreapp2.1\MSBuild\MSBuild.dll s:\work\zero-byte-ref\zero-byte-ref.csproj /flp:v=diag /v:m
Waiting for debugger to attach (C:\Program Files\dotnet\dotnet.exe PID 18152).  Press enter to continue...
Microsoft (R) Build Engine version 15.9.9-preview+gd05d07205a for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
s:\msbuild2\artifacts\Debug\bootstrap\netcoreapp2.1\MSBuild\Microsoft.Common.Cur …
```
> Throw BadImageFormatException for zero-byte files

- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Fixes #2625
Calling ```ComputeClosure()``` again when both no conflicts and excluded references exist results in an identical output.
> Do not always call ReferenceTable.ComputeClosure() twice (#2625)

- src/Shared/FileUtilities.cs
This avoids race conditions such as #3712, where the field https://github.com/Microsoft/msbuild/blob/0591c15d6c638cad38091fbe625dde968f86748d/src/Shared/FileUtilities.cs#L44 can be set to the same value depending on the current app domain.
> Update FileUtilities to include the current app domain id

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Similar to CopyOutputSymbolsToOutputDirectory, there should be a CopyDocumentationFileToOutputDirectory condition.
> Adding CopyDocumentationFileToOutputDirectory condition

- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/ResolveManifestFiles.cs
With the recent change of using ReferenceCopyLocalPaths for manifest creation there are a few edge cases that broke:
- if there is a native dll referenced as a Content file in a nuget package it was incorrectly assumed it was a managed reference, which could cause build breaks.
- the ClickOnce application files window was not always properly populated.
- files that were set as "Include" in the application files window but had Copy Local set to false were not correctly published
- .NET Core reference libraries were incorrectly published with ClickOnce
This change also introduces an item group "_ExcludedAssembliesFromManifestGeneration" that allows users to manually specify files that should explicitly be excluded from the list of dependencies for the manifest generation, in case there are …
> filter references before manifest generation

- src/Shared/FileMatcher.cs
- src/Shared/UnitTests/FileMatcher_Tests.cs
- src/Utilities/Microsoft.Build.Utilities.csproj
Fixes #2380
Got rid of all ```StringBuilder.Replace()``` calls by just iteratively building the regex without the tagging format and with no allocations. Execution time is so low it just gets absorbed into ```GetFileSpecInfo``` in the profiler, the 7ms that shows up is all from ```SplitFileSpec()```.
Perf profile on master:
Perf profile on this PR:
> Optimize RegularExpressionFromFileSpec (#2380)

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
To adapt assemblies version changes in Dev16. These two assemblies are dropped to msbuild folder when installing VS, so they have the same version with VS.
> Update bindingRedirect versions of Workflow build tasks dlls

- src/Tasks.UnitTests/AssemblyDependency/AssemblyFoldersFromConfig_Tests.cs
- src/Tasks.UnitTests/AssemblyDependency/FilePrimary.cs
- src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs
- src/Tasks.UnitTests/AssemblyDependency/InstalledSDKResolverFixture.cs
- src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
- src/Tasks.UnitTests/AssemblyDependency/NonSpecificVersionStrictPrimary.cs
- src/Tasks.UnitTests/AssemblyDependency/Perf.cs
- src/Tasks.UnitTests/AssemblyDependency/ReferenceTests.cs
- src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
- src/Tasks.UnitTests/AssemblyDependency/SpecificVersionPrimary.cs
- src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependency.cs
- src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependencyAppConfig.cs
- src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependencyAutoUnify.cs
- src/Tasks.UnitTests/AssemblyDependency/VerifyIgnoreVersionForFrameworkReference.cs
- src/Tasks.UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs
- src/Tasks.UnitTests/AssemblyDependency/VerifyTargetFrameworkHigherThanRedist.cs
- src/Tasks.UnitTests/AssemblyDependency/WinMDTests.cs
A little Friday refactoring, in the hopes of setting RAR changes up for clearer failures.
I suggest going a commit at a time. I tried to add `[manual]` to commits that were all manual; those probably deserve more attention.
The biggest changes were inlining a simplified definition for `AssertNoCase` which is mostly just a complexity reduction.
The biggest _win_ with this PR is pulling all the log output into the test helper, so it'll be visible from VSTS/the HTML test log.
> RAR test diagnosability

- src/Shared/CopyOnWriteDictionary.cs
Noticed a decent chunk of time in ```CopyOnWriteDictionary``` is spent just comparing references with the static dummy. Probably negligible perf gain but super easy fix. Right side is with changes. Ran this on top of the ```HybridDictionary``` removal since that was originally dominating all the runtime in here.
>  Use bool to check for dummy CopyOnWriteDictionary

- documentation/specs/static-graph.md
We're replacing export targets with the more generic mechanism of explicit project reference protocols. There were a couple of problems with export targets:
- required the child projects to know about all the possible targets that any parent can call them with.
- some export targets could have bad effects when run together (e.g. Build and Clean)
- inefficient to run all export targets when only a small subset is actually needed
> Update static-graph spec

- src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Build/BackEnd/Node/OutOfProcNode.cs
- src/Directory.BeforeCommon.targets
- src/MSBuild/CommandLineSwitches.cs
- src/MSBuild/NodeEndpointOutOfProcTaskHost.cs
- src/MSBuild/OutOfProcTaskHostNode.cs
- src/MSBuild/XMake.cs
- src/Shared/Compat/PipeSecurity.cs
- src/Shared/NodeEndpointOutOfProcBase.cs
We needed the condition before .NET Core supported duplex named pipes,
but we no longer support runtimes before that, so simplify the code by
committing to it in all cases.
> Unconditionally enable FEATURE_NAMED_PIPES_FULL_DUPLEX

- src/MSBuild/Microsoft.Build.CommonTypes.xsd
AspNetCore is adding a new feature to support inprocess hosting with IIS. We have a few csproj elements that can be specified that we would like to add for intellisense. There doesn't seem to be any extensibility points, so I went ahead and added them to the CommonTypes file.
cc/ @AndyGerlicher @shirhatti
> Add AspNetCore specific properties for csproj intellisense

- src/MSBuild/XMake.cs
- src/Shared/FileUtilities.cs
Just 2 small string allocations, so won't make a big dent, but it bothered me every time I saw it.
> Remove a couple string allocations related to GetExtension

- src/Tasks/GenerateResource.cs
No need to ifdef around these uses since they're in all of our target
frameworks now.
> IResourceWriter/Reader available in .NET Core 2.0+

- src/Build/Definition/ProjectCollection.cs
> Avoid casting Enumerable.Empty to IList

- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/ResolveManifestFiles.cs
PR #3732 introduced some code to filter native assemblies of the collection of managed input assemblies to the ResolveManifestFiles task. There are cases where registration-free COM manifests are included in the input here and those got accidentally filtered out, so we need to ensure that we only filter actual dlls.
Furthermore we identified some edge cases where there were files included in the ClickOnce manifest that had CopyLocal set to false, so we have to ensure to filter those out before we resolve the references.
>  fix publish of COM manifest files and don't publish CopyLocal=false files

- ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
- ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
- src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
- src/Utilities/ToolLocationHelper.cs
VC build needs to be able to use toolsets installed by older VS versions (native multitargeting). Before VS2017 the vc targets locations were written in the registry. To figure out Vs2017 install locations we have to call the installer API.  There also might be several instances on the machine and we need to be able to use a toolset installed in any of the instances.
Here is how the added functions are going to be used in cpp props:
```xml
<_VCTargetPath15Folders>$([Microsoft.Build.Utilities.ToolLocationHelper]::GetFoldersInVSInstallsAsString('15.0', '16.0', 'Common7\IDE\VC\VCTargets'))</_VCTargetPath15Folders>
<_VCTargetsPathForToolset Condition="'$(_VCTargetPath15Folders)' != ''">$([Microsoft.Build.Utilities.ToolLocationHelper]::FindRootFolderWhereAllFilesExist($(_VCTarge …
```
> Adding methods to locate folders and files in VS installs

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
Quick little change to make `BuildEventArgsReader` public as discussed in #3813
> Makes BuildEventArgsReader public

- src/MSBuild/XMake.cs
The code skips a node when no targets are provided. This skipping though needs to set the event to make the loop going again.
Tests will come later.
> Fix graph build hang

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.OM.UnitTests/Construction/ProjectItemDefinitionElement_Tests.cs
- src/Build.OM.UnitTests/Construction/ProjectMetadataElement_Tests.cs
- src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
- src/Build/Construction/ProjectItemDefinitionElement.cs
- src/Build/Evaluation/ProjectParser.cs
Closes #3833 
Allows all metadata that could also be specified as attributes on items to also be specified on item definitions. (inverse: `Update` metadata can't be specified on item definition. It won't parse and with the current API one can't create a metadata element with Name=Update and ExpressedAsAttribute=true)
> Allow spedifying metadata as attributes on item definitions.

- src/Build.UnitTests/Graph/IsolateProjects_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
- src/Build/BackEnd/Components/Scheduler/Scheduler.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/Shared/FileUtilities.cs
- src/Shared/UnitTests/EngineTestEnvironment.cs
- src/Shared/UnitTests/TestEnvironment.cs
Resolves #3686.
Finding the best spot to put the check was a bit interesting. The alternative I thought the most was to put the check in the cache itself, and then have the cache users specify whether they want enforcement or not for each cache lookup. Since performing the lookup and acting upon misses needs a lot of scheduler internal data, I decided to put everything in the Scheduler.
Another issue is how to actually stop the build from the Scheduler. The current solution returns a failed BuildResult to stop the build and then issues a separate error to have something appear to loggers. I can't find a good spot to have the failed build result automagically generate a build error in some of the more normal places (somewhere in ProjectBuilder / TargetBuilder / TaskBuilder so the error …
> Fail the build on target cache misses during isolated project builds

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
- src/Build/Graph/ProjectGraph.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
Note name change from Project to ProjectInstance for previously existing public API. Can restore old name Project and make new addition something like 'UnevaluatedProject' if downstream consumers might be affected.
> Static Graph: Add the ability to hook ProjectInstance creation to allow creation of Projects first

- src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
- src/Shared/FileMatcher.cs
- src/Shared/UnitTests/FileUtilities_Tests.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
Because MSBuild globs preserve the fixed directory from the project file instead of returning fully qualified paths, it is harder than previously thought to cache distinct relative globs pointing to the same file, as the cached glob expansions would need to be rebased to multiple fixed directory parts.
> Turn off caching distinct relative globs

- build/SignToolData.json
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
- src/Package/MSBuild.VSSetup/files.swr
These are dependencies of Microsoft.IO.Redist.dll but weren't available
at runtime, causing NGEN failures.
> Install System.Buffers and System.Memory

- build/BootStrapMSBuild.targets
Today Microsoft.Common.props (and Microsoft.VisualStudioVersion.v15.Common.props) are placed inside the Bin folder, which isn't where they exist in the VS directory. This leads to the current VS install's being used in the bootstrap instead of the one in the repo, making it cumbersome to test changes to Microsoft.Common.props
> MSBuild.Bootstrap to place Microsoft.Common.props correctly

- build/SignToolData.json
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
- src/Package/MSBuild.VSSetup/files.swr
These were found while investigating ngen issues and were merged into `exp/net472-optprof2`. I merged a PR from `exp/net472-optprof2` and these were missed.
> Deploy additional assemblies

- version.json
So we don't go backwards from the optprof branches.
> Bump version for vs16.0-preview1

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/BackEnd/BuildManager/GraphBuildRequestData.cs
- src/Build/BackEnd/BuildManager/GraphBuildResult.cs
- src/Build/BackEnd/BuildManager/GraphBuildSubmission.cs
- src/Build/Graph/ProjectGraph.cs
- src/Build/Graph/ProjectGraphEntryPoint.cs
- src/Build/Microsoft.Build.csproj
- src/MSBuild/XMake.cs
This enables programatic graph builds by exposing a way to ask the BuildManager for a graph build instead of the logic being inside XMake.
This also fixes a couple bugs related to how graph builds were happening and gets the logic "closer" to where we want it to end up in the end (the scheduler).
Closes: #3840
> Move graph build logic to the BuildManager

- src/Shared/CoreCLRAssemblyLoader.cs
From @vitek-karas,
> Handler for the Resolve event should never call LoadFromAssemblyName (or Assembly.Load) – that will lead to recursive loops. Resolve event handlers should only load assemblies from sources (files, memory streams).
Fixes #3352
> Remove LoadFromAssemblyName for MSBuild assemblies in the CoreCLRAssemblyLoader

- build/Packages.props
- build/SignToolData.json
- build/Versions.props
- src/Build/Construction/ProjectRootElement.cs
- src/Build/Evaluation/ProjectRootElementCache.cs
- src/Build/Microsoft.Build.csproj
- src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
- src/Package/MSBuild.VSSetup/files.swr
- src/Shared/Modifiers.cs
- src/Shared/UnitTests/FileUtilities_Tests.cs
- src/Tasks/DependencyFile.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Utilities/Microsoft.Build.Utilities.csproj
We're not currently using any of the new functionality (right @cdmihai?) and we have a [VS bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/722326) that there are related ngen failures.
This is _almost_ straight reverts; a couple had merge conflicts.
> Avoid Microsoft.IO.Redist

- src/Shared/AssemblyFolders/AssemblyFoldersEx.cs
- src/Shared/AssemblyNameReverseVersionComparer.cs
- src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
- src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs
- src/Tasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs
- src/Tasks/AssemblyDependency/AssemblyFoldersResolver.cs
- src/Tasks/AssemblyDependency/AssemblyNameReferenceAscendingVersionComparer.cs
- src/Tasks/AssemblyDependency/AssemblyResolution.cs
- src/Tasks/AssemblyDependency/CandidateAssemblyFilesResolver.cs
- src/Tasks/AssemblyDependency/DirectoryResolver.cs
- src/Tasks/AssemblyDependency/FrameworkPathResolver.cs
- src/Tasks/AssemblyDependency/GacResolver.cs
- src/Tasks/AssemblyDependency/HintPathResolver.cs
- src/Tasks/AssemblyDependency/RawFilenameResolver.cs
- src/Tasks/AssemblyDependency/Reference.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
- src/Tasks/AssemblyDependency/Resolver.cs
- src/Tasks/AssemblyDependency/TaskItemSpecFilenameComparer.cs
- src/Tasks/InstalledSDKResolver.cs
- src/Tasks/RedistList.cs
Replaces all ```System.Collection``` usages with the equivalent collections from ```System.Collections.Generic``` in RAR. Seems safe and might help performance a little.
> Remove all .NET 1.1 collections from ResolveAssemblyReference

- src/Build/Instance/ProjectItemInstance.cs
Fixes [Bug 68841](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/688412)/[Feedback 678764](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678764).
Fix the serialization of `ProjectItemInstance` such that `_itemDefinitions` (a `List<ProjectItemDefinitionInstance`) and `_directMetadata` (a `CopyOnWritePropertyDictionary<ProjectMetadataInstance>`) are serialized separately.
Currently, when serializing a `ProjectItemInstance` we collapse the metadata in both `_directMetadata` and `_itemDefinitions` into a single dictionary via the `MetadataCollection` property (when deserializing these fields will be null and/or empty collections at this point, of course). Then, when serializing _or_ deserializing we set `_directMetadata` to this new dictionary.
That means that if you start …
> Fix the serialization of ProjectItemInstance

- src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs
- src/Shared/BuildEnvironmentHelper.cs
* Added a test and associated fixes for pointing `MSBUILD_EXE_PATH` to a Dev15 VS install path.
* Added some regression tests on scenarios that shouldn't be supported.
Note that after discussing with @rainersigwald we both agreed that other scenarios shouldn't work. The scenario here is using `Microsoft.Build.dll` version 16.0+ to evaluate, and potentially build, a project when you only have MSBuild 15 installed. The engine should be backwards compatible so using older targets _should_ not be an issue. But if we add custom logic to allow this to work easily, many scenarios are going to be broken. For example multiproc builds will call MSBuild.exe to spawn workers which will fail because the versions will mismatch. However, if the environment variable is explicitly set MSBuild should honor …
> Don't block explicitly referencing MSBuild 15.0

- src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
- src/Build/Evaluation/Evaluator.cs
Adding a info message when a local property is not evaluated because there is a global property with the same name already. I re-used a can't override global property error message that we had already.
Fixes https://github.com/Microsoft/msbuild/issues/1196
> Adding a info message when a local property is not evaluated because of global property

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
As of .NET 4.6.2, the default values for ```Switch.System.IO.UseLegacyPathHandling``` and ```Switch.System.IO.BlockLongPaths``` are ```false```. Since we now target .NET 4.7.2, these are no longer necessary.
> Remove unnecessary AppContextSwitchOverrides from app.config

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
This is a new, not-to-be-used-unless-specifically-okayed-by-the-.NET
team feature that is expected to resolve some of the stability issues
caused by `DisableFXClosureWalk`. If present, it supersedes the older
flag, so we should opt into both to get performance on both 4.8+ and
older frameworks.
⚠ Note to everyone: **you shouldn't use this**. It exists only for very specific scenarios.
> Opt into DeferFXClosureWalk

- src/Shared/FileUtilities.cs
- src/Shared/NativeMethodsShared.cs
- src/Shared/Traits.cs
Also might be useful to have the ability to revert to old behavior if necessary. Should this be controlled via environment variable?
> Enable max path detection

- src/Shared/FileUtilities.cs
- src/Shared/FileUtilitiesRegex.cs
- src/Shared/Modifiers.cs
- src/Tasks/Exec.cs
Prior code acquired a `Match` and checked the `Length` to assert the full string matched.
This change uses patterns that match end of string `$` in order to draw the same conclusion, allowing the non-allocating `IsMatch` method to be used.
---
Looking at an RPS trace for d16.0 on loading a large solution, this `FileUtilities.GetFullPath`'s usage of `Regex.Match` accounted for 1.5% of total allocations.
We are looking at ways to avoid these calls (dotnet/project-system#3548), but this is a win for MSBuild regardless.
> Don't allocate RegEx Match objects in some cases

- src/Tasks.UnitTests/ComReference_Tests.cs
- src/Tasks/ComReference.cs
- src/Tasks/FileState.cs
- src/Tasks/GenerateResource.cs
Slowly working on this whenever there's time. So far this covers 2/3 tasks.
> Enable long paths on Tasks

- src/Utilities/Resources/Strings.resx
- src/Utilities/Resources/xlf/Strings.cs.xlf
- src/Utilities/Resources/xlf/Strings.de.xlf
- src/Utilities/Resources/xlf/Strings.en.xlf
- src/Utilities/Resources/xlf/Strings.es.xlf
- src/Utilities/Resources/xlf/Strings.fr.xlf
- src/Utilities/Resources/xlf/Strings.it.xlf
- src/Utilities/Resources/xlf/Strings.ja.xlf
- src/Utilities/Resources/xlf/Strings.ko.xlf
- src/Utilities/Resources/xlf/Strings.pl.xlf
- src/Utilities/Resources/xlf/Strings.pt-BR.xlf
- src/Utilities/Resources/xlf/Strings.ru.xlf
- src/Utilities/Resources/xlf/Strings.tr.xlf
- src/Utilities/Resources/xlf/Strings.zh-Hans.xlf
- src/Utilities/Resources/xlf/Strings.zh-Hant.xlf
- src/Utilities/ToolTask.cs
Fixes #3968.
Sample output:
```
Build started 11/29/2018 6:01:24 PM.
1>Project "s:\msbuild\foo.proj" on node 1 (default targets).
1>s:\msbuild\foo.proj(4,2): error MSB6011: ClassLibrary3.Class1.ValidateParameters() returned false, but did not l
og an error.
1>Done Building Project "s:\msbuild\foo.proj" (default targets) -- FAILED.
Build FAILED.
```
> Log an error when ToolTask.ValidateParameters fails

- src/Tasks/Microsoft.Common.tasks
These tasks already exist in `Microsoft.Build.Tasks.Core.dll`, but were
not exposed with a `<UsingTask>`.  I presume this is an oversight.  In
contrast, these tasks are already exposed from
`Microsoft.Build.Tasks.v4.0`, with a `<UsingTask>`.
> Expose GetFileHash & VerifyFileHash for .NET Core

- src/Tasks/SystemState.cs
Currently, each instance of the ```SystemState``` cache copies _all_ ```FileState``` objects accessed and serializes them onto disk for each project. As pointed out in https://github.com/Microsoft/msbuild/issues/2015#issuecomment-443340515, this results in large amounts of identical data written to disk and deserialized into memory.
This adds some bookkeeping to each ```SystemState``` instance to ensure that ```FileState``` objects aren't duplicated from the process-wide cache if another instance is already responsible for serializing that object. This results in some additional IO on multi-proc builds since RAR execution order may change around and result in some cache misses, but it seems to be outweighed by the huge savings in memory and RAR times.
In both of these traces, this results …
> Distribute ResolveAssemblyReference cache

- src/Shared/AssemblyNameExtension.cs
- src/Shared/ConversionUtilities.cs
- src/Shared/NativeMethodsShared.cs
- src/Tasks/AssemblyDependency/AssemblyNameReferenceAscendingVersionComparer.cs
- src/Tasks/AssemblyDependency/Reference.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
- src/Tasks/SystemState.cs
Various hotspots in the core RAR logic that were showing up in profiles, and some easy allocation reductions. I'll break this up into separate commits with exact changes and clean up a bit, but here's a side-by-side perf trace I just ran on the changes in ```ReferenceTable``` when building OrchardCore. Notably ```ResolveConflicts()``` is basically free.
> Improve ResolveAssemblyReference performance

- src/MSBuild/XMake.cs
Create the build request before the first build invocation to avoid changes to the current working directory to lead to the wrong request being created in regards to normalized paths to the projects.
This was the less risky change we could come up with for now.
> Create the build request before the first build invocation

- src/MSBuild/app.amd64.config
This ports the change from 7b279c8ad to apply to 64-bit MSBuild as well
as 32-bit.
> Get Roslyn from 15.0 folder in amd64 MSBuild, too

- .vsts-dotnet.yml
- src/MSBuild/MSBuild.csproj
- src/MSBuildTaskHost/MSBuildTaskHost.csproj
This is a hacky workaround for problems preserving .pdbs for x64 versions of our .exe projects. We'll have to manually extract/publish those, but with these changes it's possible.
Sample official build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2309328. Note that it has https://dev.azure.com/devdiv/_apis/resources/Containers/2969610?itemPath=bin%2FMSBuild%2Fx64%2FRelease%2Fnet472%2FMSBuild.pdb and https://dev.azure.com/devdiv/_apis/resources/Containers/2969610?itemPath=bin%2FMSBuildTaskHost%2Fx64%2FRelease%2Fnet35%2FMSBuildTaskHost.pdb (all links internal-only).
> Preserve bin in official build

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
- src/Shared/UnitTests/App.config
Changing the SDK40ToolsPath and FrameworkSDKRoot to look for 4.7.2 version of the framework instead of 4.6.1, given that 4.7.2 is the default installed with Dev16.
Fixes https://github.com/Microsoft/msbuild/issues/4049
> Changing the SDK40ToolsPath and FrameworkSDKRoot to look for 4.7.2

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/Hash_Tests.cs
- src/Tasks/Hash.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #4023 
Seems safe to always make hashing before ```CoreCompile``` case-insensitive regardless of file system. On a case-insensitive file system, this fixes the tagged issue. On a case-sensitive file system, adding/removing inputs that only differ by casing will still result in a different hash since we're hashing more/less characters, and breaking it seems like a very rare case.
>  Ignore case when hashing CoreCompile inputs

- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
The presence of the XML manifest for the NuGet SDK resolver will cause
MSBuild to error when the actual assembly is not present (it is present
for VS installations from a NuGet VSIX, but it's not guaranteed in
CoreXT environments). Just remove it.
Internal bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/763317
> Don't ship NuGet SDK resolver manifest for CoreXT

- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
Fix https://github.com/Microsoft/msbuild/issues/4044. The symptom of the issue is that design-time build logs (such as those obtained from Project System Tools) do not have evaluation messages or imported projects/targets. This is because the MuxLogger used by Microsoft.VisualStudio.ProjectServices.dll drops all build messages where the submission ID is not equal to the current submission ID of the logger. All evaluation messages had the submission ID set to -1 and they were all dropped.
To fix this we need to propagate the submission Id from the build request so that all log events (including evaluation messages) have a proper submission Id set. The way it is right now the BuildEventContext is Invalid, so the Submission ID is set to -1.
With this change the Submission ID is set correctly …
> Use the real submission ID in BuildEventContext.

- eng/cibuild_bootstrapped_msbuild.sh
I wanted to run this on my own machine and was annoyed when zsh didn't like it.
> Add shebang to cibuild_bootstrapped_msbuild.sh

- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
Edit the Strings.resx file and modified the value for 'InvalidFunctionStaticMethodSyntax'.
Fix #3171
> Fix misleading error message for MSB4189 when there is a type mismatch

- .vsts-dotnet-ci.yml
This doesn't directly solve the problem I set out to solve (I think we're just waiting on a feature rollout for https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-146-update#display-status-for-each-pipeline-job-in-github-checks), but it is consistent with the new names (see https://github.com/MicrosoftDocs/vsts-docs/commit/c16b2205df876ba1d083e2df2af62520efea9128 and https://github.com/MicrosoftDocs/vsts-docs/commit/d5c8e55899bcaaa079fe58a05e8dfeebf58e04be), so might as well go with it.
> Update Azure DevOps YAML element names

- src/Directory.Build.targets
I tried to disable a test with an `[ActiveIssue]` annotation and it didn't actually disable, because we weren't telling xunit to ignore known-failing tests.
> Disable tests with ActiveIssue attributes

- src/Tasks/FileIO/GetFileHash.cs
- src/Tasks/FileIO/VerifyFileHash.cs
> Typo fixes in *FileHash tasks

- version.json
This will disambiguate the official builds that came out of master that currently collide with vs16.0
> Version 16.0 + a few

- README.md
- version.json
Version change (to stop version collisions with `vs16.0`) + README change explaining branch structure.
> Move version in master to 16.1

- src/Tasks.UnitTests/WriteLinesToFile_Tests.cs
- src/Tasks/FileIO/WriteLinesToFile.cs
#4125 mistakenly targeted master. This just cherry-picks it into `vs16.0`, where it should have gone in the first place.
fyi @livarcocc
> Backport WriteLinesToFile fix

- src/Shared/UnitTests/MockEngine.cs
- src/Tasks.UnitTests/Copy_Tests.cs
This test is mysteriously failing pretty often in `vs16.0` but the failure is useless:
```
Error message
Assert.Equal() Failure\nExpected: -1\nActual: 0
Stack trace
at Microsoft.Build.UnitTests.MockEngine.AssertLogDoesntContain(String contains) in /home/vsts/work/1/s/src/Shared/UnitTests/MockEngine.cs:line 444
at Microsoft.Build.UnitTests.MockEngine.AssertLogDoesntContainMessageFromResource(GetStringDelegate getString, String resourceName, String[] parameters) in /home/vsts/work/1/s/src/Shared/UnitTests/MockEngine.cs:line 378
at Microsoft.Build.UnitTests.Copy_Tests.DoCopyOverCopiedFile(Boolean skipUnchangedFiles) in /home/vsts/work/1/s/src/Tasks.UnitTests/Copy_Tests.cs:line 582
```
So add logging and use an assert that will tell us what's wrong.
> DoCopyOverCopiedFile diagnosability

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Contributes to https://github.com/dotnet/sdk/issues/2707
This adds a stub target for the new output group to common targets, which the SDK will override.
@davkean Is this the correct pattern to follow here?
FYI, @chabiss
> Add DesignerRuntimeImplementationProjectOutputGroup

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
- src/Tasks/Microsoft.Build.Tasks.csproj
This completes the move from 15.0 to Current by consuming Roslyn
from the new directory. It is dependent on
https://github.com/dotnet/roslyn/pull/33114 which actually moves the
relevant files.
cc @jaredpar @tmat
> Expect Roslyn tasks in Current

- eng/cibuild_bootstrapped_msbuild.ps1
Avoids an error like
```
The term 'true' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
System.Management.Automation.CommandNotFoundException: The term 'true' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(I …
```
> Set debugger-launch parameter as string in CI script

- src/Build/Construction/ProjectExtensionsElement.cs
- src/Build/Construction/ProjectRootElement.cs
When setting a ProjectExtensionsElement value, MSBuild diffs the current
and desired XML and writes only in the case that they differ. But this
is producing false negatives because the InnerXml may have a namespace
inherited from the project that isn't represented in the "real" XML.
Allow the current to be equal to the desired _modulo_ that namespace.
Fixes #3904.
> Leave ProjectExtensionsElement if namespace is only diff

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
These assemblies have moved and versioned in dev16.
Update of the workaround for #1675 in #1699.
Fixes #4137.
> C++ CodeAnalysis assemblies to v16

- src/Package/MSBuild.VSSetup/files.swr
Fixes #3852 by ensuring that NuGet's tasks and targets are present
wherever MSBuild itself is, since common.targets now depends on NuGet.
Closes NuGet/Home#7390.
I did a private test build of 45c61c6e2 ([comparison view](https://github.com/Microsoft/msbuild/compare/vs16.0...exp/vsix-depend-on-nuget)), which is this commit + some build changes that shouldn't be relevant at all. DDRITs passed, Build Tools installs successfully, and the NuGet stuff is there in a C++-only Build Tools installation. Build and DDRIT results available here (Microsoft internal): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/162986
@rrelyea, can you review or nominate another NuGet reviewer?
@DustinCampbell, this should help with bugs like https://github.com/OmniSharp/omnisharp-roslyn/issues/1311 (not …
> VSIX dependency on NuGet.BuildTools

- src/Build.UnitTests/EndToEndCondition_Tests.cs
- src/Build/Evaluation/Conditionals/StringExpressionNode.cs
Some extension (for sure WiX, probably others) compare
$(MSBuildToolsVersion) against a known baseline like "4.0" to determine
further behavior. This is broken by the change of ToolsVersion to
"Current":
```
A numeric comparison was attempted on "$(MSBuildToolsVersion)" that evaluates to "Current" instead of a number, in condition " '$(MSBuildToolsVersion)' == '' OR '$(MSBuildToolsVersion)' < '4.0' ".
```
Allow these comparisons again by treating expansion of that property
specially and as equivalent to CurrentVisualStudioVersion. Those two
values matched for MSBuild 12 to 15, so there shouldn't be too much user
confusion around the change.
Fixes #4150.
> Allow numeric comparison of $(MSBuildToolsVersion)

- documentation/specs/static-graph.md
- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build.UnitTests/Graph/IsolateProjects_Tests.cs
- src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
- src/Build.UnitTests/Graph/ResultCacheBasedBuilds_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/Graph/GraphBuildRequestData.cs
- src/Build/Graph/GraphBuildResult.cs
- src/Build/Graph/GraphBuildSubmission.cs
- src/Build/Graph/ProjectGraph.cs
- src/Build/Graph/ProjectGraphEntryPoint.cs
- src/Build/Graph/ProjectGraphNode.cs
- src/Build/Microsoft.Build.csproj
- src/MSBuild/XMake.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
Types under Experimental can sustain breaking changes. They're WIP APIs, which we're still figuring out how they work. Having them in the main branch saves us from the pains of diverging forks.
> Move graph to experimental namespace

- src/Tasks/Microsoft.WorkflowBuildExtensions.targets
This target in $(MSBuildFrameworkToolsPath)\Microsoft.WorkflowBuildExtensions.targets does bad things to builds inside Visual Studio. Specifically, it generates files *only* when building from within VS, for both real and design-time builds. This leads to all kinds of build problems.
In Dev16 we no longer need these files to exist on disk for Workflow Designer scenarios. We can't modify $(MSBuildFrameworkToolsPath)\Microsoft.WorkflowBuildExtensions.targets because that would break the Workflow Designer for older versions of VS using newer versions of the Framework. Instead, we effectively turn it off by overriding it with a no-op implementation here.
> Turn GenerateCompiledExpressionsTempFile into a no-op

- documentation/specs/task-isolation-and-dependencies.md
Initial description of
* Isolating tasks to avoid load failures
* Task dependency resolution based on `.deps.json`
> Speclet for task isolation and dependency resolution

- src/Directory.BeforeCommon.targets
This has been enabled in .NET Core for a while now. Turning on the MSBuild usages of it.
(thanks for mentioning this was possible @nguerrera!)
> Enable FEATURE_DEBUG_LAUNCH on .NET Core

- version.json
Drop the `-preview` from our versions.
This will require another insertion to VS.
(Note to observers: this doesn't mean we're 100% done. Just that we think we're very close.)
> Release package versioning for 16.0

- src/Build.OM.UnitTests/Construction/WhiteSpacePreservation_Tests.cs
The previous iteration of this normalization mechanism ate the character
before a bare `\n` when run on Windows.
Noticed this while investigating bizarre local test failures in #4186.
fyi @cdmihai
> Normalize newlines with negative lookbehind

- src/Build.UnitTests/BinaryLogger_Tests.cs
- src/Build.UnitTests/ConsoleLogger_Tests.cs
- src/Build/Logging/BaseConsoleLogger.cs
- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
- src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
Using `ItemDefinitionGroup` metadata definitions, it's possible to create an item with an unexpandable metadatum: the `Include` is not a path-like thing and the metadatum uses a filesystem intrinsic metadatum name like `%(FileName)`.
Metadata is recursively expanded when logging is sufficiently high, which can lead to #4181 when 
There are a couple of options for resolving this. I'm proposing option 1 in this PR, but would like to get some opinions before going forward.
1. Log an error in the expanded metadata (including the unexpanded value and the error itself)
```
Initial Items:
Foo
-in "x\y\z"
MetadataFileName = Cannot expand metadata in expression "a\b\%(Filename).c". The item metadata "%(Filename)" cannot be applied to the path "-in "x\y\z"". Illegal characters in path.
```
2. …
> Tolerate unexpandable metadata from definitions in logging

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
Add a new intrinsic item function, `GetPathsOfAllFilesAbove`, to get all the files of a given name that are in the same or ancestor directories of the given items. This is being done to support the ".editorconfig in compiler" scenario where we need to map from all the .cs/.vb files in the project to the applicable set of .editorconfig files. For various reasons we don't want to find the .editorconfig files using a target/task, so instead we are adding this intrinsic function to allow us to find them as part of project evaluation.
There are two phases to the implementation. First we build the set of directories that we will search. For each input item, we get the item's directory and see if it is already in the set. If it is we don't need to do anything further with that item. Otherwise we …
> Add a new intrinsic item function

- src/Directory.Build.props
We couldn't do this when [support for reference assembly generation and
consumption lit up](https://github.com/Microsoft/msbuild/pull/2039), because we wanted to continue supporting older VS
builds. But now I think we've moved far enough forward in time that we
can require 15.3.
> Use reference assemblies in the MSBuild repo

- eng/config/OptProf.json
Some of the tests msbuild used in OptProf V1 have been ported to OptProfV2. Switching to using them now that they are available.
Removed the old test because it should not be necessary anymore and because it was flaky.
> Switching OptProf tests to the same we used in OptProf v1

- src/Build/Xml/XmlReaderExtension.cs
- src/Tasks.UnitTests/Exec_Tests.cs
Fixes #4210 by reverting to the old behavior of always using `XmlTextReader`. I didn't just revert #3584 because that would be a public API change, and it seems better to avoid that churn this close to release. With this PR, the read-only option is ignored.
> Support multi-line Exec Commands

- documentation/specs/static-graph.md
- src/Build.UnitTests/Graph/ResultCacheBasedBuilds_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/BackEnd/BuildManager/CacheSerialization.cs
- src/Build/Microsoft.Build.csproj
With the details from #4218 and caching.
> Update static graph spec

- .vsts-dotnet.yml
YAML variable definitions override queue-time variables, so these must
not be set in this way.
Docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#allow-at-queue-time
> Remove YAML variable definitions

- src/Shared/OpportunisticIntern.cs
Reduce rate of taking numProcessors or even more Monitor locks in string interning by increasing initial size of the string interning dictionary.
Increases from 31 to 2048.NextPrime() initial capacity. In medium-sized codebases (3K proj files) we see 200K of these; for 500 projects, 48K.
Intended to also reduce the rate of exceptions we see parsing large repos in QuickBuild:
```
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
at System.Threading.Monitor.Enter(Object obj)
at System.Collections.Concurrent.ConcurrentDictionary`2.AcquireLocks(Int32 fromInclusive, Int32 toExclusive, Int32& locksAcquired)
at System.Collections.Concurrent.ConcurrentDictionary`2.GrowTable(Tables tables, IEqualityComparer`1 newComparer, Boolean …
```
> Reduce rate of taking all Monitor locks in string interning

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Add a `GetPotentialEditorConfigFiles` target so design-time builds can
harvest these items and pass them to the project system.
> Add target to expose potential .editorconfig files

- scripts/EnumerateMSBuild.ps1
The script hadn't been updated since the 15.0->Current move. Adding both
options to keep it working everywhere.
> Enumerate MSBuild from Current

- src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
Clickonce publishing fails when a prerequisite component is set to run from a absolute location (for e.g. a network share) instead of the Home Site or Relative to the install folder. This is due to an incorrect check that needs to happen only when the prerequisite component is set to run from the Relative location. This check and the subsequent copy needs to only happen when the prerequisite component is set to run from a location relative to the installation folder.
> Devdiv 736904: Clickonce Publish error

- .vsts-dotnet.yml
When the source branch was hardcoded to `$(Build.SourceBranchName)`,
there was no good way to tell the build "build this branch, but take the
latest OptProf information from branch X". That's an important scenario
when standing up a new branch (like a release branch), or trying to
insert updated bits from a feature branch.
This requires a change to the build definition, which is the only place
(currently) that knows what variables to offer at job-scheduling time.
See https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2568755 for an example of the override working:
```
Acquiring optimization data
Downloading optimization data from service https://devdiv.artifacts.visualstudio.com, drop OptimizationData/Microsoft/msbuild/master/20190405.1/295317/1
```
> Allow overriding the optprof source branch

- src/Directory.BeforeCommon.targets
- src/Tasks.UnitTests/GenerateResource_Tests.cs
- src/Tasks/GenerateResource.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Fix https://github.com/Microsoft/msbuild/issues/2950
If resource generation runs, the compile will in turn have to run, and then every downstream project. However resource generation doesn't log why it ran. This make it unnecessarily difficult to know why an overbuild is happening, such as one I'm looking at right now in my repo.
I used the same strings as for target up to date checking so it's easier to search the log (eg for "is newer than output file"). I also used the same low verbosity that those messages have. 
If the resources are all up to date, there is essentially no extra work, and no extra logging. If they are not, at most this will generate 1 extra low verbosity event per resource file. Either way, there is no new IO.
Also a trivial commit that extracts getting file extension …
> Add up-to-date logging for GenerateResource

- src/Shared/UnitTests/MockLogger.cs
`AssertLogDoesntContain`'s summary now properly describes its function.
> MockLogger AssertLogDoesntContain Summary Described The Opposite Functionality

- src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
The issue was a dictionary lookup on the `InnerBuild` key:
`GetNodesWithProjectNumber(graph, 1).First(n => n.ProjectInstance.GlobalProperties.TryGetValue(InnerBuildPropertyName, out string p) && p == "a")`
where by chance a node with no `InnerBuild` references is evaluated before the lambda returns true
> ProjectGraph 'InnerBuildsCanHaveSeparateReferences' Failed Randomly

- .vsts-dotnet-ci.yml
- eng/cibuild_bootstrapped_msbuild.ps1
Fixes #4001 by switching the initial build of the bootstrapped-core job
to also be driven by core MSBuild.
Changes the `-hostType` parameter of `cibuild_bootstrapped_msbuild` to
`-msbuildEngine` to match the Arcade build option.
> Enable initial build with Core in CI

- src/Build/Instance/TaskRegistry.cs
Significantly improves #4155 
Opening a solution of 810 projects yields reduced string duplication.
Example string that went from 9152 duplicates to 680:
> Task Registry Now Uses Opportunistic Intern

- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
- src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
The Visual Studio IDE relies on "design-time" builds to determine what the contents of a project is. Prior to 16.0, the design-time build for .NET Framework projects utilized MSBuild host objects to determine what the command-line inputs would be to the compiler (i.e. csc.exe). In 16.0, we switched to a non-host object based method for extracting the command-line as it works better for Roslyn.
Unfortunately, the method we now use isn't supported on the very first version of the Roslyn compilers. So if a project opened in 16.0 explicitly references the Microsoft.Net.Compilers 1.0 package, then the design-time build will fail and Intellisense will be broken.
The fix is to ignore the compiler override if (and only if) we're doing a design-time build. This should be safe because a design-time …
> Disallow using Roslyn 1.0.0 targets in design-time builds

- src/Package/MSBuild.VSSetup/files.swr
Fixes #4307, depending on the new PackageGroup that comprises the
correct NuGet package for the current SKU.
> Use Microsoft.VisualStudio.PackageGroup.NuGet (16.0)

- ref/ExcludeAttributeList.txt
This is emitted by newer Roslyn compilers, but is not a meaningful
contract change in our public API, so I'm setting it to be ignored.
> Ignore IsReadOnlyAttribute in GenAPI

- .vsts-dotnet-ci.yml
`succeededOrFailed()` evaluates to `false` when the job is cancelled (as due to a
timeout), which makes diagnosing test hangs difficult. Instead, always
capture whatever logs and test output exists.
> Always copy build logs and test results

- src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
We need this and an Arcade update (https://github.com/dotnet/arcade/pull/2698) that will come in through #4297 before we can insert a 16.2 build into VS.
> Use $(VsixVersion) to set VSIX version

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
- src/MSBuild/NodeEndpointOutOfProcTaskHost.cs
- src/Shared/CommunicationsUtilities.cs
Addresses #4308
An environment variable `MSBUILDNODEHANDSHAKESALT` may be defined in order to allow MSBuild only to connect to nodes that come from the same test environment.
> MSBuild May "Salt" Node Handshake For Test Environments

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
Adding a bind redirect for Microsoft.Build.CPPTasks.Common to 16.1 from 16.0-16.1. This will allow task dlls that depend on this assembly to target 16.0 and for it to work on 16.0 and higher versions of VS.
> Adding a bind redirect for Microsoft.Build.CPPTasks.Common to 16.1

- eng/Versions.props
Works around https://github.com/dotnet/roslyn/issues/35793 which sets a
win32 resource to a bad value when there are too many dots in
`AssemblyInformationalVersion`.
Medium term, I'd rather see us on semver2, since it's a nicer overall
experience.
> Opt out of semver2

- src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
Contributes to https://github.com/Microsoft/msbuild/issues/4322
(the diff is hard to read - I just wrapped everything into a try catch)
cc @rainersigwald @danmosemsft
> Protect frequent logging crashes with catch all

- src/Build/Definition/ProjectCollection.cs
- Updated HostServices getter to use a reader lock and only upgrade to a writer when creating a value. This is a hotspot in parallel creation of projects in paths like this:
at Microsoft.Build.Evaluation.ProjectCollection.DisposableReaderWriterLockSlim.EnterWriteLock()
at Microsoft.Build.Evaluation.ProjectCollection.get_HostServices()
at Microsoft.Build.Evaluation.Project.CreateProjectInstance(ILoggingService loggingServiceForEvaluation, ProjectInstanceSettings settings)
- Moved checks on param values, and pure functional modifications to parameters, out of locks.
- Moved invariant allocations out of locks where possible.
- Updated ToolsetLocations to a read-only property since it is only set in the constructor, eliminating locking on that property.
> Reduce reader-writer lock contention in ProjectCollection

- src/Framework/ProjectStartedEventArgs.cs
Noticed this while working on something today.
> Typo in ProjectStartedEventArgs.ProjectId doc comment

- src/Tasks.UnitTests/Move_Tests.cs
`Microsoft.Build.UnitTests.Move_Tests.MoveLockedFile`
- this was marked as failing on netcore
- It expects to fail trying to move a "locked"(open for writing) file
- But on dotnet and mono, the behavior is to not fail in that operation
- Thus, marking this test as Windows/full framework only.
> Mark a test relevant only on full framework as WindowsOnly

- src/Tasks/ComReference.cs
Documentation for PtrToStructure shows the syntax PtrToStructure(IntPtr, Type) is now obsolete.   PtrToStructure<T>(IntPtr) is supported since .NET Framework 4.5.1
Documentation can be found at: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure
> Fixed Obsolete Marshal.PtrToStructure reference.

- src/Tasks.UnitTests/GenerateResource_Tests.cs
- src/Tasks/GenerateResource.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/ResGenDependencies.cs
A step towards more than just strings as embedded resources in .NET Core.
Removed all preprocessor conditions for FEATURE_RESGENCACHE, as @rainersigwald is working towards core resx parsing.
The function `GetLinkedFiles` needs a .NET Core code path. In its current state, it returns an empty array on core, while full framework will do traditional processing.
> Removal of FEATURE_RESGENCACHE checks for .NET Core

- src/Build/BackEnd/Components/Scheduler/Scheduler.cs
Limit the number of histogram bar segments. For long runs the number of segments
can be counted in hundreds of thousands (for instance a build which took 8061.7s
would generate a single line line 161,235 characters long) which is a bit
excessive and makes viewing text logs with histograms quite painful at times.
This commit implements a scaled approach in which the number of bar elements
calculated with the original formula is subdivided as follows:
* <= 100 segments remains as-is, scale 1:1, character used: `.`
* &gt; 100 <= 1000 segments, scale 1:100, character used: `+`
* &gt; 1000 segments, scale 1:1000, character used: `#`
Additionaly, scale is printed after the histogram bar if it's different than `1:1`
> Shorter node utilization histogram bars

- eng/BootStrapMSBuild.targets
- src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
- src/Package/GetBinPaths.targets
Building cloudbuild with static graph requires the 64 bit msbuild.
This PR depends on #4327, review only the latest commit.
> [Static graph] Add 64bit binaries to the bootstrap directory

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
The `GetPathsOfAllDirectoriesAbove` item intrinsic takes a set of items and is supposed to return the set of directories above those items--one item per directory. However, it doesn't properly handle some forms of relative paths. For example, if you start with these items:
* C:\alpha\beta\Class1.cs
* C:\alpha\beta\..\Class2.cs
Then you'll get the following output:
* C:\
* C:\alpha
* C:\alpha\beta
* C:\alpha\beta\..
Which means we end up with two different paths that logically represent the same "alpha" directory.
To fix this we first run the item paths through `Path.GetFullPath(...)` which reduces it to a normalized form without ".." and such.
Fixes #4392.
> Normalize paths in GetPathsOfAllDirectoriesAbove

- src/Tasks/Microsoft.Common.CrossTargeting.targets
Before this change, the `TargetFrameworks` property went through a series of implicit normalizations:
- `<_TargetFramework Include="$(TargetFrameworks)" />` would trim the semicolon delimited list of TFs
- the task batching triggered by `TargetFramework=%(_TargetFrameworkNormalized.Identity)` uses an OrdinalIgnoreCase dictionary which achieves a first one wins case agnostic deduplication 
Sadly the static graph won't see these changes because they happen at build time. I could move it to evaluation time, but that would be a breaking change to people that read `TargetFrameworks` after an explicit sdk import.
Since the change is superfluous, we could also just keep the comment and not the extra item operations. :)
> Make TF normalization explicit

- eng/Version.Details.xml
- global.json
Reverting to older Arcade version to work around
https://github.com/dotnet/arcade/issues/2944.
> Revert to Arcade 1.0.0-beta.19272.13

- src/Tasks/ManifestUtil/SecurityUtil.cs
- src/Tasks/ManifestUtil/mansign2.cs
[AB#377113](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/377113):
Currently in ClickOnce project settings, if you enter a RFC 3161 timestamp server URL, timestamping of the manifest and binaries fails. This is because the current code only works with authenthicode timestamp service.
This change will add support for RFC 3161 timestamping for ClickOnce manifests. It will first attempt an RFC 3161 timestamp and it that fails, fall back to using the older authenticode timestamping.
Reviewer: JohnHart;NingLi
> VS 377113: Add support for RFC3161 timestamping

- src/Tasks.UnitTests/Unzip_Tests.cs
`Microsoft.Build.Tasks.UnitTests.Unzip_Tests.LogsErrorIfReadOnlyFileCannotBeOverwitten`
> Fix test on mono, failing because of difference in error string

- src/Tasks.UnitTests/AssemblyDependency/WinMDTests.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
The ResolveAssemblyReference task outputs `RelatedFiles` that should contain
the native implementation file for "native" WinMD references. This is needed to
copy the implementation file locally for P2P references.
However, if the reference to the native WinMD file already has the
`Implementation` metadata set, the task does not output the implementation file
in the `RelatedFiles` output. In the case of C++ projects that output a WinMD
file, the `Implementation` metadata gets set and referencing projects fail to
copy local the implementation file.
This commit changes the behavior so that the task will output the
implementation file even if the `Implementation` metadata is set on the WinMD
reference.
Fixes #4399.
> Fix related item output for WinMD native implementation file.

- eng/Packages.props
Update to the latest System.Net.Http to avoid a warning our official build has been throwing about a stale reference.
> System.Net.Http 4.3.4

- src/Build.UnitTests/BackEnd/ResultsCache_Tests.cs
- src/Build.UnitTests/Graph/IsolateProjects_Tests.cs
- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
- src/Build/BackEnd/Components/Caching/IResultsCache.cs
- src/Build/BackEnd/Components/Caching/ResultsCache.cs
- src/Build/BackEnd/Components/Caching/ResultsCacheWithOverride.cs
- src/Build/BackEnd/Components/Scheduler/Scheduler.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
- src/Shared/UnitTests/TestEnvironment.cs
Closes #4343
PR is based on #4379, review that one first.
If a project has skipped targets, subsequent requests for those targets trigger the re-execution of the targets. This erroneously causes the static graph constraint of no cache misses. To fix it, `BuildParameters.IsolateProjects` will cause the `ResultsCache` to not issue a cache miss on skipped targets. This seems quite reasonable because in an isolated graph build, a project is visited only once.
> [Static Graph] Skipped results do not trigger cache miss enforcement

- src/Tasks/AssemblyDependency/HintPathResolver.cs
This problem introduced in https://github.com/microsoft/msbuild/pull/3700. If hint path in reference plus current directory more than MAX_PATH then MSBuild couldn't resolve the reference. But file exists and the actual path less than MAX_PATH. The problem in function GetFileAttributesEx. This function just contacted hint path with the current directory, and it doesn't work when your current directory deep into file system but the library on the top of the hierarchy. I benchmarked this fix with BenchmarkDotNet and not found a statistically significant difference between the original code and my fix.
> Support longer relative paths in ResolveAssemblyReference HintPaths

- src/MSBuild/Microsoft.Build.CommonTypes.xsd
Add two properties to fix warnings in DesktopBridge project file.
> Add Windows Application Package properties to Microsoft.Build.CommonTypes.xsd

- .vsts-dotnet.yml
This should speed up the official build considerably in addition to minimizing redundant uploads.
> Disable `bin` upload

- src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverManifest.cs
Read the file with an XmlReader instead of using serialization which reduces JIT and overall read time.
Related to #4025
> Improve the performance of the SdkResolverManifest

- src/Tasks.UnitTests/Exec_Tests.cs
- src/Tasks/Exec.cs
When UTF-8 is the system default codepage, the encoding we get is
`Encoding.UTF8`, which uses a BOM. Unfortunately, `cmd.exe` emits an
error when trying to execute a file that starts with a BOM, so all Exec
tasks on an OS with that configuration are broken.
Instead, if the default encoding is a UTF-8 variant with a BOM, force it
to use UTF-8 with no BOM.
Marking as WIP while I consult with some internal Microsoft CMD experts to see if 
1. there's a better way
1. We should cross-link to an OS bug
> Avoid emitting BOM to command script in Exec

- .vsts-dotnet.yml
- README.md
- eng/Versions.props
- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
Includes a VC++ binding redirect, so this can only be inserted to branches that have already moved to 16.3 version numbering.
> Version bump to 16.3

- src/Tasks/Microsoft.Common.CurrentVersion.targets
This will enable the VS project system to call this target to populate the Frameworks node in the solution explorer.  Microsoft.NET.Sdk will override this target (see https://github.com/dotnet/sdk/pull/3355) to provide ResolvedFrameworkReference items as appropriate.
> Add stub ResolveFrameworkReferences target

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Added `Condition="'$(DesignTimeBuild)' != 'true'"` to the `_GenerateCompileDependencyCache` target to prevent it from running during design-time builds.
Edit: This fixes #4456
> Prevent _GenerateCompileDependencyCache From Running During Design-Time Builds

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Also taking `BuildingProject` into account for the legacy project system.
Part 2 to #4472 which fixes #4456
> Prevent _GenerateCompileDependencyCache Running During Design Time Build - Legacy Project System

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.OM.UnitTests/Instance/ProjectTargetInstance_Tests.cs
- src/Build.UnitTests/Instance/ProjectInstance_Internal_Tests.cs
- src/Build.UnitTests/TestComparers/ProjectInstanceModelTestComparers.cs
- src/Build.UnitTests/TestData/ProjectInstanceTestObjects.cs
- src/Build/Construction/Solution/SolutionProjectGenerator.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Instance/ProjectInstance.cs
- src/Build/Instance/ProjectTargetInstance.cs
`DependsOnTargets` is already exposed through `ProjectTargetInstance`, so this should be fairly non-controversial, I hope :).
The motivation here is that for consumers of the MSBuild API, like [MSBuildPrediction](https://github.com/microsoft/MSBuildPrediction), are forced to use `Project` instead of `ProjectInstance` to get the values of `BeforeTargets` and `AfterTargets` (via `ProjectTargetElement`). This helps alleviate the need for `Project` in those scenarios.
> Add BeforeTargets and AfterTargets to ProjectTargetInstance

- src/Shared/FileUtilitiesRegex.cs
- src/Shared/Modifiers.cs
Fixes #2435 
Now performing basic in-place checks to determine a root from a non-root directory before calling `Path.GetDirectoryName`. This should eliminate the vast majority of times `Path.GetDirectoryName` is called within `GetItemSpecModifier`. Scenarios where it will still be called is when the current item spec is an invalid root such as:
```
C:///
\\\\\\server\\\share
```
Also swapped all uses of `string.compare(s1, s2) == 0` to `string.equals(s1, s2)` as string.equals does a length check before comparing characters.
> Minimize Path.GetDirectoryName Calls in GetItemSpecModifier

- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
`CancelledBuildInTaskHostWithDelay20` was running the MSBuild 3.5
version of the Exec task in a TaskHost, but the TaskHost in question
used the 4.0 runtime, so it ran in a copy of MSBuild.exe.
This didn't exercise the more-interesting pathway of running the
legacy task in the legacy-compat environment in MSBuildTaskHost.exe.
> Test MSBuildTaskHost

- src/Build.OM.UnitTests/Instance/ProjectInstance_Tests.cs
- src/Build.UnitTests/BackEnd/MSBuild_Tests.cs
- src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
- src/Build.UnitTests/EscapingInProjects_Tests.cs
- src/Build.UnitTests/InvalidProjectFileException_Tests.cs
- src/Build.UnitTests/TargetsFile_Test.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
- src/Tasks.UnitTests/CallTarget_Tests.cs
- src/Tasks.UnitTests/CreateItem_Tests.cs
- src/Tasks.UnitTests/MSBuild_Tests.cs
- src/Tasks.UnitTests/ResourceHandling/GenerateResourceOutOfProc_Tests.cs
- src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
https://dev.azure.com/dnceng/public/_build/results?buildId=252713&view=ms.vss-test-web.build-test-results-tab&runId=6527076&resultId=100097&paneView=debug failed in a way that's not possible to diagnose:
```
Error message
Assert.True() Failure\r\nExpected: True\r\nActual: False
Stack trace
at Microsoft.Build.UnitTests.ObjectModelHelpers.BuildTempProjectFileWithTargetsExpectSuccess(String projectFileRelativePath, String[] targets, IDictionary`2 additionalProperties) in D:\a\1\s\src\Shared\UnitTests\ObjectModelHelpers.cs:line 926
at Microsoft.Build.UnitTests.MSBuildTask_Tests.PropertyOverridesContainSemicolon() in D:\a\1\s\src\Tasks.UnitTests\MSBuild_Tests.cs:line 429
```
with no log to look at.
Instead, force callers of that helper method to pass in a log, and plumb XUnit helpers through …
> Miscellaneous test diagnosability

- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
Since I'm having trouble with #4374, disabling affected test.
cc @cdmihai -- make sure you reenable this locally as you're doing graph testing. Sorry, continuing to work on the real fix!
> Disable intermittently-hanging tests

- src/Tasks.UnitTests/MSBuild_Tests.cs
A series of bad imports caused this test to have BaseIntermediateOutputDirectory set to `\`, which expanded to c:\ because on most machines TEMP is under C:\
> Avoid writing to c:\Debug\ConsoleApp1.exe

- eng/Packages.props
- src/Build/Microsoft.Build.csproj
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
- src/Package/MSBuild.VSSetup/files.swr
S.Resources.Extensions depends on System.Memory, so I've ripped off @BenVillalobos's S.Memory setup authoring work from #4394, but not the part that actually uses Span.
I did update to 4.5.3 to match the dependency from S.Resource.Extensions.
The actual new dependency was added in the same way.
> VS Setup authoring for System.Resource.Extensions

- src/Build/Evaluation/Expander.cs
Meant to fix #4085 but can't seem to repro & prove the fix works.
Reduced allocations by making use of ReadOnlySpan. Previous functionality saw lots of .Substring() and .Trim() calls on strings. Now they're being called on ReadOnlySpan and aren't turned into strings until needed at the end of the function.
> Reduce ExtractPropertyFunction Allocations

- .vsts-dotnet-ci.yml
Three significant changes here:
1. Drop the Windows, full-framework, no-bootstrap build -- we have win/full/debug/bootstrap and win/full/release/nobootstrap so it doesn't seem helpful.
1. Stop uploading logs from both win/core/bootstrap and win/full/bootstrap to the same artifact named "FullOnWindows" 😔
1. Shorten display names so that the GitHub
and Pipelines
UIs don't truncate away useful information.
> CI definition tweaks

- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/XMake.cs
This would allow for a scenario where you want to specify a logger for all builds in a repo. Example:
Directory.Build.rsp
```bash
-ConsoleLoggerParameters:Verbosity=Minimal;Summary;ForceNoAlign
-MaxCPUCount
-NodeReuse:false
-Restore
-logger:%MSBuildThisFileDirectory%\build\MyLogger.dll
```
This will work assuming that `build\MyLogger.dll` is checked into the repo.
I can add tests, just wanted feedback on the name. Not thrilled that it uses the MSBuild property syntax, but couldn't think of something better :)
Edit: Switched to `%` instead.
> Allow specifying relative paths in .rsp files

- src/Package/MSBuild.VSSetup/files.swr
- src/Tasks/System.Resources.Extensions.pkgdef
Adding a pkgdef for System.Resources.Extensions so that it gets added to the generated devenv.exe.config in VS. Without this, VS fails to find this assembly and ends up not loading the ngen version of Core.Tasks.dll, causing it to be jitted and regressing RPS.
I did a private build with this change, inserted into VS and ran RPS and RPS passed. The test insertion PR is here: https://devdiv.visualstudio.com/DevDiv/_git/a290117c-5a8a-40f7-bc2c-f14dbe3acf6d/pullrequest/192193?_a=overview
> Adding a pkgdef for System.Resources.Extensions

- src/Build/Globbing/MSBuildGlob.cs
MSBuildGlob now interns the strings that pass through `MSBuildGlob.Parse`. This cuts down on ~90% of the string duplication that was occuring in `MSBuildGlob.Parse` 
Edit:
Should fix #4511
> MSBuildGlob Interning Memory Improvement

- src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
This test was disabled long ago but appears to be fine now, presumably due to CoreFX updates.
Fixes #301.
> Enable EncodingGetterBasedOnActualEncodingWhenXmlDeclarationIsAbsent

- src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
This reverts commit ea574a45c6856127c38957716e446b3a150687fe.
Fixes #234.
> Enable long-disabled exception from TaskExecutionHost finalizer

- src/Tasks/AssemblyDependency/ReferenceTable.cs
Fixes #4547 by respecting the Implementation metadata only when it's a .dll. The <16.2.0 behavior would only find a .dll, and the comment on ImplementationAssembly expects it to always be a .dll, so I think this is reasonable.
> WinRT: Accept Implementation metadata only when it's a DLL

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/Construction/ProjectRootElement.cs
- src/Build/Instance/ProjectInstance.cs
This fixes #4151 which causes many duplicate strings to be created. Instead of escaping a `ProjectRootElement`'s path over and over creating new strings each time, we just have it created once. This saves about 2% of the managed heap of a large solution open.
> Optimize defining file field

- src/Package/MSBuild.VSSetup/files.swr
These changes support an effort to improve VS performance after an update by tuning the assemblies ngen'd during setup.
After this change, the following assemblies should be ngen'd at priority 1:
```
msbuild\current\bin\microsoft.build.dll
msbuild\current\bin\microsoft.build.tasks.core.dll
msbuild\current\bin\microsoft.build.utilities.core.dll
msbuild\current\bin\msbuild.exe
msbuild\current\bin\system.collections.immutable.dll
msbuild\current\bin\system.threading.tasks.dataflow.dll
```
> Adjust ngen priority of assemblies for perf gains

- src/Build.UnitTests/Evaluation/ProjectCollection_Tests.cs
- src/Build.UnitTests/Evaluation/ProjectRootElementCache_Tests.cs
- src/Build.UnitTests/Evaluation/SimpleProjectRootElementCache_Tests.cs
- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/Build/BackEnd/BuildManager/BuildRequestData.cs
- src/Build/BackEnd/Node/OutOfProcNode.cs
- src/Build/Construction/ProjectRootElement.cs
- src/Build/Definition/ProjectCollection.cs
- src/Build/Definition/Toolset.cs
- src/Build/Evaluation/ConditionEvaluator.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Evaluation/ProjectRootElementCache.cs
- src/Build/Evaluation/ProjectRootElementCacheBase.cs
- src/Build/Evaluation/ProjectStringCache.cs
- src/Build/Evaluation/SimpleProjectRootElementCache.cs
- src/Build/Instance/ProjectInstance.cs
- src/Build/Instance/TaskRegistry.cs
- src/Build/Microsoft.Build.csproj
- src/Shared/Traits.cs
```ProjectRootElementCache``` is currently the largest source of perf issues in the parsing stage of our internal build engine, holding up anywhere from 35% to 60% of total parse time, almost entirely due to lock contention. It holds a single lock for all operations on the cache as it needs to synchronize access between a dictionary of weak references and LRU cache of strong references, guard against potential concurrent modifications to ```ProjectRootElement``` state, and reload on disk changes. All of these properties are important for the Visual Studio scenario, but not for a pure evaluation where state should not change and the cache is short-lived, and has a large impact on performance when parallelizing project evaluation.
This adds a ```SimpleProjectRootElementCache``` only …
> Add SimpleProjectRootElementCache

- .gitattributes
Just happened across documentation that enabled me to do some things I've wanted for a while:
* Include MSBuild core props/targets in repo stats (it's a bunch of our code!)
* Exclude Arcade code from repo stats (we don't use CMake!)
* Mark XLF files as generated (collapse them by default in PRs)
Current stats:
> Linguist tweaks

- src/Shared/UnitTests/FileUtilities_Tests.cs
- src/Tasks.UnitTests/HintPathResolver_Tests.cs
- src/Tasks/AssemblyDependency/HintPathResolver.cs
If there are newlines or white spaces passed to `Path.GetFullpath`, it will throw on fullframework. [Adding `Path.GetFullpath`](https://github.com/microsoft/msbuild/pull/4414/files) in previous change caused extra warning from Resolve Assembly Reference. This change added "skip when the path is not valid" to being back the "no warning but skip" behavior of 16.1.
If the customer has _warning as error_ enabled, a build would be successful in 16.1 but would be fail in the latest version
Yes. by https://github.com/microsoft/msbuild/pull/4414, since 16.2
Low risk.
Additional unit tests and manual end to end tests.
------------------------------
fix https://github.com/microsoft/msbuild/issues/4593
This is a strict fix for the warning problem. Please look at …
> Fix warning when newline in hintpath

- eng/Packages.props
- src/nuget/Microsoft.Build.nuspec
Consolidate versions used between VS and .NET Core.
This avoids an RPS regression in VS 16.3 which is about to switch to Dataflow 4.9.0
No.
Low.
> Update System.Threading.Tasks.Dataflow to 4.9.0

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/CreateCSharpManifestResourceName_Tests.cs
- src/Tasks/CreateCSharpManifestResourceName.cs
- src/Tasks/CreateManifestResourceName.cs
- src/Tasks/CreateVisualBasicManifestResourceName.cs
- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
- src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
In SDK projects and new project system, we have eliminated the need for DependentUpon to make the appropriate file nesting in the IDE tree. However, there is a place where the build actually uses DependentUpon to:
1. Locate a source file, and _parse (!)_ it to get first class name and namespace
2. Generate .resources accordingly.
But people and features in VS rely on this and it has been a consistent source of feedback in moving to .NET Core 3.0. This opts into new behavior to use a convention instead of requiring explicit metadata.
Original issue: https://github.com/microsoft/msbuild/issues/4488
This change is dependent upon: https://github.com/dotnet/sdk/pull/3533
In a fairly common situation for projects that use resources, avoids the need to specify `DependentUpon` metadata for each …
> Resource Naming DependentUpon Convention

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/Logging/LoggerDescription.cs
- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/Resources/Strings.resx
- src/MSBuild/Resources/xlf/Strings.cs.xlf
- src/MSBuild/Resources/xlf/Strings.de.xlf
- src/MSBuild/Resources/xlf/Strings.en.xlf
- src/MSBuild/Resources/xlf/Strings.es.xlf
- src/MSBuild/Resources/xlf/Strings.fr.xlf
- src/MSBuild/Resources/xlf/Strings.it.xlf
- src/MSBuild/Resources/xlf/Strings.ja.xlf
- src/MSBuild/Resources/xlf/Strings.ko.xlf
- src/MSBuild/Resources/xlf/Strings.pl.xlf
- src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
- src/MSBuild/Resources/xlf/Strings.ru.xlf
- src/MSBuild/Resources/xlf/Strings.tr.xlf
- src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
- src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
- src/MSBuild/XMake.cs
Loggers are required to work otherwise a build fails.  We want to distributed loggers in NuGet packages which means that the very first build would not be able to restore since loggers are added with a command-line option.
The `-logger` argument now accepts options after the class and assembly.  One new option is to make a logger optional meaning a message will be printed if the logger can't be created rather than failing the build.
Will supersede #4528  
We need to deploy a logger via NuGet that collects telemetry for improving the inner loop developer experience.
No
Low risk.
New unit tests
> Add new logger options functionality

- src/Tasks/ResourceHandling/MSBuildResXReader.cs
Add special cases in build-time resource embedding for the resource types `byte[]` and `MemoryStream`. Fixes #4581.
Enable `StronglyTypedResourceBuilder` when running on .NET Core and ensure that projects built using the .NET Core codepath get code generated using the expected types for resources. Fixes #4588, fixes #2272.
Accessing some resources would throw an exception at runtime instead of returning a resource of type `byte[]` or `MemoryStream`.
Projects affected by either problem would have to workaround by:
1. Build using desktop `MSBuild.exe`, not `dotnet build`
2. Explicitly disable the new .NET Core resource-handling codepath in the projects.
Regression from .NET Framework functionality; bugs in features new to crossplatform .NET Core MSBuild.
Low--impacts only the new resource …
> ResXFileRef special cases

- src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
- src/Tasks.UnitTests/ResourceHandling/MSBuildResXReader_Tests.cs
- src/Tasks/GenerateResource.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/ResourceHandling/BinaryFormatterByteArrayResource.cs
- src/Tasks/ResourceHandling/FileStreamResource.cs
- src/Tasks/ResourceHandling/IResource.cs
- src/Tasks/ResourceHandling/LiveObjectResource.cs
- src/Tasks/ResourceHandling/MSBuildResXReader.cs
- src/Tasks/ResourceHandling/NameUtilities.cs
- src/Tasks/ResourceHandling/StringResource.cs
- src/Tasks/ResourceHandling/TypeConverterByteArrayResource.cs
- src/Tasks/ResourceHandling/TypeConverterStringResource.cs
- src/Tasks/system.design/stronglytypedresourcebuilder.cs
This regressed (#4582) with #4420, because the (untyped, .NET 1.0) `Dictionary` passed to `Create` never contained `ResXDataNode`s any more, but the new type `LiveObjectResource` that holds live deserialized objects in memory.
~This fixes _only_ the full-framework scenarios that use `$(GenerateResourceUsePreserializedResources)=false`. When building for .NET Core with the default settings, or _using_ .NET Core to build, `StronglyTypedResourceBuilder` still doesn't work (#2272).~
Enable `StronglyTypedResourceBuilder` when running on .NET Core and ensure that projects built using the .NET Core codepath get code generated using the expected types for resources. Fixes #4588, fixes #2272.
Projects that used `ResXFileCodeGenerator` could fail to compile due to generated code losing type …
> StronglyTypedResourceBuilder output should be strongly typed

- src/Tasks.UnitTests/ResourceHandling/MSBuildResXReader_Tests.cs
- src/Tasks/ResourceHandling/MSBuildResXReader.cs
Fixes #4634
Handle the special type `ResXNullRef` in the new .NET Core-compat resource handling. Fixes #4634.
Some `.resx` files caused exceptions at runtime rather than returning `null` as a resource.
Regression from .NET Framework functionality; bugs in features new to crossplatform .NET Core MSBuild.
Low--impacts only the new resource codepaths.
> Support ResXNullRef in MSBuildResXReader

- src/Tasks.UnitTests/ResourceHandling/MSBuildResXReader_Tests.cs
- src/Tasks/ResourceHandling/MSBuildResXReader.cs
This builds on #4588; the only new change is 8c2ff60, but I wanted to expand on the newly-extracted `IsString()`.
https://github.com/rainersigwald/msbuild/compare/StronglyTypedResourceBuilder-ResXDataNode...permissive-string-types
Support more assembly-qualified names for `string` in `.resx` files.
Some legacy `.resx` files created with .NET 2.0 type references caused exceptions at runtime rather than returning strings.
Regression from .NET Framework functionality; bugs in features new to crossplatform .NET Core MSBuild.
Low--impacts only the new resource codepaths.
> Permissive string types

- src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
- src/Tasks/GenerateResource.cs
Fixes #4553, an issue where a build would fail with a (correctly emitted) MSB3822 error, but subsequent builds would succeed, producing corrupted outputs without all of the resources embedded.
Fixes an error that would cause builds to fail and pass apparently randomly, while silently producing bad output when the build passed.
Bug in new functionality introduced by .NET Core resx support for non-string types. Desktop MSBuild building desktop projects did not regress.
Low. Impacts only the new resx codepath and uses an existing delete-or-warn function.
> Improve incremental behavior on MSB3822

- src/Build/Logging/BinaryLogger/BinaryLogger.cs
- src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
- src/MSBuild.UnitTests/XMake_Tests.cs
- src/Shared/Traits.cs
Fixes an issue where binary logs omits all project project import events.
Restores expected binary logger behavior improving customer's ability to debug and our ability to help customers.
Yes introduced by https://github.com/microsoft/msbuild/pull/4485
Low
-------------------
Fixes https://github.com/microsoft/msbuild/issues/4631
LogProjectImports is modified to always pull from environment instead of caching. This is due to the environment variable itself potentially being modified within msbuild.exe.
> LogProjectImports no longer cached

- .vsts-dotnet.yml
Branches we've been using to examine VS Insertions have typically been prefixed with `exp/` (short for experimental). This change essentually adopts the `exp/` prefix as our format for automatically triggering VS insertions to measure performance.
> Enable automatic VS-insertions when on experimental branches

- .vsts-dotnet.yml
Collect OptProf profiles from the d16.3 branch, now that we have had the final snap to that branch internally.
Improved performance due to ngen optimizations. Ability to continue inserting MSBuild into VS.
No, expected infrastructure change as part of the release process.
Low.
> Point to d16.3 channel for OptProf data collection

- src/Build/BackEnd/BuildManager/BuildParameters.cs
When I added the `DiscardBuildResults` flag to `BuildParameters`, I forgot to add it to the `Clone` method. So the flag is lost in the `BuildManager` since the first thing it does is clone the parameters. Also added a comment to the effect that we do not serialize this to the nodes since it's not applicable there.
> Fix copying of DiscardBuildResults flag for BuildParameters

- src/Tasks.UnitTests/ResourceHandling/ResGen_Tests.cs
VersionLatest looks at an earlier version of the .NET SDK: the last version we want to be installed is in Latest instead, so I changed to that in our tests.
> Updated versioning in resgen tests

- src/Tasks.UnitTests/CreateCSharpManifestResourceName_Tests.cs
- src/Tasks/CreateManifestResourceName.cs
Fix #4695, build failures that arise when a `.resx` file does not specify `DependentUpon` and is in a subfolder.
Builds fail with `MSB3041`. Impacts EF migrations (aspnet/EntityFramework6#1225), some WinForms projects, and some plain-vanilla projects.
Users can explicitly opt out of the new behavior back into preview8 behavior with a property
```xml
<EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
```
Or explicitly specify `DependentUpon` for all resources:
```xml
<ItemGroup>
<EmbeddedResource Update="Migrations\*.resx">
<DependentUpon>%(FileName).cs</DependentUpon>
</EmbeddedResource>
</ItemGroup>
```
Yes, builds fail in cases that passed before. Introduced with #4597, a new feature to support resources without project-file impact.
Automated …
> Support convention-based DependentUpon for resx files in folders

- Directory.Build.props
- eng/Versions.props
- src/Package/MSBuild.VSSetup/files.swr
NGen msbuild assemblies twice. Once for vsn.exe and once for msbuild.exe, so that both these processes can load ngened assemblies independently of them referencing dlls that are different between these processes.
MSBuild assmeblies in VS are being jitted, causing performance regressions in VS. In some of the tests, there was a 10% total time regression attributed to jitting.
None.
Yes. MSBuild took dependencies on new assemblies, which caused some of its dlls to be jitted as loading the ngened version of the dlls failed due to conflicts between VS versions of these new dlls and msbuild's.
Create a private build with these changes, inserted into VS and ran RPS tests against it. Insertion test PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/201435?_a=overview.
Improvement in …
> Ngen twice

- .vsts-dotnet.yml
A case difference between `Microsoft` and `microsoft` is failing builds that attempt to consume OptProf data (published to `Microsoft) from a build that thinks it's connected to `microsoft`. Hard-coding the capitalized version.
Fixed builds for VS and SDK insertion.
Yes, this worked until something changed and caught up to the lower-case name.
Minimal. This hard codes a case-munged copy of the repo name that would have been provided for all internal builds. The URL `https://github.com/Microsoft/msbuild` should keep working with GitHub redirects.
> Hard code RepositoryName=Microsoft/msbuild

- eng/Versions.props
We shouldn't merge this until we're ready, as every change after that will require a manual version bump.
> Release branding for 16.3

- src/Directory.Build.targets
This situation can occur on fresh VS 16.3 installs, which install the .NET 4.8 SDK
but don't yet have #4690 and so still look for tlbimp in the .NET 4.6.2 SDK.
> Better error when tlbexp isn't found

- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
- src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
(Looked this up when poking around near #4687, but it's not a fix)
From the internal bug
http://vstfdevdiv:8080/DevDiv/Dev10/_workitems/edit/564085
(December 19, 2009)
> The issue here is the new requirement to automatically add an explicit
reference to mscorlib for C# projects. When doing so, the reference
resolution considers files in the "CandidateAssemblyFiles" set which
includes those items in the project that are to be copied to the output
location.
> The solution here is to pre-resolve the mscorlib path and pass that to
RAR rather than an unresolved assembly name.
> Clarify comment on _ExplicitReference

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/Copy_Tests.cs
- src/Tasks/Copy.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
When ErrorIfLinkFails is set, we error if a symbolic link or hard link fails. We also error if ErrorIfLinkFails is set without specifying we should use symbolic or hard linking for Copy tasks.
Addresses #4433.
> Adds ErrorIfLinkFails attribute for Copy Tasks.

- src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
- src/Build/Graph/ProjectGraph.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
Just cleanup: clarifying some documentation, validating some inputs, avoiding needless iterations.
> [Static Graph] ProjectGraph.GetTargetLists throws on invalid target names

- src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs
Fixes #4714 by not setting LastWriteTime on imported project files. Now that we know that this is an operation that can fail, it doesn't seem worth the risk to attempt to preserve the information.
MSBuild binlogs don't contain all the files they should, harming debuggability and our team's ability to support customers who encounter problems.
None after encountering it. Conceivably a user could update the LastWriteTime on all of their installed SDK files, but they'd have to know to do it.
MSBuild has never been able to log these files, but that had never been noticed before NuGet/NuGet.Client#2989 started setting the dates on packaged files to near the critical time. It's a regression in the overall SDK experience.
Validated fix using local build.
Low. Removes a possibly-failing operation.
> Stop setting LastWriteTime for binlog imports

- src/Build/Evaluation/Expander.cs
Fixes #4615
Does not fix the larger issue #1155, calling instance methods on metadata.
> Prevent String::Copy property function from allocating

- src/MSBuild/XMake.cs
Fixes #4705 and #2005
Added an extra case to only display the message when no "/m" argument was specified. 
I'm adding WIP since I want to get some feedback first! 
I didn't create an unit test for it (yet) as this is deeply hidden inside of the `MSBuild.Execute` and I'm still thinking about the best way to proceed. 
One of the options I'm thinking about is to change the signature of `ProcessMaxCPUCountSwitch` to return a `Tuple<int, bool>` or add a new `out bool found` parameter.  
Another option is to extract the whole if statement to a seperate method.
> Prevent maxcpucount warning when /m argument has been specified

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
- src/Shared/UnitTests/App.config
This setting matches the .NET 4.8 behavior when running in FIPS mode.
Closes #4750.
> UseLegacyFipsThrow=false

- src/Build.UnitTests/Graph/IsolateProjects_Tests.cs
- src/Build.UnitTests/Graph/ResultCacheBasedBuilds_Tests.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
- src/Build/BackEnd/Components/Scheduler/Scheduler.cs
- src/Build/BackEnd/Shared/BuildResult.cs
Whenever I get a cache access error, almost all the time I have to debug into msbuild to see what the global properties where.
One fix to the problem is to parent the error under the msbuild task's logging context, so that it shows up in the bin log, under the task, as opposed to not showing up at all like it currently happens. This enables one to look at the global properties in the binlog.
Regarding the implementation, the main problem is getting the error message from the build manager node where the scheduler runs and issues the error, to the TaskHost that executes the msbuild task, which may be in a different process. Ideally, we'd need an official mechanism for ferrying these messages. Practically, I just piggy backed on the BuildResult. This seemed like the least intrusive change. …
> [Static Graph] Move cache miss error under task logging context

- src/Build.UnitTests/Evaluation/EvaluationLogging_Tests.cs
Failing test:
```
Microsoft.Build.UnitTests.Evaluation.EvaluationLogging_Tests.GivenOneProjectThereShouldBeOneStartedAndOneEndedEvent [FAIL]
Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages
The provided expression
should start with
"Evaluation started"
but was
"Property reassignment: $(MSBuildFrameworkToolsRoot)="\Microsoft.NET\Framework\" (previous value: "/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono") at "
Stack Trace:
at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T] (T actual, System.Func`2[T,TResult] specifiedConstraint, System.Object originalActual, System.Object originalExpected, System.Func`1[TResult] customMessage, System.String …
```
> [tests] Fix Evaluation logging test which broke on mono

- src/Shared/UnitTests/ObjectModelHelpers.cs
In the object model helper test, if the expected array is null, and the other one is null, the test will then compare their contents. This is not supposed to happen, as the comment clearly states "Now that we verified the arrays are nonnull and equal in length..."
Had to do a logic fix there.
> Fix possible null dereference pointer in test

- eng/Packages.props
- eng/Version.Details.xml
- eng/Versions.props
Drop darc/maestro-updated reference to System.Resources.Extensions since it's now public.
> Reference RTM version of 3.0

- eng/common/templates/post-build/channels/netcore-dev-30.yml
- eng/common/templates/post-build/channels/netcore-dev-31.yml
- eng/common/templates/post-build/channels/netcore-dev-5.yml
- eng/common/templates/post-build/channels/netcore-internal-30.yml
- eng/common/templates/post-build/channels/netcore-release-30.yml
- eng/common/templates/post-build/channels/netcore-release-31.yml
- eng/common/templates/post-build/channels/netcore-tools-latest.yml
- eng/common/templates/post-build/channels/public-validation-release.yml
Currently we cannot publish assets from a build in devdiv to a feed in dnceng. We need this change to unblock builds while dotnet/arcade#3942 is fixed and publish to blob feeds in the meanwhile.
> Workaround to unblock builds

- src/Tasks.UnitTests/CreateCSharpManifestResourceName_Tests.cs
- src/Tasks/CreateManifestResourceName.cs
Fix #4740, build or runtime failures that arise because non-resx resources get embedded with an unexpected name.
Builds fail with `CS1508` or applications fail to extract a resource at runtime. Roadblock to adopting the final 3.0 SDK and to migrating to .NET Core 3.0 for applications with embedded resources (UI applications in particular).
Reported by multiple internal partners (CoreFX, EF) and customers.
Users can explicitly opt out of the new behavior back into preview8 behavior with a property
```xml
<EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
```
Yes, builds fail in cases that passed before. Introduced with #4597, a new feature to support (resx) resources without project-file impact.
Automated tests, including a new one for this …
> Apply DependentUpon Convention Only to .resx Files

- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/SolutionProjectGenerator.cs
Fixes #4692 by ensuring that the targets that will be created exist at evaluation time, too.
> Allow Before/AfterTargets for dynamic sln targets

- eng/Versions.props
- src/Shared/NodeEndpointOutOfProcBase.cs
If a worker closed between when it sent information and when it received it, it crashed MSBuild. This turns a fatal exception into a clean error message. Fixes #4768
> Unhandled exception when pipe to worker node closes suddenly

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/enable-cross-org-publishing.ps1
- eng/common/sdl/extract-artifact-packages.ps1
- eng/common/templates/post-build/channels/netcore-3-tools-validation.yml
- eng/common/templates/post-build/channels/netcore-3-tools.yml
- eng/common/templates/post-build/channels/netcore-dev-31.yml
- eng/common/templates/post-build/channels/netcore-dev-5.yml
- eng/common/templates/post-build/channels/netcore-internal-30.yml
- eng/common/templates/post-build/channels/netcore-release-30.yml
- eng/common/templates/post-build/channels/netcore-tools-latest.yml
- eng/common/templates/post-build/channels/netcore-tools-validation.yml
- eng/common/templates/post-build/common-variables.yml
- eng/common/templates/post-build/post-build.yml
- global.json
It appears that official builds were succeeding after #4733 only because of a coincident service outage, so updating to the latest arcade bits for publishing is likely required to support servicing 16.3.
Most of the breaking changes in #4783 are a result of the SDK update rather than Arcade changes, so this PR reverts the SDK while updating Arcade.
> [vs16.3] Arcade update for servicing

- eng/common/templates/post-build/channels/netcore-release-30.yml
Work around dotnet/arcade#4087 by hardcoding the repo name in the one channel relevant to 16.3 servicing.
> Hardcode channel-publish repo name

- .vsts-dotnet.yml
Should fix [this error in our official build](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3128260&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=13896748-c84b-5918-2517-67b7d331a1d1&l=25):
```
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19502.6\tools\Tools.proj(0,0): error : Version 3.0.100 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
```
> Switch to VS2019 queue for official build

- src/Package/MSBuild.VSSetup/files.swr
Props file initiates the wrong version.
Fixes #4728.
Successful VS insertion:
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/207287?_a=overview
> Deliver v16 props file in VSIX

- documentation/wiki/Providing-Binary-Logs.md
Change `/bl` to `-bl` to follow other places where `/` was replaced with `-` in help texts and documentation.
@dotnet-bot skip ci
> Minor binlog doc change

- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/SolutionProjectGenerator.cs
Implementation of https://github.com/microsoft/msbuild/issues/4784 
For the generated metaproj project this imports a file named `Directory.Solution.props` at the top and a file named `Directory.Solution.targets` at the bottom.
This allows users to create a single file that lets them extend the building of all solution files in their repository.
> Implementation of Directory.Solution.props and Directory.Solution.targets

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks/CreateCSharpManifestResourceName.cs
- src/Tasks/CreateManifestResourceName.cs
- src/Tasks/CreateVisualBasicManifestResourceName.cs
Fix for #4759 
Allow users to override the default source file extension
> Changing source file extension to protected in CreateManifestResourceName

- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/SolutionProjectGenerator.cs
Fixes #4811 by switching to the concrete implementation type for the `_defaultTargetNames` set.
As `ISet<T>`, the overload resolved for Union was from Linq and did not respect the left-hand
set's comparer. By moving the field to the concrete `ImmutableHashSet<T>` type, the overload
from that type is used, which does use the collection's comparer (case-insensitive).
When the target names are correctly unioned, the null-reference exception is avoided, because
the dummy target is removed only once, instead of twice (throwing NRE on the second time).
> Allow case-varying solution targets

- src/Tasks.UnitTests/ResourceHandling/MSBuildResXReader_Tests.cs
- src/Tasks/ResourceHandling/MSBuildResXReader.cs
Fixes #4773 by treating string and MemoryStream types as a prefix match on the mscorlib identity,
hoping to more closely match `Type.GetType`'s behavior.
> Permissive MemoryStream typename

- src/MSBuild/Microsoft.Build.CommonTypes.xsd
> Adding xsd properties for AssetTargetFallback and Nullable.

- src/Directory.Build.targets
- src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
- src/Tasks/GenerateResource.cs
- src/Tasks/ResourceHandling/InputFormatNotSupportedException.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Closes #308 by re-enabling the tests.
> Restore write-resource-to-text tests

- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Directory.BeforeCommon.targets
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
- src/Tasks.UnitTests/XslTransformation_Tests.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
- src/Tasks/XslTransformation.cs
Fixes #3368 
XslTransformation was ported over to .NET Core. though any functionality having to do with compiled DLLs had to be cut. This functionality is locked behind the flag: `FEATURE_COMPILED_XSL` which is defined under non-mono builds.
> Port XslTransformation to .NET Core

- src/Shared/UnitTests/MockEngine.cs
- src/Tasks.UnitTests/VerifyFileHash_Tests.cs
- src/Tasks/FileIO/VerifyFileHash.cs
Call `LogErrorWithCodeFromResources` so that the `Code` property is set in the `BuildErrorEventArgs` object
Also updated unit test and `MockEngine` to store build events for more in depth validation
Fixes #4851
> Fix VerifyFileHash error logging

- src/Tasks/Microsoft.Common.CurrentVersion.targets
If the platform target is explicitly set to x86, it sets the MSBuild architecture to the same. It then passes over the real problem when using dotnet build and returns a confusing error message instead. Fixes #4332.
> Fix error message

- src/Directory.Build.props
Ensure that compiler errors emit full paths so that files
can be correctly annotated in GitHub.
For example:
> GenerateFullPaths

- eng/Versions.props
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
In the VS repo, some projects attempted to import based on $(MSBuildToolsVersion), and got confused in the '15.0 package with the 16.3 engine' situation.
The right long-term fix is to move to 16.x packages, but for now we can just duplicate this file; all other files seemed to be loaded from the right folders automatically.
This unblocks #4823. @duncanmak and I have been using it in private testing and it looks good.
> Add Microsoft.Common.props in Current to CoreXT overlay

- .vsts-dotnet.yml
Builds prefixed with `exp/` use `master` for their `IbcSourceBranchName`
Builds NOT prefixed with `exp/` use the default `IbcSourceBranchName` (which is the branch name itself).
With this change inserted, branches prefixed with `exp/` will no longer fail because of optprof data not existing for that branch.
Yay automation!
> Completely automate experimental branch builds

- src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
solved ticket number #331 
if test platform is windows then the return is tested.
> applied platform specific attribute to avoid unnecessary test execution

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build.UnitTests/Evaluation/SimpleVersion_Tests.cs
- src/Build/Evaluation/Expander.cs
- src/Build/Evaluation/IntrinsicFunctions.cs
- src/Build/Microsoft.Build.csproj
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/Build/Utilities/SimpleVersion.cs
Usage: 
```
$([MSBuild]::VersionEquals(a, b))
$([MSBuild]::VersionNotEquals(a, b))
$([MSBuild]::VersionLessThan(a, b))
$([MSBuild]::VersionLessThanOrEquals(a, b))
$([MSBuild]::VersionLessThan(a, b))
$([MSBuild]::VersionGreaterThanOrEquals(a, b))
```
Versions are parsed like System.Version, with the following exceptions:
* Leading v or V is ignored. Allows comparison to $(TargetFrameworkVersion)
* Everything from first '-' or '+' to end of string is ignored. Allows passing in semantic versions, though the order is not the same as semver. Instead, prerelease specified and build metadata do not have any sorting weight. This can be useful, for example, to turn on a feature for >= x.y and have it kick in on x.y.z-pre.
* Remaining part of string from above is parsed with Version.Parse, then …
> Add intrinsic property function to compare versions

- src/Shared/CommunicationsUtilities.cs
Prevent unwanted node reuse.
Fixes #3137.
> Include path to MSBuild in node handshake salt

- .vsts-dotnet-ci.yml
- eng/cibuild_bootstrapped_msbuild.ps1
Example output: https://dev.azure.com/dnceng/public/_build/results?buildId=432144&view=results
Not sure why that didn't push checks annotations except from the *nix legs that were already working, but it appears to annotate the errors correctly in AzDO.
> Enable Arcade Pipelines logging in Windows builds

- src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
- src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
- src/Build/BackEnd/Components/Communications/LogMessagePacket.cs
- src/Shared/AssemblyLoadInfo.cs
- src/Shared/TypeLoader.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
- src/Shared/UnitTests/TypeLoader_Dependencies_Tests.cs
- src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
This is a collection of small things I discovered while implementing/testing/debugging #4916. Pulling into their own separate review to not distract from the important feature there.
> Diagnosability refactoring

- src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
- src/Shared/ThreadPoolExtensions.cs
- src/Shared/UnitTests/FileUtilities_Tests.cs
Noticed these while looking at `AssemblyLoadContext` implementation.
> Small fixes in TaskHostConfiguration_Tests.cs

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
- ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
- src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
- src/Build.UnitTests/BackEnd/TaskHost_Tests.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
- src/Build/Instance/TaskFactories/TaskHostTask.cs
- src/Framework/IBuildEngine6.cs
- src/MSBuild/OutOfProcTaskHostNode.cs
- src/Shared/TaskHostConfiguration.cs
- src/Shared/UnitTests/MockEngine.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
- src/Utilities/Task.cs
This is an implementation of https://github.com/microsoft/msbuild/issues/4925 which allows tasks to get the current project's global properties.
I added an `IBuildEngine6` and plumbed the global properties to the appropriate task hosts.
> Implement feature that allows tasks to get the global properties

- src/Tasks.UnitTests/Unzip_Tests.cs
- src/Tasks/Unzip.cs
Ensure that directory entries in zip archives are not attempted to be created as files. Only file entries (and their parent directories) will be created.
Currently using the `<Unzip/>` task with an archive containing directories will fail trying to `File.Open` on a directory.
```
error : Access to the path '/Users/USER/stuff/internalzipdir/' is denied.
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at …
```
> Ensure directory entries in zips are not created

- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
- src/Tasks/Microsoft.Common.CurrentVersion.targets
This allows the property to be set within a project file without its value being replaced by the imported .targets at the bottom. Particularly in SDK style projects where properties cannot be set after the imported .targets file, this unblocks a key scenario.
> Don't stomp on *DependsOn properties

- src/Shared/InterningBinaryReader.cs
- src/Shared/OpportunisticIntern.cs
- src/Shared/TaskLoggingHelper.cs
- src/Tasks/AssemblyDependency/AssemblyInformation.cs
- src/Tasks/AssemblyDependency/Reference.cs
- src/Tasks/AssignCulture.cs
- src/Tasks/RegisterAssembly.cs
- src/Tasks/ResolveNativeReference.cs
- src/Tasks/UnregisterAssembly.cs
At some point we stopped defining _DEBUG for debug builds, so all this conditional code was never being built.
```sh-session
$ rep -r "#if _DEBUG" "#if DEBUG" *.cs
1993 files processed. 9 files changed. 14 replacements.
```
> Enable lost debug-only code

- src/Shared/CommunicationsUtilities.cs
Use a directory path for the MSBuild "installation" instead of path-to-folder-of-current-assembly to normalize for the `bin`/`bin\amd64` differences that may arise in a single logical installation.
Fixes #4957
> Use MSBuildToolsDirectory32 in node handshake communication

- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/Microsoft.Managed.targets
Fixes #4677 
Fixes #1054
This turned out to be more complicated [than it should be](https://github.com/microsoft/msbuild/issues/4677#issuecomment-529662821) in order to maintain backwards compatibility with legacy behaviour (described in #4677). For example, quickbuild depends on this bug and fixing it will take some time and it's probably low priority, so the ability to pin the bad behaviour and fix later is sadly okay here.
Feedback needed on:
- the toggling property name and value. Right now it's `$(MSBuildCopyContentTransitively )` [where](https://github.com/microsoft/msbuild/compare/master...cdmihai:contentCopying#diff-02872751bc64e0ff785c9b6c1cd919b5R4438-R4441) `true` means transitive, `false` means 1-level copying, nothing means legacy (which should be the same as `false`). Would …
> Force content copying to either be recursive, 1-level, or legacy

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Previous functionality had hardcoded strings such as `Successfully launched msbuild.exe node with PID {0}`, even when using `MSBuildTaskHost.exe`. This PR changes these strings to `Successfully launched {1} node with PID {0}` where {1} is whatever the current process is.
> Node tracing uses correct exe name

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Pairs with https://github.com/dotnet/wpf/issues/2287 to fix https://github.com/microsoft/msbuild/issues/4963
Fixed the _**incredibly complicated**_ boolean logic issue that prevented _GenerateCompileDependencyCache from running at all for builds (which is when it should be running)
> Fix Incremental Builds (_GenerateCompileDependencyCache)

- src/Tasks.UnitTests/DownloadFile_Tests.cs
- src/Tasks/DownloadFile.cs
The check as to whether a file has changed compares time stamps, but returns that a file has not changed from the original if its time stamp is before when the original was last modified. This is the opposite of the desired behavior.
Fixes #4860
> Permit DownloadFile to skip unchanged files Fixes #4860

- eng/BootStrapMSBuild.targets
The second-stage build was intermittently failing on Linux because NuGet's
solution-restore logic wasn't being used. It wasn't being used because it
depends on being placed in `SolutionFile/ImportAfter`, but it wasn't being
copied from the last-known-good SDK to the bootstrap folder.
Fixes #4971 by copying `Current\**` (except the might-have-been-updated
`Microsoft.Common.props` which is already there) into the bootstrap folder
on Core.
> Copy in-SDK MSBuild extensions to bootstrap

- eng/cibuild_bootstrapped_msbuild.sh
Inside the CI script, we were specifying `debug` as the configuration, but in
the YAML we copied up the `Debug` directory. That worked because somewhere in
the guts of things, test logs got emitted to `Debug`, but didn't actually
capture the build log. Specifying with a capital letter should put everything
in the same folder for happy upload.
> Normalize on Debug case for CI script

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/Instance/ProjectInstance_Internal_Tests.cs
- src/Build/Instance/ProjectInstance.cs
Currently the only reason QuickBuild and [MSBuildPrediction](https://github.com/Microsoft/MSBuildPrediction) use `Project` instead of `ProjectInstance` is because imports are not exposed through the `ProjectInstance`. This would allow both to avoid `Project` and use `ProjectInstance` directly.
Note that I decided to just expose full paths and not the `ResolvedImport` because `ResolvedImport` is not currently translatable as it contains a pretty deep object graph which also isn't translatable. Instead of implementing `ITranslatable` on a whole bunch of stuff (including XML...), I decided to simplify and only expose the full file paths.
> Expose project imports on ProjectInstance

- eng/cibuild_bootstrapped_msbuild.ps1
Avoids errors like:
```
Cannot create a file when that file already exists.
System.IO.IOException: Cannot create a file when that file already exists.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.DirectoryInfo.MoveTo(String destDirName)
at Microsoft.PowerShell.Commands.FileSystemProvider.MoveDirectoryInfoItem(DirectoryInfo directory, String destination, Boolean force)
at <ScriptBlock>, E:\projects\test-msbuild\eng\cibuild_bootstrapped_msbuild.ps1: line 109
```
> Bootstrap build: Remove directory before moving to avoid IO exception

- .vsts-dotnet.yml
This works around any future recurrence of dotnet/arcade#2531 by
giving us symbols to manually upload if we have to.
> Upload symbols in official build

- documentation/specs/task-isolation-and-dependencies.md
- src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
- src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
- src/Build/Microsoft.Build.csproj
- src/Directory.BeforeCommon.targets
- src/MSBuild.UnitTests/ValidateAssemblyLoadContext.cs
- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/MSBuild.csproj
- src/Shared/AssemblyNameExtension.cs
- src/Shared/CoreCLRAssemblyLoader.cs
- src/Shared/MSBuildLoadContext.cs
- src/Shared/TaskEngineAssemblyResolver.cs
- src/Shared/TypeLoader.cs
- src/Tasks/AssemblyDependency/AssemblyInformation.cs
- src/Tasks/GenerateResource.cs
Use `AssemblyLoadContext` and the new `AssemblyDependencyResolver` to allow task implementations to have independent, incompatible dependencies on .NET Core.
Follows the spec from #4133 and the [tutorial on creating .NET Core plugin hosts](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support).
Since `AssemblyDependencyResolver` is a .NET Core 3.0 type, required targeting .NET Core 3.0.
Fixes #1754 (task ALC)
Fixes #4635 (logger ALC)
> Load plugins in an AssemblyLoadContext

- src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
- src/Shared/Traits.cs
- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Move the environment variable read to Traits and cache it. Otherwise we would read the environment every time a task is run.
Fixes https://github.com/microsoft/msbuild/issues/4956
From cursory glance there is nothing in the manual `LogInputs()` method that wouldn't be logged automatically. If we are missing something it's probably nothing substantial.
> Don't log RAR task inputs manually when LogTaskInputs is set.

- src/Build/BackEnd/Components/Scheduler/Scheduler.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
This reduces the time needed to debug `/isolate` errors. The errors would look like this:
> Log global properties in cache miss error

- eng/AfterSigning.targets
- src/MSBuild/MSBuild.csproj
fixes #5060 
This fixes our symbol check failures on our VS PRs by copying over the relevant `.pdb`s to where they need to be to get published during a pipeline build.
> Publish x64 Architecture Symbols

- src/Build.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build/Construction/Solution/SolutionFile.cs
Currently F# SDK-style projects are treated at `SolutionProjectType.Unknown`. This is PR fixes this and treats them as `KnownToBeMSBuildFormat`.
> Add CPS F# project type GUID

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
Turns out the shortcut in Expander for evaluating IntrinsicFunctions.Add, IntrinsicFunctions.Multiply and String.PadLeft wasn't working as expected. Under some conditions we can end up with an array of args where the first arg is a boxed double and the second one is a string.
By following the pattern with TryConvertToInt I introduce TryConvertToDouble. Also use TryConvertToInt in another place which fixes another case.
I've added unit-tests for the scenarios I encountered.
With these changes, there are no more first-chance exceptions when evaluating MSBuild's own solution. The three first-chance exceptions were observed when evaluating:
https://github.com/dotnet/arcade/blob/cc596c55ac68c952d0e052e6ed50334ed170b53a/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L6 …
> Fix Expander.TryExecuteWellKnownFunction for Add, Multiply and PadLeft.

- src/MSBuild/XMake.cs
When playing back a .binlog with using -distributedfilelogger there was a crash because CentralLogger was null.
Fixes https://github.com/microsoft/msbuild/issues/4788
> Fix nullref in binlog playback when CentralLogger is null

- src/Tasks/AppConfig/AppConfig.cs
Fixes https://github.com/microsoft/msbuild/issues/4335
> Normalize the path before opening an app.config file.

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
- src/MSBuild/XMake.cs
- src/Tasks/AppConfig/AppConfig.cs
This is just cherry-picks of #5029, #5028, and #5023, which I merged without realizing that they were targeted to `master` rather than the intended `vs16.5`. Sorry @KirillOsenkov!
> Backport stuff mistargeted to 16.6

- src/Build.UnitTests/BackEnd/AssemblyLoadContextTestTasks.cs
- src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
- src/Shared/CoreCLRAssemblyLoader.cs
Fixes #5080 by normalizing plugin assembly paths before deduplicating
loads based on those paths.
Does not fix the cross-assembly register/retrieve object problem #5084.
> Normalize plugin paths before loading

- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/AssignProjectConfiguration_Tests.cs
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
- src/Tasks.UnitTests/ResolveNonMSBuildProjectOutput_Tests.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
This task isn't required in normal operation on .NET Core, but
compiles and runs just fine so there's no reason to have a discrepancy.
Fixes #4770.
> Enable ResolveNonMSBuildProjectOutput on .NET Core

- src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
- src/Tasks/BootstrapperUtil/Util.cs
We want teams to be able to install bootstrapper packages from outside the VS MSIs where they currently come from.  Right now we only enumerate packages from a single directory that's defined in the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\GenericBootstrapper reg key.  I'm making it so if there's any additional paths specified under the AdditionalPackagePaths sub key we'll look for bootstrapper packages in those paths as well.
One small issue with this change is that when a bootstrapper specified in a clickonce or setup project isn't found we give a warning like this:
_Item '.NETFramework,Version=v4.7.2' could not be located in 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce Bootstrapper\'_
Ideally this would be updated to also mention any possible additional paths that have been specified …
> Updating BootstrapUtil to look for packages in additional folders

- src/Shared/EncodingUtilities.cs
- src/Shared/Traits.cs
- src/Tasks.UnitTests/Exec_Tests.cs
- src/Tasks/Exec.cs
- src/Utilities.UnitTests/ToolTask_Tests.cs
- src/Utilities/ToolTask.cs
Fix #4904 using the same detect-and-switch-codepage code as we use in `Exec`.
> Detect and switch to UTF-8 codepage in ToolTask with UseCommandProcessor

- src/Package/MSBuild.VSSetup/files.swr
Add an explicit list of MSBuild assemblies that might be loaded by an
application outside of the Visual Studio installation directory, so that
VS Setup can find any applications using these files and shut them down
before updating VS.
Closes #5025.
> vs.relatedProcessFiles for MSBuild assemblies

- src/Shared/CoreCLRAssemblyLoader.cs
- src/Shared/MSBuildLoadContext.cs
- src/Shared/Traits.cs
- src/Shared/TypeLoader.cs
Restore the original load-with-funky-rules-into-the-default-ALC behavior under an environment-variable escape hatch. Fixes #5086.
This looks like a lot of code, but it's almost all just undeletions. I cherry-picked the change on top of the existing ALC changes, so you can see that more clearly: https://github.com/rainersigwald/msbuild/compare/alc-escape-hatch-base...rainersigwald:alc-escape-hatch-cleanerdiff?expand=1
Compare that to the diff in #4916 to see that it makes it look like this is just adding functionality.
> Add an escape hatch for ALC isolation

- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
- src/Framework/MSBuildEventSource.cs
This creates a new eventsource pair: ExecuteTaskStart and ExecuteTaskStop. Together, they allow a user to see the name of a task and how long it took to execute (including exact start and stop time) for each task. Another pair is added to capture how long each of yield and reacquire takes (if relevant).
> Introduce ExecuteTask ETW

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
Should enable https://github.com/microsoft/msbuild/pull/5007 to log places where msbuild searches for command line arguments.
> Enable logging messages created before BuildManager.BeginBuild

- eng/cibuild_bootstrapped_msbuild.sh
- src/Tasks.UnitTests/DownloadFile_Tests.cs
- src/Tasks/DownloadFile.cs
We have some builds that are calling the DownloadFile task, and they seem to be
silently misbehaving: no errors, just hangs for a few hours and then we have to kill the process.
Looking at the code, there are a few paths through the code that result in either infinite loops or silently downloading nothing and returning success.
In particular, if a server returns a failed response, like a 500, and then the task is cancelled, it enters an infinite loop, because canRetry isn't refreshed in the loop.
Also, if a request times out the first time, where HttpClient.Send throws an OperationCanceledException, the task returns success without downloading anything.
I added tests for these two cases, and they fail without this change.
Hopefully this change is an acceptable one... I tried hard not to …
> DownloadFile behaves unexpectedly in the case of OperationCanceledExceptions

- src/Tasks.UnitTests/RegressionTests.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/microsoft/msbuild/issues/1479 as suggested in the issue description.
> Write generated AssemblyAttributes file to intermediate output path

- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/SolutionProjectGenerator.cs
Duplicate targets break the build; this prevents MSBuild's default targets from being added if they already exist.
Fixes #5071
> Prevent duplicate targets Fixes #5071

- Directory.Build.targets
Fixes #4988 
From what I can tell, this issue was caused due to arcade and msbuild both adding the same image.
> Removing nuget image on msbuild side

- src/Tasks.UnitTests/XamlTaskFactory_Tests.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
- src/Tasks/XamlTaskFactory/TaskParser.cs
Closes #75 
As far as I could observe, the only way to properly handle duplicate names is to die, because duplicate property names break code generation (code generator creates two fields with the same name), so I added the missing check and a new error message for this case.
> Fix TaskParser probably has a bug in switch de-duplication logic.

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Signed-off-by: Ilya Shipitsin <chipitsine@gmail.com>
> Avoid loading NuGet.targets if already loaded

- src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
- src/Build/BackEnd/Shared/BuildRequest.cs
- src/Tasks.UnitTests/MSBuild_Tests.cs
This is based on @MarkKharitonov's fix https://github.com/microsoft/msbuild/pull/4142 for https://github.com/Microsoft/MSBuild/issues/3939. Same change but rebases on latest and adds a unit-test.
@rainersigwald I've played with Mark's change and thought about it, and I think the best thing to do is to take Mark's change as is. I agree that it doesn't capture scenarios where a project's build is spawned via IBuildEngine* APIs and not via the MSBuild task, but we don't care about those as much. Even if we just cover the MSBuild task like this, it will be a huge improvement that covers most if not all scenarios that we really care about.
It's pretty low-risk and non-invasive. I've checked that in this expression:
```
issuingEntry.Request.CurrentMSBuildTask ?? …
```
> Pass MSBuild Task Id via project's ParentProjectBuildEventContext

- scripts/Deploy-MSBuild.ps1
- src/MSBuild/MSBuild.csproj
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
- src/Package/MSBuild.VSSetup/files.swr
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Microsoft.CSharp.targets
- src/Tasks/Microsoft.Managed.After.targets
- src/Tasks/Microsoft.Managed.Before.targets
- src/Tasks/Microsoft.Managed.targets
- src/Tasks/Microsoft.VisualBasic.targets
Quickbuild calls each project with `BuildProjectReferences=false`, which makes the main p2p target be `GetTargetPath` instead of the default (default target or the `ProjectReference.Targets`). This PR updates the target protocol for static graph to reflect this.
Unfortunately, Microsoft.Managed.targets was imported before the common targets which define `BuildProjectReferences`. So I split it up in before / after imports.
> Target protocol with GetTargetPath

- src/Shared/Traits.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
Fixes #4756 by adding TargetPath to the list of metadata that shouldn't
be forwarded to "child"/related files discovered in RAR.
Adds an escape hatch for the behavior since we're not completely sure
there isn't user code that depends on the (surprising) behavior.
> Don't propagate TargetPath to RAR related files

- src/Shared/BuildEnvironmentHelper.cs
Fixes #5151 by inserting amd64 into the path if run from a 64-bit process
and discovering MSBuild in a Visual Studio installation.
> Find amd64/MSBuild.exe when run from a 64-bit process

- src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
- src/Build/Definition/Project.cs
- src/Build/Evaluation/ItemSpec.cs
- src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.cs
- src/Shared/Traits.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
Resolves #[1655411 ](https://dev.azure.com/mseng/1ES/_workitems/edit/1655411), #[1649689](https://dev.azure.com/mseng/1ES/_workitems/edit/1649689)
This allows users to import and map metadata between two or more item types.
- Example:
```xml
<I Update="@(Foo);*.cs;@(Bar)" M1="%(Foo.M1)" M2="%(Bar.X2)">
<M3 Condition="'%(Foo.M3)'' == 'something' ">%(M1)</M3>
</I>
```
- Each matching item (i.e. each item that needs uptading) now carries a context of captured item instances from all matching referenced item types in the `Update` expression.
- Unqualified metadata (`%(M)`) binds to the operation item type (i.e. type that gets updated). Qualified metadata (`%(Foo.M)`) binds inside the set of captured item types from the `Update` expression.
- If an item matches multiple times within and …
> Allow qualified metadata references in the Update item operation

- eng/Packages.props
- src/Build.UnitTests/BackEnd/BuildResult_Tests.cs
- src/Build.UnitTests/BackEnd/EventSourceSink_Tests.cs
- src/Build.UnitTests/BackEnd/LoggingService_Tests.cs
- src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
- src/Build/BackEnd/Node/InProcNode.cs
- src/Directory.BeforeCommon.targets
- src/Framework/Microsoft.Build.Framework.csproj
- src/MSBuild/OutOfProcTaskHostNode.cs
- src/Shared/ExceptionHandling.cs
- src/Tasks/AppConfig/AppConfigException.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Utilities/Microsoft.Build.Utilities.csproj
While working on something else I noticed this old (.NET Core 1) feature flag that we don't need any more since we have the guarded APIs everywhere now.
> Remove FEATURE_VARIOUS_EXCEPTIONS

- src/Build/Definition/ProjectCollection.cs
We had worked around this issue last time in
https://github.com/mono/msbuild/commit/566653691020920c4dc9ddab218e699c8c68526c .
But fixing it this time, so that we don't hit it again.
Trace from the orignal commit:
```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
at System.String.Substring (System.Int32 startIndex, System.Int32 length) [0x00073] in /Users/radical/dev/mono/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:1626
at Microsoft.Build.Evaluation.ProjectCollection.get_DisplayVersion () [0x00026] in /Users/radical/dev/msbuild/src/Build/Definition/ProjectCollection.cs:474
at …
```
> Fix msbuild regression in version string, on mono

- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
- src/Tasks.UnitTests/CallTarget_Tests.cs
.. fails. The errors are logged by the targets invoked by `CallTarget`.
Fixes https://github.com/microsoft/msbuild/issues/5155 .
> Special-case CallTarget which doesn't return errors itself even when it

- src/Build/Instance/HostServices.cs
- src/Directory.Build.targets
- src/Package/GetBinPaths.targets
- src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
- src/Package/MSBuild.VSSetup/files.swr
This reverts commit 2d82e1a861d890fce68c8e2d42b569e5bbaf5687.
> Revert "Support host objects in 64-bit MSBuild (#5177)"

- documentation/wiki/Contributing-Code.md
- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build.UnitTests/BackEnd/ResultsCache_Tests.cs
- src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
- src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
- src/Build/BackEnd/Components/Caching/IResultsCache.cs
- src/Build/BackEnd/Components/Caching/ResultsCache.cs
- src/Build/BackEnd/Components/Caching/ResultsCacheWithOverride.cs
- src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
- src/Build/BackEnd/Components/Scheduler/Scheduler.cs
- src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
- src/Build/BackEnd/Shared/BuildResult.cs
- src/Build/BackEnd/Shared/TargetResult.cs
`BuildResult` had code in one of its constructors specifically to handle AfterTargets failures, making sure that they are propagated to the referenced target. This didn't work in multi-proc builds for multiple reasons:
1) The process orchestrating the build may have had no visibility into targets other than those requested to be executed by the worker process. This means that the `existingResults` argument typically didn't contain results for the targets with AfterTargets specified, meaning it had no way of knowing that they had failed.
2) The process orchestrating the build may not have loaded the project file handled by the worker process. This means that the `additionalTargetsToCheck` argument could have been `null`, again making it impossible for `BuildResult` to detect the …
> Don't swallow AfterTargets failures in multi-proc builds

- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
- src/Tasks.UnitTests/SGen_Tests.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
- src/Tasks/SGen.cs
The SGen task has not been implemented on .NET Core and building a project with `<GenerateSerializationAssemblies>` is failing with what looks like an infrastructure error.
This PR is adding an empty implementation of the task which throws a nicer error pointing the user to the build-time serialization mechanism supported on .NET Core - Microsoft.XmlSerializer.Generator. The changes here are analogous to how the ResolveComReference task has been implemented to allow erroring out on Core.
Fixes #3583
> Implement an empty SGen .NET Core task

- src/Build/Instance/ProjectItemInstance.cs
- src/Tasks.UnitTests/CreateItem_Tests.cs
The logic to decompress large target results was refusing to rehydrate project item metadata categorized as "item-specs". In particular, the `RecursiveDir` metadatum is explicitly set by the CreateItem task and falls into this category, causing the build to fail if certain conditions are met:
1. The build is out-of-proc.
2. The number of target results moved cross-proc meets the compression threshold.
It seems unnecessary to do elaborate validation on this codepath. We implicitly trust the serialized data. Fixing the issue by relaxing the checks so that compressed item-spec metadata can be deserialized.
Fixes #5225
> Don't fail deserialization of item-spec project item metadata

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
The previous fast path was only expecting the args of int and string, but was actually given int and char. So the fast path was not taken for expressions such as:
$(VersionSuffixBuildOfTheDay.PadLeft(2, $([System.Convert]::ToChar(`0`))))
Try to interpret int and char as int and string, this ensures the fast path is taken.
This fixes a first-chance MissingMethodException.
> Fast path when evaluating string.PadLeft(int, char)

- src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
- src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
- src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
This code is a very hot path (though only hit when LogTaskInputs is set).
There was an n^2 string concatenation problem alongside with other easily avoidable allocations.
Cache resource strings to avoid extracting them from resources every time.
Use a ThreadStatic field to avoid allocating an array every time.
Sorting key value pairs in place is 3x faster than LINQ OrderBy.
Remove an overload of GetParameterText that accepts params. Everyone calling it was calling an unnecessary ToArray().
Use List instead of IList to be able to call the overload that accepts IList.
> Reduce allocations in ItemGroupLoggingHelper.

- src/Shared/Traits.cs
- src/Tasks/Microsoft.WinFx.targets
Part 1 to fix https://github.com/microsoft/msbuild/issues/4948
Part 2 (sets the ImportWinFXTargets property to false): https://github.com/dotnet/sdk/pull/10998
This conditionally imports winfx.targets for all non-sdk style builds. Pairs with another PR for the sdk 
that ensures the condition will fall through.
> Don't import Microsoft.WinFX.targets for sdk style projects

- eng/Packages.props
- src/Build/Microsoft.Build.csproj
- src/Framework/Microsoft.Build.Framework.csproj
- src/Samples/Directory.Build.targets
- src/Tasks/Microsoft.Build.Tasks.csproj
Some NuGet packages (such as `System.Net.Http`) do not target .NET Standard 2.0 and reference tons of packages from older .NET Standard versions. The types they contain are already included in .NET Standard 2.0, so they were removed to unburden the package reference graph.
> Remove unnecessary NuGet package references.

- src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/Shared/Traits.cs
After a limit of 10k characters, stop logging task inputs.
Fixes https://github.com/microsoft/msbuild/issues/4907
cc: @rainersigwald @cdmihai How would we go about using a localized string instead of the hard-coded english one I used?
> Option to Truncate Task Input-Logging

- .vsts-dotnet.yml
Workaround for an apparent build-pool issue in the internal devdiv pool. Should be backed out ASAP.
> Add demand to try to force a different build machine

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Referenceassemblyresolver target does not contain properties to control finding of extra files.  This results in extra file accesses being done when they are not wanted simply because the file does not exist.  We would like the ability to turn this functionality off without setting BuildingProject to false as that has other implications for build logic.
> Add additional parameters to referenceassemblyresolver

- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
> Introduce timeout to prevent a hang in CancelledBuild

- src/Build/Instance/HostServices.cs
- src/Directory.Build.targets
- src/Package/GetBinPaths.targets
- src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
- src/Package/MSBuild.VSSetup/files.swr
This reverts commit 28ce126ed4f2220d87317b7f95d03d116c72bb4b.
The original commit failed RPS twice, so it was reverted. It then passed RPS twice, so this reverts its revert.
> Add back support for host objects in 64-bit MSBuild

- src/Shared/OpportunisticIntern.cs
- src/Shared/ReuseableStringBuilder.cs
This change is addressing unnecessary allocations on the string interning path. The `IInternable` implementations (except `ReuseableStringBuilder`) are struct but they end up on the managed heap anyways because of the implicit boxing taking place at the point where they are passed as an `IInternable` argument. Also, accessing the structures via the interface is relatively expensive and prevents inlining.
Fixed in this PR by genericizing the relevant methods, changing their signatures from taking `IInternable` to taking the `T` type parameter with an interface constraint.
Other changes:
- Replaced the unrolled by-character checks for hardcoded interned strings with a helper call. The old code was problematic especially given the fact that each character read was an interface call. With the …
> Eliminate boxing from OpportunisticIntern string interning paths

- src/Build.UnitTests/Evaluation/SemiColonTokenizer_Tests.cs
- src/Build/Evaluation/SemiColonTokenizer.cs
- src/Shared/OpportunisticIntern.cs
This change eliminates unnecessary string allocations in `SemiColonTokenizer` and makes it use `OpportunisticIntern` instead.
- Introduced `SubstringInternTarget ` for cases when one wishes to create substrings of an existing string. This struct wraps the string and the location of the substring.
- Implemented manual white-space trimming in `SemiColonTokenizer` to avoid potential string allocations in `String.Trim()`.
- Made `SemiColonTokenizer` use `OpportunisticIntern` so the token being returned is checked against the set of already interned strings and may itself become interned (subject to the inner workings of `OpportunisticIntern`).
Partially fixes #4172
> Intern substrings created by SemiColonTokenizer

- scripts/Deploy-MSBuild.ps1
Extracted this from #5222 
When I tried the deployment script msbuild failed not finding the satellite assemblies. Apparently this happens when you're testing msbuild bits with new resources.
> Copy satellites in deployment script

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
```$([System.String]::new(%(SomeVar))``` seems to be a commonly used pattern worth optimizing. Without this change, if SomeVar is not empty, it is handled by the general late binding logic coercing the argument to ```char[]``` and calling ```String(char[])```. That is a redundant conversion from string to char array and then from char array back to string. If the argument is empty, it fails to find a matching constructor, which is technically correct but not what the user expects.
Fixes #5275
> Add evaluation shortcuts for commonly used String ctors

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Shared/CommunicationsUtilities.cs
- src/Shared/NodeEndpointOutOfProcBase.cs
- src/Tasks.UnitTests/CreateItem_Tests.cs
I am seeing consistent test hangs on macOS Mono. A node is getting into a bad state and is failing to respond to handshakes. While I do not yet understand the root cause, it is clear that having a timeout on the handshake operation mitigates the issue. The test is now failing but does not hang, saving developer time as well as test pipeline resources.
> Enable handshake timeout on Mono

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Addressing the issue of dependency content files overwriting the referencing project's content files of the same name (see dotnet/sdk#3871). 
Test coverage in the SDK [here](https://github.com/sfoslund/sdk/blob/CopyAppSettingsIssue/src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs#L138).
> Filtering for duplicate content files with referencing projects

- src/Tasks/Microsoft.NETFramework.CurrentVersion.targets
The actual ItemGroups inside the target already do a good job of logging exactly what items were added and/or removed and in what order and with what metadata.
Emitting an extra low-pri message which is unstructured here just adds noise, slows the builds down, wastes binlog space and is otherwise redundant.
> Don't log @(ReferencePath) at the end of ImplicitlyExpandDesignTimeFacades

- src/Tasks/FileIO/GetFileHash.cs
- src/Tasks/FileIO/VerifyFileHash.cs
Based on investigations here: https://github.com/dotnet/aspnetcore/pull/21021. 
Hashes produced by GetFileHash can be calculated in parallel. This scales better for larger number of files. Some before and after with this change:
In addition, this PR has a few more cleanups as suggested here by @bartonjs https://github.com/dotnet/aspnetcore/pull/21021#discussion_r411714968
> Compute hashes in parallel in GetFileHash

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
- src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs
- src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
- src/Framework/TaskPropertyInfo.cs
- src/Tasks/Microsoft.Common.props
This enables fine-grained control over whether:
* to log each parameter (whether input or output)
* or whether to log item metadata for each ITaskItem[] parameter.
When LogTaskInputs is set the default behavior is still to log all parameters and all item metadata for ITaskItem[] parameters. Since this is very verbose and hurts performance without adding any useful information it is valuable to be able to turn this logging off in certain situations.
This approach allows controlling logging via setting simple properties or environment variables.
I've identified the specific tasks and parameters that we want to restrict logging for that would give us the most gains without losing any significant useful info:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Task-Parameter-Logging
> Allow disabling logging of task parameters and item metadata

- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
- src/Build/Evaluation/IntrinsicFunctions.cs
- src/Build/Instance/TaskFactories/TaskHostTask.cs
- src/MSBuild/NodeEndpointOutOfProcTaskHost.cs
- src/Shared/CommunicationsUtilities.cs
- src/Shared/ErrorUtilities.cs
- src/Shared/Traits.cs
Adds use of an environment variable for non-task host nodes as well. Some duplicated logic should ideally be refactored pending acceptance of an altered handshake.
Fixes #4961.
> Use environment variable for handshake Resolves #4961

- src/Build.UnitTests/Graph/GraphTestingUtilities.cs
- src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
- src/Build/Graph/GraphBuilder.cs
Hitting this on a quickbuild repo with ~550 projects and ~19K edges (due to transitive edges).
The problem was using an intermediary list to aggregate intermediary results, which exploded exponentially in size due to duplicates. Fix is to use a hash set.
The failure can't really be tested (without stress tests) because it appears in an intermediary list which finally gets dumped into a set, so there's no observable trace of the problem at the end of graph construction.
This fix avoids the exception and takes graph construction down from 5 minutes to 30 seconds on that specific repo.
> Fix "Array dimensions exceeded supported range" exception

- src/Build.UnitTests/Construction/ProjectImportElement_Tests.cs
- src/Build.UnitTests/Evaluation/ProjectSdkImplicitImport_Tests.cs
- src/Build/Construction/ProjectImportElement.cs
- src/Build/Evaluation/Evaluator.cs
- src/Framework/Sdk/SdkReference.cs
The logic around whether or not to mark the project dirty when changing one of the three properties for an SDK on an import was not taking into account that a new value might be coming from a setter.  The code now accepts these values and calculates whether or not the set operation affects the import element.
I also renamed the property to make it more clear what it represents.
I added a unit test before fixing the code to verify that this is correctly verified.
Fixes #5320
> Fix ProjectRootElement.SdkReference

- src/Tasks/Microsoft.Common.CurrentVersion.targets
It's actually `InteropOutputPath`
> Fix Comment at target ResolveComReferences

- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
This prevents ETW traces from firing when their conditions evaluate to false.
> Only log tasks that fire

- src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
In the special case where a remove operation removes all items like
```xml
<Compile Remove="@(Compile)" />
```
We currently have poor behavior because we match ("everything matches")
and then remove items one at a time. Instead, we can just empty out the
list.
Fixes #2314. Encouraged to finally do this by @maartenba's blog post https://blog.jetbrains.com/dotnet/2020/05/11/story-csproj-large-solutions-memory-usage/.
> Make Remove-all-items O(1)

- src/Build/ElementLocation/XmlDocumentWithLocation.cs
WSL2 uses a 9p share exposed as `\\wsl$` to allow the Linux filesystem
to be seen by Windows and win32 processes. This was failing with a
`System.UriFormatException` because `wsl$` is not a valid URI hostname.
Instead, just don't treat these files as read-only.
> Get past first hurdle loading a project from \\wsl$

- src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Context: https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/BuildProcess.md
This adds intellisense inside Visual Studio for
Xamarin.Android-related properties and item groups.
This is not a comprehensive list, but I picked the most important ones
based on:
1. They are commonly used and need to be configured by developers.
2. They won't be going away any time soon. (supported in .NET 5+)
> [intellisense] most commonly-used properties/items for Xamarin.Android

- src/MSBuild.UnitTests/XMake_Tests.cs
NormalPriorityBuild has hung several times. I haven't been able to figure out why it would hang and other tests that use the same path (ExecuteMSBuildExeExpectSuccess) wouldn't.
> Disable hanging tests

- src/MSBuild/XMake.cs
This otherwise breaks in linux-like environments when starting MSBuild at below normal priority unless also run with administrator privileges.
Fixes #5365
> Respect current priority Fixes #5365

- .vsts-dotnet.yml
This reverts commit f516095bba73ef0cf4c76034c854aea5fdfcbd0a.
This workaround is no longer needed after dotnet/arcade#5239.
> Revert build-pool-selection workaround

- src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
- src/Build/Resources/Constants.cs
- src/Shared/CommunicationsUtilities.cs
Fixes https://github.com/microsoft/msbuild/issues/5375. A timestamp can be different between Microsoft.Build.dll in the toolset and the copy in the amd64 subfolder.
Getting the hash of AssemblyInformationalVersion gets the SHA of the actual file.
> Use the file version instead of timestamp in handshake

- src/Shared/CommunicationsUtilities.cs
@rainersigwald 
This is the fix to mask the first byte. The nice part of having consolidated this logic is that I only have to do it once.
This is to fix https://github.com/dotnet/runtime/issues/37333.
> Mask first byte

- .vsts-dotnet-ci.yml
- .vsts-dotnet.yml
Causes spurious failures on PR build rerun like
```
##[error]Artifact FullOnWindows build logs already exists for build 683197.
```
https://dev.azure.com/dnceng/public/_build/results?buildId=683197&view=logs&j=9f11c3b6-ab7b-5d31-db2e-f92a12840391&t=161d3658-037b-58d7-7ae4-bd96b8f471dc&l=30
Many DevComm issues on this, for instance https://developercommunity.visualstudio.com/content/problem/774908/publish-artifact-fails-when-retry-failed-job.html
Just reverting the whole thing to get back to known-good.
> Revert "Switch to Pipeline Artifacts (#5062)"

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- src/Framework/Sdk/SdkResultFactory.cs
#5269 introduced an API breaking change by adding an overload to the `IndicateSuccess` method of the `SdkResultFactory` abstract class.
This class should only be implemented by MSBuild itself and by implementors of SDK resolvers when they want to mock this class for testing.  So the impact of the break is probably low, but it still seems like a good idea to fix.
> Fix API breaking change from adding SdkResolver IndicateSuccess overload

- src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs
- src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
- src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
Fixes #5445 by checking to see if an item function is invoked (the captured
expression has subcaptures) before optimizing operations on same-item
captures.
Added regression tests and improved some asserts that didn't really help me when they fired.
fyi @cdmihai, @safern
> Respect transforms in lazy eval

- src/Build/Logging/BinaryLogger/BinaryLogger.cs
This will be useful to be able to open localized binlogs. If we know the culture of the log we can fetch the right resources from the MSBuild .dlls.
> Log CurrentUICulture in binlog.

- src/Shared/WeakStringCache.Concurrent.cs
I haven't been able to reproduce #5442 on ARM64 but code inspection revealed a potential race between one thread dereferencing a `GCHandle` and another thread freeing it. The exception in #5442 does not match what I'd expect to see in such scenario but lacking other cues there's a good chance that fixing it will resolve the issue.
The concurrent implementation of `WeakStringCache` runs scavenging in parallel with other threads accessing the cache so we must never assume that an entry fetched from the cache is valid unless it's removed from the cache at the same time. 
Changes in this PR:
- `GetOrCreateEntry()` now always performs two operations on the cache. Previously it was one to three operations depending on whether it was a cache hit or cache miss. With this change hits become …
> Fix GCHandle race in WeakStringCache.Concurrent

- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/MSBuild/XMake.cs
- src/Shared/Traits.cs
Fixes #5221 
See https://github.com/microsoft/msbuild/issues/5221#issuecomment-645026616 for details
> After some investigation it looks like MSBuild is launched differently for Design Time Builds compared to regular builds. These builds don't respect the environment variable MSBUILDDISABLENODEREUSE because they explicitly set nodeReuse to true.
> Fix visual studio applying nodereuse despite MSBUILDDISABLENODEREUSE being set

- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/SolutionFile.cs
- src/Build/Instance/ProjectInstance.cs
Solution filter files erroneously combined the current directory with the path from the solution filter file to the solution file. This corrects it to combine the solution filter file's directory with the path from the solution filter file to the solution file and modifies a test to correct that problem.
Fixes #5431.
> Slnf from other directory Fixes #5431

- src/Build.OM.UnitTests/Definition/Project_Tests.cs
- src/Build/Definition/Project.cs
This should fix #5198, but it would have perf implications, so we maybe shouldn't take it.
> Prevent invalidfilenamechars when globbing Fixes #5198

- src/MSBuild/app.amd64.config
For some reason, these overrides appear to be necessary on x64/amd64
.NET Framework. They were removed in #3960 because we thought they
were redundant now, but that appears to only be the case on x86.
Fixes #5331.
> Support long paths on amd64

- src/Tasks/BootstrapperUtil/Util.cs
Right now bootstrapper packages (used by ClickOnce and VS Installer Projects) are discovered in one of two ways:
- In a default path under "Program Files (x86)\Microsoft SDKs\ClickOnce Bootstrapper\Packages"
- In customizable paths set under the "Software\Microsoft\GenericBootstrapper\AdditionalPackagePaths" reg key
Both of these involve paths/keys outside the VS install root.  For the new .NET Core packages we want to install them per instance under the MSBuild extensions path.  So this change is adding an entry to the list of folders used during package discovery to include "MSBuild\Microsoft\VisualStudio\BootstrapperPackages".
> Updating bootstrapper package locator to include a fixed location under MSBuild extensions folder

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
Fix the issue with the retail version of msbuild.exe.config, so it has a binding redirect for v15 xamlbuildtask.dll, as it does for v4.0.
> Update bindingRedirect versions of Workflow build tasks dlls (dev16)

- src/MSBuild/app.amd64.config
These ran afoul of a .NET Framework bug that means that the base
AppDomain gets .NET 4.0 behaviors instead of the modern defaults.
Fixes #5331 (by working around [AB#1148752](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1148752)).
> Remove codeBase entries for amd64 MSBuild

- src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs
- src/Build/Globbing/MSBuildGlob.cs
`Regex` is immutable and can be shared between `MSBuildGlob` instances. Analyzing the glob patterns used by real-world projects, it is clear that such sharing would have significant impact on memory. For example, loading the OrchardCore solution in Visual Studio creates ~12k instances of `MSBuildGlob` with only ~100 unique match file expressions.
The PR adds a simple process-wide cache of unique `Regex` objects that have been handed out. Reusing these expensive objects removes the memory pressure (at most one `Regex` per match file expression) and also saves non-trivial time compiling them.
Ballpark numbers:
- The memory cost of one compiled `Regex`: ~30 kB
- The time cost of compiling one `Regex`: ~5 ms
Fixes #3668
> Deduplicate and share Regex objects for globbing

- README.md
- eng/Versions.props
- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
Same changes as in the last update for 16.7.
Grepping the tree for "16.7", I'm wondering if we still need this override in eng\Versions.props:
```
<MicrosoftVSSDKBuildToolsVersion>16.7.13</MicrosoftVSSDKBuildToolsVersion>
```
> [vs16.8 snap] Updated branding for 16.8

- src/MSBuild/app.amd64.config
Reverts microsoft/msbuild#5460
This should no longer be necessary after #5471.
> Revert "Support long paths on amd64"

- src/Shared/AssemblyFolders/AssemblyFoldersEx.cs
- src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs
- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Fixes #3783 
This PR doesn't modify the source list of AssemblyFoldersEx which contains additional data (the difference was in my case only in the View property). 
~~The source list is also used in the output which is shown in the issue, so the output will still contain duplicate entries, but the search is for actual files in the folders isn't done twice.~~
This PR also removes duplicate log output.
> Remove duplicate folders before adding files to cache.

- src/MSBuild/app.amd64.config
Fixes https://github.com/microsoft/msbuild/issues/5494
Work item (Internal use): [AB#1150959](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1150959)
A regression was introduced with https://github.com/microsoft/msbuild/pull/5471, which we did to enable long path support for x64 msbuild. This fix simply backs out what caused the regression.
The regression affects the following scenarios:
- Building any UWP application with the minimum platform version set to 15063 with the configuration set to Release / x64.
- Building any c++ application that contains any COM references.
Yes
Manual patch passes test.
Low
> Revert 5471 exp/drop amd64 codebase

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Context: https://github.com/xamarin/xamarin-android/pull/4905
Fixes: https://github.com/microsoft/msbuild/issues/3916
Xamarin.Android runs MSBuild targets after `CoreCompile` and `Build`
that generates files in `$(IntermediateOutputPath)`. If you want to
add these files to `@(FileWrites)`, the build-in functionality from the
`IncrementalClean` target doesn't work unless you do something like:
<Target Name="Foo" BeforeTargets="_CleanGetCurrentAndPriorFileWrites">
The problem here being `_CleanGetCurrentAndPriorFileWrites` is "private".
Or modify `$(CoreBuildDependsOn)`:
<CoreBuildDependsOn>
$([MSBuild]::Unescape($(CoreBuildDependsOn.Replace('IncrementalClean;', 'Foo;IncrementalClean;'))))
</CoreBuildDependsOn>
This seems weird to me, and it could also break if a target was named …
> Introduce $(IncrementalCleanDependsOn)

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- src/Build.UnitTests/BackEnd/MockSdkResolverService.cs
- src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
- src/Build.UnitTests/Evaluation/SdkResultEvaluation_Tests.cs
- src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/HostedSdkResolverServiceBase.cs
- src/Build/BackEnd/Components/SdkResolution/ISdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverContext.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverRequest.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResult.cs
- src/Build/BackEnd/Components/SdkResolution/SdkResultFactory.cs
- src/Build/Evaluation/Evaluator.cs
- src/Framework/Sdk/SdkResolverContext.cs
- src/Framework/Sdk/SdkResultFactory.cs
535b289 adds the ability to pass items and properties along with a SDKResult in the single path case
4362874 adds a IsRunningInVisualStudio property to SdkResolverContext (Based on #3621)
> Add IsRunningInVisualStudio property to SdkResolverContext

- .vsts-dotnet.yml
- src/MSBuild/MSBuild.csproj
- src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
- src/MSBuild/Update-MSBuildXsds.ps1
We've been manually managing this and naturally forgotten it a few times. That's not cool. Let's let a robot do it.
This requires change to the releases: https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=749728&_a=release-history but it will be harmless to do this first and then change them.
Example internal PR: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/262150?_a=files
> Sync XSD "IntelliSense" with VS repo automatically on insertion

- documentation/wiki/MSBuild-Resources.md
When I was going through documentation, I found out that link to http://www.msbuildexplorer.com/ leads to site which offers "free" keys. This PR removes that link and keeps only link to GitHub repo
> [Documentation] Remove link to invalid site

- ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs
- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
- ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
- src/Framework.UnitTests/BuildErrorEventArgs_Tests.cs
- src/Framework.UnitTests/BuildWarningEventArgs_Tests.cs
- src/Framework.UnitTests/CustomEventArgSerialization_Tests.cs
- src/Framework/BuildErrorEventArgs.cs
- src/Framework/BuildWarningEventArgs.cs
- src/Shared/TaskLoggingHelper.cs
- src/Tasks/Error.cs
- src/Tasks/Warning.cs
As discussed in #4029 (see this [comment](https://github.com/microsoft/msbuild/issues/4029#issuecomment-652131756)) I've added the ability to set a help link for both the Error and Warning tasks. This would allow authors of MSBuild targets to issue warnings and/or errors and point users to some page describing more details about the error/warning. Obviously these would need to show up in the IDE somewhere, but I'm hoping that @davkean can take care of that. I think I've done everything that needs to be done on the MSBuild side of things, but this is my first PR here so I'm not entirely sure.
> Add ability to set a help link for errors/warnings

- .vsts-dotnet.yml
This brings back a part of #5062, but only for the upload that Arcade knows nothing about, so it shouldn't break.
Internal PR establishing that insertion still works: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/261969?_a=files
> Switch only the bin upload to a pipeline artifact

- src/Tasks/Hash.cs
I was profiling `<Hash/>` to see if I could improve it:
https://github.com/jonathanpeppers/Benchmarks/tree/msbuild-hash
Then I noticed a simple bug that calculates the `StringBuilder`
capacity:
var separatorSize = itemsToHash.Length - 1;
return totalItemSize + separatorSize;
The `- 1`, seems wrong because the separator is always appended:
foreach (var item in ItemsToHash)
{
string itemSpec = item.ItemSpec;
stringBuilder.Append(IgnoreCase ? itemSpec.ToUpperInvariant() : itemSpec);
stringBuilder.Append(ItemSeparatorCharacter);
}
This means the capacity is 1 less than it should be, and the
underlying `StringBuilder` has to "resize" itself at least once.
Just removing the `- 1`, I could see a noticeable memory usage
difference in a benchmark:
| Method |     Mean |    Error |   StdDev |   Gen …
> Fix StringBuilder capacity for <Hash/> task

- src/Build/Evaluation/Evaluator.cs
Tested manually along with https://github.com/dotnet/sdk/pull/12633
> Updating setting SDK resolver isRunningInVisualStudio

- src/Shared/NativeMethodsShared.cs
Follows what we already do for Windows.
Fixes https://github.com/dotnet/msbuild/issues/5454
> Mono: use RuntimeInformation.IsOSPlatform to check for macOS

- src/MSBuild/XMake.cs
#5381 did not account for any possible priority class, and apparently customers are using priorities that are below BelowNormal but not Idle. This will more permanently resolve the issue.
> prevent exception for increasing priority

- src/Build/BackEnd/Node/OutOfProcNode.cs
- src/Build/Definition/ProjectCollection.cs
- src/MSBuild/OutOfProcTaskHostNode.cs
- src/MSBuild/XMake.cs
This change moves adding the UnhandledException handler to the current AppDomain from various places in the MSBuild library to one location in MSBuild.exe. This ensures that it is not done when MSBuild is running hosted in another process where such handler with its side-effects is considered problematic.
Fixes #5543
> Use UnhandledException handler only in MSBuild.exe

- src/MSBuild/XMake.cs
Customer may be trying to call this without setting a node or setting a value of 1 both which will trigger an index out of range exception.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1157058
> Fix watson crashes in StartLocalNode.  

- eng/Packages.props
- src/MSBuildTaskHost/MSBuildTaskHost.csproj
Fixes https://github.com/dotnet/msbuild/issues/5620.
Unfortunately the Microsoft.NETFramework.ReferencesAssemblies does not include net35, so we're using https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35 combined with a workaround to bypass looking for System.Data.Entity.dll 3.5.0.0 in the GAC.
> Enable MSBuild building without 3.5 SP1 targeting pack installed.

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
- src/Build/Evaluation/Evaluator.cs
- src/Build/Evaluation/Expander.cs
- src/Shared/Traits.cs
Fixes: https://github.com/dotnet/msbuild/issues/5315
I have seen some comically long log messages such as:
Task "GetDependsOnNETStandard" skipped, due to false condition; ('$(_HasReferenceToSystemRuntime)' != 'true' and '$(_IsXBuild)' != 'true' and '$(DependsOnNETStandard)' == '' and '@(_XACandidateNETStandardReferences)' != '') was evaluated as ('true' != 'true' and 'true' != 'true' and '' == '' and 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rc.1.20371.13\ref\net5.0\Microsoft.CSharp.dll;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rc.1.20371.13\ref\net5.0\Microsoft.VisualBasic.Core.dll;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rc.1.20371.13\ref\net5.0\Microsoft.VisualBasic.dll;C:\Program …
> Truncate Target/Task skipped log messages to 1024 chars

- MSBuild.Dev.sln
- MSBuild.sln
Small change which fixes paths to NuGet.Config and xunit.runner.json. This enables to open these files directly from VS (and other editors).
> Fix paths to solution items

- src/Build/Logging/EvaluationLocationIdAgnosticComparer.cs
- src/Framework/Profiler/EvaluationLocation.cs
- src/Framework/Profiler/ProfilerResult.cs
Calling `GetHashCode()` on an enum results in boxing (i.e. a GC allocation) when running on .NET Framework. This has been addressed in .NET Core (https://github.com/dotnet/coreclr/pull/7895) but we want to fix it on our side still because it's showing in Visual Studio profiles:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1166715
This PR is also removing the calls to `base.GetHashCode()` which are pointless in structures that calculate the hashcode out of all their fields.
> Do not call GetHashCode() on enums

- src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
- src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
Fixes #5662 by keeping track of visited targets and avoiding an infinite loop when encountering an already-visited target.
> Don't hang on cycles in AfterTargets

- src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
- src/Build/Evaluation/ItemSpec.cs
- src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
- src/Shared/Traits.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
We often see hangs where MSBuild is enumerating the entire drive because conditions similar to this one are ignored at design time, most notably when loading projects in Visual Studio.
```xml
<Content Include="$(SomeDir)\**\*.*" Condition="'$(SomeDir)' != ''">
```
This PR addresses the problem by honoring the condition in cases where the evaluated glob file spec represents a full drive/filesystem walk, i.e. starts with ```\**\``` or ```/**/```.
Fixes #4091 after adding the condition.
> Don't expand full drive globs with false condition

- src/MSBuild/XMake.cs
The `MSBuildExeStop` event is being fired at the beginning of execution when `MSBuildExeStart` should be fired instead.
> Fix Inadvertent Call to MSBuildExeStop

- src/Tasks.UnitTests/XmlPoke_Tests.cs
- src/Tasks/XmlPoke.cs
> Use a counter instead of relying in XPathNodeIterator.Count

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
- src/Build/Evaluation/Context/EvaluationContext.cs
- src/Build/FileSystem/MSBuildFileSystemAdapter.cs
- src/Build/FileSystem/MSBuildFileSystemBase.cs
- src/Build/Microsoft.Build.csproj
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
- src/MSBuildTaskHost/FileSystem/MSBuildTaskHostFileSystem.cs
- src/Shared/FileSystem/CachingFileSystemWrapper.cs
- src/Shared/FileSystem/IFileSystem.cs
- src/Shared/FileSystem/MSBuildOnWindowsFileSystem.cs
- src/Shared/FileSystem/ManagedFileSystem.cs
- src/Shared/FileSystem/WindowsFileSystem.cs
- src/Shared/UnitTests/FileMatcher_Tests.cs
- src/Shared/UnitTests/ObjectModelHelpers.cs
- Made IFileSystem public. Added some extra methods to it from QuickBuild's file system interface. This interface will also be passed to the future project cache interface so that caches can reuse IO from evaluation and between themselves.
- EvaluationContext can take an IFileSystem. This enables QuickBuild and VisualStudio to share their file system caches with msbuild evaluations.
Possible Next steps (future PRs):
- Pass the interface to sdk resolvers in a non breaking manner. AFAIK they do a lot of IO
- I saw some evaluation bits that do IO without passing through the interface, so propagating the interface to those places as well seems like a potential perf gain.
> Share file system caches via the EvaluationContext

- src/Build.UnitTests/Evaluation/Expander_Tests.cs
- src/Build/Evaluation/Expander.cs
Fixes #5702 by only attempting to truncate an item entry if it has a value.
fyi @jonathanpeppers
> Allow expands-to-empty item transforms again

- .github/CODE_OF_CONDUCT.md
- README.md
This addresses dotnet/org-policy-violations#2274. For more details, see https://github.com/dotnet/org-policy/blob/master/doc/PR15.md
> Use .NET Foundation Code of Conduct

- src/Build/Construction/Solution/SolutionFile.cs
This PR adds another language to the list of project type guids considered as _KnownToBeMSBuildFormat_. Without presence in this list, newer features such as _/graphBuild_ will silently exclude the language from participation (per #5159). Synergy DBL (*.synproj) conforms to the [MSBuild Project Reference Protocol](https://github.com/dotnet/msbuild/blob/master/documentation/ProjectReference-Protocol.md) and is otherwise a compatible language other than being missing from this list.
> Allow Synergy DBL to be a known supported type GUID #5159

- src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Several property and metadata elements were documented as having boolean type, yet were not given a type in the XSD, or given string type.
This commit applies the msb:boolean type to such elements.
Doing so gives autocompletion of expected values when editing a project file in the XML editor.
> Set type to boolean in XSD where documented as such

- src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build/Construction/Solution/SolutionFile.cs
This is fairly simple PR which fixes #4328.
One thing which may seem dangerous is check for start of line with `#`. I am accessing it by index, but I an be sure that I will not get `NullReferenceException` or `IndexOutOfRangeException`, because it is not null (previous if) and it is not empty, because of previous check in if.
> Ignore comments when parsing solution file

- src/Build/Logging/BinaryLogger/BinaryLogger.cs
- src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs
Fixes #5383 
The behavior of /bl with Embed (which is the default) is such that it will create a zip file named msbuild.ProjectImports.zip next to the binlog, and when the build completes it will embed the zip into the binlog and delete the binlog.
This poses a problem for some processes (which can be called as part of a build) that expect all files in the local directory to be accessible. Since MSBuild is holding open this ProjectImports.zip file, a process like React Native's `react-native bundle` command will fail the build due to sharing violations.
How tested: Validated with a simple setup of 2 csproj, the first includes the second. Verified that the resulting binlog still includes the imported projects. I changed the closing logic a little because ZipArchive requires to be closed …
> Create ProjectImports.zip in memory instead of on disk

- src/Build/Construction/Solution/SolutionFile.cs
The error displayed a hashset instead of the path to the filter file used to create the hash set and extended a relative path into a full path using the current working directory instead of the directory containing the .sln.
> Fix incorrect and confusing slnf error Fixes #5712

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
- src/Tasks/FormatUrl.cs
- src/Tasks/GenerateApplicationManifest.cs
- src/Tasks/GenerateLauncher.cs
- src/Tasks/GenerateManifestBase.cs
- src/Tasks/ManifestUtil/ApplicationManifest.cs
- src/Tasks/ManifestUtil/Constants.cs
- src/Tasks/ManifestUtil/LauncherBuilder.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/Microsoft.Common.tasks
- src/Tasks/ResolveManifestFiles.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Enables manifest generation for .NET (Core) applications.
.NET (Core) deployments in ClickOnce require a .NET FX based Launcher binary that activates Core application.
The rest of the code deals with setting proper properties and item groups to collect .NET Core files for deployment and set correct parameters for various manifest generation tasks.
For end-to-end scenarios, a change in .NET SDK is needed: https://github.com/dotnet/sdk/pull/13208
Relevant links:
ClickOnce for .NET 5 - Architecture: https://microsoft.sharepoint.com/teams/dotNETDeployment/Shared%20Documents/ClickOnce/ClickOnce%20for%20.NET%205%20%E2%80%93%20Architecture.docx?web=1
> Add support for ClickOnce manifest generation for .NET (Core) applications

- src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Fixes https://github.com/dotnet/project-system/issues/6600
Adds:
- `AnalysisMode`
- `EnforceCodeStyleInBuild`
> Add code analysis properties to project XSD

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks/GenerateLauncher.cs
- src/Tasks/GenerateManifestBase.cs
- src/Tasks/ManifestUtil/ApplicationManifest.cs
- src/Tasks/ManifestUtil/Constants.cs
- src/Tasks/ManifestUtil/Manifest.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/ResolveManifestFiles.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
For .NET Core Console apps of EXE type, the final exe that invokes the built DLL is initially called apphost.exe and then copied to the outdir as {AssemblyName}.exe. When publish tasks are running, it receives references to the apphost.exe from the IntermediateOutputDir. The tasks need to special case this file so that it gets published correctly as {AssembyName}.exe and not apphost.exe
> AppHost checks in ClickOnce publish

- src/Build.UnitTests/TestData/ProjectInstanceTestObjects.cs
- src/Build/Collections/CopyOnWritePropertyDictionary.cs
- src/Build/Construction/ProjectTaskElement.cs
- src/Build/Instance/ProjectTaskInstance.cs
- src/Shared/CopyOnWriteDictionary.cs
- src/Shared/UnitTests/CopyOnWriteDictionary_Tests.cs
- src/Tasks/Microsoft.Build.Tasks.csproj
- src/Utilities/TaskItem.cs
Fixes #5736 by keeping a prototype `ImmutableDictionary`-with-comparer
around using the `MSBuildNameIgnoreCaseComparer`, which is the primary
comparer used for all these dictionaries in MSBuild.
Second commit adds `OrdinalIgnoreCase` too--that is all that I found in our codebase.
@lifengl, is there an easy way to replicate your results so I can confirm that this hits everything?
> Reduce ImmutableDictionary.Comparers allocations

- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/XMake.cs
This occurs because .slnf was treated as a .sln. This resolves #5739 by separating the two at this stage.
> Prioritize building .sln if a .sln and .slnf are in the same folder Fixes #5739

- src/Build.UnitTests/BackEnd/FailingTask.cs
- src/Build.UnitTests/BackEnd/OnError_Tests.cs
- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
- src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
- src/MSBuild/OutOfProcTaskHostNode.cs
- src/Shared/UnitTests/MockEngine.cs
Fixes #5701.
Changes its meaning without altering the default behavior. Also fixed tests and added one to verify that the default is as expected.
> Flip meaning of AllowFailureWithoutError Fixes #5701

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks/ManifestUtil/SecurityUtil.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/SignFile.cs
Files will be signed with SHA1 digest when .NETCore app is published with ClickOnce provider.
Tested manually by author. Automation scenario will be added in dotnet/sdk repo when this msbuild change propagates to the dotnet/sdk repo.
Low.  The code change in the SignFile task maintains compatibility with previous behavior when invoked for publishing .NET FX app. The change only affect .NET Core apps publishing with ClickOnce.
john_hart, @rainersigwald, @NikolaMilosavljevic 
SignFile looks at the .NET FX version that is passed as an argument to decide if the file specified should be SHA1 or SHA2 signed. It checks that the .NET FX version > 4.5 to turn on SHA2 signing.
.NET Core apps targeting .NET Core 3.1 pass in 3.1 as the version of the FX. This causes SignFile to use SHA1 for signing …
> Fix SignFile task to be .NET Core aware

- src/Build/BackEnd/BuildManager/BuildParameters.cs
- src/MSBuild/XMake.cs
- src/Shared/Traits.cs
This is a fix for [AB#1197992](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1197992).
Customer Impact
Customers can specify whether they want nodes to be reused after startup. A change in 16.7 cached it, breaking a VS extension.
Testing
No current testing, but the author can add a unit test.
Risk
Low. The code change is minimal and although customers could have started changing the value of the environment variable after startup since 16.7, there is no clear benefit to doing so.
Code Reviewers
None (yet)
Description of fix
Disable caching of MSBUILDDISABLENODEREUSE variable.
> Msbuilddisablenodereuse live check

- documentation/wiki/ChangeWaves-Dev.md
- documentation/wiki/ChangeWaves.md
Updating the docs for an easier read.
> Refresh Change Wave Docs

- documentation/specs/static-graph.md
Several folks have asked for better documentation about what static graph is and why we think it's a good thing. That's . . . a very reasonable request!
cc @marcpopMSFT @KathleenDollard
> Motivation docs for graph

- src/MSBuild.UnitTests/XMake_Tests.cs
- src/MSBuild/XMake.cs
This pull request fixes #5714:
It adds the support for double dash ('--') indicator used in command line arguments.
With these changes it is now possible to invoke MSBuild commands using the same '--' switch indicators as it is currently possible with dotnet call.
---
Changes done in this delivery are:
* Add '--' as another correct sequence when checking for valid argument's beginning
Even if '-' beginning would also be recognized when using '*--*', adding '*--*' keeps the implementation consistent 
* Move the validation of switch beginnings into separate method
* Get the indicator's length, based on found starting string, so it can be used to correctly extract the name of switch
Without it  '*--*'  would still be unrecognized, as hardcoded *1* in 
`switchName = …
> Support '--' in a command line argument as a correct switch indicator

- src/Tasks/GenerateLauncher.cs
- src/Tasks/ManifestUtil/Constants.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Customers trying to deploy their .NET 5.0 application w/ClickOnce using Single File Self Contained Deployment mode will see a runtime failure either due to invalid entrypoint EXE name or due to missing Core CLR files (e.g. clrcompression.dll, coreclr.dll, clrjit.dll).
**Testing**
Core ClickOnce .NET Core scenarios for both .net 3.1 and .net 5.0 have been validated by sujitn;johnhart;ningli;yaya.
CTI team is doing a full test validation.
**Risk**
Low. The changes are scoped to .NET Core ClickOnce deployment in Single File mode.
**Code Reviewers**
johnhart
**Description of fix**
When a .NET 5.0 app is published with Single-File enabled, not all dependent runtime files are included in the single file bundle EXE. Some files get excluded and need to be published …
> Add files missing in ClickOnce SingleFile bundle.

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/ResolveManifestFiles.cs
Customer trying to deploy their .NET Core 3.1 or 5.0 application w/ClickOnce using Self Contained Deployment (SCD) mode in its default setting (SingleFile=false) will see app fail to launch due to missing .NET Core runtime files in publish folder.
**Testing**
Core scenarios for both .NET Core 3.1 and .NET 5.0 have been validated by sujitn;johnhart;ningli;yaya.
CTI team is doing a full test validation.
**Risk**
Low. The changes are scoped to .NET Core app ClickOnce deployment in SCD Mode with SingleFile=false.
**Code Reviewers**
johnhart
**Description of fix**
ClickOnce Publish is a new feature being added to .NET Core apps. .NET Core apps have a SCD mode that ClickOnce is not aware of. ClickOnce behavior in .NET FX is to filter out references for files that below to …
> Fix for SCD ClickOnce publish of .NET Core App

- src/Shared/CommunicationsUtilities.cs
Fixes one of the causes for https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1172859
Some (but not all) customers will stop having repeatedly failing node handshakes, allowing them to build without restarting Visual Studio. A change in 16.7 relied more heavily upon a flaky API that this change avoids.
**Testing**
The current fix is part of 16.8, and one customer who had experienced the problem with 16.7 tentatively suggested that 16.8 was not broken. Also, all the customers who have reported difficulties and provided COMM traces indicating they shared this problem were using 16.7 at the time.
**Risk**
Very low. The code change is minimal, the new way of looking up a version is already in use in 16.8 without it causing problems, as far as we know, and the new version …
> Improve reliability of node handshake in 16.7 to match 16.8 for version information

- eng/BootStrapMSBuild.targets
Some files, like Microsoft.Common.tasks, were missing from the 64bit bootstrap, causing build errors.
> Copy build files to 64bit bootstrap directory

- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
This was attempted in #5290 but we hit a hang in this test again this week (https://dev.azure.com/dnceng/public/_build/results?buildId=860511).
> Add xunit timeout to hanging CancelledBuild test

- src/Build/Evaluation/Evaluator.cs
The big refactoring is making ProjectElementContainer have a set of Lists of different types of children, lazily initialized and semi-lazily kept sorted. Its children are often accessed using Children.OfType<...> now, and that would eliminate numerous passes over that LinkedList in addition to numerous conversions. Although these methods are called very often, the total number of Children turned out to be surprisingly small, generally under 50 and often under 10, so although there is still a win here, it might be with an undesirable complexity cost, especially since I couldn't make a single object (e.g., Dictionary) that could store all the lists without needing individual conversions afterwards, so the lists would still have to be remade unless I want one list per type.
> Clean up Evaluator.cs

- eng/Versions.props
- src/Tasks/GetReferenceAssemblyPaths.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
MSBuild currently gives a bad error message when using older .NET Core sdk's and targeting `net5.0`. The error message is not helpful so we want to update it for that specific scenario.
Customers using an older SDK and targeting `net5.0` currently receive an error that does _not_ help their scenario. This PR fixes that message.
Low. We've acknowledged that this change will break legacy UWP projects that target `netcore50`, and are okay with that. The discussion for that is located here: https://github.com/dotnet/msbuild/issues/5833. Based on telemetry there seem to be somewhere between 1~4 users that would hit this scenario.
@Forgind 
@rainersigwald 
Change the error message when the discovered assembly is `net5.0` and we're on an older SDK.
---
Fixes …
> Update 16.7 error message when trying to use net5.0

- eng/Versions.props
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Customers trying to deploy their .NET Core app w/ClickOnce will not have the application assembly and application EXE authenticode signed with the cert they set in their ClickOnce settings.
**Testing**
Core ClickOnce .NET Core scenarios for both .net 3.1 and .net 5.0 have been validated by sujitn;johnhart;ningli;yaya.
CTI team has completed full test validation.
**Risk**
Low. The changes are scoped to .NET Core ClickOnce deployment when signing is enabled in the ClickOnce settings.
**Code Reviewers**
johnhart
**Description of fix**
During ClickOnce publish, the application assembly DLL and wrapper EXE are not getting signed when signing is enabled in the ClickOnce settings. 
This change will invoke SignFile msbuild task to sign the built assembly dll and exe. For the …
> Fix ClickOnce signing bug where built assembly and final exe are not signed

- src/Build.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build/Construction/Solution/SolutionFile.cs
This pull request fixes: #5027 
Changes introduced in this PR covers the case where having a project without *EndProject* label, next projects contained in this malformed solution *.sln* file are not built.
So this PR adjusts the behavior of MSBuild to the Visual Studio (please see https://github.com/dotnet/msbuild/issues/5027#issuecomment-571215016)
---
Changes done in this delivery are:
* Add new case to project's parsing procedure where the next line read in the project's configuration (in malformed *.sln* file) is any of project's configuration detail, nor *EndProject* label, but is in fact the beginning of new project's configuration.
* Recursively read the next spotted project (which is incorrectly nested in the one missing it's *EndProject* label) and add it to parsed projects
* …
> Fix: Projects skipped when missing EndProject

- src/Tasks/Microsoft.Common.CurrentVersion.targets
In same change wave as NoWarn (can change to a separate one if desired.)
@sbomer, here's WarnAsError. WarnNotAsError is a little more complicated, though I'd be happy to try to help if you want to try to implement it yourself.
> Support WarningsAsErrors as MSBuildWarningsAsErrors

- src/Package/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
- src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
Clean up some of our Microsoft-internal nonshipping packages so that they are compliant with what a dotnet package should look like.
> Nonshipping nuget compliance

- src/Build.UnitTests/Parser_Tests.cs
- src/Build.UnitTests/Scanner_Tests.cs
- src/Build/Evaluation/Conditionals/Scanner.cs
- src/Build/Resources/Strings.resx
- src/Build/Resources/xlf/Strings.cs.xlf
- src/Build/Resources/xlf/Strings.de.xlf
- src/Build/Resources/xlf/Strings.en.xlf
- src/Build/Resources/xlf/Strings.es.xlf
- src/Build/Resources/xlf/Strings.fr.xlf
- src/Build/Resources/xlf/Strings.it.xlf
- src/Build/Resources/xlf/Strings.ja.xlf
- src/Build/Resources/xlf/Strings.ko.xlf
- src/Build/Resources/xlf/Strings.pl.xlf
- src/Build/Resources/xlf/Strings.pt-BR.xlf
- src/Build/Resources/xlf/Strings.ru.xlf
- src/Build/Resources/xlf/Strings.tr.xlf
- src/Build/Resources/xlf/Strings.zh-Hans.xlf
- src/Build/Resources/xlf/Strings.zh-Hant.xlf
Attempt at https://github.com/dotnet/msbuild/issues/5615
- It is mentioned in https://github.com/dotnet/msbuild/issues/5615 that MSBuild should both error and warn about this so not sure which is the correct approach here. An error might break a lot of existing code, but it might be the correct thing to do (?).
- Also not sure whether this warrants a new string error message, though I did create one. If so, should I commit my untranslated xlf files? I am not familiar with the i18n process in MSBuild.
Any feedback welcome.
> Detect whitespace in property name

- documentation/wiki/ChangeWaves-Dev.md
- documentation/wiki/ChangeWaves.md
Partially checks a box in https://github.com/dotnet/msbuild/issues/5756
Making the docs clearer. Specifically answering why we went with opt-out vs opt-in and improving dev docs
> Update Change Wave Docs

- src/Build.UnitTests/Scanner_Tests.cs
- src/Build/Evaluation/Conditionals/Scanner.cs
This weakens the check somewhat, since it only checks just inside parentheses, but that allows people to put spaces in, say, property conditions after a comma.
Fixes #5863
> OnlyCheckWhitespaceInsideParenthesis Fixes #5863

- eng/Packages.props
- eng/Versions.props
Some T4 template files fail at build time with a problem due to `System.Collections.Immutable` in MSBuild being older than Roslyn's copy.
```
An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.MissingMethodException: Method not found: 'System.Collections.Immutable.ImmutableDictionary2<!!0,!!1> System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary(Builder<!!0,!!1>)'.
at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.AddSyntaxTrees(IEnumerable1 trees)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable1 trees)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonAddSyntaxTrees(IEnumerable1 trees)
at Microsoft.VisualStudio.TextTemplating.CompilerBridge.PrepareNewCompilati …
```
> Update System.Collections.Immutable to 5.0.0

- src/Shared/UnitTests/MockEngine.cs
- src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
- src/Tasks.UnitTests/AssemblyDependency/SuggestedRedirects.cs
- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
- src/Tasks/Resources/Strings.resx
- src/Tasks/Resources/xlf/Strings.cs.xlf
- src/Tasks/Resources/xlf/Strings.de.xlf
- src/Tasks/Resources/xlf/Strings.en.xlf
- src/Tasks/Resources/xlf/Strings.es.xlf
- src/Tasks/Resources/xlf/Strings.fr.xlf
- src/Tasks/Resources/xlf/Strings.it.xlf
- src/Tasks/Resources/xlf/Strings.ja.xlf
- src/Tasks/Resources/xlf/Strings.ko.xlf
- src/Tasks/Resources/xlf/Strings.pl.xlf
- src/Tasks/Resources/xlf/Strings.pt-BR.xlf
- src/Tasks/Resources/xlf/Strings.ru.xlf
- src/Tasks/Resources/xlf/Strings.tr.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
- src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
This adds logging all information about which assemblies caused conflicts and why when the warning appears.
Fixes #608
> Always log conflict information in MSB3277

- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
- src/Package/MSBuild.VSSetup/files.swr
This addresses two problems with #5879:
1. Failures in VS RPS related to JITting at runtime. With no `ngenApplication` specified, our SCI got ngened in the context of the default VS application, which isn't `MSBuild.exe`. Then at runtime, it wasn't loaded because the MVID of the ngened assembly (VS's special optprof-augmented copy) didn't match the one located at runtime (the standard retail copy from our repo).
2. Added binding redirects for SCI. If a task depended on having access to our copy of SCI at our old version, updating our version would cause it to fail to load. Add a binding redirect like `devenv.exe` and Roslyn assemblies have to pull that reference to our copy.
> Binding redirect for Immutable upgrade; ngen in our context

- .vsts-dotnet.yml
In a conversation between Rainer and Rick Krause
Rick mentions:
> You’re using the wrong package feed— https://devdiv-test.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json.
Change the feed source in your task to  https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json
And: 
>Actually, you could drop the feedSource value altogether, since it defaults to the value I said to use.
Thanks, Rick
It gets passed the step, but fails now at signing validation
`[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20509.7\tools\SdkTasks\SigningValidation.proj(56,5): error : Signing validation failed. Check signcheck.errors.log for more information.`
Pipeline Build: …
> Remove feedSource parameter from MicroBuild task

- src/Build.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build/Construction/Solution/ProjectInSolution.cs
- src/Shared/Resources/Strings.shared.resx
- src/Shared/Resources/xlf/Strings.shared.cs.xlf
- src/Shared/Resources/xlf/Strings.shared.de.xlf
- src/Shared/Resources/xlf/Strings.shared.en.xlf
- src/Shared/Resources/xlf/Strings.shared.es.xlf
- src/Shared/Resources/xlf/Strings.shared.fr.xlf
- src/Shared/Resources/xlf/Strings.shared.it.xlf
- src/Shared/Resources/xlf/Strings.shared.ja.xlf
- src/Shared/Resources/xlf/Strings.shared.ko.xlf
- src/Shared/Resources/xlf/Strings.shared.pl.xlf
- src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
- src/Shared/Resources/xlf/Strings.shared.ru.xlf
- src/Shared/Resources/xlf/Strings.shared.tr.xlf
- src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
- src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf
This pull request fixes: #4836
Changes introduced in this delivery extends the *MSB5009* with additional information about the incorrectly nested project within the solution. Additional details are:
* incorrectly nested project's name (without the full path, unique name only),
* incorrectly nested project's GUID
**NOTE:** original *MSB5009* error is kept in the resources for backward compatibility (see commit messages) while the extended MSB5009 can be easily invoked with extended name.
---
Changes done in this delivery are:
* Create additional version of *MSB5009* error with modified error message - meaning stays the same as original *MSB5009* error, but incorrectly nested project's name and GUID is added as arguments.
* Replace the old *MSB5009* with the extended one for each place …
> Provide MSB5009 error with project's name and it's GUID

- src/Tasks.UnitTests/CreateCSharpManifestResourceName_Tests.cs
- src/Tasks.UnitTests/CreateVisualBasicManifestResourceName_Tests.cs
- src/Tasks/AssignCulture.cs
- src/Tasks/CreateCSharpManifestResourceName.cs
- src/Tasks/CreateVisualBasicManifestResourceName.cs
- src/Tasks/Culture.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/dotnet/msbuild/issues/3064
Allows a workaround for those that want to embed resources that have cultures within their filenames. 
Add the `WithCulture` metadata to your EmbeddedResource and set it to `false`.
```xml
<EmbeddedResource Include="a.cs.b" WithCulture="false"/>
<EmbeddedResource Include="light.sms.text" WithCulture="false" />
<EmbeddedResource Include="Resources.en.xml" WithCulture="false" />
<EmbeddedResource Include="some.cs.template" WithCulture="false" />
```
> Allow Cultures Within Names For EmbeddedResources

- eng/Packages.props
- eng/Version.Details.xml
- eng/Versions.props
Add the darc metadata for our dependencies on NuGet and Roslyn. These are toolset dependencies because we use them to construct our bootstrap folder/test environments, but we don't have product code dependencies here--`RoslynCodeTaskFactory` requires Roslyn but doesn't depend on it in the normal way to break cycles/allow floating versions.
This PR changes versions only for the Roslyn build task used for unit tests, making it match the toolset version used to make the bootstrap.
> Darc for bootstrap dependencies

- src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
- src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
Fixes #5766
Introduced by #5350
> Optimization neglected to include condition

- .vsts-dotnet.yml
Before this change, the 'get optprof data from master for exp branches' logic always overrode the parameter that allows overriding the source branch, so if an exp branch needed data from non-master it broke.
Check to see that the passed-in value is the default (the real source branch name) before overriding it.
> Allow overriding exp branch optprof sources

- src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
- src/Build/BackEnd/BuildManager/BuildManager.cs
The logic to handle exceptions thrown on logging and communication threads was trying to make the build submission fail with the exception but it didn't always complete it. This manifested as the build hanging, for example when building with `MSBUILDNODECONNECTIONTIMEOUT = 0`, which is almost guaranteed to throw `InternalErrorException` in `InstantiateNode`.
This PR fixes it by making sure that all submissions are completed in `OnThreadException`. Unlike the original code, proper care is taken to avoid race conditions - i.e. the build result is mutated only if hasn't already been passed to the completion handler.
Fixes #5911
> Don't hang builds on BuildManager internal errors

- src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
- src/Build/Utilities/FileSpecMatchTester.cs
- src/Shared/FileUtilities.cs
First commit: update a test such that it passes only if matching is case insensitive.
Second commit: modify FileUtilities.ComparePathsNoThrow such that it can be made to be always case sensitive or case insensitive. Note that this was changed about seven months ago in [#4997](https://github.com/dotnet/msbuild/pull/4997) where it had previously been a todo to make case sensitivity depend on OS but that implemented it.
Third commit: fix a test that theoretically ensured case insensitivity but in practice did not, changed to care about case in the same PR.
The second commit fixes #5749.
> Make matching case insensitive regardless of OS Fixes #5749

- src/Framework/LazyFormattedBuildEventArgs.cs
- src/Shared/ResourceUtilities.cs
- src/Shared/TaskLoggingHelper.cs
- src/Utilities/TrackedDependencies/FileTracker.cs
In couple of places we have not leveraged LazyFormattedBuildEventArgs properly.
With these changes strings would not be necessary to format, in cases when logging is limited like `/clp:PerformanceSummary`
Related issue #2700
> Fix lazy string format

- src/Shared/Constants.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/ResolveManifestFiles.cs
Port of #5885 to point to master.
> [16.9] ClickOnce publish does not publish certain runtime references in the correct destination folder

- src/Tasks.UnitTests/OutputPathTests.cs
- src/Tasks/Microsoft.Common.CrossTargeting.targets
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/Microsoft.Common.props
- src/Tasks/Microsoft.Common.targets
While this is not officially supported on non-sdk projects, NuGet Pack targets need a common output path to put '.nupkg' across both type of projects.
Required for NuGet/Home#9234 in PR NuGet/NuGet.Client#3270
Also Fixes #1664
> Add BaseOutputPath to common targets

- src/Framework/MSBuildEventSource.cs
- src/Tasks/AssemblyDependency/ReferenceTable.cs
This reverts commit f7111327ed928e28b3b57e1b4b83377a6299669b.
This was failing with F#'s older version of MSBuild.
> Revert "Modify ETW to capture the number of resolved references (#5923)"

- src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
This has hung several times lately, including [here](https://dev.azure.com/dnceng/public/_build/results?buildId=910820&view=logs&j=20125c81-7edb-551b-693a-61efae016b74&t=7ce25265-aabe-59d3-d73c-06619cfcc3c4). Adding a timeout to make that a bit better.
> Add timeout to hanging test

- eng/Versions.props
- src/Shared/Constants.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
- src/Tasks/ResolveManifestFiles.cs
ClickOnce publish fails to publish runtime assets from the Runtimes sub-folder of Nuget package. The published app will then fail to launch after the install.
**Testing**
CTI team has completed ClickOnce Publish validation for Full FX, .NET Core 3.1 and .NET Core 5.0.
**Risk**
Low (limited to ClickOnce tasks/targets). The changes are scoped to a targets and task invoked for ClickOnce publish only and the new code is run only when certain metadata (DestinationSubDirectory) is present for any reference.
**Code Reviewers**
johnhart;nikolam;rainersigwald;forgind
**Description of fix**
Nuget packages can have a runtimes sub-folder that contain copylocal files that need to be available at runtime. These assets need to be published to a path that is specified in the …
> ClickOnce publish does not publish certain runtime references in the correct destination folder

- src/Build.UnitTests/Construction/SolutionFile_Tests.cs
- src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- src/Build/Construction/Solution/ProjectInSolution.cs
- src/Build/Construction/Solution/SolutionFile.cs
- src/Build/Graph/GraphBuilder.cs
This change updates `ProjectInSolution.AbsolutePath` to return a normalized path.  At the moment it simply returns the result of a `Path.Combine()` which leaves `..\` path segments in place and does not contain OS-specific path separators.
Fixes #5949 and https://github.com/NuGet/Home/issues/10307
> Have ProjectInSolution.AbsolutePath return a normalized path

- src/Tasks/Exec.cs
@rainersigwald 
EchoOff is documented to:
> If true, the task will not emit the expanded form of Command to the MSBuild log.
> Exec: take EchoOff into account when command fails

- src/Tasks.UnitTests/CodeTaskFactoryTests.cs
- src/Tasks/CodeTaskFactory.cs
Fixes #5822 by filtering out the default MSBuild assemblies from the UsingTask list.
9bfc622 is the real work but there were a bunch of refactorings to make that clear. I recommend going commit-by-commit.
> Allow redundant specification of MSBuild assemblies in inline tasks

- ref/Microsoft.Build/net/Microsoft.Build.cs
- ref/Microsoft.Build/netstandard/Microsoft.Build.cs
- src/Build/BackEnd/Shared/CircularDependencyException.cs
Closes https://github.com/dotnet/msbuild/issues/5811
> made CircularDependencyExcpetion class public

- src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
- src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactoryTaskInfo.cs
Equals() method on RoslynCodeTaskFactoryTaskInfo was using reference equality to compare hashsets, and thus always returned false. So we never could reuse existing compilations from the dictionary, always compiling the task from scratch.
Use SetEquals instead and add a unit-test that verifies that there's only one compilation happening now (instead of two).
Fixes https://github.com/dotnet/msbuild/issues/5948
> RoslynCodeTaskFactory: Fix caching of assemblies

- src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
We missed a case when the MSBuild task is starting a project build where we didn't pass the parent context if we already had a configuration.
https://github.com/dotnet/msbuild/pull/5013 was the initial fix, but it only fixed the case when matchingConfig was null. This fixes the other case.
Just copying this line:
https://github.com/dotnet/msbuild/blob/a2c42ce9fc8d6fbd4a8cd600073803b8687c9341/src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs#L1134
Fixes https://github.com/dotnet/msbuild/issues/5473
> Pass CurrentTaskContext as ParentBuildEventContext

- src/Build.UnitTests/BackEnd/MockLoggingService.cs
- src/Build/BackEnd/Components/Logging/ILoggingService.cs
- src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
- src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs
- src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
It is very useful to associate ProjectStarted with the evaluation used for the build. We have the MS.B.E.ProjectInstance in ProjectLoggingContext, so pass that to LogProjectStarted.
Fixes https://github.com/dotnet/msbuild/issues/4926
> Pass EvaluationId to ProjectStarted event

- src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
This test has been hanging repeatedly lately. See, for example:
https://dev.azure.com/dnceng/public/_build/results?buildId=934918&view=logs&j=1522e9b9-b859-5e5f-ec86-a68fc9508baf&t=a8d37b2d-1a39-51d6-c11e-8665c8c9811e
> Skip hanging test

- src/Build/BackEnd/BuildManager/BuildManager.cs
- src/Build/BackEnd/BuildManager/BuildSubmission.cs
- src/MSBuild.UnitTests/XMake_Tests.cs
Fix #5837 by moving the promotion of warnings to build failures to the `BuildSubmission` level instead of doing it in `BuildManager` (where the result change happened at `EndBuild()` time and thus wasn't visible when checking the result after the submission completed:
https://github.com/dotnet/msbuild/blob/c70d520b5b8df990f651f0d00cd186a68cb277c6/src/MSBuild/XMake.cs#L1256-L1268
> Warnings-as-errors fail BuildSubmission results

- ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
- ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
- src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #5934.
@dsplaisted, does this look how you expected?
> Optionally output unresolved assembly conflicts

- NuGet.config
These have been deprecated and are now failing--see
https://github.com/dotnet/core-eng/wiki/MyGet-Migration-New-Homes
> Remove myget feed references

- .gitattributes
This is a more accurate description of what's going on here; the code canonically lives in `dotnet/arcade` and so is [vendored](https://github.com/github/linguist/blob/master/README.md#vendored-code) here.
> Switch eng/common to linguist-vendored

- .github/ISSUE_TEMPLATE/04_blankissue.md
- .github/ISSUE_TEMPLATE/config.yml
Issues filed with no template don't get the untriaged label assigned to them, this makes it slightly more annoying to track things in our bug review meeting (separate query for issues we need to get back to).
Disabled blank issues, and created a template that contains a blank issue, but assigns the `untriaged` label to it.
`untriaged` essentially means: "Get to this during bug triage, until we've assigned this out and determined what kind of issue this is."
> Assign Blank Issues the Untriaged Label

- src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #1257168
Issue: ClickOnce is currently publishing contents of Nuget packages that are marked as developement dependencies. These package references should be excluded by publishing providers.
Filter out the development dependencies from the _DeploymentReferencePaths item group. The filtering happens by looking at the CopyToPublishDirectory attribute on ReferenceCopyLocalPaths group which is set to false for said packages.
CTI has validated specific packages that are affected and also validated the change against top 50 NuGet packages.
> Fix how ClickOnce handles developement dependency package references

- README.md
- eng/Versions.props
- src/MSBuild/app.amd64.config
- src/MSBuild/app.config
Not until vs16.9 is brought up-to-date.
Also, for the binding redirects/code bases, is it a string comparison, a version comparison, or a number comparison? Wondering if it would interpret 16.9 as greater or less than 16.10.
> Update branding for 16.10

- src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
- src/Build/BackEnd/Components/ProjectCache/ProjectCacheItem.cs
- src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
- src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
Fixes CI
Arcade PR passed CI -> projectcache was merged -> Arcade PR was merged using the stale CI success from before projectcache being merged.
`ProjectCachePlugin.csproj` now targets net5.0.
`Microsoft.Build.Engine.UnitTests.csproj` assigns `net5.0` TargetFramework instead of `netcoreapp2.1`.
Relaxed nullable warnings that were turned into errors in pipeline builds. @cdmihai please double check `ProjectCacheItem.cs` for what I did with the nullable warnings.
CI testing should be enough. If we want to play it safe, an `exp/` run should be good validation.
Fun fact: Apparently, `Microsoft.Build.Engine.UnitTests.csproj` manually assigns a TargetFramework?
> Fix Nullable Warnings & projectcacheplugin.csproj now targets net5.0

- .vsts-dotnet.yml
- PublishToBlob.proj
- eng/Publishing.props
- eng/common/templates/job/publish-build-assets.yml
Fixes #
Onboarding to V3 publishing. 
Link to what is V3 -> https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md#what-is-v3-publishing-how-is-it-different-from-v2
CI build - https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4391278&view=results
Promotion pipeline - https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4391300&view=results
Hardcoding of BUILD_REPOSITORY_URI is temporary fix. This will be reverted once this is fixed https://github.com/dotnet/arcade/issues/6827
> Onboarding to V3 publishing 

- .vsts-dotnet.yml
- PublishToBlob.proj
- eng/Publishing.props
- eng/common/templates/job/publish-build-assets.yml
Reverts dotnet/msbuild#6052
Going to revert this change, as the change is making the build flaky.
> Revert "Onboarding to V3 publishing "

- src/Tasks/ResolveManifestFiles.cs
**Context**
Issue: 
ClickOnce filters our assemblies that are part of the .NET Framework from publishing. This is done by looking up the assembly reference in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\<version> folder. This works reliably for .NET FX scenarios. However for .NET Core, this check is not reliable. For a packages like System.ServiceModel.Primitives, the system.servicemodel and system.servicemodel.primitives assemblies get filtered out because they are present under C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore but they are not present in .NET Core's runtime pack.
This will lead to app launch failure due to missing dependency.
**Changes Made**
Fix ClickOnce's assembly filtering code for .net core to not filter …
> Update to assembly filtering in ClickOnce task for .NET Core scenario

- .vsts-dotnet.yml
We currently aren't able to override where we download optprof data from. This is an issue when we have optprof build failures because they create drop locations which aren't populated if the optprof run fails.
Pass `OptProfDropName` in our yaml to the build script, which ultimately passes `VisualStudioIbcDrop` to the script that runs optprof. This value can override the drop our builds look at.
**Note:** `VisualStudioIbcSourceBranchName` and `IbcSourceBranchName` are **mutually exclusive**. Arcade complains if both are set. If you set `OptProfDropName`, clear the value in `IbcSourceBranchName`.
`OprProfDropName` must be of this format: `OptimizationData/dotnet/msbuild/master/20210119.2/935213/1`
[This pipeline build](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4406987&view= …
> Allow OptProf Drop Override

- src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Null reference error when ReferenceVersions are not set, introduced in https://github.com/dotnet/msbuild/pull/5990
Bug repros with https://github.com/dotnet/sdk/pull/15430. These changes were tested with that PR and fix the issue.
> Fix null reference error on ResolveAssemblyReference

- .vsts-dotnet.yml
We currently aren't able to override where we download optprof data from. This is an issue when we have optprof build failures because they create drop locations which aren't populated if the optprof run fails.
Pass `OptProfDropName` in our yaml to the build script, which ultimately passes `VisualStudioIbcDrop` to the script that runs optprof. This value can override the drop our builds look at.
**Note:** `VisualStudioIbcSourceBranchName` and `IbcSourceBranchName` are **mutually exclusive**. Arcade complains if both are set. If you set `OptProfDropName`, clear the value in `IbcSourceBranchName`.
`OprProfDropName` must be of this format: `OptimizationData/dotnet/msbuild/master/20210119.2/935213/1`
[This pipeline build](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4406987&view= …
> Allow optprof override

- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
Fixes https://github.com/dotnet/roslyn/issues/46300
Source generators fail on projects that depend on the `XamlPreCompile` target because it removes analyzers for performance reasons. Because source generators are passed in via the analyzers collection, they are also removed, which causes build failures. Roslyn added the `/skipAnalyzers` flag in https://github.com/dotnet/roslyn/pull/46669 which allows the caller to keep the analyzers item group populated, skipping the analyzers and running the generators.
Changed the `XamlPreCompile` target to match the roslyn CSC invocation, as it should.
Manually tested patching the file on VS preview and confirmed the project can succesfully build, where it didn't without the patch.
> Bring XamlPreCompile up to date with roslyn targets

- .vsts-dotnet-ci.yml
Until it can parse C# 9 syntax. Followed by issue #6058
> Disable Mono CI

- src/Shared/FileUtilities.cs
- src/Tasks.UnitTests/GenerateBindingRedirects_Tests.cs
While authoring #5238 and other PRs, I did some refactors that have been piling up. I'm upstreaming some of them here.
Simplify `#ifdef` logic (across source code)
Normalize and Fix namespaces (in Test projects)
If existing tests passes then it's A-OK!
I make sure that these changes are purely cosmetic and doesn't impact any functional changes in the release build.
> Miscellaneous refactors leftover from #5238

- src/Tasks/Microsoft.CSharp.CurrentVersion.targets
Fixes #6088
$(Nullable) not passed into csc invoked in XamlPreCompile, causing nullable waring in project with xaml and nullable enabled
Passes $(Nullable) as targets in roslyn
None
I wonder what are involved by this issue. WPF (.NET Core) is not involve.
Technically this is a critical bug to every version after 16.3 because it blocks WarningAsError.
> Pass $(Nullable) to csc in XamlPreCompile

- src/Utilities.UnitTests/ToolTask_Tests.cs
Fixes https://github.com/dotnet/msbuild/issues/4781, https://github.com/dotnet/msbuild/issues/3580.
@Forgind ptal.
> Fix FindOnPathSucceeds failing on some Linux flavors

- src/Package/MSBuild.VSSetup/files.swr
Fixes https://github.com/dotnet/msbuild/issues/6116
Include the next version of Microsoft.VisualStudio.PackageGroup.NuGet to unblock an internal team.
We should run this through an experimental branch. (not prefixed with exp/ so we can use the optprof workaround)
See teams channel
> Remove Version Requirement On M.VS.PG.NuGet
