dotnet/msbuild

dir.targets
According to MSDN (http://msdn.microsoft.com/en-us/library/7szfhaft.aspx), the
single quotes can be left off for "simple alphanumeric strings or boolean values".
This is not the case here (it is a property), so we should use single quotes.
Note that MSBuild ignores this, but it results in a parser error on Mono's xbuild.
=> dir.targets: correctly enclose 'Exists' condition in single quotes

src/XMakeCommandLine/MSBuild.csproj, src/XMakeTasks/Microsoft.Build.Tasks.csproj
Building these projects on a case-sensitive file system revealed that the file casing
is different on disk. Fixed the reference in csprojs to match the name on disk.
=> Fix casing of file references in csprojs

src/Framework/UnitTests/BuildErrorEventArgs_Tests.cs, src/Framework/UnitTests/BuildFinishedEventArgs_Tests.cs, src/Framework/UnitTests/BuildMessageEventArgs_Tests.cs, src/Framework/UnitTests/BuildStartedEventArgs_Tests.cs, src/Framework/UnitTests/BuildWarningEventArgs_Tests.cs, src/Framework/UnitTests/CriticalBuildMessageEventArgs_Tests.cs, src/Framework/UnitTests/ExternalProjectFinishedEventArgs_Tests.cs, src/Framework/UnitTests/ExternalProjectStartedEventArgs_Tests.cs, src/Framework/UnitTests/ProjectFinishedEventArgs_Tests.cs, src/Framework/UnitTests/ProjectStartedEventArgs_Tests.cs, src/Framework/UnitTests/TargetFinishedEventArgs_Tests.cs, src/Framework/UnitTests/TargetStartedEventArgs_Tests.cs, src/Framework/UnitTests/TaskCommandLineEventArgs_Tests.cs, src/Framework/UnitTests/TaskFinishedEventArgs_Tests.cs, src/Framework/UnitTests/TaskStartedEventArgs_Tests.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/UnitTests/BackEnd/EventSourceSink_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/TaskRegistry_Tests.cs, src/XMakeTasks/CreateManifestResourceName.cs
Hey guys,
Thanks for open sourcing this. Appreciate the continued effort in open sourcing more and more Microsoft software!
I noticed some typos missed in PR #7 and a couple hanging comments that I touched up.
=> Fixes typos

README.md
```
Visual Studio uses MSBuild, but it (VisualStudio) doesn't depend on Visual Studio.
^ Subject          ^ Object     ^ Subject Reference
```
doesn't make sense.
I haven't been able to sleep.
This will put my mind at ease:
> Visual Studio uses MSBuild, but MSBuild *does not* depend on Visual Studio.
=> [Nefarious Grammar] Bad sentence structure

dir.targets, src/Framework/BuildEventArgs.cs, src/Framework/BuildEventContext.cs, src/Framework/BuildFinishedEventArgs.cs, src/Framework/BuildMessageEventArgs.cs, src/Framework/IBuildEngine.cs, src/Framework/LazyFormattedBuildEventArgs.cs, src/Framework/ProjectStartedEventArgs.cs, src/Shared/CanonicalError.cs, src/Shared/FrameworkLocationHelper.cs, src/Shared/NodeEndpointOutOfProcBase.cs, src/Shared/TaskLoggingHelper.cs, src/Shared/TypeLoader.cs, src/Utilities/AppDomainIsolatedTask.cs, src/Utilities/MuxLogger.cs, src/Utilities/TaskItem.cs, src/Utilities/ToolLocationHelper.cs, src/Utilities/ToolTask.cs, src/dirs.proj
- many more remain but I focused on the visible ones (e.g. non UT)
- can provide a full listing of the remaining ones (scripted checks)
=> Fixed some typos

src/Shared/AssemblyFoldersEx.cs, src/Shared/Constants.cs
Some additional spelling fixes.
=> Spelling fixes.

src/XMakeTasks/FileIO/ReadLinesFromFile.cs, src/XMakeTasks/FileIO/WriteLinesToFile.cs, src/XMakeTasks/ListOperators/FindUnderPath.cs, src/XMakeTasks/ListOperators/RemoveDuplicates.cs
Those constructors seem to be totally unnecessary, as compiler generates empty ones by default
=> Removing redundant contructors (empty is provided by default)

src/XMakeBuildEngine/Definition/ProjectCollection.cs
The implementation of GetVersionInfo() in Mono doesn't set the ProductVersion property, so ProjectCollection.Version crashes when trying to construct the Version object from an empty string.
As a workaround, the Version object can be created using the individual components of the product version, which are properly filled by Mono. That's also more efficient that relying on string version parsing.
=> Fix Mono crash when getting the MSBuild version

dir.props, dir.targets
The targets files bootstrap NuGet.exe by downloading it on demand using
inline C# code via CodeTaskFactory.  This is not supported on xbuild
hence a build on a fresh enlistment will fail.
This change fixes that by using curl to bootstrap NuGet.exe in a
non-windows environment.
=> Fix NuGet restore

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/Microsoft.NETFramework.props, src/XMakeTasks/Microsoft.NETFramework.targets
1. Changed Microsoft.NetFramework.* file names to Microsoft.NETFramework.*
2. Disabled a call to GetRegistryValueFromView when not on Windows
=> Minor changes to props/targets files:

src/XMakeTasks/NativeMethods.cs
Fixed logic for extracting the version, culture and key token from assembly directories in the Mono GAC.
=> Fix GAC assembly name parsing for Mono

src/XMakeBuildEngine/Definition/ToolsetReader.cs
The 4.0 toolset is installed in the Mono framework directory.
Other toolsets are installed in the xbuild directory.
=> Fix loading of Mono toolsets

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Copy .mdb files when they are generated by the compiler instead of .pdb files.
=> Copy .mdb files 

Samples/TaskUsageLogger/Properties/AssemblyInfo.cs, Samples/TaskUsageLogger/TaskUsageLogger.cs, Samples/TaskUsageLogger/TaskUsageLogger.csproj, Samples/dir.props, Samples/dir.targets, Samples/dirs.proj, build.proj, src/MSBuild.sln
Creates a new 'Samples' directory and adds the 'TaskUsageLogger', a fairly simple logger I built a while back that records (in CSV format) data about all tasks run in a build.  
Also includes a couple of edits to the solution file to stabilize the IDE build experience.
=> Add sample logger 

build.pl, dir.props, dir.targets, src/Framework/UnitTests/Microsoft.Build.Framework.UnitTests.csproj, src/Utilities/UnitTests/Microsoft.Build.Utilities.UnitTests.csproj, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeCommandLine/UnitTests/CommandLineSwitches_Tests.cs, src/XMakeCommandLine/UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
Added a Perl script to build using xbuild, rebuild using generated
MSBuild, and run tests. The last two steps are optional. The outputs
can be redirected (this would include binaries, packages, and logs).
In order to be able to redirect, made some project file fixes.
=> Added build script for Mac/Linux

src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs
The AssemblyInformation class uses GetFileVersion() in mscoree to get the runtime version of an assembly, so it won't work outside Windows. With this patch, when not running on Windows a managed
version reader will be used.
=> Added implementation of GetRuntimeVersion for non-windows systems

src/XMakeBuildEngine/Definition/ToolsetReader.cs
Hitting this on Unix. Follows the same pattern as the other adds in the method.
=> Guard against duplicate keys for 4.0 toolset.

src/Shared/FileUtilities.cs, src/Shared/NativeMethodsShared.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Evaluation/Expander.cs, src/XMakeBuildEngine/Instance/ProjectInstance.cs, src/XMakeBuildEngine/Resources/Constants.cs, src/XMakeCommandLine/app.config
Fix slashes on Unix & Mac in properties that look like paths. If the
path points at the Mono framework directory, fix it up based on the
framework version.
Add some of the standard properties associated with toolsets. These
are normally found in the registry, but for Mono they are easy to
deduce.
=> XPlat compatibility changes

dir.props, dir.targets, src/.nuget/packages.config, src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Add a dependency on the Roslyn compilers NuGet. Copy binaries to the output
directory and load props file that overrides the compiler tasks parameter so
that they use the new compilers (controled by a property).
=> Allow building with Roslyn compilers

Samples/RebuildWithXmlLog.cmd, Samples/XmlFileLogger/ILogNode.cs, Samples/XmlFileLogger/ItemGroupParser.cs, Samples/XmlFileLogger/LogProcessNode.cs, Samples/XmlFileLogger/ObjectModel/Build.cs, Samples/XmlFileLogger/ObjectModel/InputParameter.cs, Samples/XmlFileLogger/ObjectModel/Item.cs, Samples/XmlFileLogger/ObjectModel/ItemGroup.cs, Samples/XmlFileLogger/ObjectModel/Message.cs, Samples/XmlFileLogger/ObjectModel/OutputItem.cs, Samples/XmlFileLogger/ObjectModel/OutputProperty.cs, Samples/XmlFileLogger/ObjectModel/Project.cs, Samples/XmlFileLogger/ObjectModel/Target.cs, Samples/XmlFileLogger/ObjectModel/Task.cs, Samples/XmlFileLogger/ObjectModel/TaskParameter.cs, Samples/XmlFileLogger/Properties/AssemblyInfo.cs, Samples/XmlFileLogger/PropertyBag.cs, Samples/XmlFileLogger/UnknownTaskParameterPrefixException.cs, Samples/XmlFileLogger/XmlFileLogger.cs, Samples/XmlFileLogger/XmlFileLogger.csproj, Samples/dir.props, Samples/dirs.proj
Adding a structured XML file logger to the samples folder.
In Visual Studio 2015, one of the changes we made to MSBuild was to enable some additional logging in diagnostics mode, specifically around task inputs and outputs. This XmlFileLogger project is a sample of how you might use that information. The output XML file is not as much of a trace log but a structure of how the project was built with inputs and outputs. I've found this especially useful when you know what parameter is used, but not where it came from and what else uses it.
* It will hold onto everything in memory in order to output the contents at the end. Probably not a good idea to use it on a really huge project. If there's demand, this could be fixed.
* Events aren't in order, especially with a multi-core build. They …
=> Adding XmlFileLogger project to the Samples folder.

build.pl
There was a space in the shebang of build.pl, making it fail when invoked with ./build.pl
Also set the execute permission on the file in git so it works automatically after cloning.
=> Fix shebang in build.pl and set execute flag

src/Shared/FileUtilities.cs, src/XMakeCommandLine/XMake.cs
Until now, switches on Mono only supported the '-' prefix instead of '/'.
This was done for simplicity to be able to determine if the parameter is a path or MSBuild switch.
By using a similar heuristic as introduced in https://github.com/Microsoft/msbuild/pull/67, we can now use slashes as well. The heuristic checks if the first segment of a string with slashes is a directory on disk, if yes it's very likely a path. Otherwise it's a switch.
Fixes #48
Note: I built MSBuild itself with these changes and using / for the switches which worked fine. I don't know where it makes sense to add unit tests since those would only work on Unix filesystems.
=> Reenable switches that start with a slash on Mono

src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs
Set MONO29679=1 to enable.
@akoeplinger, @ValMenn
=> Put workaround for Mono issue in GetFrameworkName().

.gitattributes, build.pl
Before, build.pl would always take xbuild from /usr/bin which causes problems when another xbuild is in the PATH.
Also fix line endings for *.pl to be the platforms default so it works out of the box on Linux.
=> Allow build.pl to find xbuild in current PATH

src/Shared/FrameworkLocationHelper.cs
Allow explicitly overriding the root reference assembly folder via "ReferenceAssemblyRoot" env var.
@ValMenn @AndyGerlicher
=> Add override for reference folder base path.

src/XMakeTasks/UnitTests/Exec_Tests.cs
.. Use ';' instead of '&' to separate commands
=> [tests] Fix Exec tests on Unix

build.pl, src/.nuget/Microsoft.Build.Mono.NoSymbols.nuspec, src/.nuget/Microsoft.Build.Mono.nuspec, src/.nuget/Microsoft.Build.Windows.nuspec, src/after.MSBuild.sln.targets
Created nuspec files and a target.
Updated build.pl adding -p switch to create the package.
=> Allow building nuget packages for MSBuild

src/XMakeTasks/UnitTests/Exec_Tests.cs
.. that broke the test on Unix.
=> [tests] NoTempFileLeaks - Remove unnecessary single quote ..

src/XMakeBuildEngine/Construction/Solution/SolutionFile.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionFile_Tests.cs
Fixes #62: allows empty lines in solution configuration to simulate a
scenario of source control merges that end up creating empty lines in
the following sections:
- SolutionConfigurationPlatforms
- SolutionProperties
- NestedProjects
Visual Studio can open solutions like these, and so should MSBuild.
=> Fixes #62 allows blank lines in solution configuration

src/Utilities/UnitTests/TrackedDependencies/TrackedDependenciesTests.cs
.. by fixing changing paths like "foo\\bar" to Path.Combine("foo", "bar"). And fixing it to work on systems which don't support <1sec file time information, like mac.
=> Fix TrackedDependenciesTests on mac ..

src/XMakeBuildEngine/Construction/Solution/SolutionProjectGenerator.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionProjectGenerator_Tests.cs
As identified in issue #69, there's a somewhat-rare corner case where the `TargetOutputs` of an `MSBuild` invocation does not contain the expected output.  Most of the juicy details are there.
The `SolutionConfigurationWithDependenciesRelaysItsOutputs` test was added based on the original repro case of the associated [Connect report](https://connect.microsoft.com/VisualStudio/feedback/details/1176406/msbuild-targetoutputs-does-not-include-projects-with-explicit-project-dependencies-listed) and then fixed.
It would be fabulous if this fix could also be back-ported to MSBuild 12.0 (or even 4.0), as that's where the issue was originally discovered.
=> Metaprojects should relay outputs

src/XMakeTasks/ManifestUtil/SecurityUtil.cs, src/XMakeTasks/Strings.resx
#71 Improved exception handling in _SecurityUtilities.SignFile_.
A specific check is now performed for a _null_ value in the _PrivateKey_ property.
The message prefix chosen here, `MSB3487`, may appear to have skipped two at first glance - this is intentional, based on the following comment in _Strings.resx_:
`// MSB3485 MSB3486 not used but already shipped, do not reuse`
=> #71 Improved exception handling in SecurityUtilities.SignFile

src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs
The Mono implementation looked at FrameworkDisplayName which is something like `.NET Portable Subset`, but the Windows/COM implementation got the framework identifier as `.NETPortable,Version=v4.5,Profile=Profile259`.
Changed the Mono implementation to get the first constructor argument of the attribute, which contains what we want.
/cc @JeremyKuhne now that the Mono bug is fixed, I noticed this while testing.
=> Fix getting FrameworkName from TargetFrameworkAttribute on Mono

src/XMakeTasks/UnitTests/ResolveAssemblyReference_Tests.cs
Changes instances of hardcoded paths such as:
`c:\WINNT\Microsoft.NET\Framework\v2.0.MyVersion`
to use `readonly` fields which are constructed to be valid on both
Windows and Unix. Replace all occurrences of these paths, to use the
new fields.
Also, adds a s_rootPathPrefix field that can be "C:\\" or "/".
PR-URL: #111
=> [tests] Fixes ResolveAssemblyReference tests

src/XMakeTasks/UnitTests/ResolveAssemblyReference_Tests.cs
Changes instances of hardcoded paths such as:
`c:\MyComponents\1.0`, `c:\MyLibraries\...` etc
to use readonly fields which are constructed to be valid on both
Windows and Unix. Replace all occurrences of these paths, to use the
new fields.
PR-URL: #124
=> Fixes ResolveAssemblyReference tests on mac

build.pl, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeTasks/UnitTests/ResolveAssemblyReference_Tests.cs
Exclude tests marked with category WindowsOnly on !Windows, when
running nunit from build.pl .
This is useful for disabling tests that make sense only on Windows,
eg, those that depend on presence of Registry or WinMD.
PR-URL: #125
=> [tests] Disable tests on Unix that depend on Windows only features

src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs
Fixes PropertyFunctionStaticMethod1 test.
=> [tests] Expander: Fix typo for the Unix case of the test

src/XMakeTasks/UnitTests/XamlTaskFactory_Tests.cs, src/XMakeTasks/UnitTests/XamlTestHelpers.cs
.. by using the correct case for assembly file names like:
`microsoft.build.tasks.core.dll` => `Microsoft.Build.Tasks.Core.dll`
The incorrect case causes compilation errors in the XamlTaskFactory
tests on case sensitive filesystems, for example on xfs/Linux.
=> [tests] Fix XamlTaskFactory tests on case sensitive filesystems ..

src/XMakeTasks/Copy.cs, src/XMakeTasks/NativeMethods.cs
Use the link() library function for the xplat MSBuild so creating hardlinks works on other platforms too.
See dotnet/buildtools#197
=> Copy Task: implement hardlink support for non-Windows OS

src/XMakeTasks/UnitTests/ResolveAssemblyReference_Tests.cs
.. assembly names, like:
`System, Version=10.0.0.0, Culture=Neutral, PublicKeyToken='b77a5c561934e089'`
This form is not supported by Mono. And the unquoted form is equivalent.
So, changing these to unqouted format, fixes the tests on Mac, like:
`System, Version=10.0.0.0, Culture=Neutral, PublicKeyToken=b77a5c561934e089`
=> [tests] ResolveAssemblyReference: Do not quote PublicKeyToken in ..

src/XMakeTasks/UnitTests/GenerateResourceOutOfProc_Tests.cs, src/XMakeTasks/UnitTests/GenerateResource_Tests.cs
"||" is an invalid filename on Windows but not on Unix. Some tests
depend on GenerateResource task failing because of invalid characters
in the filename. So, use "\0" as the filename for such tests,
which is invalid on Unix.
=> [tests] GenerateResource: Use NUL as the invalid char on unix

src/XMakeBuildEngine/UnitTests/Construction/SolutionFile_Tests.cs, src/XMakeTasks/Exec.cs, src/XMakeTasks/UnitTests/Exec_Tests.cs
Fixes #142 and probably #104 (thanks @akoeplinger for pointing that out!).
Definitely not an expect on code pages and cmd.exe encoding, but this works better than previously in all the scenarios I tested. 
The only remaining encoding issue I found is if the command you run has non-ansi characters (e.g. `echo 创建` was the test case I used), it will still show up as ?? on the console. I don't think that can be fixed here though.
=> Exec task unicode fix

src/XMakeTasks/UnitTests/XamlTaskFactory_Tests.cs, src/XMakeTasks/XamlTaskFactory/TaskParser.cs
TaskParser.Parse(string contentOrFile, string)
.. first argument can either be a filename or xaml string. Existing
code depended on Path.GetFullPath returning null for xml string, for
this detection. But on Unix, xml string could be a valid file path.
So, instead we utilize the knowledge that:
On Windows:
- xml string will be an invalid file path, so, Path.GetFullPath will
return null
- xml string cannot be a rooted path ("C:\\<abc />")
On Unix:
- xml string is a valid path, this is not useful as Path.GetFullPath
will return !null in most cases
- xml string cannot be a rooted path ("/foo/<abc />")
We have an additional check for rooted paths, just to be able to throw
the correct error in case of:
- Unix, @contentOrFile being a non-existant file path
An additional test is added for this …
=> [xaml] TaskParser.Parse: Handle detection of content or file on Unix.

src/XMakeBuildEngine/UnitTests/Construction/SolutionFile_Tests.cs, src/XMakeTasks/Exec.cs, src/XMakeTasks/UnitTests/Exec_Tests.cs
This just catches us up to the latest master, but it's a nontrivial merge so I figured I'd get it reviewed separately.
=> Merge Unicode-related exec changes into xplat

dir.props, src/Shared/CommunicationsUtilities.cs, src/Shared/FrameworkLocationHelper.cs, src/Shared/LogMessagePacketBase.cs, src/Shared/TaskEngineAssemblyResolver.cs, src/Shared/TaskHostConfiguration.cs, src/Shared/TaskLoader.cs, src/Shared/TaskLoggingHelper.cs, src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs, src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs, src/XMakeBuildEngine/BackEnd/Components/BuildComponentFactoryCollection.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/LogMessagePacket.cs, src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TaskBuilder.cs, src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TaskHost.cs, src/XMakeBuildEngine/BackEnd/Node/InProcNode.cs, src/XMakeBuildEngine/BackEnd/Node/NodeConfiguration.cs, src/XMakeBuildEngine/BackEnd/TaskExecutionHost/AddInParts/ITaskExecutionHost.cs, src/XMakeBuildEngine/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/XMakeBuildEngine/Debugger/DebuggerManager.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs, src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs, src/XMakeBuildEngine/Instance/TaskFactories/AssemblyTaskFactory.cs, src/XMakeBuildEngine/Instance/TaskFactories/TaskHostTask.cs, src/XMakeBuildEngine/Instance/TaskRegistry.cs, src/XMakeBuildEngine/Microsoft.Build.csproj
This pull request finishes the changes necessary to successfully compile Microsoft.Build for .NET Core.  Lots of code which depended on features which weren't available was simply disabled, so more work will be needed to make sure that the code works on .NET Core.
=> Port Microsoft.Build to .NET Core

src/Shared/TempFileUtilities.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionFile_Tests.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionProjectGenerator_Tests.cs
- I think a test was added that changed (static) state in the
ProjectCollection's Global Project Collection. This was causing a few
tests to fail asserts depending on what order things ran. I just set it
to unload after each run.
- While I was there I couldn't help but change the logic that creates a
temp file and immediately deletes it and adds an extension to it.
Closed #164
=> Fix broken unit tests

dir.props, src/Framework/LazyFormattedBuildEventArgs.cs, src/Shared/ProjectErrorUtilities.cs, src/Shared/ResourceUtilities.cs, src/Shared/TaskLoggingHelperExtension.cs, src/Utilities/TrackedDependencies/CanonicalTrackedOutputFiles.cs, src/Utilities/TrackedDependencies/FlatTrackingData.cs, src/Utilities/TrackedDependencies/TrackedDependencies.cs, src/Utilities/UnitTests/TrackedDependencies/MockEngine.cs, src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/XMakeBuildEngine/Debugger/DebuggerLocalType.cs, src/XMakeBuildEngine/Debugger/DebuggerManager.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Instance/ProjectInstance.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeCommandLine/native.rc, src/XMakeTasks/CommandLineBuilderExtension.cs, src/XMakeTasks/DataDriven/DataDrivenToolTask.cs, src/XMakeTasks/XMakeTasksUnitTests/XMakeTasksUnitTests.csproj
An MsbuildDebugger property must be added to a configuration to enable.
Removed a few unused condition constants that are no longer used.
=> Made MSBuild Debugger compilation conditional.

src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/Utilities/UnitTests/TrackedDependencies/FileTrackerTests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/MSBuild_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/TaskBuilder_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/TaskRegistry_Tests.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionProjectGenerator_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/ItemDefinitionGroup_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsVersion_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/Toolset_Tests.cs, src/XMakeBuildEngine/UnitTests/EscapingInProjects_Tests.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Evaluator_Tests.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ProjectRootElementCache_Tests.cs, src/XMakeBuildEngine/UnitTests/InvalidProjectFileException_Tests.cs, src/XMakeBuildEngine/UnitTests/TargetsFile_Test.cs, src/XMakeCommandLine/UnitTests/XMake_Tests.cs, src/XMakeTasks/UnitTests/GenerateResource_Tests.cs, src/XMakeTasks/UnitTests/MSBuild_Tests.cs, src/XMakeTasks/UnitTests/XamlDataDrivenToolTask_Tests.cs
Between the signing change and adding Roslyn toolset components, many of
the unit tests I previously disabled now work. There are a few left that
have issues still, I didn't want to spend too much time right now though.
=> Re-enabling unit tests

dir.targets
This will allow the CI build to have nice displays for our test results,
as well as an overall pass/fail for the build script.
Note: there's a corresponding Jenkins definition change.  I made it for the PR build so creating this request *should* show test results.
=> Preserve Xunit test result XML

BuildAndCopy.cmd, CreatePrivateMSBuildEnvironment.proj, RebuildWithLocalMSBuild.cmd, dir.props
This addresses the issues I ran into in #190, though I agree with @dsplaisted that a better long-term solution (with all targets + tasks packaged up and referenced through nuget) will be necessary.
There was a subtle problem with the way we were building the second time
in RebuildWithLocalMSBuild.cmd before.  Because the newly-built MSBuild
was toolsVersion 14.1, it looked for paths like
C:\Program Files (x86)\MSBuild\14.1\Microsoft.Common.props
which naturally don't exist--MSBuild 14.1 exists only within this folder
where we built it.
This change alters RebuildWithLocalMSBuild and friends to build out an
MSBuildExtensionsPath folder local to the repo that can be used by setting
/p:BootstrappedMSBuild=true.
Unfortunately, the .targets and .props files contained within the MSBuild
repo …
=> Use local extensions when building post-bootstrap

.gitignore, build.cmd, dir.props, dir.targets, src/.nuget/NuGet.Config, src/.nuget/packages.config, src/CopyTestPrerequisites.proj, src/Framework/UnitTests/Microsoft.Build.Framework.UnitTests.csproj, src/Framework/UnitTests/project.json, src/Framework/UnitTests/project.lock.json, src/XMakeBuildEngine/project.lock.json, src/dir.targets, src/xunit.runner.json
Before this change, we couldn't run xunit tests from within Visual Studio because xunit couldn't load the assemblies using shadow copies, and had no way to disable shadow copies.  The latest xunit (2.1.0-rc1), however, fixes xunit/xunit#560 and allows disabling shadow copies.
We now run xunit tests two ways: in VS through the visual studio runner, and at build time using the MSBuild runner.
=> Update to latest xunit and adopt VS test runner

build.cmd, build.proj, dir.props, dir.targets
This PR updates the build infrastructure to be closer to the current version in dotnet/buildtools.  It also downloads NuGet.exe as part of the MSBuild build instead of build.cmd.  This will help it work with the build lab infrastructure which needs to invoke an MSBuild project for the build.
=> Bootstrap NuGet download with msbuild instead of build.comd

build.proj
When we moved package restore from build.cmd to build.proj, we stopped
restoring the packages required for "normal" reasons, as opposed to build
tools.
This adds a step that will restore the packages from the entry point
project.
It's unfortunate that nuget doesn't understand traversal projects, which
means restoring packages based on the .sln rather than the list in
build.proj which will actually be built.  We could potentially also
restore **\project.json, but then that would require N calls to nuget.exe.
This seems better for now.
I noticed this problem when I built on my laptop (which hadn't built since before the nuget v3 switcheroo and `build.proj` change, and got some errors:
```
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(83,5): error : The package …
```
=> Restore NuGet packages from build.proj

build.proj, dir.targets
Fixes issue building when NuGet packages aren't present yet
=> Don't import compilers props file from NuGet package during traversal build (when it may not yet be restored)

src/XMakeTasks/Exec.cs
In the, probably very rare, case you don't have System32 on your path the
chcp command will fail. Changed to use the full path off of %SystemRoot%.
=> Update chcp command to use full path.

dir.targets
I had a situation where I wanted to make sure I had the latest nuget.exe,
so I deleted it, assuming that this target would re-download it.  It
didn't, because the only listed output of the target (the
I-downloaded-stuff semaphore) was up to date relative to the inputs.
Adding the .exe as an output resolves this.
Really, we should probablys split this target into two (download nuget.exe
and restore tools) for finer-grained incrementality, but this is quicker
(we should also resolve the race conditions here by moving these tasks to
a separate project so that there's no race created by doing the restore in
all projects).
=> Add nuget.exe to outputs of _RestoreBuildTools

src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/UnitTests/WriteCodeFragment_Tests.cs, src/XMakeTasks/WriteCodeFragment.cs
This is not a great long term solution to this, but it works for all the test cases (and there were quite a few) and it was quick to make. A better solution would be to use Roslyn, but we already have a reference to Microsoft.Build.Tasks.CodeAnalysis which depends on part of Roslyn (but not enough) and I don't want to introduce changes to that at this point.
=> Adding WriteCodeFragment to NetCore build

src/XMakeBuildEngine/UnitTests/BackEnd/TaskItemComparer.cs
(Courtesy of Viva64 and their PVS-Studio static analyzer. http://habrahabr.ru/company/pvs-studio/blog/268001/ )
=> Fixed a typo in TaskItemComparer

src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs, src/XMakeBuildEngine/Definition/ProjectCollection.cs, src/XMakeBuildEngine/UnitTests/BackEnd/MSBuild_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsetReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Evaluator_Tests.cs, src/XMakeCommandLine/XMake.cs
Previously, the "default" ToolsetDefinitionLocation settings were scattered across the tree as Registry | ConfigurationFile (or vice-versa).  Unifying those into a build-in enum member gives us a nice way to centralize changes . . .
Which we want to do for netcore, because netcore does not support reading from the registry (doesn't exist cross-platform) or the configuration file (netcore doesn't support those APIs).  This was aready done in xmake.cs, but that change didn't affect unit tests, many of which were failing because they couldn't find the current toolset version (14.1) in the registry--where they didn't need to be looking!
=> Unify default ToolsetDefinitionLocation

dir.props, src/XMakeBuildEngine/Instance/TaskRegistry.cs, src/XMakeBuildEngine/Resources/Strings.resx, src/XMakeBuildEngine/UnitTests/EscapingInProjects_Tests.cs
This is a start down the road to getting tests passing on CoreCLR.
I think the main thing to discuss is strategy.  In this PR I've done this:
- Introduce new feature flags for the high-level MSBuild features that are disabled.
- `#if`ed out tests that touch the high-level features using those flags.
- Added the first error in what will be a series that we'll throw when a feature is disabled.
Pros to this approach:
- Easy to understand why a test is disabled.
- Hopefully easy to enable a feature by setting that feature flag, then tracking down and fixing test failures.
- Easy to run tests because expected-to-fail tests aren't even built.
Cons:
- Feature flags for tests (based on MSBuild features) are decoupled from the reason features are disabled (based on CoreCLR features).
- Compiling …
=> Higher-level feature flags for test disablement

src/XMakeBuildEngine/Construction/ProjectRootElement.cs
Many unit tests were failing on .NET Core because of a subtle difference
in behavior between the XmlTextReader we use on full framework and the
XmlReader we use in its absence--when disposed, XmlTextReader closed the
file, while XmlReader does so only when told to do so explicitly.
Since project files were still open, unit test cleanup that attempted to
delete the test project files was failing with a file-in-use
IOException.  That's bad, but more generally we shouldn't hold a lock on
the files for longer than we need to, so we should match the
full-framework behavior.
This reduces test failures in Engine from 241 to 179.
=> Close project files after reading them in Core

src/XMakeTasks/UnitTests/AssignCulture_Tests.cs
This test relied on culture-checking code that is no longer valid, since
ce30ce4 removed the concept of IsValidCultureString in favor of the
just-try-it-and-see-what-the-OS says technique which is currently favored.
=> Remove LooksLikeCultureButIsnt test

src/XMakeBuildEngine/Evaluation/Expander.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs
This fixes #249, at least for unit tests.
@ValMenn does this look ok?  I'm a little concerned about fixing paths at the list-of-paths level, but this does fix all of the unit tests we have.
=> Work around universal string coercion in property functions

src/XMakeCommandLine/XMake.cs
Fix for issue #261.
Extract out common ifdef code from MSBuildApp.GatherAllSwitches(): regardless of the ifdef branch, the first argument needs to be deleted since it is not a command line argument but the executable name.
I also extracted out another code snippet that seemed common to both ifdef branches.
=> Logger bug #261

dir.targets
Workaround for #224
The Windows SDK plugin for Visual Studio adds a msbuild file that represents a hidden dependency for the MSBuild build process.
Added a target early in the build process to check for the existence of this file. The target runs right before _RestoreBuildToolsWrapper, which is the first common target between master and xplat builds.
=> Add target to check for Windows SDK presence

src/XMakeTasks/GetSDKReferenceFiles.cs
- Bug when the directoryToFileList started with the redistFilePath but
was not actually a match (e.g. folder ending in ARM would watch ARM64).
- To fix the issue I added a trailing slash to both sides.
=> Fix GetSDKReferenceFiles folder compare bug

src/XMakeCommandLine/XMake.cs
MSBuild originally used Environment.commandline to get the command line
arguments.
However, .Net Core removed the commandline property.
In consequence, the first element of the new args array has to contain
the executable path so as not to break downstream code. 
MSBuildApp.GatherAllSwitches expects the first argument to be the executable name. It then stores it separately into a field and deletes it from the args list. 
If the executable is not there,  the first valid argument is stored as the executable name and gets deleted.
Therefore main has to ensure that the first argument is the executable.
@AndyGerlicher @dsplaisted @rainersigwald
=> Insert Executable path as first element of args

README.md
Visual Studio seems to get cranky if you don't restore packages before
opening src/MSBuild.sln, so tell users how to do that.
I'm not sure this is the best approach, but at least it seems to work.
<strike>A similar change is also needed to <https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging>, but unfortunately github wikis do not support pull requests, so someone with write access to the wiki will have to take care of that.</strike>
Er, wait, your wiki is actually wiki, unlike most github wikis, so I made the wiki edit already!  Hooray for the broken link in RebuildWithLocalMSBuild.cmd, which made me notice this (by virtue of presenting me with a big fat edit box instead of an error message).
=> Add "Restore NuGet packages" build step to README.md

NuGet.Config, build.proj
- Update NuGet.Config so that packages will be restored to packages folder in repo root, instead of one level up
- Add build option to skip bulk package restore, since this isn't needed if you haven't changed the packages, but seems to be slow anyway
=> Fix repository path in NuGet.Config, add option to skip bulk restore

src/XMakeCommandLine/UnitTests/XMake_Tests.cs
Fixes #261 
I added a wrapper method runMSBuildWithinCoreRun that is now called by all the "MSBuild.exe" calling tests.
After talking to Daniel, it seems that in the future msbuild might be called from within other runtimes as well. The above mentioned wrapper should make it easier to generalize those tests to run in any runtime.
@AndyGerlicher @rainersigwald @dsplaisted
=> Update CommandLine tests that invoke msbuild.exe to invoke it through corerun.exe

src/Shared/CommunicationsUtilities.cs, src/Shared/FileUtilities.GetFolderPath.cs, src/Shared/NativeMethodsShared.cs, src/Utilities/ToolTask.cs, src/Utilities/UnitTests/ToolTask_Tests.cs, src/XMakeBuildEngine/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs, src/XMakeBuildEngine/Logging/BaseConsoleLogger.cs, src/XMakeBuildEngine/Logging/ConsoleLogger.cs, src/XMakeBuildEngine/Utilities/Utilities.cs, src/XMakeTasks/Exec.cs, src/nuget/Microsoft.Build.Tasks.Core.nuspec, src/nuget/Microsoft.Build.Utilities.Core.nuspec, src/nuget/Microsoft.Build.nuspec, targets/runtime.project.json, targets/runtime.project.lock.json
These changes resolve a number of issues MSBuild encounters on startup. All of them are pretty minor.
Note, that when the compilers are copied into the output directory, the System.Collections.Immutable.dll and System.Reflection.Metadata.dll may get overwritten with earlier versions (depends on file dates). This is a separate issue, but if correct versions are present, the result can build a simple project.
=> Changes that allow MSBuild to run on Linux

src/Shared/Compat/TypeExtensions.cs, src/Shared/Compat/defaultbinder.cs, src/XMakeBuildEngine/Evaluation/Expander.cs, src/XMakeBuildEngine/Resources/Constants.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs
Fixes #281, and should also fix issues encountered trying to self-build or build corefx where property functions (such as those calling `String.TrimEnd()`) would fail.
The root cause of the issue was that in porting to .NET Core, I replaced a call to Type.GetMethod with logic that was more strict, requiring all argument types to be assignable to the parameter types, which didn't allow for argument coercion.  This change pulls in more of the reflection code from `RuntimeType` and `DefaultBinder` to more closely match full Framework MSBuild's behavior.
=> Fix argument coercion in property functions

src/XMakeBuildEngine/Logging/FileLogger.cs, src/XMakeBuildEngine/UnitTests/FileLogger_Tests.cs, src/XMakeTasks/Exec.cs, src/XMakeTasks/UnitTests/Exec_Tests.cs
Fixes #251 
Will conflict with concurrent PR #246 
Exec task:
- the default encoding is UTF-8
- the windows and unix consoles are forced to use utf-8
Filelogger:
- default encoding is UTF-8 with BOM headings
@ValMenn @AndyGerlicher @rainersigwald
=> Fix test failures due to Exec and FileLogger encoding issues

src/Shared/MSBuildNameIgnoreCaseComparer.cs, src/Shared/NativeMethodsShared.cs, src/Utilities/ProcessorArchitecture.cs, src/Utilities/ToolLocationHelper.cs, src/Utilities/UnitTests/ProcessorArchitecture_Tests.cs
GetSystemInfo from in kernel32.dll was used for one purpose - to
obtain processor architecture. Refactor code to query for processor
architecture instead of the system info. Added appropriate property
to NativeMethodsShared and implemented equivalent for Unix (common
for Linux & OSX).
=> Implement xplat Processor Architecture query

src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/Utilities/UnitTests/ToolTask_Tests.cs, src/XMakeCommandLine/UnitTests/XMake_Tests.cs, src/XMakeTasks/Exec.cs, src/XMakeTasks/UnitTests/Exec_Tests.cs
1. Make sure we quote string that follows "sh -c" in Exec and ToolTask
2. If there is nothing following "sh -c", Unix shell
becomes interactive. Prevent it by adding an 'echo'
to the command.
3. Fix encoding environment variables in Exec task
4. Minor text fixes related to casing and slashes
=> Fix Exec and ToolTask for Linux and minor text fixes

src/XMakeTasks/AssemblyRegistrationCache.cs, src/XMakeTasks/ResGenDependencies.cs, src/XMakeTasks/ResolveComReferenceCache.cs, src/XMakeTasks/StateFileBase.cs
This fixes the scenario of switching builds using RTM and Update 1. Normal usage this should only be for an uninstall scenario since MSBuild is typically in the GAC, but in cases of a checked in toolset or using the open source version we should be backwards compatible. This is just renaming the fields back for the cache classes.
=> Generate resources cache fix

src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
I disabled the 2 tests that PR #296 broke because they either use the registry or windows special folders.
=> Disable tests for registry or special folders

targets/DeployDependencies.proj
I'm trying to chase down the real issue, but for now this will hopefully
work around problems with failures related to nuget restore not doing the
right thing on "clean" machines.
=> Restore runtime twice to work around #262

CompatBaseline.txt, src/Utilities/CommandLineBuilder.cs, src/XMakeTasks/UnitTests/CommandLineBuilderExtension_Tests.cs
This refers to the compatibility report in issue #299.
Makes FixCommandLineSwitch internal and adjusts a test in order to avoid namespaces conflicts (that would have been caused by an internalVisibleTo)
=> Fix Compatibility Issues

src/XMakeTasks/UnitTests/GenerateResource_Tests.cs
This fixes the bad build caused by #311 due to concurrent PRs.
=> Remove FixCommandLineSwitch from GenerateResource_Tests

src/XMakeTasks/CodeTaskFactory.cs, src/XMakeTasks/UnitTests/CodeTaskFactoryTests.cs
- Check to see if the TMP folder exists before calling CompileAssemblyFromSource.
- Added unit test to cover scenario where the TMP path doesn't exist.
Closes #328
=> Modifying CodeTaskFactory to create the TMP folder.

src/Utilities/CommandLineBuilder.cs, src/Utilities/UnitTests/CommandLineBuilder_Tests.cs, src/XMakeTasks/UnitTests/Al_Tests.cs, src/XMakeTasks/UnitTests/AxImp_Tests.cs, src/XMakeTasks/UnitTests/AxTlbBaseTask_Tests.cs, src/XMakeTasks/UnitTests/CommandLineBuilderExtension_Tests.cs, src/XMakeTasks/UnitTests/GenerateResourceOutOfProc_Tests.cs, src/XMakeTasks/UnitTests/TlbImp_Tests.cs, src/XMakeTasks/UnitTests/WinMDExp_Tests.cs
On Unix, we convert switches of the form `/foo` to `-foo`, transparently for
tasks and in some cases explicitly in the tasks. This is not required
as the relevant tools (eg. mcs/csc) accept both style of switches. If it is
really required in a particular case, then the task should do that explicitly,
rather than doing it under the covers (`CommandLineBuilder.AppendSwitch`).
The tests also used `CommandLineBuilder.FixCommandLineSwitch` to match the switch
change on Unix. This is also changed to match the changed behaviour.
Following the same theme, `CommandLineBuilder.FixCommandLineSwitch` is no
longer used or required, so, it is also removed.
=> Do not convert switches like `/foo` to `-foo` on Unix

dir.props
In order to eliminate the specific Debug-NetCore-Ubuntu configuration I had to extract out the properties it set (TargetPlatformIdentifier, RuntimeSystem, TargetSystem, RuntimeArchitecture).
By default these now self define based on the current OS. 
For deploying on different platforms than the host one, the TargetPlatformIdentifier needs to be specified
=> Remove Ubuntu configuration: system and architecture properties are now self defining

src/XMakeBuildEngine/UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs
This test seems a bit flaky; it's failed a few times in CI builds for no
discernable reason (and passed on retry of the same source).
Unfortunately, the failure was just that an Assert.True failed, which
didn't provide much actionable information (not even which of the two
asserts it was).
In the hopes of making the next failure clearer, this change:
* Splits the two asserts into two tests so we can see which is failing
* Moves to Assert.Equals, to get xunit's stringification of the objects
on failure (so we can hopefully see a difference).
=> Improve diagnosability of LogBuildStarted test

src/XMakeTasks/Exec.cs, src/XMakeTasks/UnitTests/Exec_Tests.cs
* Use source (.) to run shell scripts -- no need for exec permission
* Fix encoding on Linux so that scripts don't have a BOM
* Since exit code on failure is always 1 on Linux added additional checks.
* A test that checks the exit code is fixed to account for the fact that Linux exit codes are byte-wide
=> Fix Exec tasks & tests for *nix

Samples/dir.targets, src/dir.targets
When we build msbuild using the system installed msbuild, all the
involved build dependencies (DLLs, EXEs, target files) should be system
dependencies, not a mix between system dependencies and app local ones.
This fix deletes the import in the dir.targets which overrides the
dependency location regardless of the build. The consequence of this
import was that the system build used the program files
Microsoft.CSharp.Core.Targets but the app local CSC task. On VS update 1
this breaks the build.
A future task would be to ensure that the applocal msbuild can build itself by restoring the RebuildWithLocalMSbuild script to actually rebuild with local msbuild, and then to check that the msbuild.log that nothing outside of the bin folder is referenced (except Nuget caches).
=> Use system dependencies on system builds

CreatePrivateMSBuildEnvironment.proj, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProc.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs, src/XMakeBuildEngine/BackEnd/Node/OutOfProcNode.cs, src/XMakeCommandLine/XMake.cs
Resolves #339 by requiring that any node that will be used as a worker have the same value for `nodeReuse` as the coordinator.
=> Avoid ambient node reuse when not requested

src/XMakeCommandLine/XMake.cs
Extra check if file is really a solution file.
Because the Windows API has legacy behavior, the searchpattern *.sln will be converted to *.sln*.
=> #360 - MSBuild accidentally enumerates *.sln* when searching for solutions

src/dirs.proj, src/nuget/Microsoft.Build.Framework.nuspec, src/nuget/Microsoft.Build.Tasks.Core.nuspec, src/nuget/Microsoft.Build.Utilities.Core.nuspec, src/nuget/Microsoft.Build.nuspec
Currently the NuGet packages have '<frameworkAssembly/>' elements in them which causes the in-box reference assembly version of the DLL to be referenced instead of the one in the NuGet package when compiling on .NET Framework.
This wasn't working when compiling with the .NET CLI, so this PR changes the NuGet packages so that the DLLs in the packages will now be used when compiling for .NET Framework.
=> Don't use frameworkAssembly references in NuGet packages for .NET Framework

NuGet.Config, dir.props, override.targets, src/.nuget/packageLoad.targets, src/.nuget/packages.OSX.config, src/.nuget/packages.config, src/XMakeBuildEngine/project.json, src/XMakeCommandLine/project.json, targets/DeployDependencies.proj, targets/LinuxDeployDependencies.proj, targets/runtime.project.json
Continuation of PR #369 
The previous PR included bumped up corefx dependencies which crashed windows tests. For this PR I reset all dependencies to the xplat baseline and only bumped up when necessary for osx compilation.
In addition:
- addressed comments from the previous PR.
- left the xunit VS runner untouched for now.
=> Osx Build (with xplat based dependencies)

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
The test for _DebugSymbolsProduced was not taking into account the new portable PDB setting.
=> Portable PDBs need to be copied to output

.gitattributes, cibuild.sh, netci.groovy
- Added shell script for Linux and OSX. It has two scopes, compilation and testing.
- Updated netci.groovy script to account for Linux and OSX. Linux is currently switched off.
@mmitche 
Items left:
=> Work In Progress: CI script for Linux and OSX

src/Utilities/TaskItem.cs
This appears to have been accidentally conditionalized away for .NET Core
builds in 70aebd1.
Fixes #378.
=> Override ToString for TaskItem

netci.groovy
Linux and OSX do not yet run tests, they just compile.
Moved the line instead of passing skipIfNoTestFiles  = true to
addXunitDotNetResults as a sanity measure to ensure we do not loose the
test phase by mistake and not notice it. :)
@mmitche: would merging this to master cause the Jenkins projects to be silently recreated/updated or will they get duplicated? (if they get duplicated, is there a method we could call in the netci script to clean previous projects?)
=> Only archive CI tests for windows

cibuild.sh
The CI on master for Ubuntu and OSX was failing due to missing msbuild.log file (we don't build crossplatform on master).
Since I could not find a way to differentiate PRs targeting master from the ones targeting xplat within the netci.groovy script, I updated the stub cibuild.sh to output stub logs.
@mmitche
=> Stub log to avoid CI failing on master for crossplatform

BuildAndCopy.cmd, RebuildWithLocalMSBuild.cmd, build.cmd, netci.groovy
I was looking at enabling CI for full-framework builds in xplat and noticed again that we don't reliably fail the script on intermediate step failures.  This has caused some confusion in the past and it's clearly just a bad idea.
=> Improve CI diagnosability

src/XMakeBuildEngine/Construction/Solution/SolutionProjectGenerator.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionProjectGenerator_Tests.cs
Fix for #396.  Detailed description in the commit message.
@olivierdagenais I'd appreciate it if you could take a look at this.  I made some pretty big changes to the `SolutionConfigurationWithDependenciesRelaysItsOutputs` test that I *think* capture the correct intent of [the Connect bug](https://connect.microsoft.com/VisualStudio/feedback/details/1176406/msbuild-targetoutputs-does-not-include-projects-with-explicit-project-dependencies-listed) and #69, but they're very different from what was there before.
Note: I untabified some of the embedded MSBuild in the test, so looking at this with [?w=1](https://github.com/Microsoft/msbuild/pull/402/files?w=1) is recommended.
=> Return only new outputs as metaproject outputs

build.pl
`build.pl` is vulnerable to shell command injection if there are metacharacters in various paths.  This patch fixes these issues.  It also does some cleanup of the Perl code.
=> Fix shell injection issues in build.pl

cibuild.sh
Add a --target (CoreCLR|Mono) command line option, with a fallback
to CoreCLR. This just sets the configuration to use `Debug-Netcore`
or `Debug-MONO` . This helps to compile and run tests using `cibuild.sh`
for mono.
=> [cibuild.sh] Add command line option to select CoreCLR or Mono build

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/Microsoft.NETFramework.CurrentVersion.props
Tests that used `Microsoft.Common.targets` were failing after 0437195
because the common targets/props had some registry properties. For now,
I'm just commenting those parts of the files out in this branch, but this
will require a long-term fix so that we can restore the registry lookups
for full-framework-MSBuild-requiring projects.
=> Comment out registry access in our targets

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
There is not currently an `al.exe` that works on Linux, so satellite
assemblies are not creatable there. Fortunately, they're not needed, so we
can just stop trying to create them when running .NET Core MSBuild.
=> Do not create satellite assemblies in .NET Core

src/XMakeCommandLine/CommandLineSwitches.cs, src/XMakeCommandLine/XMake.cs
New build is not showing the debug message, it's handled by a condition  in `ShowHelpMessage()`.
I have removed the condition and debug message.
=> Removed help message for /debug in #426

dir.props, src/Shared/TaskHostConfiguration.cs, src/XMakeTasks/GenerateResource.cs
In some places in the code, there was an assumption that
FEATURE_APPDOMAIN and FEATURE_BINARY_SERIALIZATION
are always enabled/disabled together, which breaks the build
if you only enable FEATURE_APPDOMAIN. This fixes those issues
before enabling appdomain on mono.
Without this things like CodeTaskFactory don't work, TaskRegistry just
throws an error.
=> Enable FEATURE_APPDOMAIN for mono builds

src/XMakeTasks/Exec.cs, src/XMakeTasks/UnitTests/Exec_Tests.cs
Proposed change for #397. This should revert the change to the existing behavior (will not change the code page) in almost all cases, but still allow for those who do have non-ANSI characters in their Command. This solution seems a little unfortunate, and we are open to additional input if anyone has a better idea. I tried to implement it with an escape hatch (setting Never or Always on the task) so the user has more control if absolutely necessary.
Exec task was previously changed to use UTF8 code page because of an issue
running commands that contained non-ANSI characters. This turned out to be
problematic with some older tools that did not correctly support the cmd
code page change. With this change, we will only change the code page when
the command the Exec task is running cannot be …
=> Update Exec task to only use UTF8 when required.

src/XMakeBuildEngine/Instance/ProjectInstance.cs
Added in foreach loop in projecttaskinstance in order to check individual loggers for verbosity setting; if diagnostic, then set logtaskinputs to true, following implementation approach as used in XMake.
=> Tied to issue #400, logtaskinputs setting on projectinstance object

src/XMakeBuildEngine/Evaluation/Conditionals/Scanner.cs, src/XMakeBuildEngine/UnitTests/Parser_Tests.cs
I suppose there is a bug in a method ```ParseInternalItemList```. It just reads token to the first closing paren, which is causing creation of incorrect token ```@(MainEmbeddedFiles->AnyHaveMetadataValue('Filename', 'UserControl1')``` instead ```@(MainEmbeddedFiles->AnyHaveMetadataValue('Filename', 'UserControl1'))```. 
I made a fix and add some unit tests. @rainersigwald can you take a look on my solution?
=> #368 fixed Scanner to consume correct close paren.

src/XMakeTasks/ManifestUtil/SecurityUtil.cs, src/XMakeTasks/ManifestUtil/Strings.resx
Added search path in `SecurityUtil.SigntoolNotFound` message, So it'll be easier to locate the exact path. For proper messaging move the `ApplicationException` to `GetPathToTool` method.
=> Added signtool.exe path in SecurityUtil.SigntoolNotFound error, fix #425

NuGet.Config, cibuild.sh, dir.props, src/.nuget/packageLoad.targets, src/.nuget/packages.OSX.config
1. Remove some v2 sources from NuGet.Config
2. Update dnx package to rc2-16357 (the old package is no longer available)
3. Use 'ulimit -n 2500' to avoid 'Too many open files' error from dnx
4. Make sure mono compilers that come with the mono MSBuild bootstrap package have executable permission.
=> Fix some issues with OSX build

build.cmd, src/Utilities/ToolLocationHelper.cs, src/XMakeTasks/GetReferenceAssemblyPaths.cs, src/XMakeTasks/UnitTests/GetReferencePaths_Tests.cs
Some fields were not protected by the lock. Added the lock.
This branch was made out of the update 2 branch, therefore this PR is also a merge of update2 into master
=> Make the static state of ToolLocationHelper thread safe

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
This reverts commit 658fc55ea8af591299d7d59bc7a4fd3908b39f6d.
That change detected "is building using the Mono compiler" through the
condition "is not on Windows_NT", which isn't accurate since the Roslyn
compiler works fine on Linux and OS X now. That caused errors to find
`.mdb` files when building with Roslyn and creating debug symbols on
Unices--so this fixes #459.
=> Revert "Copy .mdb files when they are generated by the compiler instead"

src/XMakeCommandLine/XMake.cs, src/XMakeTasks/Dependencies.cs, src/XMakeTasks/StateFileBase.cs
_602201c_ When reverting the CodeFormatter private field name changes (#314), the Dependencies class was missed. This causes an incompatibility going from  Update 1 back to RTM and causes a null ref. This change fixes the compat issue (rename the field) and updates the serialization version to ensure U1 -> U2 works as expected.
_c863538_ Looks like the field was renamed for STANDALONEBUILD but not otherwise.Correcting this.
=> ResGen Cache Serialization Fix

src/xunit.runner.json
This is so that the Jenkins plugin that gathers xUnit test results shows the correct test names, because the converter trims the first portion of the test name, assuming that it is prefixed with the full class name
=> Show full class and method name in output results

src/Utilities/UnitTests/project.json, src/Utilities/project.json, src/XMakeBuildEngine/UnitTests/project.json, src/XMakeBuildEngine/project.json, src/XMakeCommandLine/UnitTests/project.json, src/XMakeCommandLine/project.json, src/XMakeTasks/UnitTests/project.json, src/XMakeTasks/project.json
As advertised just removed usage of "Microsoft.Win32.Registry" from ...\msbuild\src\Utilities\project.json and ...\msbuild\src\XMakeTasks\project.json (#439).
=> #439 - Removed usage "Microsoft.Win32.Registry" from project.json.

src/XMakeCommandLine/CommandLineSwitches.cs, src/XMakeCommandLine/UnitTests/CommandLineSwitches_Tests.cs
This PR relates to solve an issue reported to the CakeBuild system ( cake-build/cake#680 ).
Currently when running MSBuild and specifying multiple properties all aren't logged when diagnostic verbosity.
This might be by design? but when debugging and logging at least I and 1 more users find this a bit confusing when parts of the command line is omitted.
I tracked the issue to GetEquivalentCommandLineExceptProjectFile() in [./src/XMakeCommandLine/XMake.cs#L1840](https://github.com/Microsoft/msbuild/blob/a804b8a3e47f388a31272c0cf95da888f99a2457/src/XMakeCommandLine/XMake.cs#L1840)
And the value is set on each iteration in [./src/XMakeCommandLine/CommandLineSwitches.cs#L448](https://github.com/Microsoft/msbuild/blob/a804b8a3e47f388a31272c0cf95da888f99a2457/src/XMakeCommandLine/CommandLineSwit …
=> Adjusts so all command line propertied are logged when using diagnostic

src/XMakeCommandLine/UnitTests/XMake_Tests.cs
Environment.SpecialFolder.System resolves to "" on Mono, so, instead
hardcode the path to "/bin/cat" on !Windows
=> CommandLineTest: Use correct path to 'cat' on !Windows

src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs, src/XMakeTasks/project.json
getting the TargetFrameworkAttribute custom attribute.
Say, it is trying to get the attribute for Abc.dll, but that assembly
has a custom attribute from an assembly Xyz.dll. Mono will try to look
for Xyz.dll, and crash if it cannot find that. This was encountered
while trying to build some projects.
GetFrameworkName has an alternate implementation which uses
System.Reflection.Metadata.PEReader to get the metadata. So, choose that
implementation for MONO builds.
Also, this required adding a reference to System.Collections.Immutable
in project.json .
=> On Mono, use PEReader in AssesmblyInformation.GetFrameworkName for

src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeTasks/UnitTests/ResolveAssemblyReference_Tests.cs
These changes were in the code earlier, but seem to have been lost
in the nunit->xunit migration. But they are still relevant, so, adding them
again.
=> Disable windowsonly tests when running on !Windows platforms

src/XMakeCommandLine/UnitTests/XMake_Tests.cs
from an arbitrary path. This will ensure that the test is actually
running against the built MSBuild, instead of the installed MSBuild
assemblies (via GAC).
This fixes the two tests on OSX.
=> XMakeAppTests: Copy MSBuild.exe dependencies also, when trying to run

src/XMakeBuildEngine/UnitTests/Evaluation/Preprocessor_Tests.cs
These tests include the current directory inside an xml comment. If the
path happens to contain `--`, which is not allowed inside xml comments,
then these tests break. This showed up on CI servers where the path did
include these characters!
Issue: https://github.com/Microsoft/msbuild/issues/491
=> Fix issue #491 - test breakage on CI

src/XMakeTasks/CultureInfoCache.cs
Since Core clr does not provide a list of known cultures, check against a hardcoded one.
This is blocking net core selfhosting: on win core the AssignCulture task gives Strings.Shared.resx no culture (because CultureInfo's constructor throws CultureNotFoundException), but on OSX core it gives it the "shared" culture (because the constructor does not throw). This leads to GenerateCompileInputs not adding the shared resource which in turns leads to runtime crashes.
=> Validate culture name on core clr

src/.nuget/packageLoad.targets
On OS X, it gives the error:
```bash
find: ftsopen: No such file or directory
```
and on Ubuntu:
```bash
find: cannot search `': No such file or directory (TaskId:2)
```
(both errors can be verified on CI run before this PR)
This change fixes that error.
=> Fix the find error

dir.props
This also fixes the build for mono/osx.
The build would break because mcs was getting duplicate references like:
1. /reference:/Users/ankit/dev/misc/lib/mono/4.5-api/Facades/System.IO.dll
2. /reference:/Users/ankit/.nuget/packages/System.IO/4.0.10/ref/dotnet/System.IO.dll
Ref(1) was resolved because of `ImplictlyExpandDesignTimeFacades`, and
Ref(2) came from the task `PrereleaseResolveNugetPackages`. This task
reads from the project.lock.json (generated by `dnu restore`), and for
4.5.1 case these assemblies were marked to have the assemblies from the
package be used. This is not the case for 4.6, where these assemblies
instead have entries like `ref/net45/_._`, effectively suggesting that
the assembly should be resolved from the GAC instead.
There are newer version of these package (like …
=> dir.props: Update mono build to target 4.6 instead of 4.5.1

src/Shared/NativeMethodsShared.cs
Due to historical reasons[1], Environment.OSVersion.Platform returns
a value of `Unix` even for OSX. So, instead check for existence of
/usr/lib/libc.dylib
=> NativeMethodsShared.IsOSX: Fix this for mono

src/Shared/FileUtilities.cs, src/Shared/NativeMethodsShared.cs
This method tries to adjust paths that seem to be framework paths and
seem to have a major version higher than 4, and maps them to a different
path like `../xbuild/A.B/bin/..` .
/framework/base/path/vA.B/foo to /framework/base/path/xbuild/vA.B/bin/foo
It's not clear what this was trying to fix, but it is unnecessary and
incorrect. This gets used in a common code path for processing
properties, so it ends up getting applied to all properties and can be
applied more than once, which results in mangled paths, like:
<Foo>/Users/ankit/dev/misc/lib/mono/v8.0/asd</Foo>
.. becomes ..
/Users/ankit/dev/misc/lib/mono/xbuild/8.0/bin/bin/asd
Issue: #503
=> NativeMethodsShared.FixFrameworkPath: Remove

dir.props, src/Shared/TaskHostConfiguration.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/XMakeBuildEngine/BackEnd/Node/NodeConfiguration.cs
- Disable FEATURE_PIPE_SECURITY for mono builds
- #if out a PipeSecurity use
- s,FEATURE_APPDOMAIN,FEATURE_BINARY_SERIALIZATION,
for using INodePacketTranslator.TranslateDotNet
Issue #531
=> Fix mono/OSX build

src/Shared/NativeMethodsShared.cs
OSX is also a Unix, so check for the less generic kind first. So, change
return IsUnix ? "Unix" : (IsOSX ? "OSX" : "Windows_NT")
to
return IsOSX ? "OSX" : (IsUnix ? "Unix" : "Windows_NT")
=> NativeMethodsShared.OSName: Fix the case of OSX

src/dirs.proj, targets/UpdateBuildValues.targets
- This is in BuildTools > 206, which causes many build issues. We will
need to revert this change when we're able to take the new package.
- I need this change because the GitPushRemote variable was added.
=> Adding custom UpdateBuildValues target

src/XMakeTasks/Al.cs, src/XMakeTasks/LC.cs
- the name and case matches what mono uses and should be fine for
windows
=> Fix ToolName for AL and LC - al.exe and lc.exe respectively

src/XMakeTasks/Al.cs, src/XMakeTasks/AspNetCompiler.cs, src/XMakeTasks/LC.cs, src/XMakeTasks/ResGen.cs, src/XMakeTasks/SGen.cs, src/XMakeTasks/WinMDExp.cs
`ToolExe` can be overriden from project files. If not set, then it
falls back to `ToolName`. So, use `ToolExe` in `GenerateFullPathToTool`
instead of `ToolName`.
=> Tasks: Fix overriding `ToolExe` from project files.

dir.props, src/Shared/NodeEndpointOutOfProcBase.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
- commit 583a73e21ac36093e285d473eefec701d9f60d5f was incorrect,
see https://github.com/Microsoft/msbuild/pull/560#discussion_r59051335
Essentially, FEATURE_PIPE_SECURITY means that `PipeSecurity` is
available in the framework. Revert the earlier fix.
- this patch also enables FEATURE_PIPE_SECURITY for mono builds
- Fixes windows build broken by the regression
=> Fix regression in use of PipeSecurity

src/Shared/NativeMethodsShared.cs
Based on the discussion in issue #539, $(OS) property will return
`Windows_NT` whenever running on windows and `Unix` for any other OS.
NativeMethodsShared.OSName is used to set that property, hence this is
being changed.
=> $(OS) should return only two values - `Windows_NT` and `Unix` .

src/Shared/NativeMethodsShared.cs, src/Shared/ToolsetElement.cs, src/XMakeBuildEngine/Definition/ProjectCollection.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs, src/XMakeBuildEngine/Definition/ToolsetLocalReader.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Definition/ToolsetRegistryReader.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Resources/Strings.resx, src/XMakeBuildEngine/UnitTests/Definition/ToolsetConfigurationReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs, src/XMakeBuildEngine/UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/XMakeCommandLine/app.config
Port of #478 (thanks @radical !) to master.
Tried to do minimal changes (merge conflicts + `#if` code that doesn't apply to master).
The goal here is to experiment shipping MSBuild out of the GAC / Registry / Program Files under Visual Studio. This would mean an `Import` to targets under `Program Files` would try under the MSBuild folder first then fallback.
Related to #558
=> Port extensions path fallback

cibuild.sh
This fixes build with mono >= 4.4.x
=> cibuild.sh: Use new version of mono_msbuild_bootstrap* for mono builds.

src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs
- Remove final fall-back that will point to MSBuild in the Framework
directory.
- Remove checking loaded assembly locations as framework assemblies (e.g.
mscorlib) are located next to MSBuild v4.
In both of these cases, finding/running MSBuild.exe from the framework
directory (MSBuild v4) will cause issues.
=> Simplify FindMSBuildExe using FileUtilities logic

src/Shared/FileUtilities.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs
- When we're in devenv process, read the config file from msbuild rather
than devenv.exe.config.
- Fixed a bug with the running tests check. Previously this value was
always true.
=> Read toolsets from msbuild.exe.config file when in VS

src/Shared/UnitTests/App.config, src/XMakeCommandLine/app.config
Think it didn't have it in there when we weren't using the OSS signing and had no public key. Adding it back as it was causing some issues in VS not playing nice with binding redirects.
Also removed the comment that it should use Microsoft.Build.Engine since we're no longer compatible with Microsoft.Build.Engine anyway.
=> Add PublicKeyToken to msbuildToolsets in app.config

src/Framework/Microsoft.Build.Framework.pkgdef, src/Utilities/Microsoft.Build.Utilities.Core.pkgdef, src/XMakeBuildEngine/Microsoft.Build.pkgdef, src/XMakeTasks/Microsoft.Build.Tasks.Core.pkgdef
This change will tell Visual Studio where to find MSBuild as well as
providing a binding redirect in devenv.exe.config.
=> Update pkgdef to add binding redirection

src/Shared/INodePacketTranslator.cs, src/Shared/NodePacketTranslator.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Definition/ToolsetRegistryReader.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsetConfigurationReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/Toolset_Tests.cs
Quick fix for a bug I found in the fallback search paths. We can revisit the implementation, but I need to get this in to continue testing.
Basically converted the type to Dictionary<string, List<string>> since translation for those types already existed (added a simplified Dictionary translate method). I also added to the Toolset translation test functionality to include the fallback paths.
=> Toolset Translation Bug Fix

src/Shared/NativeMethodsShared.cs, src/Shared/ToolsetElement.cs, src/XMakeBuildEngine/Definition/ProjectImportPathMatch.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Definition/ToolsetRegistryReader.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTests/Definition/ToolsetConfigurationReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsetReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/Toolset_Tests.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs, src/XMakeCommandLine/app.config
Changed the implementation of the fallback search paths to be more
generic. It will now replace and fallback any property defined in the
config file.
- Lots of renames to remove reference to MSBuildExtensionPath
- Some small refactoring that bothered me while reviewing a lot of the
code :)
I did this because ASP.NET has the following in their xproj files:
```XML
<VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">15.0</VisualStudioVersion>
<VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
<Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" Condition="'$(VSToolsPath)' != ''" />
```
I tried going down other routes that would fallback because `VSToolsPath` …
=> Make the extensions path search/fallback generic.

BuildAndCopy.cmd, RebuildWithLocalMSBuild.cmd, dir.props, src/Framework/Microsoft.Build.Framework.pkgdef, src/Shared/Constants.cs, src/Shared/UnitTests/App.config, src/Utilities/Microsoft.Build.Utilities.Core.pkgdef, src/XMakeBuildEngine/Microsoft.Build.pkgdef, src/XMakeBuildEngine/UnitTests/Definition/ToolsetReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsetRegistryReader_Tests.cs, src/XMakeBuildEngine/UnitTests/TargetsFile_Test.cs, src/XMakeCommandLine/app.config, src/XMakeTasks/Microsoft.Build.Tasks.Core.pkgdef
We want the assembly version to (for now at least) not be 15.0 which would
conflict with Visual Studio "15" Preview which is loaded in the GAC.
However, we do want to be compatible with the ToolsVersion. This change
updates the ToolsVersion from 15.1 to 15.0 and leaves the assembly version
at 15.1.0.0.
=> Update ToolsVersion to 15.0

CreateSetupPackageLayout.proj
It doesn't need the version. Only used internally for setup.
=> Update fopx setup package name

src/XMakeTasks/Exec.cs
started, so it isn't required and would be incorrect.
=> Exec: Don't add `cd $working_dir` as that is set when the process is

CreateSetupPackageLayout.proj
The created fopx had to start with the OutDir in order to sign. I added
another folder (layout) and that was no longer true.
=> Fix signing issue with setup package

src/Shared/FileUtilities.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs
The GetExecutionInfo method is not very clear on when it should override
the execution info (i.e. what process we're in). With this change,
devenv.exe is no longer considered as a test harness (not sure why it was
in the first place) and we now always override the execution info unless
we're in msbuild.exe. I believe this is the intent of the method in the
first place, but there have been so many issues in it I'm not entirely
sure.
This resolves an issue where in certain cases running in Visual Studio
configuration is read from devenv.exe.config for toolsets.
=> Override FileUtilities process info when in Visual Studio

src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/XMakeBuildEngine/Construction/ProjectOnErrorElement.cs, src/XMakeBuildEngine/Construction/ProjectOutputElement.cs, src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/Definition/ProjectItemDefinition.cs, src/XMakeBuildEngine/Definition/ProjectMetadata.cs, src/XMakeBuildEngine/Definition/SubToolset.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/Evaluation/ProjectStringCache.cs, src/XMakeBuildEngine/Instance/HostServices.cs, src/XMakeBuildEngine/Instance/ProjectItemDefinitionInstance.cs, src/XMakeBuildEngine/Instance/ProjectItemGroupTaskInstance.cs, src/XMakeBuildEngine/Instance/ProjectItemGroupTaskItemInstance.cs, src/XMakeBuildEngine/Instance/ProjectItemGroupTaskMetadataInstance.cs, src/XMakeBuildEngine/Instance/ProjectMetadataInstance.cs, src/XMakeBuildEngine/Instance/ProjectOnErrorInstance.cs, src/XMakeBuildEngine/Instance/ProjectPropertyGroupTaskInstance.cs, src/XMakeBuildEngine/Instance/ProjectPropertyGroupTaskPropertyInstance.cs, src/XMakeBuildEngine/Instance/ProjectPropertyInstance.cs, src/XMakeBuildEngine/Instance/ProjectTargetInstance.cs, src/XMakeBuildEngine/Instance/ProjectTaskInstance.cs
Fix #610.
I used Resharper to find invalid names.
Please note that there are still 3 unresolved symbols:
XMakeBuildEngine\Construction\ProjectOnErrorElement.cs:23 Cannot resolve symbol 'ExecuteTargets'
XMakeBuildEngine\Construction\ProjectOutputElement.cs:22 Cannot resolve symbol 'Name'
XMakeBuildEngine\Construction\ProjectOutputElement.cs:22 Cannot resolve symbol 'ItemName'
I do not know how to fix them (there is no corresponding property)
=> Fix #610 - Update DebuggerDisplay for renamed fields

netci.groovy
The build logs are often *most* interesting when the build fails, so we should be capture them regardless of job failure.
Noticed this when trying to investigate the Ubuntu failure on #629.
=> Archive MSBuild logs on job failure

dir.props
Apparently BuildTools separates tasks in two categories, build tasks and packaging tasks.
Build tasks were setup to use net46 published tasks, but packaging tasks were not. Fixed the mismatch by making both resolve to net46.
This caused the VSTS microbuild build to fail in the NugetPack task.
=> Use net45 version of BuildTools packaging tasks

CreateBootstrappedMSBuild.cmd, RebuildWithLocalMSBuild.cmd, dir.props, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj
This change will build MSBuild.exe and MSBuildTaskHost.exe as x86/x64 and
all other assemblies AnyCPU. This matches the shipping configuration.
Also replaced AnyCPU default with x86 to match the the default in our
shipping code.
Closes #618
When building **x86**:
```
MSBuild.exe
Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0xb
ILONLY    : 1
32BITREQ  : 1
32BITPREF : 0
Signed    : 1
```
```
Microsoft.Build.dll
Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : 0x9
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 1
```
When building **x64**:
```
Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32+
CorFlags  : 0x9
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 1
```
```
Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32
CorFlags  : …
```
=> Build only MSBuild.exe platform specific

.gitignore
Noticed that the `.vscode` directory was showing up in `git status` after making my changes; this should help it ignore such directories, for users of VS Code.
=> gitignore: Ignore VS Code-generated files

dir.props, src/.nuget/project.json, src/nuget/MSBuild.nuspec, src/nuget/Microsoft.Build.Framework.nuspec, src/nuget/Microsoft.Build.Targets.nuspec, src/nuget/Microsoft.Build.Tasks.Core.nuspec, src/nuget/Microsoft.Build.Utilities.Core.nuspec, src/nuget/Microsoft.Build.nuspec
The `dotnet` moniker is the deprecated moniker for `dnxcore50`, and `dnxcore50` is the deprecated moniker for `netcoreapp1.0`
Since we want msbuild packages to be referenceable from both `net46` and `netcoreapp1.0`, they should really target the intersection APIs, which is `netstandard1.3`
=> Update nuspecs from targetting dotnet to targetting netstandard1.3

src/Shared/UnitTests/RunnerUtilities.cs, src/XMakeCommandLine/UnitTests/XMake_Tests.cs, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/XMakeTasks/UnitTests/PortableTasks_Tests.cs
An attempt to write some automated tests to check that tasks should be runnable by all msbuild flavors.
The tests invoke our sample portable task with the desktop msbuild, and with the non-desktop msbuilds.
Unfortunately this is not ideal. The ideal case would also check that msbuild's nuget packaging allows consumers of msbuild packages to target both `net46` and `netcoreapp1.0` / `netstandard1.3` and assert that the msbuild packages get successfully restored.
Unfortunately this requires a big change to xplat's build logic so it executes in 3 steps:
1) build and package msbuild
2) restore the sample projects using the local, freshly built packages
3) run msbuild tests (some of them depend on the sample projects)
=> Add tests for running portable tasks

RebuildWithLocalMSBuild.cmd, cibuild.sh, dir.props, init-tools.sh, src/XMakeBuildEngine/UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs, targets/BootStrapAppLocalMSBuild.proj
A few script fixes:
* Use the just-restored `corerun` for the second (post-bootstrap) build, for better test coverage and since that's required after the merge from master.
* Make `init-tools.sh` actually fail in more failure cases.
Fixes #628 and #590.
Thanks, @akoeplinger!
=> Xplat script improvements

netci.groovy
Xunit does not report *some* test failures on Ubuntu. Our build scripts use the same arguments for xunit on osx and ubuntu, so the problem seems to be somewhere else (xunit, coreclr, corefx, etc). I am reverting enabling Linux tests until I find out what is happening.
=> Revert "Merge pull request #668 from cdmihai/enableLinuxCITests"

src/Shared/InprocTrackingNativeMethods.cs, src/Utilities/TrackedDependencies/FileTracker.cs, src/Utilities/UnitTests/TrackedDependencies/FileTrackerTests.cs
:memo: This is destined for the Update 3 branch. I'll merge to master in another PR after it's in there.
This ports internal changes made to support an update to `Tracker.exe` and `FileTracker.dll` that allows them to support a process tree that has mixed 64-bit and 32-bit processes.
These changes will not work without a build of Update 3 installed, because Tracker and FileTracker are built inside the Microsoft firewall and not publicly available. Filed #649 to track making them available. The tests can also be re-enabled by making Update 3 a requirement to build on Windows (once it exists outside the firewall).
=> Support process trees with both 32- and 64-bit processes in FileTracker

src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
We are currently trying to move all the tools that are used to build corefx(which includes MSBuild) to run on the DotNet CLI and the shared framework that comes with it. The problem with MSBuild, is that when `\m` is passed in, it always tries to look for corerun.exe (or corerun in non-Windows) to lunch new processes like `corerun.exe MSBuild.exe ...`. With my change, msbuild will now detect the host process that was used originally, and use the same one for its children. For example:
```
>dotnet.exe msbuild.exe /m build.proj
//That will cause that the children processes will be like:
>dotnet.exe msbuild.exe ...
```
PTAL: @cdmihai @rainersigwald @dsplaisted 
FYI: @weshaggard @stephentoub
=> Detecting Host Process to launch new instances of msbuild when /m is passed in

src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
I randomly hit this test when breaking into a test assembly, and noticed it was SUPER verbose when it could be short and sweet.
=> Assert.Throws in ToolLocationHelper_Tests

src/XMakeCommandLine/app.config
Also updated VCTargetsPaths to match current installed toolset.
@yuehuang010 can you also review the `VCTargetsPath` for legacy? The current `VCTargetsPath` points to the low-impact location.
Closes #679
=> Add MSBuildFrameworkToolsPath64 to app.config

src/XMakeTasks/AssemblyDependency/ResolveAssemblyReference.cs, src/XMakeTasks/Strings.resx
Update error message with expected, actual and target `Assembly` name
Considered "....expected....",
but its name "....actual....".
Didn't match the expected version  "..assembly name."
Issue #502
=> RAR name mismatch message with Assembly name

dir.props
This was missed in the update to xunit 2.1.0 RTM in a86122bd0. Tests
passed on machines that had the old package installed but failed on clean
machines.
=> Update xunit version in dir.props

src/Shared/UnitTests/MockLogger.cs, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeBuildEngine/UnitTests/Instance/ProjectInstance_Internal_Tests.cs
Converting this to be more "xunity" in 2c9f334 was wrong, because many of
the cases threw an exception *derived* from ArgumentException, not exactly
an ArgumentException. `ThrowsAny` describes that case.
=> Allow derived exceptions in PassEmptyAndNullTPM

src/Utilities/ToolTask.cs
.. environment variable is set. This affects temporary files like
script/batch files, response files generated by Exec task or similar
temporary files generated by Tasks inheriting from ToolTask .
=> ToolTask: Preserve the temporary files if MSBUILDPRESERVETOOLTEMPFILES

src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/UnitTests/AssignLinkMetadata_Tests.cs, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
=> Enable AssignLinkMetadata in .NET Core build

src/XMakeTasks/Delete.cs
Xamarin MSBuild-based remote infrastructure relies on inheriting and 
extending the base tasks to execute remotely (as well as locally). 
For consistency with the other build tasks, this should not be sealed 
either.
=> Make Delete non-sealed, just like Copy, Move, MakeDir, etc.

src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs
Work around #696 by disabling this test entirely.
=> Disable CancelledBuildWithDelay20 test

src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs, src/XMakeCommandLine/app.config
Add a hook into the intrinsic functions to get the full path to the
MSBuild tools path and VS install root for the extensions path variables.
This is blocking some tests internally because the "." is getting read and evaluated to a different path. I also think it given that this logic is now somewhat more complicated that we should do something like this to calculate the paths rather than limit to a single line property evaluation as it was (I never liked the `..\..\..\` or `.` appearing in the variable).
Note: I'm looking for feedback and ideas on where to put this code, this is not complete. I may commit this to unblock the tests internally, but either way this needs to be updated.
=> Calculate a better MSBuild tools/extensions path.

setup/files.swr
Missed this in my rename of the setup package. This doesn't get caught until it tries to insert the package in the VS setup build.
=> Rename setup package ID in files.swr

src/XMakeTasks/Microsoft.Build.Tasks.csproj
- This should have been embedded in Microsoft.Build.Tasks to match the
shipping product.
=> Adding ManifestUtil string resources to MS.Build.Tasks

src/XMakeCommandLine/app.config
Related to #704
When referring to a function in a property definition MSBuild will escape
the value. This was causing the MSBuildToolsPath to contain escape
characters since the value is used directly. Referring to an already
defined property (VsInstallRoot) will workaround this issue.
=> Workaround for issue causing ToolsPath character escaping

cibuild.sh, src/Utilities/ToolTask.cs, src/XMakeTasks/Exec.cs
It's generally best practice to prefix a Bash script with `#!/usr/bin/env bash` rather than `#!/bin/bash`. Although 99% of the time the `bash` executable will be in `/bin` (or at least a symlink of it will be), in some cases it may not be-- see [this StackOverflow answer](http://stackoverflow.com/a/21613044/4077294) for an example.
Using `env` ensures we search through all the directories in $PATH for `bash`, rather than restricting it to just the one in `/bin`. Also, there shouldn't be a performance loss since `env` replaces its own process with the arguments it's given, rather than starting a new one (similar to the difference between `command` and [`exec command`](http://wiki.bash-hackers.org/commands/builtin/exec) in Bash).
=> Replace uses of #!/bin/bash with #!/usr/bin/env bash

src/dir.targets
Extracting this from #693, because it's causing us to fail to build NuGet packages in our (internal) build that produces them. On my machine, this can build after clean when invoked like the build definition does (with machine MSBuild).
Thanks for the fix, @mfilippov!
=> Only include GitVersioning when it exists

src/XMakeCommandLine/app.config
Common C++ targets import this property whose value includes
$(MSBuildExtensionsPath). This workaround will allow for the extension
targets to be found when MSBuild is installed next to Visual Studio.
=> Add _CppCommonExtensionTargets search path workaround.

src/Shared/AssemblyNameExtension.cs, src/Shared/CommunicationsUtilities.cs, src/Shared/NodeEndpointOutOfProcBase.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs
Note: *compilation*. Tests fail all over the place.
This also doesn't get MSBuildTaskHost building. That'll require more work. But everything else compiles.
=> Fix Debug compilation problems in xplat

src/XMakeTasks/BootstrapperUtil/Util.cs
Since this is just for Willow, I removed the code which used versions. 
Also I removed the path BOOTSTRAPPER_WOW64_REGISTRY_PATH_BASE  as the content
under WOW6432 will be automatically be presented to 32 bit apps running on 64 bit OS.
=> Updating path to versionless registry for GenericBootstrapper

setup/files.swr
This will ensure that the AnyCPU binaries in the root and AMD64 folder are
bitwise identical. This was a suspected culprit in an issue where x64 OOP
MSBuild ended up loading multiple duplicate types.
Related to #764
=> Update setup to drop x86 AnyCPU binaries for AMD64

src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs
Fix a null ref Exception when the evaluator tries to implement import
search paths for a property that does not (yet) exist. In this case the
search path(s) will still be checked but the current null value will be
ignored.
=> Fix project import search paths when property undefined.

src/Shared/BuildEnvironmentHelper.cs, src/Shared/FileUtilities.cs, src/Shared/FrameworkLocationHelper.cs, src/Shared/InternalErrorException.cs, src/Shared/Strings.shared.resx, src/Shared/TaskLoader.cs, src/Shared/ToolsetElement.cs, src/Shared/UnitTests/FileUtilities_Tests.cs, src/Utilities/Microsoft.Build.Utilities.csproj, src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderInProc.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs, src/XMakeBuildEngine/Instance/TaskRegistry.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTests/BackEnd/TaskRegistry_Tests.cs, src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsetReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj, src/XMakeTasks/Microsoft.Build.Tasks.csproj
Move all build path environment discovery to new class
- With Dev15, finding MSBuild is a bit trickier. This change tries to
address that by moving the logic to a single place and streamlining the
usage.
- Audited code that needed to find the MSBuild path to use this.
Previously there were a variety of methods used, ideally this should be
the only one (other than perhaps finding tools from another toolset).
Closes #704
=> Calculate a better MSBuild tools/extensions path

src/Utilities/TrackedDependencies/FileTracker.cs, src/Utilities/UnitTests/TrackedDependencies/FileTrackerTests.cs
When TEMP/TMP environment variable points to a drive root folder (D:\) without any further folder nesting, TEMP path results in null. This fix allows TEMP path to point to a drive root and also fixes #606.
=> Fix temp path issue

src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets, src/XMakeTasks/Microsoft.VisualBasic.CurrentVersion.targets
Conditionally import design time targets that will be installed with the next Preview of Visual Studio 15. These targets override CPS project properties schema to enable functionality introduced by the [Roslyn Project System](https://github.com/dotnet/roslyn-project-system).
/cc @AndyGerlicher @srivatsn @davkean 
For reference:
- Roslyn Project System [Design Time targets](https://github.com/dotnet/roslyn-project-system/tree/SigningTesting/src/Targets)
- Work Item: https://github.com/dotnet/roslyn-project-system/issues/128
=> Import design time targets for Roslyn Project System

src/XMakeTasks/ManifestUtil/SecurityUtil.cs
With the previous code, if `signtool.exe` wasn't found in the Windows SDK *and* the .NET 4.0 SDK wasn't installed, `SignFile` would throw instead of failing gracefully.
Closes #787.
=> Gracefully handle missing .NET SDK in SignFile

src/XMakeTasks/SignFile.cs
This reduces code complexity and might make callstacks easier to decode.
=> Convert SignFile to an exception filter

src/XMakeTasks/ManifestUtil/mansign2.cs
Resolves #791
This line was #ifed out in the VS repo for quite a long time, but the
initial GitHub code drop was missing the condition. Restoring it to
prevent a regression in signing scenarios.
=> Avoid XmlLicenseTransform in AuthenticodeSignLicenseDom

src/.nuget/NuGet.Config
Pretty sure the stale feed URLs were causing CI failures like in #797.
Not 100% sure why we'd need the corefx feed in master, but I suspect it's for transitive dependencies from buildtools.
=> Update MyGet feed URLs

src/Shared/BuildEnvironmentHelper.cs, src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs
- When running in Blend.exe, treat as if we're in Visual Studio.
Previously we could not find Visual Studio and ended up setting the
value to null.
=> Add BuildEnvironmentHelper support for Blend.exe

src/XMakeCommandLine/app.config
This was added as a temporary workaround. Removing fallback from that
import property.
=> Remove workaround fallback for _CppCommonExtensionTargets

src/MSBuild.sln, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj
MSBuildTaskHost.csproj has been building since 2e2298a, but it wasn't
added to the solution, so it didn't show up in Visual Studio.
I also removed the AnyCPU configuration for MSBuild.exe and
MSBuildTaskHost.exe, since they should both always be built for an
explicit architecture.
@AndyGerlicher objection?
=> Add MSBuildTaskHost to MSBuild.sln

src/Shared/Modifiers.cs, src/Utilities/UnitTests/TaskItem_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
Fixes #813
On Windows, `%(Directory)` strips the drive letter-colon-backslash
prefix from full paths. For unixy paths, the same meaning isn't exactly
clear, but there's a known root (`/`) that could be stripped
equivalently.
After this change, the correct metadata reference to get full directory
is `%(RootDir)%(Directory)` on Windows (as it always has been) and on
other OSes (as Mono's xbuild has been doing, and as seems most
consistent).
=> Directory item metadata should be relative

netci.groovy
When tests fail in random, puzzling ways, it is probably helpful to have the xml outputs and the test 
stdout
[This comment](https://github.com/dotnet/dotnet-ci/blob/master/jobs/generation/Utilities.groovy#L852) suggests we can separate globs by commas, so that's what I did. Hopefully it works. If not, I'll manually create an ArchivalSettings object
(PR created in response to this CI failure: http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/_Windows_NT_prtest/644/)
=> Archive test results

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
The compiler is adding support for a new flag on `/debug:`.  This updates the targets for this feature.
Context of the change: https://github.com/dotnet/roslyn/pull/12711
=> Support for /debug:embedded

src/XMakeTasks/ManifestUtil/SecurityUtil.cs
- Update search path to include the new location for the SignTool installed by a singleton MSI. This is necessary as otherwise SignTool comes from Windows SDK which is a heavyweight component which is not justified to be included as a dependency just for the SignTool.
- Update condition for continuing the search to include the actual existence of the file in case the path is not null as there are scenarios in Dev15 in which the "toolPath" to be found but the signtool is not present.
=> Fix SignFile task for Dev15 ClickOnce signed publishing

src/XMakeCommandLine/app.config
- Add trailing '\' on VCTargetsPath
- Add AdroidTargetsPath and iOSTargetsPath per C++ team. This matches
values that were previously set by optional installed components.
=> Update app.config for C++ target default properties

src/Shared/FrameworkLocationHelper.cs
In the initial xplat work for MSBuild, these were changed from being
compile-time constants to static fields, because they now have conditional
behavior dependent on whether the code is running on Windows.
That introduced a subtle bug: `s_dotNetFrameworkRegistryKeyV35` needs to
know `dotNetFrameworkVersionFolderPrefixV35`, but was textually before it.
Since static field initialization is
[executed in the textual order in which they appear in the class
declaration](https://msdn.microsoft.com/en-us/library/aa645758.aspx), the
registry key got the bogus value (with a null string appended to it
instead of the .NET 3.5 version string).
=> Initialize .NET 3.5 key name before use

src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/app.amd64.config
Initial fix for #834. Setting `codeBase` to ensure that all MSBuild
assemblies get loaded from the same location (in the MSBuild bin folder)
even if they're loaded from the amd64 MSBuild.exe.
This isn't a great solution--the app.config files should be generated from a common
source, because they should be identical except for the codeBase. Also, we
probably shouldn't even ship copies of the assemblies into the amd64
folder if they'll never be used. But this is an urgent bug so I'm
providing a quick workaround to be followed up with a long-term fix.
=> Set codeBase for MSBuild assemblies in x64 MSBuild

src/XMakeBuildEngine/UnitTests/Evaluation/ExpressionShredder_Tests.cs
ExpressionShredder_Tests.ExtractItemVectorExpressionsSingleExpression7
and
ExpressionShredder_Tests.ExtractItemVectorExpressionsSingleExpression8
were identical. I modified
ExpressionShredder_Tests.ExtractItemVectorExpressionsSingleExpression8
and added seperator to expression. This also closes #729.
=> Modify identical unit test. This also closes #729.

targets/runtimeDependencies/project.json
.. nuget . This can be seen if you clean the global/user and local nuget
cache and then build:
Microsoft.Build.Framework -> /Users/ankit/dev/msbuild/bin/x86/OSX/Debug-MONO/Output/Microsoft.Build.Framework.dll
MSBUILD : error : The package Microsoft.DotNet.BuildTools.TestSuite with version 1.0.0-prerelease-00508-01 could not be found in /Users/ankit/.nuget/packages. Run a NuGet package restore to download the package. [/Users/ankit/dev/msbuild/targets/DeployDependencies.proj]
=> Fix mono/OSX build - missing `Microsoft.DotNet.BuildTools.TestSuite`

cibuild.cmd
Checking this into xplat so that cf10c8a9 has a cibuild.cmd script to
target in the xplat branch. As-is, it always builds for .NET Core, even if
asked to build for desktop. A follow-up, full-featured cibuild.cmd will be
capable of building both desktop and Core.
=> Stub cibuild.cmd to enable multi-runtime CI builds

cibuild.cmd, netci.groovy
Needed for #342.
This adds another dimension to the CI build definitions, so we can start
building both the .NET Core and Desktop framework versions of MSBuild out
of the xplat branch.
Since `netci.groovy` only creates jobs, it can't know what branch is being
targeted for a PR-validation job. So the validation script must exist
everywhere. Since master doesn't build for .NET Core, I'm adding a stub
cibuild.cmd that's just a shim for the existing CI build script. Builds in
master will trigger two full-framework builds, with one labeled "CoreCLR".
This should be a temporary situation since the branches should be unified
soon.
=> Enable multi-runtime builds in CI infrastructure

src/XMakeCommandLine/XMake.cs
This was disabled when removing calls to `Debugger.Launch`, but in mode 2
`MSBUILDDEBUGONSTART` doesn't actually need that API and is .NET Core
friendly.
=> Allow MSBUILDDEBUGONSTART=2 for .NET Core

src/Shared/FileUtilities.cs, src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Evaluation/IEvaluatorData.cs, src/XMakeBuildEngine/Instance/ProjectInstance.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
Addresses #732 
This implementation:
- is performed after evaluation => lacks flow accuracy of inter-item references
- appends `Provenance.Inconclusive` to the result when the match is inside an indirect property / item reference
- does not expand any globs
Since the expander / evaluator do not keep a trace of what happened, this implementation expands the string twice and diffs the results to understand what happened and to give accurate occurrence results.
Also, this implementation is a temporary one. It will get refactored when it has to consider Update and Remove. And there's a chance it will get removed and re-implemented on top of lazy evaluation to gain flow accuracy. And then re-implemented again if / when we have scanners, parsers, and interpreters over the itemspec …
=> Get item provenance

src/UpdateLocalizedResources.targets
SignFiles target needs it.
The SignFiles output finally looks alright:
```
Submitting C:\projects\msbuild_2\bin\x86\Windows_NT\Debug\Microsoft.Build.Utilities.Core.dll for Test signing (TaskId:222)
Submitting C:\projects\msbuild_2\bin\x86\Windows_NT\Debug\cs\Microsoft.Build.Utilities.Core.resources.dll for Test signing (TaskId:222)
Submitting C:\projects\msbuild_2\bin\x86\Windows_NT\Debug\de\Microsoft.Build.Utilities.Core.resources.dll for Test signing (TaskId:222)
Submitting C:\projects\msbuild_2\bin\x86\Windows_NT\Debug\es\Microsoft.Build.Utilities.Core.resources.dll for Test signing (TaskId:222)
Submitting C:\projects\msbuild_2\bin\x86\Windows_NT\Debug\fr\Microsoft.Build.Utilities.Core.resources.dll for Test signing (TaskId:222)
Submitting …
```
=> Add satellite assemblies to FilesToSign

src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config, src/XMakeTasks/Microsoft.Xaml.targets
This PR is to fix an issue with VS "15" being unable to build workflow projects. Workflow projects use a custom MSBuild task called XamlBuildTask. XamlBuildTask creates a new AppDomain that attempts and fails to load the GAC version of MSBuild assemblies rather than the applocal ones in VS "15".
Microsoft.Xaml.targets in this version of MSBuild is a shim to load the .NET Framework version. The XamlBuildTaskPath MSBuild property is used as the ApplicationBase for the new AppDomains by XamlBuildTask. This PR sets this property to the applocal folder. In concert, we are placing XamlBuildTask.dll in the applocal folder of VS "15".
The other change is to apply an assembly binding redirect from the framework version (4.0.0.0) of XamlBuildTask to the VS "15" version (15.1.0.0). This is to ensure …
=> Updates to support XamlBuildTask

src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config, src/XMakeTasks/Microsoft.Xaml.targets
#856 was needed for Visual Studio "15" Preview 4, but we've taken changes into `master` that we don't want to ship quite yet. I cherry-picked the changes to a newly created stabilization branch. This just merges those back into master so future history spelunking is easier.
=> Merge Xaml task changes back to master

cibuild.cmd, cibuild.sh, targets/BootStrapFullFrameworkMSBuild.proj
📝 My plan is to get this in, set up a failing CI build, and then make it pass. I have that mostly working on my machine, so now it's time to see if Jenkins agrees with me.
This is a port of cibuild.sh, because RebuildWithLocalMSBuild didn't
support arguments and cibuild.sh is a better name. The code was initially
copied from RebuildWithLocalMSBuild.cmd.
Needed for #342.
=> Introduce cibuild.cmd

src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Multiprocess builds were hanging when called through `dotnet build3`,
because the child process spawned from `LaunchNode` failed immediately on
start with
```
A fatal error was encountered. The library 'hostpolicy.dll' required to
execute the application was not found
```
That was because MSBuild preserved the path to `dotnet`, but not the
additional arguments required for it to assemble a runtime environment.
This commit uses the property bag that the host provides to find the right
deps file. At the moment, there is no programmatic way to access the
runtimeconfig, so I'm relying on a heuristic--that it'll match the deps
file.
The property-bag access code is based on
https://github.com/dotnet/cli/blob/b7075b857b48b08908bd340ffd3f41f756318339/src/Microsoft.DotNet.Cli.Utils/Muxer.cs#L36-L40 …
=> Pass dotnet host options to worker nodes

setup/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
Add a .nuspec file that captures the set of binaries we need to make available to the Visual Studio build. Our VSTS build process will be updated to create the NuGet package and upload it to the appropriate store.
A few things to note:
1. The package will be created and published by the official build; we don't need to add any further projects, scripts, etc. to the source tree.
2. As the official build runs for both x86 and x64, we're going to end up with two copies of the package. To differentiate them, they will have different IDs: VS.ExternalAPIs.MSBuild.**x86** and VS.ExternalAPIs.MSBuild.**x64**. At the moment, the contents will be identical, so we anticipate that only the x86 version will actually be used.
3. The version number will be specified when running the `nuget pack` …
=> Create a package for use by the Visual Studio build

build.cmd, cibuild.sh
It's not entirely clear why yet, but when MSBuild tries to spawn another
node, it emits
```
The specified deps.json [O:\msbuild\bin\Bootstrap\MSBuild.deps.json] does
not exist
```
And hangs. Disabling to get clean CI builds while debugging.
=> Disable multiprocess build (work around #874)

setup/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
Update the .nuspec file for the CoreXT package. It turns out we don't need the
architecture (x86, x64, etc.) burned into the name, so drop that. However, we
do want the branch name burned into the description. There may be times when
two different branches are producing packages with very similar version numbers,
and we'll want a reasonably easy way to figure out where they came from.
=> Update .nuspec for CoreXT package

targets/runtimeDependencies/project.json
Move System.IO.Compression and System.IO.FileSystem dependencies up in runtimeDependencies project.json
During packaging, Microsoft.DotNet.Build.Tasks.Packaging.dll loads NuGet.Common.dll which attempts to load System.IO.FileSystem version 4.0.1.0.  However, System.IO.FileSystem version 4.0.0.0 ends up in our output directory which causes runtime assembly load errors.
Moving the dependency up in project.json appears to ensure the correct version gets copied to our output directory.
=> Move System.IO.Compression and System.IO.FileSystem dependencies 

src/Utilities/ToolLocationHelper.cs, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
`FrameworkPathOverride` set in `Microsoft.Common.CurrentVersion.targets`,
does not use the `$(TargetFrameworkRootPath)` while calling
`ToolLocationHelper.GetPathToStandardLibraries(...)` .
<FrameworkPathOverride Condition="'$(FrameworkPathOverride)' == ''">$([Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget)))</FrameworkPathOverride>
This means that if the project is targeting a custom framework,
which is installed in a directory different from the default root path,
then it won't be able to find the framework and eventually,
`FrameworkPathOverride` will be set to an incorrect path. This can be
seen with mono/osx which has an alternate directory for
Xamarin mobile …
=> Respect $(TargetFrameworkRootPath) in ToolLocationHelper APIs

build.cmd, cibuild.sh, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
cd53996d introduced some tricks to ensure that, when we're invoked by
`dotnet build3`, a worker node can get spawned correctly. Unfortunately,
the technique that worked in that situation gave bad information in the
MSBuild selfhost build post-bootstrap, after 51f6d76 switched us to use
dotnet.exe instead of corerun.
=> Only override deps and runtimeconfig if they exist

src/Shared/BuildEnvironmentHelper.cs
All of the code that could read configuration data out of
msbuild.exe.config is dependent on System.Configuration, which isn't
available in .NET Core. The reading code was all #if'ed out, but we still
required that the file be physically present, or MSBuild would fail on
initialization.
I made `IsValidMSBuildPath` dependent on the same compile-time check as
src/Shared/ToolsetElement.cs.
=> Do not require msbuild.exe.config on .NET Core

src/UpdateLocalizedResources.targets
Something is causing the satellite assemblies to not be signed.
Trying this out as a potential solution
=> Add StrongName metadata to FilesToSign item

cibuild.cmd, src/dirs.proj, src/nuget/Microsoft.Build.Framework.nuspec, src/nuget/Microsoft.Build.Targets.nuspec, src/nuget/Microsoft.Build.Tasks.Core.nuspec, src/nuget/Microsoft.Build.Utilities.Core.nuspec, src/nuget/Microsoft.Build.nuspec
* Update NUSPEC so that the version is coming from build properties
* Update NUSPEC so that dependency version is coming from build properties
* Don't build packages during the first build
Fixes #528, related to #692
=> Fix NuGet package versions

src/Utilities/Microsoft.Build.Utilities.csproj, src/Utilities/ProcessExtensions.cs, src/Utilities/ToolTask.cs
Current implementation of KillTree was tied to Windows Kernel32.dll P/Invocation.
This ports the Unix implementation of same from dotnet/cli repo:
https://github.com/dotnet/cli/blob/04f40f9/test/Microsoft.DotNet.Tools.Tests.Utilities/ProcessExtensions.cs
(not sure if there is a better way to consume it as a package instead of copy-pasta :spaghetti:?)
Fix #434
Fix #757
=> Port cross-plat ProcessExtensions from CLI

dir.props, setup/files.swr, src/.nuget/packages.config, src/XMakeBuildEngine/project.json
We had added a dependency to System.Collections.Immutable which got overwritten by the VS build, thus breaking MSBuild. This PR bumps up collections.immutable and csc.
=> Bump up System.Collections.Immutable

src/Shared/AssemblyFolders/Serialization/AssemblyFolderCollection.cs
In the VS scenario, unelevated builds failed with
```
C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1825,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly. [c:\branch\qa\vc\ide\tests\endtoend\EndToEnd.csproj]
C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1825,5): error MSB4018: System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\bin\AssemblyFolders.config' is denied.
```
The installed VS path is ACLed so that files in it aren't writable by normal processes, but the default access request from the FileStream constructor is `FileAccess.ReadWrite`. `FileShare.Read` is the …
=> Open AssemblyFolder.config with minimal rights

build.cmd
If msbuild is invoked with the (default) `/nodeReuse:true` argument,
worker nodes hang around for a period of time after the build is complete
to see if more work will be incoming. This is normally a nice
startup-time-reducing perf optimization. But in our own build, it means
that many newly-created MSBuild assemblies are opened and uneditable,
failing builds and causing cleans to fail.
Changing the Windows build script to just always pass `/nodeReuse:false`.
=> Avoid node reuse during desktop-hosted builds

src/Utilities/UnitTests/project.json, src/XMakeBuildEngine/UnitTests/project.json
These were updated in the runtime package list (so our final output was
ok), but not in these consumers.
=> Update stale references to Roslyn targets

src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs
Related to issue #916.
When I run Microsoft.Build.UnitTests.Evaluation.Expander_Tests.Medley (from
Microsoft.Build.Engine.UnitTests.dll) by itself, the test passes. When I run all
tests in the assembly, however, it fails with this message:
> FAILURE: Expected '$([Microsoft.VisualBasic.FileIO.FileSystem]::CurrentDirectory)'
>   to not parse or not be evaluated but it evaluated to
>   'E:\Projects\msbuild\bin\x86\Windows_NT\Debug'
> Expected: True
> Actual:   False
> Stack Trace:
>   src\XMakeBuildEngine\UnitTests\Evaluation\Expander_Tests.cs(3141,0): at
>     Microsoft.Build.UnitTests.Evaluation.Expander_Tests.Medley()
Specifically, the test seems to fail if I also run the
PropertyStaticFunctionAllEnabled method in the same class first. That's the only
other test in the assembly that …
=> Disable a failing unit test

Before.Microsoft.Common.targets, dir.props
Microsoft.Portable.Core.props blindly sets <TargetFrameworkIdentifier /> so our assemblies show that as the framework instead of NETStandard1.3
I had to use a Before.Microsoft.Common.targets because the assembly info file contents are generated before our dir.targets is imported.
=> Fix TargetFrameworkIdentifier for CoreCLR builds

src/XMakeBuildEngine/UnitTests/Parser_Tests.cs
As the format strings don't contain any format items the `Uri` object is never inserted into the string, making the `Uri` instantiation (and therefore the `String.Format` calls) unnecessary.
=> Remove unnecessary string formatting

src/XMakeTasks/BootstrapperUtil/BootstrapperBuilder.cs
On line [826](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/BootstrapperUtil/BootstrapperBuilder.cs#L826) the local boolean variable `validate` is checked to be `true`.
As there is no code between there and these `if` statements that can modify `validate`, these `if` statements will always resolve to `true`, making them unnecessary.
=> Drop unnecessary if statements

src/XMakeBuildEngine/BackEnd/Components/Scheduler/Scheduler.cs, src/XMakeBuildEngine/UnitTests/BackEnd/MSBuild_Tests.cs, src/XMakeTasks/ManifestUtil/XmlUtil.cs, src/XMakeTasks/UnitTests/MSBuild_Tests.cs
Not all given format items are used in the format string. This removes the unused format items.
=> Remove unnecessary format items

src/XMakeTasks/AssemblyRemapping.cs
In `AssemblyRemapping.cs`, there is invalid null object checking, there `name` variable should be checked for null instead of  main `obj`.
=> Null check was with main object instead of casting object. 

build/LegacyPackages/14.0/.gitignore, build/LegacyPackages/14.0/Microsoft.Build.Conversion.Core/Microsoft.Build.Conversion.Core.nuspec, build/LegacyPackages/14.0/Microsoft.Build.Engine/Microsoft.Build.Engine.nuspec, build/LegacyPackages/14.0/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, build/LegacyPackages/14.0/Microsoft.Build.Framework/Microsoft.Build.Framework.nuspec, build/LegacyPackages/14.0/Microsoft.Build.Framework/project.json, build/LegacyPackages/14.0/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, build/LegacyPackages/14.0/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.nuspec, build/LegacyPackages/14.0/Microsoft.Build.Tasks.Core/project.json, build/LegacyPackages/14.0/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, build/LegacyPackages/14.0/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.nuspec, build/LegacyPackages/14.0/Microsoft.Build.Utilities.Core/project.json, build/LegacyPackages/14.0/Microsoft.Build/Microsoft.Build.cs, build/LegacyPackages/14.0/Microsoft.Build/Microsoft.Build.nuspec, build/LegacyPackages/14.0/Microsoft.Build/project.json, build/LegacyPackages/14.0/build.cmd
1. I ended up using `#if !NETSTANDARD` so that I could have just 1 source file per assembly.  This makes it a little tougher to see what is left out but not impossible
2. Please review each nuspec
3. The version I'm using for the packages is 14.VSUpdateNumber.PackageRevision[-tag].  So when this goes public it will be 14.3.0.  If we service it, we'll increment the build number.  If we push a new version of Visual Studio we'll update the minor version.
4. This requires both dotnet.exe and nuget.exe to be on the PATH to run.  Is that an okay detail?
5. This will all break once dotnet.exe changes to not use project.json for builds and moves to MSBuild.exe instead.  I'll have to update this to use a csproj and the appropriate .targets.
Fixes #926
=> Projects for creating NuGet packages for MSBuild 14.0 binaries

src/XMakeBuildEngine/UnitTests/BackEnd/TaskExecutionHost_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/TaskRegistry_Tests.cs, src/XMakeTasks/AssemblyDependency/ResolveAssemblyReference.cs
As the return types for those methods/properties are already of the type indicated, the casts are superfluous.
=> Drop superfluous casts

src/XMakeTasks/CodeTaskFactory.cs, src/XMakeTasks/ResolveKeySource.cs
The first `if` is identical to the one at line 250 and `_log.HasLoggedErrors` can't have changed in the meantime, making the check obsolete.
And `pfxSuccess` is set to `false` in line 165. It is only modified in the `if` at line 190 and therefore will always be `true` in the else, making the `!pfxSuccess` check obsolete.
=> More if-tweaking

src/XMakeBuildEngine/BackEnd/Components/Logging/LoggingService.cs
`_nextProjectId` is assigned to itself. I assume the `+=` was just a `+` at one time.
=> Remove self assignment

src/XMakeBuildEngine/Definition/ProjectItem.cs
Both `configurationReader` and `_directMetadata` have `if`-checks just before the ternary checks, ensuring that they're not `null`, making the ternary expression unnecessary. 
I also dropped the `configurationReaderToUse` variable, as it's a copy of `configurationReader` and the only place it's used is in the next line where we still have access to the same `configurationReader`.
=> Remove unnecessary terniary checks

src/XMakeCommandLine/XMake.cs
The surrounding `if`-clauses prevent the checks from actually guarding against anything.
=> Fix asserts

src/Framework/Microsoft.Build.Framework.csproj, src/OrcasEngine/OrcasEngine.csproj, src/Utilities/Microsoft.Build.Utilities.csproj, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj, src/XMakeConversion/XMakeConversion.csproj, src/XMakeTasks/Microsoft.Build.Tasks.csproj
I discovered that our fully-signed builds were no longer actually
signing our product binaries. We use MicroBuild for strong-name and
Authenticode signing, and it looks for FilesToSign items in projects.
Searching through our code, I could only find these in a couple of
places related to resources assembly and VSIX production. These
correspond to the binaries that are, in fact, still being signed.
I'm not 100% sure what happened, but I think this is due to moving to a
new version of Microsoft.DotNet.BuildTools in commit db26c2d3. I assume
that it used to generate these items, and no longer does so. The fix
here is to explicitly add a FilesToSign item to each project producing
a product binary.
=> Sign product binaries

version.json
Update version.json to specify "15.1-preview5" rather than just "15.1".
This makes it clear that the binaries and NuGet packages are pre-release
verions.
This impacts the naming of our NuGet packages, which will now be called
something like "MSBuild.15.1.208-preview5-g524a1042af.nupkg".
=> Update version number

src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs
Definition\ToolsetConfigurationReader.cs(15,7): warning CS0105: The using directive for 'Microsoft.Build.Construction' appeared previously in this namespace [D
Introduced here: https://github.com/Microsoft/msbuild/commit/0a3eb9b25c3ee9f3692d5fe83fcec80ae0698d9c#diff-9166d838beb43a2c911aa6d163edd91dR13
=> Fix build warning

cibuild.cmd
The variable value wasn't being passed to build.cmd
Also add possible value of "build" and make string comparison case insensitive
=> Fix --scope argument in cibuild.cmd

dir.props, src/Framework/Microsoft.Build.Framework.nuget.targets, src/Utilities/Microsoft.Build.Utilities.nuget.targets, src/XMakeBuildEngine/Microsoft.Build.nuget.targets, src/XMakeCommandLine/MSBuild.nuget.targets, src/XMakeTasks/Microsoft.Build.Tasks.nuget.targets
These files are generated by NuGet restore and shouldn't be checked in (they are already in the `.gitignore`)
I also set the property `IncludeNuGetImports` to `false` so these files won't be imported because they just generate a warning anyway:
```
warning : Packages containing MSBuild targets and props files cannot be fully installed in
projects targeting multiple frameworks. The MSBuild targets and props files have been ignored.
```
=> Remove *.nuget.targets and *.nuget.props

dir.targets
This got lost on the xplat branch, but it's nice to have.
cc @AndyGerlicher--pretty sure we talked about this bugging us.
=> Restore "xunit ->" message when running tests

src/XMakeTasks/Microsoft.Common.props
It was using 4 spaces instead of 2 like most other files.
=> Fix whitespace in Microsoft.Common.props

dir.targets
The app.config in the test deployment directory is the same as the normal one.  The binplacing isn't working as part of the project because everything gets built to Windows_NT first and then copied to Windows_NT_Test second.  The first project containing an msbuild.exe.config binplaces the file but the rest, including the unit tests, don't bother because the file is up to date.
=> Ensure the MSBuild.exe.config is properly binplaced for unit tests

src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/Evaluation/Expander.cs, src/XMakeBuildEngine/Evaluation/ItemSpec.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.EvaluatorData.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.ItemFactoryWrapper.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.RemoveOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.UpdateOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs, src/XMakeBuildEngine/Utilities/EngineFileUtilities.cs
I've started doing this so addressing bugs like [this one](https://github.com/Microsoft/msbuild/issues/931) does not require me to change 3 different code clones (or more).
I extracted out the ItemSpec class out of the lazy evaluator code and gave it the capability of matching items against itself.
Todos:
=> Common Item spec representation

src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs
Changed the import search path logic to import matches from ALL folders
when a wildcard is specified. For example:
- <Project Import="$(propsdir)\*.props">
- (Where $(propsdir) has fallback to c:\1, c:\2)
- MSBuild will import c:\1\*.props AND c:\2\*.props.
The motivation behind this change is when packages install to common
extension points in VS "15". Some packages may still install to the old
(global) MSBuildExtensionsPath location and others may install to the
app-local path. This change will allow for MSBuild to import the union of
those extension points.
Note: We discussed as a team having MSBuild "de-dupe" imports (i.e. if it
imported foo.props in the original location it would not import a fallback
foo.props). This method becomes very tricky with all the import options …
=> Import all search paths when importing a wildcard

src/XMakeBuildEngine/UnitTests/EscapingInProjects_Tests.cs, src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/Microsoft.Common.props, src/XMakeTasks/Microsoft.Common.targets, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/XMakeTasks/UnitTests/ProjectExtensionsImportTestBase.cs, src/XMakeTasks/UnitTests/ProjectExtensionsPropsImportTest.cs, src/XMakeTasks/UnitTests/ProjectExtensionsTargetsImportTest.cs
Implementation according to this: https://github.com/Microsoft/msbuild/issues/784#issuecomment-241880891
Fixes #784
- Should this import come before or after the directory.build.props?  I had the import come **after** but this might give users less control because their local imports will happen before the NuGet imports.
FYI @eerhardt
=> Implement imports for project extensions

src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
Addresses: #919 
Also removed the GetAllGlobs(ProjectItem) overload since the CPS team has no use for it
=> GetItemProvenance(ProjectItem) now finds only the elements that might affect that item

setup/files.swr
64 bit msbuild failed because our previous vsix setup copied the x86 satellites into the x64 bin directory.
To test this, I built the vsix package locally and ran msbuild from the command line from both the x86 and the x64 vsix bin directories.
=> Copy the 64 bit satellite assemblies for 64 bit msbuild in the vsix package

src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ItemEvaluation_Tests.cs
Use loops and explicit stacks to traverse the linked list of previous operations instead of recursion.
=> Fix stack overflow with large number of item includes for the same item list

src/Utilities/ToolLocationHelper.cs, src/XMakeBuildEngine/UnitTests/Construction/XmlReaderWithoutLocation_Tests.cs, src/XMakeCommandLine/UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
- Duplicate namespace declaration in ToolLocationHelper
- Add new or override to XmlReaderNoIXmlLineInfo.Close()
- warning CS0436: The type 'AssemblyResources' in 'D:\MSBuild2\src\XMakeCommandLine\UnitTests\..\A
ssemblyResources.cs' conflicts with the imported type 'AssemblyResources' in 'MSBuild, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Usi
ng the type defined in 'D:\MSBuild2\src\XMakeCommandLine\UnitTests\..\AssemblyResources.cs'. [D:\MSBuild2\src\XMakeCommandLine\UnitTests\Microsoft.Build.Comman
dLine.UnitTests.csproj]
=> Fix some build warnings

src/Shared/MSBuildNameIgnoreCaseComparer.cs
When we moved to GitHub, we never set up the projects to define RETAIL for
release builds, as was done in the old repo. This led to a memory-use
regression because we were calling the debug method instead of the
optimized one.
Instead of defining RETAIL, I've switched to !DEBUG which reduces the
number of independent switches but seems to keep the required concept
afloat.
=> Change #if RETAIL to !DEBUG

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
For .NET Core projects, we want to pass AutoUnify=true to the RAR task. That gets set through the AutoUnifyAssemblyReferences property which derives it value from the AutoGenerateBindingRedirects property. It’s odd to have AutoGenerateBindingRedirects=true in the NETCore.props given binding redirects don’t mean anything in .NETCore. This change makes it so that we can set AutoUnifyAssemblyReferences in the props file.
/cc @rainersigwald @cdmihai @AndyGerlicher
=> Set AutoUnifyAssemblyReferences only if it hasn't already been set

setup/files.swr, src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/Microsoft.CSharp.targets, src/XMakeTasks/Microsoft.Common.CrossTargeting.targets, src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/Microsoft.Common.Traversal.targets, src/XMakeTasks/Microsoft.VisualBasic.targets
This implements the portion of cross-targeting that we agreed must happen first in msbuild proper and as soon as possible to uncover any unforseen breaking impact on existing projects.
1. Redirect Microsoft.VisualBasic/CSharp.targets to new Microsoft.Common.Traversal.targets if $(TargetFrameworks) is set, but $(TargetFramework) is empty.
2. Implement the protocol where every project will pass its TFM down to project references and get the properties that configure the destination to the best compatible target.
3. For now, the common traversal targets just import based on a variable that we will set in a props hook, but ultimately some general logic should probably be live there, and there should be a way for arbitrary nuget packages to participate. This needs design we have not yet done …
=> Traversal targets for cross-targeting

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Remove the runtime check to copy the satellite assemblies in .net core. I am currently working on a [fix](https://github.com/dotnet/sdk/pull/122) to generate satellite assemblies on .Net Core. This fix is required to make sure that the generated assemblies are copied from `obj` to `bin` folder.
cc @cdmihai @eerhardt
=> Fix to copy generated satellite assemblies (in .NetCore) from intermediate to output folder

setup/files.swr, src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/Microsoft.CSharp.targets, src/XMakeTasks/Microsoft.Common.CrossTargeting.targets, src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/Microsoft.VisualBasic.targets, src/nuget/Microsoft.Build.Targets.nuspec
@cdmihai @jeffkl @AndyGerlicher @rainersigwald
=> Port traversal targets for cross-targeting to xplat branch 

src/XMakeTasks/GetInstalledSDKLocations.cs, src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/Resources/Strings.resx
- Added optional parameter 'WarnOnNoSDKsFound' to GetInstalledSDKLocations
task. Default to previous behavior (true).
- Disabled warnings from the Microsoft Common props when Windows / Windows
Phone 8.1 SDKs are not found. For Dev15 this is a typical case for many
users and today a clean build produces two warnings.
- Added the platform identifier and version to the warning message.
Output will look like:
"No SDKs were found for TargetPlatform = WindowsPhoneApp v8.1"
=> Disable warning when legacy installed SDKs not found.

src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/UnitTests/TargetsFile_Test.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs
Fixes #724 
While excludes with slashes currently work crossplatform, they mostly work out of accident. This PR makes FileMatcher work with both slashes and backslashes. Also wrote more tests.
=> Make FileMatcher more friendly with forward and backward slashes

src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeTasks/UnitTests/GetInstalledSDKLocations_Tests.cs
There were several minor test-only problems that caused this test to fail, which is why it was disabled while trying to figure out #799.
Most of the line changes were just a bulk replace--you might like to look at the commits after the first one.
=> Fix ResolveSDKFromRegistryAndDisk test on xplat

src/Framework/AssemblyInfo.cs, src/Utilities/AssemblyInfo.cs, src/XMakeBuildEngine/AssemblyInfo.cs, src/XMakeCommandLine/AssemblyInfo.cs, src/XMakeTasks/AssemblyInfo.cs
Currently localized builds depend on resources for all cultures, including en.
This means that if you don't have satellite assemblies for en, you won't be
able to load resources at all.
We want to keep this behavior for localized *debug* builds since it will help
us flush out problems related to localization and how we layout our satellite
assemblies on disk. For *release* builds, however, we want en to fall back to
resources in the main assembly. This allows the MSBuild binaries to be used
even without satellite assemblies installed.
=> Update resource fallback behavior

src/XMakeBuildEngine/UnitTests/EscapingInProjects_Tests.cs, src/XMakeTasks/Microsoft.Common.props, src/XMakeTasks/Microsoft.Common.targets, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/XMakeTasks/UnitTests/ProjectExtensionsImportTestBase.cs, src/XMakeTasks/UnitTests/ProjectExtensionsPropsImportTest.cs, src/XMakeTasks/UnitTests/ProjectExtensionsTargetsImportTest.cs
These extensions will generally come from package management systems by writing to a file named:
$(MSBuildProjectExtensionsPath)\$(MSBuildProjectFile).<SomethingUnique>.props
Each package management system should use a unique moniker to avoid collisions.  It is a wild-card import so the order of the import is based on the file system's ordering.
Fixes #784
- Included unit tests
- Fix tests that broke when BaseIntermedateOutputPath was moved.
Current import order is:
1. directory build props
2. project extension props
3. project extension targets
4. directory build targets
PORT TO master:
Conflicts:
src/XMakeTasks/Microsoft.Common.props
src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
=> Port wildcard import of project extensions from xplat

src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
This saves memory. Otherwise, the extra list tips over the memory sensitive GC aware code from the ProjectCollection cache (and potentially other special MSBuild caches) leading to a lot of GC calls and thus performance hits.
=> Only record extra Evaluator data when needed

src/XMakeTasks/Microsoft.Common.CrossTargeting.targets
1. Move build,clean,rebuild targets and dispatch helper up from SDK targets
2. Pull in nuget restore targets
3. Pull in package-provided targets
@srivatsn @rainersigwald @AndyGerlicher
=> Add common targets and extensibility x-targeting targets

build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec
System.Resources.Reader should be 4.0.0 which it is for the other packages.
=> Fix bad dependency in Microsoft.Build.Tasks.Core package

src/XMakeTasks/Microsoft.Common.CrossTargeting.targets
Cherry-pick 93f8c8a50b1586e27cb93ed92f6910df4fcba29f:
Add common targets and extensibility x-targeting targets
1. Move build,clean,rebuild targets and dispatch helper up from SDK targets
2. Pull in nuget restore targets
3. Pull in package-provided targets
@rainersigwald
=> Port cross-targeting target changes to xplat

src/Shared/BuildEnvironmentHelper.cs, src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs
In .NET Core, the AppContext.BaseDirectory can be used to locate the application's dependencies.
Related to #1039
=> Update BuildEnvironmentHelper to locate .NET Core app directory

build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec
This was part of c09995d8911e3e64a6d33df18a3084099d1b6c07 but it went in just after the logic to automatically update these.
=> Update nuspec references to include System.AppContext

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Just like BuiltProjectOutputGroupOutput and DebugSymbolsProjectOutputGroupOutput
=> FinalOutputPath should always be FullPath for consistency

setup/files.swr, src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/Microsoft.CSharp.CrossTargeting.targets, src/XMakeTasks/Microsoft.CSharp.targets, src/XMakeTasks/Microsoft.VisualBasic.CrossTargeting.targets, src/XMakeTasks/Microsoft.VisualBasic.targets
When VS is installed it lays down a DesignTime.targets which tells the project system about the project (capabilities, msbuild rules etc.). This is pulled in by the common targets and so is available in the inner build. However it is also needed in the outer build to open a cross-targeting project in VS. When a project is opened, the CPS project system needs information like the project's capabilities, rules etc to initialize itself and without the design time targets that blows up. 
This change simply adds C# and VB cross-targeting targets and imports the designtime targets (if they exist).
@nguerrera @rainersigwald @cdmihai @AndyGerlicher
=> Pull in DesignTime.targets in the crosstargeting build

src/XMakeBuildEngine/Construction/ProjectRootElement.cs
This method was changed causing compat issues. Adding it back.
Closes #1079
=> Add back ProjectRootElement.Create overload.

src/XMakeTasks/AssemblyDependency/ReferenceTable.cs, src/XMakeTasks/SystemState.cs
Example ProjectA depends on ProjectB. Building ProjectA should copy all the satellite assemblies from ProjectB. This was working on windows but not on Unix.
There seems to be a behavior difference between Unix and Windows when using the search pattern `"*."` to get all the sub-directories. I have filed issue to track that - https://github.com/dotnet/corefx/issues/11943.
Meanwhile workaround that issue using "*" search pattern.
cc @rainersigwald @cdmihai
=> Fix to copy reference project satellite assemblies on Unix.

build/NuGetPackages/CreateNuGetPackages.proj, build/NuGetPackages/Microsoft.Build.Runtime.nuspec
I copied most of the <file /> items from the existing `.nuspec` and was able to add in the "shim" ones for full framework only.
Projects that reference this package will be able to use the MSBuild runtime to do project evaluation and in-proc builds provided they have all of the other props, targets, and executables needed.
Fixes #1039, #882, and #872.  Also fixes #1000 indirectly but the user will need to reference this package instead.
=> NuGet package containing the MSBuild runtime

build/NuGetPackages/CreateNuGetPackages.proj, src/.nuget/project.json, version.json
New packages use CreatePackages.proj instead of the dirs.proj.  This just updates the versioning logic to match what was previously done in master so that these packages will have the same versioning.
* Update version of Nerdbank.GitVersioning in our dir.props
* Add release branch of xplat for now
Related to #1039 
FYI @OmarTawfik
=> Update versioning in new packages

netci.groovy
This will make it easier to diagnose CI build failures that happen during
init--currently there's a message printed to stderr that says to look at a
file that's already deleted.
=> Archive `init-tools.log` in CI builds

src/Shared/EncodingStringWriter.cs, src/Shared/ProjectWriter.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/Construction/ProjectElement.cs, src/XMakeBuildEngine/Construction/ProjectExtensionsElement.cs, src/XMakeBuildEngine/Construction/ProjectItemElement.cs, src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs, src/XMakeBuildEngine/Construction/ProjectPropertyElement.cs, src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/Construction/Solution/ProjectInSolution.cs, src/XMakeBuildEngine/Definition/NewProjectFileOptions.cs, src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/Definition/ProjectLoadSettings.cs, src/XMakeBuildEngine/Evaluation/ProjectParser.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/Resources/Strings.resx, src/XMakeBuildEngine/UnitTests/BackEnd/MSBuild_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectFormatting_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/DefinitionEditing_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/EditingElementsReferencedByOrReferences_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectMetadata_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeBuildEngine/Xml/ProjectXmlUtilities.cs
This change ended up being somewhat more involved than I had originally hoped, and I wish I would have made the changes atomically in separate commits but I didn't have time to go back and do that after the fact. Most of the complexity revolves around mismatch between what the intent of the code appeared to be and what it actually did. The biggest example being `_writeXmlDeclaration` which was calculated but not used. To get the behavior I wanted (not writing the XML declaration when `UTF8`), this had to be fixed. But of course unit tests were expecting the old behavior so many helper methods had to be changed. We also have a fair bit of complexity because we derive from XmlDocument base classes so we can't use many of the static Create methods that were likely added later that add …
=> Support to remove unnecessary XML in project file

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
TargetFramework was getting passed down from referencing project to referenced project, which would send the referenced project straight to wrong inner build and return no properties because it gets the default target for classic projects instead of the new one from the SDK.
@rainersigwald @eerhardt @srivatsn @AndyGerlicher
=> Prevent /p:TargetFramework=x from flowing to GetTargetFrameworkProperties

src/Shared/INodePacketTranslator.cs, src/Shared/NodePacketTranslator.cs, src/XMakeBuildEngine/Definition/ProjectImportPathMatch.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Definition/ToolsetRegistryReader.cs, src/XMakeBuildEngine/UnitTests/Definition/ToolsetConfigurationReader_Tests.cs, src/XMakeBuildEngine/UnitTests/Definition/Toolset_Tests.cs
Fixes #1056 by using `ProjectImportPathMatch`'s already-precomputed string
field that represents the string to search for in an Import. Computing it
every time through `GetProjectImportSearchPaths` was wasteful.
This required a number of changes:
* Converted `ProjectImportPathMatch` to a class so it could be passed by
reference, so it could be
* Passed by reference to a translator so it could be
* Made `INodePacketTranslatable` so it could be
* Used in the toolset directly.
Since I removed the only use of `TranslateDictionaryList`, I deleted it
from both the interface and implementation of `NodePacketTranslator`.
=> Use property-format string in Import search paths

src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs
Dev15 MSBuild introduced a change of behaviour.
Dev14 MSBuild did not match excludes and includes when they referred to
the same file, but one was relative and the other absolute
Dev15 MSBuild knows how to match excludes and includes when one is relative and
the other is absolute
=> Tests for absolute / relative includes and excludes

build/NuGetPackages/CreateNuGetPackages.proj
For some reason this broke but it shouldn't be importing the parent dir.props because it overrides $(BaseOutputPath)
=> Fix package creation

build/NuGetPackages/CreateNuGetPackages.proj, cibuild.cmd, dir.props, src/dirs.proj, src/nuget/MSBuild.nuspec, src/nuget/Microsoft.Build.Conversion.Core.nuspec, src/nuget/Microsoft.Build.Engine.nuspec, src/nuget/Microsoft.Build.Framework.nuspec, src/nuget/Microsoft.Build.Targets.nuspec, src/nuget/Microsoft.Build.Tasks.Core.nuspec, src/nuget/Microsoft.Build.Utilities.Core.nuspec, src/nuget/Microsoft.Build.nuspec
Back by popular demand.  This is a revert of a26376148ef0d0d83e450d25439190400516e2b9 with the packages marked as deprecated.
I'll modify the build def to publish continue publishing the old packages to the buildtools feed while the newer ones will get published to the msbuild feed.  The older ones will continue to follow the versioning scheme `0.1.0-X` and the new ones are versioned `15.1.X`.
When I rename `MSBuild.exe` to `MSBuild.dll` I'll have to update the old packages as well.  Hopefully soon we can stop building them.
FYI @nguerrera @eerhardt
=> Bring back older packages

build/LocalizationTasks/EmitLocalizedResources.cs, build/dirs.proj, cibuild.cmd, dir.props, src/UpdateLocalizedResources.targets, src/dir.targets
This improves development experience: ideally, we'd want devs to always produce satellites. If satellite production also updates xlf files, then this produces lots of unwanted diffs (if the dev does not want to commit xlf changes).
=> Separate Xlf file syncing from localized builds

src/XMakeTasks/Microsoft.Common.CrossTargeting.targets
An "outer" build that imports `CrossTargeting.targets` can't use
`Microsoft.Common.targets`'s extensibility hooks, because some targets in
those folders may expect a fully-specified ("inner") build environment.
But NuGet (at least) needs to be able to extend the outer build--so that
it can restore to get to the inner builds.
This introduces a new folder
`Microsoft.Common.CrossTargeting.targets\ImportAfter` and a new property
`CustomAfterMicrosoftCommonCrossTargetingTargets` that allow the
CrossTargeting (outer) build to be extended.
Closes #1061.
=> Introduce CrossTargeting extensibility imports

src/dirs.proj
This is for the legacy packages only.
@tmeschter had already excluded Microsoft.Build.Engine and Microsoft.Build.Conversion.Core from building packages for NetCore.  This excludes the other packages from building on net46 because they only package files into netstandard1.3 directories anyway.
This will make it possible for me to update the build definition to be publishing the legacy and new packages during the same build.
=> Build the correct legacy packages for the correct framework

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
SatelliteDllsProjectOutputGroup did not include the FinalOutputPath
like BuiltProjectOutputGroupOutput, DebugSymbolsProjectOutputGroupOutput and
DocumentationProjectOutputGroupOutput do, making it harder to unify treatment
of those items.
=> Provide FinalOutputPath metadata for SatelliteDllsProjectOutputGroup

setup/files.swr, src/OrcasEngine/Microsoft.Build.Engine.pkgdef, src/XMakeCommandLine/MSBuild.csproj, src/XMakeConversion/Microsoft.Build.Conversion.Core.pkgdef
Include `Microsoft.Build.Conversion.Core.dll`, `Microsoft.Build.Engine.dll`, and the schema files to match existing install structure.
=> Update vsix setup

src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config
After c3f85b added these to our VSIX and we stopped using the ones built
from the VS repo (as version 15.0), various things in VS broke because
Microsoft.Build.Engine 15.0 couldn't be loaded. Adding redirects for it
and Conversion.Core which was changed similarly.
Fixes the MSBuild.exe side of
https://devdiv.visualstudio.com/DevDiv/_workitems?id=273046.
=> Add app.config redirects for deprecated assemblies

cibuild.sh
This moves the HOME folder to $WORKSPACE so that CI machines will delete the NuGet package cache and start fresh every time.
=> Move HOME folder on CI machines

setup/files.swr
Schema files should be under Bin\MSBuild not 15.0\MSBuild.
=> Fix schema file path in vsix setup

cibuild.sh, dir.targets, src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/UnitTests/EscapingInProjects_Tests.cs
Some tests use ObjectModelHelpers.CreateInMemoryProject() in order to create a temporary project.  The current implementation points to the TEMP folder which on many machines can contain well over 10,000 files.  The glob tests are timing out on Mac machines in CI probably because their TEMP folders contain even more files.
I also had to fix some tests using "wierdo" files since they are trying to create an in-memory project but expect certain things on disk.
=> Fix unit tests that use CreateInMemoryProject

src/XMakeBuildEngine/Definition/Project.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
I tested this on an artificial project with 10000 elements. Without these changes calling GIP took 1600ms. With these changes, it takes 200ms (on 12 logical cores). CPS was fine with the slight change in behaviour.
=> Improve GetItemProvenance performance

build/LocalizationTasks/EmitLocalizedResources.cs, build/dirs.proj, dir.props, src/UpdateLocalizedResources.targets, src/dir.targets
This solves a race in the SyncXlf task. Because localization is per project, and because MSBuild uses a Shared directory with shared resources (which is not a project but gets linked in by all the other projects),
each project will try to sync the shared xlf files and crash with concurrent writes.
Short term fix is to disable parallel builds when xlfs are synced. Long term fix would be turning the stuff under Shared into a csproj project.
#1138 depends on this.
=> Fix xlf syncing race

dir.props, src/UpdateLocalizedResources.targets
Fixing the race in #1145 created two other races:
- if only one project updates the shared xlf, if that project is not the first one, all the others see stale shared xlf files. This means the other projects' generated resx files will be stale. Can crash msbuild with resource not found exception
- if a project is generating resx from shared xlf just as the anointed project is updating them, the xlf won't be able to be opened.
Fast fix is to just disable parallel builds when SyncXlf is set to true. CI should not sync xlf files. We should only do this manually when we want to commit the changed xlf files (requesting localization or adding new resources (to avoid crashing localized msbuilds with resource not found)).
Other, better, but more time consuming solutions:
- synx xlf during an extra …
=> Disable parallel build on xlf sync

src/Shared/FileUtilities.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
Files with invalid characters will throw an exception, so do a check beforehand to avoid the exception.
CPS reported that projects with many non file items are hard to debug because all of the exceptions coming from this method.
Perf tests show that ~10ms are added to a GIP call on a project with 10000 item elements (from ~230ms to ~240) when GIP is called with no illegal items as paths (exceptions would not have been thrown). When all GIP calls have illegal strings as paths then, no perf hit happens. Probably the check cancels itself out with not having to call GetFullPath and swallowing the exception
=> ﻿Avoid IO exceptions when possible

src/Utilities/TrackedDependencies/FlatTrackingData.cs
This allows avoiding costly operations in the C++ build.
Submitting on behalf of @olgaark.
=> FlatTrackingData ctor with TreatRootMarkersAsEntries

src/XMakeTasks/UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs
I made an embarrassing error in f0f3487a: I deleted the Fact attribute
entirely, instead of just deleting its Skip argument.
Fixing that revealed a mismerge in 46437cc4 that put "Indirect" in a
couple of places it shouldn't have been.
Last of #799
=> Enable VerifyTargetFrameworkAttribute tests

setup/Microsoft.Build.swixproj, src/Shared/Constants.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/project.json, src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/project.json
- Change setup binpath to end in 'Output'
- Remove #if around STATIC_VERSION_NUMBER. Visual Studio version was not
defined in that way.
- Move System.Collections.Immutable to NuGet reference of the correct
version.
=> Fix-up xplat desktop build.

src/Framework/XamlTypes/DataSource.cs
Add a new property to DataSource to allow a CPS `IProjectProperties` to have customizable behavior.
For example, a rule file could contain the following:
```xml
<Rule.DataSource>
<DataSource Persistence="ProjectFile" PersistenceStyle="Attribute" HasConfigurationCondition="False" ItemType="MyType" />
</Rule.DataSource>
<StringProperty Name="MyProperty">
<DataSource PersistenceStyle="Element" />
<StringProperty> 
```
This will default to storing all properties from that rule as an attribute on the MSBuild Item, except for `MyProperty`, which will use the same data source, but be persisted as a child XML element.
=> Add PersistenceStyle property to DataSource

src/Utilities/ApiContract.cs, src/Utilities/PlatformManifest.cs, src/Utilities/ToolLocationHelper.cs, src/Utilities/UnitTests/Microsoft.Build.Utilities.UnitTests.csproj, src/Utilities/UnitTests/PlatformManifest_Tests.cs, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
Add support for the new Platform.xml value "VersionedContent" (boolean).
If present and true, this flag instructs ToolLocationHelper to retrieve References from a versioned folder. SDK team will make the appropriate changes to Platform.xml, UAP.props, and UAP.arm.props to ensure other content paths are updated appropriately.
=> adding support for versioned SDK content in ToolLocationHelper

src/Shared/BuildEnvironmentHelper.cs, src/Shared/InternalErrorException.cs, src/Shared/VisualStudioLocationHelper.cs, src/Utilities/Microsoft.Build.Utilities.csproj, src/Utilities/project.json, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj, src/XMakeCommandLine/MSBuildTaskHost/project.json, src/XMakeCommandLine/project.json, src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/project.json, src/dir.targets
This change allows for MSBuild to query the Visual Studio setup COM API (via managed interop) for instances of Visual Studio. When running on a machine with Visual Studio "15" this allows for a user to invoke the Build API without additional context (i.e. generic command window).
Also changed the behavior of the static initialization to not throw a TypeInitializationException on failure to find MSBuild.
Fixes #1161
=> Allow MSBuild to query VS setup for toolset

Before.Microsoft.Common.targets, build/NuGetPackages/Microsoft.Build.Runtime.nuspec, cibuild.cmd, cibuild.sh, dir.props, src/Shared/BuildEnvironmentHelper.cs, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuild.runtimeconfig.json, src/XMakeCommandLine/UnitTests/XMake_Tests.cs, src/XMakeCommandLine/project.json, src/dir.targets, src/nuget/MSBuild.nuspec
Instead of targeting NETStandard1.5, our executable should target netcoreapp1.0.  This also renames MSBuild.exe to MSBuild.dll
Related to #1136 Rename MSBuild.exe to MSBuild.dll for .NET Core
Closes #1136 and #1098
=> Target netcoreapp1.0 for MSBuild executable

src/XMakeBuildEngine/UnitTests/Construction/ElementLocation_Tests.cs, src/XMakeBuildEngine/Xml/ProjectXmlUtilities.cs
This just ignores purely whitespace text nodes.  The XML reader only looks at the first 4k of text to determine if it should be ignored.  Our tests are generating 70k of whitespace so the XML reader gives up after 4k and assumes its a text node.
Closes #270
Fixes test failures in #1004 when this change is ported to master.
=> Ignore whitespace text nodes when parsing projects

src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/ElementLocation/XmlDocumentWithLocation.cs, src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs, src/XMakeBuildEngine/UnitTests/Construction/ElementLocation_Tests.cs
fixes #985
If you have URL characters in your project path like `C:\Project\Project%20\proj.csproj` `XMLTextReader.Read()` method try to unescape these characters. In result the build is failed because it doesn't find the path. Workaround is to load xml from `StreamReader` instead of `string`.
=> Use streamreader instead of string to load xml

dir.props
Fixes #1128 by pointing to the subfolder where MSBuild's optimization data
lives in the (internal-only) datastore.
This fix requires the IBCMerge Microbuild plugin 0.3.1 or greater.
=> Locate optimization data in MSBuild subfolder

src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj
This was caused by the introduction of project.json to the project.  We are setting NuGetTargetMoniker in dir.props before this project has changed the TargetFrameworkVersion.
So you get these warnings:
```
"D:\MSBuild\src\XMakeCommandLine\MSBuildTaskHost\MSBuildTaskHost.csproj" (default target) (1) ->
(ResolveNuGetPackages target) ->
warning : Your project is not referencing the ".NETFramework,Version=v4.6" framework. Add a reference to ".NETFramework,Version=v4.6" in the "frameworks" section of your project.json, and then re-run NuGet restore.
```
=> Fix build warnings in MSBuildTaskHost

src/Shared/CanonicalError.cs, src/Shared/FileUtilitiesRegex.cs, src/Shared/ProjectWriter.cs, src/XMakeBuildEngine/Construction/Solution/SolutionFile.cs, src/XMakeBuildEngine/Evaluation/ConditionEvaluator.cs, src/XMakeBuildEngine/Evaluation/Expander.cs, src/XMakeTasks/AssemblyDependency/AssemblyFoldersExResolver.cs, src/XMakeTasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs
To make them run faster (.net blog says 30% faster). The increased Regex creation time should be shadowed by how many regex calls are made during evaluation (e.g. for each metadata reference) and execution.
Some regexes I could not make lazy because they are referenced from the MSBuildTaskHost which compiles against .net 3.5
=> Make static regex compiled

src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs
Globbing tests are enumerating every file in the current directory and this test is changing the current directory to the machine wide temp location.  On CI machines, there are 350,000 files there.
=> Fix hang in OS X test

src/XMakeCommandLine/UnitTests/XMake_Tests.cs
* Fix casing of response file name (casing matters on xplat)
* Copy `MSBuild.runtimeconfig.json` to temp dir
* Re-enabled the tests
Closes Tests that copy msbuild.exe fail on xplat netcore #1112
=> Fix tests that copy msbuild.exe fail on xplat netcore

dir.props, ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, ref/net46/Microsoft.Build/Microsoft.Build.cs
- This was missed when the feature was merged to xplat. The feature flag
was added to the code but not defined in the build.
=> Enable VisualStudioSetup Feature

src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Evaluation/ItemSpec.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IItemOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.RemoveOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.UpdateOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTests/Evaluation/ItemEvaluation_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
On the test repo (solution with 72 VCX projects) this reduces evaluation by ~120ms. The improvement should get significantly better the more cross item references there are.
Items can cross-reference each other during evaluation via:
- item references (`Include="@(a)"`)
- conditions on item groups, items, and metadata (`Condition="@(a->Count()) != 0"`)
- metadata item references (`<m>@(a)</m>`)
In terms of memory, the cache pressure isn't that large because many other allocations are prevented by not doing the repeated computations, so the more cross item references there are, the more the cache pays for itself
=> Cache Item computation

cibuild.cmd, cibuild.sh
Introduce a new switch `--build-only` which will do the first build only.
`--bootstrap-only` now does the first build and then creates the bootstrap folder.
Also removed an erroneous `echo on` in `cibuild.cmd`
=> Change --bootstrap-only switch in cibuild

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
We should select the AssemblyFolder.config before the AssemblyFolderEx
since the former will be used for new assemblies in Visual Studio "15"
going forward. If the registry implementation is searched first we risk
resolving assemblies from previous versions of Visual Studio before the
newer assemblies are considered.
=> Re-order assmebly search paths in RAR

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/netstandard1.3/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, src/Framework/IBuildEngine5.cs, src/Framework/IEventSource.cs, src/Framework/Microsoft.Build.Framework.csproj, src/Framework/TelemetryEventArgs.cs, src/OrcasEngine/Engine/EventSource.cs, src/Shared/TaskLoggingHelper.cs, src/Shared/UnitTests/BuildEventArgsExtension.cs, src/Shared/UnitTests/MockEngine.cs, src/Utilities/MuxLogger.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/CentralForwardingLogger.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/EventSourceSink.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/ILoggingService.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TaskHost.cs, src/XMakeBuildEngine/Definition/ProjectCollection.cs, src/XMakeBuildEngine/UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/MockLoggingService.cs, src/XMakeCommandLine/Microsoft.Build.CommonTypes.xsd, src/XMakeCommandLine/OutOfProcTaskHostNode.cs, src/XMakeTasks/Microsoft.Build.Tasks.csproj, src/XMakeTasks/Microsoft.Common.tasks, src/XMakeTasks/Resources/Strings.resx, src/XMakeTasks/Telemetry.cs, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/XMakeTasks/UnitTests/TelemetryTaskTests.cs
1. Telemetry is available to us via the LoggingService
2. Telemetry is available to task authors via IBuildEngine5.LogTelemetry() or TaskLoggingHelper.LogTelemetry()
3. Telemetry is available to target authors via the <Telemetry /> task.
To receive telemetry, consumers will need to implement an ILogger and attach to the TelemetrySent.  They can specify loggers to constructors in the object model or specify them at the command-line.
Closes #1191
=> Implement telemetry as another log message type 

src/Utilities/ToolLocationHelper.cs, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
Add new method GetSDKContentFolderPath() to enable us retrieve content folder path from versioned path if needed. In RS2 SDK, we added version information in SDK path. This is the method to make sure we get correct path.
=> Add new method GetSDKContentFolderPath()

src/XMakeBuildEngine/Evaluation/Evaluator.cs
Fixes https://github.com/Microsoft/msbuild/issues/1217
Test failures in GetUnversionedSDKUnionMetadataLocation and some response file tests seem unrelated.
@rainersigwald
=> Lower verbosity of BeforeTargets/AfterTargets diagnostics

src/XMakeTasks/GenerateResource.cs, src/XMakeTasks/UnitTests/GenerateResource_Tests.cs
Closes #1197.
This implementation is sufficient for current .NET Core--see #1247 for
details. If we start supporting linked resources, this will produce false
up-to-date results and must be changed.
cc @danmosemsft @eerhardt
=> GenerateResources incrementality for netcore

src/XMakeBuildEngine/Definition/ProjectCollection.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectCollection_Tests.cs
Since we're only setting `AssemblyVersion` but reading the "file version", then on non-Windows we display `0.0.0.0`.  Instead, this will now display the "product version" which comes from the `AssemblyVersionAttribute` and works on both Windows and non-Windows.
I've also added a unit test to ensure that this doesn't happen again.
Closes #1249
=> Fix displayed version

src/XMakeTasks/Microsoft.CSharp.CrossTargeting.targets, src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets, src/XMakeTasks/Microsoft.VisualBasic.CrossTargeting.targets, src/XMakeTasks/Microsoft.VisualBasic.CurrentVersion.targets
Imports for Design time targets is moved before common targets so that
targets that gets imported through common targets, like Nuget, will be
able to override the target and property values.
@Microsoft/build @srivatsn for review
=> Move design time targets import before Common targets

src/XMakeBuildEngine/Construction/Solution/SolutionFile.cs
... are known to be MSBuild format, so treat them as such.
Fixes #1237.
=> CPS and Roslyn project system GUIDs

src/Shared/BufferedReadStream.cs, src/Shared/NodeEndpointOutOfProcBase.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeCommandLine/MSBuild.csproj, src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj
This change adds a read buffer for reads from the named pipe streams which are used to communicate between MSBuild processes.  As there are lots of short reads in the serialization code, this should improve performance of the communication.
=> Add stream buffering for named pipe reads

src/Framework/IEventSource.cs, src/Framework/IEventSource2.cs, src/Framework/Microsoft.Build.Framework.csproj, src/OrcasEngine/Engine/EventSource.cs, src/Utilities/MuxLogger.cs, src/Utilities/Task.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/CentralForwardingLogger.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/EventSourceSink.cs, src/XMakeBuildEngine/Definition/ProjectCollection.cs
We can still improve on this by having an ILogger2 and update Logger but this will keep the telemetry stuff in without breaking people who implement IEventSource
=> Introduce IEventSource2 to not break usages of IEventSource

cibuild.cmd
I find myself doing this a lot:
```
D:\MSBuild>cibuild.cmd --scope Build && cibuild.cmd --target CoreCLR --scope build
```
This just builds both if you specify `--target both` and it also preserves the original command-line arguments.
Also fixed a missing echo from a recent change I made.
=> Add --target All to cibuild.cmd

src/Shared/UnitTests/ObjectModelHelpers.cs, src/Utilities/ProcessExtensions.cs, src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs
Also change ObjectModelHelpers.SleepCommand() to use a TimeSpan and different commands.
Disable CancelledBuildInTaskHostWithDelay20 and CancelledBuildInTaskHostWithDelay40 for scenarios where there is no task host support
Closes #1269
=> Fix unhandled exception when killing processes on non-Windows

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Targeted mitigation for #1276.
VC++ noticed a dramatic regression in solution-load performance related to
the time cost of ResolveProjectReferences. That affects all projects, but
we can safely assume that a .vcxproj is NOT using cross-targeting, while
it's impossible to detect from the outside whether a .csproj is.
This commit avoids the regression for C++ projects by just not calling the
MSBuild task again for .vcxproj references.
/cc @nguerrera @olgaark @srivatsn
=> Avoid x-targeting perf impact on vcxproj

dir.props
BuildTools now writes a file named "version.txt" which is unfortunate because GitVersioning also looks for a file named that.
This change sets `$(ObjDir)` so the BuildTools version.txt will be out of the paths taht GitVersioning searches.
=> Fix GitVersioning after recent BuildTools update

src/Shared/BuildEventFileInfo.cs, src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/UnitTests/InvalidProjectFileException_Tests.cs
When #1004 moved the standard XML reading approach to be stream-based
rather than file-based, the exceptions thrown on malformed XML
changed--System.Xml no longer knows the path, so it isn't included in the
XmlException. That caused MSBuild to fail to report the location of the
XML error in a nice way as it had done before.
Almost every case where we constructed a BuildEventFileInfo object already
had access to the full path, so I added a constructor that accepted that
as an argument and overrides the possibly-empty path returned from
XmlException.SourceUri.
Fixes #1286.
=> Keep path in invalid project exceptions

src/OrcasEngine/Engine/Engine.cs
Since we changed ProductVersion to include the git commit, the previous code was trying to call `new Version("15.1.318-preview5+gfd25bc9c7d")` 
Discovered while looking into https://devdiv.visualstudio.com/DevDiv/MSBuild/_workitems?id=286389&triage=true&_a=edit
=> OrcasEngine should not use ProductVersion

src/Shared/NodePacketTranslator.cs
Fixes #651, which was occurring because the serialized SubmissionId
returned from the remote node didn't match the saved SubmissionId, so it
wasn't marked as complete in BuildManager.OnProjectFinished. Since there
was an incomplete submission, the build never finished.
=> Keep BuildEventContext.SubmissionId in serialization

src/Shared/FileUtilities.cs, src/XMakeBuildEngine/Evaluation/ItemSpec.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs, src/XMakeBuildEngine/Utilities/EngineFileUtilities.cs
Resolves #1106.
Also fixes various issues with slash normalization which got exposed by the fix for #1106:
- slashes are normalized only when the string is a path
- checking whether a string is a valid path uses a union of Windows and !Windows characters, based on: https://github.com/Microsoft/msbuild/issues/781#issuecomment-243942514
- Re-implement Path.GetFileName so it works with potentially malformed paths.
- Normalize the slashes before normalizing the path. Otherwise .Net's implementation of GetFullPath does not work.
=> GetItemProvenance should not unescape input

src/XMakeBuildEngine/Resources/Constants.cs, src/XMakeBuildEngine/Utilities/Utilities.cs
This only applies for "app local" MSBuild.  Our NuGet package does not have the Extensions folder and the dotnet CLI is already setting this so property.
Closes #1335
=> Remove "Extensions" folder from MSBuildExtensionsPath

src/XMakeCommandLine/XMake.cs
The switch is #ifdef'd out in our list of possible switches but not the help.  I skimmed the other switches in help and /validate looks like the only one we missed.
Closes #1342
=> Remove /validate switch from help on .NET Core

dir.props, src/Shared/CommunicationsUtilities.cs
RtlMoveMemory is not available on Nano Server, so the runtime check
introduced in 60a585c isn't quite right: Nano Server is Windows but
doesn't have this API exposed.
Introduce a new feature flag for RtlMoveMemory, used only when building
for Full Framework. For Mono and .NET Core builds, use the simpler (and I
guess slower? Would like to see a benchmark)
Environment.GetEnvironmentVariables codepath.
Related to #1233.
=> Only use RtlMoveMemory on Full Framework

src/XMakeCommandLine/Microsoft.Build.CommonTypes.xsd
Update schema to add TargetFramework to PropertyGroup, PackageReference to ItemGroup and the valid sub properties of PackageReference.
Related to #1317
=> Add TargetFramework and PackageReference to the schema

src/Shared/NodePacketTranslator.cs
`GetTypeInfo().Assembly` seems to produce bogus results at least some of
the time (noticed especially for XmlException). Since exceptions are
serialized by including the exception's type and assembly, and then
deserialized by reflecting over that assembly to find the type's
constructor, this could cause an unhandled exception if the assembly
couldn't be loaded.
This change wraps the attempt to find the constructor robust to
file-not-found errors--if the assembly can't be loaded, simply use the
preexisting FormattedError fallback case.
Fixes #1246.
=> Make SerializedException robust to load errors

src/XMakeBuildEngine/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
Resolves the worst UI behavior of #1308 by avoiding
the slow synchronous operations when hosted by
devenv.exe.
=> Avoid result caching in Visual Studio

build/NuGetPackages/Microsoft.Build.Conversion.Core.nuspec, build/NuGetPackages/Microsoft.Build.Engine.nuspec, build/NuGetPackages/Microsoft.Build.Framework.nuspec, build/NuGetPackages/Microsoft.Build.Runtime.nuspec, build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec, build/NuGetPackages/Microsoft.Build.nuspec, dir.props, src/MSBuild.sln, src/XMakeBuildEngine/project.json
After our NuGet packages are pushed, the XMLNS is different in the downloaded one as well as the encoding/BOM.
I'm hoping just removing this stuff is enough to fix this problem.
I also updated the solution to include the new nuspecs and removed the old ones.
=> Remove xml stuff from nuspecs

src/Shared/FileMatcher.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs
[test.txt](https://github.com/Microsoft/msbuild/files/593579/test.txt)
I've included a sample project file that would cause a null ref in src/Shared/FileMatcher.cs. I looked around inside GetFilesRecursiveStep to see if Files should have just been set to an empty array, but it didn't appear to match stylistically with the surrounding code so I just put the guard in GetFilesRecursive.
=> Guard against null ref when a Glob exclude fails to match any files

ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Shared/FileUtilities.cs, src/XMakeBuildEngine/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
* `ShouldCloneXmlAttribute()` method
* BuildRequestEngine.cs(843,17): warning CS1587: XML comment is not placed on a valid language element
* FileUtilities.cs(575): warning CS1574: XML comment has cref attribute 'GetFullPathNoThrow(string, string)' that could not be resolved
* FileUtilities.cs(597): warning CS1574: XML comment has cref attribute 'GetFullPathNoThrow(string, string)' that could not be resolved
=> Update ref assembly source and fix some warnings

src/XMakeTasks/UnitTests/Exec_Tests.cs
The issue was fixed by #886.  This is a revert of 2b3d4f1cd1cb50a3c942d77e316338e448385d2f with the expected exit code updated for cross-platform.
Closes #434
=> Enable Exec_Tests.Timeout

src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs
This test shouldn't be as flaky because I fixed a bug in killing processes in 9bcc0028f211b6198f8514ae4a7e7f823dba18ce
Closes #696
=> Enable CancelledBuildWithDelay20

src/XMakeCommandLine/XMake.cs
If MSBUILDDEBUGONSTART=2 you will now see:
```
Waiting for debugger to attach (PID 21552).  Press enter to continue...
```
Closes #1118
=> Print out prompt and process ID when waiting for a debugger to attach.

src/XMakeTasks/UnitTests/WriteCodeFragment_Tests.cs, src/XMakeTasks/WriteCodeFragment.cs
CodeDom is not available on .net core, so copy over its string quoting implementation.
Ideally, all this code should be replaced with crossplatform Roselyn
Fixes #1294
=> Mimic Full Framework string quoting

src/XMakeBuildEngine/Construction/ProjectElementContainer.cs, src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/ElementLocation/XmlDocumentWithLocation.cs, src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/WhiteSpacePreservation_Tests.cs, src/XMakeBuildEngine/Xml/XmlReaderExtension.cs
I've spent way too much time on this already. Pushing to get feedback or ideas. You can see I tried to set _normalize = false. This worked on Full Framework, but seems to do nothing on .NET Core. Whatever implementation I use seems to have some sort of bug and is not usable...
Background:
* Previous implementation on Full Framework used XmlTextReader(path). This contained an issue with certain characters (#985) and was fixed by using streams (#1004). #1004 also changed from XmlTextReader to XmlReader.
* XmlReader contains logic to normalize line endings. Internally, it sets the Normalize property to true and replaces (some? all?) \r\n with \n.
This change switches implementation to use XmlTextReader with a stream on Full Framework. This class sets the internal Normalize to false and does …
=> Fix issue with xml file line ending normalization

src/UpdateLocalizedResources.targets
Because AfterTargets does not guarantee that the target will be executed
after its AfterTargets, but DependsOnTargets does.
This lead to the `AddSatelliteAssembliesToFilesToSignItem` target being executed before the item it read got computed.
=> Signing specific loc targets use DependsOnTargets

src/XMakeTasks/NativeMethods.cs
=> Compare strong names only when both assemblies are strong named

src/Shared/UnitTests/App.config, src/XMakeBuildEngine/Definition/ToolsetLocalReader.cs, src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config, targets/DeployDependencies.proj
This change was postponed to another release. Keeping the functionality of
consuming Roslyn from a single location, just adjusting the path. Compared
to previous release, we will now *always* consume Roslyn from the 32-bit
MSBuild folder. This should be fine as the bits are identical.
Related to #1339
=> Undo consume Roslyn from new location.

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs
1. Add extra overloads for `ProjectRootElement.TryOpen` with `preserveFormatting` options.
2. Expose `PreserveFormatting` as a read-only property on `ProjectRootElement`. CPS needs this for the live-reload scenario.
=> Add preserveFormatting overloads. Expose PreserveFormatting as read-only property

src/XMakeCommandLine/InitializationException.cs, src/XMakeCommandLine/Resources/Strings.resx, src/XMakeCommandLine/UnitTests/XMake_Tests.cs, src/XMakeCommandLine/XMake.cs
If Directory.Exists then the current code just uses that as the base directory to search.
Needed to add a new error so that the directory path of what was searched is shown instead of it just saying "this directory".  I also updated the help text.
```
Syntax:              MSBuild.exe [options] [project file | directory]
Description:         Builds the specified targets in the project file. If
a project file is not specified, MSBuild searches the
current working directory for a file that has a file
extension that ends in "proj" and uses that file.  If
a directory is specified, MSBuild searches that
directory for a project file.
```
Closes #1225
=> Support Directory project path argument

dir.props, ref/net46/Microsoft.Build/Microsoft.Build.cs, src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs, src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/BuildEventArgTransportSink.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/EventSourceSink.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/ILoggingService.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/LoggingService.cs, src/XMakeBuildEngine/BackEnd/Shared/BuildResult.cs, src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/EventSourceSink_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/MockLoggingService.cs, src/XMakeCommandLine/CommandLineSwitches.cs, src/XMakeCommandLine/Resources/Strings.resx, src/XMakeCommandLine/UnitTests/CommandLineSwitches_Tests.cs, src/XMakeCommandLine/XMake.cs
Specify just /WarnAsError to have all warnings logged as errors as well as have the build fail.
Specify a comma delimited list of warning codes to have just that set of warnings treated as errors as well as have the build fail.
Targets will still show as succeeded and the tasks will continue to execute but the overall build result will be a failure.
Related to #68 and will close in my next change to add /NoWarn.
Help text should be reviewed as well:
```
/warnaserror[:code[;code2]]
List of warning codes to treats as errors.  Use a semicolon
or a comma to separate multiple warning codes. To treat all
warnings as errors use the switch with no values.
(Short form: /err[:c;[c2]])
Example:
/warnaserror:MSB4130
When a warning is treated as an error the target will
continue to execute as if it …
```
=> Implement /WarnAsError to treat specified warnings as errors

ref/net46/Microsoft.Build/Microsoft.Build.cs, src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs, src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/BuildEventArgTransportSink.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/EventSourceSink.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/ILoggingService.cs, src/XMakeBuildEngine/BackEnd/Components/Logging/LoggingService.cs, src/XMakeBuildEngine/UnitTests/BackEnd/EventSourceSink_Tests.cs, src/XMakeBuildEngine/UnitTests/BackEnd/MockLoggingService.cs, src/XMakeCommandLine/CommandLineSwitches.cs, src/XMakeCommandLine/Resources/Strings.resx, src/XMakeCommandLine/UnitTests/CommandLineSwitches_Tests.cs, src/XMakeCommandLine/XMake.cs
You cannot suppress all warnings, if you specify empty `/warnasmessage` or `/nowarn`, you get an error message.
Warnings are mutated into just a message.
Ignore the first commit which is the implementation of /WarnAsError
Closes #68
Closes #47
Closes #910 
So this:
```
MyProject.proj(3,18): warning MSB4130: The condition "true or true and true" may have been evaluated incorrectly 
in an earlier version of MSBuild. Please verify that the order of the AND and OR clauses is written as intended. To 
avoid this warning, add parentheses to make the evaluation order explicit.
```
Becomes this in with Verbosity=Detailed 
```
MyProject.proj(3,18): message MSB4130: The condition "true or true and true" may have been evaluated incorrectly
in an earlier version of MSBuild. Please verify that the …
```
=> Implement /NoWarn functionality

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Satellite assemblies are produced only with TargetPath metadata, which makes rediscovering their culture later in the build very difficult. Simply preserving it as a distinct metadatum makes scenarios such as NuGet packaging of Roslyn analyzers that are localized much easier.
BTW, I'm not sure about the target branch for this. I think it should ship xplat as well as in Dev15 RC.3. Is this the right branch for that?
=> Preserve Culture metadata on satellite assemblies

src/XMakeBuildEngine/Construction/ProjectRootElement.cs
The initial implementation caused errors when editing a project in Visual
Studio. The Roslyn Project System uses Project.Xml.RawXml to decide what
to show to the user, and handles edits by saving that file. When RawXml
had _Implicit elements, that made the first save create an invalid project
with a literal _Implicit attribute in its imports (as well as imports from
both the Sdk attribute and the now-present Import elements).
To fix this, do the same transformation for RawXml that was being done for
Save.
=> Do not reveal implicit elements through RawXml

Samples/Dependency/Dependency.csproj, cibuild.cmd, cibuild.sh, src/Shared/Compat/TypeExtensions.cs, src/Shared/Compat/XmlCharType.cs, src/Shared/NodeEndpointOutOfProcBase.cs, src/Shared/TaskHostConfiguration.cs, src/Shared/UnitTests/NativeMethodsShared_Tests.cs, src/Utilities/UnitTests/Microsoft.Build.Utilities.UnitTests.csproj, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs, src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/XMakeBuildEngine/BackEnd/Node/NodeConfiguration.cs, src/XMakeBuildEngine/Collections/ConvertingEnumerable.cs, src/XMakeBuildEngine/Definition/Toolset.cs, src/XMakeBuildEngine/Definition/ToolsetReader.cs, src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs, src/XMakeBuildEngine/UnitTests/BackEnd/TaskBuilder_Tests.cs, src/XMakeBuildEngine/UnitTests/Construction/XmlReaderWithoutLocation_Tests.cs, src/XMakeBuildEngine/UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeCommandLine/UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj, src/XMakeCommandLine/XMake.cs, src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs, src/XMakeTasks/GenerateResource.cs, src/XMakeTasks/GetReferenceAssemblyPaths.cs
Fixed the 40+ remaining warnings when building for .NET Core.  Most were related to `#if`'s in the wrong place.  
This also enables `/warnaserror` in cibuild but I had to add 3 warnings to the `/nowarn` list:
```
warning AL1053: The version '1.2.3.4-foo' specified for the 'product version' is not in the normal 'major.minor.build.revision' format.
warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.
warning MSB3026: Could not copy "XXX" to "XXX". Beginning retry 1 in 1000ms.
```
=> Fix more warnings, enable /warnaserror

src/Shared/FileUtilities.cs, src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs
Rather than just "fix" the file path, this normalizes it and fixes the directory separators.  I did not make a unit test because `FileUtilities.NormalizePath()` is well tested.
Closes #55
=> Add NormalizePath() to IntrinsicFunctions

src/XMakeTasks/GetReferenceAssemblyPaths.cs, src/XMakeTasks/UnitTests/GetReferencePaths_Tests.cs
When this message was converted to a warning (for #173), we added an escape-hatch environment variable to revert to the previous warning-only behavior. A comment indicated that the escape hatch should be removed before the next major release, so I'm removing it.
@AndyGerlicher
=> Remove escape-hatch for NoReferenceAssemblyDirectoryFound

src/BuildValues.props, src/XMakeBuildEngine/Construction/ProjectElementContainer.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectSdkImplicitImport_Tests.cs
Fixes #1431.
If a project had an Sdk attribute (and thus implicit Import elements), calling DeepClone on it could throw:
```
Unhandled Exception: System.ArgumentException: The reference node is not a child of this node.
at System.Xml.XmlNode.InsertAfter(XmlNode newChild, XmlNode refChild)
at Microsoft.Build.Construction.ProjectElementContainer.AddToXml(ProjectElement child)
at Microsoft.Build.Construction.ProjectElementContainer.InsertAfterChild(ProjectElement child, ProjectElement reference)
at Microsoft.Build.Construction.ProjectElementContainer.DeepClone(ProjectRootElement factory, ProjectElementContainer parent)
at Microsoft.Build.Construction.ProjectElementContainer.DeepClone(ProjectRootElement factory, ProjectElementContainer parent)
at …
```
=> Consider Implicit status to find insertion loc

src/BuildValues.props, src/XMakeBuildEngine/Construction/ProjectElementContainer.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectSdkImplicitImport_Tests.cs
=> Ignore implicit on remove

src/XMakeTasks/LC.cs, src/XMakeTasks/UnitTests/LC_Tests.cs
File arguments are not supported by lc.exe until version 4.6.2 as explained in issue #914
=> Fix lc.exe compatibility with file arguments

src/Shared/UnitTests/App.config, src/XMakeBuildEngine/Definition/ToolsetLocalReader.cs, src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config, targets/DeployDependencies.proj
Reverts Microsoft/msbuild#1391
=> Redo consume Roslyn from new location

src/XMakeTasks/Error.cs, src/XMakeTasks/Resources/Strings.resx, src/XMakeTasks/UnitTests/ErrorWarningMessage_Tests.cs, src/XMakeTasks/Warning.cs
Logs (No message specified)
Closes #1350 
Sample output
```
Build started 12/5/2016 2:41:07 PM.
Project "C:\Users\jeffkl\Desktop\Stuff\1350.proj" on node 1 (default targets).
C:\Users\jeffkl\Desktop\Stuff\1350.proj(8,5): error : (No message specified)
Done Building Project "C:\Users\jeffkl\Desktop\Stuff\1350.proj" (default targets) -- FAILED.
Build FAILED.
"C:\Users\jeffkl\Desktop\Stuff\1350.proj" (default target) (1) ->
(Build target) ->
C:\Users\jeffkl\Desktop\Stuff\1350.proj(8,5): error : (No message specified)
0 Warning(s)
1 Error(s)
Time Elapsed 00:00:00.35
```
=> Log a message when nothing is specified to Error and Warning tasks

src/XMakeTasks/WriteCodeFragment.cs
MSBuild currently uses 'VB' as the name of <Language> for a VB project, so WriteCodeFragment should support the same.
=> Add 'VB' as a language name for WriteCodeFragment

src/XMakeBuildEngine/Evaluation/Preprocessor.cs
Looks like there was one place in the preprocessor where it wasn't replacing "--" with "--" in Xml comments.
@rainersigwald
=> Fix invalid Xml comment being generated in preprocessor if "--" is in the path to a resolved Sdk

src/XMakeBuildEngine/Definition/ProjectImportPathMatch.cs, src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs
- Fix scenario where import fallback is specified in the toolset for a
property that is not defined. This scenario works but will throw a
null-ref exception trying to error if the imported project is not
found.
- Added checks for null and guards against empty strings being considered
for fallback.
Fixes #1458
=> Fix null-ref on project import fallback error message.

src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/Evaluation/Expander.cs, src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs, src/XMakeBuildEngine/Resources/Strings.resx, src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs, src/XMakeBuildEngine/UnitTests/MockElementLocation.cs
Only accepts a file name
Expander magically passes the directory containing IElementLocation.File before the method is called so users don't have to specify both arguments.
Closes #1277
=> Implementation of GetPathOfFileAbove

src/XMakeCommandLine/XMake.cs
Sometimes MSBuild is running under `MSBuild.exe` but sometimes it's running under `dotnet.exe`.  This change just prints out the path to the "main module" so its easier to determine what to attach the debugger to.
=> Print process module path when waiting for debugger to attach

src/XMakeTasks/CodeTaskFactory.cs
We could that since the assembly is loaded via `Assembly.Load(byte[])`, it is not allowed to use loaded dependencies because they came from a different load context.  This change keeps a static dictionary around with a mapping of assembly strong name and assembly.  If the inline task asks for the dependency at run time, the assembly resolve handler will return the loaded assembly if the strong name is the same.
Users will still experience runtime exceptions if they only list top-level dependencies in their `<Reference />` list.  To get around this, they'll need to list the full closure of dependencies that are not in the GAC or the MSBuild.exe directory.
Closes #594
=> Add AssemblyResolve handler for in-memory assemblies in CodeTaskFactory

dir.props, src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs, src/XMakeTasks/NativeMethods.cs
`AssemblyInformation.GetRuntimeVersion` calls into `mscoree.dll`, which is part of NetFX and not available on .NET Core.
Because .NET Core is the only flavour of .NET available on Nano Server, this task would fail on Nano Server.
In this PR, the call to `mscoree.dll` is put behind a `FEATURE_MSCOREE` feature flag which is set for NetFX only. If this feature flag is not set, `ManagedRuntimeVersionReader.GetRuntimeVersion(path);` is used instead.
Related issues:
Closes #1233
dotnet/cli#4469
dotnet/cli#5081
/cc @rainersigwald, @jeffkl
=> Fix AssemblyInformation.GetRuntimeVersion on Nano Server

build/MicrobuildTest.ps1
Checker for MSBuild's internal build that verifies that the layout looks good, assemblies are signed, etc
Future possible checkers:
- unzip the nuget and vsix packages and repeat the checkers on the contents
There will probably be some follow-up PRs after this one once we get this running in Microbuild. I tested it on binary drops by changing the drops such as to hit each branch in the checkers
=> Checker for Microbuild output

src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs, src/XMakeBuildEngine/BackEnd/Shared/BuildRequestConfiguration.cs, src/XMakeBuildEngine/Construction/Solution/SolutionProjectGenerator.cs, src/XMakeBuildEngine/Instance/ProjectInstance.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionFile_Tests.cs, src/XMakeBuildEngine/UnitTests/Construction/SolutionProjectGenerator_Tests.cs
This allows users to access any target when building a solution.  The target may or may not exist but this will create the corresponding targets in the `.metaproj`.
I had to pass along the target names from the build request all the way down to the solution generator via ReadOnlyCollections.
Closes #1275
=> Generate targets in metaproj

src/XMakeBuildEngine/Logging/BaseConsoleLogger.cs, src/XMakeBuildEngine/Logging/ParallelLogger/ParallelConsoleLogger.cs
Always show the Time Elapsed and Build Succeeded text whenever the user
specifies the 'summary' console property flag regardless of log verbosity
or presence of the ErrorsOnly / WarningsOnly flags.
Closes #1513
=> Enable build summary text for more scenarios.

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs, src/XMakeBuildEngine/Resources/Strings.resx, src/XMakeBuildEngine/UnitTests/Evaluation/ProjectRootElementCache_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
This would enable IDEs to keep reloading a ProjectRootElement when the user changes the file instead of doing reference swapping or relying on `DeepCopyFrom` / `DeepClone` which do not preserve XML trivia (whitespace and comments).
This helps address #1442 and #1472.
Unclear points to discuss, probably best left for a future PR:
- Should the ProjectRootElementCache reload instead of forgetting entries when the white space preservation missmatches or `autoReloadFromDisk` is true?
- pros
- references stay the same so no weird stale issues (e.g. an evaluated Project gets stale if the Cache decides to forget the ProjectRootElements the Project references, and would stop receiving changed events.). An alternative to this is to forget entries but pipe through new events so evaluated projects …
=> ProjectRootElement can reload itself

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets, src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/XMakeTasks/UnitTests/RegressionTests.cs
We used to ensure the trailing slash in common targets but I moved this to common props.  This however broke the scenario when a user sets the property since the trailing slash is not ensured and the _CheckForInvalidConfigurationAndPlatform target would then fail.
I also introduced a unit test to ensure this doesn't regress again.
Closes #1509
=> Ensure BaseIntermediateOutputPath has a trailing slash when set by user

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Shared/XMakeAttributes.cs, src/XMakeBuildEngine/Construction/ImplicitImportLocation.cs, src/XMakeBuildEngine/Construction/ProjectElement.cs, src/XMakeBuildEngine/Construction/ProjectElementContainer.cs, src/XMakeBuildEngine/Construction/ProjectImportElement.cs, src/XMakeBuildEngine/Construction/ProjectRootElement.cs, src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Evaluation/Preprocessor.cs, src/XMakeBuildEngine/Evaluation/ProjectParser.cs, src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/UnitTests/Evaluation/Preprocessor_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ElementLocationPublic_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectSdkImplicitImport_Tests.cs
Had to do some hacky stuff in the preprocessor but all of that code is private and we can make it better in the future.
Closes #1447
=> Implementation of implicit imports during evaluation instead of parsing

src/XMakeTasks/Microsoft.NETFramework.CurrentVersion.targets
=> Only include DesignTimeFacadeAssemblies which are not in ReferencePath

build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec, build/NuGetPackages/Microsoft.Build.nuspec
These changes were made automatically via `cibuild.cmd --target
CoreCLR`, and update the checked-in specs to match the new references.
=> Update nuspecs for #1522

src/Utilities/project.json, src/XMakeBuildEngine/UnitTestsPublicOM/project.json, src/XMakeBuildEngine/project.json, src/XMakeTasks/project.json, targets/runtimeDependencies/project.json
Upgrading dependencies across the board as a consequence of taking the
Roslyn + System.Collections.Immutable update in #1522 updated too much,
causing breakage in dotnet CLI. See dotnet/cli#5266 for some discussion.
This commit attempts to keep the dependencies for .NET Core MSBuild
identical to what they were before while still taking the
System.Collections.Immutable update for Full Framework that's required to
avoid a VS perf hit.
=> Avoid .NET Core 1.1 dependencies for Core

src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs, src/XMakeBuildEngine/UnitTests/Evaluation/ProjectRootElementCache_Tests.cs
This is related to
https://devdiv.visualstudio.com/DevDiv/_workitems?id=366048 and
https://devdiv.visualstudio.com/DevDiv/_workitems?id=366077, and
possibly #1526.
In those bugs, a worker node is started and given build requests for the
same project while that project changes on disk. The first build works
(fresh load in the worker node). The second build works (content is
reloaded). But the third one fails--it throws because the project "has
unsaved changes" when it's trying to reload it again. That failure isn't
well communicated back to the main node, so this tends to not log
anything and just abruptly fail the build.
To fix this, I'm reverting the part of #1507 that hit in the worker
node--the only place where `_autoReloadFromDisk` is set to true in the
current world. Instead of using …
=> Drop + reload changed projects in worker nodes

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
This supports the publish scenario of Microsoft.NET.Sdk-based projects that reference non-Microsoft.NET.Sdk-based projects.
Fix dotnet/sdk#543
=> Add default implementation of GetCopyToOutputDirectoryItems

src/XMakeBuildEngine/Microsoft.Build.csproj
This file is required by the VSIX builder, and was placed in Output as
part of the transitive dependencies of
Microsoft.Build.Tasks.CodeAnalysis, but more recent versions don't have
that dependency, so it wasn't getting placed.
Added a workaround to ensure that Immutable appears in the folder.
=> Binplace System.Collections.Immutable to Output

src/Shared/NativeMethodsShared.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj, src/XMakeBuildEngine/UnitTestsPublicOM/project.json
VS has potentially expensive TypeResolve events, so cache IsMono. Apparently the c++ side of things even triggers a design time build during some TypeResolve calls.
=> Cache IsMono call

cibuild.cmd
I'll only be updating cibuild.cmd so ignore the other change as I'm using it to test this.
=> Fail the CI build if there are any uncommitted changes

src/XMakeTasks/Copy.cs
Copy task: Use MessageImportance.Normal when logging messages about failures to create hard/sym links. 
Fix for #1564
=> Copy task: Use MessageImportance.Normal when logging messages

src/XMakeBuildEngine/Construction/ProjectRootElement.cs
Change the default behavior of `ProjectRootElement.Open(String, ProjectCollection)` and `ProjectRootElement.TryOpen(String, ProjectCollection)` to pass `preserveFormatting: null`. This way calls using that overload will not trigger project reloads and set preserveFormatting to false.
=> Change Open and TryOpen to pass preserveFormatting: null

build/MicrobuildTest.ps1
With these changes, we can finally run this script with every microbuild
=> Fix build checker when running inside microbuild environment

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Visualy Studio will drop this file to the root of MSBuild only. On x64
MSBuild the file won't be found unless it looks in MSBuildToolsPath32.
=> Read AssemblyFolders.config from ToolsPath32

README.md
I thought we might want to point people to the latest reference of MSBuild on docs. Also, removed locale and product family version from the msdn links so they go to the latest and to the locale specified by the user in their machine.
=> updated some doc links

dir.targets, src/XMakeCommandLine/MSBuild.csproj
Add logic to respect the `LargeAddressAware` property as was done in the VS repo. Added that property to the `MSBuild.exe` project.
Fixes #1580 by restoring behavior from v14 and prior builds.
=> Set LARGEADDRESSAWARE for x86 .exes

src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/XMakeBuildEngine/Evaluation/ItemSpec.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs, src/XMakeBuildEngine/Utilities/EngineFileUtilities.cs
Fixes #1598. The problem is worse than item provenance alone. `<I Include="..\a.foo" Exclude="**\*.foo"/>` excludes `..\a.foo` in xplat, but didn't in dev14. This PR fixes issues of this type.
=> Glob matching is path aware

ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, ref/netstandard1.3/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, src/Utilities/ToolTask.cs, src/Utilities/UnitTests/ToolTask_Tests.cs
Current ToolTask implementers are able to set values for previously undefined environment variables and to override previously defined variable values via the EnvironmentVariables property. They are not, however, able to remove Environment Variables which should not be passed down to the ToolTask's child process. 
This inability to manage a ToolTask's environment creates issues particularly in the builds of programs whose behavior is affected by the process environment like https://github.com/dotnet/cli. A ToolTask which invokes such a program needs to be able to selectively provide a `clean` process, ensuring deterministic build behavior. Of course, sometimes it makes sense for such variables to flow, but there is not a current option for preventing that flow without re-implementing …
=> Allow ToolTask.GetProcessStartInfo to be overridden

src/XMakeBuildEngine/Evaluation/Evaluator.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.RemoveOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.UpdateOperation.cs, src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs, src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs
Partially resolves #1475 by making Removes and Updates whose condition evaluates to false not apply to `Project.Items`
Leaves #1616 unfixed. Fixing that one requires changes that are too risky for RTW. The items from `Project.ItemsIgnoringCondition` are only used by the old project system, meaning their Solution Explorer will show incorrect data when using conditioned Removes and Updates.
=> Update and Remove should not apply to Project.Items when their condition is false

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
1. Deal with UWP case where NugetTargetMoniker is needed instead of TargetFrameworkMoniker
2. Provide mechanism to override the moniker that is passed to reference
3. Provide mechanism to pick any target framework of reference
4. Provide mechanism to skip the best TFM computation for known single-targeting case
@AndyGerlicher @rainersigwald
**Customer scenario**
*Primary:* 
Referencing an SDK/CPS-based project from UWP project would behave incorrectly (pick wrong TFM of reference) or fail with incorrect incompatibility error.
Also:
* There was no supported way to override the moniker sent to refs.
* There was no supported way to pick a different TFM than the one selected by the SDK for a cross-targeted ref, but sometimes you want to test a different one than the one deemed best for the …
=> Improve P2P handling for cross-targeting

src/Utilities/TrackedDependencies/FileTracker.cs
In conjunction with internal PR https://devdiv.visualstudio.com/DevDiv/MSBuild/_git/VS/pullrequest/55140, fixes internal bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/286164, which prevents processes from running under Tracker.exe when FileTracker32.dll is found in a path with non-ANSI (Unicode) characters on the path.
=> Filetracker from global ansi path

src/XMakeBuildEngine/Evaluation/Expander.cs
String.TrimEnd has a new overload for a single char in .NET Core 2.0. However, when MSBuild encounters this new overload first, it throws a FormatException which is not caught - breaking the build.
The fix is to catch the FormatException just like an InvalidCastException and continue searching the rest of the reflection MethodInfos for a match.
Fix #1634
@rainersigwald @AndyGerlicher 
This change isn't necessary for "1.0", but I need to get an MSBuild version with this fix to unblock taking a new corefx in dotnet/cli/master.
=> Catch FormatException coming from Convert.ChangeType.

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
**Customer scenario**
Building a classic portable class library with any project references fails
**Bugs this fixes:**
[VSO 377419](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=377419&_a=edit)
**Workarounds, if any**
Set ReferringTargetFrameworkForProjectReferences=$(TargetFrameworkMoniker) in your project file.
**Risk**
Low
**Performance impact**
Low
**Is this a regression from a previous update?**
Yes, introduced very recently.
**Root cause analysis:**
We missed that $(NugetTargetMoniker) can contain multiple values and validation did not run through classic PCL scenarios.
**How was the bug found?**
Dogfooding. (The dogfooders affected have tested with this fix applied and confirmed it eliminates the problem.)
@AndyGerlicher @rainersigwald @cdmihai
=> Do not use NTM if it has more than one value

dir.targets
Unfortunately, we have two processes that run in sequence to modify the
output binary in place. This can happen:
* Initial compile
* First editbin
* First OpenSourceSign
* Second compile (skipped, up to date)
* Second editbin (runs, wasn't incremental before this commit)
* Second OpenSourceSign (runs, prior step makes it appear out of date)
The last OpenSourceSign then complains "this assembly is already
signed", breaking the build.
Fixes #1657 by treating editbin + OpenSourceSign as a unit for purposes
of incrementality.
=> Make LargeAddressAware incremental

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Partially fixes dotnet/sdk#739.
The first iteration of cross-targeting support code unconditionally
queried each ProjectReference for the best TFM to build against, and
then explicitly specified that TFM when building the reference. This
caused a race condition when building a set of projects that had a
single-TFM project and another project that had a reference to it. The
entry point (probably .sln) build would build the referenced project
with no TF specified, and then the referencing project would build it
with an explicit TF specified. These two builds appeared different to
the MSBuild engine (because they had different sets of global
properties) and so were both executed, resulting in a race condition.
The fix is in two parts:
* Allow a project to report back through …
=> Respect projects that say they only have one TFM

src/XMakeTasks/UnitTests/FileStateTests.cs
The other usage was already removed in ee0d5b1115d28e7672e8d64a0a45229093f0fbdf
This change removes some tests that I believe were never finished.
Closes #277
=> Remove test dependency on notepad.exe

src/XMakeBuildEngine/Microsoft.Build.csproj, src/XMakeBuildEngine/project.json
For full framework we're pulling this reference from the GAC and on .NET Core its coming from a NuGet package.  This leaves us with references to different versions which is not ideal.
=> Unify reference to System.Threading.Tasks.Dataflow

src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets, src/XMakeTasks/Microsoft.VisualBasic.CurrentVersion.targets
The Web SDK uses the `AppDesignerFolder` property to [exclude launchSettings.json files from publish](https://github.com/aspnet/websdk/blob/75184cba7a7a59c580caf60a74fac247a29d807b/src/Web/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L28):
```xml
<Content Update="$(AppDesignerFolder)/**" CopyToPublishDirectory="Never" Condition="'$(AppDesignerFolder)' != ''"/>
```
However, the `AppDesignerFolder` property is currently only set in the [CSharp](https://github.com/dotnet/roslyn-project-system/blob/fae6ac3cda03df01d05ab47d10b95e39134c85c7/src/Targets/Microsoft.CSharp.DesignTime.targets#L14) / [Visual Basic](https://github.com/dotnet/roslyn-project-system/blob/fae6ac3cda03df01d05ab47d10b95e39134c85c7/src/Targets/Microsoft.VisualBasic.Desig …
=> Add default values for AppDesignerFolder property

src/XMakeTasks/Microsoft.Common.CrossTargeting.targets
Fixes #1065 by duplicating `DispatchToInnerBuilds` to the crosstargeting
version of `Clean`. This enables Clean to run before Build (or the
arbitrary user target set via the `InnerTargets` property), reducing the
surprise of command line builds that use `/t:Clean;Build` rather than
`/t:Rebuild`.
This change also changes the cross-targeting definition of `Rebuild` to
match the standard `Clean;Build` rather than invoking `Rebuild` on each
inner build. That makes it easier to author outer-build extension logic,
fixing NuGet/Home#4475.
=> Enable clean + build of crosstargeting projects

build/NuGetPackages/Microsoft.Build.Framework.nuspec, build/NuGetPackages/Microsoft.Build.Runtime.nuspec, build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec, build/NuGetPackages/Microsoft.Build.nuspec, dir.props
This enables users to publish their msbuild depending app for net46 and get the closure of dependencies needed for msbuild.
I just copied over the net46 only dependencies from the project.json files over to the nuspec files.
This change should affect neither VS (which depends on msbuild via the vsix) nor CLI (who only publishes msbuild packages for .net core, not full framework).
Resolves #1681
=> Add net46 dependencies to msbuild nuspecs

src/Build/Microsoft.Build.csproj
To make our microbuild definition pass again for xplat.
=> Mark System.Threading.Task.Dataflow as Private=true

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets
Fixes the RID P2P component of dotnet/sdk#696 
This is part of a two-part PR. The second part is dotnet/sdk#828. 
These PRs, together, enable the following class of projects:
* A RID-specific root project [App.csproj]
* A portable dependency project [Library.csproj]
With this fix in place, one can:
* `dotnet restore App.csproj`
* `dotnet build -r osx.10.11-x64 App.csproj`
Without the fix, Library.csproj will not build because the `osx.10.11-x64` runtime identifier will be passed through as a global property, forcing it to build for a target that does not exist in the NuGet assets file.
The MSBuild portion of the fix adds `RuntimeIdentifier` to the list of `RemoveProperties` passed to the P2P in `_GetProjectReferenceTargetFrameworkProperties`. It also passes along the value of …
=> Enable P2P's to determine their own compilation RID

src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config
This addresses the repro case for #1675, but not its root cause. By
providing a `codeBase` for the CA assemblies, we ensure that any running
MSBuild can find them when deserializing a log message.
=> Work around #1675 for C++ Code Analysis scenarios

src/Shared/HybridDictionary.cs, src/Shared/UnitTests/HybridDictionary_Tests.cs
Indexer (defined in IDictionary) implemented in a way that recursively
calls itself. Nothing called this code, but if it did it would be wrong
(stack overflow).
Closes #77
=> Fix invalid indexer in HybridDictionary

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build/Instance/ProjectInstance.cs
The debugger display was referring to fields that have since been renamed. Changed it to call through properties to avoid needed to handle null'd out fields.
=> Fix ProjectInstance's debugger display

build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks.UnitTests/XmlPeek_Tests.cs, src/Tasks.UnitTests/XmlPoke_Tests.cs, src/Tasks.UnitTests/project.json, src/Tasks/Microsoft.Build.Tasks.csproj, src/Tasks/XmlPeek.cs, src/Tasks/XmlPoke.cs, src/Tasks/project.json
Had to add some additional dependencies and fix up some tests to use `netstandard` APIs.
Closes #1731
=> Enable XmlPeek and XmlPoke tasks for .NET Core. 

src/Tasks/Microsoft.CSharp.CurrentVersion.targets, src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
Fixes dotnet/sdk#522 and dotnet/cli#5131
The .NET CLI has a command to add projects to a solution.  It needs to know what project type Guid to use in the solution for projects where it's not explicitly defined in the project file.  This change adds a `DefaultProjectTypeGuid` property for C# and VB that it can use for this.
@jeffkl @rainersigwald @AndyGerlicher @jgoshi @davkean for review.
@KevinRansom @enricosada the F# targets should also add this property, I believe the F# value is `{F2A71F9B-5D33-465A-A702-920D77279786}`
=> Add DefaultProjectTypeGuid property for C# and Visual Basic

src/Tasks/Exec.cs
Comment correction. Comment states that _ignoreStandardErrorWarningFormat defaults to true, but it defaults to false. Brought up in discussion https://github.com/Microsoft/msbuild/issues/766.
=> _ignoreStandardErrorWarningFormat defaults to false

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/netstandard1.3/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, src/Shared/FrameworkLocationHelper.cs, src/Utilities/ToolLocationHelper.cs, src/Utilities/UnitTests/ToolLocationHelper_Tests.cs, src/XMakeTasks/Al.cs, src/XMakeTasks/AspNetCompiler.cs, src/XMakeTasks/GetFrameworkPath.cs, src/XMakeTasks/GetFrameworkSDKPath.cs, src/XMakeTasks/ResolveComReference.cs, src/XMakeTasks/SGen.cs, src/XMakeTasks/SdkToolsPathUtility.cs, src/XMakeTasks/UnitTests/SdkToolsPathUtility_Tests.cs
Will likely close PR #1696 in favor of this one. Wanted to get the idea out there for review.
* Add support for .net SDK 4.7. It will release with Dev15.1.
* Update VersionLatest to remain at 4.6.2 (latest at RTM).
* Add VersionLatestOnMachine to identify latest MSBuild knows about.
* Fix issue with fallback (StackOverflow on unit tests).
@davkean Given what we have to work with, how does this sound? VersionLatest would be fixed per major update (4.6.2 for Dev15). VersionLatestOnMachine would mean use the latest whatever version it is (that MSBuild knows about, still has to be updated per sdk release). (I realize this isn't implemented, I just wanted to get the idea out for review in case anyone can think of something obvious we're missing.)
=> Add support for .net SDK 4.7 - VersionLatestOnMachine

version.json
Bumps the build version to 1000 (as of 6 commits ago when the branch diverged). We will now be at `15.1.1006`.
=> Bump build version offset for vs15.1

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.UnitTests/BinaryLogger_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs, src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsDispatcher.cs, src/Build/Logging/BinaryLogger/BuildEventArgsFieldFlags.cs, src/Build/Logging/BinaryLogger/BuildEventArgsFields.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Build/Microsoft.Build.csproj, src/Build/Resources/Strings.resx, src/MSBuild/CommandLineSwitches.cs, src/MSBuild/MSBuild.csproj, src/MSBuild/Resources/Strings.resx, src/MSBuild/XMake.cs, src/Shared/UnitTests/ObjectModelHelpers.cs
/binaryLogger[:output.binlog]
Serializes all build events to a compressed binary file. By default the file is in the current directory and named "msbuild.binlog". The binary log is a detailed description of the build process that can later be used to reconstruct text logs and used by other analysis tools. A binary log is usually 10-20x smaller than the most detailed text diagnostic-level log, but it contains more information. (Short form: /bl or /binlog)
Examples:
/bl
bl:output.binlog
binlog:..\..\custom.binlog
binaryLogger
For now this commit only includes the logger (writer), but the reader is disconnected. In subsequent PRs we will add an option to playback the binary log into any other set of existing loggers.
Support for the new format will be added to MSBuild Structured Log Viewer …
=> Introduce a new BinaryLogger logger.

src/Build.UnitTests/project.json, src/Build/project.json, targets/runtimeDependencies/project.json
devenv.exe has a binding redirect for Dataflow of `oldVersion="4.0.0.0-4.5.65535.65535" newVersion="4.5.24.0"`. We need to have the same dependency, otherwise msbuild crashes when loaded in-proc inside devenv.exe
=> Synchronize Dataflow dependency to what VS uses

src/Tasks/Microsoft.Common.CurrentVersion.targets
This prevents conflicts while building large solutions with projects
that share intermediate output directories.
I was receiving the error "**Could not write lines to file 'CoreCompileInputs.cache' because it is in use...**"  using the **VS 2017 RC** while building a 120+ project solution that shares intermediate output directories. This change brings the CoreCompileInputs.cache in line with other intermediate output files.
Fixes Issue #1645
=> Adding MSBuildProjectFile to CoreCompileInputs.cache filename

src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/MSBuild/Resources/Strings.resx
Two minor fixes from code review feedback (Rainer).
The way the tests are written is objects are manually created, then serialized and deserialized back. The length of the bytes written needs to be the same as the number of bytes read back.
For each object type, a set of fields are compared on the original object and deserialized copy and we make sure the values are the same.
=> Add a set of unit-tests for serializing and deserializing BuildEventArgs.

src/Utilities/ToolLocationHelper.cs
Correct paths for reference assemblies for systemManagementContract, part of the IOT extension SDK, are not resolved with insider preview SDK, 15003 and 15021. The files are in here: 
C:\Program Files (x86)\Windows Kits\10\References\<VERSION>\Windows.System.SystemManagementContract\3.0.0.0\Windows.System.SystemManagementContract.winmd. 
The reason is when we call GetApiContractReferences we didn't check the Versioned property of the sdk. So it returned the path without <VERSION>
=> Add versioned check for GetApiContractReferences

src/Tasks/Microsoft.Common.CrossTargeting.targets
Instead of batching over `%(_TargetFramework.Identity)` (and thus
serializing calls to the MSBuild task), issue build requests for all
target frameworks in parallel. Since the escape-hatch parameter
`BuildInParallel` isn't defined in the outer build, I defined it here to
preserve the existing behavior of being able to serialize the build even
with /m by passing /p:BuildInParallel=false.
Fixes #1064
=> Execute inner builds in parallel

src/MSBuild/XMake.cs
I've discovered that task inputs are not logged when using binary logger. This is because the logic here only logs task inputs if verbosity is Diagnostic or the env. variable MSBUILDLOGTASKINPUTS is set to 1.
http://source.dot.net/#MSBuild/XMake.cs,948
http://source.dot.net/#Microsoft.Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs,168
It is safe to set the "global" verbosity to diagnostic where I'm setting it, because from eyeballing the data flow from that point the only place it's consumed at is the check for log task inputs.
=> Log task inputs when using binary logger.

src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs, src/Build/Resources/Strings.resx, src/MSBuild/XMake.cs, src/Shared/Resources/Strings.shared.resx
To see more details from a unit-test exception let's not catch the exception inside the Replay() method but instead catch it at the caller site.
To still give a meaningful user message we need to share the resource for "InvalidLogFileFormat".
=> Move an exception one level up.

src/Build/Logging/ConsoleLogger.cs, src/Build/Logging/FileLogger.cs
Because FileLogger used the default value of the SetColor and ResetColor
delegates, it was quietly changing and resetting console color for every
log message that was considered by the FileLogger. On Windows, this was
unnecessary but not too noticeable. On Unix systems, though, console
colors are set by emitting an escape code to the output stream, so this
became observable.
Explicitly passing the Dont* mechanisms to prevent the unnecessary work
from happening. I removed the null check for the `write` delegate from
ConsoleLogger's constructor because it seemed cleaner to set the
delegate to `null` from FileLogger than to explicitly specify the
default `Console.Out.Write`.
Fixes #1792.
=> Don't set console color from FileLogger

src/MSBuild/XMake.cs, src/Shared/CommunicationsUtilities.cs, src/Tasks/AssemblyDependency/GenerateBindingRedirects.cs
[V3041](https://www.viva64.com/en/w/V3041/) The expression was implicitly cast from 'long' type to 'float' type. Consider utilizing an explicit type cast to avoid the loss of a fractional part. An example: double A = (double)(X) / Y;. Microsoft.Build CommunicationsUtilities.cs 615
[V3118](https://www.viva64.com/en/w/V3118/) Milliseconds component of TimeSpan is used, which does not represent full time interval. Possibly 'TotalMilliseconds' value was intended instead. MSBuild XMake.cs 629
[V3095](https://www.viva64.com/en/w/V3095/) The 'name' object was used before it was verified against null. Check lines: 229, 235. Microsoft.Build.Tasks GenerateBindingRedirects.cs 229
[V3095](https://www.viva64.com/en/w/V3095/) The 'publicKeyToken' object was used before it was verified against null. …
=> PVS-Studio: fixed vulnerabilities

setup/Microsoft.Build.vsmanproj
Resolves a build failure in the vsmanproj project. The P2P swixproj project does not
import common targets and does not have GetTargetFrameworkProperties target.
=> Fix P2P build failure in MicroBuild

dir.targets
VS150COMNTOOLS is not defined in our MicroBuild environment.
=> Update EditBin target to use VsInstallRoot property

src/Build/Logging/BaseConsoleLogger.cs
When replaying a binary log with multiproc I've discovered a crash in the DescendingByElapsedTimeComparer. In the case when both p1 and p2 were reentrant we were returning -1 always even if they were different objects.
This resulted in a crash:
```
There was an exception while reading the log file: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'Microsoft.Build.BackEnd.Logging.BaseConsoleLogger+PerformanceCounter+DescendingByElapsedTime'.
```
In the case when both performance counters are reentrant let's sort them by name such that it's stable.
The bug was always reproducible and after the fix I've never seen it again. …
=> Fix DescendingByElapsedTimeComparer

dir.targets
Arg. I didn't clear bin folder when I tested this without `VSINSTALLDIR` set.
=> Fix typo in EditBin target.

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Resources/Strings.resx
Log a low priority message during evaluation when a property that was previously assigned is being assigned a new and different value. This is useful to determine when your property might be stomped over later.
Also adding Evaluation started and Evaluation finished messages for each project evaluation to logically isolate messages coming from the evaluation phase.
Sample log output:
```
Evaluation started ("C:\CodeCleanupTools\SortProjectItems\SortProjectItems.csproj")
Property reassignment: $(ProcessorArchitecture)="msil" (previous value: "AnyCPU") at C:\MSBuild\bin\Bootstrap\15.0\Bin\Microsoft.Common.CurrentVersion.targets (457,5)
Evaluation finished ("C:\CodeCleanupTools\SortProjectItems\SortProjectItems.csproj")
```
=> Log when a property is being assigned a new value.

src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs, src/XMakeBuildEngine/UnitTests/Evaluation/Evaluator_Tests.cs
Fix for #1751, which regressed with lazy item evaluation.
=> Item references should be case-insensitive

dir.props, ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, src/Build/Instance/TaskRegistry.cs, src/Build/Resources/Strings.resx, src/Shared/TaskEngineAssemblyResolver.cs, src/Tasks.UnitTests/CodeTaskFactoryTests.cs, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks/CodeTaskFactory.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Tasks/Resources/Strings.resx, src/Tasks/XamlTaskFactory/XamlTaskFactory.cs
1. Allow task factories to load on .NET Core
2. Update TaskEngineAssemblyResolver for .NET Core
3. Log an error for CodeTaskFactory and XamlTaskFactory when running on .NET Core
4. Update unit tests
Related to #304
=> Enable task factories for .NET Core

src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs
Turns out this unit-test didn't reset the TargetLoggingContext.EnableTargetOutputLogging like the other tests around it.
=> Fix a unit-test that fails when MSBUILDTARGETOUTPUTLOGGING is set.

src/Shared/CanonicalError.cs, src/Utilities.UnitTests/CanonicalError_Tests.cs
If a Clang/GCC-style error didn't have any text, an
IndexOutOfRangeException exception was thrown. This guards against that.
Unit tests for a normal Clang/GCC error and a degenerate one have been
added.
Fixes https://github.com/Microsoft/msbuild/issues/1796
=> Fix crash parsing Clang/GCC messages with no text

src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
My hypothesis is that when serializing properties of a ProjectStartedEventArgs we were iterating over the properties twice, first to establish count and the second time to actually write the items.
By inspecting the binary stream I've found that the log expected to find 166 property name/value pairs, but in the stream there's actually a 167th:
"SBuildLastTaskResult\u0004true\u0001\bTestItem\u0004Test\0\v5#Building with tools version \"15.0"
So I'm guessing is that the MSBuildLastTaskResult property is being set to true right after we grab the property count, but before we iterate over the properties. At least that would explain the extra property in the stream that we don't expect.
In any case the change seems good and I'd like to get this in (I'm 60% positive this will fix it).
=> Attempt to fix a race condition in TestBinaryLogRoundtrip.

src/Tasks/Microsoft.CSharp.CurrentVersion.targets, src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
The legacy project system works without it (since it's not CPS based) and there are changes in the pipeline to use a different capability to defined configurations differently. On the new project system the capability is defined by the project system (as a default). Additionally the capability was also defined in the design time targets so there is some redundancy. Having the old capabilities here conflicts with that and requires a workaround to add a remove statement elsewhere in the targets.
=> Remove ProjectConfigurationsInferredFromUsage capability from managed targets

src/Shared/UnitTests/MockEngine.cs, src/Tasks.UnitTests/GetSDKReference_Tests.cs
https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_Windows_NT_Desktop_prtest/640/ had a mysterious failure in `LogReferenceAndRedistConflictBetweenSdks` which isn't known to be flaky. But the log just indicated that a task failed, which isn't helpful.
I added the ability to keep log information in xunit's style in MockEngine, switched its internal log capture to use StringBuilder instead of super allocatey concatenation all over the place, and opted the class that failed into the new logging.
=> Capture test output to Xunit MockEngine

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build.UnitTests/Evaluation/ItemSpec_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Definition/Project.cs, src/Build/Evaluation/ItemSpec.cs, src/Build/Globbing/CompositeGlob.cs, src/Build/Microsoft.Build.csproj, src/Shared/EscapingStringExtensions/EscapingStringExtensions.cs, src/Utilities/Microsoft.Build.Utilities.csproj
Resolves #1795 
This is based on another PR: https://github.com/Microsoft/msbuild/pull/1859
=> A better GetAllGlobs

documentation/ProjectReference-Protocol.md
Wrote a document explaining what ProjectReferences do behind the scenes
and how to make a green-field project that doesn't import the machinery
of Common.targets compatibile with using them.
=> Document the ProjectReference protocol

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.OM.UnitTests/Construction/ProjectFormatting_Tests.cs, src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/Build/Construction/ProjectRootElement.cs, src/Build/Microsoft.Build.csproj, src/Build/Xml/XmlReaderExtension.cs, src/Shared/EncodingUtilities.cs, src/Shared/ProjectWriter.cs
The XmlReader does not currently consider the BOM when detecting the
Encoding. This change checks the Stream for the UTF8 BOM and if not
present use UTF8 w/o BOM Encoding.
Fixes #1768
=> Check for BOM in file when detecting Encoding.

src/dir.targets, targets/DeployDependencies.proj
Don't version test assemblies.  When building with MSBuild 15.0. MSBuildRuntimeType wasn't set so our assemblies weren't being versioned.  With the move to MSBuild 15.0, we get errors when trying to debug the tests in Visual Studio.
Copy XUnit dependencies to VS output path when building in VS.
=> Improve running of tests in VS

src/Build.OM.UnitTests/Construction/ProjectFormatting_Tests.cs, src/Build/Xml/XmlReaderExtension.cs
Thanks @davkean 
Passing in UTF8 w/o BOM Encoding object to StreamReader will allow the
StreamReader class to correctly detect encoding when a BOM exists in
the file. Using the default (UTF8 with BOM) will cause issues when the
file is UTF8 encoded without a BOM (added on save).
The overall issue was fixed in 8e3adba by reading the Stream. This
change allows for that behavior without needing to check the preamble
again.
#1898, #1768
Note: I'm not reverting my other change since part of it still necessary and the unit tests still need to read the preamble to verify the fix and we still need other aspects of that change to ensure that UTF8 and UTF8 w/o BOM are treated the same in some cases.
=> Allow StreamReader to detect file Encoding w/o BOM.

src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs, src/Build/Evaluation/Preprocessor.cs
When updating the pre-processor for the implicit imports, I changed the internal map from an XmlElement to a string.  However, the outer XML of imports can be duplicated because it can contain a property or a relative path.  This map could contain duplicates and the pre-processor would process the same import over and over until a stack overflow occurred.
This fix restores the mapping of XmlElements and adds the implicit imports to the mapping after their nodes are created.
I also added a unit test for this case.
Fixes #1893
=> Fix stackoverflow in preprocessor

src/MSBuild/Microsoft.Build.CommonTypes.xsd
Resolves https://developercommunity.visualstudio.com/content/problem/27616/missing-intellisense-in-net-core-csproj-file.html
=> Adding an xsd entry for 'Content->CopyToPublishDirectory'

src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs
Fix for regression in performance caused by #1766.
Internal Visual Studio perf tests discovered a small regression in 15.1 that appears to be due to using `MSBuildNameIgnoreCaseComparer.Default` for string comparison in the lazy evaluator. The change was originally made because of a behavior regression that caused item references to be case-sensitive. Using `StringComparer.OrdinalIgnoreCase` seems to resolve the performance issue and maintains the correct behavior from previous versions of MSBuild.
=> Perf Regression: Stop using MSBuildNameIgnoreCaseComparer

src/Deprecated/Engine/Engine/Utilities.cs, src/Tasks/AxReference.cs, src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs, src/Tasks/CommandLineBuilderExtension.cs, src/Utilities/ToolLocationHelper.cs
[V3095](https://www.viva64.com/en/w/V3095/) The 'condition' object was used before it was verified against null. Check lines: 240, 244. Microsoft.Build.Engine Utilities.cs 240
[V3095](https://www.viva64.com/en/w/V3095/) The 'ReferenceInfo' object was used before it was verified against null. Check lines: 80, 90. Microsoft.Build.Tasks AxReference.cs 80
[V3095](https://www.viva64.com/en/w/V3095/) The 'packageFileName' object was used before it was verified against null. Check lines: 1439, 1448. Microsoft.Build.Tasks BootstrapperBuilder.cs 1439
[V3095](https://www.viva64.com/en/w/V3095/) The 'metadataNames' object was used before it was verified against null. Check lines: 243, 253. Microsoft.Build.Tasks CommandLineBuilderExtension.cs 243
[V3095](https://www.viva64.com/en/w/V3095/) The …
=> PVS-Studio: fixed potential vulnerabilities

src/Tasks/Microsoft.CSharp.CurrentVersion.targets, src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
The dotnet project system has it's own copy of these rules and these are being imported twice. This was benign before but we refactored one of the rules recently and this is now causing latest builds of wpt to be broken.
Introducing a property here that will be set by the project system to disable importing these rules.
@AndyGerlicher @cdmihai @rainersigwald
=> Add a capability to turn off importing CSharp\VisualBasic item schema files

src/Build.UnitTests/BackEnd/EventSourceSink_Tests.cs, src/Build.UnitTests/BackEnd/MockLoggingService.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs, src/Build/BackEnd/Components/Logging/BuildEventArgTransportSink.cs, src/Build/BackEnd/Components/Logging/EventSourceSink.cs, src/Build/BackEnd/Components/Logging/ILoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs, src/MSBuild/Microsoft.Build.CommonTypes.xsd, src/Shared/Constants.cs
Introduce `MSBuildTreatWarningsAsErrors` property that when set to true will treat all warnings as errors when building a project.
Introduce `MSBuildWarningsAsErrors` property which is a semicolon delmited list of warning codes to treat as errors when building a project.
Introduce `MSBuildWarningsAsMessages` property which is a semicolon delimited list of warning codes to treat as low importance messages.
This allows users to control warnings at the project level via standard MSBuild properties.  They can be set in a project, an import, or from the command-line.
The limitation here is that the warnings can only include ones that occur during a build.  This is because the properties are not read until after parsing so warnings generated during parse/evaluation happen too soon.  For these …
=> Implement ability for project properties to suppress and elevate warnings

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs, src/Build/Evaluation/LazyItemEvaluator.cs
Fixes #1932.
This partially reverts 816d37362bc34a6dd754607cad8c601ae8f13000,
specifically the part (quoted from the commit message):
` Side effect change: if metadata properties are evalauted early,
there's no use for operation application to expand them yet again, so
cache the property expansion during operation construction and use the
cached values during operation application. This should also be a perf
improvement when metadata references are present within metadata, as
that triggers the re-evaluation of all metadata elements for each item
instance.`
We can't use the metadata expanded at operation construction time as we
didn't expand referenced item metadata at that time. This breaks a case
where the item metadata has a value like: …
=> Fix metadata reference in a property function, in an item metadata

cibuild.sh
Classes of change:
* Quoting variable expansions to handle spaces better
* Switching from backticks to `$(..)` expansions
* Avoiding `egrep` in favor of `grep -E`
* Removed unused `BOOTSTRAPPED_RUNTIME_HOST`
=> 🚨 Fix shellcheck warnings in cibuild.sh

src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileUtilities_Tests.cs
The FileUtilities.LooksLikeLinuxPath() only returns true if the first path
segment is a directory. This can't be true for files in the root directory
on *nix systems. This commit adds an additional check to determine if the
parameter is a file.
=> Fix for MSBuild command parser confused by Fully Qualified Path to proj files in Linux root #1894

src/XMakeCommandLine/app.amd64.config
This change is part of an internal change to the XAML build tasks to
enable support for x64 builds. This was broken in Visual Studio 2017
because MSBuild assemblies are no longer in the GAC and any app domain
created by a task may not be able to find MSBuild assemblies correctly.
Closes #1943
=> Update amd64 app.config to find XAML build tasks.

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build.UnitTests/Evaluation/ItemSpec_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Definition/Project.cs, src/Build/Evaluation/ItemSpec.cs, src/Build/Globbing/CompositeGlob.cs, src/Build/Microsoft.Build.csproj, src/Shared/EscapingStringExtensions/EscapingStringExtensions.cs, src/Utilities/Microsoft.Build.Utilities.csproj
This reverts commit b98bc3ad486f5dac5eebf19e2d973fef4ab5e22e and brings back the new GetAllGlobs
Initial Revert PR: https://github.com/Microsoft/msbuild/pull/1946
Initial PR with the new GetAllGlobs.
I also made the GlobResult constructor public so API users can create mocks.
=> Revert "Revert "A better GetAllGlobs (#1871)" (#1946)"

src/XMakeCommandLine/app.amd64.config, src/XMakeCommandLine/app.config, src/XMakeTasks/Microsoft.Xaml.targets
The root cause of the issue is because MSBuild cannot find the XamlBuildTask.dll for X-platform build (I.e.: using x86 MSBuild to build x64 assembly). The fix requires 3 changes as below.
WF Team: First change is to drop XamlBuildTask.dll and Microsoft.Activitity.Build.dll to …\MSBuild\15.0\Bin\amd64 rather than MSBuild\15.0\Bin. Second change is to update the app base for 2nd app domain so that they can find XmlBuildTask.dll.
MSBuild Team: Another change is in Github to update the XmalBuildTaskPath to $(MSBuildToolsPath64) in "Microsoft.Xaml.Targets".
=> Build failure on 64-bit MSBuild as could not load assembly " XamlBuildTask.dll”

src/Shared/AssemblyNameExtension.cs, src/Shared/AssemblyUtilities.cs, src/Tasks/AppConfig/DependentAssembly.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs
AssemblyName.Clone is not available in early versions of .NET Core.
Until we can upgrade MSBuild to use .NET Core 2.0, we can't call the
Clone method directly. This change will attempt to call .Clone using
reflection and if not available fallback to the previous .NET Core
behavior.
Potential fix for #2015 (when running on .NET Core 2.0).
=> Use AssemblyName.Clone when possible.

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.OM.UnitTests/Construction/ConstructionEditing_Tests.cs, src/Build.OM.UnitTests/Construction/ProjectSdkImplicitImport_Tests.cs, src/Build/Construction/ProjectImportElement.cs, src/Build/Evaluation/ProjectParser.cs, src/Build/Xml/ProjectXmlUtilities.cs, src/MSBuild/Microsoft.Build.Core.xsd
* This feature was regressed in #2002
* Update unit tests to verify functionality
* Update ProjectParser to parse SDK name/version values and construct an SdkReference object to be used by the evaluator.
Closes #2034
=> Fix issue importing an SDK via Import element.

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs, src/Build.UnitTests/ExpressionTreeExpression_Tests.cs, src/Build/Evaluation/Conditionals/FunctionCallExpressionNode.cs, src/Build/Evaluation/Evaluator.cs
Allows `<Import Project="import1.props;import2.props" />` to work.  This also updates `Exists` so that this will work:
```xml
<Import Project="import1.props;import2.props"
Condition="Exists('import1.props;import2.props')" />
```
It also works with properties:
```xml
<Project>
<Imports>import1.props</Imports>
<Imports>$(Imports);import2.props</Imports>
<Import Project="$(Imports)" Condition=" '$(Imports)' != '' And Exists($(Imports))" />
</Project>
```
**It does not work with items** because items are not available when evaluating `<Import />` elements.
Closes #890
=> Implement importing a list of files

src/Build/Globbing/CompositeGlob.cs
Threadpools are a scarce resource in VS, do not use them.
We should instead consider other optimisations: #2044
=> Do not use PLINQ in CompositeGlob

src/MSBuild/Resources/Strings.resx, src/MSBuild/XMake.cs
Fixes #1662. Framework names are not localized (see for example
https://docs.microsoft.com/ko-kr/dotnet/), so I'm just defining the
string in code and passing it to the (localized) resource.
=> Name framework type in logo

netci.groovy
Reverts Microsoft/msbuild#2068
Appears to cause test failures on `Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetUnversionedSDKUnionMetadataLocation`.
=> Revert "Use Dev15.1 in CI"

build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec, build/NuGetPackages/Microsoft.Build.nuspec, dir.props, setup/files.swr, src/Build.OM.UnitTests/project.json, src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build.UnitTests/project.json, src/Build/Evaluation/IntrinsicFunctions.cs, src/Build/Microsoft.Build.csproj, src/Build/Resources/Constants.cs, src/Build/Resources/Strings.resx, src/Build/project.json, src/Framework.UnitTests/project.json, src/MSBuild.UnitTests/project.json, src/MSBuild/project.json, src/Shared/UnitTests/App.config, src/Shared/UnitTests/ObjectModelHelpers.cs, src/Tasks.UnitTests/project.json, src/Tasks/project.json, src/Utilities.UnitTests/project.json, src/Utilities/project.json, targets/DeployDependencies.proj, targets/runtimeDependencies/project.json
VS needs 4.0.1.0. If we use anything else, we won't get VS' ngened copy which then makes all of msbuild not be ngened.
This PR also brings back #1926 which got reverted in #1951
=> Differentiate version for RuntimeInformation and bring it back for property functions

src/Tasks.UnitTests/Touch_Tests.cs
Although the tests passed as @rainersigwald pointed out in #2085 it makes more sense to keep the space out. It was just an unintentional replacement in the first place that also now makes the ternary look odd.
=> Test: Non existing -> nonexistent

src/MSBuild/app.amd64.config, src/MSBuild/app.config
Fixes #2047 by always using the 32-bit registry to locate `$(SDK35ToolsPath)` and `$(SDK40ToolsPath)`.
=> Use 32-bit registry for .NET SDK locations

src/Build.OM.UnitTests/Definition/Project_Tests.cs
@eerhardt pointed out in https://github.com/Microsoft/msbuild/pull/2091#discussion_r116822777 that "indented" was probably "intended" :stuck_out_tongue_winking_eye:
=> Typo: Intended -> Indented

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, src/Build.OM.UnitTests/Construction/ProjectSdkImplicitImport_Tests.cs, src/Build.UnitTests/BackEnd/SdkResolution_Tests.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolution.cs, src/Build/Evaluation/Evaluator.cs, src/Framework/Sdk/SdkResolverContext.cs, src/Shared/UnitTests/TestEnvironment.cs
* Adds MSBuild version.
* Fix ProjectFilePath to be the full path to the project (equivalent to
'$(MSBuildProjectFullPath)').
* Fix issue where SolutionFilePath can be set by Common targets to
'*Undefined*'. When this is the case, set to null for consistency.
Closes #2097, #2083, #2082 
Looking into adding some tests, will have a followup commit.
=> Add Version and fix ProjectPath in SdkResolverContext

src/Tasks/Microsoft.Common.CurrentVersion.targets
This fixes SatelliteDllsProjectOutputGroup when SatelliteDllsProjectOutputGroupOutputIntermediate items already exist so that it doesn't double up and malform SatelliteDllsProjectOutputGroupOutputIntermediate items.
When localization for an app occurs another way (like Microsoft's own LCL tooling) the FinalOutputPath isn't what is calculated here. We can preset it in the Intermediate items, but we need MSBuild to preserve that metadata when it is there.
=> Fix custom localization and packing of satellite assemblies

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs, src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs, src/Build.UnitTests/BackEnd/RequestBuilder_Tests.cs, src/Build.UnitTests/OpportunisticIntern_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Build/BackEnd/Shared/BuildRequestConfiguration.cs, src/Build/BackEnd/Shared/ConfigurationMetadata.cs, src/Build/Evaluation/ProjectStringCache.cs, src/Shared/Constants.cs, src/Shared/OpportunisticIntern.cs
In addition, put a protective check in the two known msbuild string caches to preemptively avoid caching unique strings.
False positive caching is still hit in the following scenarios
- building successive in-memory mutations of the same `ProjectInstance` instance, in the same BeginBuild-EndBuild-ResetCaches session
- building different `ProjectInstance` instances over the same file, in the same BeginBuild-EndBuild-ResetCaches session
To fix these I think we have to actually remove the dummy variable and change `ConfigurationMetadata` (implements what it means to be a unique build in the engine) to account for the entire `ProjectInstance` state.
=> Do not leak dummy variable in user owned ProjectInstance object

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/MSBuild/MSBuild.csproj, src/MSBuildTaskHost/MSBuildTaskHost.csproj, src/Shared/NativeMethodsShared.cs, src/Shared/Traits.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Utilities/Microsoft.Build.Utilities.csproj
Fixes #2052 by calling the more performant `GetFileAttributesEx()`
first, and falling back to the slower `CreateFile()` + `GetFileTime()`
_only_ if `GetFileAttributesEx` reports that what it opened was a
"reparse point" (symlink).
=> Avoid CreateFile in hot GetLastWriteFileUtcTime

src/Build.UnitTests/ConsoleLogger_Tests.cs, src/Build.UnitTests/FileLogger_Tests.cs, src/Build/Logging/BaseConsoleLogger.cs, src/Build/Logging/ConsoleLogger.cs, src/Build/Logging/FileLogger.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs, src/Build/Logging/SerialConsoleLogger.cs
A change was (#1513) to allow for more control over log summary text.
Specifically, the ask was to allow for the use of ErrorsOnly /
WarningsOnly with Summary. That change also impacted the file log output
and in some cases caused build summary to output to the log file when
using ErrorsOnly.
This change defaults to not showing the summary text in the FileLogger
when ErrorsOnly or WarningsOnly is set (it can still be displayed with
the Summary flag). This reverts behavior back to pre-VS2017 behavior and
allows for an empty err/wrn file to be produced.
Closes #1968
=> Fix regression with log file summary.

src/Utilities.UnitTests/MockEngine.cs
The old way was confusing to diagnose because it didn't emit the log,
and also (horror of horrors) did a bunch of string concatenation.
Separating this from #2114 since it's not directly related, and got a bit bigger than I'm willing to sneak in there.
=> 🔨 Better logging for AssertLogContains in Utilities

src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.Common.tasks
Provides an item, `ReferencePathWithInterfaceOnlyAssemblies`, that
consists of the reference (interface-only) versions of assemblies where
available, allowing a consuming task to be incrementally up-to-date
after implementation-only changes have been made to a reference.
When `%(ReferenceAssembly)` metadata is unavailable for a given
reference, the new item contains the implementation assembly directly.
Additionally creates a new output item for the current project's
reference assembly by default when `$(Deterministic)` is `true`. If this
is created, it is copied to the output directory using the new
`CopyRefAssembly` task, which copies only if the ref assembly is
different from the current file. If present, the ref asm is passed to
the project's consumes in metadata.
See #1986, …
=> Common.targets support for reference assemblies

src/MSBuild/Microsoft.Build.CommonTypes.xsd
Fixes #2125 by removing the section of the XSD that was commented as
"only to avoid schema validation warnings". That's obsolete because VS
no longer checks schema for MSBuild. And we don't need to expose these
names in autocomplete.
=> Remove "private" item names from XSD/IntelliSense

src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs, src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Build/BackEnd/Shared/WorkUnitResult.cs
First attempt, looking for feedback. It works and fixes the error, but it scares me a bit!
This issue occurs when two targets are scheduled to be built (e.g.
ProduceError1 and ProduceError2) and the condition of the first target
causes it to not execute and a dependent target
(BeforeTargets='ProduceError1') fails. In this example, ProduceError2
still executes.
Fixes #2116
=> Fix issue where targets are executed after an error.

build/NuGetPackages/Microsoft.Build.Framework.nuspec
The Nuspec reference generator wants it that way, and the CI is failing
if there are any diffs
=> Reorder nuspec dependencies

src/Tasks/Microsoft.Common.CurrentVersion.targets
e3a3d69 added a new FindReferenceAssembliesForReferences target, which
ran just before ResolveReferences. Dogfooding this revealed targets in
the VS SDK (at least) that manipulate @(ReferencePath) and are hooked in
as AfterTargets of ResolveReferences. That was silently ignored,
corrupting the user's build.
Fixes #2134 by moving FindReferenceAssembliesForReferences later in the
process, so anyone hooking ResolveReferences will see the changes they
make in the compiler.
This is not a fully general solution to the problem that someone might
hook an arbitrary point and manipulate @(ReferencePath), but it unbreaks
an obvious hook point.
=> Find ref asms after ResolveReferences

src/Build/Logging/BinaryLogger/BinaryLogger.cs
Due to new BuildEventContext.EvaluationID
It is okay to break people because the binary logger has not RTMed yet. After 15.3, each version bump needs to introduce some dispatching code so that the current version is backwards compatible. Worst case design is forking the reader / writer for each version number.
=> Bump up Binarry Logger file format version

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/IntrinsicFunctions.cs, src/Build/Resources/Strings.resx, src/Shared/UnitTests/ObjectModelHelpers.cs
We lose the ability to give a nicer error message when a platform
doesn't exist and case insensitivity, but ultimately not having a
diverged method of checking for what OS we're on is preferable.
Closes #2127
=> Use base IsOSPlatform implementation.

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, src/Build.UnitTests/BackEnd/BuildManager_Tests.cs, src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Framework/Microsoft.Build.Framework.csproj, src/Framework/ProjectEvaluationFinishedEventArgs.cs, src/Framework/ProjectEvaluationStartedEventArgs.cs
Also updated binary log serialization to support it.  Loggers will receive the message through the `IEventSource.StatusEventRaised` event.  The messages will no longer show up in the text log.
An upcoming change will look at these events so that project evaluation can be displayed in the performance summary.
=> Add ProjectEvaluationStartedEventArgs and ProjectEvaluationFinishedEventArgs

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build.UnitTests/Evaluation/EvaluationLogging_Tests.cs, src/Build.UnitTests/Instance/ProjectInstance_Internal_Tests.cs, src/Build/BackEnd/Components/Logging/EvaluationLoggingContext.cs, src/Build/Definition/Project.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/IEvaluatorData.cs, src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs, src/Build/Instance/ProjectInstance.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Framework.UnitTests/EventArgs_Tests.cs, src/Framework/BuildEventContext.cs
Rename EvaluationID to EvaluationId to maintain consistency
=> Rename EvaluationID to EvaluationId to maintain consistency

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, src/Build/Evaluation/Evaluator.cs, src/Framework/ProjectImportedEventArgs.cs
This ensures that as few strings are allocated as possible
=> Use LazyFormattedBuildEventArgs in ProjectImportedEventArgs

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs, src/Build/Evaluation/Evaluator.cs, src/Framework/ProjectEvaluationFinishedEventArgs.cs, src/Framework/ProjectEvaluationStartedEventArgs.cs
Should clean up a few more string allocations.
=> Use LazyFormattedBuildEventArgs for messages of project evaluation started/finished

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build/Definition/Project.cs
As its a breaking change because most official builds treat warnings as errors.
=> Do not mark EvaluationCounter as obsolete

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs, src/Build/Microsoft.Build.csproj, src/Build/Resources/Strings.resx, src/MSBuild/Resources/Strings.resx, src/MSBuild/XMake.cs
To improve the diagnosability of build logs a new option is added to collect project files and all imported projects used during the build.
There are three options: don't capture sources, capture to a standalone .ProjectImports.zip archive and embed the zip archive directly into the binary log. The last option (embed) is the default.
=> Embed projects and imports in binary log

src/Build/Logging/BaseConsoleLogger.cs, src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs, src/Build/Logging/SerialConsoleLogger.cs, src/Build/Resources/Strings.resx
1. Additional counters for project evaluation.
2. Update ConfigurableForwardingLogger to forward BuildStatusEvents
a. This ensures that project evaluation started/finished events are piped through in multi-proc builds so the performance summary can correctly contain evaluation numbers.  The events are only forwarded if the verbosity is diagnostic or the performance summary will be shown.
Summary looks like this:
```
Project Evaluation Performance Summary:
25 ms  D:\CommonBuildToolset\Examples\src\CSharp\Windows\dirs.proj   1 calls
29 ms  D:\CommonBuildToolset\Examples\src\CSharp\Windows\UnitTests.MSTest\UnitTests.MSTest.csproj   1 calls
30 ms  D:\CommonBuildToolset\Examples\src\CSharp\Windows\UnitTests.NUnit\UnitTests.NUnit.csproj   1 calls
74 ms …
```
=> Include evaluation performance in performance summary

setup/files.swr, src/Build/Microsoft.Build.csproj, src/Build/project.json, targets/DeployDependencies.proj, targets/runtimeDependencies/project.json
VS is using 4.1.2.0 (nuget 4.3.0) whereas we were accidentally using 4.1.0.0 (nuget 4.1.0). This caused the loader to not use NGENed assemblies.
=> Differentiate version for System.IO.Compression

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build.UnitTests/Construction/ProjectRootElement_Tests.cs, src/Build.UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Construction/ProjectRootElement.cs, src/Build/Definition/ProjectLoadSettings.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Instance/ProjectInstance.cs, src/Build/Resources/Strings.resx, src/Shared/Traits.cs, src/Shared/UnitTests/ObjectModelHelpers.cs
New ProjectLoadSetting to control the feature
New code only runs after the project fails to load and the file existence is checked which should not impact performance.
Closes #1727
=> Ignore missing imports

src/Tasks/Microsoft.Common.CurrentVersion.targets
These look like good places to use ref assemblies if present--but we need to track down owners for the various tools here and confirm that they're correct.
@jcouv
=> Ref asm bugfixes

README.md
Also fixed a link to the rolling job from Desktop to Full, since we
changed the name of the job.
=> Update README with vs15.3 information

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, src/Tasks.UnitTests/WinMDExp_Tests.cs, src/Tasks/WinMDExp.cs
Fixes #2140 by always using a response file for winmdexp, avoiding
issues with too-long calls to CreateProcess.
Concerns:
=> Always use response file for winmdexp

src/Tasks/Microsoft.Common.CurrentVersion.targets
Some projects (and some NuGet packages) override GetTargetPath, and they
can't be expected to keep up with changes in the metadata now returned
by it.
This change moves the computation of the item returned from GetTargetPath
and Build into its own target (recycling
GetTargetPathWithTargetPlatformMoniker), so that it will still be
created by a project that overwrites GetTargetPath.
Fixes #2183.
=> @(TargetPathWithTargetPlatformMoniker) outside GetTargetPath

src/Shared/Traits.cs, src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks/AssemblyDependency/AssemblyInformation.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/Delegate.cs, src/Tasks/SystemState.cs
I recommend going through this commit-by-commit; a couple of commits are straightforward refactors that look complicated in the final diff.
There are two improvements here:
* When using the non-Full Framework `AssemblyInformation` extraction, read a file only once, populating `Dependencies` and `FrameworkName` with a single `FileStream`
* Read `AssemblyInformation` from a given path exactly once (instead of twice).
This chips away at #2015.
=> RAR performance improvements on Core

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, src/Tasks.UnitTests/WinMDExp_Tests.cs, src/Tasks/WinMDExp.cs
This reverts commit 184da1a84e1aaa3b2e4c0198154c66fa8858e0cd.
That commit compiled and produced reasonable output but the output is not accepted by (the current version of?) `winmdexp.exe`, which expects that arguments in the response file are newline rather than space separated.
@yizhang82 @AndyGerlicher
=> Revert "Always use response file for winmdexp (#2177)"

src/Tasks/Microsoft.Common.CurrentVersion.targets
PR #2180 caused a performance-test scenario internal to Microsoft to
start failing. The root cause was that the projects in the test
customized `$(IntermediateOutputPath)` _very_ late, after importing
CSharp.targets (and transitively Common.targets). That meant that the
path stored in `$(CopyOutOfDateMarker)` was no longer under
`$(IntermediateOutputPath)`, and that the directory wasn't created before
the new code attempted to touch the marker file.
Ideally, projects would set `IntermediateOutputPath` _before_ importing
common.targets, but that hasn't been strictly required in all cases
before so requiring it now is an unacceptable regression.
The late customization was handled for other intermediate outputs by
defining their paths with items (expanded after all properties are
expanded) …
=> Late bind CopyUpToDateMarker

src/Shared/Traits.cs, src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks/AssemblyDependency/AssemblyInformation.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/Delegate.cs, src/Tasks/SystemState.cs
In .NET Core, it's safe to use an AssemblyInformation object without
disposing it, but that's not true in full framework because of the use
of COM objects to extract information from the assembly. Backing out the
cache until we can test a fix that correctly disposes the objects
(including for RAR failures and exceptions).
This reverts commit be56bc33a441ec97d91861a44d63c52a489e747f.
This reverts commit 55f846e7c290828f798fcba4c148708ad2d4510b.
=> Revert RAR AssemblyInformation caching

src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Shared/Traits.cs, src/Shared/UnitTests/TestEnvironment.cs
The logging of import events introduced a 100ms regression in c++
scenarios. Hiding them under an escape hatch for now. The binary logger
is the only thing that sets them on.
Later on, we should add another enum value to ProjectLoadSettings to
enable API users to run this. Or figure our how to flow debugger
verbosity into the Evaluator so we can branch on it.
=> Hide import events under an opt in flag

src/MSBuild/app.amd64.config, src/MSBuild/app.config
If a code task factory uses System.IO.Compression it will pick up 4.0.0.0 from the GAC and since we load our local 4.1.2.0 we end up with two versions of the .dll loaded side-by-side, causing havoc.
=> Add binding redirect for System.IO.Compression to 4.1.2.0.

src/Shared/CoreCLRAssemblyLoader.cs
Fixes #2203 by including the culture folder in the search for assembly locations, if an assembly culture is defined.
=> Search for satellites next to task assemblies

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/netstandard1.3/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, src/Tasks.UnitTests/ToolTaskExtension_Tests.cs, src/Tasks.UnitTests/WinMDExp_Tests.cs, src/Tasks/CommandLineBuilderExtension.cs, src/Tasks/ToolTaskExtension.cs, src/Tasks/WinMDExp.cs, src/Utilities.UnitTests/CommandLineBuilder_Tests.cs, src/Utilities/CommandLineBuilder.cs
Update WinMDExp task to use a response file with new line separators
Add new property to CommandLineBuilder and CommandLineBuilderExtension class to use newlines instead of spaces
Add new property to ToolTaskExtension to use newlines in response files instead of spaces.
Update WinMDExp task to use a response file with newline separators and unquoted arguments
WinMDExp fails if there are quotes anywhere in the response file passed
to it, but correctly understands spaces in paths passed to /reference:
when the arguments are newline separated. Avoid ToolTask's default
quoting rules when populating the response file.
Reverts 0174f995. Fixes #2140.
=> Add ability to use newline separators in response files and update WinMDExp task to use it

build/NuGetPackages/Microsoft.Build.Framework.nuspec, build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec, build/NuGetPackages/Microsoft.Build.nuspec, src/Build.OM.UnitTests/project.json, src/Build/project.json, src/Framework/project.json, src/Shared/EncodingUtilities.cs, src/Tasks/Exec.cs, src/Tasks/project.json, src/Utilities/project.json
Fixes #2187 by fixing the broken assumption that .NET Core MSBuild is
always running under a Unicode-compatible codepage. That's not true on
.NET Core on Windows, for the same reason the original checks were
needed on full framework on Windows.
FYI @forki -- thanks for reporting the problem!
=> Query for OEMCP in core/Windows

targets/BootStrapMSBuild.proj
Without this change, I got failures like
```
S:\msbuild\bin\Bootstrap\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets(30,5): error MSB4062: The "ResolvePackageFileConflicts" task could not be loaded from the assembly S:\msbuild\bin\Bootstrap\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\tools\net46\Microsoft.NET.Build.Extensions.Tasks.dll.  Could not load file or assembly 'file:///S:\msbuild\bin\Bootstrap\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\tools\net46\Microsoft.NET.Build.Extensions.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class …
```
=> Copy task assemblies from installed extensions

src/Build/Instance/ProjectItemInstance.cs
This was causing about 0.3% of allocations (12 MB) of a particular scenario installing NuGet packages.
=> Do not allocate in TaskItem.GetHashCode

src/Shared/FileUtilities.cs
This was allocating 1.3% (43 MB of opening ProjectSystem.sln) of all allocations of VS open solution.
=> Stop allocating new char[] for invalid path/file chars

src/Shared/FileUtilities.cs
This method got inlined a few methods, so it's hard to see, but I think this was this array creation, or probably also including an inlined: https://github.com/Microsoft/msbuild/pull/2284.
=> Avoid params char[] allocation

src/Tasks/ManifestUtil/mansign2.cs
The code modified in this PR is used by clickonce to sign the manifest file. In order to support signing with SHA-2 cert, a workaround was added. However, this workaround should be opted out for 3rd party crypto providers. Otherwise, it causes verification failure(unknown publisher) when the manifest file is signed by a SHA-2 EV cert.
=> Should not opt in the SHA-2 workaround for 3rd party crypto providers

src/Tasks/Exec.cs
Fixes #2273 by falling back to `%ComSpec%` when `ToolLocationHelper.GetPathToSystemFile("cmd.exe")` returns a nonexistent value, as it does when `SHGetFolderPath` returns the user's home directory instead of the system directory, as it sometimes does on Nano Server.
Tested against the trivial `<Exec>` repro project and against a `dotnet new mvc` project; both succeed.
=> Use ComSpec when GetPathToSystemFile(cmd) is bogus

version.json
We probably DO NOT want to take this right now.
Just getting it out so it's one click away from done when we decide to drop `-preview` from our 15.3 packages.
=> 🔖 Move to release version numbering for 15.3

src/Build/Collections/HashTableUtility.cs
This was allocating 0.2% of data in the MSBuild process during solution open.
=> Avoid boxing dictionary enumerator

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/Expander.cs
In some cases, we evaluate a condition to false (which can be short circuited) but then expand the string fully.  The full condition can contain an error that wouldn't normally be seen if it evaluates to false early.
Fixes #2259
=> Do not cause an error or failed build when logging an expanded condition

LICENSE
Legal team pointed out that our license should reflect that MSBuild is a .NET Foundation project.
=> Update License to reflect .Net Foundation

src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.NETFramework.CurrentVersion.targets
...and check it in ImplicitlyExpandDesignTimeFacades
Fixes dotnet/sdk#1393.  What is happening with that bug is that the System.Runtime facades are not being added in the design-time build when you have a reference from a .NET Framework project to a .NET Standard 1.x project that doesn't have any output on disk yet.  This results in failed intellisense, which persists even after you build the solution and/or restart VS, because the design-time build is cached.
An alternative fix to this would be to set the `TargetPlatformIdentifier` of .NET Standard projects to `Portable`.  Then the existing logic that handles references to PCLs would kick in.  I would like to change the `TargetPlatformIdentifier` of .NET Standard projects to `Portable` in the future, as I think it's more correct than the …
=> Add target framework metadata to TargetPathWithTargetPlatformMoniker

src/Tasks/Microsoft.Common.CurrentVersion.targets
Avoid calling FullPath and the associated performance penalty. We should
not need the FullPath in this case as we are only hashing the list of
files (relative path is fine since the cache is per project).
Fixes #2276
On the project in the bug time spent in _GenerateCompileDependencyCache target went from ~30ms to ~10ms (debug bits).
=> Reduce allocation in _GenerateCompileDependencyCache

src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs, src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
Perf optimization: If the Update operation references itself (e.g. `<I Update="@(I)"/>`) then all items are updated and matching is not necessary.
Implements the simpler, more constrained optimization from #2314
=> Self referencing Update operations skip matching

src/Build/Evaluation/ItemSpec.cs
This was allocating a capture class, Func and boxing the enumerator of Fragments:
=> Remove unneeded allocations in ItemSpec.MatchesItem 

src/Build/Evaluation/Expander.cs
This was showing up as ~2% of all allocations in this trace: https://github.com/dotnet/sdk/pull/1432#issuecomment-316852561.
To make sure this wasn't causing additional overhead (as there's additional argument checking in the StringBuilder.Append(string, int, int) overload, I did a MicroBench mark:
``` C#
[MemoryDiagnoser]
public class SubString
{
public string Field = "This is a real long long argument";
[Benchmark]
public void StringBuilder_Append()
{
for (int i = 0; i < 10000; i++)
{
StringBuilder builder = new StringBuilder();
for (int j = 0; j < 5; j++)
{
builder.Append(Field, 20, 11);
}
}
}
[Benchmark]
public void StringBuilder_AppendViaSubString()
{
for (int i = 0; i < 10000; i++)
{
StringBuilder builder = new StringBuilder();
for (int j = 0; j < 5; j++)
{ …
```
=> Remove unneeded substring

src/Build/Evaluation/Expander.cs
This was allocation 0.3% of all allocations in some traces.
=> Avoid creating char[] allocations

src/Build.UnitTests/Collections/MSBuildNameIgnoreCaseComparer_Tests.cs, src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs, src/Build/Collections/PropertyDictionary.cs, src/Build/Definition/ProjectCollection.cs, src/Build/Evaluation/ConditionEvaluator.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/Expander.cs, src/Build/Resources/Constants.cs, src/Build/Utilities/EngineFileUtilities.cs, src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/Shared/MSBuildNameIgnoreCaseComparer.cs, src/Shared/NativeMethodsShared.cs, src/Shared/OpportunisticIntern.cs, src/Shared/Traits.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Shared/UnitTests/ObjectModelHelpers.cs
This PR ports the changes from an internal fork of MSBuild with the goal of removing the fork. There are two types of changes
- feature flagged features that are needed by internal tooling
- not expanding wildcards
- caching wildcard expansions
- caching file system existence checks
- changes that reduce lock contention
I tested this locally and RPS. RPS shows no degradation, and the local tests show about 5ms improvement for a 28 project solution.
Each commit contains one logical change, for ease of review.
=> Port internal changes

src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs, src/Shared/BuildEnvironmentHelper.cs
When MSBuild is detected outside of a Visual Studio environment, allow
the ToolsDirectory32 and 64 properties to be set correctly when
MSBuild.exe exists in the correct folder structure (amd64\MSBuild.exe).
=> Detect MSBuild amd64 environment running outside VS

src/Build.UnitTests/Collections/OMcollections_tests.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
This was redundant with xunit's `Assert.Throws` so this reduces
unnecessary complexity.
Primarily done through replacing
```
ObjectModelHelpers\.AssertThrows\(typeof\(([^)]*)\), delegate { ([^;]*);\s*}\)
```
with
```
Assert.Throws<$1>( () => $2 )
```
=> Remove ObjectModelHelpers.AssertThrows

src/Build.UnitTests/BackEnd/TaskRegistry_Tests.cs, src/Build/Instance/TaskRegistry.cs, src/Build/Resources/Strings.resx, src/Framework/ITaskFactory.cs
If TaskType is null it can cause a NullReferenceException in our code.  This change ensures that ITaskFactory implementations return a value for this property.
Fixes #1508
=> Display an error if an ITaskFactory does not set the TaskType property.

src/Tasks/Microsoft.Common.CurrentVersion.targets
Need to confirm these changes with owners of:
Continuation of #2167 for the post-15.3 timeframe.
=> Use ref assemblies in more locations

src/Build/Construction/ProjectElement.cs, src/Build/Resources/Strings.resx, src/Build/Xml/ProjectXmlUtilities.cs
Fixes #2373 by only checking the top-level namespace of a project, not
the namespace of every element.
This is arguably incorrect since XML namespace _could_ be per-element,
but a) that never worked before and b) you'd have to manually edit a
project in a fairly odd way to get that, so the performance gain here
seems to outweigh the risk.
=> Remove namespace check of every XML element

src/Build/Construction/ProjectRootElement.cs
Remove allocation when projects/targets don't have an SDK.
This was the cause of 0.2% allocations in a design-time build.
=> Remove enumerable allocation

src/Build/Collections/HashTableUtility.cs
This method is only called once, and only passed Dictionary - avoid the boxing of the enumerator, which saves 0.6% of allocations in a design-time build.
=> Remove enumerator allocation

src/Build.OM.UnitTests/project.json, src/Build.UnitTests/project.json, src/Framework.UnitTests/project.json, src/Tasks.UnitTests/project.json, src/Utilities.UnitTests/project.json, targets/runtimeDependencies/project.json
Picks up fix for shouldly/shouldly#437, which should get tests running
on the Mono runtime on non-Windows again.
=> Update Shouldly to 3.0.0-beta0003

src/Tasks.UnitTests/GenerateResourceOutOfProc_Tests.cs, src/Tasks.UnitTests/GenerateResource_Tests.cs
`NothingOutOfDateExceptReference` has been mysteriously failing in PR builds, but the message was useless:
```
MESSAGE:
Assert.True() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at Microsoft.Build.UnitTests.GenerateResource_Tests.InProc.RequiredTransformations.NothingOutOfDateExceptReference()
```
To make the output more useful, I taught the GenerateResource tests how to log to xunit instead of the console, and refactored the failing test to have more logging and assertions that have some hope of telling us what went wrong.
I would recommend looking at the second commit by itself. The first one was a big refactor to change all of the callsites of the `CreateTask*` helper methods to plumb through the test output.
Lots more opportunity for refactoring here!
=> GenerateResources test diagnosibility

src/MSBuild.UnitTests/XMake_Tests.cs
Fixes tests on mono/osx.
Microsoft.Build.UnitTests.XMakeAppTests.ResponseFileInProjectDirectoryWinsOverMainMSBuildRsp
Microsoft.Build.UnitTests.XMakeAppTests.ProjectDirectoryIsMSBuildExeDirectory
=> [tests] CopyMSBuild: copy .dll.config too

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
Under Mono/osx, even when using in-tree msbuild, solution before/after
files (eg. NuGet) get picked up from the installed mono. So, only count
targets coming from `.sln.metaproj` files, which would be the ones
generated by the SolutionGenerator.
The change should be safe for all platforms.
Fixes
Microsoft.Build.UnitTests.Construction.SolutionProjectGenerator_Tests.IllegalUserTargetNamesDoNotThrow
=> [mono][tests] Fix SolutionGenerator test on mono/osx

src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs, src/Shared/BuildEnvironmentHelper.cs
When using TryFromMSBuildAssembly with Microsoft.Build.dll inside the amd64 directory, the VisualStudioInstallRootDirectory
is incorrectly evaluated as if in 32 bits mode.
Fix for #2367
=> Fix #2367: incorrect evaluation of VisualStudioInstallRootDirectory

src/Shared/Traits.cs, src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks/AssemblyDependency/AssemblyInformation.cs, src/Tasks/AssemblyDependency/AssemblyMetadata.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/Delegate.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Tasks/SystemState.cs
My previous attempt at this in #2192 had a bad side effect: it kept handles within `AssemblyInformation` objects live in the cache past the point of RAR returning, because nothing disposed them. They should have been cleaned up eventually, if finalizers ran after GC, but that wasn't sufficient to keep an internal test that did a rebuild in VS working--it failed copying from obj to bin because a the file in bin was held in use.
This is a cleaner approach: wrap the extraction process as it was done before, and cache an object consisting only of the results.
That "object consisting only of the results" seems like it should just be `AssemblyInformation` instead of a new type. I introduced the new type to minimize churn and maximize understandability of this change in the short term.
Relates …
=> Return of RAR metadata caching

version.json
Builds from the master branch were being categorized as "release"
builds, and GitVersioning was emitting the official version number as a
three-part version like `15.5.42-preview`, which broke automated
releases, which need the four-part version number for the ExternalAPIs
package.
@AndyGerlicher this should unbreak the automated ingestions.
=> Ensure all VSTS builds have four-part versions

netci.groovy
I messed up in #2394 and didn't notice because I expected the MonoTest config to fail.
It did, but for the wrong reason: it wasn't building correctly and bailed out immediately.
That's because `cibuild.sh` didn't recognize the `MonoTest` runtime. Because it doesn't exist!
Fixing this by redundantly specifying `--target Mono` in mono flavor jobs. Since the last argument wins, this fixes the specification while keeping the code closer to what we want its final form to be.
=> Build known target in MonoTest CI

src/Shared/FileUtilities.cs
The previous iteration of this code allocated a new string in every call
for the file path. Avoiding that by using the `IndexOfAny` overload that
takes a start position.
=> Avoid allocation in PathIsInvalid

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs, ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/.nuget/project.json, targets/GenApi.targets
Resolves a build error during GenAPI caused by the copy of
System.IO.FileSystem.dll in the new GenAPI package being bad (it's not
signed). Reverting back to the old version.
=> Revert GenAPI Package Update

src/Build/Definition/Toolset.cs, src/Build/Evaluation/Conditionals/FunctionCallExpressionNode.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/Expander.cs, src/Shared/FileUtilities.cs, src/Shared/ProjectErrorUtilities.cs, src/Shared/ReuseableStringBuilder.cs
Remove opportunistic array allocation from `GetTaskFiles`
Remove IEnumerator and closure capture allocations from `FunctionCallExpressionNode`
Remove IEnumerator allocations from `Evaluator.ReadNewTargetElement`
Remove IEnumerator allocations from `Evaluator.PerformDepthFirstPass`
Remove IEnumerator allocations from `Expander.ExpandIntoItemsLeaveEscaped`
Reduce `string`  allocations from `FileUtilities.PathsEqual`
Reduce boxing allocations from `ProjectErrorUtilities`
Remove `StringBuilder.Clear` allocation on discarded `StringBuilder`s
Saves 20% of allocations (496MB) in a Rosyln restore (2389MB to 1893MB)
/cc @davkean @KirillOsenkov
=> Reduce Allocs

src/Build.OM.UnitTests/Definition/DefinitionEditing_Tests.cs, src/Build.OM.UnitTests/Instance/ProjectInstance_Tests.cs, src/Build.UnitTests/Evaluation/Expander_Tests.cs
Tests were failing on one of our CI environments because they were
built from a path containing a `@` character. As long as there were no
special characters in the paths used for the tests, the tests weren't
sensitive to whether the expected values were escaped properly.
Tested with
```
TMPDIR=/Users/raines/src/msbuild/tmp@ ./cibuild.sh --scope Tested
```
=> Escape or avoid escaping paths in tests

src/Tasks/Resources/Strings.resx
Before:
```
Using "WriteLinesToFile" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "WriteLinesToFile"
MSB3493:
```
After:
```
Using "WriteLinesToFile" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "WriteLinesToFile"
MSB3493: Skipping write to file "Bar" because content would not change.
```
=> Fix resource string for MSB3493

src/Build/Evaluation/Expander.cs, src/Shared/ReuseableStringBuilder.cs
This reduces allocations by 3% by avoiding the Join by slightly increasing allocations in Append.
Before:
After:
Scenario is attempting to mimic a solution wide design-time build from here: https://github.com/dotnet/project-system/issues/2712.
=> Reduce allocations in ExpandExpressionCaptureIntoStringBuilder

src/Build/Evaluation/Expander.cs, src/Build/Evaluation/ItemSpec.cs
This removes ~0.2% of enumerator boxing after https://github.com/Microsoft/msbuild/pull/2437 has been merged:
=> Remove enumerator boxing

src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/TaskItemSpecFilenameComparer.cs, src/Tasks/GetSDKReferenceFiles.cs
Avoid allocating strings for filenames, when we can take a slice of the `ItemSpec` instead.
Also some general style cleanup.
=> TaskItemSpecFilenameComparer cleanup

src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs, src/Shared/BuildEnvironmentHelper.cs
Fixes #2369 by relaxing the check to find any Visual Studio 15.*
install. This is required because Visual Studio 2017 Update 3 reports as
15.3.something, which wouldn't be found by the old code. Before Visual
Studio 15.2, a bug in VS setup caused it to report 15.0 (erroneously,
but compatibly with the old MSBuild behavior).
=> Check only the major version when finding VS

src/Tasks/Exec.cs, src/Utilities.UnitTests/ToolTask_Tests.cs
Triple-quotes seem to have been expanded as 
`{empty quoted string}{single-quoted string}{empty quoted string}`
rather than special
escaping. That confused an updated version of System.Diagnostic.Process,
so simplifying the quoting.
See https://github.com/dotnet/corefx/issues/23496#issuecomment-324519381 for context.
=> Single-quote Exec command line on *nix

src/MSBuild/app.amd64.config, src/MSBuild/app.config, src/Shared/UnitTests/App.config
Fixes #2338 by opting out of .NET 4.6.2+'s backward-compatible
LegacyPathHandling. See
https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/21/more-on-new-net-path-handling/
for details.
=> Opt into new .NET Framework path handling

build/NuGetPackages/Microsoft.Build.Runtime.nuspec
Clarifies the uses of the Microsoft.Build.Runtime package, hopefully
with caveats that encourage people that don't need it to avoid using it.
Inspired by https://github.com/Microsoft/msbuild/issues/2369#issuecomment-323859015 -- thanks for the feedback, @artiomchi.
=> Make description of Runtime package scarier

dir.props, src/Shared/CommunicationsUtilities.cs
Fixes #2402 by walking the OS environment block return via pointer math,
rather than first copying it to a `char[]` and walking that with safe
code.
=> Avoid allocating char[] in GetEnvironmentVariables

src/Tasks/Microsoft.Common.CurrentVersion.targets
All tasks in the target already have a condition '@(SDKReference)' != '' so to improve performance we can condition the target instead
Fixes #2443
=> Add condition to GetInstalledSDKLocations

src/MSBuild/app.amd64.config, src/MSBuild/app.config, version.json
Add binding redirect for RuntimeInformation facade
Not specifying this binding redirect was causing ngen issues with a
future version of .NET was installed.
Internal tracking bug: 467584
=> Add binding redirect for RuntimeInformation facade

src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs, src/Shared/BuildEnvironmentHelper.cs, src/Shared/Constants.cs
Fixes #2369 by relaxing the check to find any Visual Studio 15.*
install. This is required because Visual Studio 2017 Update 3 reports as
15.3.something, which wouldn't be found by the old code. Before Visual
Studio 15.2, a bug in VS setup caused it to report 15.0 (erroneously,
but compatibly with the old MSBuild behavior).
=> Port #2454: Check only the major version when finding VS

src/Tasks/Microsoft.Common.CurrentVersion.targets
This fix allows put all reference assemblies into a custom folder or NuGet package and use it in build time on CI.
=> Allow using the TargetFrameworkRootPath property from MSBuild.exe.config for setup reference assemblies folder.

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
App.config was being included twice and cause a warning in the error list.
=> Remove duplicate include of App.config

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/BuildManager/BuildRequestData.cs, src/MSBuild/XMake.cs, src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileMatcher_Tests.cs
1. Clear file enumerations cache because when the environment variable `MsBuildCacheFileEnumerations` is set, wild card expansions are cached.
2. Clear file existence cache because when the environment variable `MsBuildCacheFileExistence` is set, file existence is cached
/cc @dfederm
=> Clear more caches after /restore if necessary

setup/MsBuild.Engine.Corext/.readme.txt, setup/MsBuild.Engine.Corext/MSBuild.Engine.Corext.cxspec, setup/MsBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec, setup/MsBuild.Engine.Corext/TestBuild.cmd
This package aggregates to MsBuild.Corext. Because MsBuild.Corext is hand made, updating it to new versions is difficult. MsBuild.Engine.Corext alleviates this issue by upgrading the master package with the deliverables of this repo (engine binaries and the common build files)
=> Add MsBuild.Engine.Corext package

src/Build/BackEnd/Components/Communications/NodeEndpointInProc.cs, src/Build/BackEnd/Node/InProcNode.cs, src/Build/BackEnd/Node/OutOfProcNode.cs, src/Build/Instance/TaskFactories/TaskHostTask.cs, src/MSBuildTaskHost/Concurrent/ConcurrentDictionary.cs, src/MSBuildTaskHost/Concurrent/ConcurrentQueue.cs, src/MSBuildTaskHost/MSBuildTaskHost.csproj, src/MSBuildTaskHost/TypeLoader.cs, src/Shared/NodeEndpointOutOfProcBase.cs, src/Shared/TypeLoader.cs
Those following changes improve msbuild performance at least in 2 times. The build time in our case decreased **from 31 minutes to 13 minutes**.
In CoreCLR project we faced with major performance problem in Linux environment related to msbuild where building our C# tests (more then 10000 stand-alone C#/IL projects) takes a lot of time, much more than on Windows.
I started to investigate and figured out that most of time root msbuild process spends spinning trying to acquire some locks. The perf report shows that fact:
```
59.63%  dotnet   libcoreclr.so                         [.] Object::EnterObjMonitorHelperSpin
18.21%  dotnet   libcoreclr.so                         [.] AwareLock::Contention
1.05%  dotnet   libcoreclr.so                         [.] …
```
=> Major performance improvements (.NET Core + Linux)

src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
This saves 0.1% of allocations in a solution I'm testing with:
=> Remove boxing of enumerator

src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
We're not boxing the enumerable because LINQ has a fast path - but there's overhead here that's not needed.
=> Avoid calling through LINQ

src/Tasks/Microsoft.Common.CurrentVersion.targets
Use the same file name as the output directory $(TargetFileName).config. This is sufficiently unique because $(TargetFileName) is also written to the intermediate directory without further disambiguation.
Fix #1786
=> Shorten intermediate app.config path to avoid MAX_PATH

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs, src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs, src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs, src/Build.UnitTests/BackEnd/TaskHost_Tests.cs, src/Build/BackEnd/BuildManager/BuildRequestData.cs, src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs, src/Build/BackEnd/Components/BuildRequestEngine/FullyQualifiedBuildRequest.cs, src/Build/BackEnd/Components/RequestBuilder/IRequestBuilderCallback.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/CallTarget.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/MSBuild.cs, src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs, src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs, src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs, src/Build/BackEnd/Shared/BuildRequest.cs, src/Build/Resources/Strings.resx, src/MSBuild/Microsoft.Build.CommonTypes.xsd, src/MSBuild/XMake.cs, src/Tasks.UnitTests/MSBuild_Tests.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets
Note: Tests still to come. Since this is a lot of cascading changes I wanted to get it out for review before I spent too much time on tests.
Add optional `SkipNonexistentTargets` attribute to the `MSBuild` task. This allows for the ability to make changes to our project to project reference protocol which would be an otherwise breaking change.
Related to #2472
Closes #2471
=> Add support to skip missing targets in MSBuild task

src/Build.UnitTests/BackEnd/SdkResolution_Tests.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolution.cs, src/Framework/Sdk/SdkResolver.cs
If an SdkResolver returns null, then we throw a NullReferenceException
Also cleaned up the test a little
=> Fix NullReferenceException in SdkResolution

src/Build/Collections/CopyOnWritePropertyDictionary.cs, src/Build/Instance/ProjectItemInstance.cs
Sometimes when `SetMetadataObject` is executing, `RemoveMetadata` can set the backing collection to `null` which causes a `NullReferenceException`.  This change adds an atomic "remove if empty" operation to the `CopyOnWritePropertyDictionary<T>` which will clear the dictionary without resetting the reference to null.
Fixes #2264
=> Fix NullReferenceException in ProjectItemInstance.SetMetadataObject

src/Build.UnitTests/Collections/MSBuildNameIgnoreCaseComparer_Tests.cs, src/Build/Collections/CopyOnWritePropertyDictionary.cs, src/Build/Collections/PropertyDictionary.cs, src/Build/Collections/RetrievableEntryHashSet/HashSet.cs, src/Build/Evaluation/Expander.cs, src/Build/Microsoft.Build.csproj, src/MSBuild/MSBuild.csproj, src/Shared/IConstrainedEqualityComparer.cs, src/Shared/MSBuildNameIgnoreCaseComparer.cs, src/Utilities/Microsoft.Build.Utilities.csproj
Fixes: #2434
Partially fixes: #2429
MSBuildNameIgnoreCaseComparer has complicated logic/state for comparing partial strings ("constrained lookups") to avoid allocations when evaluating projects. This required it to have fields remembering the index/length to compare, and lock around said state to avoid multiple threads partying on it at same time. To avoid the contention https://github.com/microsoft/msbuild/commit/cc1e115c138dde4e72585c7b7fa77b83d57847a2#diff-92c6141b604c1dbb4e995702a79391ab introduced a change where we ended up creating unique comparers for every collection, causing [a bunch of allocations](https://github.com/Microsoft/msbuild/issue/2434). This also did not reduce the CPU overhead of [calling Monitor.Enter itself](https://github.com/Microsoft/msbuild/issues/2429). 
This …
=> Make MSBuildNameIgnoreCaseComparer stateless

src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
Still testing. Corrected the assertion to see what the issue is. I suspect the CI doesn't have the same version of the Windows SDK as the old one did.
=> Skip GetUnversionedSDKUnionMetadataLocation

src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs, src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs, src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileMatcher_Tests.cs
Avoids expensive string normalization on each discovered directory.
Improves performance (and probably memory) by not calling path aware comparisons and string normalizations during the recursive file walk. Instead, the user specs are normalized before the walk begins.
Also closes #1874 
Results based on building NHibernate.Test.csproj referenced in https://github.com/Microsoft/msbuild/issues/2392#issuecomment-330029024
=> Normalize include and exclude specs before file walking

src/Shared/FileUtilities.cs
IsVCProjFilename was allocating 0.1% in a large solution's evaluation:
=> Avoid allocating checking extension

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs, src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.NETFramework.CurrentVersion.targets
Fixes #2199.  This is needed for .NET 4.7.1 to support references to .NET Standard 2.0 libraries.
@AndyGerlicher @cdmihai @jeffkl @nguerrera @ericstj for review
=> Include .NET Framework facades if there is a reference to netstandard.dll

src/Build/Microsoft.Build.csproj, src/Build/Xml/ProjectXmlUtilities.XmlElementChildIterator.cs, src/Build/Xml/ProjectXmlUtilities.cs
For each project and for every container construct in a project (ItemGroup, ImportGroup, etc) we were allocating a `List<XmlElementWithLocation>` and a `XmlChildEnumerator`. In large solutions with large import graphs this was adding up to a non-trivial amount of allocations (1.7% of all allocations during evaluation in one trace).
Replaces these with a struct-based enumerable/enumerator that manually walks the child elements.
=> Avoid iterator/list allocations when parsing projects

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/Resources/Strings.resx
Modify the message MSB3277 to include the name of the conflicting assembly - a partial resolution of #608 . The message will be repeated once for each distinct assembly that is experiencing conflicts.
Old message:
```
MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  
These reference conflicts are listed in the build log when log verbosity is set to detailed.
```
New message (sample):
```
MSB3277: Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.  
These reference conflicts are listed in the build log when log verbosity is set to detailed.
```
I found two unit tests that trigger this warning - `ConflictWithBackVersionPrimary()` and `ConflictWithBackVersionPrimaryWithAutoUnify()`, both …
=> Include the name of the conflicting assembly as a part of warning MSB3277

src/Build/Construction/ProjectRootElement.cs
Building a single project I saw 17,537 `ElementLocation` objects being created.  It turns out that code in `XmlElementWithLocation` and `XmlAttributeWithLocation` was making new objects because the document full path is not set in time.
This change sets the document full path sooner.  This reduced the number of ElementLocation objects being created from 17,537 to just 9,237 (47% less)
FYI @davkean
=> Set document full path sooner to reduce allocations

src/Build/Evaluation/LazyItemEvaluator.cs
Remove 4 allocations:
- Boxed Enumerator
- WhereSelectEnumerableIterator
- OfTypeIterator
- Func<T, TResult>
This removes 2% of allocations in a large partner's solution.
=> Unlinqify ProcessItemSpec

targets/BootStrapMSBuild.proj
- Include Sdk Resolver in bootstrapped MSBuild.  This should mean the bootstrapped MSBuild can successfully build SDK-Style projects that use the 2.0 SDK or higher
- Add binary logging to build scripts
@AndyGerlicher @cdmihai @jeffkl for review
=> Include Sdk Resolver in bootstrapped MSBuild

src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/LazyItemEvaluator.cs
This was the cause of a large amount (1.2%) of allocations in a large project, some of which end up on the large object heap.
Large project from a partner:
Smaller project with mix of .NET Framework/.NET Standard projects:
=> Remove unnecessary List<T> instantiation

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build.UnitTests/Evaluation/ExpressionShredder_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs, src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs, src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/Expander.cs, src/Build/Evaluation/ExpressionShredder.cs, src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/Build/Evaluation/LazyItemEvaluator.cs, src/Build/Evaluation/SemiColonTokenizer.cs, src/Build/Microsoft.Build.csproj
This replaces SplitSemiColonSeparatedList's implementation with a struct-based enumerator. This avoids two types of allocations:
- Removes the need for short-lived `List<string>` just to collect the results (up to 1% of allocations)
- Removes the boxing of the enumerator in most cases when iterating the results (due to the `IList<T>` return type) (up to 0.6% of allocations)
This takes some of the changes @benaadams made in https://github.com/Microsoft/msbuild/pull/2401 and takes it further.
Future changes in later PRs:
- ~Make the same change to ExpandIntoStringListLeaveEscaped~ https://github.com/Microsoft/msbuild/pull/2586/commits/2cc0ade98bd4198a3c9bb26ecf1f8296783054fb
- Introduce a "string segment" to reduce short-lived string allocations such as Trim and Substring.
Running numbers.
=> Remove short-lived List<T> allocations from SplitSemiColonSeparatedList

src/Build.UnitTests/Evaluation/ItemSpec_Tests.cs, src/Build/Definition/Project.cs, src/Build/Evaluation/ItemSpec.cs, src/Build/Evaluation/LazyItemEvaluator.cs, src/Build/Microsoft.Build.csproj, src/Build/Utilities/EngineFileUtilities.cs, src/Build/Utilities/FileSpecMatchTester.cs
This includes https://github.com/Microsoft/msbuild/pull/2590, so be sure to only review the last commit https://github.com/Microsoft/msbuild/commit/16be8a35614dabf16c4e1e15c9f53ae14b7d368f.
This removes the capture class from CreateFileMatcher which was 0.3% of allocations (74 MB) in a large partner's solution:
=> Reduce more allocations in CreateFileMatcher

NuGet.Config, dir.props, src/.nuget/project.json, targets/BootStrapMSBuild.proj, targets/DeployDependencies.proj
Needed for #2595 
* Download NuGet.Build.Tasks from package (myget feed).
* Cleanup bootstrap. Avoid copying BuildTools blindly into the output folder.
* Correct some path properties. A lot of things just worked because we copied so much.
=> Cleanup bootstrap build

src/Build/Evaluation/ItemSpec.cs, src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
LazyOperation.Apply [is very allocation hungry](https://github.com/Microsoft/msbuild/issues/2599) and requires a small refactoring to prevent the gigabytes of data that its allocating while opening a partner's solution. To make reviews as easy as possible - I'm breaking off small portions on the road to the refactoring to try reduce regressions/review pain.
Below is unlinqifying RemoveOperation.SelectItems.
=> Remove LINQ operations

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/Shared/Traits.cs
This took 0.2% of CPU, and 0.1% of allocations in a .NET Standard/.NET Framework mixed project.
=> Remove the disable intrinsic MSBuild tasks escape hatch

src/Build/Evaluation/Evaluator.cs
Remove 6 allocations from ExpandAndLoadImports, approx. 0.1% of allocations.
Removes a `string[]`, `ConcatIterator`, `List<T>` and Array enumerator from `pathsToSearch` creation.
Removes a `string` and boxed `List<string>.Enumerator` from the Join.
=> Remove allocs

src/Tasks/AssemblyDependency/AssemblyResolution.cs
Stop boxing in CompileDirectories and avoid extra List<T> overhead.
This was about 0.1% in a mixed .NET Framework/.NET Standard solution.
=> Stop boxing in CompileDirectories

src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs
Note, I left the behavior "as is" which is that it always logs inputs/outputs regardless of whether they exist, ie the previous null checks would never have returned false because they were always assigned a value.
While this uses a StringBuilder under the covers, it pulls it from mscorlib's pool.
=> Remove unneeded StringBuilder alloc

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
Type all fields as List<T> and then just foreach over them. This avoids the box.
Also initialize capability in a few places.
=> Init smarter and rewrite loops

src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Build/Instance/ProjectInstance.cs, src/Utilities/ToolLocationHelper.cs
String.Join added an IEnumerable<string> overload in 4.0. This doesn't reduce the # allocations, but it does reduce the size of the allocations and prevent the copying.
=> Remove unneeded ToArray

src/MSBuildTaskHost/MSBuildTaskHost.csproj
Removes warning about it being in the project root.
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The file 'OutOfProcTaskAppDomainWrapper.cs' could not be added to the project.  Cannot add a link to the file E:\msbuild\src\MSBuildTaskHost\OutOfProcTaskAppDomainWrapper.cs. This file is within the project directory tree.	MSBuildTaskHost			
```
=> Remove <Link/> from OutOfProcTaskAppDomainWrapper

src/Build/Evaluation/ExpressionShredder.cs
ItemExpressionCapture represents four types of expressions; function call, a normal transform, separator transform and the entire outer expression. All expressions pay for the fields of the other regardless of whether they use them. 
This is a tiny little cleanup to reduce the diff when I attempt to split them up into their appropriate expressions.
=> Remove unused features of expression capture

build/NuGetPackages/Microsoft.Build.Framework.nuspec, build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec, build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec, build/NuGetPackages/Microsoft.Build.nuspec, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build.UnitTests/project.json, src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/Build/Evaluation/LazyItemEvaluator.cs, src/Build/Utilities/EngineFileUtilities.cs, src/Build/project.json, src/Framework/project.json, src/Shared/FileMatcher.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Tasks.UnitTests/project.json, src/Tasks/project.json, src/Utilities/project.json
Here are the optimization changes that were discussed in #2392, which are divided into three commits:
1. Usage of `Directory.EnumerateFiles` and `Directory.EnumerateDirectories` and checking excludes with a custom wildcard matching algorithm.
2. Adding directory caching passed by `LazyItemEvaluator`
3. Traversing subdirectories in parallel by using `Parallel.ForEach`
For the parallel change I did some modifications in order to prevent spawning too much threads. With the old modification the traversing created up to 9 threads on my computer, with the new one, it creates up to 4 threads. I found this to be a good balance between performance and threads being used, at least on my computer (Intel I7 860).
[This](https://github.com/maca88/msbuild/commit/24ccceeafb1d7969107fc02c272bcd29909eea4d# …
=> Optimizations for FileMatcher.GetFiles 

src/Shared/ResourceUtilities.cs
Accidentally removed it when adding obsolete therefore defeating the purpose of it existing (to catch accident calls to FormatResourceString without any args). As pointed out by @pilchie: https://github.com/Microsoft/msbuild/pull/2609#discussion_r143490068.
=> Add back the parameter to FormatResourceString

src/Tasks/Microsoft.Common.CurrentVersion.targets
Setting this property to `true` will skip evaluation of `FrameworkPathOverride` which can be expensive.
New SDK projects set FrameworkPathOverride to an empty string because all references from from NuGet packages.  So calculating the value is unnecessary overhead.
Fixes #2518 once the SDK sets this property in `Sdk.props`
=> Introduce EnableFrameworkPathOverride property

src/Build/Evaluation/LazyItemEvaluator.cs
This removes 0.2% of allocations due to a bug in System.Collections.Immutable.
=> Remove boxed enumerator allocation

src/Build/BackEnd/Components/RequestBuilder/Lookup.cs, src/Build/Collections/ItemDictionary.cs
This cuts allocations in Lookup.GetItems by half, from 2.8% -> 1.4% in a mixed .NET Standard/.NET Framework solution.
This is a minimal change to avoid introducing regressions but this code path is extremely allocation heavy, it's creating and copying collections into other collections *a lot*. ItemDictionary would be better replaced with a different collection:
Before:
After:
=> Reduce allocations in Lookup.GetItems

src/Build/Evaluation/IntrinsicFunctions.cs, src/MSBuild/XMake.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileUtilities_Tests.cs
1. `MSBuild.rsp` next to `MSBuild.exe`
2. `Directory.Build.rsp` in project directory or above
3. 1MSBuild.rsp` in the project directory
* Move `GetDirectoryNameOfFileAbove` and `GetPathOfFileAbove` to `FileUtilities` so they can be reused
* Show an error if there is an invalid switch in the response file
=>  Have MSBuild.exe search for a Directory.Build.rsp in the project directory or above

dir.props, documentation/ProjectReference-Protocol.md, src/.nuget/project.json, src/Tasks/Microsoft.Common.CrossTargeting.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets, targets/BootStrapMSBuild.proj, targets/bootstrapDependencies/Core/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets
Replaces #2472 and #2458
Still WIP. I need to get the NuGet task pulled down for bootstrap build.
=> Double Evaluation Fix

ref/net46/Microsoft.Build/Microsoft.Build.cs, ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs, src/Build.UnitTests/Definition/Project_Internal_Tests.cs, src/Build/Definition/Project.cs, src/Build/Definition/ProjectLoadSettings.cs, src/Build/Resources/Strings.resx, src/Shared/Traits.cs
Up until now project based evaluations evaluated certain elements (properties / groups, items / groups, item definition groups) even when their condition was false. This PR adds an option to turn this off.
Tested with [this project](https://github.com/jeromelaban/MicrosoftIssues/blob/master/MsBuildEarlyEvalIssue/XTargetProject/XTargetProject.csproj) and dropped a node_modules inside. Respecting conditions takes ~600ms, not respecting them takes ~1200ms.
CPS will have to turn this on via ProjectLoadSettings.DoNotEvaluateElementsWithFalseCondition
Closes #2502
=> Option to not evaluate elements with false conditions

src/Tasks/SystemState.cs
Fixes: #2440.
This makes sure that we only ever call GetLastWriteTime once during a single ResolveAssemblyReference session.
Note: I tried to maintain the existing behavior as much as possible and avoid rewriting this whole thing, except one change - previously, if a file on disk was found to be later than the process-wide cache, the process-wide entry would never get evicted (due to TryAdd). It now does.
This reduces CPU in GetFileState from 2.2% -> 0.9% in a mixed .NET Framework/.NET Standard solution.
Before:
After:
=>  Avoid multiple GetLastWriteTime on same assembly in ResolveAssemblyReference

src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs, src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs, src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs, src/Build/BackEnd/Components/RequestBuilder/ItemBucket.cs, src/Build/BackEnd/Components/RequestBuilder/Lookup.cs, src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Shared/Traits.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/Shared/UnitTests/TestData/GlobbingTestData.cs, src/Shared/UnitTests/TestEnvironment.cs
This is another implementation of #2639 which introduced a big perf regression.
Background:
Computing items under target elements is duplicated functionality with computing items under project elements. The clones used to be quite similar in the past, but have greatly diverged in the past year: initially, both clones would compute includes separately from excludes, and then obtain the final list of items by subtracting the excludes from the includes (excludes would hit the disk if they contained globs). Items under project underwent multiple modifications, like lazy item computation to avoid hitting the disk, and computing wildcard excludes together with wildcard includes to further avoid hitting the disk.
#2557 started normalizing items (for item elements under project elements) if they …
=> Fix exclude normalization mismatch in target item computation

setup/MsBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
The common targets got a dependency on a new Nuget task, which ships with VS15.5. Older MSBuild.Corext packages need to function with the newest MSBuild.Engine.Corext package, so as a temporary workaround we're including the nuget files. When VS15.5 ships, we should remove nuget, as MSBuild.Corext 15.5 will bring the nuget files.
I've also updated our Microbuild logic to create the bootstrap directory, so the nuspec will find the files.
Tested the whole union with Purger, which builds fine.
=> Distribute Nuget files in corext package
