src/XMakeBuildEngine/Microsoft.Build.csproj

Prevent TypeLoadException when running under Mono/Linux.

---

build.pl

Requires Perl to run.
In order to run tests, ***nunit-console*** program must be on the path.

Changed build.pl to work under Windows.

---

src/.nuget/packages.config

@ValMenn @AndyGerlicher @akoeplinger

Update Roslyn to RC3

---

build.cmd

Add NuGet download and pgk install in build.cmd

---

dir.props
src/Framework/project.lock.json
src/Shared/FileUtilities.cs
src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs
src/XMakeBuildEngine/BackEnd/Components/BuildComponentFactoryCollection.cs
src/XMakeBuildEngine/BackEnd/Components/Communications/NodeManager.cs
src/XMakeBuildEngine/BackEnd/Components/IBuildComponentHost.cs
src/XMakeBuildEngine/Microsoft.Build.csproj
src/XMakeBuildEngine/project.lock.json
src/XMakeCommandLine/AssemblyResources.cs
src/XMakeCommandLine/CommandLineSwitchException.cs
src/XMakeCommandLine/CommandLineSwitches.cs
src/XMakeCommandLine/InitializationException.cs
src/XMakeCommandLine/LogMessagePacket.cs
src/XMakeCommandLine/MSBuild.csproj
src/XMakeCommandLine/MSBuild.nuget.targets
src/XMakeCommandLine/OutOfProcTaskHostNode.cs
src/XMakeCommandLine/ProjectSchemaValidationHandler.cs
src/XMakeCommandLine/XMake.cs
src/XMakeCommandLine/project.json
src/XMakeCommandLine/project.lock.json

With these changes, MSBuild.exe successfully compiles for .NET Core.

Port MSBuild project to .NET Core

---

src/Shared/FrameworkLocationHelper.cs
src/Utilities/ToolLocationHelper.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
src/XMakeTasks/GetFrameworkPath.cs
src/XMakeTasks/GetFrameworkSDKPath.cs
src/XMakeTasks/UnitTests/SdkToolsPathUtility_Tests.cs

Adding support for Framework 4.6.1 SDK.

---

.gitignore
build.cmd
dir.props
dir.targets
src/.nuget/packages.config
src/Framework/UnitTests/Microsoft.Build.Framework.UnitTests.csproj
src/Framework/UnitTests/packages.config
src/Framework/UnitTests/project.json
src/XMakeBuildEngine/Microsoft.Build.csproj
src/XMakeBuildEngine/packages.config
src/XMakeBuildEngine/project.json

Like dotnet/Roslyn#4753, we'd like to be on the more futureproof path.  Plus, hopefully this will make it easier to stay within striking distance of convergence between xplat and master.

Replace packages.config with project.json

---

dir.props
dir.targets
src/Framework/UnitTests/project.json
src/Framework/UnitTests/project.lock.json
src/Shared/UnitTests/CopyOnWriteDictionary_Tests.cs
src/Shared/UnitTests/NativeMethodsShared_Tests.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/Utilities/CommandLineBuilder.cs
src/Utilities/Microsoft.Build.Utilities.csproj
src/Utilities/UnitTests/TaskItem_Tests.cs
src/Utilities/UnitTests/ToolTask_Tests.cs
src/Utilities/UnitTests/TrackedDependencies/FileTrackerTests.cs
src/Utilities/UnitTests/TrackedDependencies/TrackedDependenciesTests.cs
src/Utilities/UnitTests/project.json
src/Utilities/UnitTests/project.lock.json
src/XMakeBuildEngine/project.lock.json
src/XMakeCommandLine/MSBuild.csproj
src/XMakeCommandLine/UnitTests/CommandLineSwitches_Tests.cs
src/XMakeCommandLine/UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
src/XMakeCommandLine/UnitTests/ProjectSchemaValidationHandler_Tests.cs
src/XMakeCommandLine/UnitTests/XMake_Tests.cs
src/XMakeCommandLine/UnitTests/project.json
src/XMakeCommandLine/UnitTests/project.lock.json
src/XMakeTasks/UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
src/XMakeTasks/UnitTests/project.json
src/XMakeTasks/UnitTests/project.lock.json

More changes in tests projects towards conversion to CoreCLR.

Test projects updates

---

src/XMakeBuildEngine/Microsoft.Build.csproj

This should have been part of 49fbe21 but I missed it.
@ValMenn objections?

Remove manual reference to Tasks.Dataflow

---

dir.targets
src/.nuget/packages.config

Details as to why in comments in dir.targets

Use xunit console runner

---

src/XMakeTasks/GetSDKReferenceFiles.cs
src/XMakeTasks/StateFileBase.cs

Addresses part of #230.
These are two cases where we used BinaryFormatter to create and read a cache file. I just added a version field to those objects to invalidate previous versions. I had a repro solution where GenerateResources would crash with an old cache file, this fixes that.

Add version to a few serialized cache files.

---

dir.props

This probably isn't done.  Gotta do a bit of onion-peeling.

Rolling builds for xplat

---

src/nuget/Microsoft.Build.nuspec

This PR adds a .nuspec to create a NuGet package for Microsoft.Build.dll.

Create NuGet package for Microsoft.Build

---

src/XMakeTasks/ResolveManifestFiles.cs

Issue 76:
https://github.com/Microsoft/msbuild/issues/76

Patch for issue #76

---

RebuildWithLocalMSBuild.cmd
src/Shared/NativeMethodsShared.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/FxCopExclusions/Microsoft.Build.Suppressions.cs
src/XMakeBuildEngine/UnitTests/BackEnd/TargetBuilder_Tests.cs
src/XMakeTasks/AssemblyDependency/ReferenceTable.cs

I've fixed a few of the easiest FxCop warnings here, fixed the spelling of an existing justification, and also fixed a link in one of the batch files.
Next up: tackling IDisposable.

A few easy fixes

---

src/MSBuild.sln
src/Shared/FileUtilities.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectCollection_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectMetadata_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Microsoft.Build.Engine.OM.UnitTests.csproj
src/XMakeBuildEngine/UnitTestsPublicOM/project.json
src/XMakeBuildEngine/UnitTestsPublicOM/project.lock.json
src/dirs.proj

Enable the last test assembly (plus get all of its tests to the disabled-or-passing state).

Enable PublicOM tests

---

targets/CopyTestPrerequisites.proj

Workaround to obtain core target files

---

src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs
src/XMakeTasks/Microsoft.VisualBasic.targets

Change Microsoft.VisualBasic.targets encoding to utf-8

---

.gitattributes
cibuild.sh
netci.groovy

On master, the CI script for Linux and OSX exits.
@mmitche

Crossplatform CI aborts on master

---

cibuild.sh
dir.props
src/.nuget/packages.config
targets/LinuxDeployDependencies.proj

- set HOME if not set (HOME not set on CI machines)
- use unzip instead of tar (tar failed on linux)
- bump up compilers (the version we used was removed form myget)
- reuse nuget cache variable
Fixes #390

Updates for CI

---

dir.props
src/nuget/MSBuild.nuspec
src/nuget/Microsoft.Build.Tasks.Core.nuspec
src/nuget/Microsoft.Build.Utilities.Core.nuspec
src/nuget/Microsoft.Build.nuspec

Disable registry access entirely for NetCore flavors

---

dir.props
src/.nuget/packages.config
src/XMakeBuildEngine/project.json
src/nuget/Microsoft.Build.nuspec

Updating older NuGet references.
May take a few iterations, I just wanted to try this on the CI machine.

CI Build Fix

---

NuGet.Config
Samples/PortableTask/PortableTask.csproj
Samples/TaskUsageLogger/TaskUsageLogger.csproj
src/.nuget/project.json
targets/runtime.project.json

I went through all the NuGet packages we referenced and got them in sync. Horrible manual process unfortunately. I also removed the daily feeds so it wouldn't look there since it shouldn't be needed right now.
This now builds on my machine, hopefully the CI will pass.

Sync NuGet package versions.

---

src/XMakeTasks/GetReferenceAssemblyPaths.cs
src/XMakeTasks/UnitTests/GetReferencePaths_Tests.cs

When the targeted .NET framework reference assembly folder is not found,
an error (rather than warning) will be generated. This will prevent
producing a build that could be invalid.
Closes #173

Promote Framework not found (MSB3644) warning to error

---

src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs

hardcoding like "foo\\bar".
Fixes some tests on OSX.

Expander_Tests: Use Path.Combine to construct paths instead of

---

src/XMakeBuildEngine/Evaluation/Preprocessor.cs
src/XMakeBuildEngine/UnitTests/Evaluation/Preprocessor_Tests.cs

comments, as it is invalid. Also, fix the related test to match.
This should fix issue #491 .

Preprocessor: Sanitize "--" in file paths, when writing them out to xml

---

netci.groovy
src/Framework/UnitTests/project.json
src/Framework/UnitTests/project.lock.json
src/Utilities/UnitTests/project.json
src/Utilities/UnitTests/project.lock.json
src/XMakeBuildEngine/Evaluation/Preprocessor.cs
src/XMakeBuildEngine/UnitTests/Evaluation/Preprocessor_Tests.cs
src/XMakeBuildEngine/UnitTests/project.json
src/XMakeBuildEngine/UnitTests/project.lock.json
src/XMakeBuildEngine/UnitTestsPublicOM/project.json
src/XMakeBuildEngine/UnitTestsPublicOM/project.lock.json
src/XMakeCommandLine/UnitTests/project.json
src/XMakeCommandLine/UnitTests/project.lock.json
src/XMakeTasks/UnitTests/project.json
src/XMakeTasks/UnitTests/project.lock.json

Partial port of changes from 706ad7dd.

Enable tests in OS X CI jobs

---

src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProc.cs

Explicitly specify /nodeReuse in node creation

---

dir.props
src/.nuget/project.json
src/dir.props
src/dir.targets

Add MicroBuild NuGet package

---

src/XMakeBuildEngine/Logging/BaseConsoleLogger.cs
src/XMakeBuildEngine/Logging/ConsoleLogger.cs
src/XMakeCommandLine/Strings.resx

Eliminat some code duplication, SetColor and ResetColor were already
defined in BaseConsoleLogger.cs

Option for using ANSI-Colors that works with redirection

---

CreateSetupPackageLayout.proj
src/Shared/FrameworkLocationHelper.cs
src/Utilities/ToolLocationHelper.cs
src/XMakeBuildEngine/AllEngine/allengine.proj
src/XMakeBuildEngine/AllEngineAndConversion/allengineandconversion.proj
src/XMakeBuildEngine/ApexTests/ApexTests.csproj
src/XMakeBuildEngine/allmajorprojects/allmajorprojects.proj

Porting changes from VS 15 internal fork.
- Some changes related to internal proj files that changed
- Updates to ToolLocationHelper for VS version 15.
Adding DataFlow dll to setup package
Resolves #547.

VS15 changes port

---

Samples/TaskUsageLogger/TaskUsageLogger.csproj

Fix windows/mono build: Samples/TaskUsageLogger - Target framework v4.6,

---

src/XMakeBuildEngine/Evaluation/Evaluator.cs
src/XMakeBuildEngine/UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs

- This allows for something like $(MSBuildProgramFiles32)\MSBuild to be a
fallback search path.
- Tests were disabled in master w/o the feature defined.

Expand extension path fallback and enable tests.

---

netci.groovy

It should be disabled (same as Ubuntu).

Fix OSX CI for master

---

src/XMakeTasks/Exec.cs

The previous comment was accurate but relied on esoteric knowledge of Windows internals. Adding a link that provides that knowledge.
cc @radical

Clarify explanation of pushd for exec task

---

src/XMakeBuildEngine/Collections/RetrievableEntryHashSet/HashSet.cs

This is a port of an internal fix that just came up, cb621469 in the VS
repo.

Fix CS1574 warning

---

src/Shared/FrameworkLocationHelper.cs
src/Utilities/ToolLocationHelper.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
src/XMakeTasks/GetFrameworkPath.cs

Adding support for 4.5.2 target framework

---

netci.groovy

We can't differentiate PR jobs by the branch they target. This is an issue because PRs targeting master should only have Windows CI jobs. 
For tests, this means the CI should only collect test results when test result files are there. The only risk here is that if someone turns off the tests entirely, the main build succeeds and Jenkins will not complain.

Skip CI test result archiving if no test result files found

---

src/Shared/FrameworkLocationHelper.cs
src/Utilities/ToolLocationHelper.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
src/XMakeTasks/GetFrameworkPath.cs

Also some code cleanup. There's a lot more that could be done (especially the constants at the top of the file that are poorly used), but hopefully it's improved some while I was there.

Adding Framework 4.6.2 for VS "15"

---

src/Shared/InprocTrackingNativeMethods.cs
src/Utilities/TrackedDependencies/FileTracker.cs
src/Utilities/UnitTests/TrackedDependencies/FileTrackerTests.cs

Note: much duplication here is from cherry-picks @AndyGerlicher did to get bugfixes into U3, so the changes should already exist in master.

RI dev14 Update 3 RC

---

src/XMakeBuildEngine/Definition/ToolsetReader.cs

ToolsetReader: Fixes and code improvements for mono build

---

src/XMakeTasks/FileState.cs

I wasn't able to get it fully building locally (I didn't try very hard though, honestly ;)), but this is a pretty innocuous small change :). I assume there's some kind of CI process that will be able to check if I messed up the syntax :D.
Fixes #755 
/cc @rainersigwald

remove debugging message from FileDirInfo

---

src/XMakeCommandLine/app.config

Remove trailing ) in SDK35ToolsPath property.

---

src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

New string appeared between xlf creation and when localization team translated them. This commit syncs the xlf against the latest resource state on master.

Update xlf files with new string

---

netci.groovy

Make CI test artifact glob recursive

---

src/XMakeTasks/Microsoft.Data.Entity.targets
src/XMakeTasks/Microsoft.ServiceModel.targets
src/XMakeTasks/Microsoft.WinFx.targets
src/XMakeTasks/Microsoft.WorkflowBuildExtensions.targets
src/XMakeTasks/Microsoft.Xaml.targets

.. targets, might not be available like on OSX, so make the imports
conditional on their existence.

Fix mono/osx build: The "real" targets file corresponding to the shim

---

build.proj
dir.traversal.targets
setup/files.swr

Getting ready to turn on localized builds in microbuild and VS insertion.
This PR adds the satellite assemblies into the vsix and fixes up the build to eliminate a race

Localized vsix packages

---

src/XMakeBuildEngine/Evaluation/Evaluator.cs
src/XMakeBuildEngine/Evaluation/Expander.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.EvaluatorData.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.ItemFactoryWrapper.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs
src/XMakeBuildEngine/Microsoft.Build.csproj
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectItemElement_Tests.cs
src/XMakeBuildEngine/project.json

Fork of #770 to rebase it, fix it, and address comments from other PR.
If CI passes I'll go ahead and merge it in

Lazy item evaluation

---

src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderInProc.cs

Named semaphores are not supported on Unix in .NET Core
Ref: https://github.com/dotnet/coreclr/blob/5e9a125/src/mscorlib/src/System/Threading/Semaphore.cs#L96
We use static Semaphore which is instantiated per process when the first
node is created, and release it only when "shutdown packet" is encountered.
This fixes some of the failing tests on Ubuntu.

Use static semaphore instead of named semaphore

---

src/XMakeBuildEngine/Definition/Project.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs

Get all globs

---

src/Shared/FileMatcher.cs
src/Shared/UnitTests/FileMatcher_Tests.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs

Fixes #917
There was a trailing slash missmatch between two parts of code that have never been put together until now

Fix FileMatcher bug around trailing slashes

---

src/XMakeTasks/UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs

These checks are duplicates of the ones done on lines 1011, 1748 an 2744 respectively.

Drop identical checks

---

src/Shared/UnitTests/FileMatcher_Tests.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs
src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs
src/XMakeTasks/UnitTests/Exec_Tests.cs
src/XMakeTasks/UnitTests/GenerateResource_Tests.cs

Some I conditionally disabled on netcore, some just worked.

Enable desktop tests that were skipped in xplat

---

src/XMakeBuildEngine/Evaluation/Expander.cs
src/XMakeBuildEngine/Instance/ProjectInstance.cs
src/XMakeTasks/AssemblyDependency/ReferenceTable.cs
src/XMakeTasks/AssemblyDependency/ResolveAssemblyReference.cs

Similar to #950.
All these `if`-checks have nearly identical checks just before, making these unnecessary as the result won't be different.

Remove unnecessary if statements

---

src/Shared/CoreCLRAssemblyLoader.cs

Related to issue #750.
We need the ability to load task-containing assemblies from arbitrary
locations on disk determined at run time, along with thei dependencies.
It is assumed that their dependencies will be located next to them in
the file system, or in some well-known location.
Ideally we would handle the dependencies by hooking the `Resolving`
event on the default `AssemblyLoadContext`. However, due to
https://github.com/dotnet/coreclr/issues/5837 we can't currently do
this. Instead, we need to implement our own `AssemblyLoadContext`.
This is what we currently do. However, we run into a problem when a task
assembly depends on, say, Microsoft.Build.dll (which is pretty much
guaranteed). Microsoft.Build will already be loaded into the default
`AssemblyLoadContext`, but since our task …

Update assembly loader

---

src/XMakeBuildEngine/Construction/Solution/SolutionFile.cs

This PR contains just the `src/XMakeBuildEngine/Construction/Solution/SolutionFile.cs` change from #958, as requested by @cdmihai.

More if drops

---

setup/files.swr

Somehow this was missed and placed by another component in VS. Adding it
to the package layout.

Add Microsoft.Common.props to setup package.

---

src/Shared/UnitTests/MockLogger.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs

This is mostly to help me diagnose a mysterious `ToolLocationHelper` test, but it also includes some infrastructure that should help many future tests (once they get opted into xunit logging).

Improved test logging

---

src/Shared/FileMatcher.cs
src/Shared/UnitTests/FileMatcher_Tests.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/UnitTests/TargetsFile_Test.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs

Port #917 to xplat

---

src/Shared/FileMatcher.cs
src/Shared/FileUtilities.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/Evaluation/ItemSpec.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IncludeOperation.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs
src/XMakeBuildEngine/Utilities/EngineFileUtilities.cs

Fix Escaping bug

---

build/LegacyPackages/14.0/build.cmd

I will publish them to NuGet.org and MyGet unless anyone objects...

Remove prerelease tag from MSBuild 14 packages

---

setup/files.swr
src/XMakeTasks/Microsoft.Build.Tasks.csproj
src/XMakeTasks/Microsoft.VisualStudioVersion.v15.Common.props

This file is currently being dropped into VS internally.

Add Microsoft.VisualStudio.v15.Common.props

---

src/Framework/BuildEventArgs.cs
src/Framework/BuildEventContext.cs
src/Framework/BuildStatusEventArgs.cs
src/Framework/INodeLogger.cs
src/Framework/Microsoft.Build.Framework.csproj
src/Framework/ProjectStartedEventArgs.cs
src/Framework/TargetFinishedEventArgs.cs
src/Framework/TargetStartedEventArgs.cs
src/dir.props
src/dir.targets

I'm going to include these in the NuGet packages.  But we're missing some comments on stuff so I started this pull request to get through them all.
Please verify my doc comment updates are accurate.

XML doc files for our assemblies

---

src/Shared/AssemblyFolders/AssemblyFoldersFromConfig.cs
src/Shared/EventArgsFormatting.cs
src/Shared/FileMatcher.cs
src/Shared/RegistryHelper.cs
src/Shared/TaskLoggingHelper.cs
src/Shared/VersionUtilities.cs
src/Utilities/AssemblyFolders/AssemblyFoldersFromConfigInfo.cs
src/Utilities/Microsoft.Build.Utilities.csproj
src/Utilities/ProcessorArchitecture.cs
src/Utilities/ToolLocationHelper.cs
src/Utilities/ToolTask.cs
src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs
src/Utilities/TrackedDependencies/CanonicalTrackedOutputFiles.cs
src/Utilities/TrackedDependencies/FileTracker.cs
src/Utilities/TrackedDependencies/FlatTrackingData.cs
src/dir.targets

- Need a good description for the FlatTrackingData class
- Found a bug in my original commit where the XML documentation file wasn't being named properly

XML documentation for Microsoft.Build.Utilities

---

src/XMakeTasks/UnitTests/Exec_Tests.cs

I've seen this test fail because there are different numbers of files in
TEMP before and after the test--but it's always because something else was
running at the same time and using temp files.

Isolate Exec-doesn't-pollute-TEMP test files

---

build/NuGetPackages/Microsoft.Build.Framework.nuspec
build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec
build/NuGetPackages/Microsoft.Build.nuspec
src/XMakeBuildEngine/Microsoft.Build.csproj

Fixes #1031 Update NuGet packages to contain XML documentation
Also found a bad merge in Microsoft.Build.csproj

Include XML documentation files in NuGet packages

---

src/.nuget/packageLoad.targets
src/MSBuild.sln
src/Utilities/UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
src/Utilities/project.json
src/XMakeBuildEngine/UnitTests/Construction/ElementLocation_Tests.cs
src/XMakeBuildEngine/UnitTests/Instance/TaskItem_Tests.cs
src/XMakeCommandLine/UnitTests/XMake_Tests.cs
src/XMakeTasks/UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs
src/XMakeTasks/UnitTests/CodeTaskFactoryTests.cs
src/XMakeTasks/UnitTests/CreateCSharpManifestResourceName_Tests.cs
src/XMakeTasks/UnitTests/GenerateResource_Tests.cs
src/XMakeTasks/UnitTests/MSBuild_Tests.cs
src/XMakeTasks/project.json

Enable xplat tests

---

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs

- New property bool UseSymboliclinksIfPossible

Update ref API for Microsoft.Build.Tasks.Core

---

src/Shared/StrongNameHelpers.cs
src/XMakeTasks/GenerateResource.cs
src/XMakeTasks/UnitTests/AssemblyDependency/Miscellaneous.cs
src/XMakeTasks/UnitTests/AxTlbBaseTask_Tests.cs
src/XMakeTasks/UnitTests/GenerateResource_Tests.cs
src/XMakeTasks/UnitTests/GetInstalledSDKLocations_Tests.cs

Last batch of xplat full framework tests

---

src/nuget/Microsoft.Build.Targets.nuspec

Fix #1109 
@rainersigwald @srivatsn @eerhardt

Add language-specific x-targeting targets to nuspec

---

build/NuGetPackages/Microsoft.Build.nuspec
ref/net46/Microsoft.Build/Microsoft.Build.cs
ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs

New overload to ProjectRootElement.Create()
Update nuspec with casing issue.

Update public API

---

build/NuGetPackages/Microsoft.Build.Runtime.nuspec

Add language-specific x-targeting targets to new packages

---

netci.groovy

CI localized builds via cibuild.cmd

---

src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/Definition/Project.cs
src/XMakeBuildEngine/Resources/Strings.resx
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/DefinitionEditing_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs

Exception based implementation of https://github.com/Microsoft/msbuild/issues/736

Project can throw when item elements are split

---

src/XMakeBuildEngine/UnitTests/Evaluation/ProjectRootElementCache_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs
src/XMakeCommandLine/UnitTests/XMake_Tests.cs

There are three in here and three remain unchecked in #799.
/giphy I want to believe

Yet more desktop tests

---

documentation/consuming-nuget-package.md

Rough draft documentation for NuGet packages.  Please proof-read and comment as necessary.
FYI @Sarabeth-Jaffe-Microsoft

Create documentation for NuGet packages.

---

build/LocalizationTasks/SaveXlfToResx.cs
build/LocalizationTasks/UpdateXlfFromResx.cs
build/LocalizationTasks/project.json

This allows us to specify whether a string is new or updated
PR based on #1145. Only the last commit is new.

Bump up xlf parser

---

src/XMakeBuildEngine/Construction/ProjectElement.cs
src/XMakeBuildEngine/Construction/ProjectElementContainer.cs
src/XMakeBuildEngine/Construction/ProjectItemElement.cs
src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs
src/XMakeBuildEngine/Evaluation/ProjectParser.cs
src/XMakeBuildEngine/Resources/Strings.resx
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectItemElement_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectMetadataElement_Tests.cs

Allow item metadata to be expressed as attributes on the item element instead of child Xml elements

---

src/XMakeBuildEngine/Resources/Strings.resx

Correct typo in ProjectMustBeInMSBuildXmlNamespace

---

src/Shared/CoreCLRAssemblyLoader.cs

When the default `AssemblyLoadContext` cannot find a dependency of a task assembly (because it does not know where to look) it fires the `Resolving` event, and uses whatever `Assembly` object is returned. Our implementation of the handler simply looks next to each known task assembly and loads and returns the first assembly with a matching short name.
This generally works fine but can be a problem if there are two or more task assemblies that depend on assemblies with the same short name but different versions--the task may ask for version 2.0.0.0, but end up with 1.0.0.0 instead. If it then tries to access an API that does not exist in 1.0.0.0 you'll get an exception.
The fix for this issue is to check the version of a candidate assembly before loading it. If it doesn't match, we simply …

Update assembly loader to account for version numbers

---

src/XMakeBuildEngine/Xml/ProjectXmlUtilities.cs

Manual port of 96e6a3078acd765791a0e1a520b385fbcf11ae4c from xplat

Ignore whitespace text nodes when parsing projects

---

src/MSBuild.sln
src/OrcasEngine/OrcasEngine.csproj
src/OrcasEngine/project.json
src/Utilities/Microsoft.Build.Utilities.csproj
src/XMakeCommandLine/MSBuildTaskHost/MSBuildTaskHost.csproj
src/XMakeConversion/XMakeConversion.csproj
src/XMakeConversion/project.json

Fix some issues in xplat branch.

Fix issues in xplat project

---

cibuild.sh
dir.props
targets/runtimeDependencies/project.json

* Detect the runtime in cibuild.sh
* Pass that along to our runtime dependencies instead of it being hard coded to ubuntu 14
Closes #833

Support for building on ubuntu 16.04

---

README.md

These are the jobs that are updated by the generator script
`netci.groovy`. The other jobs seem to be remnants of an older CI
configuration.

Re-re fix badges

---

setup/files.swr

Rename pt to pt-BR in our setup package.

---

src/Shared/BuildEnvironmentHelper.cs
src/Shared/InternalErrorException.cs

Previously we assumed that if the entry point for our code was a test
runner that we were running as part of our unit test suite and had a few
code path differences (specifically around loading toolsets from config
file). The test was too broad and would detect when we were in a unit
test not associated with MSBuild and cause the build to fail.
This change first detects if we're in a known test runner (as it did
before) and then also checks to ensure that one of our known test
assemblies is loaded.
Fixes #1218

Add precision for detecting when running tests.

---

src/XMakeBuildEngine/Evaluation/Evaluator.cs
src/XMakeBuildEngine/Evaluation/ItemSpec.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IItemOperation.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.IncludeOperation.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.RemoveOperation.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.UpdateOperation.cs
src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs
src/XMakeBuildEngine/Microsoft.Build.csproj
src/XMakeBuildEngine/UnitTests/Evaluation/ItemEvaluation_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/Project_Tests.cs

Merge Cache GetItems Computations to xplat

---

src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs

Cherry pick 5f7c86cc190560c2321d568694bb6429a7f823b from xplat to unbreak Release builds on master.

Fix build break in Release configuration. (#1234)

---

src/Utilities/ToolLocationHelper.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs

@XianghanWang Can you take a quick look? The only changes I made were to add `[PlatformSpecific(Xunit.PlatformID.Windows)]` to all your new tests.

Merge #1239 to xplat

---

src/XMakeBuildEngine/Construction/ProjectElementContainer.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ConstructionEditing_Tests.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectMetadataElement_Tests.cs

Fixes #1210 
While doing this I found #1253 which I'll tackle in a separate PR

Adding metadata as element skips over existing metadata as attributes

---

src/XMakeTasks/UnitTests/GenerateResource_Tests.cs

Casing issue and a timing issue.
Closes #1297

Fix tests that weren't working on Linux

---

netci.groovy

I already edited the build definitions so it should work just fine.  If there are any problems, it'll be easy to revert.

Update CI environment to run tests on Ubuntu

---

ref/net46/Microsoft.Build/Microsoft.Build.cs
src/XMakeBuildEngine/Construction/ProjectElement.cs
src/XMakeBuildEngine/Construction/ProjectItemElement.cs
src/XMakeBuildEngine/Construction/ProjectMetadataElement.cs
src/XMakeBuildEngine/Evaluation/ProjectParser.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectRootElement_Tests.cs

Project Element cloning asks a new hook if it is OK to clone attributes

---

build/LocalizationTasks/ConvertToNeutralXlf.cs
build/LocalizationTasks/EmitLocalizedResources.cs
build/LocalizationTasks/LocalizationUtils.cs
build/LocalizationTasks/Microsoft.Build.LocalizationTasks.csproj
netci.groovy
src/Framework/Microsoft.Build.Framework.csproj
src/OrcasEngine/Engine/Engine.cs
src/OrcasEngine/Resources/xlf/Strings.xlf
src/Shared/BuildEventFileInfo.cs
src/Shared/Resources/xlf/Strings.shared.xlf
src/UpdateLocalizedResources.targets
src/Utilities/Resources/xlf/Strings.xlf
src/XMakeBuildEngine/Construction/ProjectRootElement.cs
src/XMakeBuildEngine/Definition/Toolset.cs
src/XMakeBuildEngine/Resources/xlf/Strings.xlf
src/XMakeBuildEngine/UnitTests/InvalidProjectFileException_Tests.cs
src/XMakeCommandLine/Resources/xlf/Strings.xlf
src/XMakeConversion/Resources/xlf/Strings.xlf
src/XMakeTasks/ManifestUtil/Resources/xlf/Strings.ManifestUtilities.xlf
src/XMakeTasks/Resources/xlf/Strings.xlf
src/dir.targets

Resolved Conflicts in:
build/LocalizationTasks/Microsoft.Build.LocalizationTasks.csproj
src/Framework/Microsoft.Build.Framework.csproj

Merge master into xplat

---

src/XMakeBuildEngine/UnitTestsPublicOM/Construction/WhiteSpacePreservation_Tests.cs

Added tests to help investigate #1321

Whitespace tests for adding siblings

---

src/XMakeTasks/Microsoft.Common.CrossTargeting.targets

Fix #1364
@rainersigwald @AArnott

Specify build as default target for cross-targeting projects too

---

src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs
src/XMakeBuildEngine/UnitTests/Evaluation/Expander_Tests.cs

Property function for EnsureTrailingSlash()

---

src/Shared/UnitTests/App.config
src/XMakeBuildEngine/Definition/ToolsetLocalReader.cs
src/XMakeBuildEngine/Definition/ToolsetReader.cs
src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs
src/XMakeCommandLine/app.amd64.config
src/XMakeCommandLine/app.config
src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets
src/XMakeTasks/Microsoft.Common.tasks
src/XMakeTasks/Microsoft.VisualBasic.CurrentVersion.targets
targets/BootStrapMSBuild.proj
targets/DeployDependencies.proj
targets/roslyn/project.json

Related to #1183 and dotnet/roslyn#14660.
cc @OmarTawfik -- I'll test this + your current package in VS.
cc @piotrpMSFT -- the coming change will require a layout update for the CLI too

Consume Roslyn from its new location

---

cibuild.cmd
cibuild.sh

Hoping this will insulate us a little bit from problems we're seeing in CI where things in TEMP are messed up.

Alter TEMP folder when running in CI

---

src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs
src/XMakeCommandLine/app.amd64.config
src/XMakeCommandLine/app.config

@olgaark look right?
Fixes #1384

Allow override of VCTargetsPath property.

---

ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs

Somehow I missed the netstandard1.3 WarningsAsErrors and WarningsAsMessages properties.
Skip CI please

Update ref assembly source

---

src/XMakeCommandLine/Resources/Strings.resx

I meant to fix this before I merged but missed it...

Fix error code from my incorrect merge

---

src/dir.targets

This reverts commit d83721a9b39c59d67a6c8721d93bae26b65c4eb5.

Revert "Disable GitVersioning in CI to work around #1409"

---

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets

Include .config files in AllowedReferenceRelatedFileExtensions

---

src/Shared/BuildEnvironmentHelper.cs
src/Shared/FrameworkLocationHelper.cs
src/Shared/ToolsetElement.cs
src/Utilities/UnitTests/ToolLocationHelper_Tests.cs
src/XMakeBuildEngine/Definition/ToolsetConfigurationReader.cs
src/XMakeBuildEngine/Definition/ToolsetReader.cs
src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs
src/XMakeBuildEngine/UnitTests/BuildEnvironmentHelper_Tests.cs
src/XMakeCommandLine/app.amd64.config
src/XMakeCommandLine/app.config

Refactor / fix build environment discovery.

---

setup/files.swr

(affects internal Visual Studio setup only)

Specify ngen architecture for amd64 executables.

---

src/Shared/FileMatcher.cs
src/Shared/UnitTests/ObjectModelHelpers.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Definition/ProjectItem_Tests.cs
src/XMakeBuildEngine/Utilities/EngineFileUtilities.cs

Exclude computation skips over illegal file specs

---

NuGet.Config
cibuild.sh
dir.props
src/.nuget/project.json
src/Utilities/project.json
src/XMakeBuildEngine/UnitTestsPublicOM/project.json
src/XMakeBuildEngine/project.json
src/XMakeTasks/project.json
targets/runtimeDependencies/project.json

Update to match change in Roslyn tools.

Update System.Collections.Immutable to 1.2.1

---

src/Utilities/Resources/Strings.resx
src/Utilities/Resources/xlf/Strings.de.xlf

Copied over from the internal MSBuild repository as the internal localization files are not used anymore.

Update German translation

---

src/XMakeBuildEngine/Construction/Solution/SolutionProjectGenerator.cs
src/XMakeBuildEngine/UnitTests/Construction/SolutionProjectGenerator_Tests.cs

Fix solution targets

---

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
src/Framework/Microsoft.Build.Framework.csproj
src/OrcasEngine/OrcasEngine.csproj
src/XMakeConversion/XMakeConversion.csproj

Somehow 3 projects were left out of the reference assembly source code generation.
Also updated the generated sources.

Update projects that should be generating reference assembly sources

---

src/XMakeBuildEngine/UnitTests/BackEnd/TaskRegistry_Tests.cs

Test used to compile an assembly on the fly which is brittle.  The test project already has enough references to contain the task itself.
The test will now run on .NET Core as well
Closes #211

Embed task in TaskRegistry_Tests

---

src/XMakeCommandLine/UnitTests/XMake_Tests.cs

Enable some tests that used to fail on .NET Core

---

src/XMakeBuildEngine/Definition/Project.cs
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectSdkImplicitImport_Tests.cs

Fix issue with implicit imports and GetLogicalProject()

---

src/XMakeBuildEngine/Evaluation/ProjectParser.cs
src/XMakeBuildEngine/Resources/Strings.resx
src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectItemElement_Tests.cs

Better message when Exclude appears without Include

---

cibuild.cmd
dir.targets
src/XMakeCommandLine/MSBuild.csproj

Includes a fix for @jeffkl's comments on #1605.

🔀 RI vs15-rtw

---

src/XMakeTasks/Microsoft.Common.CurrentVersion.targets

Follow up upon testing of #1621 
@AndyGerlicher

Don't overwrite pre-existing SetTargetFramework

---

setup/files.swr

Updating paths in reaction to the recent file layout change under src

Rename paths in SWR

---

src/MSBuild/app.amd64.config
src/MSBuild/app.config
src/Tasks/Microsoft.Common.CurrentVersion.targets

Thanks @jeffkl , can't use the GitHub UI to merge branches anymore.

Merge vs15rtw -> xplat

---

src/Build/BackEnd/Components/Caching/ConfigCache.cs

Add lock in ConfigCache when clearing configurations

---

src/Tasks/Microsoft.Common.CrossTargeting.targets

I just copied and pasted this from [Microsoft.Common.targets](https://github.com/Microsoft/msbuild/blob/xplat/src/Tasks/Microsoft.Common.targets#L129-L141)
Closes #1721
@AndyGerlicher please bar check

Import Directory.Build.targets in Microsoft.Common.CrossTarget.targets

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

File will now be removed on /t:Clean
Closes #1577

Add CoreCompileInputs.cache to FileWrites

---

ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs
ref/netstandard1.3/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs
src/Utilities/ToolLocationHelper.cs
src/XMakeCommandLine/Microsoft.Build.CommonTypes.xsd

Cherry-pick commits to go into VS15.1 branch.

Prep VS15.1 branch

---

dir.targets

Cherry-pick 754c9d1 from xplat

FI to vs15.1: Make LargeAddressAware incremental

---

build/NuGetPackages/Microsoft.Build.Framework.nuspec
build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec
build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec
build/NuGetPackages/Microsoft.Build.nuspec
dir.props

This reverts part of #1682.
Should resolve #1725

Remove nuspec dependencies

---

src/MSBuild/Microsoft.Build.CommonTypes.xsd

Typo: Sufix->Suffix

---

src/MSBuild/XMake.cs

Previously we didn't support replaying logs when /m was specified (we were just ignoring all distributed logger records).
Now we also log into the central logger for each distributed logger record.
We also correctly initialize loggers that implement INodeLogger by passing the CPU count.
After this change replaying a log with /m is now supported.

Support replaying logs with /m.

---

src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs
src/Build/Evaluation/ItemSpec.cs
src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs
src/Build/Evaluation/LazyItemEvaluator.cs
src/Shared/UnitTests/ObjectModelHelpers.cs

Fixes #1359
Details in commit message: https://github.com/cdmihai/msbuild/commit/ae4dba8052d8423a8a57fd08910bc6ef5b7fcb22

Expand metadata properties earlier

---

src/Shared/BuildEnvironmentHelper.cs

Fix typo in BuildEnvironmentHelper

---

cibuild.cmd
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs

Resolves #1748 (detailed investigation and reasoning there), This PR goes with the dummy global property fix.

Add dummy global property for project instance based builds

---

dir.props

Came up in #2004. Easy to do, so why not?

Compile with /deterministic+

---

src/Build.UnitTests/FileLogger_Tests.cs
src/Build/Logging/FileLogger.cs

Making Jeff's wishes come true :)

Fix for MSBuild does not create a directory for the log file (#1684)

---

src/XMakeCommandLine/app.amd64.config

Reverts Microsoft/msbuild#1944

Revert "Update amd64 app.config to find XAML build tasks."

---

src/Tasks.UnitTests/DirectoryBuildProjectImportTestBase.cs
src/Tasks/Microsoft.Common.CrossTargeting.targets
src/Tasks/Microsoft.Common.props
src/Tasks/Microsoft.Common.targets

Implements #1949 
cc @rainersigwald @jeffkl

Add auto-imported Directory.Build.props/.targets to MSBuildAllProjects automatically

---

src/MSBuild/app.config
src/Tasks/Microsoft.Xaml.targets

Port #2001 from 15.2 to master.
This change was rejected for 15.2.

Fix build XamlBuildTask failure on 64-bit MSBuild

---

src/MSBuild/Microsoft.Build.Core.xsd

This will enable IntelliSense autocompletion for this attribute when
editing project files in Visual Studio. Closes #1923.

Simple XSD entry for <Project Sdk="" />

---

src/MSBuild/app.config
src/Tasks/Microsoft.Xaml.targets

Port #2020 to `vs15.3-preview` branch.

Port: Fix build XamlBuildTask failure on 64-bit MSBuild (#2001) (#2020)

---

src/MSBuild/Microsoft.Build.CommonTypes.xsd

This resolves https://github.com/dotnet/project-system/issues/1800

Adding intellisense for the "Title" property, which is used by NuGet Packaging.

---

Samples/TaskUsageLogger/TaskUsageLogger.cs
src/Build.OM.UnitTests/Definition/Project_Tests.cs
src/Build.UnitTests/BackEnd/LoggingService_Tests.cs
src/Build.UnitTests/OpportunisticIntern_Tests.cs
src/Shared/StringBuilderCache.cs
src/Tasks.UnitTests/CreateProperty_Tests.cs

Think this is the last of it. Just took a quick second pass to see what I had accidentally hit "Ignore All" in #2085

Spelling 2: Electric Boogaloo

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs

Prompted by #1932 and https://github.com/Microsoft/msbuild/pull/1933#discussion_r110026336.
The asserts are taken from dev14's behaviour.

Tests for element reference as property function arguments

---

src/Build.UnitTests/ConsoleLogger_Tests.cs
src/Build/Logging/BaseConsoleLogger.cs
src/Build/Logging/ConsoleLogger.cs
src/Build/Logging/FileLogger.cs
src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
src/Build/Logging/SerialConsoleLogger.cs
src/Build/Utilities/Utilities.cs

I did some refactoring and code modernization while working on #2110 but didn't want to include these changes as part of that review. Most of it just R# style cleanup, but I also moved from ArrayList/Hashtable to List<>/Dictionary<>.

Console/File Logger Refactoring

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Cherry-pick #2139 to the vs15.3-preview2 branch. Will need escrow approval.

Find ref asms after ResolveReferences (#2139)

---

src/Shared/Resources/Strings.shared.resx
src/Shared/Traits.cs

Remove escape hatch resource

---

src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs
src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs

Solves #2069 
Works around https://github.com/dotnet/corefx/issues/20609

Replace RemoveAll with Remove

---

src/Shared/Constants.cs
version.json

Bump version to 15.6

---

src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs
src/Build/Construction/ProjectRootElement.cs

Reloading root element from memory keeps initial file

---

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs

Reduce iterations of ShutdownNodesAfterParallelBuild

---

README.md

Badges worked but links didn't. 🤦

Update links under badges to Full name

---

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
src/Build/Evaluation/Evaluator.cs

Caused by 51e8cdc86cb2dec580b5010e2d201a282c14633c which overly caught exceptions that didn't have an InnerException.
Fixes #2228

Fix NullReferenceException in evaluator

---

src/Shared/Constants.cs
version.json

Changing version to match VS release this is expected to ship with.

Version to 15.5

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Evaluation/Expander.cs
src/Build/Evaluation/LazyItemEvaluator.cs
src/Build/Utilities/EngineFileUtilities.cs
src/Shared/Traits.cs

Found these two by looking at low hanging profiler fruits. RPS results claim that they increase a scenario by 19%, and in local tests they improve the evaluation times of a 28 project solution by about 60ms.

Perf improvements

---

src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
src/MSBuild.UnitTests/XMake_Tests.cs
src/Shared/ResourceUtilities.cs
src/Shared/UnitTests/FileUtilities_Tests.cs
src/Shared/UnitTests/TypeLoader_Dependencies_Tests.cs
src/Shared/UnitTests/TypeLoader_Tests.cs
src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
src/Tasks.UnitTests/PortableTasks_Tests.cs
src/UnitTests.Shared/AssemblyResources.cs
src/UnitTests.Shared/Microsoft.Build.UnitTests.Shared.csproj
src/UnitTests.Shared/RunnerUtilities.cs
src/UnitTests.Shared/project.json
src/dirs.proj

Move RunnerUtilities for now and we can move more classes later.

Introduce Microsoft.Build.UnitTests.Shared class library

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build.UnitTests/project.json
src/Build/Evaluation/Expander.cs

Support newlines in property functions

---

src/Shared/NodePacketTranslator.cs

When a CultureInfo is serialized on an MSBuild node (running on a newer .net framework) and sent to the MSBuildTaskHost (running on an older .net framework), the MSBuildTaskHost might not be able to deserialize the CultureInfo, as some culture codes are supported on newer .net framework versions but not on older ones.
Fallback to CultureInfo.CurrentCulture if CultureInfo cannot be instantiated for the culture code sent over from the msbuild node.
Alas, it is quite hard to write a unit test for this. I checked this manually by making BuildParameters default the msbuild culture to something illegal on .net 2.0 ("en-de") and then debugging through the translation code and making sure "en-de" gets defaulted to the current culture.

Fallback culture translation for MSBuildTaskhost

---

src/Build.UnitTests/ConfigureableForwardingLogger_Tests.cs
src/Build.UnitTests/ConsoleLogger_Tests.cs

Improve ConsoleLoggerTest and ConfigureableForwardingLogger_Tests

---

build/NuGetPackages/CreateNuGetPackages.proj
build/NuGetPackages/Microsoft.Build.Framework.nuspec
build/NuGetPackages/Microsoft.Build.Runtime.nuspec
build/NuGetPackages/Microsoft.Build.Tasks.Core.nuspec
build/NuGetPackages/Microsoft.Build.Utilities.Core.nuspec
build/NuGetPackages/Microsoft.Build.nuspec
dir.props
setup/Microsoft.Build.swixproj
setup/files.swr

The packages msbuild ships under should contain the third party notice.

Add third party notice in packages

---

netci.groovy

Use latest-or-auto

---

targets/BootStrapMSBuild.proj

Copy everything under MSBuildExtensionsPath\Microsoft. One of the
targets there has a task which was not being copied previously.

Fix bootstrap build.

---

src/Build.UnitTests/Definition/ToolsetConfigurationReaderTestHelper.cs
src/Build.UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Microsoft.Build.csproj
src/Shared/FileUtilities.cs
src/Shared/StringExtensions.cs
src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
src/Utilities.UnitTests/StringExtensions_Tests.cs

Fallback properties are case insensitive

---

setup/MsBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
setup/MsBuild.Engine.Corext/TestBuild.cmd

I based the initial package on my local output directory, but it turns out it was in a bad state. Respecified the dependencies against a clean build. I also twiked the nuspec to make it easier to consume from our VSTS build definition.

Fixup package

---

src/Build/Evaluation/IntrinsicFunctions.cs

Edits to the XML documentation comments for GetPathOfFileAbove and GetDirectoryNameOfFileAbove for consistency, clarity and typo reduction ;)

Clarify documentation of Get...OfFileAbove methods

---

src/Shared/UnitTests/FileUtilities_Tests.cs

Added test cases for #2166

---

src/Build.UnitTests/BinaryLogger_Tests.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs

Fix BinaryLogger not creating directories when it doesn't exist

---

src/Build/Evaluation/Evaluator.cs
src/Build/Instance/ProjectItemInstance.cs

We already know how many elements these collections are going to contain, size them accordingly.
tag @pilchie

Initialize collections with up-front counts

---

src/Shared/AssemblyUtilities.cs
src/Tasks/CultureInfoCache.cs

Use reflection to find CultureInfo.GetCultures

---

src/Build/Instance/ProjectInstance.cs

Fixes: https://github.com/Microsoft/msbuild/issues/2283
This reduces 4 allocations to 1 (the yield enumerable/enumerator).

Reduce allocations in GetItemsByItemTypeAndEvaluatedInclude

---

src/Build.UnitTests/Evaluation/ItemSpec_Tests.cs
src/Build/Definition/Project.cs
src/Build/Evaluation/ItemSpec.cs
src/Build/Evaluation/LazyItemEvaluator.cs

Fixes: #2551
This was allocating up to 5.5% of allocations:

Replace project path with directory

---

src/Build/Evaluation/ItemSpec.cs
src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs

This includes: https://github.com/Microsoft/msbuild/pull/2600.
Fixes part of https://github.com/Microsoft/msbuild/issues/2599.

Remove boxing of enumerators

---

src/Build/Evaluation/Expander.cs
src/Build/Evaluation/ItemSpec.cs

This was from 0.5 -> 1% allocations.

Replace Tuple -> struct Pair

---

src/Build.OM.UnitTests/Definition/Project_Tests.cs
src/Build.UnitTests/Evaluation/ItemSpec_Tests.cs

@davkean found and fixed an issue in #2597 where MSBuildGlob.Parse received files instead of directories. Added some tests for those scenarios which would have failed before.

Add tests for matching absolute files

---

ref/net46/Microsoft.Build/Microsoft.Build.cs
ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs
src/Build.UnitTests/Definition/Project_Internal_Tests.cs
src/Build/Definition/Project.cs
src/Build/Definition/ProjectLoadSettings.cs
src/Build/Resources/Strings.resx
src/Shared/Traits.cs

Option to not evaluate elements with false conditions (#2626)

---

dir.props
documentation/ProjectReference-Protocol.md
src/.nuget/project.json
src/Tasks/Microsoft.Common.CrossTargeting.targets
src/Tasks/Microsoft.Common.CurrentVersion.targets
targets/BootStrapMSBuild.proj
targets/bootstrapDependencies/Core/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets

Double evaluation fix merged into VS15.5.

Merge master -> 15.5

---

ref/net46/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
ref/net46/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs
ref/netstandard1.3/Microsoft.Build.Tasks.Core/Microsoft.Build.Tasks.Core.cs
ref/netstandard1.3/Microsoft.Build.Utilities.Core/Microsoft.Build.Utilities.Core.cs
src/Shared/FrameworkLocationHelper.cs
src/Tasks/GetFrameworkPath.cs
src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
src/Utilities/ToolLocationHelper.cs

Following the pattern from #1728

Add support for .NET SDK 4.7.1

---

src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
src/Build/Evaluation/LazyItemEvaluator.cs

Removes unneeded Func and LINQ allocations.

Reduce allocations from evaluator

---

src/Build.UnitTests/Definition/Project_Internal_Tests.cs
src/Build/Definition/Project.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Evaluation/IEvaluatorData.cs
src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs
src/Build/Instance/ProjectInstance.cs

This scopes down the effect of the flag introduced in #2629.

Restrict effect of DoNotEvaluateElementsWithFalseCondition

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
src/Shared/XmlUtilities.cs

This went into master on accident. Porting to vs15.5.

Port #2662 to vs15.5

---

src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Shared/UnitTests/TestEnvironment.cs

Cherry pick https://github.com/Microsoft/msbuild/commit/14dabf5953195c8fe1b0112ccd5025f5c7db190a into vs15.5

Cherry pick into 15.5

---

PublishToBlob.proj
src/.nuget/project.json

Update feed tasks version

---

build/Versions.props
src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj

* Update to use NuGet package
* Update sournces feed to use Roslyn nightly

Fix reference to Microsoft.Build.Tasks.CodeAnalysis

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

adding CollectReferencedNuGetPackages so consumers that partially import VS targets are not broken.
VS Bug [526825](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/526825)

Add collect referenced nuget packages target

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Adding CollectReferencedNuGetPackages so consumers that partially import VS targets are not broken.

Port #2764: Add collect referenced nuget packages target

---

src/Build/Evaluation/Expander.cs
src/Build/Evaluation/IntrinsicFunctions.cs
src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs
src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
src/Tasks.UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs

This allows block registry request on Windows for better toolset isolation.

Fix build when FEATURE_WIN32_REGISTRY disabled.

---

src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs

This was missed in #2777
Closes #2789
Not bumping the version, we didn't even do an official build between then and now.

Serialize TargetName in TargetSkippedEventArgs

---

ref/net46/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
ref/netstandard1.3/Microsoft.Build.Framework/Microsoft.Build.Framework.cs
src/Build.OM.UnitTests/Instance/ProjectItemInstance_Tests.cs
src/Build.UnitTests/EvaluationProfiler_Tests.cs
src/Build/Evaluation/Evaluator.cs
src/Framework/Profiler/EvaluationLocation.cs

/cc @KirillOsenkov 
Closes #2785

Fix typo 'defintion'

---

src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Evaluation/Profiler/EvaluationProfiler.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
src/Framework/Profiler/EvaluationLocation.cs
src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
src/MSBuild/XMake.cs

Quick stab at adding this. @KirillOsenkov  look right?
FYI @smera

Add profile data to binary log file

---

dir.props

Quote $(PackagesDir) in DnuRestoreCommand

---

src/Tasks/ManifestUtil/CngLightup.cs
src/Tasks/ManifestUtil/SecurityUtil.cs
src/Tasks/ManifestUtil/mansign2.cs

Add support for signing manifest file with CNG certificate in ClickOnce tooling.

adding CNG support for ClickOnce tooling

---

src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs

Change exception filtering for FileNotFoundException
Remove two try...catch statements in favor of the inner one.  If no SDKs are found, an InvalidProjectException is thrown anyway.
Follow-up items from #2850

Minor improvements to SDK resolver execution

---

src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs

Also fix issue with LogWarning trying to find a resource if you pass in String.Empty

Fix issue in SdkResolverLoader when logging a warning

---

src/MSBuild.sln
src/NuGetSdkResolver.UnitTests/GlobalJsonReader_Tests.cs
src/NuGetSdkResolver.UnitTests/MockSdkLogger.cs
src/NuGetSdkResolver.UnitTests/MockSdkResolverContext.cs
src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj
src/NuGetSdkResolver.UnitTests/NuGetSdkLogger_Tests.cs
src/NuGetSdkResolver.UnitTests/NuGetSdkResolver_Tests.cs
src/NuGetSdkResolver.UnitTests/project.json
src/NuGetSdkResolver/NuGet.MSBuildSdkResolver.csproj
src/NuGetSdkResolver/Properties/AssemblyInfo.cs
src/NuGetSdkResolver/project.json
src/dirs.proj
targets/DeployDependencies.proj

Unit tests for GlobalJsonReader, NuGetSdkLogger, and NuGetSdkResolver

Add NuGet.MSBuildSdkResolver.UnitTests assembly

---

ref/net46/Microsoft.Build/Microsoft.Build.cs
ref/netstandard1.3/Microsoft.Build/Microsoft.Build.cs
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/BuildManager/BuildRequestData.cs
src/Build/BackEnd/BuildManager/RequestedProjectState.cs
src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
src/Build/BackEnd/Shared/BuildRequest.cs
src/Build/BackEnd/Shared/BuildResult.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Microsoft.Build.csproj

First stab at a design for #2640.
TODO:

Request explicit properties and items in an API build

---

setup/MsBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec

Remove Cryptography.Algorithms from CoreXT pkg

---

Directory.Build.props
Directory.Build.targets
src/Build.UnitTests/BackEnd/RequestBuilder_Tests.cs
src/Directory.BeforeCommon.targets
src/Directory.Build.props
src/Directory.Build.targets
src/ExcludeAPIList.txt
src/Package/MSBuild.Engine.Corext/MSBuild.Engine.Corext.csproj
src/Package/ReferenceAssemblies/Directory.Build.targets
src/Shared/UnitTests/TestAssemblyInfo.cs
src/Shared/UnitTests/TestEnvironment.cs
src/Xunit.NetCore.Extensions/AssemblyFixtureSupport/AssemblyFixtureAttribute.cs
src/Xunit.NetCore.Extensions/AssemblyFixtureSupport/XunitTestAssemblyRunnerWithAssemblyFixture.cs
src/Xunit.NetCore.Extensions/AssemblyFixtureSupport/XunitTestClassRunnerWithAssemblyFixture.cs
src/Xunit.NetCore.Extensions/AssemblyFixtureSupport/XunitTestCollectionRunnerWithAssemblyFixture.cs
src/Xunit.NetCore.Extensions/AssemblyFixtureSupport/XunitTestMethodRunnerWithAssemblyFixture.cs

- Fix Windows build when not called from build script
- Embed interop types
- Generate documentation files, include them in NuGet packages

Fix Windows build, embed interop types, generate documentation files

---

netci.groovy

Use the environment variable, based on the suggestion from https://github.com/Microsoft/msbuild/pull/2938#issuecomment-362132587

Stronger fix for VsDevCmd

---

README.md
build/Versions.props
src/Directory.Build.targets
src/MSBuild/MSBuild.csproj
src/MSBuildTaskHost/MSBuildTaskHost.csproj

Package includes a managed assembly that sets the appropriate flag
https://github.com/KirillOsenkov/LargeAddressAware

Use LargeAddressAware package instead of editbin.exe

---

netci.groovy

This reverts commit 3ae111b0ecd8beb0c51a4e0d3fe0b34e72d6d9ae.

Revert "Disable macOS CI (#3053)"

---

src/Directory.BeforeCommon.targets

Seems to cause issues on Mac (node crash).

Disable FEATURE_APM on Core

---

documentation/wiki/Binary-Log.md
documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
documentation/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild.md
documentation/wiki/Contributing-Code.md
documentation/wiki/Home.md
documentation/wiki/Interactions-with-the-internal-repository.md
documentation/wiki/Localization.md
documentation/wiki/MSBuild-Resources.md
documentation/wiki/MSBuild-Tips-&-Tricks.md
documentation/wiki/Microsoft.Build.Framework.md
documentation/wiki/Rebuilding-when-nothing-changed.md
documentation/wiki/ResolveAssemblyReference.md
documentation/wiki/Roadmap.md
documentation/wiki/Something's-wrong-in-my-build.md
documentation/wiki/Target-Maps.md

This way, we can accept PRs for it.
Related to #3023.

Relocate wiki to the main repo

---

build/SignToolData.json
src/Directory.Build.props

I verified package layout is correct for Microsoft.Build.Runtime package

Target netcoreapp2.0 and netcoreapp2.1 for MSBuild.exe

---

build/Versions.props

Heard the older versions have an issue with VS 15.6.

Update Nerdbank.GitVersioning version

---

dir.props
src/.nuget/project.json
src/NuGetSdkResolver.UnitTests/project.json
src/NuGetSdkResolver/project.json

Version bump with Visual Studio 15.6.3.

Update NuGet to 4.6.1-rtm-5019

---

build/Versions.props
src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
src/NuGetSdkResolver/NuGet.MSBuildSdkResolver.csproj

This bumps the assembly version.

Update NuGet to 4.7.0-preview3.5039

---

src/MSBuild.UnitTests/XMake_Tests.cs
src/Samples/PortableTask/portableTaskTest.proj
src/Tasks.UnitTests/PortableTasks_Tests.cs
src/Tasks.UnitTests/RegressionTests.cs
src/UnitTests.Shared/RunnerUtilities.cs

Some improvements to tests that I made while investigating failures for node reuse.

Test diagnosability improvements

---

ref/Microsoft.Build/net/Microsoft.Build.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/BuildManager/BuildParameters.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BackEnd/Node/InProcNode.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Build/Construction/ProjectImportElement.cs
src/Build/Definition/Project.cs
src/Build/Definition/ProjectCollection.cs
src/Build/Instance/ProjectInstance.cs
src/Directory.BeforeCommon.targets
src/MSBuild/OutOfProcTaskHostNode.cs

Some minor changes while reading through code for another PR.

Minor code readability/style refactor

---

dir.props
src/.nuget/project.json
src/NuGetSdkResolver.UnitTests/project.json
src/NuGetSdkResolver/project.json

NuGet is changing assembly version in 15.6.5, so we need to update again.

Update NuGet to 4.6.2-rtm-5055

---

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs

Previously, node reuse was part of the handshake between nodes but two
MSBuild process cones started at roughly the same time could steal each
other's newly-created processes:
* MSBuild A would start a process with `/nr:false`
* MSBuild A' would start and wait for a connection
* MSBuild B would look for live nodes that accepted its handshake
* MSBuild B would connect to and handshake with MSBuild A'
* MSBuild A would try to connect to MSBuild A', fail, and start another
new process.
Prevent this by only attempting to connect to processes we started when
using `/nr:false`. Fixes #3140.
The only change is wrapping the formerly `#if`ed connect-to-idle-node code with an additional runtime check. Whitespace makes it look bigger.

Don't steal nodes when not reusing nodes

---

src/Build/BackEnd/BuildManager/BuildParameters.cs
src/MSBuild/XMake.cs

Default node reuse to true only on Windows

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
src/Build/Construction/Solution/ProjectInSolution.cs
src/Build/Construction/Solution/SolutionFile.cs

Detect shared projects when parsing solution files

---

src/Package/MSBuild.Engine.Corext/.readme.txt
src/Package/MSBuild.Engine.Corext/README.md

Obey GitHub format so that the readme is [autodiscovered](https://github.com/rainersigwald/msbuild/tree/corext-readme/src/Package/MSBuild.Engine.Corext), and make it
slightly more descriptive.

Update CoreXT package readme

---

src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec

Rename occurred here: https://github.com/Microsoft/msbuild/pull/3198
PR build failed: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/innerloop_Windows_NT_Full_prtest/343/consoleFull#181472954279494335-f7bd-47d0-8771-8661e00c2db2
But we merged anyway :(

Update MsBuild.Engine.Corext.nuspec reference to README.md

---

netci.groovy

Add sourcebuild rhel CI jobs

---

src/Tasks/XmlPoke.cs

Code side of MicrosoftDocs/visualstudio-docs#858.

📝 XmlPoke.Value doc-comment fix

---

netci.groovy

See https://github.com/Microsoft/msbuild/issues/3265

Disable RHEL7.2 job

---

src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs

Add threading hint that RequestHandlerPumpProc is long running

---

ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
src/Shared/FrameworkLocationHelper.cs
src/Tasks/GetFrameworkPath.cs
src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
src/Utilities/ToolLocationHelper.cs

Support .NET Framework 4.7.2

---

src/MSBuild/XMake.cs

Display informational version

---

build/build.sh

.. as that directory is not used for other builds.

build.sh: Check for packages count if $pack or $dotnetBuildFromSource

---

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/BuildManager/BuildSubmission.cs
src/Shared/UnitTests/ObjectModelHelpers.cs

Details in second commit message.

Prevent build hang on identical submissions

---

build/Versions.props
netci.groovy
src/Tasks.UnitTests/Exec_Tests.cs

Hopefully the new CLI contains this fix: https://github.com/dotnet/corefx/pull/29512
Which should make our RHEL job work.

Bump cli version

---

README.md
build/Versions.props

Update package refs to 2.1.0 versions.

.NET Core 2.1 RTM

---

netci.groovy

Not sure what is wrong with Ubuntu 14.04 it hasn't been working lately and unsure of the value add of multiple versions.
Disabling Mono pending #3289

Disable failing Ubuntu 14.04 and Mono CI

---

build/build.ps1

Set toolsetdir to env var if building on source-build

---

src/Build.UnitTests/BackEnd/BatchingEngine_Tests.cs
src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs
src/Build.UnitTests/BackEnd/Lookup_Tests.cs
src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs
src/Build.UnitTests/BackEnd/TargetUpToDateChecker_Tests.cs
src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/Lookup.cs
src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
src/Build/Definition/Project.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Instance/ProjectInstance.cs

Remove some more MSBuild debugger code

---

src/Directory.BeforeCommon.targets

Closer to actual. With the Collections.Immutable change this drift might be significant for a few days.

Use IBC data from d15.8stg

---

src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
src/Build/Evaluation/Context/EvaluationContext.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635449

Fix issue where a previously used isolated context gets reused again

---

ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs
src/Build/Construction/Solution/ProjectInSolution.cs
src/Build/Evaluation/Conditionals/FunctionCallExpressionNode.cs
src/Build/Evaluation/Conditionals/Parser.cs
src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks/AppConfig/DependentAssembly.cs
src/Tasks/AppConfig/RuntimeSection.cs
src/Tasks/AssemblyDependency/FrameworkPathResolver.cs
src/Tasks/AssemblyDependency/InstalledAssemblies.cs
src/Tasks/AssemblyDependency/Reference.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
src/Tasks/CallTarget.cs
src/Tasks/CodeTaskFactory.cs
src/Tasks/MSBuild.cs
src/Tasks/ManifestUtil/CompatibleFrameworkCollection.cs
src/Tasks/ManifestUtil/DeployManifest.cs
src/Tasks/RedistList.cs
src/Tasks/ResolveManifestFiles.cs
src/Tasks/ResolveSDKReference.cs
src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
src/Tasks/SystemState.cs
src/Utilities/TrackedDependencies/CanonicalTrackedFilesHelper.cs
src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs

- Removed a few more ArrayLists.
- Converted some internal-facing properties from array to List<T> and removed related unneeded List<T>.ToArray() calls.
- For #3320

Allocation reductions and some .NET 1 data structure removal

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.en.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Shared/FileUtilities.cs
src/Shared/UnitTests/ObjectModelHelpers.cs

Graceful error on metadata expansion failure

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Collections/CopyOnWritePropertyDictionary.cs

_(This is my first PR in a microsoft repository (or any popular repository for that matter)... so any feedback would be greatly appreciated.)_
This PR attempts to fix #2870 
Note: I wasn't sure were exactly to put the tests. I hope i haven't missed it quite as much 😄

Unqualified metadata case sensitivity fix

---

src/Directory.BeforeCommon.targets

Based on https://github.com/Microsoft/msbuild/pull/3519#discussion_r202882567 :)

Point IBCMergeBranch to master

---

.vsts-dotnet-ci.yml
.vsts-dotnet.yml
build/SetMicrobuildVersion/version.json
version.json

I think the versioning changes I had to make here break the official build, so I need to run an official build before this is ready for review.

Adopt VSTS CI builds (in parallel to existing Jenkins)

---

build/build.ps1
ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build/BackEnd/Shared/BuildResult.cs
src/Build/BackEnd/Shared/IBuildResults.cs
version.json

FI from 15.8 and a version bump.

15.9 branch updates

---

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs

Primary contents is #3554 to master, but also includes a vbump accept-master.

RI vs15.9stg

---

src/Build.UnitTests/ConsoleLogger_Tests.cs

This time, I'm going to be very sure that there are many lines in
the commit message.
So that it's a good test case.
Right?

Normalize newlines II: Normalize harder

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.en.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Expand help text for restore command line parameter

---

src/Utilities/ToolTask.cs

Log full exception string during ToolTask exceptions

---

src/Directory.BeforeCommon.targets
src/Shared/FileMatcher.cs
src/Shared/FileUtilities.cs
src/Shared/NativeMethodsShared.cs
src/Tasks/FileState.cs

There are a number of factors within MaybeAdjustFilePath() (regex, default StringComparison, short circuit placement) causing huge impacts on build times on Unix.
Here are a few sample performance summaries from identical VMs on the same machine showing the relative differences, using the WebLarge solution [here](https://github.com/mikeharder/dotnet-cli-perf/tree/master/scenarios/web/large/core) and incremental build. Approx. 18 seconds was shaved off the Linux build time for this one.
There's some more info for this method in #67.
Windows:
```
Target Performance Summary:
0 ms  ValidateProjects                           1 calls
0 ms  GenerateUserSecretsAttribute               3 calls
0 ms  _CheckForUnsupportedSelfContained          1 calls
0 ms  GenerateBindingRedirectsUpdateAppConfig …
```

Improve build time discrepancy between Windows and Unix

---

src/Tasks/system.design/stronglytypedresourcebuilder.cs

Introduced with conversion to generics

Fix regression in StronglyTypedResourceBuilder

---

build/Packages.props
src/Samples/Directory.Build.targets

This version has an updated copy of LibGit2Sharp that supports Ubuntu
18.04 and other newer distros.
It builds on my Ubuntu 18.04 machine.

Nerdbank.GitVersioning 2.2.13

---

build.cmd
build/Packages.props
build/SignToolData.json
build/Versions.props
build/build.ps1
build/build.sh
build/cibuild.cmd
build/cibuild.sh
netci.groovy
src/Build/Construction/ProjectRootElement.cs
src/Build/Evaluation/ProjectRootElementCache.cs
src/Build/Microsoft.Build.csproj
src/Directory.Build.props
src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
src/Package/MSBuild.VSSetup/files.swr
src/Shared/Modifiers.cs
src/Shared/UnitTests/FileUtilities_Tests.cs
src/Tasks/DependencyFile.cs
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj

Extracted common changes from 2 branches that I'm working on.
Tested the changes by aliasing the IO types in FileUtilities. (actual change in separate branch)

Add Microsoft.IO.Redist and System.Memory package

---

src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
src/Shared/FileMatcher.cs
src/Shared/FileUtilities.cs
src/Shared/UnitTests/FileUtilities_Tests.cs
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj

Enumeration key disambiguates out of cone relative globs

---

documentation/specs/static-graph.md

After discussing with the team, we decided to make the spec a file in the repo so that we could easily track changes, propose changes, etc.
Previously it was in this issue and this is just a c&p from there: #3696

Static graph spec

---

build/Packages.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Used the dll versions from what gets into our vsix.

Add binding redirects for redistributed dlls

---

src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphNode.cs
src/Build/Microsoft.Build.csproj

Initial ProjectGraph interfaces/stubs

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build/BackEnd/BuildManager/BuildParameters.cs
src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
src/MSBuild/CommandLineSwitches.cs
src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.en.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs

Add /isolateProjects argument

---

src/Tasks/Microsoft.Common.CurrentVersion.targets
src/Tasks/ResolveManifestFiles.cs

* ClickOnce: filter references before manifest generation (#3732)

RI 15.8 -> 15.9

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphNode.cs
src/MSBuild/XMake.cs

Build a graph containing a single node

---

src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

LOC CHECKIN | msbuild-vs15.9 | 20180920

---

src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/Microsoft.Build.CommonTypes.xsd
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

Only conflict was the IBC merge branch.

RI 15.9 -> master

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphNode.cs
src/MSBuild/XMake.cs
src/Shared/UnitTests/EngineTestEnvironment.cs

Traverse project graph to construct target list for each project

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/MSBuild.cs
src/Build/BackEnd/Shared/ConfigurationMetadata.cs
src/Build/Collections/PropertyDictionary.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphNode.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.en.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs

Account for global properties in graph nodes

---

version.json

To avoid conflicts with `master`

Increment version in exp/net472 branch

---

src/Build/Graph/ProjectGraph.cs
src/Tasks/Microsoft.Common.CurrentVersion.targets
src/Tasks/Microsoft.Common.props

Define ProjectReferenceTargets for Build, Clean, and Rebuild

---

src/MSBuild/XMake.cs

Closes: #3684
This won't work until #3800 is completed. Locally I tested this change with that change also applied.
Tested using a build graph of 6 projects in this zip file. The binlog inside also shows correct build ordering for a graph (each project is top-level):
[GraphBuildTest.zip](https://github.com/Microsoft/msbuild/files/2421914/GraphBuildTest.zip)

Build an entire project graph

---

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/BackEnd/Shared/CircularDependencyException.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.en.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Detect a cycle during graph creation and print all the projects that are involved in a cycle.

Detect cycles in a graph

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphEntryPoint.cs
src/Build/Microsoft.Build.csproj
src/MSBuild/XMake.cs

Add support for multiple entry points in the ProjectGraph

---

documentation/specs/static-graph.md

Mostly this is just reorganization and clarification based on the recent internal architecture review.
Notably, graph builds and isolated builds are described separately since they're really two separate (but still related) features. It also just helps for clarity to describe graph builds in full first before introducing the complications of isolated builds.

Update the static graph spec based on internal architecture review

---

documentation/specs/static-graph.md

Addressing feedback from #3841 that came in after it was merged

More graph spec updates based on feedback

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphNode.cs

Add support for referencing projects and graph roots

---

documentation/specs/static-graph.md

Add I/O tracking to the static graph spec

Add I/O tracking to the static graph spec

---

documentation/evaluation-profiling.md

I needed to use this for the first time in a long while today and found the docs slightly unclear.

Profiler doc elaboration

---

.vsts-dotnet-ci.yml
src/Directory.Build.props

To allow better artifact preservation in our CI

Change test output to artifacts/log/TestResults

---

.vsts-dotnet.yml
build/Internal/Directory.Build.props
build/Internal/Directory.Build.targets
build/Internal/Toolsets.csproj
build/Packages.props
src/Build/Microsoft.Build.csproj
src/Directory.BeforeCommon.targets
src/Directory.Build.props
src/Directory.Build.targets
src/Framework/Microsoft.Build.Framework.csproj
src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj

Moving our optimization process from MicroBuild to RepoTools implementation. This probably only makes any sense to @rainersigwald and @tmat

Update IBC data consumption process

---

version.json

Bump version in master

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Add DefineConstants to incremental compilation inputs

---

src/Tasks.UnitTests/WriteCodeFragment_Tests.cs
src/Tasks/WriteCodeFragment.cs

Fix WriteCodeFragment removing duplicate arguments

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.en.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs

Forgot to add command line help information.

Help information for input/output cache switches

---

src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
src/Shared/FileMatcher.cs
src/Shared/UnitTests/ObjectModelHelpers.cs

Glob cache key disambiguates a prepended project directory

---

.vsts-dotnet.yml
eng/Build.props
eng/CIBuild.cmd

This addresses @rainersigwald last comments on the move to arcade PR.
@dsplaisted could you review please?

Turn off tests on official builds

---

.vsts-dotnet.yml

@livarcocc 
I assume .vsts-dotnet.yml is only for internal builds.
Validation build is in progress - https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2314166
I had to create a different build definition because I didn't have permissions to push to Microsoft/msbuild (I could only push to my fork), as a result, I wasn't able to validate that I haven't broken signing but I think it should be fine.

Publish darc

---

README.md
documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md

I spent a good 20 minutes wondering why Christian's changes in #4055 weren't reducing overbuild. Figured I would update the docs when I found out that changed :).

Update docs for bootstrap build changes

---

src/Tasks.UnitTests/ReadLinesFromFile_Tests.cs
src/Tasks.UnitTests/WriteLinesToFile_Tests.cs
src/Tasks/FileIO/WriteLinesToFile.cs

Add DirectoryCreate to ensure the target directory exists

---

src/Deprecated/README.md

Add text to discourage changes under the `Deprecated` folder, since it's in maintenance don't-touch-unless-necessary mode.

Add README to src/Deprecated

---

.vsts-dotnet-ci.yml
eng/Version.Details.xml
eng/Versions.props
eng/cibuild_bootstrapped_msbuild.sh
eng/common/PublishBuildAssets.cmd
eng/common/build.ps1
eng/common/build.sh
eng/common/cross/x86/sources.list.bionic
eng/common/cross/x86/sources.list.trusty
eng/common/cross/x86/sources.list.vivid
eng/common/cross/x86/sources.list.wily
eng/common/cross/x86/sources.list.xenial
eng/common/darc-init.ps1
eng/common/helixpublish.proj
eng/common/sdk-task.ps1
eng/common/templates/phases/base.yml
eng/common/templates/phases/publish-build-assets.yml
eng/common/templates/steps/send-to-helix.yml
eng/common/tools.ps1
eng/common/tools.sh
global.json
src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj

This is intended to replace #4046. I squashed all the darc-driven updates, cherry-picked @livarcocc's changes, and made a few new changes.

Manual arcade update

---

eng/cibuild_bootstrapped_msbuild.ps1

Port f38903cf7 to the Windows Powershell build script.

Disable debugger hang on Core/Windows, too

---

eng/config/OptProf.json

The ones I ended up checking in where actually the unsupported ones.

Changing the test set once again

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs

Added all functions from #3051

Added more property function fastpaths

---

src/Tasks/AssemblyDependency/AssemblyInformation.cs

Fix https://github.com/Microsoft/msbuild/issues/3466 as explained there.
@KirillOsenkov

Fix extra null in version string in log

---

src/Tasks.UnitTests/Copy_Tests.cs

Pulling this change out from another PR. Does not appear to solve the flakiness, but at least it's a step forward :)

Move test to TestEnvironment

---

src/MSBuild/Microsoft.Build.CommonTypes.xsd
src/Tasks/FileIO/WriteLinesToFile.cs

WriteLinesToFile Task documentation update

---

.vsts-dotnet.yml
eng/Version.Details.xml
eng/Versions.props
src/Build.UnitTests/BackEnd/MSBuild_Tests.cs
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Directory.Build.targets
src/Shared/NativeMethodsShared.cs
src/Shared/UnitTests/FileUtilities_Tests.cs
src/Tasks.UnitTests/FileStateTests.cs
src/Tasks.UnitTests/MSBuild_Tests.cs

Updating the version of SignTool to one that properly strong name signs amd64 bits.

Updating the version of SignTool

---

src/Build/Instance/HostServices.cs
src/Build/Instance/IRunningObjectTableWrapper.cs
src/Build/Instance/RunningObjectTable.cs

As a result to wait for the separate thread. It need to be async
Also make ROT init Lazy

Change to MTA when creating ROT

---

src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Fix a set of translations that were accidentally reset in
https://github.com/Microsoft/msbuild/pull/4349.

Fix translations

---

version.json

I think it's time to switch to RTM branding. Ok with you @Pilchie @livarcocc?

vs16.1 RTM versioning

---

src/Shared/FileMatcher.cs
src/Shared/UnitTests/FileMatcher_Tests.cs

Don't match directories with prefix matches in globbed exclude patterns

---

documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md
documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
documentation/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild.md
documentation/wiki/Something's-wrong-in-my-build.md

Added documentation for potential contributors who develop on release versions of visual studio while MSBuild is on a preview version of the .NET Core SDK.

Updated "something's wrong in my build" wiki page

---

documentation/wiki/Binary-Log.md
documentation/wiki/Home.md
documentation/wiki/Providing-Binary-Logs.md

Move the information from [my gist](https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b) to a better home.

Add documentation for providing binary logs

---

src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
src/Tasks/GenerateResource.cs
src/Tasks/ResourceHandling/BinaryFormatterByteArrayResource.cs
src/Tasks/ResourceHandling/FileStreamResource.cs
src/Tasks/ResourceHandling/PreserializedResourceWriterRequiredException.cs
src/Tasks/ResourceHandling/TypeConverterByteArrayResource.cs
src/Tasks/ResourceHandling/TypeConverterStringResource.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.en.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Allow string resources without property or S.R.Extensions ref

---

src/MSBuild/Microsoft.Build.CommonTypes.xsd

Added many missing properties to CommonTypes as well as attributes to PackageReference and a new item for FrameworkReference.
Fixes https://github.com/microsoft/msbuild/issues/3979
cc @DamianEdwards

Added many missing properties to CommonTypes

---

src/Tasks.UnitTests/Exec_Tests.cs

While doing something entirely unrelated, I asked myself "does the `Exec` task fail if it times out, even if `IgnoreExitCode == true`? It does, so I wrote a test to immortalize the current behavior.

Test that timed-out Exec fails regardless of IgnoreExitCode

---

src/Directory.Build.props

Dogfooding a new Roslyn feature in this repo.

Enable compiler support for editorconfig

---

src/Build/Evaluation/Expander.cs

Using spans in ExtractPropertyFunction helps avoid one unnecessary substring call. This saves a whopping ~0.2% allocations. A small win but a win nonetheless.

Bringing Spans Into ExtractPropertyFunction

---

.vsts-dotnet.yml

This is a planned change to onboard to yaml stages.
Infra-structure change.
No.
Low

Yaml stages

---

.vsts-dotnet-ci.yml

This is being used on other repos as well.
Currently, builds are failing because of this.
cc @chcosta

Setting continueOnError: true on publish tasks

---

.vsts-dotnet.yml

see https://github.com/dotnet/arcade/blame/2401b8ba8c5d95168bf7083ec99af6f2d994844a/Documentation/CorePackages/YamlStagesPublishing.md#L61-L70
Marking WIP because we want to wait on this until after preview9/preview3.

Set PublishUsingPipelines when publishing

---

ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs
ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs
ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
src/Shared/FrameworkLocationHelper.cs
src/Tasks/GetFrameworkPath.cs
src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
src/Utilities/ToolLocationHelper.cs

Updating .NET SDK to version 4.8.

Exp/version 4.8

---

eng/common/templates/post-build/channels/netcore-dev-30.yml
eng/common/templates/post-build/channels/netcore-dev-31.yml
eng/common/templates/post-build/channels/netcore-dev-5.yml
eng/common/templates/post-build/channels/netcore-internal-30.yml
eng/common/templates/post-build/channels/netcore-release-30.yml
eng/common/templates/post-build/channels/netcore-release-31.yml
eng/common/templates/post-build/channels/netcore-tools-latest.yml
eng/common/templates/post-build/channels/public-validation-release.yml

Ports #4733 to target `master`

Work around cross-account publishing to Azure Artifacts

---

src/Build.UnitTests/FileLogger_Tests.cs
src/Build/Logging/FileLogger.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.en.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

FileLogger writes current logging verbosity

---

src/Build.UnitTests/BackEnd/BuildRequestEngine_Tests.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs

Done so the project can meet the project style guidelines. Also makes code easier to read.

Simplify delegate invokation (Auto-fix by IDE)

---

eng/Versions.props

I think we need to take this before #4760

Branding for (potential) 16.3.1 servicing

---

eng/Versions.props

No more known work for the next servicing release.

RTM branding for 16.3.1

---

src/MSBuild/app.amd64.config

Found by @dfederm (pointed out offline).
This mirrors #4487 to the amd64 app.config.

Point to 4.8 SDK in amd64 app.config as well

---

src/Build.UnitTests/Graph/ParallelWorkSet_Tests.cs
src/Build/Graph/GraphBuilder.cs
src/Build/Graph/ParallelWorkSet.cs

- Address PR comments from #4483 
- Remove redundant code
- Add unit tests
- Fix potential thread hangs

[Static Graph] Fix hangs and redundant code in ParallelWorkSet

---

src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs

The documentation for ConcurrentDictionary<T>.GetOrAdd() states:
> If you call GetOrAdd simultaneously on different threads, valueFactory may be called multiple times, but only one key/value pair will be added to the dictionary.
In all of my testing, a particular SDK was never resolved more than once so I didn't think we had a problem.  However, on an NGen'd MSBuild, I noticed that an SDK was being resolved multiple times.  This is because the `GetOrAdd()` method does not guarantee that a method is only called once.  Instead, it guarantees that if multiple threads call the method simultaneously they will all receive the same return value.
So the fix is to return a `Lazy<T>` instead.  This means that multiple threads could new up multiple instances of Lazy<T> but all threads will receive …

Fix CachingSdkResolverService concurrency.

---

ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
src/Utilities/ToolTask.cs

Added overridable method after proc.Start()

---

eng/common/post-build/setup-maestro-vars.ps1

This was deleted in #4827 but that seems to be failing builds.

Restore setup-maestro-vars.ps1

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Remove Dev10 quirks in targets

---

src/Build/Evaluation/Evaluator.cs

Lazy should be the default. This removes the non-lazy version as an option.
Fixes #975.

Remove non-lazy item evaluation

---

src/Tasks.UnitTests/CodeTaskFactoryTests.cs
src/Tasks/CodeTaskFactory.cs
src/Tasks/DownloadFile.cs
src/Tasks/FileIO/GetFileHash.cs
src/Tasks/GenerateResource.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.en.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
src/Tasks/Unzip.cs
src/Tasks/XamlTaskFactory/XamlTaskFactory.cs
src/Tasks/ZipDirectory.cs

Fixes problems revealed by tests enabled in #4869.
Fixes #4892.

Log errors with/without code as appropriate

---

scripts/Deploy-MSBuild.ps1
src/MSBuild/MSBuild.csproj
src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
src/Package/MSBuild.VSSetup/files.swr
src/Tasks/Microsoft.Build.Tasks.csproj
src/Tasks/Microsoft.Common.CurrentVersion.targets
src/Tasks/Microsoft.NET.props
src/Tasks/Microsoft.NETFramework.CurrentVersion.props
src/Tasks/Microsoft.NETFramework.props

Fix https://github.com/microsoft/msbuild/issues/4782
By extracting these props
Tested locally with override files. TargetFrameworkSDKToolsDirectory is set

Import few property in netframework props for core

---

src/Directory.BeforeCommon.targets
src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
src/Tasks/GenerateResource.cs
src/Tasks/ResGenDependencies.cs
src/Tasks/system.design/stronglytypedresourcebuilder.cs

Rename to FEATURE_RESXREADER_LIVEDESERIALIZATION

---

src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs

PlatformSpecific Testing for Windows

---

src/Shared/CommunicationsUtilities.cs

Because CommunicationsUtilities is in Shared, it can get compiled into multiple
different assemblies. Important here are MSBuild.exe, MSBuildTaskHost.exe and
Microsoft.Build.dll.
If the method called during the handshake is from a mismatched assembly from
the host, the handshake can spuriously mismatch. But we can't unify on a
single assembly because MSBuildTaskHost doesn't load any other modern assemblies
(only .NET 3.5 MSBuild assemblies).
Instead, use the directory of the running MSBuild assembly in the handshake.
All current distributions of MSBuild require having all the assemblies in the
same directory and loading them together as a set, so this should not lose
generality.

Use directory-of-MSBuild in node handshake

---

eng/Packages.props
eng/Versions.props
global.json

Including chained NuGet update.

Move to .NET Core SDK 3.1.100

---

src/Build/BackEnd/Components/RequestBuilder/IntrinsicTask.cs
src/Build/Definition/ResolvedImport.cs
src/Build/Definition/Toolset.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Instance/ProjectItemDefinitionInstance.cs

Various minor cleanup.
Should review commit-by-commit (this will not be squashed on completion).

Various minor cleanup

---

src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
src/Shared/Resources/Strings.shared.resx

Removes UESanitized as discussed in #4899.
Also converts some repetitive tests to theories.

Remove unnecessary code

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.en.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs

A suggestion to solve the issue #2892

Added the message at the end of the command /help output

---

eng/Versions.props

Prepping this early. Don't merge it until we're ready.

Final Branding 16.5

---

src/Shared/UnitTests/xunit.runner.json

On my dev box, the longest-running test was 24 seconds, so I'm hoping this is a reasonable time limit.

Report long-running tests in xunit

---

src/Tasks.UnitTests/NuGetPropsImportTests.cs
src/Tasks/Microsoft.Common.CrossTargeting.targets
src/Tasks/Microsoft.Common.CurrentVersion.targets
src/Tasks/Microsoft.Common.props

Import NuGet.props

---

eng/Packages.props
src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build/Construction/Solution/SolutionFile.cs
src/Build/Construction/Solution/SolutionProjectGenerator.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Microsoft.Build.csproj
src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
src/Package/MSBuild.VSSetup/files.swr
src/Shared/FileUtilities.cs
src/Shared/NativeMethodsShared.cs
src/Shared/ProjectFileErrorUtilities.cs
src/Shared/Resources/Strings.shared.resx
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.en.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

This reverts commit 2e4c1867b08f0fe9ae2591cde6cb73ab304efeff.

Revert "Revert "Apply a solution filter (#4899)" (#5142)"

---

src/Build/Instance/HostServices.cs
src/Directory.Build.targets
src/Package/GetBinPaths.targets
src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
src/Package/MSBuild.VSSetup/files.swr

I'm still trying to test this locally, but the MSBuild bits seem to work fine and I think the problem now lies in the Xaml markup compiler. Thought I'd put this up early just to confirm, because to say I'm unfamiliar with your build infrastructure is a gross understatement :)
(Hopefully) fixes [AB#1077964](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1077964)

Remove block and publish tlb both platforms

---

eng/Packages.props
src/Build/Microsoft.Build.csproj
src/Framework/Microsoft.Build.Framework.csproj
src/Samples/Directory.Build.targets
src/Tasks/Microsoft.Build.Tasks.csproj

This reverts commit 1ae86d63c271f20985f8d327132628c105fae0ae.

Revert "Remove unnecessary NuGet package references (#5242)"

---

src/Build/Construction/Solution/SolutionConfigurationInSolution.cs
src/Build/Construction/Solution/SolutionFile.cs
src/Build/Construction/Solution/SolutionProjectGenerator.cs

Merge NuGet solution-parsing fix to 16.6

---

src/Build/Instance/ProjectItemInstance.cs

See details in https://github.com/microsoft/msbuild/issues/5267

Prevent a spurious ArgumentOutOfRange in CopyOnWriteDictionary.Set

---

src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

LOC CHECKIN | microsoft/msbuild vs16.6 | 20200420

---

src/Build/BackEnd/Node/OutOfProcNode.cs

Making debugging easier, one step at a time

Adding Shutdown Message to Worker Nodes

---

src/MSBuild/XMake.cs

Updating .NET Core branding to .NET

---

eng/Versions.props
src/Package/MSBuild.VSSetup/MSBuild.clientenabledpkg
src/Package/MSBuild.VSSetup/files.swr

Fixes [AB#1111666](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1111666)

Enable MSBuild assemblies for client scenarios

---

src/Build/Evaluation/Expander.cs

This one gets hit a lot in a quickbuild repo I've been debugging through and the Expander exception was getting annoying :)

Add String.IndexOf to well known functions

---

src/Build/Evaluation/Expander.cs

This reverts commit fe0b082321f3f3cb5bd64a6ccd324e24added884.
Fixes #5360

Revert "Add String.IndexOf to well known functions (#5342)"

---

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
src/Build.OM.UnitTests/NugetRestoreTests.cs
src/UnitTests.Shared/RunnerUtilities.cs

Nuget restore test Resolves #5313

---

src/Build.UnitTests/EscapingInProjects_Tests.cs
src/Shared/UnitTests/ObjectModelHelpers.cs

Hoping to help chase down a CI test failure we're having now.

Add test logging in escaping tests

---

eng/Packages.props
src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build/Construction/Solution/SolutionFile.cs
src/Build/Construction/Solution/SolutionProjectGenerator.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Microsoft.Build.csproj
src/Build/System.Text.Encodings.Web.pkgdef
src/Build/System.Text.Json.pkgdef
src/Package/MSBuild.Engine.Corext/MsBuild.Engine.Corext.nuspec
src/Package/MSBuild.VSSetup/files.swr
src/Shared/FileUtilities.cs
src/Shared/NativeMethodsShared.cs
src/Shared/ProjectFileErrorUtilities.cs
src/Shared/Resources/Strings.shared.resx
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.en.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

This reverts commit 2e4c1867b08f0fe9ae2591cde6cb73ab304efeff.
Original slnf change was #4899
Revert was #5142. #4899 was reverted because it created a System.Text.Json dependency that has now been corrected.

Apply a solution filter (revert revert)

---

src/Shared/CommunicationsUtilities.cs

Private method no longer used.

Remove GetBaseHandshakeForContext

---

src/Build.UnitTests/Utilities_Tests.cs
src/Shared/CommunicationsUtilities.cs

TaskHost bit was sometimes being overwritten by a FileVersionHash with a 1 in its eighth bit. This prevents that from being a problem by switching to xor instead of or.
Fixes #5423.

Prevent Task Hosts from communicating with other nodes Fixes #5423

---

src/Tasks/Microsoft.Common.CurrentVersion.targets
src/Tasks/Microsoft.Common.props

Switch default for GenerateFullPaths Fixes #5358

---

README.md

-   Removed unnecessary chart from the file
-   Fixed some minor spelling mistakes.

Improved README.md content

---

eng/Versions.props

I vaguely remember there was something about intentionally making a merge conflict if someone tried to change the version by accident, but if I misremembered, let me know, and I can fix it.

Final branding

---

.github/ISSUE_TEMPLATE/01_bugreport.md
.github/ISSUE_TEMPLATE/02_performanceissue.md
.github/ISSUE_TEMPLATE/03_mybuildisbroken.md

This should help with our bug triage meeting.

Added untriaged labels to all new issues

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Utilities/NuGetFrameworkWrapper.cs

MSBuild side of https://github.com/dotnet/sdk/issues/12614

Converting target framework intrinsic functions to use min version parts

---

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
src/Framework/MSBuildEventSource.cs

This PR adds logging of packet size in node communication.

Logging of packet size in OutOfProc communication

---

ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs
ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs
src/Shared/TaskLoggingHelper.cs
src/Tasks/Error.cs

https://github.com/dotnet/msbuild/pull/5488 caused CloudBuild to fail:
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/264748 (internal link)
because of https://github.com/dotnet/msbuild/pull/5488#discussion_r452300514
This should fix that.

Fix possibly ambiguous overload

---

src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs

Use StringComparison when comparing strings

---

src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
src/Build.OM.UnitTests/ObjectModelRemoting/LinkedProjectCollection_Tests.cs
src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs
src/Deprecated/Engine/Engine/Expander.cs
src/Deprecated/Engine/Properties/BuildProperty.cs
src/Deprecated/Engine/Properties/BuildPropertyGroup.cs
src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/XMake.cs
src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks.UnitTests/AssemblyDependency/Perf.cs
src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependency.cs
src/Tasks/ManifestUtil/ApplicationManifest.cs
src/Tasks/ManifestUtil/TrustInfo.cs

Remove redundant semi colons

---

src/Build.UnitTests/BackEnd/LoggingService_Tests.cs
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs
src/Build/Construction/Solution/SolutionProjectGenerator.cs
src/Build/Errors/InternalLoggerException.cs
src/Build/Instance/HostServices.cs
src/Build/Instance/TaskFactoryLoggingHost.cs
src/Deprecated/Conversion/ProjectFileConverter.cs
src/Deprecated/Engine/Engine/Engine.cs
src/Deprecated/Engine/Engine/EngineCallback.cs
src/Deprecated/Engine/Engine/EngineProxy.cs
src/Deprecated/Engine/Engine/Scheduler.cs
src/Deprecated/Engine/Engine/TaskExecutionModule.cs
src/Deprecated/Engine/Errors/InternalLoggerException.cs
src/Deprecated/Engine/Introspector/TargetCycleDetector.cs
src/Deprecated/Engine/LocalProvider/LocalNode.cs
src/Deprecated/Engine/LocalProvider/LocalNodeProvider.cs
src/Tasks.UnitTests/AssignProjectConfiguration_Tests.cs
src/Tasks.UnitTests/ResolveComReference_Tests.cs
src/Tasks.UnitTests/ResolveNonMSBuildProjectOutput_Tests.cs

Refactoring to remove redundant '== true' using Roslynator.
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1033.md

Remove redundant '== true'

---

.gitignore

Prevent accidents like the on #5601 fixes

Git ignore etl trace files

---

src/Build/Instance/TaskFactories/TaskHostTask.cs
src/Shared/TaskParameter.cs

Use 'is' operator instead of 'as' operator

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes https://github.com/dotnet/msbuild/issues/5622

Set TargetPlatformMoniker on nonempty TargetPlatformIdentifier and Version

---

src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs

See #5453 
Couldn't get it to repro so I'm disabling it.

Disable hanging test

---

src/Build.UnitTests/BackEnd/MockHost.cs
src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs
src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs
src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
src/Build/BackEnd/Components/Communications/NodeInfo.cs
src/Build/BackEnd/Components/Scheduler/Scheduler.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverManifest.cs
src/Build/Collections/LookasideStringInterner.cs
src/Build/Graph/ProjectInterpretation.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Logging/BaseConsoleLogger.cs
src/Samples/XmlFileLogger/ObjectModel/TaskParameter.cs
src/Shared/Debugging/PrintLineDebugger.cs
src/Shared/FileSystem/WindowsFileSystem.cs
src/Shared/FrameworkLocationHelper.cs
src/Shared/NativeMethodsShared.cs
src/Tasks/FileIO/GetFileHash.cs
src/Tasks/GenerateManifestBase.cs
src/Tasks/LockCheck.cs
src/Tasks/ManifestUtil/Manifest.cs
src/Tasks/ManifestUtil/SecurityUtil.cs
src/Tasks/SdkToolsPathUtility.cs
src/Tasks/TlbImp.cs
src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs
src/Utilities/ProcessorArchitecture.cs
src/Utilities/ToolLocationHelper.cs

Refactor to convert switch statements to switch expressions to simplify code.

Convert switch statement to switch expression

---

src/Build/Evaluation/Expander.cs
src/Build/Logging/ParallelLogger/ParallelLoggerHelpers.cs
src/Deprecated/Engine/Engine/EngineCallback.cs
src/Deprecated/Engine/Engine/Expander.cs
src/Deprecated/Engine/Engine/NodeLoggingEvent.cs
src/Deprecated/Engine/Engine/ProjectBuildState.cs
src/Deprecated/Engine/Engine/XmlSearcher.cs
src/Deprecated/Engine/Logging/ParallelLogger/ParallelLoggerHelpers.cs
src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
src/Tasks/GenerateResource.cs

https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1089.md

Use --/++ operator instead of assignment

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

This XSD file controls completion of MSBuild project files in the editor. Adding these values allows completion of values for the Nullable element.
---
Corresponding VS PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/265087
cc: @jcouv

Enumerate possible values for the Nullable property

---

src/Build.UnitTests/BackEnd/TaskHost_Tests.cs
src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Shared/FileUtilities.cs

https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1097.md

Remove redundant 'ToString' call

---

documentation/wiki/Providing-Binary-Logs.md

Adding a note within this guide for folks that are using VS.

Add Note About Capturing Binlogs Through VS

---

src/Tasks.UnitTests/XmlPoke_Tests.cs

Convert test assertions to Shouldly

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Visual Studio currently doesn't have auto completion in csproj for these. I think this should fix that.

Add some missing boolean elements

---

src/MSBuild/XMake.cs
src/Shared/NativeMethodsShared.cs

Attempt to fix #435
- I'm not sure whether similar code should be needed for Unix support.
- I don't have a machine with > 32 cores to actually test this.
Potentially relevant:
- https://github.com/dotnet/corefx/pull/25630

Fix cpu core count detection

---

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build/Construction/Solution/SolutionFile.cs

This first commit should cause it to break on Linux, as it uses the default slashes. If that is correct, I will push the fix I think should work.

Correctly interpret slashes Fixes #5715

---

src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
src/Utilities/Resources/xlf/Strings.fr.xlf

Loc checkin

---

eng/Versions.props

Please don't merge until we're ready.

Final branding for 16.8.0

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes #5420
SDK-side change still required

Prevent outputpath from flowing to projectreferences

---

src/Framework/MSBuildEventSource.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs

Also some (very minor) optimizations in RAR.

Add ETW capturing the number of resolved references

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

This should unblock our insertions
Release here: https://dev.azure.com/devdiv/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=903711

Remove trailing slash error check for OutputPath and BaseOutputPath

---

src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Loc update

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/pull_request_template.md

Let's improve our PR review process! 
The main goal here is to provide more context for the PR's we submit.

Improve PR Template Baseline

---

src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/XMake.cs
src/Shared/QuotingUtilities.cs
src/Tasks.UnitTests/CommandLine_Support.cs

Was doing something in xmake and the ArrayList bothered me, so I took it out and applied some other cleanups as well.

Remove ArrayList from XMake and other cleanup

---

eng/common/templates/post-build/post-build.yml

Fixes #
Unblock Msbuild build
post-build.yml - added new channel VS 16.9
Arcade update on Monady (1/22) will update this change. Basically its the same change I made in arcade (PR -> https://github.com/dotnet/arcade/pull/6840/files)

Add VS 16.9 channel

---

src/StringTools/StringTools.pkgdef

Fix StringTools assembly name

---

eng/common/templates/post-build/post-build.yml

Fixes #
Missing VS 16.10 Channel 
post-build.yml

Add VS 16.10 channel

---

src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Loc updates

---

documentation/specs/threading.md

Add some developer documentation about the things I've learned about the threading model in worker nodes recently.

Short doc on the threading model

---

src/Shared/FileDelegates.cs
src/Shared/FileUtilities.cs
src/Shared/UnitTests/FileUtilities_Tests.cs
src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs
src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks.UnitTests/AssemblyDependency/Perf.cs
src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
src/Tasks.UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs
src/Tasks.UnitTests/HintPathResolver_Tests.cs
src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs
src/Tasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs
src/Tasks/AssemblyDependency/AssemblyFoldersResolver.cs
src/Tasks/AssemblyDependency/AssemblyResolution.cs
src/Tasks/AssemblyDependency/CandidateAssemblyFilesResolver.cs
src/Tasks/AssemblyDependency/DirectoryResolver.cs
src/Tasks/AssemblyDependency/FrameworkPathResolver.cs
src/Tasks/AssemblyDependency/GacResolver.cs
src/Tasks/AssemblyDependency/HintPathResolver.cs
src/Tasks/AssemblyDependency/RawFilenameResolver.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
src/Tasks/AssemblyDependency/Resolver.cs
src/Tasks/InstalledSDKResolver.cs
src/Tasks/SystemState.cs

This commit broke RPS (https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/302845)
Reverting it fixed RPS (https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/303584)

Revert "Optimize FileExists lookup (#6033)"

---

src/Shared/MSBuildLoadContext.cs

This reverts commit 183645c502cc41de4b63662704b7b339c32f0f12.
cc: @marcpopMSFT

Revert "Add NuGet assemblies to the list of well-known assemblies."

---

.vsts-dotnet-ci.yml
.vsts-dotnet.yml

Part of https://github.com/dotnet/msbuild/issues/6249
Include main as a branch to trigger CI for master -> main transition.
Add main to CI and pipeline yml files.
If you'd like to sanity check (should take ~1 min), see https://github.com/dotnet/arcade/blob/main/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md#2-add-main-triggers-to-yaml-pipelines

Add main as a CI & pipeline trigger

---

README.md

Also add a line about how to build Release.

Fix Git URL in readme.

---

src/Build.UnitTests/BinaryLogger_Tests.cs
src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs

Normal codeflow of approved 16.9 servicing fixes to 16.10.

Merge 16.9->16.10

---

.vsts-dotnet.yml

Aplying https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_wiki/wikis/DevDiv.wiki/12566/Using-Scale-Set-pools-for-Build-Pipelines?anchor=drop-to-an-onprem-server
.vsts-dotnet.yml updated, few tasks versions bumped up
run in azdo exp branch

Moves build into scale sets pool

---

src/Tasks/ResGenDependencies.cs

Mark serializable

---

ref/Microsoft.Build/net/Microsoft.Build.cs
ref/Microsoft.Build/netstandard/Microsoft.Build.cs
src/Build/BackEnd/Components/Communications/EntryNodeEndpointOutOfProc.cs
src/Build/BackEnd/Components/Communications/EntryNodeHandshake.cs
src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
src/Build/BackEnd/Node/EntryNodeCommand.cs
src/Build/BackEnd/Node/OutOfProcEntryNode.cs
src/Build/Microsoft.Build.csproj
src/MSBuild/XMake.cs
src/Shared/CommunicationsUtilities.cs
src/Shared/INodePacket.cs
src/Shared/NodeEndpointOutOfProcBase.cs

Parking MSBuild server V2.
Work left:
- unit tests
- refactoring
- address few TODOs

Parking MSBuild Server V2

---

.vsts-dotnet.yml

Moves 16.11 build into scale sets pool

---

.vsts-dotnet-ci.yml

Update ubuntu version

---

src/MSBuild/app.amd64.config
src/MSBuild/app.config

Switch VCTargetsPath to v170

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Descriptions from https://docs.microsoft.com/dotnet/core/tools/global-tools-how-to-create#package-the-tool

Add .NET tool properties to XSD

---

src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs

Don't log Building with tools version "Current".

---

Directory.Build.props
global.json

This is tested. I'll do that tomorrow.

Use SDK precomputed cache

---

eng/common/internal/Tools.csproj

Mirror of action from ongoing PR https://github.com/dotnet/arcade/pull/7693 to unblock Main.

Remove xml declaration from Tools.csproj

---

src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs

@Forgind I keep my promises ;)

Delete dead code.

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Fixes https://github.com/dotnet/msbuild/issues/6854

Add SatelliteResourceLanguages property to common types schema

---

documentation/Changelog.md

I feel a bit bad condensing so much work into "performance improvments".

MSBuild 17.0 release notes

---

.vsts-dotnet-ci.yml
.vsts-dotnet.yml
src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
src/Build.UnitTests/BackEnd/MSBuild_Tests.cs
src/Build.UnitTests/EscapingInProjects_Tests.cs
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/Build.UnitTests/TargetsFile_Test.cs
src/Shared/Constants.cs
src/Shared/FrameworkLocationHelper.cs
src/Tasks.UnitTests/GetReferencePaths_Tests.cs
src/Tasks.UnitTests/MSBuild_Tests.cs
src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
src/Tasks.UnitTests/RegressionTests.cs
src/Tasks.UnitTests/ResourceHandling/GenerateResourceOutOfProc_Tests.cs
src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
src/Tasks/AssemblyDependency/Resolver.cs
src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
src/Utilities.UnitTests/ToolLocationHelper_Tests.cs
src/Utilities/ToolLocationHelper.cs

They're still prerelease but it's time.

Switch to VS 2022 pools

---

eng/Packages.props
src/Framework/Microsoft.Build.Framework.csproj
src/MSBuild/app.amd64.config
src/MSBuild/app.config

This corresponds to [AB#364153](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/364153), and updates the packages that were updated in Visual Studio in that internal PR.
Part of #5852 (but not all of it).

Update some dependencies to 6.0 versions

---

src/Tasks/LC.cs
src/Tasks/Microsoft.Build.Tasks.csproj
src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt

This isn't going to be supported per https://github.com/dotnet/winforms/issues/1462.

Log explicit failure for LC on Core

---

src/Build/Construction/ProjectRootElement.cs

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1125.md

SA1125 use shorthand for Nullable types

---

eng/Common.globalconfig

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1132.md

SA1132 Do not combine fields

---

eng/Common.globalconfig

Set CA1070 to Warning

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/Caching/RegisteredTaskObjectCache.cs
src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs
src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
src/Build/Collections/ItemDictionary.cs
src/Tasks/RCWForCurrentContext.cs

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1643.md

SA1643: Finalizer appropriate summary text

---

eng/Common.globalconfig

Disable CA1805

---

eng/Common.globalconfig

Follow up to #7227 to enable warning on CA1050

Enable warning on CA1050

---

eng/Common.globalconfig

Follow up to #7198 as we didn't change the severity to warning.

Enable warning on SA1520

---

eng/Common.globalconfig

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1510.md

Enable SA1510 to Warning

---

eng/Common.globalconfig
src/Shared/AssemblyFolders/AssemblyFoldersFromConfig.cs

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1102.md

SA1102 Query clause should follow previous clause

---

src/Build/Microsoft.Build.csproj
src/Directory.BeforeCommon.targets
src/Directory.Build.props
src/Samples/Directory.Build.props
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj

Apply source-build patches

---

src/Framework/Microsoft.Build.Framework.csproj

Per the comment, this was removable once we turned on nullable. Which was done in #7130.

Remove CS8632 suppression

---

global.json

Might as well use the latest and greatest.

.NET SDK 6.0.200

---

.vsts-dotnet.yml

Fixes issue in CI related to vsmanifests containing duplicate entries.

Update MicroBuildSwixPlugin 1->4

---

documentation/MSBuild-Server.md

Fixes #7370
Describes communication protocol for MSBuild Server.

Added MSBuild server doc (communication protocol)

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
src/Tasks/DownloadFile.cs
src/Tasks/PublicAPI/net/PublicAPI.Shipped.txt
src/Tasks/PublicAPI/netstandard/PublicAPI.Shipped.txt

That allow control timeout behavior on flaky networks.

Add Timeout parameter for the DownloadFile task

---

src/Shared/MSBuildLoadContext.cs
src/Shared/UnitTests/TypeLoader_Tests.cs

revert deps.json change

---

src/Package/MSBuild.VSSetup/files.swr

Add Microsoft.Build.Framework.tlb

---

src/Build.UnitTests/BackEnd/BuildRequest_Tests.cs
src/Build.UnitTests/Instance/HostServices_Tests.cs
src/Build/Instance/HostServices.cs
src/Build/Instance/RunningObjectTable.cs
src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
src/Directory.BeforeCommon.targets
src/Tasks/AssemblyDependency/GlobalAssemblyCache.cs
src/Tasks/GenerateResource.cs
src/Tasks/Microsoft.Build.Tasks.csproj
src/Tasks/NativeMethods.cs
src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt

Remove the `#if`s and switch to runtime checks + OS guards.

Enable FEATURE_COM_INTEROP everywhere

---

.vsts-dotnet.yml

Update vs17.2 loc branch

---

src/Build/FileSystem/DirectoryCacheFileSystemWrapper.cs
src/Directory.BeforeCommon.targets
src/Shared/FileMatcher.cs

This removes the prebuilt Microsoft.IO.Redist in MSBuild for source-build.

Disable Microsoft.IO.Redist in source-build.

---

.vsts-dotnet.yml

This reverts commit b1451d7b72eb6c76c6e39e44a640f4d2a276a8bd.
This broke our official builds.

Revert "Generate Sbom for VS insertions (#7811)"

---

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Shared/UnitTests/ObjectModelHelpers.cs

This fixes some broken Graph and ProjectCache UTs (which aren't failing PR or CI builds since they're disabled by #4501...) and also does some minor refactoring/cleanup of the UTs

Fix Graph and ProjectCache UTs

---

.vsts-dotnet.yml
global.json

This reverts commit 659a296a34870ea26a1ffa02919d886fd6445e2e.
Fixes #

Revert "Sbom for VS insertion  (#7826)"

---

.github/fabricbot.json

Remove unused tasks or tasks we manually do anyway.
Collapse `needs-attention` into `needs-triage`
Note: This file was **auto-generated**.

Simplify labeler bot

---

src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs
src/Build/BackEnd/Node/OutOfProcNode.cs

A minor change to cleanup and remove some dead code from NodeEndpointOutOfProc

Cleanup / Remove some dead code from NodeEndpointOutOfProc

---

src/Build/Evaluation/Evaluator.cs

One parameter's default value was never overriden, and I also simplified an if statement.

Simplify import throwing logic

---

eng/Versions.props
src/Build.OM.UnitTests/Definition/Project_Tests.cs
src/Build.UnitTests/BackEnd/BuildEventArgTransportSink_Tests.cs
src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs
src/Build.UnitTests/BackEnd/DebugUtils_tests.cs
src/Build.UnitTests/BackEnd/TargetUpToDateChecker_Tests.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
src/Build/BackEnd/Components/Scheduler/Scheduler.cs
src/Framework/NativeMethods.cs
src/MSBuild/OutOfProcTaskHostNode.cs
src/MSBuildTaskHost/MSBuildTaskHost.csproj
src/Shared/CommunicationsUtilities.cs
src/Shared/Debugging/DebugUtils.cs
src/Shared/ExceptionHandling.cs
src/Shared/FileUtilities.cs
src/Shared/NodeEndpointOutOfProcBase.cs
src/Shared/TempFileUtilities.cs
src/Shared/UnitTests/FileUtilities_Tests.cs
src/Shared/UnitTests/TestEnvironment.cs
src/Tasks.UnitTests/Copy_Tests.cs
src/Tasks/CodeTaskFactory.cs
src/Tasks/GetSDKReferenceFiles.cs
src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
src/Tasks/TlbReference.cs
src/Tasks/WriteCodeFragment.cs
src/Utilities/TrackedDependencies/FileTracker.cs

17.3 security update

---

global.json

No urgent need, just keeping up.

Update to .NET SDK RC2

---

src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs

I have merged merged previous PR prematurely :-( Sorry
Ranamed WorksCorrectlyWithCurlyBraces as recommended.

Renaming TestCache2 test

---

src/Build/Evaluation/Evaluator.cs

Fixes
This is causing trouble (see #8167 and #8168)

Revert VSToolsPath error

---

.vsts-dotnet.yml
eng/Version.Details.xml
eng/Versions.props
eng/common/build.ps1
eng/common/generate-sbom-prep.ps1
eng/common/generate-sbom-prep.sh
eng/common/init-tools-native.ps1
eng/common/internal/NuGet.config
eng/common/internal/Tools.csproj
eng/common/sdl/sdl.ps1
eng/common/templates/job/execute-sdl.yml
eng/common/templates/job/onelocbuild.yml
eng/common/templates/job/source-build.yml
eng/common/templates/jobs/jobs.yml
eng/common/templates/post-build/post-build.yml
eng/common/templates/steps/execute-sdl.yml
eng/common/tools.ps1
global.json
src/Build.OM.UnitTests/Definition/Project_Tests.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Tasks.UnitTests/Exec_Tests.cs

Most of the file changes here are from an arcade update.
There were a couple minor stylistic changes in tests, one unnecessary but coherent change to a test, and updating the yml file from 17.2 to 17.3.

Update 17.3 from 17.2

---

eng/Versions.props

Should have been part of #8201. Whoops!

Version 17.4.1

---

global.json

And require VS 17.4 (when we need VS).

Update to SDK 7.0.101

---

eng/Versions.props

Final release branding

---

src/UnitTests.Shared/EnvironmentProvider.cs

Fixing build errors after the merge clash

Fix stylecheck errors

---

documentation/README.md
documentation/wiki/Nodes-Orchestration.md

Enriched transcript of a talk with @rainersigwald about MSBuild nodes orchestration and scheduling.
I added some extra interpretations and links that were not voiced in the talk - so I'll be happy for review for corectness of the doc.

Add nodes orchestration doc

---

src/Tasks/FileIO/WriteLinesToFile.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Warn about unused WriteOnlyWhenDifferent attribute

---

Directory.Build.props

We should be dogfooding this project-system feature.
cc @drewnoakes

Dogfood "build acceleration"

---

.github/fabricbot.json

May fix #8487
This may not work as intended, primarily because vs* may not expand to vs17.4/etc. I'm proposing merging this, since it shouldn't hurt, then checking to see if it works and tweaking it if not.

Add PR bot action

---

.github/fabricbot.json

Test that VS needs an exact path

---

src/MSBuild/XMake.cs

This feels very noisy to me at normal verbosity; I kept being surprised that I was seeing it.

Demote rsp-file-used message importance

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Yet another placeholder for TFM - in node build progress

Adding placeholder for TFM

---

.vsts-dotnet.yml
eng/Versions.props
eng/common/templates/job/job.yml
eng/common/templates/steps/component-governance.yml

Fixes - replacing the previous wrong flow PR: https://github.com/dotnet/msbuild/pull/8774

[vs17.6] vs17.4 to vs17.6 merge

---

src/MSBuild/XMake.cs

The binary logger, when turned on, sets the verbosity to diagnostic. This should not be true if the user explicitly requests another verbosity.
Fixes #4543

Change how verbosity is set Fixes #4543

---

src/MSBuild/XMake.cs

Reverts dotnet/msbuild#8805, fixes #8845.

Revert "Change how verbosity is set Fixes #4543"

---

src/Tasks/ResourceHandling/MSBuildResXReader.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

I noticed that this wasn't localized, and it should be, as this could feasibly be user-facing.

Localize error

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

@dfederm tried to see what the error was when he specified /low:Foo and got...a missing resource exception. Whoops. This fixes that.

Add missing resource

---

eng/Versions.props

Relates to https://github.com/dotnet/msbuild/issues/8896
To be merged only after adjust to VS insertions

17.7 final branding

---

NuGet.config
eng/Versions.props

Version 17.8

---

eng/BootStrapMSBuild.targets

Try to fix the build error after reenabling static graph restore

Try to fix the build error after reenabling static graph restore

---

eng/sdl-tsa-vars.config

TSA notification emails not sent out to proper group
Updated contacts based on current ownership

Update TSA config

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

System.Text.Json 7.0.3

---

.vsts-dotnet.yml
global.json

Fixes of source build template error and verification error of msbuild version.  Have verify the fixes in the pipeline.
https://github.com/dotnet/msbuild/pull/9041 miss the updates

Update source build template, vs version and XCopyMSBuildVersion

---

eng/Version.Details.xml

Fixes CG alerts from source build

Fix the System.Security.Cryptography.Pkcs secuity error

---

eng/Versions.props

Bump Versions.props to 17.7.2 as preparation for servicing packege

Bump Versions.props to 17.7.2

---

src/Tasks/Copy.cs

Update Copy task to log full paths

---

src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs

ProjectCache: Break away from UI thread for initialization to avoid VS hangs.
This fixes a hang reported by some users which appears to impact some specific scenarios.
For some legacy scenarios in VS, it appears that design-time builds are not properly detected by the project cache and so trigger the scenario. This runs on the UI thread, which itself is bad, but then in the `InitializePluginsForVsScenario` method, some tasks are used which also execute on the UI thread and the specific plugin the customer is using makes many async calls which ends up hanging the UI thread.
Originally, I had wrongly assumed that the `Parallel.ForEach` would cause the code in the body to run in a separate thread, breaking away from the UI thread. However, that's a bad assumption as with a small number of …

ProjectCache: Break away from UI thread for initialization to avoid VS hangs

---

eng/Versions.props

final branding for 17.8

---

.editorconfig

The latest public preview of 17.8 cannot build this repo.
Added IDE0305 to `.editorconfig` as a suggestion.

Make repo buildable with VS 17.8.0 Preview 3.0

---

src/Build.UnitTests/BackEnd/BuildManager_Logging_Tests.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Framework/ChangeWaves.cs
src/Framework/Traits.cs

Experimental insertion for https://github.com/dotnet/msbuild/pull/9318

---

.vsts-dotnet-ci.yml
.vsts-dotnet.yml

Add performance branch official build trigger.

Add performance branch official build trigger

---

eng/dependabot/Packages.props

Upgrade the version of the package manually. 
For more context why it is done manually please see here: https://github.com/dependabot/dependabot-core/issues/7206
Upgrade version of Microsoft.VisualStudio.Setup.Configuration.Interop
Existing tests should pass

Upgrade Microsoft.VisualStudio.Setup.Configuration.Interop version

---

eng/Version.Details.xml
eng/Versions.props
eng/dependabot/Packages.props
src/Build/BackEnd/Components/Communications/DetouredNodeLauncher.cs

Merge a couple of commits that went into main "after the fork" but we want them anyway.

FI main->vs17.9

---

.vsts-dotnet.yml
eng/Versions.props

Disable localization for vs17.8

Disable localization for vs17.8

---

src/MSBuild/MSBuild.csproj
src/Package/MSBuild.VSSetup/files.swr
src/Tasks/Microsoft.Build.Tasks.csproj

This was added in #9193 but not usable in VS.

Include M.Common.Test.targets in VSIX

---

eng/Versions.props

final branding for 17.9

---

src/Tasks/Microsoft.Common.CrossTargeting.targets

Should fix https://github.com/dotnet/sdk/issues/37712
cc:  @rainersigwald @Forgind   @baronfel  @Evangelink @nohwnd

Import the new `Microsoft.Common.Test.targets` target for multi-tfm

---

.vsts-dotnet.yml

These are old and unused these days.

Remove legacy properties

---

eng/Versions.props

Build failures.
The partial revert of https://github.com/dotnet/msbuild/commit/8e84d63bdcca193855acef2420974625560e3bf1

Return UsingToolMicrosoftNetCompilers tag to fix build failure

---

.opt-prof.yml

Opt prof pipeline failure
Remove extra content based on review
https://dev.azure.com/devdiv/DevDiv/_git/DotNet-msbuild-Trusted/commit/a488138b25bd49fe7e24bbb0a0dd3f068c73a107?refName=refs%2Fheads%2Fmain&path=%2F.opt-prof.yml&_a=compare

Remove extra prod tags for Opt prof

---

documentation/Deploy-MSBuild.md
documentation/wiki/MSBuild-Resources.md

Fixes #9832
Updating documentation concerning using the deployment PowerShell script on Linux.

Improve deployment script documentation.

---

eng/Versions.props

Bump version to 17.11

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Added more expressive documentation for "Folder" element in the schema

---

eng/Versions.props

Final branding for 17.10

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Comment clarification - as this got conusing duirng investigating platform negotiation inner workings

Clarify platform negotiation comment

---

documentation/wiki/FeatureAvailability.md

See the comment https://github.com/dotnet/msbuild/pull/9719#discussion_r1550039463

Add Feature Availability Document Page

---

.vsts-dotnet-ci.yml
eng/Versions.props

[vs17.7] Backport #10024

---

src/Tasks/ManifestUtil/ManifestFormatter.cs
src/Tasks/ManifestUtil/ManifestReader.cs
src/Tasks/ManifestUtil/XmlUtil.cs

Failed insertion in VS (it had required tests failures)
Delegate stream handling to the caller (it is needed later)
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/545969

Handle specific dispose cases in xml-related utils

---

.opt-prof.yml

update Windows-10-Enterprise-20H2 image in pipelies for MSBuild opt prof

Update from `Windows-10-Enterprise-20H2` to `Windows-11-Enterprise-23H2`

---

documentation/specs/proposed/BuildCheck-feature-threat-model.md

Fixes #10064
Initial version of BuildCheck threat model doc

Inital version of buildcheck threat model

---

src/Deprecated/Conversion/ProjectFileConverter.cs
src/Deprecated/Engine/Engine/BuildTask.cs
src/Deprecated/Engine/Engine/Import.cs
src/Deprecated/Engine/Engine/ImportCollection.cs
src/Deprecated/Engine/Engine/Target.cs
src/Deprecated/Engine/Engine/TargetCollection.cs
src/Deprecated/Engine/Engine/Toolset.cs
src/Deprecated/Engine/Engine/ToolsetCollection.cs
src/Deprecated/Engine/Engine/UsingTask.cs
src/Deprecated/Engine/Engine/UsingTaskCollection.cs
src/Deprecated/Engine/Engine/Utilities.cs
src/Deprecated/Engine/Errors/InternalLoggerException.cs
src/Deprecated/Engine/Errors/InvalidProjectFileException.cs
src/Deprecated/Engine/Errors/InvalidToolsetDefinitionException.cs
src/Deprecated/Engine/Errors/RemoteErrorException.cs
src/Deprecated/Engine/Items/BuildItem.cs
src/Deprecated/Engine/Items/BuildItemGroup.cs
src/Deprecated/Engine/Items/BuildItemGroupCollection.cs
src/Deprecated/Engine/LocalProvider/LocalNode.cs
src/Deprecated/Engine/Logging/ConsoleLogger.cs
src/Deprecated/Engine/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
src/Deprecated/Engine/Logging/DistributedLoggers/DistributedFileLogger.cs
src/Deprecated/Engine/Logging/FileLogger.cs
src/Deprecated/Engine/Logging/LoggerDescription.cs
src/Deprecated/Engine/Properties/BuildProperty.cs
src/Deprecated/Engine/Properties/BuildPropertyGroup.cs
src/Deprecated/Engine/Properties/BuildPropertyGroupCollection.cs
src/Deprecated/Engine/Solution/SolutionWrapperProject.cs

We are working on actually deprecating the projects under the `deprecated` folder.  For now adding the deprecation message to public classes.

Added deprecation messages

---

documentation/specs/proposed/BuildCheck-feature-threat-model.md

#10136, #10137
Add public documentation for custom BuildCheck rules.

Extend BuildCheck-feature-threat-model.md

---

src/BuildCheck.UnitTests/EndToEndTests.cs

Disable CustomAnalyzerTest

---

.vsts-dotnet.yml
eng/Versions.props

Disable localization for vs17.10

Disable localization for vs17.10

---

.vsts-dotnet.yml
eng/Versions.props

Adding a comment about localization in order to cause a merge conflict, when https://github.com/dotnet/msbuild/pull/10269 flows automatically to this branch releases and main. 
See https://github.com/dotnet/msbuild/pull/10269#discussion_r1646558936

Add comment about localization 2

---

src/Tasks/Microsoft.Common.tasks

https://github.com/dotnet/sdk/pull/41951#discussion_r1669378278

Note Roslyn UsingTasks duplication in SDK

---

.github/ISSUE_TEMPLATE/07_buildchecksuggestion.yml

Let's give users an ability to create BuildCheck suggestions

Add buildcheck suggestion template

---

documentation/specs/BuildCheck/Codes.md

Fix typo in BuildCheck codes doc

---

.github/workflows/inter-branch-flow.yml
eng/Versions.props

Introducation of the merge flow. 
Added the github workflow (actions) which will be executed on push changes into the vs1** branches and will automatically create upstream merge request. 
Testing was done manually: 
https://github.com/f-alizada/msbuild/actions
Should be merged only after this: https://github.com/dotnet/msbuild/pull/10257 is merged

Add inter-branch merge flow file

---

src/Build/CompatibilitySuppressions.xml
src/Tasks/CompatibilitySuppressions.xml
src/Utilities/CompatibilitySuppressions.xml

I didn't notice that these got lost in #10491 before I approved it.

Preserve compat suppression comments

---

src/Build/BackEnd/Shared/BuildResult.cs
src/Build/Definition/Project.cs
src/Build/Evaluation/Context/EvaluationContext.cs
src/Tasks/MSBuildInternalMessage.cs

Fixes some doc warnings generated by the ms learn bot.

Fixed cross references and some invalid tags

---

documentation/specs/BuildCheck/Codes.md

The doc is not in sync with our code - this change is bringing it up to sync

Fix props check doc

---

Directory.Build.targets
eng/Versions.props
eng/cibuild_bootstrapped_msbuild.ps1
eng/cibuild_bootstrapped_msbuild.sh
global.json

Use RC1 SDK

---

src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/MSBuild.UnitTests/NodeStatus_SizeChange_Tests.cs

Some tests can fail on systems with different settings...

Fix for some tests which can fail due the environment setup

---

.vsts-dotnet.yml

Part of: https://github.com/dotnet/msbuild/issues/10665
Updating the localization comment so changes do not get merged automatically.

Update localization comment for main

---

.config/git-merge-flow-config.jsonc

Part of: https://github.com/dotnet/msbuild/issues/10665
Updating branch flow from 17.11 -> 17.12 -> main.

Update merge flow

---

.vsts-dotnet.yml
eng/Versions.props

Part of: https://github.com/dotnet/msbuild/issues/10665
Disabling localization for 17.11.

Disable localization for 17.11

---

documentation/release-checklist.md

* We have a new package that we do not want to forget publishing
* We are removing 2 packages that we want to stop publishing
For those reason an explicit list of packages to remove will be helpful

Specify packages list to publish in release-checklist.md

---

NuGet.config
eng/Packages.props
eng/Versions.props

Enable NuGetAudit and fix warnings 
#10712

 Enable NuGetAudit

---

.config/1espt/PipelineAutobaseliningConfig.yml

Add policheck baseline

---

eng/Version.Details.xml

Update System.Text.Json to 8.0.5

Update System.Text.Json to 8.0.5

---

src/Deprecated/Conversion/Microsoft.Build.Conversion.Core.pkgdef
src/Package/DevDivPackage/DevDivPackage.csproj
src/Package/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
src/Package/GetBinPaths.targets
src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
src/Package/MSBuild.VSSetup/MSBuild.clientenabledpkg
src/Package/MSBuild.VSSetup/files.swr

temporary revert dotnet/msbuild#10817 due to issues with insertion.
I will redo it after https://github.com/dotnet/msbuild/pull/10843

Revert "Remove Conversion.Core registrations (#10817)"

---

Directory.Build.targets
NuGet.config
eng/Versions.props

Remove msbuild17.12 feed and WorkaroundDotnetSdk43339

Remove msbuild17.12 feed and WorkaroundDotnetSdk43339

---

src/UnitTests.Shared/ObjectModelHelpers.cs

I happened by this code and was sad at how allocatey it was.
We don't care much in unit tests but I was moved to fix it.

Allocate less in test CleanupFileContents

---

src/Shared/XMakeElements.cs

```
D:\a\_work\_temp\temp\msbuild\src\Shared\XMakeElements.cs(44,13): warning IDE0002: Name can be simplified [D:\a\_work\_temp\temp\msbuild\src\Build\Microsoft.Build.csproj]
D:\a\_work\_temp\temp\msbuild\src\Shared\XMakeElements.cs(45,13): warning IDE0002: Name can be simplified [D:\a\_work\_temp\temp\msbuild\src\Build\Microsoft.Build.csproj]
D:\a\_work\_temp\temp\msbuild\src\Shared\XMakeElements.cs(46,13): warning IDE0002: Name can be simplified [D:\a\_work\_temp\temp\msbuild\src\Build\Microsoft.Build.csproj]
D:\a\_work\_temp\temp\msbuild\src\Shared\XMakeElements.cs(47,13): warning IDE0002: Name can be simplified [D:\a\_work\_temp\temp\msbuild\src\Build\Microsoft.Build.csproj]
D:\a\_work\_temp\temp\msbuild\src\Shared\XMakeElements.cs(48,13): warning IDE0002: Name can be simplified …
```

fix IDE0002 in XMakeElements.cs

---

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs

This test failed on my machine and it wasn't clear why (#10952),
so I'm updating its assertions and style to report more clearly.

Modernize Regress314573_VeryLongPaths

---

eng/dependabot/Packages.props

Update Microsoft.BuildXL.Processes to 0.1.0-20241105.3

Update Microsoft.BuildXL.Processes to 0.1.0-20241105.3

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml

the automatic merge was enabled and the PR https://github.com/dotnet/msbuild/pull/10994 merged. But we still need a review from source build

Revert "[main] Update dependencies from dotnet/roslyn"

---

eng/TestAssets.targets
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj

Fixes #10547
We need to track the template's state.
Add the test verifying template installation, creation and building the created project.
Added a new test.

Add the test verifying build check template

---

documentation/wiki/ChangeWaves.md
eng/Versions.props
src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Framework/ChangeWaves.cs
src/Framework/ProjectStartedEventArgs.cs
src/Shared/Constants.cs
src/UnitTests.Shared/ObjectModelHelpers.cs

Due to breaking more stuff than intended, I'm reverting this PR to be in sync with main.

Revert backport pr 10942 to vs17.12

---

documentation/wiki/ChangeWaves.md
eng/Versions.props
src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Framework/ChangeWaves.cs
src/Framework/ProjectStartedEventArgs.cs
src/Shared/Constants.cs
src/UnitTests.Shared/ObjectModelHelpers.cs

Reverts dotnet/msbuild#11088
Gift that keeps on giving. Sorry.

Revert "Revert backport pr 10942 to vs17.12"

---

eng/Versions.props
src/Build/CompatibilitySuppressions.xml

17.14 Branding

---

eng/Versions.props

Bumping the version so we can insert into VS after optprof run

[vs17.13] Bump version

---

.config/git-merge-flow-config.jsonc

Parto of #11126
Add vs17.13 to interbranch flow

Update interbranch flow

---

.vsts-dotnet.yml
eng/Versions.props

Part of #11126
We localize only the last release branch

[vs17.12] Disable 17.12 localization

---

documentation/wiki/ChangeWaves.md

We experienced couple cases of users having a stale ChangeWave opt-out, while not being aware. This only delayes future breakages.
Let's make it explicit that ChangeWave opt-out is temporary and that a bug should exist for problematic behavior.

Update ChangeWaves doc

---

.config/tsaoptions.json

Update areapath in tsaoptions.json

---

documentation/specs/proposed/BuildCheck-net10-polishing.md

Onepager of 'BuildCheck polishing' story.

BuildCheck polishing one-pager

---

azure-pipelines/vs-insertion.yml
eng/Versions.props

internal discussion
in servicing don't autocomplete, in main yes
to be mergeflown to all servicing and main branch

Don't autocomplete servicing insertions

---

.vsts-dotnet.yml
eng/Versions.props

Fixing release branches OptProf issues for 17.11

[vs17.11] Select proper VS channel

---

.vsts-dotnet.yml
eng/Versions.props

Fixing release branches OptProf issues

[vs17.12] Select proper VS channel

---

src/Framework/LazyFormattedBuildEventArgs.cs

Fixes #11242
Preventing unhandled exceptions during logging that might be comming from ToString on arbitrary types.

Grace handle custom ToString issues

---

.vsts-dotnet.yml
eng/Versions.props

Fixing release branches OptProf issues

[vs17.13] Select proper VS channel

---

.vsts-dotnet.yml
eng/Versions.props

Fixing release branches OptProf issues

[vs17.10] Select proper VS channel

---

.vsts-dotnet.yml
eng/Versions.props

Fixing release branches OptProf issues

[vs17.8] Select proper VS channel

---

src/Build/Evaluation/IntrinsicFunctions.cs

continuation of https://github.com/dotnet/msbuild/pull/11210
contributing to https://github.com/dotnet/msbuild/issues/7598

replacing a batch of Regex with their generated variant

---

documentation/wiki/Binary-Log.md

Add example to documentation about event id(s)

Add example to documentation about event id(s)

---

.exp-insertions.yml
.vsts-dotnet.yml
eng/Versions.props

Fixes our CI breaking after the latest arcade update for vs17.12,vs17.13,main
restoring from correct config
to be mergeflown
exp run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10985067&view=results

[vs17.12] Fix arcade tool restore

---

.config/1espt/PipelineAutobaseliningConfig.yml
.config/guardian/.gdnbaselines

Port https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted/pullrequest/599457

Port 1ES Pipeline Templates PR

---

.opt-prof.yml
.vsts-dotnet.yml
eng/Versions.props

infra improvements based on internal discussions,
in one PR to save space in history
to be mergeflowed

[17.8] remove optprof image name, restore arcade tools correctl

---

src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Fixes #11515
I forgot to move restore-related resources.
I moved them now.
Manual.

Moving forgotten TL resources

---

.github/workflows/SyncAnalyzerTemplateMSBuildVersion.yml

Test SyncAnalyzerTemplateMSBuildVersion  action

Add permmision and test branch

---

eng/Versions.props

Follow-up to https://github.com/dotnet/msbuild/pull/11538

Upgrade `Microsoft.VisualStudio.SolutionPersistence` to 1.0.52

---

.config/git-merge-flow-config.jsonc

Updated merge flow to:
- 17.13 -> 17.14
- 17.14 -> main

Update merge flow 17.14 -> main

---

.vsts-dotnet.yml
eng/Versions.props

Disabling localization for 17.13.

Disable loc for 17.13

---

.vsts-dotnet-ci.yml
eng/Versions.props

- Final branding for 17.14 branch.
- Updating the baseline packages to 17.13 non-preview version
- restoring version bump check on PRs

[17.14] Final branding

---

.vsts-dotnet-ci.yml
eng/Versions.props

Add the check on version bump up.

Add the check on version bump up

---

src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj
src/Framework/BinaryTranslator.cs
src/Framework/BuildEventArgs.cs
src/Framework/IBuildEngine7.cs
src/Framework/IBuildEngine8.cs
src/Framework/InternalErrorException.cs
src/MSBuild/MSBuild.csproj
src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj

Observed in https://github.com/dotnet/sdk/pull/48436
Fixes IDE0040, IDE0350, IDE0052, IDE0051 and NU1510
Fixes #

Fix warnings shown in VMR with recent SDK

---

.github/policies/resourceManagement.yml

Onboard breaking change label & bot

Add breaking-change bot

---

src/Tasks/ManifestUtil/SecurityUtil.cs
src/Tasks/ManifestUtil/mansign2.cs

And some minor clean-up changes:
* added readonly to a field
* added parameter names to function parameters

removed dead code that had been removed in NETFX

---

src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs

Address some allocations in BuildRequestEngine

---

src/Framework/BinaryTranslator.cs

Provide HashSet size when possible

---

src/Shared/CopyOnWriteDictionary.cs

Avoid some enumerator boxing in CopyOnWriteDictionary

---

NuGet.config
eng/Version.Details.xml
src/BuildCheck.UnitTests/EndToEndTests.cs

Reverts dotnet/msbuild#11854 to fix official builds.
Passed exp build at https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=11615215.

Revert "[main] Source code updates from dotnet/dotnet"

---

src/Tasks/DownloadFile.cs

[main] Merge tag v17.14.8

---

eng/Versions.props
src/Tasks/DownloadFile.cs

[vs17.13] Merge tag v17.13.26

---

documentation/release-checklist.md

Removing the check from the release checklist template.

Update release checklist template

---

documentation/specs/BuildCheck/BuildCheck-Architecture.md

Update ownership areas for BuildCheck to reflect current team composition.

Update ownership areas for BuildCheck

---

src/Tasks.UnitTests/ResolveAssemblyReference_CustomCultureTests.cs

Added logging capture--I made this fail and it truncated the log, making the failure hard to diagnose.

Improve diagnosability in ResolveAssemblyReference_CustomCultureTests

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props

Update version of package in PrebuiltBaseline for resolve the issue in internal build pipeline

Update version of package in PrebuiltBaseline to 5.11.6

---

src/Build/Definition/Toolset.cs

part of #12122
based on https://github.com/dotnet/msbuild/commit/3d6339e4aff7fe03b8f0041e99dae687332d12e8 in prototype
TaskRegistry multithreaded causes initializations of these fields from multiple threads
synchronizing 3 field initializations (1 with lazy, 2 with double checked locking)
existing tests
~~also removed some dev10 relevant code to simplify~~

adjust Toolset for multithreaded execution

---

eng/Versions.props

DotNetBuildOrchestrator -> DotNetBuildFromVMR

Update VMR orchestrator property

---

azure-pipelines/vs-insertion-experimental.yml

Update source pipeline for insertion yml

Update source pipeline for insertion yml

---

documentation/specs/build-nonexistent-projects-by-default.md

Reacting to https://github.com/dotnet/msbuild/pull/12156#discussion_r2243598285.

Update reasoning in a doc

---

azure-pipelines/vs-insertion-experimental.yml
azure-pipelines/vs-insertion.yml

Adjust schedule to have it executed per hour basis for main & exp insertions

Adjust schedule to have it executed per hour basis for main & exp insertions

---

.vsts-dotnet.yml

Update to MicroBuildSigningPlugin@4

Update to MicroBuildSigningPlugin@4

---

src/Build/BackEnd/Components/Scheduler/SchedulingData.cs

Fixes #
The compiler generated enumerator used in `UnscheduledRequestsWhichCanBeScheduled` is used frequently enough to contribute a significant amount of allocations.
This can be avoided by switching to a struct enumerator that does the same filtering. Here's one of the paths before:
and after:

Use a struct enumerator for unscheduled requests

---

eng/Versions.props
global.json

Version from https://dotnet.microsoft.com/en-us/download/dotnet/10.0.

Update to GA preview 7 SDK

---

.github/workflows/inter-branch-merge-flow.yml
.vsts-dotnet.yml
eng/Versions.props

Add inter-branch merge flow file to get auto-merge run on vs16.11.

[vs16.11] Add inter-branch merge flow file

---

.config/git-merge-flow-config.jsonc

I created a vs18.0 branch, so let's include it in the flow.

Add 17.14->18.0->main automerges

---

src/Build/Instance/ProjectInstance.cs

Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2586915/
the recent change https://github.com/dotnet/msbuild/commit/ac5fef4f089f3d99cda2042b540919c06481f803#diff-40f77147ccc6867c10324ec4ddf8110ede2e43499d939b73ef83c7f5febb7a75 doesn't have null check on an attempt to get property from `_environmentVariableProperties ` collection that can be null.
Handle possible null ref exception.
In the referenced ticket you can find a dump and check the callstack of exception and exact line that throws:
```
0:000> !ip2md 00007FFE726D8367
MethodDesc:   00007ffe71fca150
Method Name:  Microsoft.Build.Execution.ProjectInstance..ctor(Microsoft.Build.Execution.ProjectInstance, Boolean, Microsoft.Build.Execution.RequestedProjectState)
Class:        00007ffe7221bdc8
MethodTable:  00007ffe72018e50 …
```

Add null check for environmentVariableProperties

---

documentation/Property-tracking-capabilities.md

Updated the documentation to clarify property tracking scenarios and event types, including changes to the number of event types and special behavior for property reassignment.

Clarify property tracking capabilities in documentation
