ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs, ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs, src/Shared/FileMatcher.cs, src/Tasks.UnitTests/Unzip_Tests.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.en.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf, src/Tasks/Unzip.cs
Fixes #5169
See #5169
Unzip Task now has "Include" and "Exclude" optional properties to pass a pattern to filter archive entries to be unzipped.
Added following tests:
- CanUnzip_WithIncludeFilter
- CanUnzip_WithExcludeFilter
- CanUnzip_WithIncludeAndExcludeFilter
These 3 test the ability to include/exclude files from the archive unzip.
Unable to translate the resources to all languages. Can someone provide guidance/translations?
=> Added Include/Exclude filtering capability to Unzip Task (#5169)

scripts/Deploy-MSBuild.ps1
Arcade change didn't take into account Deploy-MSBuild, and it failed with a Microsoft.NET.StringTools.dll does not exist error. That was actually very fortunate (thanks ladipro!) since it otherwise would have silently accepted looking into the wrong folder (from a previous bootstrap build) and deploying something that hadn't actually been updated, which would have been extremely confusing.
This only fixes the instance I found, but I would recommend someone look for other similar instances.
Also, assuming this is eventually merged, @BenVillalobos for awareness, since it would have to be reverted also if we revert the arcade change.
=> Fix deploy-MSBuild after arcade change

src/Shared/FileDelegates.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileUtilities_Tests.cs, src/Tasks.UnitTests/AssemblyDependency/GlobalAssemblyCacheTests.cs, src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/AssemblyDependency/Perf.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks.UnitTests/AssemblyDependency/VerifyTargetFrameworkAttribute.cs, src/Tasks.UnitTests/HintPathResolver_Tests.cs, src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs, src/Tasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs, src/Tasks/AssemblyDependency/AssemblyFoldersResolver.cs, src/Tasks/AssemblyDependency/AssemblyResolution.cs, src/Tasks/AssemblyDependency/CandidateAssemblyFilesResolver.cs, src/Tasks/AssemblyDependency/DirectoryResolver.cs, src/Tasks/AssemblyDependency/FrameworkPathResolver.cs, src/Tasks/AssemblyDependency/GacResolver.cs, src/Tasks/AssemblyDependency/HintPathResolver.cs, src/Tasks/AssemblyDependency/RawFilenameResolver.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/AssemblyDependency/Resolver.cs, src/Tasks/InstalledSDKResolver.cs, src/Tasks/SystemState.cs
https://github.com/dotnet/msbuild/issues/5018
Optimize FileExists lookup for Resolver.ResolveFromDirectory used cases, by caching list of files in the lookup directory and verify its existence against it.
RAR Resolver.ResolveFromDirectory, changes needed to propagate new FileIO delegate and fixing related unit tests
Tested to build OrchadCore and Roslyn
Performance saving:
- OrchardCore - none, this project has all references externally resolved and Resolver.ResolveFromDirectory is not called
- Roslyn t:Rebuild - 6% or RAR execution time
- dotnet new mvc; dotnet build - none, seems like all SDK based projects have all references externally resolved
I am not 100% sure if increased code complexity and introduced risk is worth the potential saving.
=> Optimize FileExists lookup

src/Framework/ChangeWaves.cs
Fixes #6077
ChangeWaves.ApplyChangeWave reads the environment variable every single call, regardless of whether or not _cachedWave is set. The parsed change wave is already cached, so let's take advantage of that.
Place the `ShouldApplyChangeWave` check before we pull the environment variable.
Existing tests should suffice.
=> Skip reading environment variable when changewave has already been parsed

eng/config/OptProf.json
[Gen Lu suggested](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1269588) that our previous optprof test "ManagedLangs" may not be what we need anymore. I agree, considering our original test included building & typing and we only care about builds.
Use "VSPE.OptProfTests.DDRIT_RPS_ManagedLangs_Debug" test rather than "ManagedLangs.OptProfTests.DDRIT_RPS_ManagedLangs" for optprof runs.
Will launch an exp/ branch.
This won't solve our optprof issues, but is a small fix while I'm here.
=> Update Optprof Tests 

src/Build/Utilities/NuGetFrameworkWrapper.cs, src/Shared/MSBuildLoadContext.cs
Contributes to https://github.com/dotnet/sdk/issues/15558.
In a single MSBuild process, most of the NuGet binaries are being loaded into more than one `AssemblyLoadContext`.  The ready to run code associated with these binaries can only be used in a single `AssemblyLoadContext`, which means that usage of the assembly in all other contexts must be jitted.  This shows up as an extra 736 methods that get jitted (measured as 147.6ms).
1. Change `NuGetFrameworkWrapper` to use `Assembly.LoadFrom` instead of `Assembly.LoadFile` when using reflection to load NuGet.Frameworks.dll.  This ensures that the assembly is not loaded into the NULL loader context, and unifies the load with later loads of the same assembly.
2. Add all of the NuGet assemblies to the list of well-known assemblies in …
=> Change Load Behavior for NuGet Components

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs, src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
When writing out a binary log we now deduplicate strings and dictionaries. This results in a significant performance increase and binlog size reduction. Performance increase is about 2x on average, size reduction is about 4x on average, but up to 30x for large binlogs.
Add two new record kinds: String and NameValueList. A string record is written the first time we encounter a string we need to serialize. The next time we see the string we only write its index in the total list of strings.
Similarly, NameValueList is a list of key and value strings, used for Properties, environment variables and Item metadata. The first time we're writing out a list we write a record, and subsequent times just the index.
This keeps the binlog format streaming, so if the logging is interrupted midway, we …
=> Deduplicate strings in binlogs

src/Directory.BeforeCommon.targets, src/Shared/FileUtilities.cs
`FEATURE_SPAN` is defined only when building the .NET Core flavor of MSBuild but the feature has been supported everywhere but downlevel .NET Framework for some time.
Removed `FEATURE_SPAN` together with all code conditionally compiled when the flag was **not** defined. Wrapped the code in `#if !CLR2COMPATIBILITY` instead as it's not used when building MSBuildTaskHost.
Existing unit tests. There might be some very minor perf win on non-Windows OSes where we were previously using strings (i.e. Mono).
This is code cleanup.
=> Use Span<T> on all platforms that support it

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
This pull request fixes #3922.
The *MSB4064* error has been provided with additional information about the assembly such as it's version, full name, etc.
---
Changes provided within this commit contains:
* modify the MSB4064 string in resources,
* adjust it's usage in the code throwing this error,
* run the default translations by compilation
---
Results:
The example of MSB4064 printed is presented below:
=> Enhance msb4064 unexpected task attribute error

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/Shared/NodeEndpointOutOfProcBase.cs
Byte arrays are a major source of LOH allocations when streaming logging events across nodes. Allocating a large MemoryStream once and then growing it as needed almost completely removes allocations for byte arrays.
This should significantly improve memory traffic during large builds.
=> Reduce byte array allocations when reading/writing packets

src/StringTools/StringTools.csproj
Fixes #6084
As a dependency of MSBuildTaskHost, StringTools is built for .NET 3.5, in addition to modern .NET Framework and .NET Core.
Made the project built on machines without the 3.5 targeting pack installed by setting `BypassFrameworkInstallChecks`, same as #5621.
Successfully built MSBuild on a clean VM without any 3.5 bits installed.
Thank you @KirillOsenkov for spotting this and suggesting the fix.
=> Enable building StringTools without 3.5 SP1 targeting pack installed

NuGet.config, eng/Packages.props, src/Directory.Build.targets
Fixes CI
The new NuGet security analysis will fail builds that don't meet certain criteria.
`Microsoft.DotNet.BuildTools.GenAPI` binaries were generated by the dotnet/buildtools repo. Looking at the repo it looks like its been replaced with arcade. The arcade feed we have (dotnet-eng) contains the `GenAPI` binaries under a slightly different name (buildtools removed from the name).
Remove the dotnet-core feed because it doesn't point to an internal site.
Look for `Microsoft.DotNet.GenAPI` instead of `Microsoft.DotNet.BuildTools.GenAPI`. It exists on the `dotnet-eng` feed. 
CI will tell us if this doesn't work.
https://docs.opensource.microsoft.com/tools/nuget_security_analysis.html
=> Remove dotnet-core feed & Update GenAPI Assembly Name

eng/config/OptProf.json
This reverts commit 27ff9a7b89b0abfbba7dc049acd892f1c59de240.
The commit has been identified as the source of RefSet perf regression as flagged when inserting MSBuild bits into Visual Studio.
Reverted the change.
Re-ran training scenarios with this change, optimized MSBuild with the resulting OptProf data, and confirmed that it passed Visual Studio insertion gates.
=> Revert "Use debug-specific optprof test (#6106)"

ref/Microsoft.Build.Engine/net/Microsoft.Build.Engine.cs, ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs, ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs, ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs, ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs, ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs, ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs, ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build/Microsoft.Build.csproj, src/Deprecated/Conversion/Microsoft.Build.Conversion.csproj, src/Deprecated/Engine/Microsoft.Build.Engine.csproj, src/Directory.BeforeCommon.targets, src/Directory.Build.props, src/Directory.Build.targets, src/Framework/Microsoft.Build.Framework.csproj, src/Tasks/Microsoft.Build.Tasks.csproj, src/Utilities/Microsoft.Build.Utilities.csproj
When https://github.com/dotnet/msbuild/pull/6141 updated from Microsoft.DotNet.BuildTools.GenAPI to Microsoft.DotNet.GenAPI our reference assembly source generation logic stopped working.
Turns out the new NuGet package targets relies on singular spelling to insert itself after PrepareForRun:
<PrepareForRunDependsOn Condition="'$(GenerateReferenceAssemblySource)' == 'true'">
Update our spelling to singular everywhere now that we're using the new package.
=> Rename GenerateReferenceAssemblySources -> GenerateReferenceAssemblySource

src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs, src/Build.UnitTests/BackEnd/IntrinsicTask_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs, src/Build/Evaluation/ItemSpec.cs, src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Fixes [AB#1261123](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1261123) (feedback ticket)
Checking metadata for matches was taking (#fragments in item) * (#fragments in item to remove) * (#metadata). For many users, this was extremely slow.
Put fragments into a custom MetadataSet object before checking for a match. This takes it from O(n * r * m) to O(m * (n + r)). Since m is normally small, this is a substantial improvement.
Time on a single operation went from ~180 seconds to ~150 ms for the penultimate version. It also passes @cdmihai's extensive unit tests.*
Is there any reason to keep the error for referencing multiple items? As a user, I would expect not-match-on-metadata to ignore metadata and match-on-metadata to ignore the item.
Is it ok …
=> Optimize Match-on-metadata

documentation/specs/rar-as-service.md
During implementing of RAR code we realize we need to revisit some of our decisions from https://github.com/dotnet/msbuild/issues/5536
Updating .md document to reflect our current plan.
=> Modify rar-service design doc

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Shared/UnitTests/ObjectModelHelpers.cs
Fixes two issues when the plugin throws an exception in Plugin.EndBuildAsync during graph builds:
- Plugin.EndBuildAsync got called twice because of a missing finally clause: https://github.com/dotnet/msbuild/compare/master...cdmihai:fixCacheExceptionHandling?expand=1#diff-2b0716a511d8f4ee690ebd5c3a59dec1e3f9a5eab4ab2a80a1018820a658accbR1946
- Plugin.EndBuildAsync got called after the graph build returned, instead of before (which allows the GraphBuildResult to be properly set as failed with the exception from Plugin.EndBuildAsync): https://github.com/dotnet/msbuild/compare/master...cdmihai:fixCacheExceptionHandling?expand=1#diff-2b0716a511d8f4ee690ebd5c3a59dec1e3f9a5eab4ab2a80a1018820a658accbR1730
=> Fix cache exception handling

src/Build/Evaluation/Expander.cs, src/Shared/ErrorUtilities.cs, src/Shared/FileUtilities.cs, src/StringTools/SpanBasedStringBuilder.cs
Fixes #6063
Property expansion has been identified as one of the hot spots in project evaluation and `ExpandPropertiesLeaveEscaped` alone
accounts for almost 20% of overall evaluation time of simple projects.
Several optimizations have been made to the calltree under `ExpandPropertiesLeaveEscaped`. Notably:
- Unnecessary and counter-productive string pinning has been removed.
- A slow `strchr`-like function has been replaced with a simple call to `String.IndexOf`.
- Series of `if`s have been replaced with a `switch`.
- Allocation of `List<object> results` has been eliminated.
- Allocation of temporary substrings extracted from the expression has been eliminated.
The combined performance win is 10% in `ExpandPropertiesLeaveEscaped`, so close to 2% for evaluation overall.
Expander is well …
=> Optimize property expansion

src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs, src/Build/Evaluation/Context/EvaluationContext.cs, src/Build/Globbing/MSBuildGlob.cs, src/Build/Utilities/FileSpecMatchTester.cs, src/Shared/FileMatcher.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Tasks/Unzip.cs
Fixes #6069 
Glob expansion has been identified as one of the performance bottlenecks when building .NET Core projects. The cost is not negligible with a simple Hello World project and gets progressively worse when the project directory (transitively) contains more files, be it source files or completely unrelated files. Since glob expansion is part of project evaluation, it directly impacts Visual Studio performance as well, especially solution load performance.
This PR is a collection of several changes to the globbing logic aiming to make .NET Core project evaluation faster.
- Refactor, simplify, and micro-optimize hot code paths,
- Eliminate exclude patterns early if it's clear that they don't intersect with the include,
- Optimize most common glob patterns to match without regex …
=> Optimize glob evaluation

src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj, src/MSBuild.UnitTests/XMake_Tests.cs, src/Shared/CoreCLRAssemblyLoader.cs, src/Shared/MSBuildLoadContext.cs
Fixes #6186 
#6126 changed the load behavior for NuGet dlls by forcing them to load in the default assembly load context.  This effectively pinned their versions to the SDK, which is not a safe behavior for targets that may wish to carry their own versions of NuGet or other DLLs that they might load.
Rather than pinning specific DLLs, change the behavior to load all DLLs that are in the MSBuild directory in the default assembly load context.  This allows targets to carry their own versions of dependencies, while avoiding loading assemblies that are packaged with MSBuild into multiple assembly load contexts, and thus losing the benefits of precompilation.
Verified that dotnet build hello-world has the correct load and jitting behavior.
Verified that tasks can load their own copies of NuGet …
=> Fix Loading of Plugin Assemblies

src/MSBuildTaskHost/MSBuildTaskHost.csproj, src/StringTools/StringTools.csproj
=> jnm2.ReferenceAssemblies.net35 should be a private dependency

src/Build/Construction/Solution/SolutionFile.cs, src/Build/Construction/Solution/SolutionProjectGenerator.cs, src/Deprecated/Engine/Solution/SolutionWrapperProject.cs, src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #6162
There is currently a property to access the solution file from MSBuild. This adds a similar ability to access solution filter file paths, if relevant.
Added SolutionFilterName as a known property.
None yet.
This will need docs changes, too.
cc @rcmdh.
=> Permit direct access to a SolutionFilterName property Fixes #6162

ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs, ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs, ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs, ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs, src/Tasks/Exec.cs, src/Utilities/ToolTask.cs
Fixes #5724
Added UseUtf8Encoding parameter to ToolTask and removed it from Exec. Exec is a ToolTaskExtension, which is clearly an extension of ToolTask, but this may still count as a breaking change, in which case I could add it back to Exec with `new` to make it compile.
MrTrillian tried this with a reduced repro solution, and it resolved the problem.
=> Permit specifying that we should use utf-8 in ToolTask

documentation/wiki/Providing-Binary-Logs.md
We should have live.msbuildlog.com in our doc that aka.ms/msbuild/binlog points to.
Didn't spend much time thinking on what I added. Let's suggest changes.
=> add live.msbuildlog.com to binary log doc

src/Tasks/Microsoft.CSharp.CrossTargeting.targets, src/Tasks/Microsoft.CSharp.CurrentVersion.targets, src/Tasks/Microsoft.CSharp.targets, src/Tasks/Microsoft.Common.CrossTargeting.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.Common.overridetasks, src/Tasks/Microsoft.Common.props, src/Tasks/Microsoft.Common.targets, src/Tasks/Microsoft.Common.tasks, src/Tasks/Microsoft.Data.Entity.targets, src/Tasks/Microsoft.Managed.Before.targets, src/Tasks/Microsoft.NET.props, src/Tasks/Microsoft.NETFramework.CurrentVersion.props, src/Tasks/Microsoft.NETFramework.CurrentVersion.targets, src/Tasks/Microsoft.NETFramework.props, src/Tasks/Microsoft.NETFramework.targets, src/Tasks/Microsoft.ServiceModel.targets, src/Tasks/Microsoft.VisualBasic.CrossTargeting.targets, src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets, src/Tasks/Microsoft.VisualBasic.targets, src/Tasks/Microsoft.WinFx.targets, src/Tasks/Microsoft.WorkflowBuildExtensions.targets, src/Tasks/Microsoft.Xaml.targets, src/Tasks/Workflow.VisualBasic.targets, src/Tasks/Workflow.targets
Part of #4779
Make Common props, targets and tasks easier to read and understand.
Fixup whitespace and new lines only in Common props, targets and tasks files.
Part of the larger refactoring that'll lead into #1686
- Remove all trailing spaces
- Fixup new lines where necessary
- Add new lines between every block to make it clear.
- Remove unnecessary new lines to reduce scrolling.
NIL
I'll also make sure not to mess up the git blame too much.
To make reviewing easier, I had split up the changes logically rather than a file.
Also, please do not that these changes won't make much difference alone but with other formatting and refactors that follow this will make a world of difference in reading these files.
=> Fixup whitespace and new lines in Common props, targets and tasks

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build/BackEnd/Components/ProjectCache/CacheResult.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCachePluginBase.cs
Turns out it's hard to test the plugin and assert results if CacheResult does not have public members :)
=> Make CacheResult members public

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs, src/Build/Construction/Solution/SolutionProjectGenerator.cs
Fixes internally reported bug
I had previously added SolutionFilterName as a property. I missed one place it needed to be added for it to be passed properly to BuildRequests. This manifested as build failures in unusual cases when the engine generated a metaproj, didn't save it to disk—only into a cache, then queried the cache to see whether a project had already been built with the same name/guid/global properties. Because the third changed, it failed to recognize it and failed the build.
Added the property in the one missing spot.
@jeffkl showed me it working on one repro on his computer. I intend to try it on another repro shortly.
=> Pass SolutionFilterName as a property

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/Shared/MSBuildNameIgnoreCaseComparer.cs
We are currently working on bringing up .NET on the IBM Z architecture (s390x-ibm-linux), which uses big-endian byte order.  During that process we have run into a couple of endian-specific bugs in msbuild code.
* In MSBuildNameIgnoreCaseComparer::GetHashCode, when reading pairs of characters aliased to an int, handle the single last remaining char correctly on big-endian systems.
* In NodeProviderOutOfProcBase, byte-swap the packet length on big-endian systems.
On IBM Z, a msbuild package built with this patch successfully builds and executes a "hello world" program.  We were also able to successfully bootstrap msbuild (build it with itself) on IBM Z.  (This of course also requires the work-in-progress dotnet runtime port, and for the bootstrap an endian bugfix to nuget is also …
=> Fixes for big-endian systems

src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.en.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
This pull request updates the general "switch" description in the help message.
This can be considered as a follow-up of #5786 delivery, where double-dash switch indicator has been added.
---
The changes contain:
* Help message update: added third indicator's option and removed "*both*" as it's now invalid
* Applied changes to the localizations
=> General "switch" description in help message - update for "--" indicator

src/Build/Evaluation/ItemSpec.cs, src/Build/Utilities/EngineFileUtilities.cs, src/Shared/EscapingUtilities.cs, src/Shared/UnitTests/EscapingUtilities_Tests.cs
Fixes #6061 
`EngineFileUtilities.GetFileList` has been identified as one of the performance bottlenecks when building .NET Core projects. Since this code is called as part of project evaluation, it directly impacts Visual Studio performance as well, especially solution load.
Tweaked the code under `GetFileList`:
- Smarter order of wildcard checks to optimize for the common case.
- Optimized hex number parsing and wildcard detection.
Existing unit tests for correctness, ETL traces for performance.
This change together with #6151 is showing about 30% less time spent in this particular function when building a Hello World .NET Core project with the Framework version of MSBuild. It's an OK win for project evaluation perf but translates to less than 1 ms of total command line build time.
This …
=> Optimize EngineFileUtilities.GetFileList

eng/Packages.props, src/Build.UnitTests/Definition/ToolsetConfigurationReader_Tests.cs, src/Build.UnitTests/Definition/ToolsetReader_Tests.cs, src/Build.UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs, src/Build.UnitTests/Evaluation/ToolsetConfigurationNet5_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Definition/ProjectCollection.cs, src/Build/Definition/ToolsetConfigurationReader.cs, src/Build/Definition/ToolsetReader.cs, src/Build/Definition/ToolsetRegistryReader.cs, src/Build/Evaluation/IntrinsicFunctions.cs, src/Build/Microsoft.Build.csproj, src/Build/Utilities/RegistryKeyWrapper.cs, src/MSBuild/MSBuild.csproj, src/MSBuild/XMake.cs, src/Shared/FrameworkLocationHelper.cs, src/Shared/ToolsetElement.cs, src/Tasks.UnitTests/Copy_Tests.cs, src/Utilities/Microsoft.Build.Utilities.csproj
This change will give NET5.0 MSBuild the option to read toolset information from the configuration file ONLY if ToolsetDefinitionLocation is set to 'ConfigurationFile'. Otherwise everything should work the exact same way as before.
This change is beneficial as it allows net5.0 MSBuild to evaluate projects that only net framework MsBuild could before. Since ConfigurationFile wasn't an option in net5.0 before (Due to System.Configuration being only net472), toolsets available to net5.0 MsBuild was minimal, but with this change a net5.0 MsBuild user could specify ConfigurationFile as the ToolsetDefinitionLocation when creating a ProjectCollection and more toolsets would be available depending on the MsBuild.exe provided. 
Updated all the System.Configuration references to …
=> Toolset configuration net5.0

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/dotnet/msbuild/issues/5981
Despite targeting x64 during builds, x86-bitness al.exe runs anyway, throwing a warning because of it.
Before calling the AL task check if we're targeting x64 and pass it along with the tools sdk path.
Create a winforms project (any really), create a _cultured_ resx file (insert monacle emoji here), set it as embedded resource, build the project with /p:Platform=x64. You get `ALINK : warning AL1073: Referenced assembly 'mscorlib.dll' targets a different processor [C:\src\projects\templates\Win
FormApp\WinFormApp\WinFormApp.csproj]` without the fix.
Tested on a bootstrap build on the repro.
I took into consideration that changing this logic within the code itself could break a lot of people. Consider that it's a public class that many …
=> Pass x64 architecture to al.exe when targeting x64

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs, src/Build/Construction/Solution/ProjectInSolution.cs
Fixes #6236
#5950 introduced a call to `Path.GetFullPath()` to get a path that is normalized.  However, in some cases Visual Studio stores unsupported paths which will cause `Path.GetFullPath()` to throw.
`Path.GetFullPath()` can also throw a `PathTooLongException` which is now handled.
Revert to legacy code path of just calling `Path.Combine()` then do the `Path.GetFullPath()` in a `try...catch` on a best effort.
Regression test added
https://developercommunity.visualstudio.com/t/msbuild-failing-with-web-site-project-in/1359528
=> Handle unsupported paths in ProjectInSolution.AbsolutePath

src/Tasks.UnitTests/ResourceHandling/GenerateResourceOutOfProc_Tests.cs, src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/StateFileBase.cs, src/Tasks/SystemState.cs
Fixes #6242
Implementing new binary format of RAR cache can clash between MSBuild versions when version in IDE differs to version used for build from command line.
- Lower verbosity of 'MSB3088: Could not read state file' message
- Change default naming schema of RAR cache
=> Fix rar cache incompatibility warning message (#6242)

src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs
This property has both summary comments and inheritdoc. It causes a docs build warning to have both.
Contributes to dotnet/dotnet-api-docs#5411.
=> Remove inheritdoc

src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Fixes #6221
When the project load setting `IgnoreInvalidImports` is set, the caller expects imports that couldn't be loaded to just be ignored in a best effort attempt to load the project.  However, the code path of the project expression evaluating to an empty string was overlooked in #2720
I've checked the `ProjectLoadSettings` in the evaluator when the project import expression evaluates to an empty string and logged an event and skipped the import
I've added a unit test
The first commit is the implementation, the second commit is just a conversion to Shouldly
=> Ignore invalid import when expression empty

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #
VS Publish providers supports an option called ReadyToRun (R2R) by compiling application assemblies as ReadyToRun format.
ClickOnce publishing does not support this option.
The change adds support for enabling R2R option in ClickOnce publish.
To do so, the _DeploymentComputeClickOnceManifestInfo ClickOnce target checks the PublishReadyToRun property when PublishSingleFile is not enabled (loose files scenario). If it is true, then it will replace the R2R'ed assemblies within ClickOnceFile group with the corresponding R2R assemblies from the obj\...\R2R folder.
In addition, it calls SignFile task to sign the R2R application image.
CTI has testing the R2R configuration with top 50 NuGet packages. In addtion, other normal ClickOnce publish scenarios have been tested with top 50 NuGet …
=> Enable Ready To Run option for ClickOnce publish

src/Tasks.UnitTests/OutputPathTests.cs, src/Tasks/Microsoft.Common.CrossTargeting.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.Common.props, src/Tasks/Microsoft.Common.targets
Fixes internally reported bug
EnsureTrailingSlash and HasTrailingSlash use slightly different escaping mechanisms in some cases. Reverting to prevent failures.
=> Revert broken code cleanup

src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Fixes #6224
Sent inner exception's full ToString() information instead of just its message.
=> Provide more information with BadImageReferenceException

.vsts-dotnet-ci.yml, .vsts-dotnet.yml, README.md
Fixes https://github.com/dotnet/msbuild/issues/6249
This should finalize our master to main transition.
Remove master as a trigger.
exp/ branches should default to `main` for optprof data now.
Rename master to main in our primary readme file.
There are plenty of references to master in our documentation, but they'll forward to main so our links won't be broken.
=> Change references from master to main

src/Build/BackEnd/Components/Logging/LoggingService.cs
Customers reported issues like:
```
Error The "ResolveAssemblyReference" task failed unexpectedly.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
at Microsoft.Build.BackEnd.Logging.LoggingService.GetWarningsToBeLoggedAsErrorsByProject(BuildEventContext context)
at Microsoft.Build.BackEnd.Logging.TaskLoggingContext.GetWarningsAsErrors()
at Microsoft.Build.BackEnd.TaskHost.get_WarningsAsErrors()
at Microsoft.Build.BackEnd.TaskHost.ShouldTreatWarningAsError(String warningCode)
at Microsoft.Build.Utilities.TaskLoggingHelper.LogWarning(String subcategory, String warningCode, String helpKeyword, String helpLink, String file, Int32 lineNumber, Int32 columnNumber, Int32 …
```
=> Verify that a key is in the warningsAsErrors dictionary before using it

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs, src/Build/Construction/Solution/ProjectInSolution.cs
Trying to build a solution with MSBuild.exe that contains a web site project causes MSBuild.exe to crash. This only affects the command line but includes _dotnet build_. It requires a relative path in the solution file and we've received 2 customer reports so far.
In those cases, we would return "C:\foo\http://localhost:8080" as an absolute path and then crash msbuild.
New unit test added. We will reach out to manual test team and compat test team to find out if website projects are included in their matrix.
Low, new code path has a `try...catch` and falls back to previous behavior.
@Forgind @cdmihai @BenVillalobos 
Previously a property in the MSBuild API would return a string containing an "absolute path" but did not expand path segments like `..\`.  We changed the code to call …
=> Handle unsupported paths in ProjectInSolution.AbsolutePath (#6238)

src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
We have the `MSBUILDADDITIONALSDKRESOLVERSFOLDER` environment variable as a test hook to specify where SDK Resolvers should be loaded from.  However, SDK resolvers need to be multi-targeted between .NET Framework and .NET (Core).  So setting this environment variable to where you have a .NET Framework SDK resolver means that `dotnet` builds will fail, and setting it to a .NET resolver means `msbuild` builds will fail.
So this adds runtime-specific test hook environment variables: `MSBUILDADDITIONALSDKRESOLVERSFOLDER_NETFRAMEWORK` and `MSBUILDADDITIONALSDKRESOLVERSFOLDER_NET`.
=> Support runtime-specific SDK resolver test hook

documentation/wiki/UnGAC.md
I'd like to have an easy link to send folks that have GAC issues with msbuild. aka.ms/msbuild/ungac should do the trick. There's no good place to point that link to, so here's a basic doc that should get folks unblocked if they really are seeing a GAC issue with MSBuild.
Added a doc.
=> Basic doc on msbuild and the gac

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/EvaluationLinkMocks/MockProjectLink.cs, src/Build/Definition/Project.cs, src/Build/ObjectModelRemoting/DefinitionObjectsLinks/ProjectLink.cs
Fixes #
Perf ddrits regression in ProjectServices implementation of this.
This GetAllGlobs override is unused anymore since CPS has been changed to use the GetAllGlobs(evaluationContext)
Remove newly added GetAllGlobs override.
=> Remove unused GetAllGlobs override in ProjectLink

src/Build/Utilities/NuGetFrameworkWrapper.cs
Fixes #6289
#6126 changes the way that `NuGet.Frameworks.dll` is loaded to be used by `NuGetFrameworkWrapper` from a call to `LoadFile` to a call to `LoadFrom.  The path passed in to the `Load*` call is the same in both cases, but the behavior is different when running on .NET Framework.
On .NET Framework, calling `LoadFile` results in IJW loading rules being followed, and a different copy of `NuGet.Frameworks.dll` 
than the one requested being loaded.  It also appears to match the one loaded into the LOAD context.  Calling `LoadFrom` results in the specified assembly being loaded, but it doesn't match the copy of the assembly loaded into the LOAD context.  Thus, it remains in the LOADFROM context instead of being promoted to the LOAD context.
Later on, there is a collision between code …
=> Fix Bootstrap Build

src/Tasks/AssemblyDependency/AssemblyInformation.cs
Fixes #6200 
`InvalidOperationException` was being thrown by `AssemblyInformation.CorePopulateMetadata`, causing the ResolveAssemblyReference task to fail rather than disregarding the file.
I copied the code from AssemblyNameExtension to ensure there is metadata present before getting a metadata reader: https://github.com/dotnet/msbuild/blob/6819f7ab06c3f43e83ff4059d417395e0af06c01/src/Shared/AssemblyNameExtension.cs#L214-L231
I looked for unit tests for AssemblyInformation, but could not find any, so I didn't add a unit test for this case. However, I successfully built the project that was reproducing the error in #6200, indicating that the change did indeed fix the issue.
=> Throw BadImageFormatException when missing PE metadata

src/Build.UnitTests/BackEnd/MockLoggingService.cs, src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs, src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs, src/Build/BackEnd/Components/Logging/ILoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs, src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs, src/Build/Instance/TaskFactories/TaskHostTask.cs, src/MSBuild/OutOfProcTaskHostNode.cs, src/Shared/TaskHostConfiguration.cs
Fixes https://github.com/dotnet/msbuild/issues/6306
https://github.com/dotnet/msbuild/pull/6174 didn't properly account for warningsaserrors and warningsasmessages together. This PR makes each taskhost aware of both WarningsAsMessages and WarningsAsErrors when telling tasks whether or not an error should be treated as a warning.
LoggingService and TaskLoggingContext expose a `GetWarningsAsMessages` to each taskhost for them to store.
No changes to IBE8 API
Taskhosts first check if a warning would be treated as a message when telling tasks whether or not a warning should be treated as a warning.
Added test cases for WarningsAsMessages getting translated properly for the OOPTHN.
Added test cases for WarningsAsErrors and WarningsAsMessages for the same warning code.
Added test case for …
=> Properly Consider WarningsAsMessages In TaskLoggingHelper's `HasLoggedErrors`

src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileUtilities_Tests.cs
For some reason, the pre-caching change seems to fail in the installer repo at the build step because of a failing relative path calculation. This version seems to work.
=> Change relative path calculation

eng/Versions.props, src/MSBuild/app.amd64.config, src/MSBuild/app.config
Branding update for 17.0.
I skipped the readme changes, since I what we normally put would not be true at this point, since we haven't forked for 16.11 or even 16.10, and changes in main (we expect) will go into 16.10/11 still.
@olgaark, should I change `..\..\..\Microsoft\VC\v160\Microsoft.Build.CPPTasks.Common.dll` to `..\..\..\Microsoft\VC\v170\Microsoft.Build.CPPTasks.Common.dll`?
Are there any other changes that need to be made for a major version release?
=> branding update

src/Tasks/ManifestUtil/ApplicationManifest.cs
cc @ghogen 
Contributes to dotnet/dotnet-api-docs#2053.
For doc comment guidelines, see https://github.com/dotnet/dotnet-api-docs/wiki.
=> Improve doc comments

documentation/wiki/ChangeWaves.md, src/Shared/Constants.cs, src/Tasks.UnitTests/AssignTargetPath_Tests.cs, src/Tasks/AssignTargetPath.cs
Fixes #2795
and indirectly fixes https://developercommunity.visualstudio.com/t/copytooutputdirectorypreservenewest-ignored-inside/1332219?from=email&viewtype=all#T-ND1363347
There's currently no way to include items in a project such that:
1. Visual studio sees them in a specific folder (via `<Link>`).
2. They are published to a user-defined path (currently controlled via `<Link>`)
Modify the `AssignTargetPath` task to return early if `TargetPath` metadata is already set on a particular item.
Here's the repro I'm using:
```xml
<TargetFramework>netstandard2.0</TargetFramework>
<ItemGroup>
<Content Include="Files\**">
<Link>Files\%(Filename)%(Extension)</Link>
<TargetPath>%(Filename)%(Extension)</TargetPath> …
```
=> Allow Custom CopyToOutputDirectory Location With TargetPath

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/BuildManager/BuildRequestData.cs, src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs, src/Build/BackEnd/Shared/BuildRequestConfiguration.cs, src/Build/Definition/ProjectLoadSettings.cs, src/Build/Evaluation/Evaluator.cs, src/MSBuild.UnitTests/XMake_Tests.cs, src/MSBuild/XMake.cs
Fixes #6281
`BuildRequestDataFlags` and `ProjectLoadSettings` are set during `/t:restore` in a best effort to run the Restore target in hopes that it will correct the potentially bad state that a project is in.  Visual Studio also sets `ProjectLoadSettings.IgnoreMissingImports` so that an unresolved MSBuild project SDK doesn't prevent loading of a bad project so it can give the user an error and let them edit the file.
However, this means that from the command-line an unresolved SDK doesn't fail `/t:restore`.  This is because the missing "import" is ignored and non-existent targets are ignored so the build succeeds.
Introduced two new `BuildRequestDataFlags`:
* `SkipNonexistentNonTopLevelTargets` - A new flag to be used in this context to tell the build to ignore non-existent targets but …
=> Fail Restore when an SDK is unresolved or entry target does not exist

src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/Build/Evaluation/Evaluator.cs
Some loggers depended on ProjectStartedEventArgs.GlobalProperties being not null and set. It will take a long time to move them to ProjectEvaluationFinished (needs to bump MSBuild dependency to 16.10).
For now log GlobalProperties in both places (ProjectStarted and ProjectEvaluationFinished). Hopefully the deduplication will save us from any significant increase in binlog size.
Fixes https://github.com/dotnet/msbuild/issues/6341
=> Bring back ProjectStarted.GlobalProperties

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs, src/Build/Construction/Solution/SolutionFile.cs
Fixes #6317
We previously added support for building solution filter files. With that support, we did not allow them to contain lists of projects with a trailing comma or comments. These are both permitted by VS, so this PR updates our handling of solution filter files to permit building with trailing commas or comments.
Also adds a test.
=> Permit comments and trailing commas in solution filter files

src/Build/BackEnd/Components/Scheduler/IScheduler.cs, src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs, src/MSBuild/CommandLineSwitches.cs, src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.en.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf, src/MSBuild/XMake.cs
Change the DetailedSummary command-line switch from parameterless to parameterized, allowing the user to have control and explicitly set it to false if needed, overriding the default of true when the verbosity is diagnostic.
This is backwards compatible with the previous behavior, so if /ds is specified, it is equivalent to turning it on.
Fixes https://github.com/dotnet/msbuild/issues/4409
=> Allow turning detailed summary off

ref/Microsoft.Build.Utilities.Core/net/Microsoft.Build.Utilities.Core.cs, ref/Microsoft.Build.Utilities.Core/netstandard/Microsoft.Build.Utilities.Core.cs, src/Shared/FrameworkLocationHelper.cs, src/Tasks.UnitTests/ResourceHandling/GenerateResourceOutOfProc_Tests.cs, src/Tasks/GenerateResource.cs, src/Utilities/ToolLocationHelper.cs
GenerateResource tests were failing when only VS 2019 and 10.0 Windows SDK is installed. I suspect the task itself would also fail if run with ExecuteAsTool.
The problem is that we started look up with .NET 4.6.1 and lower. Start lookup with .NET 4.8 instead and fallback down the chain. This should still find all earlier SDKs too.
Introduce latest versions of Visual Studio too.
Fixes https://github.com/dotnet/msbuild/issues/6266
=> Make GenerateResource look up resgen.exe in 10.0 SDK

src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Shared/Constants.cs
It would be very useful to embed more than just the project files into the binlog. For example, project.assets.json is a common request: https://github.com/dotnet/msbuild/issues/3529. global.json or nuget.config would be other examples. Some users may want to embed all *.cs files as well.
Add a special EmbedInBinlog item type recognized by BuildEventArgsWriter. If after evaluation the items contain EmbedInBinlog, all such items will be logged if the evaluated include points to a full file path that exists on disk. A given file can be mentioned more than once, but will only be embedded once. If a file doesn't exist or is empty, it will not be embedded. If the item is added from a target (after evaluation is done), it will not be embedded.
Checking for EmbedInBinlog is done in …
=> Add support for embedding arbitrary files into binlog

src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
Don't use Program Files\Reference Assemblies as that might not exist for 64-bit.
Pass ITestOutputLogger to MockLogger to get the full log in case of failure.
Search for a log substring that will only be there in case of success. Even successful logs can contain [] when the file is at the root of the directory so RecursiveDir will be empty.
Fixes https://github.com/dotnet/msbuild/issues/6267
=> Fix TasksCanAddRecursiveDirBuiltInMetadata()

src/Build/Construction/Solution/SolutionFile.cs, src/Build/Construction/Solution/SolutionProjectGenerator.cs, src/Deprecated/Engine/Solution/SolutionWrapperProject.cs, src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd, src/Tasks/Microsoft.Common.CurrentVersion.targets
We decided that adding support for a SolutionFilterName property was premature. The point of a solution filter is to permit loading or building only a subset of a more complicated solution file. Of note, however, it is not to permit changing behavior based on which subset is being built—if a full solution is buildable, any associated solution filter file should be as well. Furthermore, if that information is not properly propagated within Visual Studio, it may lead to different behavior when building from the command line versus Visual Studio.
=> Remove SolutionFilterName support

ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks/Microsoft.Build.Tasks.csproj
Fixes #6279.
This task isn't used in the standard .NET SDK build process and was never enabled for the .NET Core/5.0+ flavor of MSBuild.
Include/stop removing task class from core flavors.
Unit tests.
=> Enable FindInvalidProjectReferences for .NET Core

.vsts-dotnet.yml, eng/Publishing.props, eng/Version.Details.xml, global.json
V3 publishing is much faster and is required for publishing to the "VS 17.0" channel.
Followed this: https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3
Add eng\publishing.props with single propertygroup `PublishingVersion` set to 3.
Pass `publishingInfraVersion: 3` to post-build yml.
Should launch an exp/ branch to verify this
Added `exp/bevillal/v3-publish-test` as a default channel to "VS 17.0" and kicked off a pipeline build here: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4655204&view=results
=> Move to V3 publishing

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs
The project cache plugin can fail with exceptions from any of its APIs. Currently some exceptions from certain APIs get lost and the build fails with no errors.
This PR ensures that:
- no exceptions get lost
- the build is marked as failed when any plugin API fails
- `BuildManager.ExecuteSubmission(BuildSubmission)` always completes the build submission with the exception when it detects that it's running in a detached thread.
- `BuildManager.BuildGraph` observes the exceptions captured above and rethrows them to mimic what happens when `ExecuteSubmission(BuildSubmission)` does not run in a detached thread.
- `BuildManager.EndBuild` marks the overall build result as failed if exceptions are thrown in `BM.EndBuild`.
Added unit tests to ensure that exceptions thrown from any possible plugin …
=> Fix project cache plugin exception handling

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheException.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/Microsoft.Build.csproj, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf, src/MSBuild/XMake.cs, src/Samples/ProjectCachePlugin/AssemblyMockCache.cs
Treat project cache exceptions similar to how MSBuild treats exceptions from `ILogger.Initialize` and `ILogger.Shutdown`. This avoids the "file an issue against the MSBuild team" console messages.
Treat errors logged by the project cache similar to how MSBuild treats errors logged by tasks. Which is to check whether they logged an error and if yes, shut the build down (project cache does not do "continue on error").
- Adds a `ProjectCacheException` which gets handled similarly to `LoggerException`
- Beefed up the existing exception handling tests to also assert what happens when the project cache logs errors instead of throwing exceptions.
=> Improve plugin exception logging

documentation/wiki/ChangeWaves.md, src/Build/BackEnd/Shared/BuildRequestConfiguration.cs, src/MSBuild.UnitTests/XMake_Tests.cs, src/MSBuild/XMake.cs
#6312 made (good, IMO) changes to the behavior of `-restore` and `-t:restore` invocations of MSBuild in malformed projects. Since these are new errors, though, the new behavior might fail passing builds. So put it behind a change wave Just In Case.
=> Changewave 16.10 for restore failures

eng/Packages.props, src/MSBuild/app.amd64.config, src/MSBuild/app.config
MSBuild redistributes System.Memory but does not binding redirect it. This causes the QB cache plugin to fail (qb.exe works because it has binding redirects, but the plugin fails because it's a dll and dlls don't have binding redirects).
Both MSBuild and VS ship with System.Memory 4.0.1.1 so this should not have any negative consequences.
In general, shouldn't MSBuild add binding redirects for [all the assemblies that it redistributes](https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Package/MSBuild.VSSetup/files.swr#L39-L52)? I see that MSBuild redistributes a bunch of assemblies but does not binding redirect them. @danmoseley @ericstj
=> Add binding redirects for all assemblies redistributed by MSBuild

src/Build/Xml/XmlReaderExtension.cs
Fixes #2576
The code already has support for parsing project files as read-only when we know that we're not going to be asked to write them back to disk. This flag is currently unused because the initial implementation in #3584 introduced a regression related to whitespace in attribute values (#4210).
Trivially reverted part of #4213 that addressed the regression and added a hack to make `XmlReader` behave the same as `XmlTextReader`.
Existing unit tests for correctness and ETW for performance. `XmlDocumentWithLocation.Load()` is ~26% faster with this change compared to baseline when building .NET Core projects. This translates to about 10 ms per one incremental CLI build of a Hello world application.
=> Ignore comments and whitespace when parsing read-only XML files

src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs, src/Build/Instance/ProjectItemInstance.cs, src/Framework/TaskItemData.cs, src/Shared/TaskParameter.cs, src/Utilities/TaskItem.cs
Fixes https://github.com/dotnet/msbuild/issues/6379
We have a situation where we are in a worker node and a task runs in a separate AppDomain and logs a TaskParameterEventArgs. Since logging is asynchronous there's a risk that by the time the node packet translator accesses the TaskParameterEventArgs.Items the AppDomain is already unloaded and we crash when trying to enumerate item metadata.
Detect that we're in another AppDomain and eagerly take a snapshot of task items with all metadata.
I wasn't able to reproduce the issue, but I will ask the customer to validate with the bootstrap MSBuild I built from this PR and see if it goes away.
=> Snapshot Items of TaskParameters from another AppDomain

README.md, eng/Versions.props, src/MSBuild/app.amd64.config, src/MSBuild/app.config
While mainline development is now focusing on 17.0, we want to have the 16.11 branch ready in case we end up contributing.
Setting up a branch for MSBuild inserted into Visual Studio 16.11.
Grepped the tree for other occurrences of 16.10.
=> Update branding for 16.11

eng/Versions.props, src/MSBuild/app.amd64.config, src/MSBuild/app.config
Mainline development is switching to Visual Studio 17.0.
Merging current `vs17.0` branch into main to pick up branding changes.
Grepped the tree for other occurrences of 16.10.
=> Update branding for 17.0

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/Expander.cs
Fixes #6413
This is a regression introduced in #6128. MSBuild crashes when evaluating a project where a property function returns null and its result is concatenated with another non-empty value.
Add a null check.
Fixed and extended the relevant test case.
Enable "Hide whitespace changes" when reviewing this change.
=> Fix NullReferenceException when expanding property functions that return null

eng/Versions.props, src/Build.UnitTests/BinaryLogger_Tests.cs, src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs
Work item (Internal use): [AB#1325685](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1325685)
Fixes #6436 which causes this crash in cases where MSBuild's result
caching is turned on (generally this is for large builds in 32-bit
MSBuild).
Customers with large builds see MSBuild crashes.
Yes. Worked in 16.8, regressed in 16.9.0 because of #5997
Validated minimal repro (using forced caching) passes where it failed on released bits.
Low. Additional guarding falling into existing case so log output shouldn't suffer.
=> Ensure context is not cached before logging info

src/Tasks/Microsoft.CSharp.CurrentVersion.targets, src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets
The CSC task was not being passing EditorConfig Files when invoked as part of XamlPreCompile. In addition the `GenerateMSBuildEditorConfigFileCore` task needs to have been run to actually generate the required file. Fixes #6323.
Source Generators fail in WinUI 3 projects.
Never fully worked. Started passing analyzers to the XamlPreCompile compiler in #6096 (16.9), but didn't pass config files, which are often needed for source generators.
@chsienki locally patched and validated against repro provided by partner.
Low. Conceivably breaks projects that depend on the current behavior (pass config files that are incorrect for this step) but we know of no such cases.
=> Fix generated editor config files for xaml precompile

.vsts-dotnet.yml
Fixes optprof and RPS runs for vs16.9 branch
=> Update VS version to use in optprof and RPS runs

eng/Versions.props, src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs, src/Build/Construction/Solution/SolutionProjectGenerator.cs
Fixes #6373
Solution metaprojects should have a target for each project they contain, so that you can build a single project or set of projects in the context of the solution. A regression in 16.10 means that instead, specifying a project name as a target when building a solution attempts to build a target with that name for every project in the solution.
Customers cannot build a subset of a solution by specifying a project between #6282 and this PR.
Yes, from 16.9. This bug was introduced in #6282. The critical line is line 786 of SolutionProjectGenerator, though all similar instances were reverted in this case. Note that as #6282 is an agglomeration of functionally unrelated changes, no other files in #6282 relied on the changes in SolutionProjectGenerator.
Reverted the part of #6282 …
=> Building a subset of a VS solution at the command line causes MSB4057

src/Tasks/ManifestUtil/SecurityUtil.cs
Fixes # DevDiv 1308643
ClickOnce publishing build task invokes signtool.exe installed by the ClickOnce bootstrapper MSI to sign published files. The MSI writes the signtool.exe path under the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ClickOnce\SignTool regkey. 
On 64 bit OS, the MSI writes to this regkey under the WoW node. On VS64/msbuild64, the signing task tries to read the regkey from the non-WoW node where it does not exist. This causes ClickOnce Publish in VS64 to fail.
Fix the signing task to look in the Registry32 view of the registry for the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ClickOnce\SignTool key.
Verified fix on x86 and x64 VS.
=> Fix signing tool lookup for VS64

src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs, src/Build/Construction/ProjectRootElement.cs, src/Build/Evaluation/ProjectStringCache.cs
Fixes #6456
Calling `Xml.Reload` on a `Microsoft.Build.Evaluation.Project` leaks memory because the old `XmlDocument` is not removed from the `ProjectStringCache`.
`ClearAnyCachedStrings` is now called on the document that's not retained by `ProjectRootElement`. This would normally be the old document being replaced by `Reload`.
Existing unit tests and manually verified using the repro snippet in #6456. 
Targeting VS16.11 with this change as we've seen multiple feedback tickets related to this. In pathological scenarios the leak really OOMs the Visual Studio process.
Going forward we should see if we can eliminate the error-prone cache altogether (#5444).
=> Fix memory leak in ProjectRootElement.Reload

src/Build/BackEnd/BuildManager/BuildManager.cs, src/Samples/ProjectCachePlugin/AssemblyMockCache.cs
Hopefully fixes https://teams.microsoft.com/l/message/19:3212bf033f4c4b5198643a04fa1048fa@thread.skype/1620160142660?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1620160142660&teamName=.NET%20Developer%20Experience&channelName=MSBuild&createdTime=1620160142660
Protected writes to _overallBuildSuccess with _syncLock
=> Lock writes to _overallBuildSuccess

eng/Versions.props
This avoids diffs in the genapi-generated public interface that are happening
because of changes in generated code for records in Roslyn 3.10.
=> Use packaged C# compiler

src/Shared/TranslatorHelpers.cs, src/Tasks.UnitTests/GetSDKReference_Tests.cs, src/Tasks/GetSDKReferenceFiles.cs
I think this is almost right, but TranslatorHelpers needs System.Collections.Concurrent on .NET 3.5, or I need to be able to translate a concurrent dictionary without translating it. (?) Any idea on how I can get around that?
=> Remove BinaryFormatter from GetSDKReferenceFiles

src/Tasks/StateFileBase.cs, src/Tasks/SystemState.cs
~~Based on #6350 for convenience. That PR centralized the cache deserialization logic for StateFileBase, so it would be easy to accidentally overwrite this change with that one when resolving merge conflicts.~~
The precomputed cache from https://github.com/dotnet/installer/pull/10037 lives in Program Files after it's installed on a new computer. Program Files can only be accessed with admin privileges, which not all users have and those that have generally wouldn't expect. This permits reading the precomputed cache even without admin rights.
Switch how the file is read.
=> Rar permissions fix

src/Shared/TranslatorHelpers.cs
Fixes #6389
Strong Name Key Pairs aren't available on .NET 6+, and although it's fine to serialize null and remember that's what it is, deserializing involves assigning null to something that shouldn't exist, which is throwing an error, invalidating all RAR caches.
This fixes that problem.
No longer serialize or deserialize a null value for KeyPair.
Allowed precomputed cache to function properly. (Local test only)
/cc: @rokonec
=> Remove KeyPair deserialization

src/Build.UnitTests/BackEnd/Scheduler_Tests.cs, src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/Components/Logging/LoggingContext.cs, src/Build/BackEnd/Components/Scheduler/SchedulableRequest.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Build/BackEnd/Shared/BuildRequest.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Proxy builds are what project caches issue on cache hits. They are a cheap version of the expensive targets that were avoided by the cache. They need to produce the same properties and items the expensive target produced, but with none of the CPU / IO expensive stuff.
The proxy builds are super cheap because they only return properties / items. It is not worth scheduling them to out of proc nodes because:
- IPC overhead
- when they get scheduled to out of proc nodes they get re-evaluated. This is wasted computation because proxy builds are guaranteed to get evaluated on the scheduler node (where the inproc node resides)
Scheduling proxy builds to the inproc node makes a project cache build with full cache hits 16% faster.
Duplicated what the scheduler does to confine traversal projects to …
=> Schedule proxy builds to inproc node

src/Tasks/AssemblyRegistrationCache.cs, src/Tasks/DependencyFile.cs, src/Tasks/ResGenDependencies.cs, src/Tasks/ResolveComReferenceCache.cs, src/Tasks/StateFileBase.cs, src/Tasks/SystemState.cs
This broke an internal test (see https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/326484).
I tested reverting the PR that removed the [Serializable] attributes as well as just adding them back in parallel. Both PRs worked:
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/327003
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/327004
So I would suggest just taking the smaller change to unblock master without creating unnecessary future changes.
/cc: @rainersigwald @BenVillalobos
=> Add [Serializable] to PortableLibraryFiles and other similar classes

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes # https://github.com/dotnet/msbuild/issues/5981
MSBuild didn't support customers using the x64 AL.exe tool by default when their projects targeted x64. https://github.com/dotnet/msbuild/pull/6207 implemented a fix to include `x64` in the path when relevant, but [this commit](https://github.com/dotnet/msbuild/pull/6207/commits/ca5012a3532a86cb9cfe841d431453cb3b0db250) mistakenly forgot to update one property name which results in an empty parameter being passed. This results in the x86 version of AL.exe being the default choice.
This fix changes the name of the property to the correct one that is set just before AL is called.
Customer's that want to compile .resx files using 64-bit AL.exe require a workaround to do so. This change will allow this workaround to become default …
=> Use new variable for the AL tool path

.vsts-dotnet-ci.yml
These should have been changed when we updated past .NET Core 2.1 but were missed.
Fixes these warnings:
Should be futureproof since it's just "upload everything that's not `net472`".
=> Update test-upload TargetFramework

src/Build/Construction/Solution/SolutionProjectGenerator.cs
Solution metaprojects are assembled in a confusing way that impacts what
targets can be hooked into via BeforeTargets/AfterTargets. Prior to this
change one couldn't hook before the build would attempt to traverse the
list of projects in the solution.
Extend the "list of targets we know we'll create shortly" list to
include the things that are in the `InitialTargets` list and
`GetSolutionConfigurationContents`.
Fixes #6452.
See related #4694, #5109.
=> Add solution-validation targets as hook points

scripts/Deploy-MSBuild.ps1, src/Build/BackEnd/BuildManager/BuildManager.cs
- updated VS deploy script to copy more files needed during runtime
- added option to break into the BuildManager via a new env var. This makes it super easy to debug msbuild running in devenv without having to copy over local bits
=> Improve vs debugging

src/Build.UnitTests/BackEnd/NodePackets_Tests.cs, src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Framework/BuildMessageEventArgs.cs, src/Framework/TaskParameterEventArgs.cs
Log the Line and Column of add or remove items in ItemGroups inside targets. Previously we could only recover the file from the parent target, but not exactly which line in the file corresponded to the add/remove.
Now we can exactly pinpoint which add/remove is executing. No need to log the file because we can recover this information from the parent target. This saves space.
=> Log location of intrinsic tasks

ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs, ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs, src/Build.UnitTests/BackEnd/NodePackets_Tests.cs, src/Build.UnitTests/BackEnd/TargetResult_Tests.cs, src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/BackEnd/Components/Communications/TranslatorExtensions.cs, src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs, src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs, src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs, src/Build/BackEnd/Shared/TargetResult.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Framework/BuildEventContext.cs, src/Framework/BuildMessageEventArgs.cs, src/Framework/TargetSkippedEventArgs.cs, src/Shared/BinaryTranslator.cs
We weren't logging TargetSkippedEventArgs in two cases: when the target was satisfied from cache (previously built), or when the outputs were up-to-date. We were logging simple messages. Switch to logging TargetSkippedEventArgs in these cases as well.
Add a new TargetSkipReason enum to indicate why the target was skipped. Store and serialize it for node packet translator and binary logger.
When logging a TargetSkippedEventArgs because a target was built previously it is also useful to find the original target invocation (e.g. to see the target outputs). Add OriginalBuildEventContext to TargetResult and ensure it is translated properly. Add OriginalBuildEventContext on TargetSkippedEventArgs and serialize that as well (both node packet translator and binary logger).
Note that if the target …
=> Add TargetSkipReason and OriginalBuildEventContext to TargetSkippedEventArgs

ref/Microsoft.Build.Framework/net/Microsoft.Build.Framework.cs, ref/Microsoft.Build.Framework/netstandard/Microsoft.Build.Framework.cs, src/Build.UnitTests/BackEnd/MockLoggingService.cs, src/Build.UnitTests/BackEnd/NodePackets_Tests.cs, src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/BackEnd/Components/Logging/ILoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Framework/TaskStartedEventArgs.cs
We currently log the file in which a task is invoked, but we don't log the line and column, so if there are multiple tasks of the same name in a target, there's an ambiguity as to which task it is.
Pass the line and column information to TaskStartedEventArgs.
Fortunately we don't need to increment the binlog file format as we can piggy-back on the existing infrastructure for messages which can already log line and column if present. Reading older binlogs with the new MSBuild will work as the line and column flags won't be set, so no attempt to read anything extra. Reader newer binlogs with old MSBuild (same version but pre-this change) will also work as the line and column fields will be set and the existing infrastructure will read them, but nothing will consume that data.
=> Log TaskStarted line and column

src/Directory.BeforeCommon.targets, src/MSBuildTaskHost/MSBuildTaskHost.csproj
Fixes [AB#1329223](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1329223)
We're hitting issues with MSBuildTaskHost importing the Microsoft.VisualStudio.Setup.Configuration.Interop assembly, which is not being ngen'd properly. Turns out we don't need to import this package at all, so I've removed the packagereference along with un-defining constants when on net3.5 to prevent compilation errors.
Tested a successful build with msbuildtaskhost.csproj
Also don't define FEATURE_VISUALSTUDIOSETUP for MSBuildTaskHost.csproj[automated] Merge branch 'vs16.11' => 'main'
=> Stop MSBuildTaskHost importing Microsoft.VisualStudio.Setup.Configuration.Interop

.vsts-dotnet.yml
Fixes https://github.com/dotnet/msbuild/issues/6085
Fixes two issues:
- If an official build is kicked off that had stale optprof, no optprof, or is a branch that never would have optptrof (think `exp/`), it would fail. We'd then have to re-run using a specific optprofdropname
- When overriding the optprofdropname, we need to delete the IbcSourceBranchName. This is one less thing for the kitten (or any other dev launching pipeline builds of specific branches) to worry about!
Our official builds now take OptProfDropName as a pipeline parameter. We should leave the default value (which is `default`) if we don't plan to use a custom drop. When we do, paste your optprofdrop there and the script should do the rest.
No more manually clearing the `IbcSourceBranch` pipeline variable!
See …
=> Official Builds With Custom OptProf 'Just Work'

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Adding these allows them to be provided in Visual Studio's completion.
- ProduceReferenceAssemblies
- UseWindowsForms
- UseWPF
=> Add common properties to XSD

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/ProjectCache/CacheResult.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheDescriptor.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Shared/UnitTests/ObjectModelHelpers.cs
Can review the commits individually.  Ignore whitespace helps.
The project cache was being queried serially. Oops.
This is because the monolithic BuildManager._syncLock was being held during the cache query, thus serializing all access.
Implements the 2nd option from the design doc: https://gist.github.com/cdmihai/0955cb217b2cbd66e18c89b20bf68319#2-reuse-how-the-buildmanager-offloads-parallel-work-to-build-nodes
- Reverted code of ExecuteSubmission to what it was before project cache plugins.
- Changed ExecuteSubmission to either issue a cache request or a build request (until now it only issues build requests)
- The cache request is sent to the ProjectCacheService which submits it to the thread pool. This achieves parallelization of cache requests
- Each cache request, on its own thread: …
=> Make cache queries parallel

.vsts-dotnet-ci.yml
It's taking longer than we initially hoped so moving it to get it off the critical path.
=> Move RichCodeNav to its own job

eng/SourceBuild.props
Fixes dotnet/source-build#2068
This was something I discovered while trying to consume the Source-Build intermediate package produced by the first ArPow changes made in #6387
Set the `SourceBuildManagedOnly` property correctly.
Verified the resulting `Microsoft.SourceBuild.Intermediate.msbuild` package is not named rid specific.
=> Add SourceBuildManagedOnly to SourceBuild.props

ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs, src/Tasks/Microsoft.Build.Tasks.csproj
Fixes #6098
The `SignFile` task is referenced by the SDK for both .NET Framework and Core/5+, but not actually included in the non-framework assemblies.
Include `SignFile.cs` in the non-framework compilation.
A simple test, applying `SignFile` to one of the DLLs in artifacts using a self-signed certificate, succeeded.
=> Enable SignFile on .NET Core/5+

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs, src/Build.UnitTests/BackEnd/Scheduler_Tests.cs, src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs
There are two ways in MSBuild to disable the inproc node:
- via the environment variable `MSBuildNoInprocNode`
- by setting `BuildParameters.DisableInprocNode`
The implementations of these two, as you'd expect from MSBuild, are totally separate, they have nothing in common. The env var informs the Scheduler to [assign all requests to out of proc nodes](https://github.com/dotnet/msbuild/blob/fa96a2a81e0fb8c028057fa204bbf386bfb36aec/src/Build/BackEnd/Components/Scheduler/Scheduler.cs#L2048-L2053), regardless of their affinities. And the build parameter informs the NodeManager to just [bail out on inproc node creation and return null](https://github.com/dotnet/msbuild/blob/fa96a2a81e0fb8c028057fa204bbf386bfb36aec/src/Build/BackEnd/Components/Communications/NodeManager.cs#L100).
This means …
=> Scheduler should honor BuildParameters.DisableInprocNode

src/Framework/MSBuildEventSource.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
I'm poking around the question "why do builds using the .NET SDK take longer than older non-SDK builds?" and RAR time is one major factor. It'd be nice to have a complexity estimate in the ETW events: is this RAR instance resolving 3 files, or 300?
Add lightweight information about the size/complexity of a RAR
invocation by logging counts of the most interesting input/output lists.
Collected updated traces manually and confirmed data present.
⚠ Note this is currently targeting 16.11. Open to discussion on pushing it to main/17.0 instead.
=> Log RAR "size" in ETW

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileUtilities_Tests.cs
Fixes #6493
Summary
MSBuild's MakeRelative function does not fit the spec for how that function should work. 
Customer impact
Customers who use our MakeRelative function expect the relative path produced to end in a slash if and only if the input path ends in a slash. It currently does not end in a slash whether or not the input path ended in a slash. Users can invoke this function directly, and it can lead to dlls not being found, among other problems.
Regression?
Yes, from #6311 (16.10 Preview 2). The URI-based function that had existed prior failed in another scenario, and the new form is also faster. This PR resolves a bug associated with that change.
Changes Made
Only removes the ending slash if the input path did not end in a slash.
Testing
Extensive unit test coverage. This is a …
=> Fix MakeRelative regression in v16.10 (rebased to vs16.10 branch)

src/Build/BackEnd/Components/Logging/LoggingService.cs
Fixes #6498
Switch from the "use the new logic if any logger is present that supports it" to the more conservative "use the old logic if any logger doesn't support the new logic".
Customers who use MSBuild binary logs in conjunction with a legacy logger like one Azure DevOps provides for you would see a crash
```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure. 
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.NullReferenceException: Object reference not set to an instance of an object. 
at MSBuild.Logger.BuildConfiguration.Equals(Object obj) 
at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y) 
at …
```
=> Don't move Properties and Items to ProjectEvaluationFinished if legacy loggers present

eng/Versions.props, ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Shared/UnitTests/FileUtilities_Tests.cs
Pulling together approved PRs #6531, #6520, and #6513 with a version bump.
=> Servicing fixes for 16.10.2

src/Tasks/Microsoft.Common.CrossTargeting.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.Common.props
Some Microsoft-internal build environments override the property MSBuildToolsPath32
with a value that isn't actually the right thing, so explicitly call the property
function instead.
Fixes [AB#1334751](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1334751).
=> Use GetToolsDirectory32 explicitly for NuGet imports

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Shared/FileMatcher.cs, src/Shared/FileUtilities.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Shared/UnitTests/FileUtilities_Tests.cs
- Fix MakeRelative regression in v16.10
- Pulled in some external changes to Microsoft.Build.cs
- Don't move Properties and Items to ProjectEvaluationFinished if legacy loggers present
- Introduce IsAllFilesWildcard() and call it from MatchFileRecursionStep
=> Update 17.0-preview1 with 16.10 servicing fixes

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/MSBuild.UnitTests/ValidateAssemblyLoadContext.cs, src/Shared/CommunicationsUtilities.cs, src/Shared/NodeEndpointOutOfProcBase.cs
We actually meant 'or higher' and now that's expressible, so doing so.
Should fix the hang that held up https://github.com/dotnet/installer/pull/10804.
Note: 16.11, since this just restores the previously compiled behavior before we updated to net5.0.
=> Update NETCOREAPP2_1 ifdefs

.vsts-dotnet.yml
Migrates us "fully" onto the OneLocBuild.yml template. We were missing a condition and parameter in the template import.
Thought: This doesn't need to be backported to <=`vs16.11` right? Those builds should be having the onelocbuild template imported regardless. On second thought, they may need the `MirrorRepo` parameter.
Add `MirrorRepo` parameter
Add condition on importing the template.
Will create `exp/` branch to test this.
=> Properly condition onelocbuild template

.vsts-dotnet.yml
See https://github.com/dotnet/msbuild/pull/6561#issuecomment-862627551.
Because we're getting updated localization from 16.11, we need to tell the automation to send the PRs to the 16.11 branch.
=> Set branch for loc PRs

src/MSBuild/app.amd64.config, src/MSBuild/app.config
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1340776
The Workflow Foundation build tasks are built by VS and installed to the MSBuild bin folder (see src\SetupPackages\Workflow\Workflowv2\core\files.swr in the VS repo).  These assemblies have been bumped to 17.0 as part of the Dev17 product cycle, but the msbuild bindings were still looking for 16.0.  This led to the following build error for Workflow projects:
>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WorkflowBuildExtensions.targets(110,5): error MSB4062: The "ReportDeferredValidationErrorsTask" task could not be loaded from the assembly Microsoft.Activities.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35. Could not load file or assembly 'Microsoft.Activities.Build, …
=> Bind to 17.0 version of Workflow build tasks for Dev17

.github/ISSUE_TEMPLATE/01_bugreport.md, .github/ISSUE_TEMPLATE/02_performanceissue.md, .github/ISSUE_TEMPLATE/03_mybuildisbroken.md, .github/ISSUE_TEMPLATE/04_blankissue.md
Updating untriaged to needs-triage was done for consistency (needs-attention/design/more-info), ease of search/use (no spaces, all lowercase). Not to mention `untriaged` eventually meant some combination of "find a bucket this fits in" and "this needs attention".
However updating the label requires an update to our bug templates that apply those labels.
These bugs should have gotten `needs-triage` labels applied but the bug templates still try to apply `untriaged`.
https://github.com/dotnet/msbuild/issues/6553
https://github.com/dotnet/msbuild/issues/6551
=> Issue templates apply needs-triage label

src/Build/Evaluation/Evaluator.cs, src/Framework/MSBuildEventSource.cs
This reverts commit e9946d0e7aec542587cc2f374abcf544e85d5e47.
Fixes #
https://github.com/dotnet/msbuild/issues/6039
=> Revert "Add more params to the evaluation pass stops"

eng/BootStrapMSBuild.targets, eng/Packages.props, eng/Version.Details.xml, src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
Looks like this was useless but cost time doing darc update flow. Pulling it from the pre-bootstrap SDK directly.
=> Simplify reference to Microsoft.Extensions.DependencyModel

.vsts-dotnet-ci.yml
I'm tired of seeing warnings all the time and the lifetime of 16.11 will very likely exceed the lifetime of the 16.04 image so backporting #6488.
=> Backport Ubuntu update to 16.11

src/Build/Evaluation/ExpressionShredder.cs, src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/Build/Evaluation/LazyItemEvaluator.cs
Fixes #6062
Minor fixes for the LazyItemEvaluator: unnecessary memory allocations were removed.
Manual testing.
=> Minor perf fixes for LazyItemEvaluator

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #6510
MSBuild currently incorrectly expects PDB files to be produced by a refonly compile.
This defaults both `ProduceReferenceAssembly` and `ProduceOnlyReferenceAssembly` (slightly earlier than before).
When `ProduceOnlyReferenceAssembly` is set to `true`, don't expect symbols to be produced.
=> Do not expect PDB files for a refonly build

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Resources/Constants.cs
There's no easy way to get all of MSBuild's version numbers at evaluation time or build time.
Added `MSBuildFileVersion` and `MSBuildSemanticVersion`. With these two, users should have all the information they require to mix and match all the version components they want: 
Updated version test.
Targeting 16.11 as it only adds new stuff that should not break. Caveat is if users define the new built-in properties. We'll break those users. Though I think those users don't exist :)
=> Add reserved properties MSBuildFileVersion and MSBuildSemanticVersion

eng/BootStrapMSBuild.targets, eng/Version.Details.xml, eng/Versions.props, eng/common/dotnet-install.sh, eng/common/internal-feed-operations.ps1, eng/common/internal-feed-operations.sh, eng/common/sdk-task.ps1, eng/common/sdl/execute-all-sdl-tools.ps1, eng/common/sdl/init-sdl.ps1, eng/common/sdl/run-sdl.ps1, eng/common/templates/job/onelocbuild.yml, eng/common/tools.ps1, eng/common/tools.sh, global.json
Reverts dotnet/msbuild#6552. The official build is broken because the internal build agents don't have VS 16.10 yet.
=> Revert "[main] Update dependencies from dotnet/arcade"

src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
Remove an assert that is too aggressive. When reading old binlogs the TargetSkipReason is not known, so TargetSkipReason.None is a valid state.
We can do a best effort and infer the skip reason for format version 13.
Fixes #6563
=> Infer target skip reason from older binlogs

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
This test hangs. We haven't been able to figure out why.
Adding as much logging as I can think of -- to stdout, which
will be in the .log file, since the XML results file isn't
created in the hang case.
=> Extremely verbose logging for CancelledBuild

README.md
We changed build definitions months and months ago, and should update the links.
=> Update build badge links

src/MSBuild/app.amd64.config
Fixes #5331 by explicitly specifying all quirks that the runtime should specify for us because we target .NET 4.7.2.
Obnoxiously, amd64 MSBuild was fixed for long paths for exactly one release, 16.7. 16.8 broke it again.
=> Opt into quirks in amd64 MSBuild explicitly

src/Tasks/Microsoft.Common.CurrentVersion.targets
Ensure file association icons files get published as loose files in Single-File publish for ClickOnce
Fixes #1340931
ClickOnce applications can associate file extension and icons with the application. In this scenario, the icon files should be published. When published in Single-File mode, we fail to publish the icon files.
In Single-File publishing, ClickOnce only publishes the SF Exe and any uncompressed file that cannot go into the bundle. The ico files get ignored. The fix made now ensure that ico files in FileAssociation item list are also published as uncompressed file. These file need be be outside of the bundle so that the ClickOnce installer and runtime can see them.
CTI tested all configurations (Portable/x64/x86 across FDD/SCD and SF modes).
=> Publish FileAssociation Icons correctly in Single-File ClickOnce publish

src/Build.UnitTests/BackEnd/BinaryTranslator_Tests.cs, src/Build/BackEnd/BuildManager/CacheSerialization.cs, src/Build/BackEnd/Shared/BuildRequestConfiguration.cs, src/Build/BackEnd/Shared/TargetResult.cs, src/Shared/BinaryTranslator.cs, src/Shared/ITranslator.cs, src/Shared/InterningBinaryReader.cs, src/Tasks/GetSDKReferenceFiles.cs, src/Tasks/StateFileBase.cs
Fixes #3954
The `Buffer` class is 100 kB (40 for characters and 60 for the byte array) and it is being allocated a lot, easily in the order of tens of thousands of instances per build. OOM crashes are often blamed on such allocations.
1. Made the byte array allocation lazy since in many scenarios it ends up not being used.
2. Implemented a trivial `Buffer` pooling which eliminates >97% of allocations.
Opted for a 1-element static cache to keep the last used `Buffer` around. This works very well given MSBuild's single-threadedness and keeps the code simple and policy-free.
=> Make InterningBinaryReader pool buffers

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Samples/ProjectCachePlugin/AssemblyMockCache.cs, src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
Non static graph builds using the project cache didn't set the ProjectInstance on the cache request, leading to crashes in the cache.
Recreate the BuildRequestData for the cache request after the cache service evaluates projects. I was initially using the original BuildSubmission.BuildRequestData which does not contain the project instance.
Unit tests
This does not affect non project cache code paths so it shouldn't be a risk for 16.11.
=> Fix missing project instance in project cache requests

src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
My preference is to use `ImmutableSegmentedList<string>` for this (avoids the Large Object Heap and avoids the array copy in `ToImmutable()`), but I haven't finished implementing it yet in Microsoft.CodeAnalysis.Collections. In the mean time, I've corrected an acute performance problem by using ~`ImmutableArray<string>`~ `List<string>` instead of `ImmutableList<string>`.
Fixes [AB#1344683](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1344683)
=> Use List<string> for excludes

src/Tasks/GenerateResource.cs
This was a heinous bug to repro.
Using VS 17.0.0+, create a blank UWP app with target platform version 16299 or 17134. Build Debug/x86.
If that doesn't work, clean and build again.
If that doesn't work, clean and build again.
It should work every time, but from my testing, every other clean-build cycle succeeds even following identical steps. Every other build clean-build cycle fails with a message saying an attempt was made to load a file with incorrect format. This is normally a BadImageFormatException and caught (see comment above), but it seems that with dev 17, that is sometimes (always?) wrapped in an ArgumentException and not caught. This fixes that problem by catching both.
Maybe we should verify that the ArgumentException mentions BadImageFormatException before just continuing? …
=> Catch ArgumentException as well as BadImageFormatException when failing because of libraries without resources

src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs, src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs, src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs, src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildParameters.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Shared/ErrorUtilities.cs, src/Shared/UnitTests/TestAssemblyInfo.cs
Based on #6568. Review that one first. First commit of this PR is [Don't launch debugger window for all tests](https://github.com/dotnet/msbuild/commit/529e2ae13d060adb50f7cf5304e6f781d8666941).
Turns out the VS workaround was initializing the plugin on every project query, thus crashing the cache.
Initialization is happening only once now.
`ProjectCacheService` is now asserting that it's always in expected states.
Unit tests.
Does not affect non project cache code paths so should be no risk for 16.11.
=> Ensure project cache initialization happens only once

src/Directory.BeforeCommon.targets, src/Directory.Build.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/dotnet/msbuild/issues/5792
We had two areas where MSBuild checked TargetFramework based on whether it started with `netcore` and `netstandard`.
Ex:
https://github.com/dotnet/msbuild/blob/a71067913c82bcb5d79a13f40ff8b12cbd384c1c/src/Directory.BeforeCommon.targets#L114
With net5.0 resolving to `net5.0` instead of `netcoreapp5.0`, this logic would no longer succeed, so here's a quick fix via intrinsic function `GetTargetFrameworkIdentifier` introduced in https://github.com/dotnet/msbuild/pull/5429.
------
Some other notes:
There are a few other areas that look like we could use these intrinsic functions, but it would overcomplicate the logic. Here's what I found with `rg -iF "StartsWith('net"`
```
src\MSBuild.Bootstrap\MSBuild.Bootstrap.csproj
55:  <Import …
```
=> Check TargetFramework Using Intrinsic Function

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs, src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs, src/Build.UnitTests/ConsoleLogger_Tests.cs, src/Build/Logging/BaseConsoleLogger.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
This PR supersedes https://github.com/dotnet/msbuild/pull/6514
Console logger support for IncludeEvaluationPropertiesAndItems.
Includes https://github.com/dotnet/msbuild/pull/6520, but we can take this commit out if it's merged separately.
OutputItems was pretty much duplicated in ParallelConsoleLogger. Unify with the base implementation and extract methods that need to be replaced by the derived type.
Support for reading project configuration description either from ProjectStartedEventArgs.Items or ProjectEvaluationFinishedEventArgs.Items.
Skip TestItemsWithUnexpandableMetadata. Issue https://github.com/dotnet/msbuild/issues/6518 is tracking. More work is needed to understand the desired behavior of the system under test and then fix the test to test the desired behavior.
Skip …
=> Console logger support for IncludeEvaluationPropertiesAndItems

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Build/BackEnd/Components/Scheduler/SchedulingData.cs
Fixes a bug in proxy build scheduling introduced by #6386. If a the BuildRequestConfiguration associated with a proxy request has been built before on an out of proc (oop) node then the scheduler will fail with either one of:
- affinity mismatch error. This happens when the proxy build is assigned to the inproc (inp) node but its configuration is already assigned to an oop node `AND` serving other existing requests, either blocked or running.
- unscheduled requests remain even if there's free oop nodes that can serve them. This happens (as far as I can tell) when the proxy's configuration is already assigned to an oop node (because a previously built non proxy request was assigned there) `AND` there's no other existing requests for that configuration
The fix in this PR is to not assign a …
=> Don't schedule proxy builds to inproc node if their configs previously built on oop nodes

documentation/wiki/ChangeWaves.md, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/dotnet/msbuild/issues/1054
IncrementalClean has the behavior of deleting content items from transitive references on rebuild of the main project. With the move to 17.0, we want to default to copying all transitive content items into the main output folder to avoid this behavior.
Under change wave 17.0, default `MSBuildCopyContentTransitively` to true.
Tested locally on https://github.com/rainersigwald/IncrementalCleanDemo
=> Default to transitively copying content items

src/Build/Definition/Project.cs
_data was extracted to a ProjectImpl class, so need to add the implementation field first.
This regressed in https://github.com/dotnet/msbuild/pull/4673
=> Fix [DebuggerDisplay] for Project

documentation/wiki/ChangeWaves.md, src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs, src/Build/Globbing/MSBuildGlob.cs, src/Shared/FileMatcher.cs, src/Shared/UnitTests/FileMatcher_Tests.cs
Fixes #6599
Compiled regular expressions have a high first-call cost on .NET Framework, especially when running in a 64-bit process. At best, they need to be used thousands of times to make up for the compilation cost. In some cases compiled regexes are even slower than interpreted ones.
Switched regexes used in `MSBuildGlob` to interpreted on .NET Framework. Also optimized capture groups as suggested by @ToddGrun and removed a couple of unused fields.
- Existing unit tests with added coverage for `MSBuildGlob.MatchInfoResult`.
- Experimental insertion to confirm the CPU time win.
=> Don't compile globbing regexes on .NET Framework

src/Shared/MSBuildLoadContext.cs
The idea behind the fallback was that we'd load an assembly
that matched (by simple name) from the MSBuild directory if
there wasn't a match in the task/plugin folder. But
assemblies aren't in the MSBuild folder (or anywhere on disk)
by simple name: they have an extension. So this was never
working.
That was mostly irrelevant, because the assemblies that are
'next to MSBuild' in the .NET SDK are in MSBuild.deps.json
as assembled in the SDK repo. But in our own bootstrap build,
that's not the case and the normal fallback matters.
=> Use extension in Next-to-MSBuild fallback

documentation/Changelog.md, eng/Versions.props
Wait until we're sure nothing else needs to merge into 16.11 before merging this.
Change Contains:
Final branding
16.11 Change Log
=> 16.11 Final Branding

src/Build/Xml/XmlReaderExtension.cs
This reverts commit 1d1fec7c49795b247fc45fac0fb1fdd736c6a368.
Fixes #2576 
- The change hasn't proved impactful in the perf lab with any project types used in the runs.
- It uses reflection to access an internal member.
- It is causing an assert in `XmlTextReaderImpl` to fire for developers running Debug build of the BCL.
Altogether it appears to be a net loss and ripe for a revert.
Reverting the commit.
Build / smoke test.
=> Revert "Ignore comments and whitespace when parsing read-only XML files (#6232)"

src/Build/Evaluation/Expander.cs
[CompareInfo.IndexOf(string, char, ...)](https://referencesource.microsoft.com/#mscorlib/system/globalization/compareinfo.cs,772) on .NET Framework has two paths:
**OrdinalIgnoreCase:** Which goes through string.IndexOf(string, ...)
**Everything else:** Win32's FindNLSStringEx
Both paths allocate a string that represents the char. Instead just call through string.IndexOf(char) which does a flat ordinal comparison which is what we want. This was about 0.3% of allocations in devenv opening a 500 project solution.
I walked every instance of this across the tree and found only the ones in the PR. It doesn't look like MSBuild uses the [banned API analyzer](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md) so I …
=> Avoid string allocation while searching for a char

src/Package/MSBuild.VSSetup/files.swr
Fixes #6605 
MSBuild.exe is being JITted because NGEN images of some of its dependencies are rejected.
Use `vs.file.ngenApplications="[installDir]\MSBuild\Current\Bin\MSBuild.exe"` for all system dependencies to pick up our binding redirects.
- Experimental insertion confirmed that MSBuild.exe is no longer JITted (both x86 and x64). On x64 the number of methods compiled when building a simple hello world app went down from 1862 to 1536, time spent in JIT 810 ms -> 608 ms.
- No RPS regressions.
=> NGEN all System dependencies with ngenApplications=MSBuild.exe

src/MSBuild/app.amd64.config, src/MSBuild/app.config
Profiles show significant time spent in `clr!ThreadpoolMgr::UnfairSemaphore::Wait` (rolled into `clr!ClrSleepEx` on 32-bit). Evidently, the default TP worker thread spinning doesn't work well with our TP usage patterns.
Added `<ThreadPool_UnfairSemaphoreSpinLimit enabled="0" />` to both flavors of MSBuild.exe.config.
- RPS tests show ~15% CPU time improvement in some scenarios, no wall-clock time impact. VS perf team has signed off.
- Full build of the OrchardCore solution shows ~3.5% CPU time improvement, no wall-clock time impact.
We will likely add this setting to more VS processes, refer to [AB#1351333](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1351333) for details.
=> Disable TP semaphore spinning for MSBuild processes

src/Tasks/AssemblyDependency/Reference.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs
Fixes #6501
RAR can output paths not in their canonical forms. This allows for there to be multiple identical paths, only distinguished by extra directory separator characters, for example, which can lead to duplicate work or failing to find paths in a cache.
This normalizes all paths output by RAR, ensuring any given path is in its canonical form.
To follow.
=> Normalize RAR output paths

src/Tasks/ResolveManifestFiles.cs
Fixes AB#1449000
Satellite assemblies are not being handled correctly after ClickOnce changes for .NET Core publishing were made in VS 16.8.
Following issues have been observed post those changes:
1. If packages publish en-us resource assembly for other locales as well, we will end up adding all of them in the ClickOnce manifest. Since the strong name signature will be identical for all these resource assemblies, we will now have multiple assemblies with identical signature in the ClickOnce manifest. This will cause CO Install to fail.
2. The References item list can also contain resource assemblies. If these assemblies are also present in the SatelliteAssembly item list, we will now end up writing 2 entries for the same assembly in the manifest. This will cause CO install to fail.
When …
=> VS 1449000: Fix handling of satellite assemblies in ClickOnce

src/Tasks/Microsoft.Common.CrossTargeting.targets
Fixes #1062
The import based on this property was introduced as a temporary bootstrapping
mechanism before there was packaging extensibility available for multi-targeting.
The packaging mechanism (aka NuGet) now uses `buildCrossTargeting`/`buildMultiTargeting`,
similar to `build` package folder to hold and import multi-targeting logic via NuGet's Restore.
Thus, we don't need this workaround anymore.
Removed the temporary import based on `CoreCrossTargetingTargetsPath`
Since there are no tests for this property, as it is with all the workarounds… We'll see if we break anyone during the self-hosting period.
This patch was already a part of #6161. Since, the change was approved independently, I have separated this into a new PR.
=> Remove import using `CoreCrossTargetingTargetsPath` property

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #6543 
#6560 made `TargetRefPath` relative by mistake, which broke build in Visual Studio.
Use `MSBuildProjectDirectory` to properly root the path.
Verified that VS build works with this fix.
```
0:010> !pe
Exception object: 0000020fa4de3a90
Exception type:   System.IO.DirectoryNotFound
ExceptionMessage:          Could not find a part of the path 'C:\WINDOWS\system32\obj\Debug\net6.0\ref\HelloWorld.dll'.
0:010> !clrstack
OS Thread Id: 0x95c (10)        Child SP               IP Call Site
000000bc6023cf88 00007ffb12634ed9 [HelperMethodFrame: 000000bc6023cf88]
000000bc6023d070 00007ffb037dba49 System.IO.__Error.WinIOError(Int32, System.String)
000000bc6023d0c0 00007ffb0408d7e6 System.IO.File.InternalCopy(System.String, System.String, Boolean, Boolean)
000000bc6023d150 00007ffaa7303d70 …
```
=> Absolutize ref assembly path

src/Build.UnitTests/Evaluation/SimpleProjectRootElementCache_Tests.cs, src/Build/Construction/ProjectRootElement.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/ProjectRootElementCache.cs, src/Build/Evaluation/SimpleProjectRootElementCache.cs
Fixes #3039
There is significant amount of lock contentions in ProjectRootElementCache.Get method. 
(For OrchardCore project, for example, the total time spent waiting to take a lock ~1sec.)
Reason: the code is using a single lock to control to access the cache, and also read file into XmlDocument, when it does not exist. The later one can be slow on a slow disk.
The ProjectRootElementCache.Get function is rewritten to exclude IO operations from the locked sections.
For this goal we also had to separate logic of loading from logic of adding the element to the cache.
Unit tests + manual testing.
=> Fix lock contention in ProjectRootElementCache.Get

src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Framework/MSBuildEventSource.cs, src/Tasks/Copy.cs
I was considering adding bucket.bucketSequenceNumber, but I don't think that's too important. Complicated information can't be easily ( / efficiently) attached to ETW traces
Fixes #6616
I should make sure they appear in PerfView before merging.
=> Add ETW trace for PerformDependencyAnalysis

documentation/wiki/ChangeWaves.md, src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Build/BackEnd/Components/Scheduler/SchedulingPlan.cs, src/Build/BackEnd/Node/OutOfProcNode.cs, src/Build/Graph/ProjectGraph.cs, src/MSBuild.UnitTests/XMake_Tests.cs, src/MSBuild/OutOfProcTaskHostNode.cs, src/Shared/CommunicationsUtilities.cs, src/Shared/Debugging/DebugUtils.cs, src/Shared/Debugging/PrintLineDebugger.cs, src/Shared/ExceptionHandling.cs, src/Shared/NodeEndpointOutOfProcBase.cs, src/Shared/Traits.cs
There's still a bit of friction when debugging MSBuild, especially under VS. You have to set multiple env vars, or search through temp, find all the obscure env var names, etc
- add one env var, `MSBuildDebugEngine` to turn everything on and also automatically pick `./MSBuild_Logs` as the debug log path for everything that spews out log files.
- in addition, when `MSBuildDebugEngine`: 
- inject a binary logger directly from the build manager. This is super useful when running MSBuild in VS, as the build logging that VS gives is kind of lacking
- dump a `.dot` representation of the static graph, when one is available
This is how `MSBuild_Logs` looks like after doing a build (both VS and cmdline should produce this):
=> Improve debugging experience: add global switch MSBuildDebugEngine; Inject binary logger from BuildManager; print static graph as .dot file

src/Shared/InterningBinaryReader.cs, src/Tasks/ResolveManifestFiles.cs
Fixes #6624 
Whenever is deserialized string bigger than 20 000 chars, new char[stringSize] is allocated as temporary buffer.
It mostly happened for huge solutions (measured at 900 projects solution Solution_006_0936.sln) by global property SolutionConfiguration.
Using ArrayPool<char>.Shared for buffer renting.
- Build orchard core and msbuild.
- Measured and compared
- allocates 700MB less
- LOH size dropped to ~2.5 GB from 4GB
System.Buffers is supported by both .NET framework and .NET, although it has different internal implementation for each of those.
=> Using ArrayPool for buffers in InterningBinaryReader

scripts/Deploy-MSBuild.ps1
Fixes #6682
Deploy-MSBuild.ps1 does not properly copy files amd64 files into VS
- Handle x64 files with their backup
- Add Microsoft.Common.tasks
- Fix for net6 - removing some files
Locally
=> Fix deploy script for 64bits and net6

ref/Microsoft.Build.Tasks.Core/net/Microsoft.Build.Tasks.Core.cs, ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs, src/Tasks/Copy.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #https://github.com/dotnet/msbuild/issues/6576
https://github.com/dotnet/msbuild/issues/6576 revealed that the `.copycomplete` file marker is updated even when the `Copy` task in `_GetCopyFilesMarkedLocal` doesn't _actually_ copy anything. This can mess with incremental builds.
This change adds an output parameter, `CopiedAtLeastOneFile` to the `Copy` task that the `Touch` task is now conditioned off of.
Tested local builds
This could also be done by having an ITaskItem[] that contains all files that were actually copied. Then the touch task could check if that item were empty. I opted for the straightforward route since the ITaskItem[] solution isn't needed yet, and this implementation can easily be changed when we do need that.
=> Skip Updating CopyComplete Marker When Not Necessary

src/Shared/CoreCLRAssemblyLoader.cs, src/Shared/MSBuildLoadContext.cs
We believe these were remnants of old pre-crossgen file naming patterns that haven't been used in a very long time.
Removing the checks to avoid filesystem activity on files that almost certainly will not exist.
Fixes #5042.
=> Stop checking .ni.dll/exe on Core

src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs, src/Shared/BuildEnvironmentHelper.cs
Fixes #6681.
The change to make Visual Studio 64-bit means that projects loaded in Visual Studio get the 64-bit MSBuild, and other tools are more likely to be loading our API in a 64-bit process as well. That found this difference between the way projects are evaluated in `devenv.exe` and in `vcxprojReader.exe`.
Find the VS root from the current assembly and then reconstruct the path to the appropriate MSBuild.exe based on that + the current process's bitness, ensuring that API consumers and MSBuild.exe/devenv.exe see the same MSBuildToolsPath.
Manual overlay with a trivial API consumer.
=> Identify 64-bit MSBuildToolsPath from 64-bit API consumer

documentation/wiki/ChangeWaves.md, src/Tasks/Microsoft.Common.CurrentVersion.targets
- Revert "Absolutize ref assembly path (#6695)"
- Revert "Move ref assembly to the obj folder (#6560)"
Fixes [AB#1361354](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1361354).
Work item (Internal use): [AB#1361354](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1361354)
Revert changes to move reference assemblies to the obj folder, which appears to cause a not-yet-understood issue in Visual Studio scenarios.
Reference assemblies will reappear in the `bin/` folder as they were in prior releases.
Yes, from #6560.
Unit tests, manual patching of targets file in repro case with old copy resolves the issue.
Less testing on the new in-obj behavior.
=> Revert move of reference assemblies into obj

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #943
The description for the target GetCopyToOutputDirectoryItems was incorrect. This fixes that due to https://github.com/dotnet/msbuild/pull/6622
=> Update description about transitive copying

eng/build.ps1
#6381 added a check to run as part of CI builds which expects the `SYSTEM_PULLREQUEST_TARGETBRANCH` environment variable to exist. As a result, regular main builds which are not triggered by PRs are broken.
Added the new code behind an `if` so it runs only if the PR target branch is defined. Effectively this makes the check run only in PRs, which is by design.
Will watch the next main build.
=> Unbreak non-PR CI builds

src/Framework/MSBuildEventSource.cs
- Make EvaluateStop event adjacent to EvaluateStart
It's not well documented, but EventSource requires that the start and stop event IDs for a single thing be separated by exactly one. Since this one didn't, we weren't getting DURATION_MSEC computed for overall evaluation time in our traces.
See https://github.com/dotnet/runtime/blob/f83a9d9689433ce522b91e74a9631c83847e3b64/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L3270.
- Update Evaluate* event doc comments
- Include EvaluateStart/Stop in DOTNET_PERFLOG
- Drop Parse from DOTNET_PERFLOG
=> Miscellaneous event tweaks

src/StringTools/StringTools.csproj
Fixes #6664
The package is missing a good package description.
Added the `PackageDescription` property.
Will check the next built package.
=> Add PackageDescription to Microsoft.NET.StringTools

src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Improves an obscure error message. Cherry-picked this commit out of #6635 because 16.11 loc window is closed.
=> Specify project info in affinity missmatch error

src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
Fixes https://github.com/dotnet/msbuild/issues/6594
When the SDK's workload resolver would fail (with a filenotfound exception), we would complain about the NuGetSDKResolver. The condition was too flexible.
Specified the condition to be: If (filenotfound OR fileload exception) AND it's the nugetsdkresolver, throw that nuget message.
Otherwise, generically log "this sdk resolver {0} failed because {1}"
Tested locally.
=> Fix Misleading NuGet SDK Resolver Error Message

src/Tasks/AssemblyDependency/AssemblyInformation.cs
Fixes #6734 
Also fixes #6730
This fixes #6734 in my scenario.
=> Remove depenency on MemberRef Parent of a custom attribute constructor being a TypeReference

src/Shared/BuildEnvironmentHelper.cs
A 64-bit application is now (after #6683) getting a good VS root path,
but may still use toolsets from the wrong directory, because if it
loaded (AnyCPU) assemblies from the 'x86' location it wouldn't pass
a path containing amd64 to the BuildEnvironment constructor, so
the logic there wouldn't find the right MSBuildToolsDirectory and
config file.
Fix this in the lowest-impact way by rederiving the path to the
'correct' MSBuild.exe from the VS root and passing that to the
BuildEnvironment constructor.
Fixes #6681.
=> Recalculate MSBuild path from VS Root

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fix potential issue where an already-set 'SetTargetFramework' metadata on a `ProjectReference` item would skip logic required for SetPlatform negotiation.
When `SkipGetTargetFrameworkProperties` is true, it skips the MSBuild call to `GetTargetFrameworks`. I modified a condition to ensure it wouldn't be set to true when opted into the feature, but just below that was this:
```xml
<ItemGroup>
<_MSBuildProjectReferenceExistent Condition="'%(_MSBuildProjectReferenceExistent.SetTargetFramework)' != ''">
<SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
</_MSBuildProjectReferenceExistent>
</ItemGroup>
```
So if we skipped setting `SkipGetTargetFrameworkProperties` to true, it would still be set to true if `SetTargetFramework` was set. This would skip the call to …
=> SetPlatform Negotiation: Allow MSBuild `GetTargetFrameworks` call when `SetTargetFramework` already set

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Fixes https://github.com/dotnet/msbuild/issues/6745
The SDK added a few new features that are enabled in .NET 6 C# projects. Updating the schema file to document this feature.
=> Update XSD to include details about ImplicitUsings and Using items

eng/config/OptProf.json
Fixes #6067
There is a few dozen milliseconds worth of avoidable JITting happening in MSBuild assemblies on VS solution open. The respective methods are considered cold and not part of our NGEN images because they are not executed by current training scenarios.
Added an additional scenario to specifically cover .NET Core projects.
Ran the OptProf pipeline with this change and then Perf.DDRITs with a build optimized using the resulting optimization data.
- 50 ms less CPU spent JITting Microsoft.Build!*
- Perf.DDRITs showing improvements:
- WebToolsVS64.SolutionManagement 0100.Open Solution - devenv methods JITted down by 24.4%
- WebToolsVS64.SolutionManagement 0200.Rebuild Solution - non-devenv methods JITted down by 4.5%
- ManagedLangsVS64.RebuildSolution 0100.Rebuild Solution - …
=> Add .NET Core solution open to OptProf training scenarios

documentation/specs/project-cache.md, documentation/specs/static-graph-implementation-details.md, documentation/specs/static-graph.md
GitHub now [generates navigation options][1] in Markdown files, so no need to have them here manually.
[1]: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/
=> Delete manual Markdown ToCs

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/dotnet/msbuild/issues/5943
`@(SuggestedBindingRedirects)` is listed as an input for `GenerateBindingRedirects`, but `@(SuggestedBindingRedirects)` _never_ contains a file that exists on disk. This leads to `GenerateBindingRedirects` running for every build.
`@(SuggestedBindingRedirects)` is now hashed into `obj/$(ProjectFile).SuggestedBindingRedirects.cache` on first build or when there's an update to `SuggestedBindingRedirects`. That file is now used as the input to `GenerateBindingRedirects`, instead of the item that contains no files on disk.
The logic is placed in a new target, `_GenerateSuggestedBindingRedirectsCache` that has `DependsOnTargets="ResolveAssemblyReferences"`
Not locally tested yet.
=> Generate cache file for SuggestedBindingRedirects

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs, src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/Expander.cs, src/Shared/ResourceUtilities.cs
Stop allowing execution of `GetType()`. This can lead to calling methods that really should not be called during evaluation.
=> Block Execution of GetType() in Evaluation

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/Construction/Solution/SolutionConfigurationInSolution.cs, src/Build/Construction/Solution/SolutionFile.cs, src/Build/Construction/Solution/SolutionProjectGenerator.cs, src/Build/Graph/ProjectInterpretation.cs, src/Samples/ProjectCachePlugin/AssemblyMockCache.cs, src/Shared/UnitTests/ObjectModelHelpers.cs, src/Tasks/ResolveProjectBase.cs
Visual Studio has solution configurations and project configurations. A configuration is a (Configuration, Platform) tuple.
A solution configuration defines a specific project configuration for each project in the solution. It's like a mapping  from a solution configuration to a list of project configurations for each project.
At any moment a single solution configuration is active in VS.
When doing a real build in VS, the active solution configuration is propagated as global properties on each build request.
Up until now I didn't have a clear understanding of this, therefore the project cache setup has a bug when building under VS: it does not propagate the solution configuration information to the plugin instance.
This means that if the user selects a non-default solution configuration …
=> Propagate solution configuration information to project cache plugins

src/Build.UnitTests/BackEnd/DebugUtils_tests.cs, src/Shared/CommunicationsUtilities.cs, src/Shared/Debugging/DebugUtils.cs
Fixes #6772, fixes AB#1386501
In #6639 I thought it would be a good idea to always expose exceptions by always setting msbuild's debug path, fallbacking to the current working directory. But apparently that's a breaking change :)
Also, some processes (like VS helpers) do not propagate the user's CWD and thus end up writing under Program Files which fails with permission exceptions.
So only set the debug path to the current working directory when `MSBuildDebugEngine` is set.
Unit test and manual tests
I couldn't actually repro #6772. What I did instead was to change the oop nodes to crash right after completing the handshake, and checked that `MSBuild_Logs` does not appear in the CWD, but instead the exception dumps appear under Temp.
=> Only set debug path when MSBuildDebugEngine is set

eng/Packages.props, src/Build/System.Text.Encodings.Web.pkgdef, src/Build/System.Text.Json.pkgdef, src/MSBuild/MSBuild.csproj, src/MSBuild/app.amd64.config, src/MSBuild/app.config, src/Package/MSBuild.VSSetup/files.swr
Fixes conflicts in VS 2022 for extensions that would like to use libraries that need System.Text.Json 5.0.0 or newer.
Fixes conflicts in VS 2022 for extensions that would like to use libraries that need System.Text.Json 5.0.0 or newer.
Updated packages.
None :)
=> Update System.Text.Json to 5.0.2

documentation/specs/sdk-resolvers.md, ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolverException.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Microsoft.Build.csproj, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Fixes #6762 
When SDK Resolvers fail, we currently log a warning and try to continue the build. This leads to a failure at some point in the future, which is confusing for customers.
- SdkResolverService now catches exceptions and throws an `SdkResolverException`
- Evaluator catches SdkResolverException and fails the build, providing the inner-error message along with `MSB4242`.
- MSB4243 freed up. See notes below
Tested on a local standalone sdk. See comments below.
- MSB4242 now has a slightly different meaning. It's a catch-all "sdk resolvers failed somehow" exception. It will then report whatever the resolver's message was, so the resolver's error codes had to had to be removed. Removing the other error codes prevents this sort of message: `MSB4242: Sdk Resolver Failure: MSB4243: blah …
=> Fail Builds Fast When SDKResolvers Throw Exceptions

.vsts-dotnet.yml
We left the onelocbuild branch on 16.11, this updates it to main so we can get automatic loc updates.
Should we leave this as main, or consider 17.0 and manually update on each release (considering some automated future).
=> Update loc update branch

src/Tasks/Microsoft.Common.props
Fixes https://github.com/dotnet/project-system/issues/7561
https://github.com/dotnet/project-system/pull/7432 added a design-time target called CollectSuggestedWorkloads to https://github.com/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets. Unfortunately, that change did not account for the fact that this design-time targets file is used by non-SDK projects or projects using earlier SDKs. Such projects now fail with the error: The target "GetSuggestedWorkloads" does not exist in the project.
https://github.com/dotnet/project-system/pull/7553 temporarily worked around this by conditioning CollectSuggestedWorkloads on SDK projects with MissingWorkloadPacks. The correct fix is to move the dummy …
=> Define stand-in optional workloads targets

.vsts-dotnet.yml
The oneloc script should only run on one branch. This change updates the condition here to only run if `main` is the branch, effectively disabling oneloc on this branch.
Decided not to delete the block of code in case we need to do some loc update to 16.11 for some unlikely reason.
=> Disable vs16.11 loc updates

src/Build/Construction/ProjectElement.cs, src/Build/Construction/ProjectElementContainer.cs, src/Build/Definition/Project.cs, src/Framework/Sdk/SdkResolver.cs, src/Framework/Sdk/SdkResolverContext.cs, src/Framework/Sdk/SdkResult.cs, src/Tasks/CreateItem.cs, src/Tasks/CreateProperty.cs, src/Tasks/Hash.cs, src/Tasks/MSBuild.cs, src/Utilities/ToolLocationHelper.cs, src/Utilities/TrackedDependencies/FileTracker.cs
Fixes https://github.com/dotnet/msbuild/issues/6743
The doc build is throwing some validation errors on some XML code comment constructs, such as invalid tags or improper nesting of tags.
Fix several XML comments
No change other than code comments
=> Doc comments: fix validation issues in docs build

src/StringTools/InternableString.cs
Fixes [AB#1343753](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1343753)
We're getting hang dumps where a lock taken by the concurrent flavor of `WeakStringCache` is orphaned. This can possibly be caused by `InternableString.ExpensiveConvertToString`, which is running unsafe code under the lock, throwing a corrupting exception, thus preventing the lock-releasing finally blocks from running.
Since no bug has been found in stress runs and by extensive code inspection, I am adding a cheap invariant check to the unsafe method, hoping that it would help us figure out the issue.
Smoke-tested the invariant.
=> Add invariant check to InternableString.ExpensiveConvertToString

src/Build/Evaluation/ProjectRootElementCache.cs
The average imports/project in a recent OrchardCore solution
(primarily ASP.NET Core) is 83, so one project can by itself
evict stuff from the old cache of size 50.
There are likely further improvements to be made in this area
(some ideas in #6715), but increasing the size to 200 seems to
be a [significant improvement with an extremely small change](https://github.com/dotnet/msbuild/issues/6715#issuecomment-905788648).
=> Increase ProjectRootElementCache MRU cache

.vsts-dotnet.yml
This is required by VSEng/1ES policy.
Successful build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5180585&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=bb592630-4b9d-53ad-3960-d954a70a95cf
=> Move to VS 1ES pool

src/MSBuild/app.amd64.config, src/MSBuild/app.config
Update the binding redirect for System.Threading.Tasks.Extensions to match the version we currently ship (4.2.0.1).
I also audited all other System.* assemblies we ship and this was the only mismatch.
=> Binding redirect Tasks.Extensions 4.2.0.1

src/StringTools.UnitTests/SpanBasedStringBuilder_Tests.cs, src/StringTools.UnitTests/WeakStringCache_Tests.cs, src/StringTools/InternableString.cs
The current straightforward implementation is slow, especially on 64-bit Framework CLR. It is causing a measurable regression when evaluating large projects.
Rewrote the routine using a similar approach as [this BCL method](https://github.com/dotnet/runtime/blob/6262ae8e6a33abac569ab6086cdccc470c810ea4/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L810-L840). Calculating only 2 and not 4 characters at a time, though, to reduce the complexity since our implementation works on a list of spans and not just one string. The additional perf benefit of going 4 at a time would be relatively small.
- A new unit test to verify correctness.
- Micro-benchmark showing 1.6x boost on x86 and 2x boost on x64.
- Evaluation perf traces showing significant reduction in the time spent …
=> Optimize InternableString.GetHashCode

src/Build/Definition/ToolsetConfigurationReader.cs, src/Shared/ToolsetElement.cs
Fixes #6667 
Tools configuration is read from MSBuild.exe.config multiple time. We can simply cache related configuration section to optimize config file access.
Changes are under opt-out escape hatch.
Cached in static variable. Caching is not applied in unit tests cases.
Rebuilds and incremental build of orchard core.
ETL has been captured to verify reading from MSBuild.exe.config was optimized.
When measured the real perf difference in both CPU and wall-clock time was negligible/non-verifiable.
=> Process-wide caching of ToolsetConfigurationSection

src/StringTools/InternableString.cs
@rokonec has pointed out that ref parameters disqualify locals from being enregistered, even if the method is inlined. The perf difference between keeping the running hash code in a register vs. on the stack is staggering.
Eliminated the ref parameter.
The code got 2.5x faster on .NET Framework x64, 1.3x faster on .NET Framework x86, and 3x faster on .NET Core x64.
=> Further optimize InternableString.GetHashCode by eliminating a ref parameter

src/Build/BackEnd/BuildManager/BuildManager.cs
Fixes #6823
There is possible deadlock in BuildManager vs LoggingService when:
- verbosity=diagnostic or higher or /bl
- LoggingService works in `LoggerMode.Synchronous`
LoggingService callbacks (OnProjectStarted, OnProjectFinished and OnThreadException) has been modified into async by leveraging existing workQueue.
Compiled Orchardcore in CLI and VS2022.
If these changes are considered safe, we can optionally revert PR #6717
=> Fix deadlock in BuildManager vs LoggingService

src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
We were only logging the arguments for messages, but not for errors or warnings. Fortunately we can fix this and avoid incrementing the binlog format version.
First this moves the logic to set the `Arguments` flag into a common code path close to `Message`, and only sets the flag when the arguments are present and we're either a message, warning or error. Previously it was only set for messages (and all types derived from `Message`).
Technically all `BuildStatusEventArgs` and `CustomBuildEventArgs` also inherit from `LazyFormattedBuildEventArgs`, but the serialization for them is fully manual and we don't even write the message for them at all. We ensure that if by any accident an instance of `BuildStatus` or some other random type such as `CustomBuildEventArgs` sets the `Arguments`, we …
=> Log message arguments for warnings and errors

src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
Fixes https://github.com/dotnet/msbuild/issues/6842#issuecomment-921168797
We use static for the `CoreClrAssemblyLoader` field so each unique SDK resolver assembly is loaded into memory and JITted only once. All subsequent load requests will return assembly from the assembly loader's cache instead of loading it again from disk. This change increases the performance of SDK resolution and at the same time avoids leaking memory due to loading the same SDK resolver assembly multiple times and never unloading it.
The `CoreClrAssemblyLoader` field in the `SdkResolverLoader` class was changed from non-static to static member. The same instance of `CoreClrAssemblyLoader` will be used by all instances of `SdkResolverLoader`. It is consistent now with other uses of `CoreClrAssemblyLoader` in …
=> Use static CoreClrAssemblyLoader in the SdkResolverLoader

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Resolves #6858
Add new properties introduced in https://github.com/dotnet/designs/blob/main/accepted/2021/winforms/streamline-application-bootstrap.md#msbuild-properties
Tested by updating the local version in C:\Program Files\Microsoft Visual Studio\2022\Preview\Xml\Schemas\1033\MSBuild and verifying in VS
=> Add new Windows Forms specific props

src/Tasks/Microsoft.Common.props
This reverts commit 74e9935a4a2e0108343533b3445516ad111e87ea.
dotnet/project-system#7432 added a design-time target called CollectSuggestedWorkloads to [Microsoft.Managed.DesignTime.targets](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets). However, WAP projects do not import the managed design-time targets so their design-time builds fail because the CollectSuggestedWorkloads design-time target cannot be found (see dotnet/project-system#7561).
#6813 worked around this by defining dummy targets in Microsoft.Common.props. This change cleans up that work-around by removing the dummy design-time targets.
Reverted #6813
1. Opened a solution that uses global.json to pin to …
=> Revert "Define stand-in optional workloads targets (#6813)"

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
The `DebugType` property has a set of expected values, and is not just a plain text property.
Currently completion on the `DebugType` property offers no guidance:
This change adds those values so they appear in completion. It also documents that `pdbonly` is equivalent to `full` in recent compilers.
None.
None.
=> Add enumeration values for DebugType in XSD

src/Tasks/ManifestUtil/SecurityUtil.cs
Default to sha2 digest instead of sha1 for clickonce manifest signing when certificate signing algorithm is sha256/384/512
Fixes #6732 
When using a certificate signed with sha384/sha512 as signature algorithm, ClickOnce defaults to the sha1 algorithm for it's digest hash.
UseSha256Algorithm decides if we sign with sha1 or sha256 hash. The function has been updated to use sha256 hash when signature algorithm of the signing cert has sha256/sha384/sha512 signature algorithm.
CTI has tested signing scenario for forms and wpf apps for all 4 hash types.
=> 6732: Default to sha2 digest for clickonce manifest

scripts/Deploy-MSBuild.ps1
We stopped producing those resources in a66a243f7, so the script shouldn't attempt to deploy them.
=> Deploy-MSBuild shouldn't deploy en resources

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes users who previously worked around the issue of msbuild not using the x64 version of AL.exe.
Only append `x64\` to `_AlExeToolPath` when `PlatformTarget` == `x64` AND `_AlExeToolPath` doesn't already end with `x64\`
Tested locally
=> Avoid appending x64 to AL path if x64 is already appended

README.md, documentation/wiki/Labels.md, src/Directory.Build.props
Added a doc with a table explaining some of the more frequently used labels, and the underlying processes that apply to them.
Once this is merged I'll update the bot's "close a stale issue" message with a link to the doc.
=> Add labels documentation

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #6887
Discussion: https://github.com/dotnet/msbuild/discussions/6871
`PlatformTarget `was initially passed to managed projects because `PlatformTarget` is passed directly to the compiler, while Platform is passed to the cpp compiler. After a deeper investigation, it turns out we can pass `Platform` and `PlatformTarget` will be defined either in the project file or by the SDK _based on Platform_.
Pass and undefine Platform instead of PlatformTarget.
Usage of PlatformTarget has been removed altogether, in favor of Platform.
Tested on all projects here: https://github.com/BenVillalobos/setplatform-repro
Also confirmed by jhennessey that this solves the issue.
=> SetPlatform: Use Platform Instead Of PlatformTarget

src/Tasks.UnitTests/CSharpParserUtilitites_Tests.cs, src/Tasks/CSharpParserUtilities.cs, src/Tasks/CreateCSharpManifestResourceName.cs
Fixes #6828
CreateCSharpManifestResourceName uses a c# file parser to extract the namespace and classname to create its resource name. See the original issue for a clear explanation on how this breaks with file-scoped namespaces.
Modify the state machine within the csharp parser to stop looking for a namespace when we encounter a semicolon.
Review the final diff
=> Enable File Scoped Namespaces For Resources

src/Tasks/XslTransformation.cs
Fixes #6847
When XmlReader.Create is called and a file path is passed in, it's converted to a URI under the hood. This can mangle multi-byte characters. The solution (in the link above) is to initialize the XmlReader using a stream to the file instead of the path alone.
Call XmlReader.Create with a stream that will detect encodings.
Tested using repro in #6847
=> Initialize XmlReaders using StreamReaders

eng/SignCheckExclusionsFile.txt, eng/common/templates/post-build/post-build.yml
Fixes official builds
The msbuild intermediate sourcebuild package isn't expected to be signed and is causing failures because official builds think they are. Let's exclude the package.
=> Delete intermediate sourcebuild package

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Fixes #6782
When using MSBuildLocator, the first process you start is named after your app, not dotnet or msbuild, yet it still loads MSBuild assemblies. When it then starts an out-of-proc build on core, it tries to use the current host, which is normally dotnet.exe, but in this case is <yourApp>.exe. MSBuild can't find it to connect, so it assumes it launches another node. It should stop after that, but it just keeps going and makes hundreds or thousands of nodes until your computer crashes. That is bad. This defaults to looking for a nearby dotnet.exe (if you're on core) and uses that instead, falling back to <yourApp>.exe only on failure. This should handle any case in which you find MSBuild in an sdk installation.
Look for a dotnet.exe instead of your current host.
Broke repro.
Do not …
=> Find dotnet.exe instead of <name>.exe when building out-of-proc using MSBuildLocator

Directory.Build.props
Arcade no longer has this problem, so no need to exclude.
=> Remove NoWarn for NU5125

src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf, src/MSBuild/XMake.cs, src/Shared/EncodingUtilities.cs, src/Shared/NativeMethodsShared.cs, src/Tasks/FileState.cs
Per https://docs.microsoft.com/en-us/visualstudio/releases/2022/system-requirements, Visual Studio 2022 is not supported on pre-Windows 10 OS.
Updated and removed Windows version checks accordingly.
Build and smoke test on Windows 10.
=> Clean up minimum Windows version checks

eng/Packages.props
Fixes https://github.com/dotnet/msbuild/issues/6961
> BannedApiAnalyzers has some intentional old dependencies and it's not feasible to build it during source-build. It's already been removed from source-build and we need to remove usages. https://github.com/dotnet/roslyn-analyzers/issues/5619
> 
> BannedApiAnalyzers isn't one of the analyzers that ends up in the SDK product, so the only reason for source-build to build it is for code validation parity when building MSBuild's C# source code. That would help source-build developers write upstreamable code if the MSBuild C# code needs to be patched, but dev flows aren't the primary goal of source-build right now.
Moved `GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers"` into an item group that is excluded during …
=> Disable BannedApiAnalyzers during source-build to avoid a prebuilt dependency

src/Build.UnitTests/TestComparers/ProjectInstanceModelTestComparers.cs, src/Build/Instance/ProjectItemGroupTaskItemInstance.cs
Project cache usage forces all projects to be evaluated on the main node. When a project gets a cache miss, it gets built. When that build gets scheduled on an out of proc node, the project instance gets serialized to that node. Some recent change in msbuild turns on full project instance translation, and a bug in item element translation (incomplete translation) makes the task builder crash with a null pointer for metadata location.
This could also crash for all other VS scenarios that end up triggering full project instance translation.
Added missing translation of match on metadata attribute locations
Updated incomplete unit test
=> Add missing match on metadata location translation

src/Build/ElementLocation/XmlAttributeWithLocation.cs, src/Build/ElementLocation/XmlElementWithLocation.cs
When ownerDocumentWithLocation.FullPath is null, then ElementLocation is always created.  This is because ElementLocation.Empty.File is " " (empty not null).
This can occurs when a project is created from memory or loaded from a stream which loses all file information.  
Add null check.
Standard unittest
=> Check if Documentis null before creating elementlocation object

src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs, src/Build/Utilities/EngineFileUtilities.cs, src/Shared/FileUtilities.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Fixing a few places where we allocated objects unnecessarily. This is by no means exhaustive.
- `GetOrAdd` should be given a delegate to a method that creates a new object, not the new object itself. Otherwise we allocate and throw away the object in the "Get" case.
- When passing a callbacks to a method, a lambda expression should be used even if all arguments are passed-through. Otherwise a new delegate object is allocated on each invocation. Lambdas are cached in static fields by the compiler.
Existing unit tests.
=> Minor allocation optimizations / cleanup

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Update the allowed values enumeration for `AnalysisLevel` and `AnalysisMode` as per the changes in .NET6. Documentation at https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#analysislevel and https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#analysismode respectively
=> Update Microsoft.Build.CommonTypes.xsd for `AnalysisLevel` and `AnalysisMode` values

eng/Packages.props
Fixes https://github.com/dotnet/msbuild/issues/6935
See https://github.com/dotnet/msbuild/pull/6966#issuecomment-949888555
Remove the package reference on `Microsoft.NETFramework.ReferenceAssemblies/1.0.0`, which should let the SDK provide a `Microsoft.NETFramework.ReferenceAssemblies/1.0.2` (or higher) reference.
Built on Fedora 33 Linux with `./build.sh`.
@KirillOsenkov Can you give this a shot?
=> Remove pinned .NET Framework ref assembly package: let SDK provide it

src/Build/Evaluation/LazyItemEvaluator.RemoveOperation.cs
Fixes #6985
RemoveOperation currently requires either not MatchOnMetadata or that the fragments are ItemSpec<ProjectProperty, ProjectItem>.ItemExpressionFragments. The latter is how we do it in tests, but in the wild, we use ProjectPropertyInstance and ProjectItemInstance. It sounds like those two should extend the other two, but they don't. I think it would be valid to make them do so, but this is a minimal change that resolves the issue such that it passes both tests and the repro case in #6985 by essentially letting how Remove is invoked dictate what the type has to be.
Switch to generic P and I.
Unit tests + verified the repro case no longer repros.
=> Simplify property/item type requirements Fixes #6985

src/Build/ElementLocation/XmlDocumentWithLocation.cs
MSBuild currently loads all files whose name starts with `Microsoft.DevDiv` as read-only. It is breaking scenarios where such files are legitimately written to. It is unfortunate to use hard-codes names in general.
Removed the special handling.
Ideally would verify that the Visual Studio repo builds fine with this change but it looks like too much hassle for such a safe change (famous last words).
=> Stop loading Microsoft.DevDiv files as read-only

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Fixes #6782
Follow-up of #6890
Tried `DisableInProcNode = false` and couldn't make it work.
After some investigations, it turns out the code in `NodeProviderOutOfProcBase.GetCurrentHost()` has some issues:
https://github.com/dotnet/msbuild/blob/24b33188f385cee07804cc63ec805216b3f8b72f/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L593
In my case, `CurrentMSBuildToolsDirectory` returns `C:\Program Files\dotnet\sdk\6.0.100\MSBuild.dll`.
`FileUtilities.GetFolderAbove()` 2 levels makes it try to resolve `dotnet.exe` from `C:\Program Files\dotnet\sdk\dotnet.exe` instead of `C:\Program Files\dotnet\dotnet.exe`.
I believe this is because the filename itself was not taken into account (it counts as 1 extra step for `FileUtilities.GetFolderAbove()`)
Used …
=> CurrentHost was not properly set when DisableInProcNode = false

src/Tasks/CreateCSharpManifestResourceName.cs, src/Tasks/CreateVisualBasicManifestResourceName.cs
Fixes #5551
Addressing a small inefficiency pointed out in #5551. If the task is given multiple resource files it wastefully creates a new `StringBuilder` for each.
Reuse a cached `StringBuilder` when creating resource names.
Existing unit tests.
- The `StringBuilder` is not used "append-only" so this is *not* a good fit for `SpanBasedStringBuilder`.
- I did not put the release call inside a finally block because if the code throws an exception "leaking" a `StringBuilder` is not a big deal with very minor perf impact compared to the exception handling machinery.
=> Use cached StringBuilder in CreateManifestResourceName

src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
For 16.9 we made a change where bootstrapper packages can specify "0" for the public key value of a downloaded file and this will cause the bootstrapper to skip the public key comparison as long as the file is signed with a trusted MS cert.  However, we didn't account for the scenario where a user wants to create a self contained bootstrapper, meaning it will include a copy of the package's installer.  In this scenario we still perform the public key comparison and give a build warning when they don't match.  This change skips this check when the package specifies 0 for the public key of the file in question.
See the following thread: https://docs.microsoft.com/en-us/answers/questions/583383/publickey-token-warning-building-net-core-50-insta.html?childToView=602746#comment-602746
Skipping …
=> Preventing warning in bootstrapper package self contained scenario

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
A long time ago, I was struggling with a bug in which we created thousands of MSBuild nodes. ~~Looking at our code for creating nodes, we fail early in NodeProviderOutOfProc if (_nodeContexts.Count == ComponentHost.BuildParameters.MaxNodeCount). We have an equivalent check in NodeProviderOutOfProcTaskHost. We don't in NodeProviderInProc, presumably because we shouldn't ever have > 1 in proc node.~~
Actually, I don't think this is true because _nodeContexts aren't shared between providers. That said, rainersigwald pointed out this is still helpful if we parallelize this.
I'm wondering if the explosion might be avertable by changing the ​==​ to ​>=​. If we haven't used the in-proc node for whatever reason and we use MaxNodeCount nodes, and then we create an in-proc node, we'd have …
=> Attempt to prevent node explosions with parallel node creation

global.json
We no longer target or use .NET Core 2.1 for tests so no point in downloading the runtime.
=> Remove reference to .NET Core 2.1

.vscode/tasks.json
These are the main scenarios I want quick access to.
This came in handy when iterating with a bajillion errors across the whole codebase in #7016.
=> Add VS Code tasks.json

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
The `CopyToOutputDirectory` property only supports values `Never`, `Always` or `PreserveNewest`.
MSBuild provides an XSD file that drives IntelliSense in VS when editing project XML.
Earlier today we were debugging a broken incremental build related to the use of `Always`. It wasn't obvious what the correct value should be, as no IntelliSense was provided in VS.
This change allows VS and other consumers of the XSD to suggest and validate that the provided value is valid.
The property on some item types was previously declared incorrectly as being a boolean.
None.
=> Add enumeration values for CopyToOutputDirectory in XSD

ref/Microsoft.Build/net/Microsoft.Build.cs, ref/Microsoft.Build/netstandard/Microsoft.Build.cs, src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build.UnitTests/Globbing/CompositeGlob_Tests.cs, src/Build.UnitTests/Globbing/MSBuildGlobWithGaps_Tests.cs, src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs, src/Build/BackEnd/Shared/BuildRequestConfiguration.cs, src/Build/Definition/Project.cs, src/Build/Evaluation/ItemSpec.cs, src/Build/Globbing/CompositeGlob.cs, src/Build/Globbing/IMSBuildGlob.cs, src/Build/Globbing/MSBuildGlob.cs, src/Build/Globbing/MSBuildGlobWithGaps.cs, src/Build/Globbing/Visitor/GlobVisitor.cs
Traces of devenv during build showed a lot of CPS activity related to glob evaluation. Investigation of the code showed a few opportunities to eliminate some allocations and reduce work during construction and matching.
- Eliminate allocation of `CompositeGlob` wrapper for zero or one child (seems very common)
- Eliminate enumerator allocation in `CompositeGlob.IsMatch`
- Eliminate array allocation when constructing `CompositeGlob`
- Eliminate array allocation when constructing `MSBuildGlobWithGaps`
- Fix `CompositeGlob(IEnumerable<>)` ctor optimisation (missing `else` block)
- Make struct readonly
- Use pattern matching
- Typos & documentation
- Unit tests
This is probably easiest to review one commit at a time.
=> Improve globbing performance

.vsts-dotnet-ci.yml
macOS-10.14 is being deprecated December 2021.
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
=> Update mac version for CI

src/Tasks/AssemblyDependency/Resolver.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
When RAR is trying to find the closure of dependencies of the input
assemblies, it searches for assemblies based on identity in paths next
to currently known assemblies. Today, if there is a file of the expected
name that is not a well-formed managed assembly, RAR will silently
ignore it, without reporting any details about the file.
This changes the RAR output format
```
Dependency "DotLiquid, Version=2.0.174.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c".
Could not find dependent files. Could not load file or assembly 'DotLiquid.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
Could not resolve this reference. Could not locate the assembly "DotLiquid, Version = 2.0.174.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c". Check to …
```
=> RAR: Log full path of bad-image failures

src/Package/MSBuild.VSSetup/files.swr
This file is not used in normal MSBuild operation because Visual Studio
and MSBuild both have binding redirects to use the version from the GAC
in .NET Framework, but if an API client application doesn't have such a
binding redirect, they might fail. This keeps users of MSBuildLocator
working by shipping the file for their use.
Fixes #6976.
=> Ship System.ValueTuple.dll to VS

eng/Build.props
Temporary workaround for https://github.com/dotnet/msbuild/issues/7058 to unblock source-build while it is being investigated.
=> Disable RestoreUseStaticGraphEvaluation for source-build

src/Directory.Build.props
This works around an odd misconfiguration in the internal 1ES 2022 pools that they use the latest .NET SDK but a preview VS/MSBuild.
=> Disable ValidateExecutableReferences

src/Shared/CoreCLRAssemblyLoader.cs, src/Shared/MSBuildLoadContext.cs
Fixes #6993
See issue.
Switched to also load if the found assembly is greater than what was requested.
CI? I had trouble repro'ing this.
=> Loosen version comparisons in loading assemblies

src/Build/Globbing/CompositeGlob.cs, src/Build/Microsoft.Build.csproj, src/Build/Utilities/ImmutableCollectionsExtensions.cs
@Therzok provided some additional feedback on PR #7040 after it was merged. This PR addresses that feedback.
- Avoid allocating a closure object for each call to `CompositeGlob.IsMatch` by adding an overload of `Any` that allows passing state on the stack.
- Other API substitutions for better run time, though these code paths are not used in product code (they would be removed if not public).
Unit tests.
=> Remove closure allocation in CompositeGlob.IsMatch

src/MSBuild/app.amd64.config, src/MSBuild/app.config
Fixes #7047.
These worked in 32-bit MSBuild because the values are placed only in the
32-bit registry.
```sh-session
❯ reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8" /s
ERROR: The system was unable to find the specified registry key or value.
msbuild on frameworkpath-reg-wow [$+] via .NET v6.0.100
❯ reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8" /s /reg:32
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8
InstallationFolder    REG_SZ    C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\
ProductVersion    REG_SZ    4.8.03928
ProductName    REG_SZ    Microsoft .NET Framework 4.8 SDK
KitsInstallationFolder    REG_SZ    C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\ …
```
=> Get Microsoft SDK paths from 32-bit registry

src/MSBuild/app.amd64.config, src/MSBuild/app.config
I observed a failure in NuGet restore because a NuGet task wasn't able to
access this assembly because we updated it. The binding redirect wasn't
working because it referred to a partial name.
=> Fix binding redirect for System.Threading.Tasks.Dataflow

documentation/wiki/ResolveAssemblyReference.md, src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #3784
AssemblySearchPaths are currently set using a property (not an item because order often matters) in which either the user sets all of them or the user accepts the default. This allows the user to accept some or most of the default without accepting all of it.
It may also be reasonable to add:
```XML
<AssemblySearchPaths Condition="'$(CustomAssemblySearchPaths)' != ''">$(AssemblySearchPaths);$(CustomAssemblySearchPaths)</AssemblySearchPaths>
```
though that would only allow users to add custom paths at the predefined spot, so it may not be too helpful. I'm also unsure if it would be most likely to be used if it's first, last, or just before OutDir.
=> Permit individually settable search paths

src/MSBuild/app.amd64.config, src/MSBuild/app.config
This comes in transitively via System.Text.Json and so was missed when updating
binding redirects to the 6.0.0 versions.
=> Update System.Text.Encodings.Web binding redirect

eng/dependabot/Packages.props, src/MSBuildTaskHost/MSBuildTaskHost.csproj
Closes #6935.
These references were not removed by #6966, but could have been.
=> Drop remaining jnm2.ReferenceAssemblies.net35 references

src/Directory.Build.props
Reverts dotnet/msbuild#7065 since the official build machine image has now been updated (see passing internal build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5474330&view=logs&j=834effc5-0088-5346-39e6-11e704da850d&t=dbe71018-a6bc-5bc7-ce4d-4aa6967c40a7&l=166).
=> Revert "Disable ValidateExecutableReferences"

src/Shared/BuildEnvironmentHelper.cs
Fixes: VS Insertion PR nr: 366256
DDRIT detected memory regression. It was caused by wrongly initialize `Traits` as `running unit tests` so It allocates new `Traits` instance as oppose to use singleton.
Simple fix.
Locally
=> Fixing bug detected by DDRIT

src/Build/Evaluation/Evaluator.cs
Fixes #6307
Evaluator sometimes allocates `List<ProjectRootElement>` instances when it's not necessary.
Collection allocation is postponed and empty `Enumerable` singleton is used to represent empty result.
@drewnoakes I tried to use `ImmutableArray`, but it produced more allocations - builder is copying underlying array when creating instance of the immutable collection.
I tracked `List<ProjectRootElement>` allocations while building simple solution with two empty C# projects (.NET Framework and Core). Number of allocated instances dropped from 264 to 178.
This optimization looked like good first issue to solve, but complexity of the `Evaluator` is IMHO high and using `out` parameters for these collections makes it more difficult to track their flow :)
=> Evaluator allocation optimization

src/Build/Collections/CopyOnWritePropertyDictionary.cs, src/Build/Construction/ProjectTaskElement.cs, src/Build/Instance/ProjectInstance.cs, src/Build/Instance/ProjectItemDefinitionInstance.cs, src/Build/Instance/ProjectItemInstance.cs, src/Build/Instance/ProjectTaskInstance.cs, src/Shared/CopyOnWriteDictionary.cs
Context
The underlying immutable dictionaries are implemented as trees and as such the concept of 'capacity' does not apply.
Removing these parameters and their arguments from call sites can avoid some redundant work.
- Remove `capacity` parameters from constructors.
- Resolve conflicts between then-identical constructors.
- Update call sites.
Unit tests.
=> Remove unused 'capacity' parameter for COW dictionaries

src/Build.UnitTests/Evaluation/Expander_Tests.cs
Fixes #7027
String result of the `PropertyFunctionMSBuildDivide` test depends on the regional settings, but the `expected` value assumes US decimal symbol, so the test is failing for regional settings with different decimal symbol.
`ToString` is called on constant double value to respect current formatting.
=> Fixed test that is dependent on current regional settings

src/Deprecated/Engine/Caching/BuildItemCacheEntry.cs
Noticed this while browsing code.
This loop verifies all items in one list are present in another. Previously this involved `ArrayList.Contains`, which is O(N). As this happened in a loop, the time complexity comes out to O(N^2). Using a `HashSet<>.Contains` instead allows O(1) lookup within the loop, leading to an overall complexity of O(N).
Unit tests.
=> Replace O(N^2) with O(N)

src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs, src/Framework/Sdk/SdkResultItem.cs
Fixes #6750 
The issue #6750 describes that implementation of Equals and GetHashCode is still buggy, and it is not reliable. This change ensures that: 
1. Equals won't throw Exception,
2. Equals compare Key and its value between each KeyValues in Metadata's Key and values
3. Remove additional null check on Metadata, because Metadata property will not be null
Refactor Equals and GetHashCode methods to ensure reliable comparison as suggested in https://github.com/dotnet/msbuild/issues/6750#issue-967522986
=> Fix #6750 `SdkResultItem` equality

documentation/wiki/ChangeWaves.md, src/Tasks/Microsoft.Common.CurrentVersion.targets
Reverts dotnet/msbuild#6718
Fixes #6543.
=> Move reference assemblies into obj (again)

src/Tasks/Al.cs
Fixes #7101
The AL task's Platform property is used to find the architecture, but it can be null. If it is, we should just use the current process architecture. Instead, we were throwing a null reference exception after #7051.
Switch to yoda condition. Prevents NRE.
None
=> Prevent null reference exception with null Platform when using AL task

src/Build/BackEnd/Components/ProjectCache/PluginLoggerBase.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/PublicAPI/net/PublicAPI.Shipped.txt, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Shipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
The overall goal I'm trying to achieve is general logging cleanup of the project cache code. Currently it looks nothing like regular MSBuild logging, isn't associated with projects, and various other quirks.
This specific change is a light refactor of how the `PluginLoggerBase` provided to plugins is created. It allows for eventually providing the `BuildEventContext`.
It also removes an unused Verbosity provided to the logger. This is technically a breaking change to the public API, although a) `PluginLoggerBase` is in the experimental namespace, b) project cache is new and not likely to be widely used, and c) callers have no way currently to provide their own instance of `PluginLoggerBase`, so subclassing it in the first place makes no sense and thus is very likely not done outside of …
=> Minor refactor around project cache logging

src/Build.UnitTests/BackEnd/TargetBuilder_Tests.cs, src/Build.UnitTests/BackEnd/TargetEntry_Tests.cs, src/Build/BackEnd/Components/Logging/NodeLoggingContext.cs, src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs, src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
Just a small cleanup of `ProjectLoggingContext`. 
Specifically:
* Removed the `NodeLoggingContext` property. It was unused
* Removed some ctor params which could be retrieved from sub-objects of other params and which callers *always* provided those values form the sub-objects already
=> Minor cleanup of ProjectLoggingContext

src/Build/Instance/ProjectInstance.cs
While writing a unit test, I hit exceptions here due to having empty collections.
Ensure a non-negative number is passed for the list's capacity.
Fixed error I was seeing in unit test.
=> Avoid range exceptions when collections empty

src/Build.UnitTests/Collections/CopyOnWritePropertyDictionary_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Collections/CopyOnWritePropertyDictionary.cs, src/Build/Instance/ProjectItemInstance.cs
Some more optimisation of collection types, focussing on  `CopyOnWritePropertyDictionary<>`.
Previously, `CopyOnWritePropertyDictionary<>` wrapped a  `CopyOnWriteDictionary<>` which in turn wrapped an `ImmutableDictionary<>`.
That middle layer is redundant. Removing it reduces allocations, reduces indirection, replaces virtual calls with non-virtual ones, and allows for more optimal construction of the inner data structures.
By using `ImmutableDictionary<>` directly in `CopyOnWritePropertyDictionary<>` it's possible to remove all locking from the class entirely.
Other changes:
- Remove unused and obsolete members
- Add unit tests (which pass both before and after the core change here)
It may be easiest to review this PR commit by commit.
Unit tests.
=> Remove locking and indirection from CopyOnWritePropertyDictionary

src/Directory.Build.targets
This package is only super relevant at PR-build time so it should
be fine to drop it from source-build scenarios. Fixes #7115.
cc @MichaelSimons
=> Don't reference PublicApiAnalyzers in sourcebuild

src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs, src/Build.UnitTests/BackEnd/MockLoggingService.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/Logging/ILoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/BackEnd/Shared/BuildRequest.cs
This change creates a `projectContextId` during project cache execution to use for logging. Then that same `projectContextId` is used for the build execution (if needed) so that the cache-related log messages are structured under the build execution for that project.
Although the cache-related log messages come before the "project started" event, the somehow still get nested under it, both in console logging(!?) and binary logging. This is what we want anyway though, so I won't question it.
Example of the change in structure. Left is current, right is new:
In a future change I plan to clean up the hard-coded log messages that the `ProjectCacheService` uses in favor of properly localized string which also look more "MSBuild-y".
Note that commits are broken down to perhaps make reviewing …
=> Associate Project Cache log messages with the project execution

src/Tasks/CodeTaskFactory.cs
Fixes #7108 by moving the check of whether a given assembly is one of
the ones we'll provide by default to occur before the assembly is
loaded. This should prevent loading the amd64 copy of either assembly
side-by-side with the bin copy, and thus keep downstream consumers
from getting type definitions from the wrong assembly.
=> Avoid loading Framework/Utilities in CodeTaskFactory

eng/dependabot/Packages.props, src/MSBuildTaskHost/MSBuildTaskHost.csproj
This is no longer needed per the dotnet/sourcelink documentation, and even
without it I still see the sourcelink JSON in `MSBuildTaskHost.pdb`.
=> Remove SourceLink.Create.CommandLine

src/Build/BackEnd/BuildManager/CacheSerialization.cs, src/Tasks/GenerateResource.cs
The method `CacheSerialization.SerializeCaches` was using `File.OpenWrite(fullPath)` which is pretty confusing if a file already exists, as it will write to it without truncating it. So if a cache file was 10MB and we then write a file that is just 5KB, the file will still be 10MB.
- Use `FileStream` constructor instead with a more adequate behavior.
=> Fix bug in CacheSerialization.SerializeCaches

documentation/wiki/ResolveAssemblyReference.md, src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #3784 and Updates #7008
Follow-ups from
1. https://github.com/dotnet/msbuild/pull/7008#pullrequestreview-836812544
2. https://github.com/dotnet/sdk/pull/22719#discussion_r773444947
For multi-level properties, follow the naming pattern similar to `BaseProperty_SubOption` with an `_`
underscore character acting as a separator to make these properties clearer. We already follow this
pattern in Common props where we have `DisableLogTaskParameter_ConvertToAbsolutePath_Path`and friends.
https://github.com/dotnet/msbuild/blob/14313d17e407e24ad80e113bd475d1dd7c698656/src/Tasks/Microsoft.Common.props#L181-L183
So, Use `AssemblySearchPath_Use{Variant}` property format to control individual inclusion of different
variants of assembly search paths. By default, these properties will be opt-out …
=> Rename `AssemblySearchPathUseXXX` to `AssemblySearchPath_UseXXX` for better readability

documentation/specs/event-source.md, src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/SdkLogger.cs, src/Framework/MSBuildEventSource.cs, src/Framework/PublicAPI/net/PublicAPI.Unshipped.txt, src/Framework/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Framework/Sdk/SdkLogger.cs
Fixes #7136
Adding on to https://github.com/dotnet/msbuild/pull/6876, this change adds more events to SDK resolution.
1. Add boolean to `CachedSdkResolverServiceResolveSdkStop` so we can differentiate cached and non-cached calls
4. Add `OutOfProcSdkResolverServiceRequestSdkPathFromMainNodeStart` and `OutOfProcSdkResolverServiceRequestSdkPathFromMainNodeStop` events to track how long it takes to send/receive an SDK result from the main node
5. Add `SdkResolverEvent`, `SdkResolverEventStart`, and `SdkResolverEventStop` methods to `Microsoft.Build.Framework.SdkLogger` so that SDK resolvers can contribute to the events in SDK resolution.
=> Add more SdkResolverService events and allow SdkResolvers to log events

eng/cibuild_bootstrapped_msbuild.ps1
Failing to use the compiler server slows down the build and shouldn't be necessary.
=> Stop disabling compiler server in bootstrapped/CI build

src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/ProjectRootElementCache.cs, src/Build/Evaluation/ProjectRootElementCacheBase.cs, src/Build/Evaluation/SimpleProjectRootElementCache.cs
Fixes possible race condition in `ProjectRootElementCache.Get` supposedly introduced in #6680.
Passing a load function that uses `ProjectRootElementCache.Get` to `ProjectRootElementCache.Get` function could lead to failure (to verify a path in the loaded ProjectRootElement), due to a race condition. We eliminate calling `ProjectRootElementCache.Get` inside the load function, eliminating an unnecessary double entry to `ProjectRootElementCache.Get` function.
- Remove double entry to `ProjectRootElementCache.Get` function that could cause race condition.
- Adjust path verification in `ProjectRootElementCache` and `SimpleProjectRootElementCache` to be more safe and to have more information.
Unit tests + manual testing
The stack trace of failure:
```
> ##[error]C:\Program Files\Microsoft …
```
=> Fix possible race condition in ProjectRootElementCache.Get

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Build/Graph/GraphBuilder.cs
Fixes #6925
If you have a cycle in your ProjectReferences, that should be caught and marked as invalid with MSB4251. If you do a graph build, however, it turns into a StackOverflowException, which is much less clear. This handles circular dependencies, giving the nicer exception.
Ensures that each project "marks" itself as not to be revisited before the recursive call so that you cannot get endless recursion.
Tried with the original repro and got MSB4251 as desired.
The first commit maintains the previous caching behavior. It isn't obvious to me how much benefit there really is here, and I have yet to test it. In particular, although it could save you a good bit of work, it costs creation and manipulation of a series of intermediate HashSets that are all stored in a Dictionary, so GC …
=> Fix stackoverflowexception

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
- Fix an incorrect comment on the `DisableFastUpToDateCheck` property
- Add items for `UpToDateCheckInput`, `UpToDateCheckOutput` and `UpToDateCheckBuilt`
CI
- I added new `locID_text` entries in the XML comments. Is anything else needed here?
=> Update up-to-date check items/properties in XSD 

src/Build/BackEnd/Components/Logging/LoggingService.cs
If there's an environment variable `MSBUILDLOGPROPERTIESANDITEMSAFTEREVALUATION`, it should take precedence over the logic that sets it to false if any logger hasn't opted in.
=> Force `IncludeEvaluationPropertiesAndItems` if escape hatch is set

src/Build/Definition/ProjectCollection.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs, src/Build/Logging/ProfilerLogger.cs, src/Framework/Sdk/SdkReference.cs, src/Framework/Sdk/SdkResolver.cs, src/Framework/Sdk/SdkResolverContext.cs, src/Framework/Sdk/SdkResult.cs, src/Tasks/CodeTaskFactory.cs, src/Tasks/Copy.cs, src/Tasks/Hash.cs, src/Tasks/Unzip.cs
Fixes https://github.com/dotnet/msbuild/issues/7151
Doc comments are changed from time to time in the dotnet-api-docs repo. These changes need to be ported back to the MSBuild source, now that the MSBuild source is being used as the source-of-truth for MSBuild reference docs.
Comment-only changes in a number of source files.
The changes that were required can also be found here: https://github.com/dotnet/dotnet-api-docs/pull/7484 - this docs PR was necessary to prevent the dotnet-api-docs changes from being overwritten when the comments were re-read from MSBuild sources for the 17.0 version of MSBuild.
=> Port doc comment changes from docs repo

README.md, eng/Versions.props
16.7 is still in support for now.
Don't merge this until 17.1 is updated. I can't request changes on my own PR, though.
=> 17.2 branding

src/Shared/UnitTests/TestAssemblyInfo.cs
Fixes #7195
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1050
=> CA1050: Declare types in namespaces

documentation/wiki/Binary-Log.md
For 64-bit VS, we had to fork the extension.
Link to both versions of the extension.
N/A
N/A
=> Add link to VS2022 ProjectSystemTools extension

documentation/specs/event-source.md
=> Adds recently added ETW events to event-source.md

src/Tasks/GenerateResource.cs
Fixes #7229 by ensuring that MSBuild's processing of a `.txt` resource holds only the minimal lock: open for read and allowing other processes to read while it's open.
=> Share read for text resource files

src/Xunit.NetCore.Extensions/Xunit.NetCore.Extensions.csproj
That project references Xunit.Core (because it needs xunit types), which defines IsTestProject=true. Then Arcade's tests.targets checks that and imports XUnit.targets
https://github.com/dotnet/arcade/blob/98018d5a808e5167a4ce5e81dc6513382676d4c9/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L83
which adds a reference to xunit.runner.visualstudio
https://github.com/dotnet/arcade/blob/98018d5a808e5167a4ce5e81dc6513382676d4c9/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L10
even though that's not really needed.
Fixes #7212
All credit to @rainersigwald (see the bug). I just tested it.
=> Fix NU1701 warning Fixes #7212

eng/Common.globalconfig
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1023.md
=> SA1023 Dereference symbol '*' should not be preceded by a space.

eng/Common.globalconfig, src/Build.UnitTests/Definition/ToolsetConfigurationReader_Tests.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1020.md
=> SA1020 Increment symbol '++' should not be preceded by a space

eng/Common.globalconfig, src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/ConstructionLinkMocks/ProjectElemetExportHelper.cs, src/Build.OM.UnitTests/ObjectModelRemoting/RemoteProjectsProviderMock/ExporterMock.cs, src/Build.UnitTests/BackEnd/ConfigCache_Tests.cs, src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs, src/Shared/UnitTests/FileMatcher_Tests.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1015.md
=> SA1015 Closing generic bracket should not be followed by a space

eng/Common.globalconfig
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1006.md
=> SA1006 A C# preprocessor-type keyword is preceded by space.

src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.en.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
While writing a unit test I hit this exception and found the error message slightly misleading.
The `ProjectLoadSettings` enum does not contain a member named `RecordDuplicateImports`. This string appears to be referring to the `RecordDuplicateButNotCircularImports` member.
Changed the content of the resource string.
CI.
I've updated the XLF files manually to avoid a loc pass. Please verify that this is safe to do, and that the loc team doesn't have a shadow copy of these strings somewhere else that is considered the source of truth.
=> Fix enum member name in resource string

src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
So far we've only respected EmbedInBinlog items during ProjectEvaluationFinished (or ProjectStarted, wherever the eval items are logged).
This simple change also respects EmbedInBinlog items added from ItemGroups inside Targets during target execution.
We can now insert "printf" targets in any place in the build to embed arbitrary files in the binlog at the time that target runs.
This could also allow embedding the same file more than once, if we first copy into a temp file with a timestamp or target name attached. This can allow capturing the state of files at various stages of the build.
I have tested it and it works.
=> Embed EmbedInBinlog items added within targets

documentation/wiki/ChangeWaves.md
Some changes got in without the changewaves docs being updated. This brings that doc up to date.
Added notes for more recent changes
=> Bring changewaves.md up to date

src/Build/Logging/SerialConsoleLogger.cs, src/Tasks/ParserState.cs
Whilst going through the code I noticed the use of [`Stack`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.stack?view=net-6.0). In the documentation it suggests using [`Stack<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.stack-1?view=net-6.0).
Change `Stack` to `Stack<T>`
=> Use Stack<T> instead of Stack

eng/Common.globalconfig
Follow up to #7201 as we forgot to switch severity to warning.
=> Enable warning on SA1125

src/Build/BackEnd/BuildManager/BuildRequestData.cs
Minor change to remove an extra defensive copy of an array. A `BuildRequestData` ctor overload copies it despite the `this` ctor it calls also copying it.
~Also a very minor perf change to use an array and copy via `CopyTo` instead of cloning with a `List<>`.~
=> Remove redundant copy of BuildRequestData.TargetNames

eng/Common.globalconfig, src/Tasks/Hash.cs, src/Tasks/ManifestUtil/Util.cs, src/Tasks/ManifestUtil/mansign2.cs
Relates to #7174 
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/CA5350
I just updated the suppression attributes.
=> CA5350 Do Not Use Weak Cryptographic Algorithms

eng/Common.globalconfig
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1122.md
=> SA1122 Use string.Empty for empty strings

eng/Common.globalconfig, src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs, src/Tasks/GenerateResource.cs, src/Tasks/ManifestUtil/ApplicationManifest.cs, src/Tasks/ManifestUtil/SecurityUtil.cs, src/Tasks/ManifestUtil/Util.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1519.md
=> SA1519 Braces should not be omitted from multi-line child statement

eng/Common.globalconfig, src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs, src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs, src/Build.UnitTests/EventArgsFormatting_Tests.cs, src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs, src/Build/BackEnd/Shared/BuildRequest.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs, src/Build/Evaluation/LazyItemEvaluator.OrderedItemDataCollection.cs, src/Build/Instance/ProjectItemGroupTaskItemInstance.cs, src/Build/ObjectModelRemoting/LinkedObjectFactory.cs, src/MSBuild.UnitTests/XMake_Tests.cs, src/Shared/BufferedReadStream.cs, src/Shared/UnitTests/FileUtilities_Tests.cs, src/Tasks.UnitTests/ReadLinesFromFile_Tests.cs, src/Tasks.UnitTests/WriteCodeFragment_Tests.cs, src/Tasks/WriteCodeFragment.cs, src/Utilities.UnitTests/CommandLineBuilder_Tests.cs, src/Utilities.UnitTests/EventArgsFormatting_Tests.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1508.md
=> SA1508 A closing brace should not be preceded by a blank line

eng/Common.globalconfig, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1408.md
=> SA1408 Conditional expressions should declare precedence

eng/Common.globalconfig, src/Build/BackEnd/BuildManager/BuildParameters.cs, src/Build/BackEnd/Components/RequestBuilder/Lookup.cs, src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs, src/Build/BackEnd/Node/INode.cs, src/Build/Definition/Project.cs, src/Build/Definition/ProjectCollection.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1135.md
=> SA1135 A using directive is not qualified

eng/Common.globalconfig, src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1216.md
=> SA1216 Using static directives should be placed at the correct location

src/Framework/LazyFormattedBuildEventArgs.cs
Fixes #7015
The intent was to stash the current culture when the event args are created and then use it for formatting (which may happen later). It turns out that despite the code in `WriteToStream` and `CreateFromStream`, the culture doesn't propagate when our args are serialized and deserialized; see how new instances are created during deserialization:
https://github.com/dotnet/msbuild/blob/14efa06d736aabb3af01ff827fff9426518f5fac/src/Shared/LogMessagePacketBase.cs#L517-L535
This, together with @KirillOsenkov's comment in the linked issue, and the general doubt about the incidence of scenarios where this would be useful (a custom task emitting custom build events, explicitly changing the current culture, and relying in the culture-specific formatting) makes me want to take the risk and …
=> Remove CultureName and CultureInfo from LazyFormattedBuildEventArgs

src/Build/Evaluation/Conditionals/Token.cs, src/Build/Graph/ProjectInterpretation.cs, src/Deprecated/Engine/Conditionals/Token.cs, src/Tasks.UnitTests/ResolveComReference_Tests.cs, src/Tasks/BootstrapperUtil/Product.cs, src/Tasks/FormatVersion.cs, src/Tasks/GenerateApplicationManifest.cs, src/Tasks/GenerateManifestBase.cs, src/Tasks/StrongNameUtils.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1136.md
=> SA1136 place each enum value on its own line

eng/Common.globalconfig, src/MSBuildTaskHost/Concurrent/ConcurrentQueue.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1134.md
=> SA1134 Each attribute should be placed on its own line of code

documentation/specs/event-source.md, src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs, src/Framework/MSBuildEventSource.cs, src/Framework/PublicAPI/net/PublicAPI.Unshipped.txt, src/Framework/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Framework/Sdk/SdkLogger.cs
This reverts commit 73ee6c0b41ebfa80f5dd54560a90566a8efb20cb.
As of #7139 Microsoft-Build events can no longer be reported (i.e. they don't show in PerfView) because the ETW manifest builder is failing due to Object[] being an unsupported type. This change is a straight revert of the PR that introduced the regression.
The bug makes it harder to diagnose MSBuild issues internally and externally. Note that Microsoft-Build ETW events are recorded by the VS Feedback tool, for example.
Yes, introduced in #7139 on Dec 22nd 2021.
Very low.
No.
No.
=> Revert "Add more SdkResolverService events and allow SdkResolvers to log events (#7139)"

src/Tasks.UnitTests/Hash_Tests.cs, src/Tasks/Hash.cs
Fixes #7086
`Hash.Execute()` allocates a string which gets to the large object heap. This could be avoided without changing the resulting hash function.
Hash function is rewritten.
Unit tests & manual testing
=> Remove unnecessary allocations in Hash task.

eng/Common.globalconfig, src/Build/Construction/Solution/ProjectInSolution.cs, src/Build/Definition/ProjectItem.cs, src/Build/Evaluation/LazyItemEvaluator.OrderedItemDataCollection.cs, src/Build/Instance/ProjectInstance.cs, src/Build/Logging/BaseConsoleLogger.cs, src/Framework/ReuseableStringBuilder.cs, src/Tasks/AssemblyDependency/Reference.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/GenerateResource.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1504.md
=> SA1504 All accessors should be single-line or multi-line

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes [AB#1461672](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1461672) / https://developercommunity.visualstudio.com/t/Unable-to-publish-via-ClickOnce-for-Unpa/1631852
Apps referencing Windows App SDK packages fail ClickOnce publish due to a copy error for apphost.exe.
Apps with this package reference invoke targets that try to copy files in the ContentWithTargetPath to the output folder. ClickOnce targets add apphost.exe to ContentWithTargetPath w/o the TargetPath metadata. This results in the copy error.
Add TargetPath metadata to the item before it gets added to ContentWithTargetPath group.
CTI team has run test cases for clickonce publish across all supported configuration
=> Add targetpath metadata to file getting added to ContentWithTargetPath group

eng/Common.globalconfig, src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs, src/Build/Utilities/EngineFileUtilities.cs, src/MSBuild/CommandLineSwitchException.cs, src/MSBuild/InitializationException.cs, src/StringTools/StringTools.cs, src/Tasks.UnitTests/XslTransformation_Tests.cs
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1509.md
=> SA1509 Opening braces should not be preceded by blank line

src/Utilities.UnitTests/ProcessExtensions_Tests.cs
Fixes #7255
KillTree test starts a powershell process during execution. When the default terminal is set to Windows Terminal, the WT window is still opened after test execution.
Test now starts windowless process.
The KillTree test is still passing.
=> Start windowless process for the KillTree test

Directory.Build.targets, documentation/consuming-nuget-package.md, src/Build/README.md, src/Deprecated/Conversion/README.md, src/Deprecated/Engine/README.md, src/Framework/README.md, src/MSBuild/README.md, src/StringTools/README.md, src/Tasks/README.md, src/Utilities/README.md
This should improve understandablity of our packages.
Fixes #6991.
Details on the format:
* https://docs.microsoft.com/nuget/nuget-org/package-readme-on-nuget-org
* https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
=> Add NuGet package READMEs

src/Framework/StringBuilderCache.cs
The doc comments were hidden in an ancient format.
=> Doc-commentify StringBuilderCache

src/Framework/ReuseableStringBuilder.cs, src/Shared/EventArgsFormatting.cs
While I was editing in this area I noticed that the calling pattern around StringBuilders in FormatEventMessage looked allocatey.
Instead of creating two throwaway StringBuilders to format a single message,
1. Make a guess at the initial size based on the maximum format string,
2. Use a StringBuilder from StringBuilderCache, and
3. Reuse the builder between "construct format string" and "get final message"
=> Reuse StringBuilders in EventArgsFormatting

src/Framework/MSBuildEventSource.cs
These have specific meanings but they weren't written down in an easy form so it was easy to misuse them especially via copy/paste. Now they'll show up in hover.
=> Explain perf keywords

src/Tasks/ManifestUtil/ComImporter.cs
Fixes #
https://developercommunity.visualstudio.com/t/MSB3179:-Problem-isolating-COM-reference/1571958
Customer projects that reference a x86 COM binary cannot publish their project using ClickOnce provider.
Yes (Dev16 -> Dev17)
ClickOnce's msbuild task to generate the application manifest has code that imports COM Component by reading their registration data from the registry. In this scenario, the COM reference is an x86 binary that is registered under HKCR\WOW6432Node\Clsid node. In dev17 with msbuild being an x64  process, the code is not reading from the WOW6432Node.
The fix is to update the code that's reads COM registration data to look under the WOW6432 node of HKCR as well.
Verifed with customer provided repro project that x86 COM component is imported fine after the fix.
CTI …
=> Fix import of x86 COM Component in ClickOnce Publish

src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs, src/Utilities/ToolLocationHelper.cs
Fixes #7292
ProcessorArchitecture unit tests needed to be updated to account for arm64 machines.
Accounts for arm64 as a valid processor architecture
Tested locally on an m1 mac.
=> Account for ARM64 in ProcessorArchitecture Tests

MSBuild.sln, README.md, documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md, global.json
This will be required to target .NET 6.0+ using newer SDKs and it's easier to just move.
Also disabled the Arcade default behavior to download a copy of .NET Framework MSBuild if it's not installed; instead we'll require an installed Visual Studio 17.0+.
=> Require VS 2022 to build this repo

src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs, src/MSBuild/XMake.cs
Fixes #7216 
See #7216 
- Logging commandLine arguments passed into Execute method as oppose to Environment.CommandLine
- ren before and after and compared its binary log in viewer.
- I reviewed other places which uses  Environment.CommandLine and it seems to be OK with respect to `dotnet build` use case.
=> MSBuild command line arguments aren't logged in dotnet build

global.json
This is a workaround for https://github.com/dotnet/arcade/issues/8393
This reverts the version of the Arcade SDK to work around a bug in the merged manifest generation that is merging the manifests with incorrect values, which breaks the publishing infrastructure.
Reverted to the last version of the Arcade SDK that doesn't have the problematic changes.
Ran this test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5673773&view=results with this exact change, and then published that build to the testing channel: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5673847&view=results. The publishing build created the isolated feeds that were expected.
=> Revert to arcade without merged manifest bug

global.json
#7304 broke main builds as xcopy-msbuild appears to be required for signing validation.
Reverted the problematic part of #7304.
Build.
=> Revert "xcopy-msbuild": "none"

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
Occasionally, someone will have a misconfiguration that causes MSBuild
worker nodes to crash immediately or shortly after launch (before
establishing communication with the node that created them).
This can be really hard to diagnose, because it's not obvious that it's
happening--failure to connect to a process is nonfatal and can happen
if a user is building with two disconnected `-m` invocations. But
repeated failure is bad and if the node _never_ connects, that's a
problem.
Add comm-trace information about process lifetime. I wanted to include
the exit code too but couldn't because on Windows we call CreateProcess
instead of Process.Start.
=> Improved error message when created node crashes

src/Build.OM.UnitTests/Definition/ProjectCollection_Tests.cs, src/Build.UnitTests/Construction/ElementLocation_Tests.cs, src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build.UnitTests/Evaluation/ProjectStringCache_Tests.cs, src/Build/BackEnd/BuildManager/BuildParameters.cs, src/Build/BackEnd/Components/Communications/TranslatorExtensions.cs, src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs, src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs, src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/Build/ElementLocation/XmlDocumentWithLocation.cs, src/Build/Instance/ProjectInstance.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Build/Resources/Constants.cs, src/Deprecated/Engine/Engine/Engine.cs, src/Deprecated/Engine/Engine/Project.cs, src/Deprecated/Engine/Engine/TargetCollection.cs, src/Deprecated/Engine/Items/BuildItem.cs, src/Deprecated/Engine/Microsoft.Build.Engine.csproj, src/Directory.BeforeCommon.targets, src/Framework/AssemblyUtilities.cs, src/Framework/NativeMethods.cs, src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs, src/MSBuild/CommandLineSwitches.cs, src/MSBuild/XMake.cs, src/Shared/BuildEventFileInfo.cs, src/Shared/EnvironmentUtilities.cs, src/Shared/ExceptionHandling.cs, src/Shared/LogMessagePacketBase.cs, src/Shared/TaskLoader.cs
Enable many `FEATURE_*` flags that were disabled in the initial port to .NET Core but are now unifiable because the APIs were added in .NET Core 2.0.
Fixes #7329 and many more like it.
=> Enable feature flags for things enabled in .NET Core 2.0

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd, src/Tasks/ManifestUtil/SecurityUtil.cs, src/Tasks/ManifestUtil/mansign2.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/PublicAPI/net/PublicAPI.Unshipped.txt, src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Tasks/SignFile.cs
… timestamping fails during ClickOnce manifest signing
Fixes # 7164
ClickOnce manifest signing will obtain a RFC3161 timestamp if a timestamp server URL has been specified. If the RFC3161 timestamping fails, the code falls back to calling a legacy non-RFC3161 timestamp API. Customers do not have any option to disable this behavior if they want to enforce RFC3161 timestamping.
Add a new property DisallowMansignTimestampFallback that will not allow the fallback behavior. The default is false which means fallback will be allowed. If the property is set to true either through the csproj or msbuild CLI, the fallback API will not be called and instead the build will throw an error when RFC3161 timestamping fails.
Ongoing.
=> Provide option to fail ClickOnce publish if RFC3161 timestamping fails.

src/Build/Graph/GraphBuilder.cs, src/Build/Graph/ProjectGraphEntryPoint.cs
Fixes #5898
Executing projects changes the cwd, which makes relative paths behave unexpectedly. So when an implicit restore happens (`/restore`), then the cwd is different than what it was originally. For non-graph builds, this isn't a problem as the `BuildRequestData` gets the full path of the project file before the implicit restore, so there effectively are no relative paths to deal with. However, this was not the case for `GraphBuildRequestData`, so doing a build with `/retore`, `/graph`, and a relative path to a project file was erroring incorrectly.
The `ProjectGraphEntryPoint` constructor will now get the full path of the project file, similar to what `BuildRequestData` does today.
I also followed all uses of `ProjectGraphEntryPoint.ProjectFile` and removed any normalization since …
=> Fix handling of relative paths when using graph builds with implicit restore

src/Tasks/Microsoft.Build.Tasks.csproj
Changes package reference to the System.Net.Http to an assembly reference for .NETFramework.
Reverts part of #6879.
=> Remove unnecessary package dependency on System.Net.Http package.

src/Build/BackEnd/BuildManager/BuildManager.cs
This keeps a build with all distribution-aware loggers from vetoing the
new behavior because a logger (NullLogger) is attached that doesn't indicate
that it can handle it. It trivially can, so it should!
Related to #1222.
=> Opt into IncludeEvaluationPropertiesAndItems in NullLogger

src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs, src/Build/Evaluation/LazyItemEvaluator.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Fixes #6460
Errors from Evaluate could appear as just BUILD FAILED 0 Warnings 0 Errors, which is no good. This makes the errors appear in a fairly generic way.
It also fixes the motivating issue.
Logs an error including a full stack and the original error message with errors in Evaluate.
Fixes a bug with GetFullPath being passed an unescaped string instead of an escaped string.
Changes the error formatting such that only the first line gets reformatted.
Tried it out before and after the changes. It now prints:
```
Build FAILED.
"C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj" (default target) (1) ->
"C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj" (Inner target) (1:2) ->
MSBUILD : error : "This is an unhandled exception in MSBuild -- PLEASE FILE AN ISSUE AT …
```
=> Better evaluator errors Fixes #6460

src/Build.UnitTests/ConsoleLogger_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs, src/MSBuild.UnitTests/XMake_Tests.cs, src/MSBuild/XMake.cs, src/Shared/EventArgsFormatting.cs
Unblocks https://github.com/dotnet/sdk/pull/12030 by fixing problems that arose when combining `dotnet build` with `ProjectConfigurationDescription`.
Part of #1222.
I recommend reviewing commit-by-commit.
=> Support ProjectConfigurationDescription when SDK loggers are attached

eng/Versions.props, src/Shared/CoreCLRAssemblyLoader.cs, src/Shared/MSBuildLoadContext.cs
This reverts commit 3bb10b76c5a345b30d6bf55facacbbce47446358.
Fixes https://github.com/dotnet/sdk/issues/23498
Work item (Internal use): 
The linked commit changed MSBuild Assembly resolution to be in line with .NET Assembly resolution, but this had adverse impact on an SDK scenario that led to the wrong version of certain pre-packaged DLLs being loaded compared to previous versions of the runtime. In this case, System.Security.Cryptography.ProtectedData triggered the incorrect loading behavior.
Restore operations that use NuGet feeds with encrypted passwords began failing. There are workarounds like saving the passwords in cleartext, but this is not an ideal workaround.
This regressed behavior from 6.0.1xx and earlier series SDKs.
We still need to work with impacted customers to verify …
=> Revert "Loosen version comparisons in loading assemblies (#7042)"

.vsts-dotnet.yml
The official build started failing, but appears to be happy with this GUID-less invocation (of what should be the same task):
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5796249
=> Update official build references to tasks and pools that recently started failing

src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
Fixes https://github.com/dotnet/msbuild/issues/7137
The MainNodeSdkResolverService process incoming requests from out-of-proc nodes to handle SDK resolution.  The main node has a queue of all incoming packets that are processed by appropriate handlers.  The MainNodeSdkResolverService currently takes SdkResolverRequests and places them in a queue for processing.  This seems unnecessary to have two queues and two threads draining the queues.
Remove queue and thread that process it in favor of launching a fire-and-forget task that resolves the SDK and sends the response.
Existing tests cover this area
=> Simplify MainNodeSdkResolverService

src/Build/Resources/Constants.cs
Fixes #7428
Provide the 'native' line ending for the current OS in a portable fashion.
- Added one line in Constants.cs to add `System.Environment::NewLine` to `availableStaticMethods`.
- Minor whitespace clean up to adjust the indent of a comment and to remove a blank line in the set of `System.Environment` properties.
Built the bootstrap and tested with the following 'NewlinePropFunc.proj' project file:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<Target Name="Test">
<ItemGroup>
<stuff Include="apple;boat;cat;dog" />
</ItemGroup>
<Message Text="@(stuff, '$([System.Environment]::NewLine)')" />
</Target>
</Project>
```
When the project is run with `/v:n`, the Message task is expected to output one item per line, e.g.:
```
apple
boat
cat
dog
```
(Without the …
=> Fix dotnet/msbuild#7428 Enhancement: Add System.Environment::NewLine as a supported static property

src/Tasks.UnitTests/FormatUrl_Tests.cs, src/Tasks/FormatUrl.cs, src/Tasks/LC.cs, src/Tasks/ManifestUtil/PathUtil.cs, src/Tasks/ResolveComReference.cs
Fixes #6313
The standard task [FormatUrl](https://docs.microsoft.com/en-us/visualstudio/msbuild/formaturl-task) was disabled for .Net Core. 
- Removed the 'TaskRequiresFrameworkFailure' error for .Net Core for the FormatUrl task.
- Added a new unit test class for the FormatUrl class.
When testing with a debug build before making any changes, the debug build would report
```
Called LogErrorFromResources instead of LogErrorWithCodeFromResources, but message 'The task "FormatUrl" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details.' does have an error code 'MSB4803'
```
Two other tasks use the 'TaskRequiresFrameworkFailure' error: LC and ResolveComReference. Both were using …
=> Fixes dotnet / msbuild#6313 FormatUrl

src/Build/Graph/GraphBuilder.cs
Fixes #7475
In #7053 there's a subtle bug which is highly dependent on node ordering (which makes it even repro differently or not at all on different machines...).
Specifically, `traversedReferences` is "reset" every time `GetTransitiveProjectReferencesExcludingSelf` is called. So we can end up in a state where a node is in the `transitiveReferenceCache` but not in `traversedReferences`. In that case, `GetTransitiveProjectReferencesExcludingSelfHelper` will add the cached transitive references to the `traversedReferences` set, but *not* `incompleteReferencesOfDirectlyReferencingNode`, so the referencing node loses these transitive references.
I reworked the `GetTransitiveProjectReferencesExcludingSelf` method to a more straightforward approach. First it checks the cache. Then it creates …
=> Fix missing transitive dependencies

src/Build/Definition/Toolset.cs, src/Build/Evaluation/Evaluator.cs, src/Framework/Traits.cs
We have scenarios in internal build tools where MSBuild evaluation is executed in the parse phase under a .NET 6.0 process, prior the build phase which builds projects using full framework ```msbuild.exe```. As evaluation results in the parse phase must match the build phase for prediction to be accurate, ```MSBuildRuntimeType``` must be set to ```"Full"``` in both cases - so we currently solve this by launching a separate process under full framework which runs evaluation / parsing and serializes results back to the main process.
However, this serialization incurs a significant amount of overhead on large repos. Instead, by having the option of forcing ```MSBuildRuntimeType=Full``` when on ```RUNTIME_TYPE_NETCORE```, we would be able to evaluate these projects in-process for the majority …
=> Allow overriding MSBuildRuntimeType to "Full" on RUNTIME_TYPE_NETCORE

src/MSBuild.UnitTests/XMake_Tests.cs
We already had `_output`, we just weren't passing it in these calls,
making diagnosing failures unreasonably difficult.
=> Capture output in XMake_Tests

src/Framework/NativeMethods.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks.UnitTests/Copy_Tests.cs
Fixes #6376
We had disabled these before we had the more convenient SupportedOSPlatformGuard. Now we can use that instead.
Replaced #pragma warning disable CA1416s with SupportedOSPlatform("windows")
Built
=> Stop disabling CA1416 Fixes #6376

src/Build.OM.UnitTests/Construction/ProjectItemGroupElement_tests.cs, src/Build/Construction/ProjectElementContainer.cs
Fixes https://github.com/dotnet/msbuild/issues/7435
Context
When "DeepCopy"ing ProjectItemGroupElements, we copied attributes but not children, which meant we would lose them if present.
Changes Made
Recursively copy children as well.
Testing
Ran (and passed) rainersigwald's unit test.
=> Make DeepCopyFrom (for ProjectElementContainers) copy all descendants instead of just the direct children

src/Utilities.UnitTests/CommandLineBuilder_Tests.cs, src/Utilities/CommandLineBuilder.cs
Fixes https://github.com/dotnet/msbuild/issues/7154
The CSC compiler does not unquote disabled warnings eg `/nowarn:1701,1702,1705,NETSDK1138,CS8969,"IDE0161",NU5105,RS0041,CA1416,1701,1702` will not disable `IDE0161`. MSBuild has logic to quote strings that it believes must be quoted to be passed on a command line. It has a bug causing it to do this over eagerly in the tr-TR culture, which exposes this compiler limitation.
To fix this Regex should use RegexOptions.CultureInvariant unless they are specifically intended to have culture specific  behavior. In this case the purpose is simply to determine whether a string needs to be quoted on a command line. An example is "SYSLIB0003". The `I` does not match `[a-z]` case insensitively in tr-TR culture because lower casing `I` does not …
=> Fix regex culture bug

eng/BootStrapMSBuild.targets
Always creates a bootstrap MSBuild when building from the command line.
Added /p:CreateBootstrap=true in two places
Tested `build.cmd` on windows, and it made a bootstrap version.
=> Always make bootstrap

eng/Packages.props, eng/dependabot/Packages.props, src/Directory.Build.targets, src/MSBuild/MSBuild.csproj, src/StringTools.Benchmark/StringTools.Benchmark.csproj
An old version of these packages were getting pulled in transitively by
netstandard packages, and causing Component Governance alerts.
Fortunately, the packages aren't really used so we can just update them.
=> Bump refs to System packages

src/Build/Resources/Constants.cs
Fixes #7504
Add static properties and methods of DateTimeOffset.
Added one line in Constants.cs to add `DateTimeOffset` to `availableStaticMethods`.
Built the bootstrap and tested with the following 'DateTimeOffsetPropFunc.proj' project file:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<Target Name="Test">
<Today>$([System.DateTime]::Now)</Today>
<Today2>$([System.DateTimeOffset]::Now)</Today2>
<Message Text="DateTime:       $(Today)"/>
<Message Text="DateTimeOffset: $(Today2)"/>
</Target>
</Project>
```
When the project is run with /v:n, the values for DateTime and DateTimeOffset are displayed. The DateTimeOffset value will include the offset from UTC.
=> Fix dotnet/msbuild#7504 DateTimeOffset property function

eng/Packages.props, eng/dependabot/Packages.props
This will help us keep on the latest version of these dependencies.
They're not used in the .NET Framework build, so we should be able
to safely put them in the managed-by-automation category.
=> Manage .NET6-only dependencies with Dependabot

src/Build.UnitTests/BuildEnvironmentHelper_Tests.cs, src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs, src/Shared/BuildEnvironmentHelper.cs, src/Shared/CommunicationsUtilities.cs, src/Shared/XMakeAttributes.cs
Also improves the detection logic for MSBuild understanding how it was launched and where it exists.
=> Expand usingtask customization

src/Framework/ChangeWaves.cs, src/Shared/MSBuildLoadContext.cs, src/Shared/UnitTests/TypeLoader_Tests.cs, src/Tasks/CombineTargetFrameworkInfoProperties.cs
Fixes https://github.com/dotnet/msbuild/issues/4081 and https://github.com/dotnet/msbuild/issues/1887; progress towards https://github.com/dotnet/msbuild/issues/5037
Context
MSBuild doesn't currently respect .deps.json files for plugins (tasks). This can lead to incorrect versions of assemblies being found as finding the AnyCPU version of an assembly instead of the windows-specific version.
Changes Made
Use AssemblyDependencyResolver as a second pass (after looking for "well-known assemblies") to automatically use the deps.json file to find the right assembly.
Testing
Verified that for a task assembly with a rid-specific dependency, it finds the rid-specific dependency as specified by the deps.json file. Also verified that it can find native assemblies and that the issue that inspired …
=> Respect deps.json

eng/Packages.props, eng/Versions.props
Related to https://github.com/dotnet/source-build/issues/2835
Update Packages.props to utilizes properties defined in versions.props which get overridden by the built versions in source-build.  This eliminates prebuilts.  Before these changes, references to 6.0.0 were being added instead of the current versions e.g. System.Text.Json,6.0.4.  
I applied the same change to all 6.0.0 references.  This is only a problem for System.Text.Json but will be once the other packages are serviced for 6.0.
Ran a complete source-build to validate the prebuilts were removed.
=> Use Versions.props to eliminate source-build prebuilts

documentation/specs/low-priority-switch.md, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/Communications/INodeManager.cs, src/Build/BackEnd/Components/Communications/INodeProvider.cs, src/Build/BackEnd/Components/Communications/NodeEndpointOutOfProc.cs, src/Build/BackEnd/Components/Communications/NodeManager.cs, src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs, src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs, src/Build/BackEnd/Node/OutOfProcNode.cs, src/MSBuild/XMake.cs, src/MSBuildTaskHost/OutOfProcTaskHost.cs
Thanks @svetkereMS for bringing this up, driving, and testing.
This fixes two interconnected issues.
First, if a process starts at normal priority then changes to low priority, it stays at normal priority. That's good for Visual Studio, which should stay at normal priority, but we relied on passing priority from a parent process to children, which is no longer valid. This ensures that we set the priority of a process early enough that we get the desired priority in worker nodes as well.
Second, if we were already connected to normal priority worker nodes, we could keep using them. This "shuts down" (disconnects—they may keep running if nodeReuse is true) worker nodes when the priority changes between build submissions.
One non-issue (therefore not fixed) is connecting to task hosts that …
=> Fix low priority issues

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/Build/Microsoft.Build.csproj, src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj, src/Framework/Microsoft.Build.Framework.csproj, src/MSBuild/MSBuild.csproj, src/MSBuildTaskHost/MSBuildTaskHost.csproj, src/Tasks/Microsoft.Build.Tasks.csproj, src/UnitTests.Shared/Microsoft.Build.UnitTests.Shared.csproj, src/Utilities/Microsoft.Build.Utilities.csproj
With its move to inbox in .NET 6, it is no longer needed in any framework targeted by projects in this repo.
Fixes N/A
dotnet/announcements#190
Removed some Nuget packaage dependencies.
No code was changed.
N/A
=> Remove `Microsoft.Win32.Registry` package dependency.

documentation/wiki/ChangeWaves-Dev.md, documentation/wiki/ChangeWaves.md, src/Build.UnitTests/Scanner_Tests.cs, src/Build/Evaluation/Conditionals/Scanner.cs, src/Build/Evaluation/Evaluator.cs, src/Framework/ChangeWaves.cs, src/Shared/FileMatcher.cs, src/Tasks.UnitTests/AssignTargetPath_Tests.cs, src/Tasks.UnitTests/Exec_Tests.cs, src/Tasks/AssignTargetPath.cs, src/Tasks/Exec.cs
Removes the 16.10 change wave and associated tests and edits documentation.
This is based on the respect deps.json pr to avoid an imminent merge conflict.
=> Remove 16.10 changewave

src/Tasks.UnitTests/Copy_Tests.cs, src/Tasks/Copy.cs, src/Tasks/LockCheck.cs
Improves understandability of build issues like dotnet/sdk#9585. Fixes #7327
=> Enable LockCheck on .NET on Windows

src/Utilities/Microsoft.Build.Utilities.csproj
Used for pinging the registry as part of some windows-specific methods in ToolLocationHelper
Win32 was removed as unnecessary in parallel with introducing a new usage for it in .NET Standard, since RegistryHive and RegistryView are available without the explicit reference in net472 and .NET 6 but not .NET Standard. This adds back the reference if necessary.
Built
=> Put win32 back for .NET Standard

src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/Communications/INodeManager.cs, src/Build/BackEnd/Components/Communications/INodeProvider.cs, src/Build/BackEnd/Components/Communications/NodeManager.cs, src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs, src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs, src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs, src/Build/BackEnd/Components/IBuildComponent.cs, src/Shared/CommunicationsUtilities.cs, src/Tasks/Microsoft.NETFramework.CurrentVersion.props
Fixes #7379
MSBuild builds with Out Of Proc nodes which requires spawning processes.  Each node takes time to spawn and is serial.  This can lead to a slow start on machine with many cores.  
Parallelize Node spawn.
Changed interface in `INodeProvider` to specify number of nodes to be created and let particular implementation of `INodeProvider` decide if it does it concurrently. This way the scope of thread safety is limited and manageable.
I tried to keep current logic as much in tact as possible. For example old logic allowed to call `INodeManager` to spawn multiple in-proc nodes but then it fails anyway. That does not make much sense to me, and if we want to address it please let me know.
Various manual testing including scenarios with TaskHost.
When nodereuse and nodes are still …
=> Parallelize Node Spawning

src/Build.UnitTests/BackEnd/LoggingServiceFactory_Tests.cs, src/Build.UnitTests/BackEnd/LoggingServicesLogMethod_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Components/Logging/LoggingService.cs, src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/Build/Definition/Project.cs, src/Build/Definition/ProjectCollection.cs
Fixes #7364 
[](https://user-images.githubusercontent.com/25249058/152361351-ff5d51a9-5630-4aaf-8178-4597d5bf9773.png)LoggingService.LogComment causes large amounts of contention between unrelated evaluation threads.
image
- Reducing lock statements
- using Interlock.Add as oppose to lock { n+=x; }
- replace `Dictionary` with `ConcurrentDictionary` and remove related `lock`s
- review  `lock`s and remove unnecessary
- Replacing `DataFlow` by `ConcurrentQueue` for event processing
- Fixing unit tests
- local run unit testst
- micro benchmark comparing `DataFlow` by `ConcurrentQueue`
- exp insertion - currently failing on infrastructure - will update
- Compiled Boost.Hana as described in #3577 - no OOM exception
It has surprisingly good perf results. Maybe because I tested it on 24 core …
=> LoggingService log contention

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/Expander.cs, src/Build/Evaluation/IntrinsicFunctions.cs
Fixes #7442
Some odd parameters sometimes need to be passed through MSBuild. This provides a built-in way to avoid escaping nonsense.
Added intrinsic functions encoding or decoding a string to or from base 64.
Added unit test
=> Base64 converter Fixes #7442

.gitignore, MSBuild.lutconfig
Add a `.lutconfig` file to configure Live Unit Testing for the repo.
Changes to `.gitignore` enabled it to be used for LUT's shadow copy; a couple of test assets were failing to copy with the prior rules.
=> Enable Live Unit Testing

src/Build.UnitTests/BackEnd/TaskBuilderTestTask.cs, src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs, src/Shared/BinaryTranslator.cs, src/Shared/ITranslator.cs, src/Shared/TaskParameter.cs, src/Shared/UnitTests/TaskParameter_Tests.cs
Remove uses of TranslateDotNet for types that make sense to pass to/from tasks.
=> Handle value types explicitly in TaskParameter translation

src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Client/MSBuildClientExitResult.cs, src/Build/BackEnd/Client/MSBuildClientExitType.cs, src/Build/BackEnd/Client/MSBuildClientPacketPump.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Build/Microsoft.Build.csproj, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Framework/Traits.cs, src/MSBuild/MSBuild.csproj, src/MSBuild/MSBuildClientApp.cs, src/MSBuild/XMake.cs
Fixes #7374, #7373
Context
MSBuild client is a new code path that is triggered with opt-in env variable. It sends the build request for execution to the MSBuild server node. This approach avoids to do execute targets and tasks into a short-living process from CLI tools like .NET SDK and MSBuild.exe.
Changes Made
This PR implements a new MSBuild client classes able to communicate with MSBuild server node via the named pipe. 
Testing
Manually tested. Automatic tests will be added in another PR.
=> [WIP-FEATURE] MSBuild client

src/Build/Instance/TaskRegistry.cs
Fixes #
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1448821
Root cause:
- csproj requires lots of project properties, for this reason evaluation of project is started because project is considered dirty
- however this evaluation throws which causes this project to stay dirty
- above exception is somehow ignored by csproj and it proceeds with requesting more project properties each of those starting new evaluation in UI thread causing huge degradation in VS responsiveness
Why it throws?
- when MSBuild interprets \src\ConfigData\BuildTargets\Microsoft.DevDiv.BuildDiagCommon.targets line #119 the type "Microsoft.Build.Framework.ITaskItem[]" is resolved from another already loaded version of Microsoft.Build.Framework assembly.
this causes type check mismatch and that ParameterType …
=> Workaround mismatch type resolving

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
VerifyDTDProcessingIsDisabled2 fails fairly regularly. This is an attempt to make that not true.
Made the thread running HttpServerThread finish
I ran CI build 3x, and it passed all three times...which ultimately means very little. On the other hand, this doesn't touch production code, so it's pretty safe.
=> Maybe fix flaky test

scripts/Deploy-MSBuild.ps1
With Deploy-MSBuild.ps1
Only works if you're deploying to a folder that looks like `*dotnet*sdk*`
Note that this is a bit hacky, but I think that's fine for a script that is mostly used by us.
I tried deploying to a folder that looked like ...\dotnet\sdk\folder, and it put the Core assemblies in rather than Framework as desired.
=> Auto-detect that we need Core

scripts/Deploy-MSBuild.ps1
`else if` is a thing in powershell but only since about 3 months ago...which means that if you just updated powershell, the PR is unnecessary. This just means you don't have to be on the very latest version for it to work.
I used it
=> No else if in powershell

documentation/wiki/ChangeWaves.md, src/Tasks.UnitTests/GetCompatiblePlatform_Tests.cs, src/Tasks/GetCompatiblePlatform.cs, src/Tasks/Microsoft.Common.CrossTargeting.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Reduces the number of evaluations in platform-negotiated builds.
A (Platform=x86) -> B (Platforms=x64;x86, Platform=x86) (A, a project built as x86 references B, a project that _can_ build as x86 or x64, but will default to x86 if built in isolation)
Prior to this change, platform negotiation would build B with `SetPlatform=Platform=x86`, causing a new evaluation. This can be avoided because it would have built as `x86` with or without that global property being passed.
`GetTargetFrameworks` target now also returns the `Platform` property from the target. During platform negotiation, if the referenced project's platform matches the current project's platform, we now decide to build that project **without** passing a global `Platform` property. This prevents a new evaluation and will …
=> Platform Negotiation: Platform is considered a referenced project's DEFAULT platform

src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs, src/Build/Utilities/EngineFileUtilities.cs, src/Shared/Resources/Strings.shared.resx, src/Shared/Resources/xlf/Strings.shared.cs.xlf, src/Shared/Resources/xlf/Strings.shared.de.xlf, src/Shared/Resources/xlf/Strings.shared.es.xlf, src/Shared/Resources/xlf/Strings.shared.fr.xlf, src/Shared/Resources/xlf/Strings.shared.it.xlf, src/Shared/Resources/xlf/Strings.shared.ja.xlf, src/Shared/Resources/xlf/Strings.shared.ko.xlf, src/Shared/Resources/xlf/Strings.shared.pl.xlf, src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf, src/Shared/Resources/xlf/Strings.shared.ru.xlf, src/Shared/Resources/xlf/Strings.shared.tr.xlf, src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf, src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf, src/Shared/UnitTests/ObjectModelHelpers.cs, src/Tasks.UnitTests/CreateItem_Tests.cs, src/Tasks/CreateItem.cs
Fixes #7029 by associating a file location string with the WildcardResultsInDriveEnumeration resource name.
For https://github.com/dotnet/project-system/blob/main/build/import/Workarounds.targets#L8, it was difficult to detect the location at which the drive enumerating wildcard pattern was occurring even though a warning was logged, since 1) there was no location string added to the warning, and 2) the Exclude rather than the Remove element was shown in the warning. To resolve 1), it would be better to associate the location string with the `WildcardResultsInDriveEnumeration` resource name.
Added location string to the `WildcardResultsInDriveEnumeration` resource name in order to view the location for drive enumerating wildcard warnings and errors.
Modified ProjectItem, ObjectModelHelper …
=> Add location string to drive enumerating wildcard warning

src/Tasks.UnitTests/RemoveDir_Tests.cs, src/Tasks/RemoveDir.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Fixes https://github.com/dotnet/msbuild/issues/7563
Passing in an empty directory to the `RemoveDir` task causes the C drive to be wiped (!).
Log a warning and continue on empty itemspecs.
👀
=> RemoveDir: Ignore Empty Directories

documentation/specs/event-source.md, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Client/MSBuildClientPacketPump.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Framework/MSBuildEventSource.cs
Progress on #7496
Added some traces and an ETW trace for build time.
None
=> Server instrumentation

eng/Packages.props, eng/Versions.props, src/MSBuild/app.amd64.config, src/MSBuild/app.config
This is required in coordination with some internal VS repo changes.
=> Update some package references to 6.0 versions

src/Tasks/System.Resources.Extensions.pkgdef
To match the version we're shipping as of b362620217.
Fixes the perf DDRIT regression observed in VS insertion PR https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/365606.
=> Update System.Resources.Extensions pkgdef version

src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Build/BackEnd/Node/ServerNodeBuildCancel.cs, src/Build/Microsoft.Build.csproj, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/MSBuild/XMake.cs, src/Shared/INodePacket.cs
PR to the feature branch. It enables cancellation of the running build.
=> Added cancelation feature

documentation/wiki/ChangeWaves.md, src/Tasks/CombineTargetFrameworkInfoProperties.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets
This caused a regression in scenarios using Visual Studio 17.3 previews
with `global.json` files pointing to old .NET SDKs.
This reverts commit fe4fde95dee67b8925ff9b22a3d157d1c02e1d7b.
Conflicts:
src/Framework/ChangeWaves.cs
src/Tasks/CombineTargetFrameworkInfoProperties.cs
Fixes [AB#1534809](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1534809).
=> Restore CombineTargetFrameworkInfoProperties opt-in

src/Build/BackEnd/Client/MSBuildClient.cs, src/Framework/NativeMethods.cs
When building with the MSBuild server, you could sometimes see VT100 control character sequences rather than interpreting them as desired. This fixes that.
Tell the console to expect VT100.
Built before and after; it displayed properly with this change.
=> Fix control sequence emission

.vsts-dotnet-ci.yml, .vsts-dotnet.yml, eng/Versions.props, global.json, src/Shared/AssemblyNameExtension.cs
It throws on .NET 6 and wasn't helpful before anyway:
(from https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.keypair?view=net-5.0#remarks):
> When the runtime loads an assembly, it does not set the KeyPair property. The getter for the property is only useful if the user set the property before using the AssemblyName object to create a dynamic assembly, and subsequently wants to retrieve the key pair.
Fixes https://github.com/dotnet/msbuild/issues/7662
Work item (Internal use):
=> Avoid AssemblyName.KeyPair on .NET

.vsts-dotnet-ci.yml, .vsts-dotnet.yml, eng/Version.Details.xml, eng/Versions.props, eng/common/templates/post-build/post-build.yml, global.json, src/Shared/AssemblyNameExtension.cs
- Update dependencies from https://github.com/dotnet/arcade build 20220309.5
- Update dependencies from https://github.com/dotnet/arcade build 20220526.2
- Bump CLI version to match global.json
- Bump NuGet version to match
- Avoid AssemblyName.KeyPair on .NET (#7660)
Fixes #
Work item (Internal use):
=> backport keypair elision 16.11

src/Build/Definition/ProjectCollection.cs, src/Build/Evaluation/ProjectRootElementCache.cs, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/MSBuild/XMake.cs
Fixes #7639
Memory leak has been detected when MSBuild server runs many sessions.
- Reusing `BuildManager.DefaultBuildManager` by not disposing it.
- Reusing `ProjectRootElementCache` between MSBuild server sessions.
- Do not clear `ProjectRootElementCache` before build.
Manual tests. Manual memory consumption analyze.
When I run simple console.csproj build in loop this is how used memory looked like:
Before:
After:
Changes are isolated to Server mode only.
`XmlDocumentWithLocation.s_globalStringCache` roots unbounded `ProjectStringCache._documents` which is not cleared at the end of build but at the start of build indirectly through `ProjectRootElementCache` callbacks, so if `ProjectRootElementCache` is not reused, it is never cleared.
=> Solving memory leak by reusing BuildManager and ProjectRoolElementCache

src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs
Fixes [AB#1540178](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1540178)
When SDK resolver throw, like described here https://github.com/dotnet/msbuild/pull/2964, we need to make sure we gracefully recover from it as oppose to throw nullrefex.
Ensure not null `SdkResult` is passed into `SendData`
Manual
Since this is old bug, introduced in 2018 by https://github.com/dotnet/msbuild/commit/b57bd10b51245b980f5e5ad16773ccc40cc9d1a5#diff-b37b42cd03a0c209c8297ced3d7e23c8afa0b6f8ff900b115e424c1506a761dbR168 
there is huge chance it is not root cause as SDK resolver is not supposed to be throwing. However, this fix allows proper Build failure which hopefully will be reported by dogfooding channels if it is indeed a real bug.
=> Properly recover from SDK resolver exception.

eng/Packages.props, src/MSBuild/app.amd64.config, src/MSBuild/app.config
Fixes RPS issue
Need exp/ testing
=> Update system.memory to 4.0.1.2 & 4.5.5

src/Tasks/Copy.cs
Fixes #7088
MSBuild Error: Failed posting a file copy to an ActionBlock. Should not happen with block at max int capacity
Added break from loop if cancellation was requested.
Unit
=> CopyParallel - break from loop if cancellation was requested

src/Build.UnitTests/BackEnd/RedirectConsoleWriter_Tests.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Client/MSBuildClientExitResult.cs, src/Build/BackEnd/Client/MSBuildClientExitType.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/MSBuild/MSBuildClientApp.cs, src/MSBuild/XMake.cs
=> Moving some public types to Experimental namespace

src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs, src/Build/BackEnd/Shared/ConfigurationMetadata.cs, src/Build/Graph/GraphBuilder.cs, src/Build/Graph/ProjectInterpretation.cs
Fixes #
This fixes an issue where if two projects each building a separate platform reference the same project and that project resolves to the same platform in both cases the project graph would have two separate nodes to that that references project.
Example
proj a (x86) -> projb (anycpu)
projc(x64) -> projb (anycpu)
This would output a projectgraph with the following nodes
proj a (x86)
projb (anycpu)
projb (anycpu)
projc(x64)
Correct behavior would be 
proj a (x86)
projb (anycpu)
projc(x64)
I added in a unit test to test for this scenario. 
This way of doing the set platform negotiation is actually much closer to how it is done during build which is good as project graph is meant to mimic build as much as possible
=> Cleaning up msbuild static graph setplatform negotiation logic

src/Tasks.UnitTests/GetInstalledSDKLocations_Tests.cs, src/Tasks.UnitTests/GetSDKReference_Tests.cs, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks.UnitTests/ResolveSDKReference_Tests.cs, src/Tasks/GetInstalledSDKLocations.cs, src/Tasks/GetSDKReferenceFiles.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Tasks/ResolveSDKReference.cs
Build some tasks for .NET 6 that were previously .NET Framework only (but are really Windows-only, and should work fine in `dotnet build`).
Fixes #7452
=> Enable tasks require for building WinUI projects in dotnet build

src/MSBuild/MSBuild.csproj
Do not expose dependencies that we took only to avoid component-governance alerts caused by restoring (but not using) stale packages.
These were added in #7538, but as pointed out in comments on https://github.com/dotnet/msbuild/commit/20cdf6ff1f617fc6d486c170dff95df0300676e3, that had visible effects on our package consumers, even though it shouldn't have.
I have not yet been able to apply all of the changes desired there (each has knock-on effects), but we can easily avoid the impact on our packages via `PrivateAssets`.
Fixes #7651.
=> Hide new internal dependencies

eng/dependabot/Packages.props, src/Directory.Build.targets
We don't depend on Newtonsoft.Json, but a version of is transitively required by Microsoft.NET.Test.Sdk, which references an old version that is flagged by compponent governance alerts as vulnerable to https://github.com/advisories/GHSA-5crp-9r3c-p9vr.
Fixes https://dev.azure.com/devdiv/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/7087180?typeId=6797870.
=> Update Newtonsoft.Json in test projects

.vsts-dotnet.yml
This task had a specific old default version that had a reference to Newtonsoft.Json 9.0.1, but accepts "no version" as "use latest", so if we explicitly specify . . . nothing . . . it should resolve a component governance alert.
=> Unset bootstrapperCoreVersion in BuildVSBootstrapper

global.json
Reverts dotnet/msbuild#7724, which caused an internal official build break.
=> Revert "Update to .NET SDK 6.0.301"

src/Build.UnitTests/BinaryLogger_Tests.cs, src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs, src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs, src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Logging/BaseConsoleLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs, src/Build/Logging/SerialConsoleLogger.cs, src/Framework/Traits.cs, src/MSBuild/XMake.cs, src/Utilities/MuxLogger.cs
MSBuild has a command-line switch that tells it to output all environment variables. C++ used that fairly regularly. This PR automatically opts out of the environment variable logging change in #7484 for the duration of the one build.
Made the Trait settable via environment variable or with the file logger parameter. Since the parameter needs to be applied first, this means the Trait has to be set after the start of the build, so it is no longer read-only. In tests, Traits.Instance is reset every time a variable is read, so setting it at the start of the test does not work. For that reason, I had to make it a static variable on Traits instead of Traits.Instance.
Of importance, the Trait is reset (to the environment variable's value) at logger shutdown for any BaseConsoleLogger. There is …
=> Maybe fix cpp

src/Build/BackEnd/Components/Logging/LoggingService.cs
The change to logging environment variables (#7484) included essentially switching an if (condition) throw; to a VerifyThrow call. The VerifyThrow call creates the string that would be used in the throw eagerly, which is bad for a hot path like this.
=> Reduce allocations in routing build events

src/StringTools/StringTools.csproj
The StringTools assembly is new and was initially configured with a hardcoded
version that didn't increase over time, but this caused confusing publish-time
errors because final GA MSBuild builds produce 1.0.0 StringTools packages,
even though some prior GA build did that and published it for the first time.
Fixes #7562.
=> Version StringTools package with MSBuild

src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr, src/Package/MSBuild.VSSetup/files.swr
Since there is no code to JIT in these assemblies, specifying that
they should be ngened was just a waste of install time.
Fixes [AB#1541728](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1541728).
=> Stop ngen for resource assemblies

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes [AB#1555818](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1555818)
Installation of ClickOnce app as a Single-File with an Application Icon project property set fails to install.
Include _DeploymentManifestIconFile itemgroup to _ClickOnceFiles itemgroup in Single-File mode.
Verified publish and installation of all ClickOnce configurations (FDD and SC) with WPF and Forms app.
=> Fix installation error for ClickOnce SF apps that have an application icon set

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
The correct property name is singular, not plural.
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022
=> Fix property name for production of reference assemblies

src/Shared/FileUtilities.cs
Fixes #7752
When using MSBuildDebugEngine, we recommend specifying MSBUILDDEBUGPATH. If you specify somewhere we can't write to, we have fallbacks. However, if you specify somewhere we can write to but doesn't yet exist, we can't write to it yet, so that part returns false, and we go on to the fallbacks. This makes the folder explicitly if we can, making it return true if we can write to a directory, but it doesn't yet exist.
Create folder if needed.
Tested before and after the change, and it worked.
=> Make folder if needed for MSBUILDDEBUGPATH Fixes #7552

src/Framework/BuildEventContext.cs
This is a minor perf improvement to ensure usages of `BuildEventContext.Invalid` get the same instance instead of creating a new one each time. Since `BuildEventContext` is immutable, this should be safe.
=> Make BuildEventContext.Invalid a singleton

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
* PublishAot is new in .NET 7.
* PublishSingleFile no longer extracts things by default since ~.NET 6?
* We don't want "link"/"linker" in public facing docs because "linker" is an established term in computer engineering, and "IL Linker" (the internal tool that does IL Level trimming) is not a linker.
Cc @dotnet/ilc-contrib
=> Add PublishAot to CommonTypes and fix a couple comments

src/Build/BackEnd/Client/MSBuildClient.cs
Reduces allocations in case the tracing is not enabled
=> Reduces allocations in case the tracing is not enabled

src/Shared/TaskLoggingHelper.cs
The XML docs for LogMessageFromText have long referenced the canonical error
format but left it as an exercise to figure out what that was. But we have docs
now!
Fixes MicrosoftDocs/visualstudio-docs#7626
=> Link to new canonical-error doc

eng/dependabot/Packages.props
See https://github.com/dotnet/source-build/issues/2933
- During source-build, set PackageReferences to versions specified by their respective `*Version` properties (like `SystemCodeDomVersion` for example). Source-build will define and import properties for packages that are available during source-build.
- Then, if any of the packages didn't have *Version properties set, set them to the dependabot-managed versions.
- During a non-source-build build, these dependencies should all be set to their dependabot-managed versions, since none of these dependencies have versions properties defined in `eng/Versions.props`.
I tested the msbuild build locally by running `./build.sh` on Linux. I also tested this commit in source-build locally and confirmed that packages in this file no longer report …
=> Use package version properties for dependabot project during source build

src/Tasks/Microsoft.Common.CurrentVersion.targets
During SetPlatform negotiation, a .nativeproj or .vcxproj will have its ProjectConfiguration parsed to dynamically create `Platforms`. This behavior overrides any previously-defined `Platforms`.
Allow per-project opt out of importing Platforms from ProjectConfiguration.
=> Allow Opt-Out When Importing Platforms from ProjectConfiguration

src/Build.UnitTests/BackEnd/AssemblyTaskFactory_Tests.cs, src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs, src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/MSBuildTaskHost/TypeLoader.cs, src/Shared/LoadedType.cs, src/Shared/TypeLoader.cs
Previously checked if any base type was named ITaskItem
A type derived from a MetadataLoadContext does not inherit from any type not derived from the same MetadataLoadContext. To work around that, the previous code checked whether each input passed to a task type can be cast to an ITaskItem by comparing it and its base types to ITaskItem by full name. There may be multiple plausible base types, however. This corrects that by checking if ITaskItem IsAssignableFrom the type, ensuring that a separate "ITaskItem" is passed for MLC and non-MLC contexts.
Customers with custom tasks that take in or return types derived from ITaskItem (or ITaskItem[]) rather than ITaskItem (or ITaskItem[]) itself cannot build.
Yes, in 17.3p3.
I believe it is reasonably low, but I would like @rainersigwald to …
=> Check derivable from ITaskItem directly

src/MSBuild/XMake.cs
When escape hatch `MSBUILDENSURESTDOUTFORTASKPROCESSES` for issue https://github.com/Microsoft/vstest/issues/1503 is enabled, we should not use msbuild server. 
Otherwise, the same reasons described in the issue apply and that break `dotnet test` command.
=> Do not use msbuild server with escape hatch for VSTestTask enabled.

src/Build/Logging/BaseConsoleLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Build/Utilities/Utilities.cs, src/Shared/LogMessagePacketBase.cs
This requires passing an argument via the stack, rather than on a heap allocated closure.
This change was sitting in my workspace for a while, and I'm working through those changes now. It was motivated by allocations I saw in a trace, but I don't have any numbers available offhand.
=> Don't allocate closure objects when enumerating properties

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs, src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs, src/Build.UnitTests/Graph/ParallelWorkSet_Tests.cs, src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/Graph/GraphBuildResult.cs, src/Build/Graph/ParallelWorkSet.cs, src/MSBuild/XMake.cs
Just some cleanup and simplification in the exception handling for graph builds.
Functionally here are the differences:
* `ParallelWorkSet` now throws an aggregate exception containing all exceptions instead of just the first exception that gets thrown.
* `ParallelWorkSet` tasks no longer go away when they throw. They're caught and added to a list used in the point above.
* `BuildManager` now properly logs invalid project errors for *each* invalid project (due to the help of the points above). Previously it was attempting to catch the agg exception which was never thrown and also the way it was in the catch effectively made it unreachable in the first place.
* `GraphBuildResult` now exposes the `CircularDependencyException` via the `Exception` field instead of `Exception` being null while …
=> Simplify exception handling for graph builds

src/Shared/InprocTrackingNativeMethods.cs
Allows users of the filetracker API to successfully call tracker.exe without fail.
Arm64 msbuild processes point to the arm64 filetracker dll now.
Tested locally.
cc @jgoshi
=> Account for FileTrackerA4 in LoadFileTrackerDll

src/StringTools/StringTools.csproj
The project file element `<WarningsAsErrors>` is used to specify a list of warning codes that should be treated as errors. Passing _true_ here has no meaning.
If you're instead trying to say "treat all warnings as errors," the correct syntax is:
```xml
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```
=> Fix incorrect WarningsAsErrors elements

src/Framework/BuildEventArgs.cs, src/Framework/BuildEventContext.cs, src/Framework/BuildFinishedEventArgs.cs, src/Framework/BuildStartedEventArgs.cs, src/Framework/BuildStatusEventArgs.cs, src/Framework/LazyFormattedBuildEventArgs.cs, src/Framework/ProjectEvaluationFinishedEventArgs.cs, src/Framework/ProjectEvaluationStartedEventArgs.cs, src/Framework/ProjectFinishedEventArgs.cs, src/Framework/ProjectStartedEventArgs.cs, src/Shared/BinaryReaderExtensions.cs, src/Shared/BinaryWriterExtensions.cs
While consuming some of these types last week I was tripped up by null values a few times. This commit adds annotations for the types I experienced issues with, to hopefully avoid such problems for others in future.
In general these annotations have no run-time impact. There were a few places I had to add behaviour changes to address warnings once this code was marked `#nullable enable`.
=> Null annotate some build event args types

src/Shared/PlatformNegotiation.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://github.com/dotnet/msbuild/issues/7760
https://github.com/dotnet/msbuild/pull/7511 figured out a better way to prevent over-evaluations when A(Platform=x86) -> B(Platform=x86, Platforms=x64,x86). It allowed setplatform negotiation to check "would project B have built as what A is currently building as if we _didn't tell it anything_?
Unfortunately, there's a bug when passing a global property because `GetTargetFrameworks` passes `Platform` and `Configuration`, despite not needing to. This PR is an attempt at resolving this by no longer passing those properties, as well as undefining them.
Remove additional properties during the `MSBuild` call to `GetTargetFrameworks`.
It's possible we can't fix it this way, and instead we'll need to create **two** msbuild calls. One that's …
=> SetPlatform Negotiation: No global properties during GetTargetFrameworks

src/Directory.BeforeCommon.targets, src/Shared/FileMatcher.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
Fixes-ish [AB#1513887](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1513887)
A symlink in folder A pointing to A will recurse eternally (hang). This fixes that problem in a fairly simple way.
Check if a symlink would take us to a folder above the one we're in before following it.
I'd rather not introduce something that, if broken, just hangs.
=> Prevent symlink cycle

src/Tasks/Microsoft.Common.CurrentVersion.targets
This PR allows certain projects to opt-in to behavior that works around specific blocking scenarios for the VS Build.
The change is backporting [#7692](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fmsbuild%2Fpull%2F7692&data=05%7C01%7CNathan.Mytelka%40microsoft.com%7C43a080312d844a62ef7608da6a8f2d7f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637939460429992612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fuNOkuEspkq3mEeG3fJN1olUklhGHhOLTKSedNgC4FE%3D&reserved=0) from main into 17.3.
Internal team is unable to complete their work without this opt-in fix.
No.
Confirmed by QB
Low, change is opt-in for a new feature that is also opt-in (under a separate flag).
=> Setplatform stop config from overriding platforms

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Build/Graph/GraphBuilder.cs, src/Build/Graph/ProjectGraph.cs, src/Build/Graph/ProjectGraphNode.cs, src/Build/Graph/ProjectInterpretation.cs
Fixes #7694
Today the first project reference wins and the targets from additional project references are ignored. There is a comment saying that behavior is "in accordance with vanilla msbuild behaviour when multiple msbuild tasks call into the same logical project", but that doesn't seem to be the case.
This change changes the `TryAdd` to an `AddOrUpdate` so that multiple sets of targets are considered from multiple project references.
Referenced\Referenced.csproj:
```xml
<TargetFramework>netcoreapp3.1</TargetFramework>
<UnusualOutput>Configuration\Unusual.txt</UnusualOutput>
<Target Name="UnusualThing" Returns="$(UnusualOutput)" />
</Project>
```
Referencing\Referencing.csproj:
```xml …
```
=> [Graph] Fix target list when there are multiple ProjectReferences with different Targets metadata

src/Tasks/Microsoft.Managed.After.targets
Fixes https://github.com/dotnet/sdk/issues/24414
Previously Publish was declaring that it literally only called `GetCopyToPublishDirectoryItems` on its project references, which is clearly incorrect.
This adds the other targets which Publish calls on its project references.
Also fixed the declaration for `Rebuild`'s outer build. All Rebuild's outer build does is dispatch to the inner Clean and Build targets and Rebuild's outer never actually interacts with any ProjectReference. So it needs no `ProjectReferenceTargets` configuration.
=> Fix ProjectReferenceTargets for Publish and Rebuild

src/Build/Construction/Solution/SolutionProjectGenerator.cs, src/Build/Instance/ProjectInstance.cs
Solution metaprojects were not logged just because we created a new ProjectCollection (with no loggers included) just before evaluation them. This fixes that by using the previously created logging service.
Pipes the logging service used for other evaluations through to evaluation for the metaproject.
Without this change:
With this change:
Needed to only log used environment variables, as we were missing cases without this.
=> Enables logging when building metaprojects

src/Shared/ExceptionHandling.cs
This change really doesn't matter, but Directory.CreateDirectory already does nothing if the directory doesn't exist, so no sense pinging memory an extra time.
This'll probably save about one nanosecond if we're already failing. Totally matters.
=> Directory.CreateDirectory already checks if it exists

src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Client/MSBuildClientPacketPump.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/MSBuild.UnitTests/MSBuildServer_Tests.cs, src/Shared/UnitTests/TestEnvironment.cs
Existing CLI command "dotnet build-server shutdown" was not shutting down MSBuild server.
BuildManager.ShutdownAllNodes calls MSBuildClient which connects to Server by namedpipe and send it NodeBuildComplete packet(false) =>shutdown.
Unit testing
=> BuildManager.ShutdownAllNodes shall shut down server as well

src/Build/BackEnd/Client/MSBuildClientPacketPump.cs
Fixes #
https://github.com/dotnet/sdk/issues/26965
named pipe implementation on Linux works slightly different, and can, on `pipestream.Read()`, read only fraction of bytes.
looping until all bytes are read.
Can't repro above issues, even though I could have repro it consistently before those changes.
Shall be service patch rc1?
=> Read packet data in loop

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
The behavior of package assets referenced through a `ProjectReference` annotated with these metadata was as describe, but that wasn't obvious.
=> ProjectReference NuGet assets stuff is transitive

src/Framework/Traits.cs, src/Tasks.UnitTests/AssignCulture_Tests.cs, src/Tasks/CultureInfoCache.cs
Fixes https://github.com/dotnet/msbuild/issues/3897
Haven't tested this locally.
=> Call New GetCultureInfo API When Validating Cultures

src/Tasks/ResolveManifestFiles.cs
VS#1452098
Customer reported this issue with WinForms project with a reference to MS.ReportingServices.ReportViewerControl.Winforms that is failing ClickOnce publish when being migrated from VS 2019 to VS 2022.
The changes made in ClickOnce to support ClickOnce for .NET 5/6 has caused this regression in the ResolveManifestFiles task.
Specifically the referenced package has a localized assembly that is coming in as a reference and the task trips over while trying to figure out the culture of the assembly because it is trying to detect the culture based on the presence of the culture in the path of the reference and in this case, the path does not conform to this format.
https://developercommunity.visualstudio.com/t/Unable-to-compile-Project-from-VS2019-in/1615824
The fix is not to get the …
=> Fix regression in ClickOnce publish in project with MS.ReportingServices.ReportViewerControl.Winforms as a package reference

src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/MSBuild.UnitTests/MSBuildServer_Tests.cs, src/Shared/CommunicationsUtilities.cs, src/UnitTests.Shared/RunnerUtilities.cs
We detected flaky unit tests related to msbuild server shutdown.
Example of failing checks: https://github.com/dotnet/msbuild/pull/7835
Root cause:
When server finish its build it eventually drops namedpipe, open new one with same name and start listen on it. 
If clients is trying to connect to server during this brief time, all kinds of exceptions could happen.
a) Previously named mutex server-is-running was by server dropped after project weas build and re-acquired shortly after. Changes was made so mutex is acquired constantly.
b) Client retries during connection to server, which address all weird race conditions when server recycling named-pipe.
Several `/azp run` s
Can't repro  on Linux and MacOS even though I could before final changes.
Same bug is also possible while connecting to …
=> Fix flaky CanShutdownServerProcess test

eng/Versions.props, src/Shared/BuildEnvironmentHelper.cs
CoreXT is blocked because MSBuild can no longer discover itself when in "standalone" mode and in a non-SDK scenario.
- Injected & ran build.cmd in this repo
- Doesn't matter, it'll flow eventually (this change doesn't affect the SDK)
Low, code change is for non-VS code path and only affects MSBuild's that exist in an `amd64/` or `arm64/` directory, which does not affect the SDK scenario.
Forgind
dfederm
In the non-VS scenario, MSBuild will properly set the "root" folder when it's in the `amd64/` or `arm64/` directory, _before_ trying to find the `amd64`/`arm64` exe's.
=> Help Standalone MSBuild Find Its Family

src/Shared/ConversionUtilities.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Tasks/Microsoft.Common.CrossTargeting.targets, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/Microsoft.Common.tasks, src/Tasks/PublicAPI/net/PublicAPI.Unshipped.txt, src/Tasks/PublicAPI/netstandard/PublicAPI.Unshipped.txt, src/Tasks/SetRidAgnosticValueForProjects.cs
Fixes dotnet/sdk#21677
In .NET 6, if you run a command such as `dotnet build -r win-x64`, you will get the following error:
> C:\Program Files\dotnet\sdk\6.0.100-rtm.21474.29\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1105,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [C:\git\repro\ConsoleTest\ConsoleTest.csproj]
However, if you follow the suggestion and change it to `dotnet build -r win-x64 --self-contained`, then you will likely get an error such as the following if there are any referenced projects:
> C:\Program Files\dotnet\sdk\6.0.100-rc.2.21501.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(150,5): error NETSDK1031: It is not supported to build or publish a …
=> Don't flow self contained command-line option to referenced projects

src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
This fixes a hang in VS caused by `BuildManager.EndBuild` being called on a UI thread in some scenarios. `BuildManager.EndBuild` calls `ProjectCacheService.DisposeAsync().AsTask()`, which uses `await Task.WhenAll(...)`. This simply adds a `.ConfigureAwait(false)` to the `await Task.WhenAll(...)`.
An alternate approach would be to change out `await Task.WhenAll(...)` with `Task.WaitAll(...)`, but I figured it'd be better to use `async/await`.
=> Fix hang in VS due to EndBuild being called on a UI thread

src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs, src/Build/BackEnd/Components/Scheduler/Scheduler.cs, src/Framework/Traits.cs, src/MSBuild/XMake.cs
This is a minor bug fix which ensures the Scheduler always uses the latest value for `BuildParameters.DisableInProcNode` rather than the value provided in the first build.
Note that the Scheduler is an `IBuildComponent` which has the same lifetime as the `BuildManager`. However, `BuildParameters` is per build, so caching a value from `BuildParameters` would be incorrect.
=> Fix for Scheduler using build parameter from previous build

src/Package/MSBuild.VSSetup/files.swr
Fixes #7793
While `MSBuildTaskHost.exe` is compiling by NGEN, StringTools dependency is not found due using default `vsn.exe.config` file.
Added config file for task host to help NGEN find the dependency location.
We will see in the ngen logs :)
=> Added proper config file for task host

documentation/wiki/ChangeWaves-Dev.md, documentation/wiki/ChangeWaves.md, src/Build.UnitTests/ChangeWaves_Tests.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf, src/Framework/ChangeWaves.cs
The MSBUILDDISABLEFEATURESFROMVERSION environment variable has different casing in the code and in the documentation. For Windows setting the variable according to the documentation works fine, but Linux is case-sensitive and so documentation in the current state leads to confusion. The error message and the comments are also fixed.
=> Update Change Waves env var in docs

src/Build/BackEnd/BuildManager/BuildManager.cs, src/MSBuild/XMake.cs
Fixes #7780
When using MSBuildDebugEngine, we should log everything at diagnostic verbosity. If no loggers were attached in the normal way, we still set verbosity to diagnostic (for command line builds) and manually set both DetailedSummary and LogTaskInputs on the BuildParameters in BuildManager. I believe these are the only two variables set by binlogs that weren't being set by MSBuildDebugEngine.
This sets the verbosity to diagnostic in XMake and sets DetailedSummary and LogTaskInputs on BuildParameters.
=> Ensure diagnostic logger verbosity Fixes #7780

src/Build/BackEnd/BuildManager/BuildManager.cs
In #6468, the two callers of the method and the method itself were moved to `ProjectCacheService`. However, the original method remained behind as dead code.
=> Remove unused BuildManager.LoadSubmissionProjectIntoConfiguration

src/MSBuild.UnitTests/MSBuildServer_Tests.cs, src/MSBuild/XMake.cs
Fixes #7964
MSBuild server doesn't play well with interactive builds.
Number of scenarios when server is not used, was extended.
I also moved `DebuggerLaunchCheck` to start of `Main` to improve debuggability of code before the check method is call.
Func test added.
=> Server shouldn't start during interactive build

.vsts-dotnet.yml
This should temporarily fix our build pipeline. 
All the branches except those which starts with `vs` will use the latest good OptProf data from main branch (hardcoded).
=> Use old opt-prof data for main and exp branches.

global.json
Resolves a component governance alert related to building with the old SDK.
Successful internal build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=6697148
=> Exp/new 6.0 sdk

src/Tasks/Microsoft.Common.CurrentVersion.targets
The `SatelliteDllsProjectOutputGroupDependsOn` msbuild property is written unconditionally and without regard to its previous value. 
In this change, the targets we require are *appended* to any prior value, thereby making extensibility easier.
⛔None. What would you suggest?
This *should* theoretically be safe, since no one would reasonably set this value to anything above this point in msbuild evaluation since it would be clobbered. But if they did anyway, then it no longer being clobbered could theoretically break something. Although it seems more likely that it would *fix* or guarantee target build order where it was broken before.
=> Avoid stomping on SatelliteDllsProjectOutputGroupDependsOn

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes [AB#1619029](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1619029)
During Single-File publish, the satellite assemblies are embedded in the EXE. The ClickOnce manifest should exclude satellite assemblies in this mode but it is not doing so currently.
Satellite Assemblies item group is now being conditionally populated when SF mode is false.
Verified with repro provided by customer. Additional testing done by CTI team for all ClickOnce configurations.
=> Skip passing Satellite Assemblies to ResolveManifestFile in Single-File Mode of ClickOnce publish

src/Samples/PortableTask/PortableTask.csproj, src/Shared/TypeLoader.cs, src/Shared/UnitTests/TypeLoader_Tests.cs
Fixes #7920
When a task ships MSBuild assemblies, we try to load both those assemblies and the assemblies next to MSBuild. This confuses the MetadataLoadContext. We should just use the MSBuild that's actually building, since we'll binding redirect to that anyway.
We also load MSBuild from the runtime, but that one isn't problematic here.
Load MSBuild from one place only in TypeLoader.
=> Deduplicate list of assemblies loaded in TypeLoader

src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs, src/Build/Definition/ProjectProperty.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Instance/ProjectPropertyInstance.cs, src/Build/Logging/BinaryLogger/BinaryLogger.cs, src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs, src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs, src/Build/Logging/SerialConsoleLogger.cs, src/Shared/EnvironmentUtilities.cs, src/Utilities/MuxLogger.cs
Fixes #7922
Although it's good to hide environment variables that may contain sensitive information, some variables seldom do and can be quite helpful in diagnosing build issues. This exempts environment variables that start with MSBUILD, COMPLUS_, and DOTNET_ from the normal filtering, even in the absence of MSBUILDLOGALLENVIRONMENTVARIABLES.
Exempted certain environment variables. Also prevented any EnvironmentVariableReadEvents from firing if MSBUILDLOGALLENVIRONMENTVARIABLES is set.
I built MSBuild.Dev.slnf and checked what its environment node contained.
This will need a structured log viewer update to make it less confusing.
~Confusing to me, this only almost works. Specifically, it filtered out all environment variables except the intended ones _plus_ OS, LOCALAPPDATA, and …
=> Exempt our env var Fixes #7922

src/Build/BackEnd/Client/MSBuildClient.cs
Fixes #7993, https://github.com/dotnet/runtime/issues/75867
There were reported issues, when mutex logic failed with unhandled IOException.
Extend TryLaunchServer try-catch scope to Include opening mutex and if it throws fallback to non-server behavior.
Unit test, CI.
=> Fallback when server launch fail due to create mutex error

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #7995
#6924 changed how `IsRidAgnostic` works.  Normally, the .NET SDK should set the `IsRidAgnostic` property (added in https://github.com/dotnet/sdk/pull/21986).  But when using an older version of the .NET SDK, there is fallback logic in the GetTargetFrameworksWithPlatformForSingleTargetFramework target to replicate the previous logic.
However, this fallback logic was incorrect, as it was setting item metadata, but reading from the property to determine whether to set it to the default value.  So if the property wasn't set, the `IsRidAgnostic` metadata would always be `false`.
Manual testing
=> Fix IsRidAgnostic fallback logic

src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/MSBuild/XMake.cs
Fixes https://github.com/dotnet/msbuild/issues/8009
Theory: dotnet watch stopping was sending Ctrl+C (SIGINT) to its child processes, which is unexpected as CTRL+C is propagated from client by build server packet command through its named pipe. 
Server set its cancellation token and all subsequent build has been therefore considered as to be cancelled.
When server recieves Ctrl+C (SIGINT) it now gracefully shut down its build submissions and then terminate.
Can't repro after code changes.
=> dotnet watch causing server to always fail

src/Tasks.UnitTests/AssignCulture_Tests.cs, src/Tasks/CultureInfoCache.cs
Fixes https://github.com/dotnet/sdk/issues/27890
Customer resources containing pseudolocales were no longer recognized due to case sensitivity. This prevented resources being generated of the given pseudolocale.
Added regression test
Tested locally by manually patching the SDK
When determining culture-validity on pseudolocales, ensure **case-insensitivity** during the check.
This wasn't an issue before because these items were added to a **case insensitive hashset.** This new codepath checks the array directly, but I forgot to pass along `OrdinalIgnoreCase`.
=> Ignore case when checking for pseudolocales

src/Build/BackEnd/Client/MSBuildClient.cs
Fixes #8008
With MSBuild server, we adjust the console mode to be able to handle VT100 codes. We should undo that after each build to make it obvious to users mistakenly emitting VT100 codes that they should add code to properly handle them.
Console settings we enable while building with MSBuild server persist after the build. In particular, if a customer is outputting raw VT100 codes, they  will be properly formatted if their code is run using `dotnet run`, but their customers will see the raw codes because they will not inherit anything from MSBuild.
Verified that building the project from #8008 no longer had unexpected spacing when these private bits were deployed to an SDK.
Verified that the bug motivating our original support for VT100 codes is still resolved.
Unit tests. …
=> Restore console mode after server build

src/Build/BackEnd/Shared/ConfigurationMetadata.cs, src/Build/Definition/Project.cs, src/Build/Definition/ProjectCollection.cs, src/Build/Definition/ProjectProperty.cs, src/Build/Instance/ProjectInstance.cs, src/Build/ObjectModelRemoting/DefinitionObjectsLinks/ProjectLink.cs, src/Build/PublicAPI/net/PublicAPI.Unshipped.txt, src/Build/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Fixes #7743
CPS iterates over collections of properties to access information about them, specifically whether they are global properties or derived from the environment. The current implementation of IsGlobalProperty and IsEnvironmentProperty start by accessing the global dictionary. That call makes a copy of the dictionary before just accessing information, which impacts performance.
This gets more complicated because the global dictionary should not be modified from the outside. Based on our publicly exposed API, it should be an IDictionary, so we cannot return an ImmutableDictionary. Returning a readonly Dictionary still permits modifications, and a ReadOnlyDictionary doesn't implement IDictionary.
This attempts to circumvent the problem of returning a readonly dictionary that …
=> Reduce unnecessary allocations when accessing information about global properties

src/Tasks.UnitTests/CreateItem_Tests.cs, src/Tasks.UnitTests/ResolveSDKReference_Tests.cs, src/Tasks/ResolveSDKReference.cs
Fixes #6150
We verify that the target platform is appropriate for the target platform identifier, but that check is too specific; it doesn't permit equivalent strings from matching. So far, we only know of UAP being a windows app, hence valid for windows. This fixes that instance.
Tried to reproduce this with and without this change. The error changed, and I don't think it's related, but I'm keeping this a draft PR anyway because I'm not confident about this.
=> Specialcase UAP == windows

src/Build/Definition/ToolsetReader.cs, src/Framework/FileClassifier.cs, src/MSBuild/app.amd64.config, src/MSBuild/app.config
Fixes #7951
During testing Arm64 MSBuild we detected regression caused by not considering some Arm64 known directories as immutable for files up to date check.
Adding arm64 directories in file classifier.
Local and Arm64 device.
=> Support for Arm64 immutable directories fast file up to date check

.vsts-dotnet-ci.yml, .vsts-dotnet.yml
As a part of https://github.com/dotnet/arcade/issues/10123, we are moving all docker containers to the new tagging schema
=> Update docker tag to the latest schema

src/Framework/NativeMethods.cs
Fixes #7943
MSBuild detects the wrong processor count on Windows when debugging processor groups
Replaces GetLogicalProcessorInformationEx with GetActiveProcessorCount and removes an incorrect check for >32 processors which is incompatible with Windows boot parameters for debugging processor groups.
=> Fix processor count on Windows for multiple processor groups

src/Build.UnitTests/Parser_Tests.cs, src/Build/Construction/ProjectItemDefinitionGroupElement.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Evaluation/ProjectParser.cs
Fixes [#5436](https://github.com/dotnet/msbuild/issues/5436)
There is a significant error in the original Constuctor ProjectItemDefinitionGroupElement(XmlElement xmlElement, ProjectRootElement parent, ProjectRootElement containingProject). The second parameter and third parameter types are the same. Fix the constructor bug and parse ItemDefinationGroup in when and otherwise.
Add one test SupportItemDefinationGroupInWhenOtherwise()
=> Support ItemDefinitionGroup in Choose/When

global.json, src/Build.UnitTests/BinaryLogger_Tests.cs, src/MSBuild/XMake.cs
Fixes #7828 
Binary logger option overrides verbosity by diagnostic and prints a line even verbosity is set to quiet.
The fix introduces a variable to store the original verbosity, if the "original verbosity" is quiet, it suppresses the console output when binary logger is requested.
=> Fix issue 7828: enabling the binary logger adds console output

src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr
Slower arm64 MSBuild due to assemblies NOT being ngen'd for the arm64 architecture.
Verified no regressions in https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/426628
raines
Forgind
Change setting in our .swr file to ngen relevant assemblies as `arm64`.
=> ngen arm64 binaries as arm64

src/Build/BackEnd/Client/MSBuildClient.cs, src/Framework/NativeMethods.cs
Fixes #8008
With the MSBuild server, I added support for VT100, which meant we could understand colorization and such from an older command prompt, but I also added DISABLE_NEWLINE_AUTO_RETURN, which made the UI look worse.
Customers using MSBuild server  and trying to print newlines (`\n`) will see output with extra space.
Manually tested the change: ran the proposed repro project and saw the bug. Overwrote the MSBuild in that SDK with custom bits from this PR and retested it, and I could no longer reproduce the issue. Tried using MSBuild.exe on a random project, and the important part of the VT100 change was preserved.
rokonec
Removed the DISABLE_NEWLINE_AUTO_RETURN argument
=> Restore newline auto return

src/Shared/TaskLoggingHelper.cs, src/Utilities.UnitTests/TaskLoggingHelper_Tests.cs
Fixes #7985 
`TaskLoggingHelper.LogErrorFromException()` does not currently take into account the relatively new `AggregateException` which has inner exceptions but an outer exception with very little details.
I've updated `TaskLoggingHelper.LogErrorFromException()` to check if the specified exception is an `AggregateException` and call the method again for each inner exception, respecting all of the arguments passed in around showing details or a stack trace.
A unit test was added
Unfortunately, I can't add the other improvement around an `InvalidProjectFileException` since `TaskLoggingHelper` is compiled into `Microsoft.Build.Utilities.Core` and that assembly does not reference `Microsoft.Build.dll` so it doesn't have access to the `InvalidProjectFileException` class 😢
=> Log each inner exception of an aggregate exception in TaskLoggingHelper.LogErrorFromException()

src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Client/MSBuildClientExitType.cs, src/MSBuild/MSBuildClientApp.cs
Fixes #7993
In the MSBuild server, we identify the state of the server via mutexes. Sometimes, for reason yet unknown to us, mutex could throw the exception `System.IO.IOException: Connection timed out`. When this occurs, we fallback to old behavior building without server. We fixed some of those in #8000, but now found more situations when this happens.
MSBuild non-Windows users could have intermittent error when building with `dotnet build`. 
This does not affect Visual Studio. 
Yes, this is a regression.
Unit tests.
Low risk. The fix adds additional try-catch blocks to process this situation.
[TODO]
- Add a try-catch block to catch and process the `IOException` exception when mutexes are used.
- Add a new client exit type for this kind of error.
=> Fallback when server client fails due to mutex connection timeout error.

README.md
This appears to be required now because of an Arcade task,
GenerateTrainingInputFiles.
Closes #8057.
=> README: mention long paths

documentation/wiki/ChangeWaves.md, src/Build.OM.UnitTests/Construction/ProjectRootElement_Tests.cs, src/Build.UnitTests/Evaluation/ProjectStringCache_Tests.cs, src/Build/ElementLocation/XmlDocumentWithLocation.cs, src/Build/Evaluation/ProjectStringCache.cs, src/Framework/ChangeWaves.cs
Fixes #5444
Context
The `ProjectStringCache` does seem to have a memory leak problem when used from VS.
The reason of the leak is that it clears memory on the event from `ProjectRootElementCache`, which is raised when project is moved out of the strong cache. The unproper use of `ProjectRootElementCache` might lead to `ProjectStringCache` not freeing memory.
Also, there were doubts if this cache adds anything at all to performance. Experiments does not show significant difference for the two cases.
We decided to remove `ProjectStringCache` under a change wave.
Changes Made
- Put usage of `ProjectStringCache` under change waves below 17.6.
Testing
Unit tests
Experimental insertion
Notes
- The previous PR (that eliminates the `ProjectStringCache` altogether with the related code): #7952.
- …
=> Eliminate project string cache under a change wave.

src/Directory.Build.props, src/StringTools/StringTools.csproj
Fixes #8039
Microsoft.NET.StringTools currently contains a netstandard2.0 ref assembly but no matching implementation assembly. This causes a run-time bind failure when the library is used by a 3.1 app, for example.
The package is being picked up MessagePack which targets netstandard2.0. The issue [blocks it from updating to a newer version of the library](https://github.com/neuecc/MessagePack-CSharp/pull/1515).
Yes, this regressed in 17.3.0. Only the initial version of the package was correct.
Low.
Built the package locally and inspected its contents.
This pull request uses a [documented workaround](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#advanced-extension-points-to-create-customized-package).
Package contents without the fix:
```
/lib
net35
net472
net7.0
/ref …
```
=> Fix Microsoft.NET.StringTools netstandard2.0 pack

src/Build/BackEnd/Components/ProjectCache/CacheResult.cs
Currently `CacheResult.CreateTaskItem` is iterating the input task item's `MetadataNames` and populating the return value's metadata. This iteration includes built-in (reserved) metadata like `DefiningProjectExtension`. This kind of metadata isn't allowed to be defined directly, although it doesn't throw here but instead later when provided to RAR which makes another copy the item (`ReferenceTable.SetItemMetadata`) and that's where it throws.
This change uses `CopyMetadataTo` which should "do the right thing" to copy metadata from one item to another.
=> [Project Cache] Fix CacheResult.CreateTaskItem

src/Build/BackEnd/BuildManager/BuildManager.cs
While investigating a flaky unit test I noticed the exception stack trace was basically useless:
Stack trace:
```
at Microsoft.Build.Execution.BuildManager.EndBuild() in /_/src/Build/BackEnd/BuildManager/BuildManager.cs:line 963
at Microsoft.Build.UnitTests.Helpers.BuildManagerSession.Dispose() in D:\a\1\s\src\Shared\UnitTests\ObjectModelHelpers.cs:line 2104
at Microsoft.Build.Engine.UnitTests.ProjectCache.ProjectCacheTests.MultiplePlugins() in D:\a\1\s\src\Build.UnitTests\ProjectCache\ProjectCacheTests.cs:line 1049
```
This is due to rethrowing the exception incorrectly (`throw e;` vs `throw;`). Looks like this was done in order to flatten an `AggregateException`, but the original stack trace can be preserved there as well using `ExceptionDispatchInfo`.
=> Avoid losing the exception stack in BuildManager.EndBuild

src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs
`ProjectCacheTests.MultiplePlugins` has been slightly flaky since its inception and throws a `IndexOutOfRangeException`. After (finally) investigating, I believe it's an actual race condition in the product.
In `ProjectCacheService.DisposeAsync`, there is the following snippet:
```cs
Task[] cleanupTasks = new Task[_projectCachePlugins.Count];
int idx = 0;
foreach (KeyValuePair<ProjectCacheDescriptor, Lazy<Task<ProjectCachePlugin>>> kvp in _projectCachePlugins)
{
cleanupTasks[idx++] = Task.Run(async () => ...);
}
```
Additionally, `BuildManager` does the following:
```cs
Task.Run(() => _projectCacheService.InitializePluginsForGraph(projectGraph, _executionCancellationTokenSource.Token));
```
And `ProjectCacheService.InitializePluginsForGraph` may add to its `_projectCachePlugins`.
So my …
=> Fix race condition with ProjectCacheService disposal and background initialization

src/Shared/UnitTests/XmakeAttributes_Tests.cs
Concerns #7576.
Architecture detection in two tests is not working well for arm64 scenario.
=> Fix wrong architecture detection in tests.

documentation/wiki/Binary-Log.md, documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md, documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md, documentation/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild.md, documentation/wiki/Contributing-Code.md, documentation/wiki/Contributing-Tasks.md, documentation/wiki/Localization.md, documentation/wiki/MSBuild-Resources.md, documentation/wiki/MSBuild-Tips-&-Tricks.md, documentation/wiki/Microsoft.Build.Framework.md, documentation/wiki/Rebuilding-when-nothing-changed.md, documentation/wiki/ResolveAssemblyReference.md, documentation/wiki/Target-Maps.md, documentation/wiki/UnGAC.md
- Changed http:// links to https:// where that was the case (a handful of http:// links remain), but all changed ones were checked
- Where GitHub links changed from `master` to `main`
- Where source lines were referenced it now points to a given revision, because pointing to a branch name means the line number may be incorrect. NB: so this was very much intentional!
- Linked to the archived page for dead links
- Updated old MSDN and docs.microsoft.com and blog links to point to the current location (even if it's the archive on learn.microsoft.com)
- One wrong link (http://source.roslyn.io/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/bin_/amd64/Microsoft.Common.CurrentVersion.targets,1820) remains in ResolveAssemblyReference.md
=> Fixed some URLs in the documentation

.opt-prof.yml, .vsts-dotnet.yml, eng/config/OptProf.runsettings
Configure the new pipeline for optimization data collection.
- Added the new `.yml` file for the OptProf v2 pipeline.
- The `.runsettings` file was updated by using the custom template in the run settings generation task (instead using the default one). The default template used by the task is located [here](https://github.com/dotnet/arcade/blob/c5dd6a1da2e6d9b3423ab809fcda8af2927a408b/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/VisualStudio.IbcTraining.runsettings). I took it and updated with the `VisualStudioConfiguration` element. This element derived from value `VSINSTALLATIONTYPE = optprof` from the legacy OptProf pipeline.
- Pipeline test runs
- Experimental VS insertion
=> Configure OptProf v2 pipeline

src/Tasks/Microsoft.Common.CurrentVersion.targets
This change allows producing reference assemblies by default for both legacy and SDK project systems
The corresponding changes were merged for legacy project system
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1341885
=> enable producing reference assemblies by default

src/Shared/PlatformNegotiation.cs, src/Tasks.UnitTests/GetCompatiblePlatform_Tests.cs
Platform negotiation still ends up in situations where project A explicitly tells project B to build as B's default platform. This leads to an unnecessary global property being passed, which leads to an unnecessary evaluation, and in some cases an overbuild.
This PR adds a catch-all that empties out the global Platform property whenever we fall into this case.
Add catch-all if statement that prevents global property Platform to be passed to referenced projects when redundant (the project would have built as that platform anyway).
This will unblock the implementation of this feature in VS. the only thing currently blocking adoption of this in VS is our datacenter build(cloudbuild) graph validation. it sees two project nodes with different platform global properties evaluating to the same …
=> Fixing overbuilding of platform negotiated projects

src/Build/Definition/Project.cs
Fixes [AB#1618509](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1618509)
AsOrdered causes UI delays in VS due to thread blocking.
Processing items is still parallel, but sorting is now done classically based on original item index. 
Existing unit tests are passing
=> AsOrdered was removed

src/Build.UnitTests/BackEnd/BuildRequestConfiguration_Tests.cs
Test CacheTest2 was failing on local test runs `build.cmd -test`
It was caused by creating folder at `C:\Users\}\...` which is allowed only for admin elevated processes.
Problematic path created as subfolder of current path.
Only test was changed
Local run.
=> Create problematic test path on current tmp path

documentation/ProjectReference-Protocol.md
Fixes https://github.com/dotnet/msbuild/pull/8114
Remove this property from the documentation.
=> DisableTransitiveProjectReferences is not required for SetPlatform

src/Tasks/Microsoft.Common.CurrentVersion.targets
Reverts dotnet/msbuild#8111
To unblock SDK insertions
It produces test errors:
> Microsoft.NET.Build.Tests.GivenThatWeWantToProduceReferenceAssembly.It_produces_ref_assembly_for_appropriate_frameworks(targetFramework: "netcoreapp3.1", extension: ".csproj", expectedExists: False) [FAIL]
[31;1m[m[37m      Expected boolean to be False, but found True.
[m[30;1m      Stack Trace:
[m[37m           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[m[37m           at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[m[37m           at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[m[37m           at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[m[37m           at …
=> Revert "enable producing reference assemblies by default"

src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf, src/Tasks/Unzip.cs
Fixes [AB#1645160](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1645160)
We should check whether a zip archive is attempting to unzip into a parent directory, as that would be a security risk.
Fail if the user is attempting to unzip to a location the user has not given them permission to unzip to.
=> Fix CodeQL bug about a zip slip

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/Build/Instance/ProjectItemInstance.cs
Improves https://github.com/dotnet/sdk/issues/27738 
I was looking for a reason why "design-time-builds" are slow (see https://github.com/dotnet/sdk/issues/27738).
One method that stands out in the performance profiler is a method called `GatherTaskOutputs`.
It copies the output of the executed task into a new `ProjectItemInstance`. Copying the output metadata involves creating and populating the `ImmutableDicitionary` in the newly created `ProjectItemInstance`. The copying process turns out to be a noticeably slow operation.
Instead of copying metadata properties one by one, all properties will be copied with a single [SetItems](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2.setitems) operation.
According to BenchmarkDotNet using a single …
=> Batch metadata updates for better performance

.vsts-dotnet.yml, src/Build.OM.UnitTests/Definition/Project_Tests.cs, src/Build.UnitTests/Construction/SolutionFile_Tests.cs, src/Tasks.UnitTests/Exec_Tests.cs
Brings changes to the 17.0 branch into 17.2.
=> Update 17.2 from 17.0

global.json, src/Build.UnitTests/BackEnd/OnError_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
Fixes #6633
Added check for tasks that fail without error messages, so that a normal priority message is shown.
Extended existing tests to validate new behavior. Also validated that in dotnet test scenarios, the new message is not visible.
=> Added logging message for tasks that fail without error

src/MSBuild/MSBuild.csproj
Fixes a build race condition observed in a PR build that manifested as:
src\MSBuild\MSBuild.csproj(246,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not copy "MSBuild\Microsoft.Build.CommonTypes.xsd" to "D:\a\1\s\artifacts\xsd\MSBuild\Microsoft.Build.CommonTypes.xsd". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\1\s\artifacts\xsd\MSBuild\Microsoft.Build.CommonTypes.xsd' because it is being used by another process.
=> Copy XSDs only in outer build

src/Build/BackEnd/BuildManager/BuildParameters.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/MSBuild.UnitTests/MSBuildServer_Tests.cs
Fixes #8094
Server have cached `BuildParameters.StartupDirectory` in static variable. When consequent builds starts from different directory, this value will have incorrect value of previous builds.
`BuildParameters.StartupDirectory` was also used for creating build-in `MSBuildStartupDirectory` property.
Set `BuildParameters.StartupDirectory` when `ServerNodeBuildCommand` is received by server.
After fixes, cant repro issues from #8094
Changes can possible affect only server behavior.
=> Set BuildParameters.StartupDirectory upon build command

.vsts-dotnet.yml
We revert the temporary fix "Use old opt-prof data for main and exp branches. (#7973)" since the new optprof pipeline (see PR #8085) started to produce new optimization data.
This reverts commit 6033e4c95bcd9fa31ebe9b52462c15521cda8f62.
experimental CI run
=> Use OptProf v2 data in CI builds 

README.md, documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md, documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
- Forgind made a PR where the bootstrap flag is set automatically when building which simplifies the dev process a lot.
- Some of the documentation wasn't changed when that got merged in and we didn't notice until onboarding a new teammate 
So, this PR does the following:
- Change all of the inferences to bootstrap except on bootstrapped_msbuild.sh files, though it's likely also not needed there
- Also mention installing the SDK as installing workloads may not get the needed ASP.NET Runtime Packs for 7.0
- Also fixes a typo lol
Follow up to https://github.com/dotnet/msbuild/pull/7485 
@rainersigwald  @edvilme If there were additional things you needed to do to resolve the failures, we should add them to this PR.
cc @Forgind
=> Remove Bootstrap Property from Onboarding Docs

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs, src/Build/Instance/ProjectItemInstance.cs
Reverts dotnet/msbuild#8098 which causes #8153. We should investigate and consider bringing it back (with test coverage for whatever it is we missed!).
=> Revert "Batch metadata updates for better performance"

src/Tasks/GenerateResource.cs
This method was used only in the immediately preceding method, which was compiled conditionally. Compile it conditionally, too, for clarity.
=> Build DetermineWhetherSerializedObjectLoads less

src/Build.UnitTests/Evaluation/SimpleVersion_Tests.cs, src/Build/Utilities/SimpleVersion.cs
Fixes #8177 
Inadvertent whitespace in a .NET version string, for example, may be tricky for a customer to diagnose and can be trimmed with minimal performance and code complexity impacts.
SimpleVersion.RemoveTrivia() trims whitespace before performing its other operations.
New tests in SimpleVersion_Tests.cs.
Update source code documentation to reflect the change.
SimpleVersion_Tests run clean for both net472 and net7.0.
All string manipulation is done with Span, to preserve the goal of no heap allocations when parsing a version string.
=> SimpleVersion.Parse() ignores leading and trailing whitespace

src/Tasks.UnitTests/Copy_Tests.cs, src/Tasks/NativeMethods.cs
Fix symlink creation
I tried creating a symlink with this, and it succeeded, both in the unit test and in the wild. I also tweaked the unit test to verify that the reparse point is not 0 for the created file. I removed the early exit if the user doesn't have the expected permission.
Once both this and #8149 are merged, we should modify the test in #8149 to use this to create a symlink on windows.
=> Fix Copy with UseSymbolicLinksIfPossible = true

.opt-prof.yml, .vsts-dotnet.yml, eng/config/OptProf.runsettings
In order to be able to collect optimization data for this branch using the opt-prof v2 pipeline, we need to update the runsettings file generation. The generation happens during the CI build. 
- The `.runsettings` file was updated by using the custom template in the run settings generation task (instead using the default one). The default template used by the task is located [here](https://github.com/dotnet/arcade/blob/c5dd6a1da2e6d9b3423ab809fcda8af2927a408b/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/VisualStudio.IbcTraining.runsettings). I took it and updated with the `VisualStudioConfiguration` element. This element derived from value `VSINSTALLATIONTYPE = optprof` from the legacy OptProf pipeline.
- Added the new `.yml` file for the OptProf v2 pipeline to vs bracnhes as well, …
=>  Configure OptProf v2 pipeline 16.11

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
Fixes [`#1764`](https://github.com/dotnet/msbuild/issues/1764)
Update <i Include=""@(h->'%(identity))""> to  <i Include=""@(h->'%(identity)')"">
Original item expands to a literal string rather than a transform of the h item.
Passed
=> Fix the malformed test transforming an item allows access to metadata value

src/StringTools/StringTools.csproj
As discussed offline, the StringTools package is currently not authored correctly as the StringTools assembly is differently named between target frameworks. More precisely, the net35 assembly is named differently than the rest of the builds: Microsoft.NET.StringTools.net35.dll. Reason for that is that this assembly is binplaced into a common folder with another tfm build of the same library.
By dropping the net35 asset from the package, assembly FileNotFoundExceptions are avoided.
Contributes to https://github.com/dotnet/msbuild/pull/8116
=> Drop the net35 asset from the StringTools package

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes #8196
Work item (Internal use): [AB#1680332](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1680332)
Commit 789fa9a8d changed the `CleanPublishFolder` target to remove PublishDir unconditionally. The previous condition removed the dir only if it was set to `$OutputPath\app.publish`.
Users override `PublishDir` to custom paths and don't expect their publish dir to be deleted during clean. The change broke that behavior. 
Customers who customize `$(PublishDir)` to a central location (not uncommon, but not default) encounter build breaks on `Rebuild`, because each project tries to delete the same directory.
Other users will be confused because `Clean` deletes more than it used to.
Multiple customer reports on GitHub and via VS Feedback. A …
=> Undo change to delete PublishDir unconditionally

.vsts-dotnet.yml, eng/Version.Details.xml, eng/Versions.props, eng/common/build.ps1, eng/common/darc-init.ps1, eng/common/init-tools-native.ps1, eng/common/sdl/packages.config, eng/common/templates/job/execute-sdl.yml, eng/common/templates/post-build/post-build.yml, eng/common/tools.ps1, global.json
With these updates I can get `exp/` builds working; there's possible followup for full official builds.
- Updating 'Microsoft.DotNet.Arcade.Sdk': '5.0.0-beta.22276.2' => '5.0.0-beta.22526.12'
- Move BAR publish to windows-latest
=> Build updates for 16.11

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs, src/Tasks/AssemblyDependency/CopyLocalState.cs, src/Tasks/AssemblyDependency/Reference.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Fixes internally reported issue.
We currently skip resolving information about bad images, and that includes not setting whether they are CopyLocal. When we get to logging our results, we assume it's set, since it's set for all not-BadImages. This ensures we only access IsCopyLocal if it has been set.
Check for IsBadImage before accessing IsCopyLocal.
=> Prevent InternalError exceptions on BadImages

src/Build.UnitTests/BackEnd/MockSdkResolverService.cs, src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs, src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/DefaultSdkResolver.cs, src/Build/BackEnd/Components/SdkResolution/HostedSdkResolverServiceBase.cs, src/Build/BackEnd/Components/SdkResolution/ISdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs, src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Permits SDK resolvers to return an enumerable of messages in addition to the warnings and errors. Messages are ignored if we end up finding an SDK resolver that can resolve the SDK, but they are aggregated and printed out all at once in an InvalidProjectFileException if we fail to resolve any SDK.
This will need changes to other SDK resolvers for it to be fully effective. If this is merged, I will attempt the requisite changes to the NuGetSDKResolver and maybe the C++ SDK resolver.
Note also that this includes a breaking change, but I suspect it's seldom used, perhaps not used at all by anyone outside Microsoft.
=> Improve SDK resolver error reporting if none of the SDK resolvers attached are able to resolve a particular SDK

src/Build.OM.UnitTests/Construction/ConstructionEditing_Tests.cs, src/Build.UnitTests/Evaluation/Evaluator_Tests.cs, src/Build/Evaluation/Evaluator.cs
Fixes #8167 and Fixes #8168
The VS tools path "directory does not exist" error check did not take into account a condition on the import element. This resolves that issue.
Move the condition check earlier and have it suppress the error.
Manual testing with repro from #8168.
=> Fix vs tools path error when condition is false

eng/dependabot/Packages.props
Versions of Newtonsoft.Json <13.0.2 are flagged by compponent governance alerts as vulnerable to https://github.com/advisories/GHSA-5crp-9r3c-p9vr
Related fix: #7737. We need to update the version again. 
Fixes https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/7554893?typeId=6797870
=> Update Newtonsoft.Json version

eng/dependabot/Packages.props
Versions of System.Security.Cryptography.Xml <6.0.1 are flagged by component governance alerts as vulnerable to https://github.com/dotnet/announcements/issues/232
Fixes https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/7392363?typeId=6797870
=> Update System.Security.Cryptography.Xml version

src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
Versions of Newtonsoft.Json <13.0.2 are flagged by component governance alerts as vulnerable to https://github.com/advisories/GHSA-5crp-9r3c-p9vr
Related fixes: #7737, #8229. I found one more place where Newtonsoft.Json v13.0.1 is brought.
Fixes https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/7554893?typeId=6797870
=> Update Newtonsoft.Json version in MSBuild.Bootstrap.csproj

src/Tasks.UnitTests/Copy_Tests.cs, src/Tasks/Copy.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Fixes [#6247 ](https://github.com/dotnet/msbuild/issues/6247)
MSB3891: Both "UseHardlinksIfPossible" and "UseSymboliclinksIfPossible" were specified in the project file. Please choose one or the other.
Support both UseHardlinksIfPossible and UseSymboliclinksIfPossible are on. Initialize variable hardLinkCreated and symbolicLinkCreated. When source file and destination file are not in the same folder. It failed to create hard link and fallback to  create symbolic link.
Update test case CopyWithHardAndSymbolicLinks() to support both UseHardlinksIfPossible and UseSymboliclinksIfPossible on
**Manually test in different drivers when don't have permission create symbolic link**
**Output is as bellow:**
CopyFiles:
Creating hard link to copy "Program.cs" to "c:\MyProject\Destination\Program.cs". …
=> CopyTask: Fallback to SymbolicLinks if HardLinks fail

.opt-prof.yml, .vsts-dotnet-ci.yml, .vsts-dotnet.yml, eng/config/OptProf.runsettings
- [vs16.11] Update dependencies from dotnet/arcade (https://github.com/dotnet/msbuild/pull/7332)
- Update dependencies from https://github.com/dotnet/arcade build 20220309.5
- Update dependencies from https://github.com/dotnet/arcade build 20220526.2
- Bump CLI version to match global.json
- Bump NuGet version to match
- Avoid AssemblyName.KeyPair on .NET (https://github.com/dotnet/msbuild/pull/7660)
- Merge remote-tracking branch 'upstream/vs16.9' into backport-keypair-elision-16.11
- Merge pull request https://github.com/dotnet/msbuild/pull/7663 from rainersigwald/backport-keypair-elision-16.11
- Configure OptProf v2 pipeline 16.11 (https://github.com/dotnet/msbuild/pull/8189)
- Updating 'Microsoft.DotNet.Arcade.Sdk': '5.0.0-beta.22276.2' => '5.0.0-beta.22526.12'
- Move BAR publish to …
=> Backport opt-prof v2 vs17.0 

documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md, documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md, src/Build.UnitTests/BinaryLogger_Tests.cs, src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs, src/Framework/NativeMethods.cs, src/Tasks/Copy.cs, src/Tasks/NativeMethods.cs
Fixes https://github.com/dotnet/msbuild/issues/6773
Symlinked files were not embedded into binlog
Add detection of symlinked files and switch to their target
Support not added for full FW
Unit test added, attempting to embed symlinked file (failing without the fix)
=> Add support for symlink files embedding to binlog

.vsconfig
.NET Core 2.1 is out of support and is not used in the projects in MSBuild.sln. Removing the "Microsoft.Net.Core.Component.SDK.2.1" ID from the .vsconfig file will stop Visual Studio from complaining when .NET Core 2.1 is not installed.
Fixes #8255
Developer issue while working with MSBuild.sln in Visual Studio.
Remove one line from .vsconfig file
Tested opening the solution before and after the .vsconfig change.
=> Update .vsconfig to remove .NET Core 2.1 component

src/Build.UnitTests/BackEnd/MSBuild_Tests.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
Fixes #8188 
Items Exclusion filtering for items defined within targets is not using same filtering logic (https://github.com/dotnet/msbuild/blob/main/src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs#L483-L486) as items defined outside of targets (https://github.com/dotnet/msbuild/blob/main/src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs#L89-L93). There is a discrepancy in cross-platform paths mix-matchingh.
Rather targeted isolated change the build time exclusion evaluation (for items defined within targets) is comparing on normalized paths.
It's a question whether we rather do not want to try to extract and unify the items expansion logic - that might however be a large spanning change with notrivial regression risk.
Targetted unit test …
=> Make target items paths crossplatform

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks/AssemblyDependency/BadImageReferenceException.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
Fixes https://github.com/dotnet/msbuild/issues/6224
See issue -- a change was made to add more detail when RAR fails to resolve a reference due to encountering a BIFE. This added too much detail -- not only the message from the inner exception, but also the callstack. We should not dump callstack when there is no bug in MSBuild (or a task/logger).
Oddly enough I hit this again https://github.com/dotnet/msbuild/issues/8140 and didn't remember the original discussion, and therefore again assumed there was a bug.
1. Fix BIFE to include the message from any inner exception. (There was a suggestion in the issue that it also include the exception type, but I don't know of any case where the type is necessary in order to disambiguate what happened, and we don't have precedent for doing it. It …
=> Stop dumping stack for BadImageFormatException

src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/RedistList.cs
We do exact string comparisons with this path, and it is user-provided, so if it does not include a slash, we may do more work.
=> Ensure trailing slash for string used as key in AssemblyTableInfo's cache

src/Build.UnitTests/BackEnd/CacheSerialization_Tests.cs, src/Build.UnitTests/BackEnd/ConfigCache_Tests.cs, src/Build/BackEnd/BuildManager/CacheSerialization.cs, src/Build/BackEnd/Components/Caching/ConfigCache.cs
Fixes #4386
Any cache entries from projects excluded from isolation constraints should be excluded from the output results cache file.
Only the cache entry with the smallest configuration ID (that of the project to be built in isolation) should be serialized into the output results cache file. As described in #4386, this prevents the case where dependency projects pass down the same cache entry obtained through skipping/violating isolation constraints to a dependent project, creating duplicate input cache entries.
Added a UT.
Addressing this issue since it came up frequently when testing #8249.
=> Exclude isolation-violating cache results from output results cache (#4386)

.opt-prof.yml, .vsts-dotnet.yml, eng/config/OptProf.runsettings
Brings the following changes from the 17.0 branch into 17.2:
- [vs16.11] Update dependencies from dotnet/arcade (https://github.com/dotnet/msbuild/pull/7332)
- Update dependencies from https://github.com/dotnet/arcade build 20220309.5
- Update dependencies from https://github.com/dotnet/arcade build 20220526.2
- Bump CLI version to match global.json
- Bump NuGet version to match
- Avoid AssemblyName.KeyPair on .NET (https://github.com/dotnet/msbuild/pull/7660)
- Merge remote-tracking branch 'upstream/vs16.9' into backport-keypair-elision-16.11
- Merge pull request https://github.com/dotnet/msbuild/pull/7663 from rainersigwald/backport-keypair-elision-16.11
- Configure OptProf v2 pipeline 16.11 (https://github.com/dotnet/msbuild/pull/8189)
- Updating 'Microsoft.DotNet.Arcade.Sdk': …
=> Backport opt-prof v2 vs17.2

src/Tasks/GenerateResource.cs
Fixes #7946
The GenerateResource task previously would deserialize and reserialize resource files. It used BinaryFormatter, which is known to be unsafe; to mitigate that security risk, we added a check for the mark of the web on resource files; files with that mark are considered unsafe, and those without are considered safe to be deserialized. On core, we have a separate solution: don't deserialize and reserialize them.
More recently, in work to unify code paths, we effectively enabled the check on core. There remains a check that we're on windows, so it only affected windows computers, and most windows devices could accomplish that fine. Nanoservices, however, did not have the COM API that we called as part of the "IsDangerous" check. This led it to crash.
Using a (windows nanoserver) …
=> Disable MotW check on core in GenerateResource

src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs, src/Build.UnitTests/Graph/GraphTestingUtilities.cs, src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Build/Graph/GraphBuilder.cs, src/Build/Graph/ProjectInterpretation.cs
Originally when the graph code was written, a non-top-level multitargeting project would end up never actually dispatching to the inner builds, so that edge was removed from the graph. For example if A referenced B and B was multitargeting, A would call B(outer) with `GetTargetFrameworks`, and then call B(inner) with `Build`. B(outer) never called B(inner) (again, when B wasn't an entry point). 
However, at this point `GetTargetFrameworks` on the outer build actually does call into the inner builds, specifically the `GetTargetFrameworksWithPlatformForSingleTargetFramework` target. See:
Beyond the correctness issue, the practical impact of this is that this causes graph builds to potentially attempt to schedule outer builds before inner builds, which become blocked on the …
=> Avoid removing outer -> inner graph edge

src/Build/Logging/FancyLogger/ANSIBuilder.cs, src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs
Tweak to FancyLogger: hide the cursor so it's less obvious what part of the screen is being written at any given time, and it doesn't jump around visibly.
=> FancyLogger: Hide cursor on alternate buffer

src/Build/Logging/FancyLogger/FancyLogger.cs
Fixes #
Previously, when using <kbd>Ctrl</kbd><kbd>C</kbd> with the FancyLogger, the process would end abruptly, causing unexpected behavior such as rendered elements not erasing.
Added new `Console.CancelKeyPress` event handler
Waiting for https://github.com/dotnet/msbuild/pull/8284 to show summary at the end
=> [FancyLogger] Clear screen on ctrl-c

eng/Versions.props
Lot less to do without the build status messages!
Do you think we should update the PackageValidationBaselineVersion to 17.5.0?
=> Update version to 17.6

src/Tasks.UnitTests/XmlPoke_Tests.cs, src/Tasks/XmlPoke.cs
Fixes [#5814](https://github.com/dotnet/msbuild/issues/5814)
Can't pass empty string to XmlPoke task.
Remove the required attribute for Value and the exception when value is null.
Unit test XmlPokeWithEmptyValue()
=> Allow to set empty string for XmlPoke Value

src/Build.UnitTests/BinaryLogger_Tests.cs, src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs, src/Framework/NativeMethods.cs
Fixes #6773
Supersedes #8213 and  #8282
Symlinked files were not embedded into binlog - previous solution was too much focused on symlinks and hence requried nontrivial code to properly distinguish aymlinks with available contnet.
Alternate approach - proceed with adding file as soon as it has available content
Preexisting unit test is excercising the scenario. Added a case for empty file - that still should not be added.
=> Handle symlinks embedding into binlogs - approach #2

src/Shared/UnitTests/ObjectModelHelpers.cs
Fixes [#8288](https://github.com/dotnet/msbuild/issues/8228)
There's a bug in the cleanup logic here. Specifically, it creates the source and dest files, and at the end of the test, it calls Helpers.DeleteFiles(sourceFile, destFile); That method loops through each file and deletes it if it exists, then deletes the directory containing it if it's empty...but when we delete the source file, the directory isn't empty; it has the destination folder/file. When we delete the destination file, its folder just contains the destination file, so we delete that. Afterwards, the source folder never gets deleted. That means we can't write to it. Mentioned in https://github.com/dotnet/msbuild/pull/8211#discussion_r1040269656
Sort paths descendingly by depth, it will delete sub folder/file at first. …
=> Sort paths descendingly by depth

.opt-prof.yml, .vsts-dotnet.yml, eng/config/OptProf.runsettings
Brings the following changes from the 17.2 branch into 17.4:
- [vs16.11] Update dependencies from dotnet/arcade (https://github.com/dotnet/msbuild/pull/7332)
- Update dependencies from https://github.com/dotnet/arcade build 20220309.5
- Update dependencies from https://github.com/dotnet/arcade build 20220526.2
- Bump CLI version to match global.json
- Bump NuGet version to match
- Avoid AssemblyName.KeyPair on .NET (https://github.com/dotnet/msbuild/pull/7660)
- Merge remote-tracking branch 'upstream/vs16.9' into backport-keypair-elision-16.11
- Merge pull request https://github.com/dotnet/msbuild/pull/7663 from rainersigwald/backport-keypair-elision-16.11
- Configure OptProf v2 pipeline 16.11 (https://github.com/dotnet/msbuild/pull/8189)
- Updating 'Microsoft.DotNet.Arcade.Sdk': …
=> Backport opt-prof v2 vs17.4

src/Tasks.UnitTests/Delete_Tests.cs, src/Tasks/Delete.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
Fixes [#199](https://github.com/dotnet/msbuild/issues/199)
Add Retries which default value is 0 and RetryDelayMilliseconds default value is 1000ms properties. Initialize local value  retries, add while condition to reach the maximum Retries.
Unit test DeleteWithRetries()
=> Add Retries, RetryDelayMilliseconds parameters to Delete task

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
This helps users correctly specify this property when using XSD-driven IntelliSense.
See https://aka.ms/vs-build-acceleration for more information on this feature.
=> Add AccelerateBuildsInVisualStudio to XSD

src/Build/Logging/FancyLogger/ANSIBuilder.cs, src/Build/Logging/FancyLogger/FancyLogger.cs, src/Build/Logging/FancyLogger/FancyLoggerBuffer.cs, src/Build/Logging/FancyLogger/FancyLoggerMessageNode.cs, src/Build/Logging/FancyLogger/FancyLoggerProjectNode.cs
Fixes #
A design goal for the FancyLogger is not to have too big of an impact on performance, especially considering all the formatting, layout and constant updating on the buffer. This PR reduces render and build time when using the logger by half.
- Rendering now occurs in a completely separate project to the build, meaning it doesn't block
- Added indicators to both `FancyLoggerProjectNode` and `FancyLoggerBuffer` to avoid re-rendering when no changes occured
- Delimited for loop in `FancyLoggerBuffer.Render()` to only perform operations on the lines that are visible on the screen
- In `FancyLoggerBuffer.Render()` text is stored in a string and then logged to the console all at once to avoid laggy behavior
- Improved performance for finding lines by Id
- Code refactoring
=> [FancyLogger] Improve render performance

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/IntrinsicFunctions.cs, src/Build/Utilities/NuGetFrameworkWrapper.cs
This is the initial implementation of an experimental intrinsic designed to support the ability to build subsets of a repo/solution/project. This ability can reduce build time and support the ability to build projects based on available target resources per-platforms.
The idea is that this intrinsic would be used in a set of targets that are imported early, before standard .NET SDK targets, and could be used to filter the target frameworks that a project is going to build for. .NET's arcade will contain an initial implementation of those targets, looking something like this:
```
<PropertyGroup Condition="$(_EnableTargetFrameworkFiltering)">
<_OriginalTargetFrameworks Condition="'$(TargetFrameworks)' != ''">$(TargetFrameworks)</_OriginalTargetFrameworks>
<_OriginalTargetFrameworks …
```
=> Introduce intrinsic to 'intersect' target frameworks

src/Build/Utilities/NuGetFrameworkWrapper.cs
Recent changes #8336 and #8350 collided to produce a build break on just-introduced formatting.
=> Space around braces

src/Utilities.UnitTests/TrackedDependencies/FileTrackerTests.cs, src/Utilities/TrackedDependencies/FileTracker.cs
(Copied from https://github.com/dotnet/msbuild/pull/8351)
Fixes [AB#1678521](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1678521)
Context
https://github.com/dotnet/msbuild/pull/8049 broke the temp filtering logic by using the MSBuild-specific temp path instead of the true base temp path. This manifests as an overbuild of some C++ projects.
Changes Made
Reverted the change. Enabled relevant unit tests.
Testing
Existing unit tests and a C++ end-to-end repro.
Notes
The rest of FileTracker tests cannot be enabled without significant work (related to https://github.com/dotnet/msbuild/issues/649).
=> Fix temp file filtering in FileTracker

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
It respects PublicKey as a property in the current project
but not metadata: https://github.com/dotnet/sdk/blob/f31b16f8a6a05a600f277975a329399b44b85e9b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L114-L118
Fixes an issue reported over email.
=> XSD: InternalsVisibleTo uses Key

src/Tasks/Microsoft.Build.Tasks.csproj
This task is hit in some ClickOnce publish scenarios and failed with
a bad error message (see dotnet/sdk#29951). But it is compilable, so
let's build it.
=> Build RequiresFramework35SP1Assembly task for net7

Directory.Build.props, Directory.Build.targets, eng/Packages.props, eng/dependabot/Packages.props, global.json, src/Samples/Directory.Build.props
Move to NuGet Central Package Management and transitive pinning to dogfood the newish feature and simplify future (transitive) component updates.
=> Central Package Management

src/Samples/Directory.Build.props
https://github.com/dotnet/msbuild/pull/8317 causes a lot of red NU1008 on restore in VS
Reordered import in Samples `Directory.Build.props`
It seems order of import affects value of `ManagePackageVersionsCentrally` for sample projects: when import happens before the values of properties in `src/Samples/Directory.Build.props` takes precedence; otherwise root Directory.Build.props overwrites the value with `true`.
=> reordered import in Samples `Directory.Build.props`

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/UnitTests.Shared/EnvironmentProvider.cs, src/UnitTests.Shared/RunnerUtilities.cs
Fixes #8313
Some of the unit tests are failing when run from VS - caused by the fact that those tests are supposed to execute msbuild and fail to do so due to attempts to interpret the test runner as the dotnet host process
Added helper to infer the proper host to run the msbuild in core
Logic adopted from [SDK](https://github.com/dotnet/sdk/blob/main/src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs#L65-L94), with some alternations (removed unnecessary interop, added nullables, some styling fixes)
=> Infer dotnet host to run integration scenarios

src/Framework/NativeMethods.cs, src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs, src/Utilities/ProcessorArchitecture.cs
This makes architectures added in .NET 5, 6, and 7 known to MSBuild.
By using the architecture returned by the runtime, we eliminate the 'uname' processes started on these platform to try determine the processor architecture.
@Forgind @rainersigwald ptal.
cc @omajid @uweigand @janani66
=> Sync ProcessorArchitectures with those known by runtime.

src/Build/Logging/BinaryLogger/BinaryLogger.cs
Fixes #8394 
This is mainly so that the static graph-based restore can detect that the user enabled the binary logger so it can automatically provide a binary log for restore which is run out-of-proc so it has to be another file.
This sets `MSBUILDBINARYLOGGERENABLED=true` when the binary logger is enabled.  I originally tried to have a new property on the `EngineServices` but that doesn't work for out-of-proc nodes.  To make that work, each out-of-proc node would need to be told if the binary logger is in use for that particular build which seems like a lot overhead compared to just setting an environment variable.
Built locally and ran the bootstrap MSBuild to verify the environment variable is set.
=> Set an environment variable indicating that the binary logger is enabled

src/MSBuildTaskHost/OutOfProcTaskHost.cs, src/StringTools/InternableString.Simple.cs
Fixes part of 8329
The 3.5 version of `InternableString` uses a simpler hash code calculation, the results of which were not matching the 4.72/Core version. This manifested as a failing unit test `RetainsLastStringWithGivenHashCode` in VS.
Made the routine return the same numbers as the other implementation. It fixed the UT and also made the hash code "better" as previously we were shifting instead of rotating bits.
Existing unit tests (previously failing).
It would be nice to figure out how to run 3.5 tests in CI.
=> Fix .NET 3.5 InternableString.GetHashCode to match the full implementation

src/MSBuild/LiveLogger/MessageNode.cs
Fixes #8393 
Currently the live logger does not log the message id's. Including the message ID is useful when searching for messages from customer reports.
When receiving `BuildMessageEventArgs`, the `Code` is now also passed to `MessageNode` and printed on the display.
=> [LiveLogger] Add code to high priority messages

src/Build.UnitTests/BackEnd/DebugUtils_tests.cs, src/Build.UnitTests/Graph/IsolateProjects_Tests.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/MSBuild.UnitTests/MSBuildServer_Tests.cs, src/Shared/UnitTests/TestAssemblyInfo.cs, src/Shared/UnitTests/TestEnvironment.cs
Context
CanShutdownServerProcess seems to be flaky. We need more logs to find out why...
Changes Made
- Add support for enabling DebugEngine in integration tests
- Use it in CanShutdownServerProcess  and other flaky test
=> Enable temporary comm logging for CanShutdownServerProcess test

.github/workflows/backport.yml
Introduces backport GitHub action for automation-aided propagation of changes between branches.
**usage:**
comment
`/backport to <target bracnh>`
on PR that needs to be backported (ideally after merging). New PR will be created backporting to the requested branch.
=> Introduce backport GHA

src/Build.UnitTests/BackEnd/DebugUtils_tests.cs, src/Build.UnitTests/BinaryLogger_Tests.cs, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Framework/NativeMethods.cs, src/Shared/UnitTests/FileMatcher_Tests.cs, src/Tasks.UnitTests/Copy_Tests.cs, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/UnitTests.Shared/RequiresSymbolicLinksFactAttribute.cs
Tests currently don't pass on a clean Windows machine in a non-admin command prompt. Even on Win11 with developer mode enabled (and on a Microsoft DevBox VM, no less), the OS refuses to create symlinks unless the process runs elevated.
Made the affected tests detect the ability to create symlinks and skip if the `kernel32!CreateSymbolicLink` call is failing.
Unit tests in admin and non-admin command prompts.
As much as I would like to have maximum possible coverage by running the tests unconditionally, I believe that a good developer experience is more important here. Specifically I do not want to require contributors to run elevated or jump through hoops to make the OS cooperate. This is a niche functionality anyway.
=> Skip symlink tests when symlinks cannot be created

src/Framework/LogInterpolatedStringHandler.cs, src/Framework/LogInterpolatingHandler.cs, src/Shared/TaskLoggingHelper.cs, src/Utilities.UnitTests/MockEngine.cs, src/Utilities.UnitTests/TaskLoggingHelper_Tests.cs
Fixes #7875
This PR replaces #8410
Enables to log interpolated strings from tasks.
Added new interpolated string handler with overloads in TaskLoggingHelper.
New unit tests added.
I tried to use ```FormattableString```, but old overload had precedence.
Handler is mutable value type, but mutating methods should be invoked by compiler generated code. If you are not comfortable with it, we can change it to reference type with heap allocation.
=> Added support for logging interpolated strings in tasks.

src/Framework/IForwardingLogger.cs
It looks like someone accidentally a word.
=> Fix grammar in IForwardingLogger

src/Build.UnitTests/BackEnd/KnownTelemetry_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Framework/Telemetry/KnownTelemetry.cs, src/MSBuild/MSBuildClientApp.cs, src/MSBuild/XMake.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1708215
In VS there are multiple instances of BuildManager called asynchronously. For DTB and normal build and maybe other which I have not identified yet.
BuildManager instances acquire its own BuildTelemetry instance as oppose to sharing single BuildTelemetry instance in non thread safe manner.
Locally
=> BuildManager instances acquire its own BuildTelemetry instance

src/MSBuild/LiveLogger/LiveLogger.cs, src/MSBuild/XMake.cs
Fixes #8384
LiveLogger only needs to process certain events for its work. All other events from the MSBuild nodes should be filtered out on their way to the main node for performance. The filtering of the events is done via ConfigurableForwardingLogger.
Similar to console logger behavior, instead of registering LiveLogger as the central logger, register it as a distributed logger. 
Manual
=> Make LiveLogger distributed

documentation/wiki/Binary-Log.md, documentation/wiki/Providing-Binary-Logs.md
As discussed on triage - binlogs captured through VS project system extension tooling are less preferrable to logs captured via environment opt-in. Let's make it more explicit in our docs that we are often linking externally to our customers.
=> Improve VS binlogs providing info

src/MSBuild/XMake.cs
Fixes #8455
LiveLogger is only enabled for terminal emulators that support VT100/ANSI escape sequences. On Windows, these are supported by default on Windows Terminal, but Console Host (the old terminal emulator) does not support all of them. Hence LiveLogger checks if the code is run on Windows Terminal via the `WT_SESSION` environment variable. 
Added check for when `Environment.GetEnvironmentVariable("WT_SESSION") == null`
=> [LiveLogger] Fix for conhost.exe

src/MSBuild/LiveLogger/LiveLogger.cs
Fixes #8450
The console logger shows the total time elapsed for the build in the summary. It should also be shown on the summary for the LiveLogger
The difference between the time at build start and build end is displayed in the summary at the end of the build.
Manual testing
=> [LiveLogger] Report build time

src/Tasks/Microsoft.Managed.After.targets
When using `DeployOnBuild=true`, the `Publish` target is hooked to the `Build` target. This change reflects that in the graph p2p protocol by appending the publish targets to the build (and rebuild) targets.
=> Fix graph p2p protocol when using DeployOnBuild=true

global.json
Fixes https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/7687819?typeId=6797870&pipelinesTrackingFilter=0  Secuity issue
=> Update .Net SDK

eng/Build.props
Our CI builds fails because of bug https://github.com/NuGet/Home/issues/12373. 
It is fixed in https://github.com/NuGet/NuGet.Client/pull/5010. 
We are waiting for it to flow to CI machines. Meanwhile this PR applies a workaround.
Note: This PR needs to be reverted once it happens.
=> Temporary turn off static graph restore.

.vsts-dotnet.yml
This should temporarily fix our build pipeline.
All the branches except those which starts with `vs` will use the latest good OptProf data from main branch (hardcoded opt-prof from 20230217.4).
=> Use old opt-prof data for main and exp branches - 2

src/MSBuild/LiveLogger/LiveLogger.cs
This should avoid some exceptions observed caused by races between modifying and accessing the dictionary, part of #8458.
=> LiveLogger: ConcurrentDictionary for projects

src/Shared/BuildEnvironmentHelper.cs
Fixes #7576
Unit tests on MAC M1 machine fails. More precisely, those are unit tests related to task host. 
It happens because unit tests do not use bootstrap version of MSBuild to perform tests. So, there is no "arm64" folder and path `MSBuildToolsDirectoryArm64` ends up being null. 
Defaulted `MSBuildToolsDirectoryArm64` to `CurrentMSBuildToolsDirectory`, as it is done in case of amd64 machine.
Unit tests
=> Fix Mac ARM64 unit tests.

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs
FYI @JaynieBai 
Fixes issue causing failing insertion https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/454231
Setting verbose logging and rebuilding twice was leading to build errors.
This was caused by the fact that low-pri node reuse log event didn't have BuildContext set and ParallelConsoleLogger was choking on it (null ref).
Setting BuildEventContext on the node reuse log event
=> Fix logging of node reuse

src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs, src/Build/Graph/ProjectInterpretation.cs
In graph projects, if project A (x86) references project B (AnyCPU), we use the same global properties dictionary in both cases. This means that project A will get Platform:AnyCPU as a global property.
Platform should be the only property that changes, so anything that prevents the parent project from getting its global properties changed by dependent projects would unblock VS.
Note that we cannot use one dictionary and change the property while building B in the above example, then revert the property because that would still affect B; anyone using the project graph object would be getting incorrect information.
From a performance perspective, there should only be ~6-7 properties in the dictionary, so copying it should not be a major hit.
This change prevents the global properties …
=> fixing global properties error in Dynamic platform resolution

src/Build.UnitTests/Definition/Project_Internal_Tests.cs, src/Build.UnitTests/Instance/ProjectInstance_Internal_Tests.cs, src/Build/Definition/Project.cs, src/Build/Definition/ProjectOptions.cs, src/Build/Instance/ProjectInstance.cs
Fixes #8523
When a build happens the `BuildParameters` object passes along the `Interactive` property when creating `ProjectInstance` objects.  During evaluation, the `Evaluator` then sets the built-in `MSBuildInteractive` property to true and the SDK resolver context is also set.  
However, when you create an instance of a `ProjectInstance` object via the `ProjectInstance.FromFile(string, ProjectOptions)` method, there is no way to indicate that the evaluation should be interactive.  
This change adds a new `Interactive` property to the `ProjectOptions` object.  The value is passed to the evaluator and the `MSBuildInteractive` MSBuild property is now set.
I implemented this for:
* `ProjectInstance.FromFile(string, ProjectOptions)`
* …
=> Add ProjectOptions.Interactive so that callers can specify that project evaluation can be interactive

src/Shared/LoadedType.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1729428
Change https://github.com/dotnet/msbuild/pull/7387/files#diff-2295212a8e8b80807c0594f9e600d287e5a813c10326d71b4ac5ce907f0ecc42R45 have caused regression of not running specific net35 task in isolated AppDomain.
In our particular case of customer feedback issue, `UnregisterAssembly` task have kept some assemblies locked, because it need to load assemblies in order to unregister them, while prior this changes assembly files were released when `AppDomain` which loaded them have been deleted.
Fallback to old behavior handling detecting attributes from full types as oppose to reflection only types.
Changes was based on changes of related PR ^.
I have created repro. After fixes it no longer repros.
Consequences of this error …
=> net35 task host properly handle isolated AppDomain tasks

src/Build/Evaluation/ProjectRootElementCache.cs
Related to #8412
During research of optimization opportunities for Evaluation I have found relatively cheap win. 
Some time ago we have introduced optimized up to date check leveraging immutable file locations. See usage `FileClassifier` class for more details. This PR made `ProjectRootElementCache` use it too so cached XML file is considered valid if it was read from immutable location.
As stated above. Additionally I tried to slightly improve readability by eliminating stuff if nesting.
Locally. 
Measure gain for Orchard null incremental build /m was ~21% of Evaluation CPU time.
=> Consider XML cache valid if loaded from non modifiable file

src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1761147
`Assembly.Location` throws in fullFW (https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?source=recommendations&view=net-7.0#exceptions)
It returns empty fron net5.0 up
Altering the code to uniformly return empty path for dynamic assemblies (and prevent exceptions)
=> [Bugfix] Do not read Location of dynamic assemblies

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Related to https://github.com/dotnet/aspnetcore/issues/47029.
Document the `InvariantGlobalization` property since we intend to set it in templates.
=> Add doc for InvariantGlobalization property

eng/Build.props, eng/Versions.props, src/Build.UnitTests/BackEnd/KnownTelemetry_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Framework/Telemetry/KnownTelemetry.cs, src/MSBuild/MSBuildClientApp.cs, src/MSBuild/XMake.cs
Originall implementation did not expect multiple instances of BuildManager called concurrently. But in VS DTB and normal build are run concurrently.
This is backported from main PR #8444 
In rare cases Dictionary data structure is corrupted and can cause infinite loop. This affect only VS scenarios. 
It is currently #7 ranked VS hang issue.
Yes, introduced in VS 17.4.
Manual validation by @rokonec and automated tests. Additionally it has been in bleeding edge VS for about three weeks.
Low
=> BuildManager instances acquire its own BuildTelemetry instance (#8444)

src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
May fix #8519
Some SdkResolverResolveSdkStop events aren't being picked up. This is especially problematic, since those hold most of the interesting information. This tries to ensure that they are logged even if we throw.
Move stop event to finally block
None
=> Move ResolveSdkStop event to finally

src/Tasks/ResolveKeySource.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
The error message "Certificate signing not supported on .NET Core" is logged in ResolveManifestKey because signing from a PFX file is not enabled. `FEATURE_PFX_SIGNING`. In other places, like in `ResolveAssemblyKey()` just above, it will give the error message "PFX signing not supported on .NET Core" which is a lot less confusing.
Changed the error message logged.
=> Improve PFX error message

src/Tasks/DownloadFile.cs
Fixes [#8538](https://github.com/dotnet/msbuild/issues/8538)
With https://github.com/dotnet/msbuild/pull/8440 MSBuild is now logging callstacks for scenarios in which neither MSBuild, nor a logger, nor a task has any bug.
Assertion: a callstack should indicate someone should make a bug report.
Concatenate the exception message and that of any inner exceptions, and display that. Log the ex.ToString() in the low-prio message.
Local Testing. build with -verbosity:diag
=> Log DownloadFile error stack trace to low priority message

eng/Build.props, eng/Versions.props, src/Build.UnitTests/BackEnd/KnownTelemetry_Tests.cs, src/Build/BackEnd/BuildManager/BuildManager.cs, src/Build/BackEnd/Client/MSBuildClient.cs, src/Build/BackEnd/Node/OutOfProcServerNode.cs, src/Framework/Telemetry/KnownTelemetry.cs, src/MSBuild/MSBuildClientApp.cs, src/MSBuild/XMake.cs
Summary
Original implementation did not expect multiple instances of BuildManager called concurrently. But in VS DTB and normal build are run concurrently.
This is backported from main PR https://github.com/dotnet/msbuild/pull/8444
Customer Impact
In rare cases Dictionary data structure is corrupted and can cause infinite loop. This affect only VS scenarios.
It is currently https://github.com/dotnet/msbuild/pull/7 ranked VS hang issue.
Regression?
Yes, introduced in VS 17.4.
Testing
Manual validation by @rokonec and automated tests. Additionally it has been in bleeding edge VS for about three weeks.
Risk
Low
Note
Has been already backported to 17.5
Contains fix for infra which disables nuget static graph restore (otherwise CI pipeline is failing)
=> Concurrency bug fix - BuildManager instances acquire its own BuildTelemetry instance (#8444)

src/Tasks.UnitTests/Copy_Tests.cs, src/Tasks/Copy.cs, src/Tasks/NativeMethods.cs
Fixes #8273 
Prevent overwriting the source of a hard/symbolic link.
Always delete the destination file (unless readonly and OverwriteReadOnlyFiles is false)
Added unit test.
=> Issue8273 corrupt nu get cache

src/Tasks.UnitTests/WriteCodeFragment_Tests.cs, src/Tasks/WriteCodeFragment.cs
Fixes #8516
Setting an `OutputDirectory` where the directory does not exist, and setting an `OutputFile` would fail.
(Setting an `OutputDirectory` where the directory does not exist, and not providing an `OutputFile` value would succeed because `FileUtilities.GetTemporaryFile` calls `Directory.CreateDirectory`.)
- Added new unit tests:
- `CombineFileDirectoryAndDirectoryDoesNotExist` (pairs with `CombineFileDirectory`)
- `ToDirectoryAndDirectoryDoesNotExist` (pairs with `ToDirectory`)
- Added overload of `CreateTask`
- Changed task to call `FileUtilities.EnsureDirectoryExists`.
Added unit tests first and confirmed failure.
Ran all unit tests on Windows 11 and macOS 12 (Monterey).
=> Change WriteCodeFragment task to create directory

src/Build/Evaluation/ProjectRootElementCache.cs
Fixes #8567 
When evaluating projects in parallel, MSBuild is likely to need to load the same included files (Microsoft.Common.props, Microsoft.Managed.Core.targets, ...) at about the same time on multiple threads. This leads to wasted work as `ProjectRootElementCache` doesn't prevent the same xml file from being parsed multiple times.
Introduced per-file locking. If multiple threads need the same file and the file is not in cache, only one thread will do the actual loading and the rest will wait for it to finish.
Also encapsulated `s_getEntriesNumber` manipulation in a new `ReentrancyGuard` struct.
Existing unit tests and the solution load VS scenario where this was found.
I recommend reviewing with the **Hide whitespace** option activated.
=> Add per-file locking to ProjectRootElementCache

eng/Versions.props, src/Build/BackEnd/Components/Logging/LoggingService.cs
Customer, mainly internal like XStore, with huge repos, using `msbuild /graph /bl` on  powerful development and build computers, might experience 15x plus regression in evaluation time.
It has been identified as performance bug in our logging event pub/sub mechanism. When ingest queue reaches its bound, at .net472 `ManualResetEventSlim` causes way too many thread.Yields flooding the system with thread context switches.
This hypothesis has been verified by PerfMon perfcounter `System.ContextSwitches`.
Alhougt counterintuitive, `AutoResetEvent` , `ManualResetEvent` or even `SpinLocking` produced better behavior and with those the issue no longer reproduce.
In case of XStore it was about 7 minutes in build time.
Yes, introduced in VS 17.4.
Manual validation by @rokonec and automated tests. …
=> Use AutoResetEvent as oppose to ManualResetEventSlim

src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs, src/Build/Construction/Solution/SolutionProjectGenerator.cs, src/Build/Microsoft.Build.csproj, src/Shared/SolutionConfiguration.cs, src/Tasks/AssignProjectConfiguration.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Tasks/ResolveProjectBase.cs
Fixes #6751
This change combines the solution configuration xml parsing which the project caching code and the tasks code uses. I did not add `SolutionProjectGenerator.AddPropertyGroupForSolutionConfiguration` into the mix as that's a write scenario and the other two are read scenarios. Maybe at some point the object model could be made more robust and support both the read and write scenarios, but whatever, this is incrementally better.
Note that the main motivation here is that the graph construction code currently does not support the sln-defined configurations, ie what the `AssignProjectConfiguration` target does, so I'll be working on a follow-up change for that. And instead of creating a third copy of this parsing logic, I thought I'd send this PR to consolidate the logic first. …
=> Consolidate solution configuration xml parsing logic

.github/fabricbot.json
This updates the bot that currently posts whenever any action is taken on a PR targeting 17.4 (i.e., opened, closed, reopened, commented on, etc.) to only post when the action is to open or reopen a PR. It also extends the branches for which this takes effect to include a number of vs* branches, including some that don't currently exist.
I think this is the final or penultimate iteration. Specifically, I don't think it will fire if you target main, then retarget to vs* without closing and reopening it...unfortunately, retargeting isn't something fabric bot understands. We can add "label added:Servicing-approved" to the list of options as a proxy. That isn't perfect, but it would make it slightly more robust and slightly noisier. I'm open to doing that or not doing that.
=> Tell bot to only post when a PR is opened or reopened and let it target more servicing branches

src/Build/Evaluation/ProjectRootElementCache.cs
For `msbuild -restore` scenarios `ProjectRootElementCache` cache used to be cleared for restore could have modified or added some project files (like *.directory.props etc...). 
We can optimize it by keeping ProjectRootElements from immutable locations (like SDK) in that cache as those will be used by build following that restore.
`Clear()` does not remove immutable files from cache.
Locally
=> ProjectRootElementCache.Clear do not clear immutable files

documentation/wiki/ChangeWaves.md, src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/Expander.cs
Fixes #5113
AnyHaveMetadataValue returns empty when the itemgroup is empty, which doesn't make sense and doesn't match our documentation. This changes it to return false in that case.
If we see the function we're evaluating is AnyHaveMetadataValue, don't skip out early.
Made a unit test
=> Any have metadata value when empty Fixes #5113

src/Tasks/Microsoft.Common.CurrentVersion.targets
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1741178 (https://developercommunity.visualstudio.com/t/Always-copy-appconfig-to-executable-fol/10270579)
Customer reported that their app.config is not occasionaly getting updated in output folder.
Turns out to be a real issue specific to usage of `AutoGenerateBindingRedirects`.
**tl;dr;:** Caused by wrong up-to-date condition on `GenerateBindingRedirects` target
**More details:**
Upon closer investigation, the app config is not getting copied as the up-to-date-check is comparing to the file in obj:
It's getting into that location with `GenerateBindingRedirects` - however that was skipped in repro case:
This turns out to be caused by a wrong item specified as input for the target - hence the target was skipped if the change occured …
=> Fix app.config not getting updated in output

src/Tasks.UnitTests/WriteLinesToFile_Tests.cs, src/Tasks/FileIO/WriteLinesToFile.cs
The WPF repo and another Microsoft internal repo both reported problems
with the warning added in #8371. Since new warnings can be breaking
changes, demote the warning to a message.
Fixes #8605.
=> Demote WriteLinesToFile warning to message

src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs, src/Tasks.UnitTests/ResourceHandling/MSBuildResXReader_Tests.cs, src/Tasks.UnitTests/ResourceHandling/ResGenDependencies_Tests.cs, src/Tasks/GenerateResource.cs, src/Tasks/Microsoft.Common.CurrentVersion.targets, src/Tasks/ResGenDependencies.cs, src/Tasks/ResourceHandling/MSBuildResXReader.cs, src/Tasks/Resources/Strings.resx, src/Tasks/Resources/xlf/Strings.cs.xlf, src/Tasks/Resources/xlf/Strings.de.xlf, src/Tasks/Resources/xlf/Strings.es.xlf, src/Tasks/Resources/xlf/Strings.fr.xlf, src/Tasks/Resources/xlf/Strings.it.xlf, src/Tasks/Resources/xlf/Strings.ja.xlf, src/Tasks/Resources/xlf/Strings.ko.xlf, src/Tasks/Resources/xlf/Strings.pl.xlf, src/Tasks/Resources/xlf/Strings.pt-BR.xlf, src/Tasks/Resources/xlf/Strings.ru.xlf, src/Tasks/Resources/xlf/Strings.tr.xlf, src/Tasks/Resources/xlf/Strings.zh-Hans.xlf, src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
It will be removed in .NET 9; doing so should be discouraged.
Note that this does nothing by default, but we can change that in the SDK.
Fixes #8453
BinaryFormatter is deprecated and will be removed in .NET 9. In addition to the possibility of using a modern MSBuild with an older framework, there are apparently ways you can exempt your project, so we are not currently removing it entirely, and this warning (which is off by default) can be disabled even if it is enabled in the SDK.
I deleted `using System.Runtime.Serialization.Formatters.Binary;` in GenerateResource, then put a warning before the one usage of BinaryFormatter. That isn't necessarily the best way to figure out where it's used, as it would be helpful to know early, so feel free to comment to that effect.
Then I disabled it …
=> Add warning for using BinaryFormatter in GenerateResource on .NET 8

src/Tasks/Microsoft.Common.CurrentVersion.targets
Prefer sln-defined platforms for command-line builds over dynamic platform resolution
Today dynamic platform resolution is inconsistent due to the condition being based on `$(BuildingInsideVisualStudio)`, which is obviously only set in VS. Sln-based command-line builds wouldn't have that set though, so dynamic platform resolution would end up running. The comment on `_GetProjectReferencePlatformProperties` implies that sln-provided platforms should be used instead though, so this change switches the condition to check `$(CurrentSolutionConfigurationContents)` instead to make the experience consistent when building a sln in VS or command-line.
=> Prefer sln-defined platforms for command-line builds over dynamic platform resolution

eng/Versions.props
Also switched to final version of 17.5.0 package as our validation baseline
=> 17.6 final branding

src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf, src/MSBuild/XMake.cs
This message was in hardcoded English, but all the other deferred messages are localized.
=> Localize response-file-used message

documentation/specs/static-graph.md
.default (in MSBuild code) followed an earlier spec that referred to it as <default> and omitted some details. This clarifies the meaning of .default.
Fixes #
=> Clarify what .default means

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/Build/Microsoft.Build.csproj, src/Framework/EncodingUtilities.cs, src/Tasks/Microsoft.Build.Tasks.csproj, src/Utilities/Microsoft.Build.Utilities.csproj
This will single-instance it for improved performance.
=> Move EncodingUtilities to Framework

documentation/design/rar-core-scenarios.md
Fixes #8441
This document aims to capture the core functionality provided by the ResolveAssemblyReference task when building .NET (_Core_ - pun intended) projects. The goal is to rationalize and optimize the task, ultimately achieving substantially better performance and crossing out RAR from the list of notoriously slow build tasks.
Added the document ([preview link](https://github.com/ladipro/msbuild/blob/8441-rar-core-design/documentation/design/rar-core-scenarios.md)).
=> Document 'Resolve Assembly Reference core scenarios'

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs, src/Tasks/Microsoft.Managed.After.targets
This change fixes graph builds for multitargetting projects using BuildProjectReferences=false
Previously, when using BuildProjectReferences=false the graph would consider the outer build calling GetTargetPath on the inner builds. However, it actually calls Build when dispatching to the inner builds, and those call GetTargetPath on their dependencies. In effect this is causing graph builds to be non-graph builds since the target list is not accurately described.
This change ensures the correct behavior by separating the ProjectReferenceTargets logic for single and multi-targetting projects.
Only the top-level project is in the graph, and the inner builds do not have "Build" as a predicted target:
Dispatching to inner builds does not come from cache:
Inner builds resolving dependencies …
=> Fix graph target list for multitargetting projects using BuildProjectReferences=false

src/Build/BackEnd/Client/MSBuildClient.cs, src/MSBuild.UnitTests/MSBuildServer_Tests.cs
Fixes #8631
We have got him!
There was eluding low freq flaky test. It was caused by race condition between finishing build server client and server releasing its `I am busy` mutex.
Wait and retry when it was detected busy for 500 ms.
Clean additional logging from test.
Local, PR
=> Fix flaky test  CanShutdownServerProcess

.editorconfig
Fixes #8618
IDE0055 is currently too unspecific - opting out of it.
```
C:\src\msbuild\src\Build.UnitTests\BackEnd\MSBuild_Tests.cs(796,59): error IDE0055: Fix formatting [C:\src\msbuild\src\Buil
d.UnitTests\Microsoft.Build.Engine.UnitTests.csproj::TargetFramework=net472]
```
(changed to message and not blocking the build after this change)
=> Change IDE0055 (Fix Formatting) warning->message

src/Utilities.UnitTests/ToolTask_Tests.cs, src/Utilities/ToolTask.cs
ToolTask uses a private flag `_terminatedTool` to indicate the task execution timed out or cancelled. That flag should be reset on each execution, otherwise the return value of all following executions could be changed.
Fixes https://github.com/dotnet/msbuild/issues/8541
When the same ToolTask instance being executed multiple times (by derived classes, for example), the return status of all following executions might be wrong (`false`) if the first execution timed-out or cancelled. Such case may arise if user try to run an external tool with retry and timeout. The problem is the internal `_terminatedTool` flag has not been reset on each execution. Reset that flag on each execution solved the problem.
Resets the internal flag `ToolTask._terminatedTool` on each task execution.
The following …
=> Reset internal terminated flag in ToolTask (#8541)

eng/BootStrapMSBuild.targets, eng/Packages.props, src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj, src/MSBuild.Bootstrap/RedirectNuGetConsoleProcess.After.Microsoft.Common.targets
Today the bootstrap doesn't have `NuGet.RestoreEx.targets` (or `NuGet.Build.Tasks.Console.exe` even), so it falls back to the "regular" restore. This change brings in those bits via the `NuGet.Build.Tasks.Console` package.
=> Fix static graph restore functionality for the bootstrap

src/MSBuild/CommandLineSwitches.cs
These comments were hidden where they didn't helpfully show when I was adding a new `ParameterizedSwitchInfo`.
=> Doc commments for ParameterizedSwitchInfo

src/Build.UnitTests/Evaluation/Expander_Tests.cs, src/Build/Evaluation/Expander.cs, src/Build/Evaluation/IntrinsicFunctions.cs
Fixes #8551
The intrinsic functions include functions for bit And, Or, Xor, and Not operators but not for the bit shift operators.
Added functions LeftShift, RightShift, and RightShiftUnsigned. The functions expect values of type `int` (32 bit) which matches the existing bit operator functions. `long` (64 bit) is not supported by any of the bit operator intrinsic functions.
Tested on Windows 11 and macOS 12 Monterey.
Added to Expander_Tests.cs and ran unit tests.
Created and ran BitShift.proj project file with the following content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<Target Name="Test">
<LeftShiftTest>$([MSBuild]::LeftShift(1, 2))</LeftShiftTest>
<RightShiftTest>$([MSBuild]::RightShift(-8, …
```
=> Add bit shift intrinsic functions

eng/Versions.props, src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
Projects that have tasks that run in the .NET Framework 3.5 environment that return metadata are unusable in MSBuild 17.6.0.
The return value of `ITaskItem.CloneCustomMetadata` is an `IDictionary`, which is generally (in modern MSBuild) backed by a `Dictionary<string, string>`, but can be (when given an item from a net35 taskhost) a `Hashtable`. In the latter situation, casting entries to `KeyValuePair<,>` fails, because they conform only to `DictionaryEntry`.
Use that less-well-typed approach--the casts were present in the pre-bulk-edit version of the code. Fixes #8645.
Work item (Internal use): [AB#1790945](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1790945)
Microsoft-internal customer reported breaks in projects that use WiX3.
Yes, from #8240. …
=> Avoid overly-specific cast in bulk metadata copy

src/Tasks/Microsoft.NET.props
In general we want to produce reference assemblies whenever possible, as they improve incremental build performance.
Making them work end-to-end requires support from other components, such as fast up-to-date checks in VS. While support was originally added for SDK-style projects, it was not present for legacy `.csproj` files. Accordingly, `ProduceReferenceAssemblies` was set `true` only when the target framework was `net5.0` or later for C#/VB projects. Similarly, F# added support during `net7.0`, so a similar check was added for F# projects.
VS 17.5 ships support for reference assemblies in the legacy CSPROJ fast up-to-date check, so all C#/VB projects are supported. Similarly, F# has full support. Consequently, it is now safe to enable the production and consumption of reference …
=> .NET projects produce a reference assembly by default

src/Build.UnitTests/BinaryLogger_Tests.cs, src/UnitTests.Shared/RequiresSymbolicLinksFactAttribute.cs
Relates to https://github.com/dotnet/msbuild/issues/8643
Adding diagnostics to flaky test - to have more data on future repro
(logging the actual list of embedded files)
=> Add diagnostics to symlink embedding unittest

documentation/wiki/ChangeWaves.md, src/Build.UnitTests/BackEnd/MSBuild_Tests.cs, src/Build/BackEnd/Components/Logging/LoggingContext.cs, src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs, src/Build/Definition/ProjectItemDefinition.cs, src/Build/Evaluation/Expander.cs, src/Build/Evaluation/IItemMetadata.cs, src/Build/Evaluation/IItemTypeDefinition.cs, src/Build/Instance/ProjectItemDefinitionInstance.cs, src/Build/Instance/ProjectItemInstance.cs, src/Build/Microsoft.Build.csproj, src/Build/Resources/Strings.resx, src/Build/Resources/xlf/Strings.cs.xlf, src/Build/Resources/xlf/Strings.de.xlf, src/Build/Resources/xlf/Strings.es.xlf, src/Build/Resources/xlf/Strings.fr.xlf, src/Build/Resources/xlf/Strings.it.xlf, src/Build/Resources/xlf/Strings.ja.xlf, src/Build/Resources/xlf/Strings.ko.xlf, src/Build/Resources/xlf/Strings.pl.xlf, src/Build/Resources/xlf/Strings.pt-BR.xlf, src/Build/Resources/xlf/Strings.ru.xlf, src/Build/Resources/xlf/Strings.tr.xlf, src/Build/Resources/xlf/Strings.zh-Hans.xlf, src/Build/Resources/xlf/Strings.zh-Hant.xlf
Fixes #8527
Self referencing item metadata in an item definition within the target leads to possible unintended expansion (and cross-applying of pre-existing item instances).
This behavior is not a bug - it's the implication of the target batching feature - but might be confusing. So detection and warning is added here
A self reference (qualified or unqualified) of metadata within the item defeiniton (which is within a target) is detected and high importance message is issued.
Tests added for a warning case and for a non-warning case (self-referencing metadata outside of target context)
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/11034
It's unfortunately hard to obtain data on prevalence of this pattern due to limitations of available code searches (github search doesn't …
=> Log item self-expansion

src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf, src/MSBuild/XMake.cs
In #8608 I introduced a new string for this, but it's redundant with the one we already had that we only used to log to the console.
Dropping the "log directly to console" approach because we now (18 years later) have deferred messages, the engine API that someone didn't want to add.
Fixes #8664.
=> Unify "used response file" messages

documentation/Changelog.md, eng/Packages.props, src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Microsoft.Build.csproj, src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj, src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj, src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj, src/StringTools.UnitTests/StringTools.UnitTests.csproj, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks/Microsoft.Build.Tasks.csproj, src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
- System.Security.Principal.Windows is inbox since net6.0
- System.Net.Http is inbox since netcoreapp2.0
- System.Reflection.Metadata is inbox since netcoreapp2.0
- System.Threading.Tasks.Dataflow is inbox since netcoreapp2.0
- Remove System.Net.Http package references which aren't needed as they underlying assembly is inbox on both .NETFramework and .NETCoreApp.
By avoiding the dependencies, we minimize the dependency graph and with that the attack surface.
cc @MichaelSimons (removes netstandard1.x dependencies)
=> Avoid package dependencies on inbox libraries

src/Tasks/Microsoft.NET.props
This reverts commit 648765340670c93c682d4ac5c04efea3c605b985.
Fixes issues reported offline.
=> Revert ".NET projects produce a reference assembly by default (#8571)"

documentation/Changelog.md, eng/Packages.props, src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj, src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj, src/Build/Microsoft.Build.csproj, src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj, src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj, src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj, src/StringTools.UnitTests/StringTools.UnitTests.csproj, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks/Microsoft.Build.Tasks.csproj, src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj
Reverts dotnet/msbuild#8669 because it causes component governance alerts like (internal Microsoft link) https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/3582291?typeId=6797870&pipelinesTrackingFilter=0
=> Revert "Avoid package dependencies on inbox libraries"

eng/SourceBuildPrebuiltBaseline.xml, eng/Version.Details.xml
- Baseline a few dependencies until msbuild targets net8.0, or an arcade fix comes in
- Add SBRP dependencies (with subscription) and source build tags
=> Enable prebuilt detection

src/Build/Evaluation/ItemSpec.cs
Relates to https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1728887/
ItemSpecFragment.MatchCount result is thrown away when called from ItemExpressionFragment.MatchCount (it just needs to get info about existing match).
The mentioned codepath is on the stack of the detected UI delay. While it might not be the rootcause, it doesn't hurt to improve this behavior.
Thanks @davkean for specific suggestions pointers during ivestigation
=> ItemSpec: Do not call MatchCount when count is not needed

eng/sdl-tsa-vars.config
MSBuild had been added to the code validation pipeline but was missing the tsa config file. Per the instructions [here](https://github.com/dotnet/arcade/blob/36ac84d30381886c6bad6cd55c28771dcc4c0880/Documentation/Validation.md?plain=1#L40-L47) and after talking to Matt, adding this file
Added a tsa config file by copying from SDK
Not sure how to test this. I pushed an internal build but the checks didn't run as I'm told they run nightly in a separate pipeline.
Validation pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=2157183&view=results
=> Add tsa config file to enable validation pipeline

src/Utilities.UnitTests/ToolTask_Tests.cs
This failed for me in an unrelated PR and on my dev box and at least on my dev box it was because sometimes my PowerShell profile took longer than 1 second to process.
Pass -NoProfile to avoid that time entirely when it's not necessary.
In addition, save the engine's log to the test log to give some clues if the test fails again.
=> NoProfile in ToolTaskThatTimeoutAndRetry test

documentation/README.md, documentation/wiki/Controlling-Dependencies-Behavior.md
Relates to:
#4795
#8405 
Documenting some aspect of tailoring behavior of references. Capturing as well resolution/workarounds for the listed comunity reported issues
=> Document references peculiarities

src/Tasks/Microsoft.Common.CurrentVersion.targets
Contributes to https://github.com/dotnet/sdk/issues/19506
This fixes an issue where VS design-time builds would fail when reference assemblies could not be found.
By allowing the design-time build to continue, the .NET Project System will the nominate a restore which may bring in a package that provides those reference assemblies.
Without this addition, the task will fail and the build will end early, such that the restore does not occur and progress is not made.
This helps when users do not have targeting packs installed (such as for out-of-support versions of .NET Framework, like v4.5). With this change, a reference assembly package (like `Microsoft.NETFramework.ReferenceAssemblies.net45`) may be downloaded for the user to compile against.
Tested locally. See discussion in linked issue …
=> GetReferenceAssemblyPaths continues on error in design-time builds

.editorconfig, src/Build/Collections/ConvertingEnumerable.cs, src/Build/Construction/ProjectElementContainer.cs, src/Build/Definition/Project.cs, src/Build/Definition/ToolsetReader.cs, src/Build/Evaluation/Expander.cs, src/Build/Evaluation/ItemsAndMetadataPair.cs, src/Build/Evaluation/LazyItemEvaluator.cs, src/Build/Graph/ProjectGraph.cs, src/Build/Graph/ProjectGraphEntryPoint.cs, src/Build/Xml/ProjectXmlUtilities.XmlElementChildIterator.cs, src/Deprecated/Engine/ItemsAndProperties/ExpressionShredder.cs, src/Framework/BuildEngineResult.cs, src/Framework/NativeMethods.cs, src/Framework/Profiler/EvaluationLocation.cs, src/Shared/FileMatcher.cs, src/Shared/FileSystem/WindowsNative.cs, src/Shared/Pair.cs, src/StringTools/InternableString.Simple.cs, src/StringTools/InternableString.cs, src/StringTools/SpanBasedStringBuilder.Simple.cs, src/Tasks/AssemblyDependency/AssemblyNameReference.cs, src/Tasks/ComDependencyWalker.cs
In recent dogfood VS builds we've gotten many IDE0251 suggestions, some warnings escalated to errors in StringTools. Follow many of those suggestions, but bump the rule down to `suggestion` always, like the related IDE0250.
=> Add readonly to struct methods

src/Framework/NativeMethods.cs
Detected while working on #8413
outputIsScreen  is always falls on on non-windows OS causing /tl:auto to reject live logger
see files
locally
would effect MSB server VT100 output coloring as well.
=> Fix outputIsScreen on non-windows OS.

src/MSBuild.UnitTests/MockTerminal.cs, src/MSBuild/LiveLogger/ITerminal.cs, src/MSBuild/LiveLogger/LiveLogger.cs, src/MSBuild/LiveLogger/Terminal.cs, src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Partly Fixes #8391
Ensure all new strings used in the logger are localizable
- introduce strings in resx
- using such resource strings
- modify code to allow better localization (from `write(part1); write(part2); write(part3)` into `str = formastringfromresources(); write(str)`
local
unit tests
=> [LiveLogger ] Localize strings

src/MSBuild/LiveLogger/LiveLogger.cs
Related to #8413
Some VT100 Terminal client requires
Using URI file schema for Live Logger hyperlinks
Manual local testing on Windows, VS code and Linux.
It has been that way in Eduardo version before.
=> Using URI file schema for Live Logger hyperlinks

build.sh
Fixes source building under FreeBSD where a symlink has not been made for `bash`
`/bin/bash` is standard under OSes that ship with `bash` installed by default. FreeBSD does not have `bash` as a default shell.
For portability `/usr/bin/env bash` is used on the shebang line. This also bring it inline with other dotnet repos.
none needed?
`env` is standard at this point. I have been unable to find a non-historic UNIX-like system that places `env` in a location exclusively that is not `/usr/bin/`
=> Let env find bash

src/MSBuild/LiveLogger/AnsiCodes.cs, src/MSBuild/LiveLogger/ITerminal.cs, src/MSBuild/LiveLogger/LiveLogger.cs, src/MSBuild/LiveLogger/TerminalColor.cs, src/MSBuild/Resources/Strings.resx, src/MSBuild/Resources/xlf/Strings.cs.xlf, src/MSBuild/Resources/xlf/Strings.de.xlf, src/MSBuild/Resources/xlf/Strings.es.xlf, src/MSBuild/Resources/xlf/Strings.fr.xlf, src/MSBuild/Resources/xlf/Strings.it.xlf, src/MSBuild/Resources/xlf/Strings.ja.xlf, src/MSBuild/Resources/xlf/Strings.ko.xlf, src/MSBuild/Resources/xlf/Strings.pl.xlf, src/MSBuild/Resources/xlf/Strings.pt-BR.xlf, src/MSBuild/Resources/xlf/Strings.ru.xlf, src/MSBuild/Resources/xlf/Strings.tr.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf, src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
Example:
https://user-images.githubusercontent.com/3347530/235191194-78d9e6bf-2f26-4310-a685-82139b69be66.mp4
I like this both because it highlights the TF more clearly _and_ because it saves two characters of line width.
=> Colorize TF instead of enclosing it in brackets

.vsts-dotnet.yml, eng/Versions.props
Explict call to `ComponentGovernanceComponentDetection@0` task (via `/eng/common/templates/steps/component-governance.yml` template) based on the branch name (so that this can be invoked for 'vs*' branches as well)
This will be breaking until we consume this arcade update: https://github.com/dotnet/arcade/commit/b1a9b866bd8e28f55a68b4048306bd1ccb3acb45, it's now flowing to MSBuild main in this PR: https://github.com/dotnet/msbuild/pull/8658
Testing the changes on: https://github.com/dotnet/msbuild/tree/vs-test-only
ADO run: (vs* branch, the CG step injected) https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7672204&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=424211a8-7b86-5e93-500e-ae39b50be1a7
https://github.com/dotnet/msbuild/pull/8697 …
=> [vs17.2] Customize opt-in for CG step

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
Fixes #8471 
Adds to Autocomplete
- EmitCompilerGeneratedFiles
- CompilerGeneratedFilesOutputPath
=> Add source generated files properties to project XSD

src/Build/Collections/WeakValueDictionary.cs, src/Build/Evaluation/ProjectRootElementCache.cs
It's fairly straightforward to demonstrate that if we reach this block, then it isn't in the _strongCache anyway, so this is entirely unnecessary work.
=> Remove unnecessary remove from ProjectRootElementCache

src/MSBuild/LiveLogger/AnsiCodes.cs, src/MSBuild/LiveLogger/LiveLogger.cs
The error and warning symbols may be rendered with different width on some terminals, resulting in misaligned output.
To make sure that the message text is always aligned we
1. Print the symbol.
2. Move back to the start of the line.
3. Move forward to the desired column.
4. Print the message text.
Windows terminal:
Windows cmd:
Fedora terminal:
I've also tried saving & restoring cursor position (VT100 functions 7 and 8) but that didn't fully work on Windows. The red X was still off.
=> [LiveLogger] Fix error and warning message alignment

src/Build/Microsoft.Build.csproj, src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj, src/Tasks/Microsoft.Build.Tasks.csproj
System.Security.Principal.Windows is inbox since net6.0
System.Net.Http is inbox since netcoreapp2.0
System.Reflection.Metadata is inbox since netcoreapp2.0
System.Threading.Tasks.Dataflow is inbox since netcoreapp2.0
Leave System.Net.Http package references which aren't needed as they underlying assembly is inbox on both .NETFramework and .NETCoreApp, to avoid component governance alerts about downloading (but not using) an old version.
By avoiding the dependencies, we minimize the dependency graph and with that the attack surface.
cc @MichaelSimons (removes netstandard1.x dependencies)
=> Avoid package dependencies on inbox libraries (second attempt)

eng/Versions.props, global.json
Fixes - bunch of CVEs (up to 29): https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted?_a=alerts&typeId=15231688&alerts-view-option=active
We need to update runtime from 6.0.2 to at least 6.0.12 (this is taking it to 6.0.16 - as part of [SDK 6.0.408](https://dotnet.microsoft.com/en-us/download/dotnet/6.0))
=> [vs17.2] Update sdk version to bump pulled runtime

documentation/wiki/ChangeWaves.md, src/Framework/ChangeWaves.cs, src/Shared/Constants.cs, src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs, src/Tasks.UnitTests/HintPathResolver_Tests.cs, src/Tasks/AssemblyDependency/AssemblyFoldersExResolver.cs, src/Tasks/AssemblyDependency/AssemblyFoldersFromConfig/AssemblyFoldersFromConfigResolver.cs, src/Tasks/AssemblyDependency/AssemblyFoldersResolver.cs, src/Tasks/AssemblyDependency/AssemblyResolution.cs, src/Tasks/AssemblyDependency/CandidateAssemblyFilesResolver.cs, src/Tasks/AssemblyDependency/DirectoryResolver.cs, src/Tasks/AssemblyDependency/FrameworkPathResolver.cs, src/Tasks/AssemblyDependency/GacResolver.cs, src/Tasks/AssemblyDependency/HintPathResolver.cs, src/Tasks/AssemblyDependency/RawFilenameResolver.cs, src/Tasks/AssemblyDependency/ReferenceTable.cs, src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs, src/Tasks/AssemblyDependency/Resolver.cs, src/Tasks/InstalledSDKResolver.cs
Fixes #8634
For SDK/workload references, the SDK is currently already passing relevant metadata such as `AssemblyVersion` and `PublicKeyToken`, so there is no need for RAR to open these files and parse their .NET metadata tables to get this information. Also, barring corrupted installs, these files are guaranteed to exist on disk so there is no need for RAR to do any I/O on them (file-exists, get-time-stamp, ..)
Tweaked RAR to trust the item metadata passed by the SDK. The feature is gated on the presence of the `FrameworkReferenceName` metadatum which is not documented and is used only by the relevant SDK tasks, to my best knowledge.
SDK does not specify the `Culture` component of assembly names so it's assumed to be `neutral`. This has passed all relevant validation so far. If …
=> [RAR] Don't do I/O on SDK-provided references

src/Build/Definition/ProjectCollection.cs, src/Build/Utilities/ReaderWriterLockSlimExtensions.cs
Fixes [AB#1811627](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1811627) (@davkean will likely file a GH issue)
`ProjectCollection` uses a `ReaderWriterLockSlim` but it never takes it just for reading with `EnterReadLock`. Instead it uses `EnterUpgradeableReadLock`, which effectively provides mutual exclusion when reading data and results in unnecessary contention. The reason cited in comments revolves around reentrancy but calling `EnterReadLock` while already holding the write lock is perfectly legal with `LockRecursionPolicy.SupportsRecursion` so there's no need to mutually exclude readers.
- Made `ProjectCollection` use plain read lock instead of the upgradeable one.
- Simplified the `IDisposable` holder structs by removing the unneeded …
=> Optimize locking in ProjectCollection (low risk)

Directory.Build.props
Now that #8688 is in, we no longer get value from the SDK pre-cache. The cost of reading the cache is >50 ms per project, which typically makes it the most expensive part of RAR.
Trace from MSBuild command line build:
=> [Own build] Don't use AssemblyInformationCachePaths

documentation/wiki/ChangeWaves-Dev.md
When sending a link to this page I wanted this crosslink to exist.
=> Link from ChangeWaves-dev to ChangeWaves

eng/Packages.props, eng/Versions.props, src/Directory.Build.targets, src/MSBuild/MSBuild.csproj, src/StringTools.Benchmark/StringTools.Benchmark.csproj
Fixes: 5 remaining CG issues on vs17.2 (https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted?_a=alerts&typeId=15231688&alerts-view-option=active)
Couple packages were flagged by CG - updating those,
Plus taking inspiration from https://github.com/dotnet/msbuild/pull/7538 to override the transitive stale packages pull
Those changes are NOT to be merged into 17.4 (as those are already managed by dependabot there https://github.com/dotnet/msbuild/blob/vs17.4/eng/dependabot/Packages.props)
=> [vs17.2] Update vulnerable packages versions

src/Build/Instance/ProjectInstance.cs, src/Build/Instance/ProjectItemDefinitionInstance.cs, src/Build/Instance/ProjectItemInstance.cs
Fixes #8673
High memory allocations in CopyOnWritePropertyDictionary ImmutableDictionary was reported by partners.
Use `CopyOnWritePropertyDictionary.ImportProperties` in obvious places as oppose to `CopyOnWritePropertyDictionary.Set` in loop.
Unit tests. Local. Perf measure.
=> Use CopyOnWritePropertyDictionary.ImportProperties for batching

eng/Versions.props, global.json
Fixes - failing signing validation step of vs17.2 build
vs17.2 Signing Validation is failing (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7763789&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=cdcedd1f-8008-523f-9da1-cc35fbfef9a3):
```
(...)
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.23221.7\tools\SdkTasks\SigningValidation.proj(0,0): error : Version 6.0.311 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.10.0.26302. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.
(...)
```
Inspecting the arcade scripts - the version used is comming from https://github.com/dotnet/msbuild/blob/vs17.2/eng/common/sdk-task.ps1#L67 and can be …
=> [vs17.2] Expliciltly require matching version of VS for signing validation step

src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs, src/Build/Definition/Project.cs, src/Build/Evaluation/Evaluator.cs, src/Build/Instance/ProjectInstance.cs
When `ProjectOptions.DirectoryCacheFactory` was introduced only `Project` support was implemented. `ProjectInstance` ignores the field and while currently not a required functionality, it is a minor API gap.
Made `ProjectInstance` use `DirectoryCacheFactory` if passed in `ProjectOptions`.
- Removed `Project.GetDirectoryCacheForEvaluation` and instead plumbed the factory all the way down to `Evaluator`.
- Tweaked the unit test project to use `Condition` on `Import` rather than on `ItemGroup` to not expose differences between `Project` and `ProjectInstance` in the treatment of conditional items.
Existing updated unit test.
=> Close API gap where ProjectInstance ignores ProjectOptions.DirectoryCacheFactory

eng/Versions.props, global.json
Fixes broken 17.2 build
vs17.2 Signing Validation is failing (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7772042&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=cdcedd1f-8008-523f-9da1-cc35fbfef9a3):
```
##[error](NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) {"$id":"1","innerException":null,"message":"The resource RoslynTools.MSBuild.17.0.nupkg for package 'RoslynTools.MSBuild 17.0' doesn't exist. Did you mean roslyntools.msbuild.17.0.0.nupkg?","typeName":"Microsoft.VisualStudio.Services.NuGet.WebApi.Exceptions.PackageSubresourceNotFoundException, Microsoft.VisualStudio.Services.NuGet.WebApi","typeKey":"PackageSubresourceNotFoundException","errorCode":0,"eventId":3000}
```
So updating to 17.2.1 - to align the build tooling with vs17.4 branch
=> [vs17.2] Update the build tools

src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs, src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs, src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs, src/Build/Evaluation/LazyItemEvaluator.cs
Related to #8673
When analyzing traces from VS Orchard evaluation I have noticed few places which are easy to optimize by using `ImmutableArray` instead of `ImmutableList`.
`ImmutableArray` is almost always better in patters `loop {mutate by builder}; ToImmutable` since it is struct, allocates less, and have faster enumerator. 
There are many places where using `ImmutableArray` instead of `ImmutableList` would render better performance. I however limit changes only on places which sticks out from memory traces as non-negligable.
Local. PR gate.
Overall gain will be small, in percent's of overall allocations, but given relatively simple and safe changes, I think it is good tradeoff.
=> Improve allocations in evaluations by using ImmutableArray here and there
