dotnet/msbuild

.vsts-dotnet.yml

Fix internal official builds by updating to `MicroBuildBuildVSBootstrapper@3`, which has a fix for some internal VS infrastructure stuff.
Passed on `exp/` in https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7795060

Update to latest VSBootstrapper task

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Add missing p2p annotations for BuildGenerateSources, BuildCompile, BuildLink, FindInvalidProjectReferences
This change adds some missing `ProjectReferenceTargets` items which help with more correct graph construction.

Add missing p2p annotations for BuildGenerateSources, BuildCompile, BuildLink, FindInvalidProjectReferences

---

.vsts-dotnet-ci.yml
src/Utilities.UnitTests/ToolTask_Tests.cs

Move (only) the `Windows Full Release (no bootstrap)` leg to the `windows.vs2022preview.amd64.open` pool, which has Visual Studio 17.6 on it already.
This will unblock #8674 by avoiding https://github.com/dotnet/sdk/issues/32691; the `MSBuild.exe.config` binding redirects in the 17.6 VS will keep the current versions working for the moment.
Internal test run, since it requires splitting definitions for internal vs external: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7804696&view=logs&j=1522e9b9-b859-5e5f-ec86-a68fc9508baf&t=a8d37b2d-1a39-51d6-c11e-8665c8c9811e

Move release build leg to dnceng pool

---

eng/Versions.props

Now that 17.6 is released to nuget.org, update to the GA version of the packages as a baseline.

Update package baseline to 17.6 GA version

---

src/Tasks/ManifestUtil/SecurityUtil.cs
src/Tasks/ManifestUtil/mansign2.cs

Fixes AB#1822000
Work item (Internal use): [AB#1822000](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1822000/)
ClickOnce does not enforce SHA256 digest algo during RFC3161 timestamping of signed artifacts. For binaries, this means that depending on the version of signtool used, SHA1 is selected as the default digest algorithm.
ClickOnce signing task has been updated to default to sha256 as the timestamping digest algo for both binary and manifest signing. For binaries, this is done by passing the /td switch to signtool.exe. For the XML manifests, this is done by passing the sha256 algo id to the CryptRetrieveTimeStamp API. 
Debugged thorough the modified code.
CTI validated signing scenarios with a private.

Default to sha256 for RFC3161 timestamping of ClickOnce artifacts

---

src/Build/Evaluation/IItem.cs

Per offline conversation with rainersigwald, these comments are just wrong and should be fixed. (I'd asked because our implementations return string.Empty instead of null if a key does not exist.)

Correct IItem comment

---

eng/Packages.props

Fixes the build when `UsingToolMicrosoftNetCompilers=false`, which I've been using to work around the mismatch between a new SDK and VS but the old Toolset package (pending #8674).

Explicitly mention Microsoft.Net.Compilers.Toolset version

---

src/Utilities.UnitTests/ToolTask_Tests.cs

Fixes [#8750](https://github.com/dotnet/msbuild/issues/8750)
[PowerShell](https://github.com/dotnet/msbuild/blob/main/src/Utilities.UnitTests/ToolTask_Tests.cs#L902) sleep is used for windows - that however prooves to be a bit unstable in CI
Use cmd.exe 
/azp run for several times. It passed.

Enable ToolTaskThatTimeoutAndRetry test after change powershell.exe to cmd.exe

---

.vsts-dotnet.yml
eng/Versions.props

Cherrypicking https://github.com/dotnet/msbuild/pull/8780
> Fix internal official builds by updating to `MicroBuildBuildVSBootstrapper@3`, which has a fix for some internal VS infrastructure stuff.

[vs17.2] Cherrypicking VSBootstrapper task update

---

src/Shared/FileMatcher.cs

Seen while investigating [AB#1826498](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1826498)
The output of `GetAccessibleFileSystemEntries` is already an `IReadOnlyList<string>`, and each caller gets its own copy of that object. We do not need to produce another copy of it via the `ToArray` call that this commit removes.

Remove redundant collection copy

---

src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs

Fixes [AB#1827935](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1827935)
In cases when `LazyItemEvaluator<>.IncludeOperation.SelectItems` returns an empty array, there's no need to allocate the `ImmutableArray<>.Builder` class instance.
This change makes the allocation occur only when needed.
This was identified as contributing to GC pauses via GCPauseWatson.
This change also null annotates the file.

Don't allocate unused ImmutableArray builder

---

src/Shared/FileMatcher.cs

Fixes [AB#1826498](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1826498)
Per the [Performance Best Practices wiki](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/24181/Garbage-Collection?anchor=%E2%9C%94%EF%B8%8F-**do**-prefer-%60tolist%60-over-%60toarray%60-when-%22realizing%22-temporary-linq-queries), short-lived materialised versions of enumerations should be made using `ToList` rather than `ToArray`, as the latter commonly involves an additional copy of the results in order to trim unfilled entries from the end of the collection. When results are short lived &mdash; as they are in the code changed here &mdash; that extra copy only creates extra work and GC pressure.
This issue was flagged as a top issue by GCPauseWatson.

Use ToList over ToArray

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Fixes #2359
The help text for verbosity makes it sound like it affects file loggers, which isn't true. This makes that more clear.

Clarify help text for verbosity Resolves #2359

---

eng/Version.Details.xml

Contributes to https://github.com/dotnet/source-build/issues/3043
Declaring the `System.Configuration.ConfigurationManager` dependency in `Version.Details.xml` will allow source-build to replace the currently used `7.0.0` version with the `n-1` version coming from previously source-built artifacts in the product / VMR build.
Without this change, once repo PvP is enabled, the source-build of `msbuild` will fail in the product build.
- added an entry for `System.Configuration.ConfigurationManager: 7.0.0` to `Version.Details.xml`

add ConfigurationManager to Version.Details

---

src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs
src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs
src/Build/Evaluation/LazyItemEvaluator.cs

Fixes [AB#1827934](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1827934)
The `EvaluatorData` class accepts a delegate via which it may query for items of a given item type. GCPauseWatson identified the per-instance allocation of these delegates as contributing to GC pauses.
By passing `IReadOnlyDictionary<string, LazyItemList>` instead, `EvaluatorData` can perform the lookup itself directly via that interface, rather than having a heap-allocated delegate per instance.
Existing unit tests and eyeballs.
Credit to @davkean for the proposed fix here.

Avoid delegate allocation in EvaluatorData constructor

---

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
src/Build/Evaluation/ConditionEvaluator.cs

Fixes [AB#1824943](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1824943)
In order to parse the name of a property from an MSBuild expression, this method used a regular expression to parse a simple pattern, which results in significant amounts of allocations as identified by GCPauseWatson.
The actual pattern used is very simple and can be achieved regex.
This change extracts the parsing to a helper function and adds a unit test for it. I validated that the test passed with the prior implementation, then converted it to avoid regex allocations altogether.
While at it I null annotated `ConditionEvaluator`. That was done in its own commit, if you want to review the changes separately.

Reduce allocations in ConditionEvaluator.UpdateConditionedPropertiesTable

---

src/Build/Evaluation/EvaluatorMetadataTable.cs
src/Build/Evaluation/IMetadataTable.cs
src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs

Fixes [AB#1826604](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1826604)
This change allows the metadata dictionary to be constructed with the expected size, rather than some default size which is then subject to resizing (and increased GC pressure).
This code path was identified as a top contributor to GC pauses by GCPauseWatson.
Also null annotated the types involved (in a separate commit).

Reduce allocations due to dictionary resizing

---

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/ProjectInterpretation.cs

Add support for ShouldUnsetParentConfigurationAndPlatform in solution-based graph construction
This is a continuation of #8625, where I didn't implement this feature of `AssignProjectConfiguration`

Add support for ShouldUnsetParentConfigurationAndPlatform in solution-based graph construction

---

src/Tasks/AssemblyRegistrationCache.cs
src/Tasks/DependencyFile.cs
src/Tasks/ResGenDependencies.cs
src/Tasks/ResolveComReferenceCache.cs
src/Tasks/StateFileBase.cs
src/Tasks/SystemState.cs

Related to #8827
Some of the comments mentioning `BinaryFormatter` are misleading. Most of the classes don't need to be serializable. The only exception is `PortableLibraryFile` which is serialized cross-domain on .NET Framework.
Removed `[Serializable]` and the comment about `BinaryFormatter`-based calls from several classes. Left it on `PortableLibraryFile`, ifdef'ed to .NET Framework builds only.
Experimental insertion confirmed that `PortableLibraryFile` is indeed marshaled cross-domain in some scenarios. Confirmed that it is the only such type by code inspection.

Remove references to BinaryFormatter from comments

---

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceCacheSerialization.cs
src/Tasks.UnitTests/AssemblyRegistrationCache_Tests.cs
src/Tasks.UnitTests/ResolveComReference_Tests.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
src/Tasks/RegisterAssembly.cs
src/Tasks/ResGenDependencies.cs
src/Tasks/ResolveComReference.cs
src/Tasks/StateFileBase.cs
src/Tasks/SystemState.cs
src/Tasks/UnregisterAssembly.cs

Contributes to #8635
With #8688 we no longer need to cache data on immutable framework files on disk as obtaining this information is cheap and does not require I/O.
Made `SystemState` (the RAR cache) not add such files to the per-instance dictionary. This dictionary is serialized to disk as `<project-file>.AssemblyReference.cache` so the change effectively makes the cache file smaller, saving on serialization and deserialization time.
Also refactored `DeserializeCache` into a generic method instead of taking a `Type` parameter.
For a simple ASP.NET Core app with one project reference and one package reference, the size of the cache file is reduced from 142 kB to 2 kB. Projects with no references other than the SDK will not have the cache file created at all.
Existing unit tests, manual …

Don't save data on immutable files to per-project disk cache

---

src/Build.UnitTests/Evaluation/UsedUninitializedProperties_Tests.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Evaluation/Expander.cs

Fixes [AB#1824492](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1824492)
This class would always allocate a `Dictionary<string, IElementLocation>`, even when the object is unused. This allocation was showing up as contributing to GC pauses by GCPauseWatson.
To reduce those allocations, we defer such an allocation until it is actually needed.
Added unit tests.

Reduce allocation in UsedUninitializedProperties

---

src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

This is more future-proof than the fixed link we had before.

Switch to aka.ms link for BinaryFormatter warning

---

src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
src/Build/Graph/GraphBuilder.cs

Add solution global properties for solution-based graphs
More in the vein of #8625 and #8855. Getting sln-based graph builds to be more aligned with non-graph sln builds.

Add solution global properties for solution-based graphs

---

.vsts-dotnet.yml
eng/Versions.props

Fixes #8838
MSBuild has had localization for 17.2 only, while running it in multiple release branches + main and targetting all changes to main.
Requested separate localization setup for main and release branches and created conditioned pipeline jobs that ran for main and latest release branch with proper localization package ids
FYI @cristianosuzuki77

Add localization setup for main and release branches

---

.vsts-dotnet.yml
eng/Versions.props

The expressions in #8887 were not proper ADO syntax
Fixed the ADO syntax

Fix expressions for OneLocBuild

---

src/Tasks/Microsoft.Common.props
src/Tasks/Microsoft.Common.targets

Fixes #8876
The SDK has logic it wants to run immediately after importing Directory.Build.props. This adds a hook for that so the SDK doesn't have to manually import it, disable importing Microsoft.Common.props, then re-implement part of it.

Add hook for a post-Directory.Build.props import

---

global.json

Fixes about a dozen CVEs ([internal link] https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted?_a=alerts&typeId=8799614&alerts-view-option=active)
We need runtime 7.0.5 -> 7.0.7 bump, this comes with [SDK 7.0.304](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)
(7.0.2xx channel is not updated with this relase)

Update sdk version to bump pulled runtime

---

eng/Version.Details.xml

Contributes to https://github.com/dotnet/source-build/issues/3043.
Declaring the `System.Security.Cryptography.Pkcs` dependency in `Version.Details.xml` will allow source-build to replace the currently used `7.0.0` version with the `n-1` version coming from previously source-built artifacts in the product / VMR build.
Without this change, once repo PvP is enabled, an ref pack of `7.0.0` will be bundled with the produced package, causing build time exceptions for consumers that try to load in the dependency.
This is a follow-up to https://github.com/dotnet/msbuild/pull/8818 - the change should've been included with the mentioned PR but the issue described was originally missed during testing.
- added an entry for `System.Security.Cryptography.Pkcs: 7.0.0` to `Version.Details.xml`.

add Security.Cryptography to Version.Details

---

eng/Versions.props
eng/dependabot/Packages.props

Fixes CVE-2023-29331
[CVE-2023-29331](https://github.com/advisories/GHSA-555c-2p6r-68mm)

[vs17.4] Update vulnerable System.Security.Cryptography.Pkcs

---

.editorconfig
eng/Packages.props
eng/Version.Details.xml
eng/Versions.props
global.json
src/Tasks/Microsoft.Build.Tasks.csproj

Fixes CVE-2023-28260
Same change as this bump on main https://github.com/dotnet/msbuild/pull/8894

[vs17.6] Update sdk version to bump pulled runtime

---

src/MSBuild.UnitTests/LiveLogger_Tests.cs
src/MSBuild.UnitTests/Snapshots/LiveLogger_Tests.DisplayNodesOverwritesWithNewTargetFramework.verified.txt
src/MSBuild.UnitTests/Snapshots/LiveLogger_Tests.DisplayNodesShowsCurrent.verified.txt
src/MSBuild/LiveLogger/LiveLogger.cs
src/MSBuild/LiveLogger/Terminal.cs

The root cause of #8781 is that the optimize-output-by-skipping-identical-characters logic is not aware of escape sequences, so it goes horribly awry when the replacing line differs after the first escape sequence.
Instead, apply the previous logic only if there are no escape sequences; if there are, replace the entire line.
If this proves to cause too much flicker or perform slowly, we could implement escape-sequence-aware truncation, length, and comparison, but we can wait for feedback to that effect.

Overwrite colorized lines instead of incremental updates

---

eng/Versions.props
src/Package/MSBuild.VSSetup/files.swr

OptProf failing on vs17.6 after recent changes
Cherrypicked https://github.com/dotnet/msbuild/pull/8737

[vs17.6] Dont ngen taskhost Fixes our lack of optprof data (#8737)

---

src/Build/Instance/ProjectInstance.cs

Fixes [Bug 1835789](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1835789): [GCPauseWatson] MSBuild: ProjectInstance.DeepClone resizing an ItemDictionary because its passing the wrong capacity (31 MB/s)
The ProjectInstance copying constructor creates an item dictionary using an initial capacity of the number of _item types_ instead of the number of items are being added to the collection. This is causing it to be resized.

ProjectInstance: create a ProjectItemInstance dictionary of the correct size in copying constructor

---

src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceCacheSerialization.cs
src/Tasks.UnitTests/RARPrecomputedCache_Tests.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
src/Tasks/ResGenDependencies.cs
src/Tasks/StateFileBase.cs
src/Tasks/SystemState.cs

Fixes #8636
RAR uses a per-project disk cache to store data on referenced assemblies between executions. Per our common targets, for typical .NET projects the cache lives in `obj/{configuration}/{tfm}/{project-file-name}.AssemblyReference.cache`. The cache has currently non-deterministic contents, often containing more than what's actually needed. This is because items are effectively only added to and never removed from it.
Specific issues:
- If the RAR pre-cache is used via `AssemblyInformationCachePaths`, its contents is copied into per-project caches of all affected projects, making them deserialize this - typically large amount of - data on each execution. The pre-cache shipped with the SDK is 2 MB in size.
- The changes made in #8802 won't take effect until the developer cleans or …

Make RAR disk cache deterministic (serialize only what's actually used)

---

eng/SourceBuildPrebuiltBaseline.xml
eng/dependabot/Packages.props

Fixes CVE-2023-29331
[CVE-2023-29331](https://github.com/advisories/GHSA-555c-2p6r-68mm)
Version bump that should have been done by dependabot

Update System.Security.Cryptography.Pkcs (dependabot missed it)

---

src/Tasks/Microsoft.Common.CrossTargeting.targets

Enables NuGet targets to depend on source control information w/o workaround in Source Link packages.
Fixes https://github.com/dotnet/msbuild/issues/3294.

Add InitializeSourceControlInformation target to common cross-targeting targets

---

src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
src/Tasks.UnitTests/AssemblyDependency/StronglyNamedDependencyAppConfig.cs
src/Tasks/AppConfig/AppConfig.cs

Fixes [#ADO-1827728](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1827728)
Build of FullFW app was failing for customer with specific nonenglish characters  in path
Passing `Stream` to `XmlReader.Create` instead of path - that is not grace handled 
Explicit test added that failed before the fix

Support all codepages in path to app.config

---

src/Build.UnitTests/BinaryLogger_Tests.cs
src/Framework.UnitTests/AssemblyLoadBuildEventArgs_Tests.cs
src/Framework/AssemblyLoadBuildEventArgs.cs

Fixes #8784
Credit for finding the issue with serialization: @rokonec 
AssemblyLoad log messages were appearing in the VS output window based on file logger verbosity
AssemblyLoadBuildEventArgs  were not de/serializing it's `Importance`. The default value is `High`. So if another logger was consuming LowImportnace messages - including AssemblyLoadBuildEventArgs , then those were in multiprocess build transfered to main node, where their `Importance` jumped to `High` - and hence they got consumed by other loggers with lower verbosity (including VS output).

Fix AssemblyLoadBuildEventArgs transfering

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs

Fixes [#8205](https://github.com/dotnet/msbuild/issues/8205)
The following set of [item functions](https://learn.microsoft.com/en-us/visualstudio/msbuild/item-functions?view=vs-2022) allow to condition on or filter items based on metadata:
AnyHaveMetdataValue
HasMetadata
WithMetadataValue
These functions make it super simple to include items or condition based on metadata during evaluation time, without the need of batching (inside a target).
Over the last years I often wished that there would also be a WithoutMetadataValue item function so that the following pattern wouldn't require an extra target:
```
<Target Name="GetCompileFilteredItems">
<ItemGroup>
<CompileFiltered Include="@(Compile->WithMetadataValue('ExcludeFromX', ''))" />
<CompileFiltered …
```

Add WithoutMetadataValue

---

src/Build/BackEnd/BuildManager/BuildManager.cs

Fixes #8735, possibly #5689, #2845
There were race condition when `ProjectFinished` log message has been processed after `BuildResult` event. Even though `ProjectFinished` log message event is always send before `BuildResult` event from Node, because `ProjectFinished` is asyncronously routed by `LoggingService` reversing order can and do often happen.
Updating `_overallBuildSuccess` in one place when submission is considered to be done and assumed its final state.
Can't local repro.

Fix /warnaserror false positive overall success

---

src/Build/BackEnd/Components/Logging/LoggingService.cs

Fixes #8814
Messages coming from Nodes were handled differently than direct messages, for failing builds purposes.
Treating log messages from Node same as direct messages
Cant repro the local repro after changes

Fix ContinueOnError false positive

---

eng/Version.Details.xml

Contributes to dotnet/source-build#3528
When attempting to run an MSBuild command from an SDK that was source-built using the Mono runtime, the following exception occurs:
```
MSBUILD : error MSB1021: Cannot create an instance of the logger. Microsoft.Build.BackEnd.Logging.CentralForwardingLogger Could not load type of field 'Microsoft.Build.Shared.TypeLoader:_context' (4) due to: Could not load file or assembly 'System.Reflection.MetadataLoadContext, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
```
This is a regression caused by the change in https://github.com/dotnet/installer/pull/16637. That change allowed the msbuild repo to compile against the package versions that it defines rather than source-build overriding the package version …

Add more packages to Version.Details for source-build

---

src/Shared/ProcessExtensions.cs

This is more efficient, and doesn't require the OS (which could be a container image) to include the `pgrep` executable.
@Forgind @rainersigwald ptal.

ProcessExtensions: use BCL Process.Kill.

---

eng/sdl-tsa-vars.config

Enabling BinSkim scan over build artifacts in [Validate-DotNet pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=827)
Issue: https://github.com/dotnet/arcade-services/issues/2647
@andriipatsula will merge this once the change in the pipeline is tested. After the validation pipeline run you can expect a TSA email with some alerts from the BinSkim scan

Enable BinSkim scan in nightly validation

---

src/Tasks/Copy.cs

Fix https://github.com/dotnet/msbuild/issues/3891
Ctrl-C calls Cancel() on the task. That signals the cancelation token we [pass into the ActionBlock](https://github.com/dotnet/msbuild/blob/92f3600820b5d5da87e4a0dcf141c709d0817a03/src/Tasks/Copy.cs#L561) which throws an exception that we do not catch.
Note: the exception is caught in two other places; those are still required as they would otherwise be caught in the generic catch there and log and error.
No unit test here is really feasible without exceptional efforts.

Fix copy cancelation

---

src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs

Fixes #8816
As discussed in #8816 we are trying the simplest solution, i.e. do not fail when LoggingContext is not yet properly initialized.
Simple IF
Local.
@KirillOsenkov Can you please test if this PR addresses #8816 issue properly?

Send AssemblyLoadBuildEventArgs only for valid LoggingContext

---

src/Build/Instance/ProjectItemInstance.cs

Tiny improvement to the hash code calculation perf - ItemSpec is just EscapingUtilities.UnescapeAll(_includeEscaped), which is a simple deterministic transform so we can just use the string.
Added a comment to explain why we can't easily hash in something about the metadata. This means that all items with the same item spec continue to have the same hash code, which can cause degenerate performance.

improve TaskItem hashcode

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Resources/Constants.cs
src/Framework.UnitTests/OperatingSystem_Tests.cs
src/Framework/OperatingSystem.cs
src/MSBuild.UnitTests/XMake_Tests.cs

Fixes #5982
Expose methods added in .Net 5.0. Create alternate stand-in for net471.
- Add `Microsoft.Build.Framework.OperatingSystem` as stand-in substitute for net471. The class assumes that only Windows is supported.
- Add unit tests for `Microsoft.Build.Framework.OperatingSystem`.
- Modify Constants.cs to static methods either from `System.OperatingSystem` or from `Microsoft.Build.Framework.OperatingSystem`.
- Add unit tests for `IsOSPlatform` property function
Tested on windows 11 and macOS 12. tested by running full suite of unit test.

Expose static methods from System.OperatingSystem

---

src/Build/Evaluation/Evaluator.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1848255
On .NET Framework this boxes an enum, and allocated 600 MB in a trace I was looking at.

Avoid boxing enum

---

eng/BootStrapMSBuild.targets
src/Tasks/Microsoft.Common.CurrentVersion.targets

I copy/pasted a sample usage of WriteOnlyWhenDifferent--the one with the casing `True`, which sparked a discussion over what MSBuild style should be. It should be lowercase.

Unify casing for boolean true in targets

---

documentation/wiki/ChangeWaves.md
src/Tasks.UnitTests/Hash_Tests.cs
src/Tasks/Hash.cs

Fixes (internal) https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1645155/
Moving away from crypthographicaly weak `SHA1` to `SHA256` for Hash task
`SHA1` - `SHA256`
Existing tests

Moving from SHA1 to SHA256 for Hash task

---

src/BannedSymbols.txt
src/Build.OM.UnitTests/Construction/ProjectImportElement_Tests.cs
src/Build.OM.UnitTests/Construction/ProjectImportGroupElement_Tests.cs
src/Build.OM.UnitTests/Construction/ProjectItemDefinitionGroupElement_Tests.cs
src/Build.OM.UnitTests/Construction/ProjectItemGroupElement_tests.cs
src/Build.OM.UnitTests/Construction/ProjectPropertyGroupElement_Tests.cs
src/Build.OM.UnitTests/Construction/ProjectTargetElement_Tests.cs
src/Build.OM.UnitTests/Construction/ProjectUsingTaskElement_Tests.cs
src/Build.OM.UnitTests/Construction/UsingTaskParameterGroup_Tests.cs
src/Build/Construction/ProjectChooseElement.cs
src/Build/Construction/ProjectElementContainer.cs
src/Build/Construction/ProjectImportGroupElement.cs
src/Build/Construction/ProjectItemDefinitionElement.cs
src/Build/Construction/ProjectItemDefinitionGroupElement.cs
src/Build/Construction/ProjectItemElement.cs
src/Build/Construction/ProjectItemGroupElement.cs
src/Build/Construction/ProjectOtherwiseElement.cs
src/Build/Construction/ProjectPropertyGroupElement.cs
src/Build/Construction/ProjectRootElement.cs
src/Build/Construction/ProjectTargetElement.cs
src/Build/Construction/ProjectTaskElement.cs
src/Build/Construction/ProjectWhenElement.cs
src/Build/Construction/UsingTaskParameterGroupElement.cs
src/Build/Definition/Toolset.cs
src/Build/Evaluation/Evaluator.cs
src/Directory.Build.targets
src/Shared/ReadOnlyCollection.cs

Performance improvement with noticeable impact when using static graph in large repos.
~10% reduction in static graph construction time in a specific large repo.
No.
Automated tests, manual runs on reporting repo showing noticeable improvement.
Low.
Avoid OfTypeIterators when enumerating project xml children
In a recent profile of a graph construction, it was observed that a large amount of boxing was happening for `ProjectElementSiblingEnumerable`. This change simplifies how xml children are enumerated by adding an internal `ChildrenEnumerable` property which directly exposes the `ProjectElementSiblingEnumerable` which should avoid boxing, at least in some code paths (the public API makes it hard to avoid everywhere...).
Additionally, a very common usage of enumerating children was to do …

Avoid OfTypeIterators when enumerating project xml children

---

src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
src/Build/Graph/ProjectInterpretation.cs
src/Tasks/Microsoft.Common.CurrentVersion.targets

Allow dynamic platform resolution for projects not mentioned in a solution.
Enables adoption of dynamic platform resolution for dev-desktop scenarios in a large internal repo.
No.
This was tested in the VS repo on the VC sln which covers lots of scenarios
Low--feature has low adoption because of sticking points like this, so blast radius of regression is low.
Currently we turn off dynamic platform resolution for a whole solution if a single project in the solution is assigned a configuration. This is problematic as some projects are outside of the scope of the solution but still have certain targets that run on them that are architecture specific. These projects will build as the wrong architecture because no configuration is defined and no platform negotiation takes place.
I removed the …

Removing sln level turn off of setplatform feature

---

src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs
src/MSBuild/XMake.cs

Fixes #8595
Embedding of large amount of files to binlog can lead to OutOfMemoryException due to memory pressure. It also causes LOH fragmentation and Gen2 collections. 
Large builds cannot use the binary logger due to an OOM crash.
Yes, in 16.8 (#5718).
Before:
After:
Medium--adds new filesystem dependencies which could fail, but is similar to the pre-16.8 mechanism and tries to be tolerant of failures.
This change reverts in-memory operations and uses temp file for embedded files. The file is now stored in temporary directory (instead of binlog target directory) to avoid problems with file watchers. There might be possible another optimizations, but goal of this PR is to unblock our partners. We can optimize further in separate PR.

Fix of OutOfMemoryException when embedding large amount of files to binlog

---

eng/BootStrapMSBuild.targets
eng/Build.props

Reverts dotnet/msbuild#8498 which should no longer be necessary now that 17.6 has rolled out broadly--it's everywhere I checked (official build, hosted agents, the pre queue).

Reënable static graph restore

---

src/MSBuild/LiveLogger/Terminal.cs

Fixes #9030 by capturing the stdout writer only _after_ setting the console encoding to support Unicode. The Console encoding setter works by [discarding its internal writer and creating a new one with the new encoding](https://github.com/dotnet/runtime/blob/ddbce91b241bcf0d7f33d04d33520659addd6dd7/src/libraries/System.Console/src/System/Console.cs#L140-L151).

TerminalLogger: Store output writer after setting it to UTF-8

---

src/Build.OM.UnitTests/Instance/ProjectItemInstance_Tests.cs
src/Build/Instance/ProjectItemInstance.cs
src/Framework/IMetadataContainer.cs
src/Framework/TaskItemData.cs
src/Shared/TaskParameter.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs
src/Utilities.UnitTests/TaskItem_Tests.cs
src/Utilities/TaskItem.cs

This reverts commit 1ff019aaa7cc17f22990548bb19498dfbbdebaec.
Fixes #
VS Insertion, [C++ Project System - PR: VC.ProjectSystem.VCProject.CachedProjectAutomation](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8047743&view=ms.vss-test-web.build-test-results-tab) fails since these changes. 
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullRequest/483186#1689247828

Revert "ResolveAssemblyReference CPU optimizations (#8916)"

---

src/Build.UnitTests/TestComparers/TaskRegistryComparers.cs
src/Build/Instance/TaskRegistry.cs

Changes extracted #8861
TaskRegistry tasks order depended on implicit ordering of tasks in internal Dictionary. This can manifest only when there are multiple tasks with same name registered and task invoking doesn't specify any parameters (arch, fw) - but then it can lead to hard to investigate bugs, so worth fixing
Added order id to task registrations, and use it for sorting fetched matches.
Existing tests

Make TaskRegistry tasks ordering deterministic (FIFO)

---

src/Build.UnitTests/BackEnd/TaskRegistry_Tests.cs
src/Build/Definition/ProjectImportPathMatch.cs
src/Build/Definition/Toolset.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Instance/TaskRegistry.cs

Fixes [ADO#1801351](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1801351) and [ADO#1801341](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1801341)
Reuses chunk of changes from https://github.com/dotnet/msbuild/pull/8861
TaskRegistry should be logically immutable after initialization and sharing is possible and ok, but there can be actual writes on first access which needs to be made thread safe
* Clarified some confusing comments
* Simplified TaskRegistry contract to allow only single shot initialization after which TaskRegistry is logically immutable
* `ProjectImportPathMatch` and `ToolSet` adjustment to better express immutability
Existing unit tests

Fix TaskRegistry mutability

---

src/MSBuild/LiveLogger/Terminal.cs

Preserve the constraint in code as well as in the commit message for #9035.

Comment for #9035

---

src/Build.UnitTests/ConsoleLogger_Tests.cs
src/Build.UnitTests/ConsoleOutputAlignerTests.cs
src/Build/Logging/BaseConsoleLogger.cs
src/Build/Logging/OptimizedStringIndenter.cs
src/Build/Logging/ParallelLogger/ConsoleOutputAligner.cs
src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs
src/Build/Microsoft.Build.csproj
src/Framework/IStringBuilderProvider.cs

Fixes [Bug 1828095](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1828095): [GCPauseWatson] MSBuild: BaseConsoleLogger.IndentString uses String.Split and StringBuilder to create an indented string
GCPauseWatson telemetry showed that `BaseConsoleLogger.IndentString` is responsible for allocating 1.99 GB of memory in VS at the 95th percentile.  This change aims to address that by replacing the multiple allocations of `String.Split` and `StringBuilder` with code that makes a single allocation of a right-sized string and then builds the indented string directly in the new string's buffer.
Benchmarking shows that -- depending on the target framework -- the new algorithm runs in 50-75% of the time of the code it replaces, and allocates 15-30% of the memory.  The optimizations have more …

Reduce runtime for and allocations from BaseConsoleLogger.IndentString

---

src/Tasks.UnitTests/CombineTargetFrameworkInfoProperties_Tests.cs
src/Tasks/CombineTargetFrameworkInfoProperties.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Fixes [#8320](https://github.com/dotnet/msbuild/issues/8320)
[CombineTargetFrameworkInfoProperties](https://github.com/dotnet/msbuild/blob/3c3b3c52a142f75532de216eb7a9b9c832d99da6/src/Tasks/CombineTargetFrameworkInfoProperties.cs#L42C16-L45)) is not handling null case of RootElementName. And empty RootElementName when UseAttributeForTargetFrameworkInfoPropertyNames is false.
Add the verification with the name of the parameter.
RootElementNameNotValid()

Improving the log of CombineTargetFrameworkInfoProperties fails with not valid RootElementName

---

src/Build/Construction/Solution/ProjectInSolution.cs
src/Build/Construction/Solution/SolutionFile.cs
src/Tasks/AppConfig/AppConfig.cs
src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs
src/Tasks/ManifestUtil/ApplicationManifest.cs
src/Tasks/ManifestUtil/AssemblyIdentity.cs
src/Tasks/ManifestUtil/DeployManifest.cs
src/Tasks/ManifestUtil/Manifest.cs
src/Tasks/ManifestUtil/ManifestReader.cs
src/Tasks/ManifestUtil/SecurityUtil.cs
src/Tasks/RedistList.cs
src/Utilities/PlatformManifest.cs
src/Utilities/SDKManifest.cs
src/Utilities/ToolLocationHelper.cs

Fixes #8972
https://github.com/dotnet/msbuild/pull/8931 fixed one instance of the issue with build issues caused by localized characters in OS paths.
This PR attempts to address the rest of the same unintended string -> uri conversion
Passing Stream to XmlReader.Create instead of path in order to prevent unintended string -> uri conversion
N/A

adjust XmlReader.Create to passed path with potentially invalid character

---

src/MSBuild.UnitTests/MSBuildServer_Tests.cs

Fixes #8956
https://github.com/dotnet/msbuild/issues/8956#issuecomment-1614321536
Improve waiting for the server is in use by the signal that a marker file is created by the build task.

Improve waiting for the server is in use by the signal that a marker file is created by the build task

---

src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
src/Build/Utilities/EngineFileUtilities.cs

Fixes #8984
When glob expansion runs in a target via ItemGroupIntrinsicTask, it implicitly invokes `EngineFileUtilities.GetFileListEscaped` for Excludes evaluation.
Traverse Exclude only if EngineFileUtilities.GetFileListEscaped wasn't called in order to avoid double traversal.
Existing cases cover this change.

Optimize exclude computation on ItemGroupIntrinsicTask target call

---

src/Build/Evaluation/Expander.cs
src/Build/Evaluation/ExpressionShredder.cs

Remove duplicated strings from Item and Property Function.  Intern these strings to reduce memory usage.
Strings used parsing Item and Property Function are duplicated many times, common offenders are "Contains", "Strings", and "true".  
Use the  Strings.WeakIntern() tool to cache the strings.  Since these are common strings which are shared among projects, use the global String store instead of the project specific store.
Profiled with the Visual Studio Memory Inspector.  This reduced 5-6mb of strings saved in our internal Repro of 200 projects.
There are still other places here duplicate string exists, this PR focus only on these locations.

Add StringIntern for Item and Property Functions.

---

src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs

Fix typo in ProjectCacheService.IsDesignTimeBuild leading to the value of BuildingProject not being checked.
This is a regression in #7833, probably due to bad copy/paste while refactoring.
Thanks @davkean for spotting this bug!

Fix typo in ProjectCacheService.IsDesignTimeBuild leading to the value of BuildingProject not being checked

---

src/Build.OM.UnitTests/Instance/ProjectItemInstance_Tests.cs
src/Build/Instance/ProjectItemInstance.cs
src/Framework/IMetadataContainer.cs
src/Framework/TaskItemData.cs
src/Shared/TaskParameter.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs
src/Utilities.UnitTests/TaskItem_Tests.cs
src/Utilities/TaskItem.cs

#8916 broke some .NET Framework scenarios and was reverted. This PR is a redo of the change with the bug fixed. It turned out that the destination of the optimized `CopyMetadataTo` may be a transparent proxy, typically a `TaskItem` object living in another appdomain, which does not work well with Linq. The fix and the test coverage are in their own commits.
Low-hanging fruit is showing in RAR performance profiles.
1. Avoided constructing `AssemblyName` on a hot path as the constructor makes expensive Fusion calls on .NET Framework. The problematic code was introduced in #8688.
2. Added a metadata bulk-set operation to the internal `IMetadataContainer` interface. Calling `SetMetadata` for more than a couple of metadata is slow if `ImmutableDictionary` is used as its backing storage. RAR is …

ResolveAssemblyReference CPU optimizations (redo)

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs

Fixes #9061
#9061
This is the proposal of option a) (disabling `TerminalLogger` entirely for `dotnet test`)
The approach b) (disabling `TerminalLogger` only for the test part of the `dotnet test`) turns out to be not 'hardenable' enough for multi-project solutions due to the fact that MSTest and MSBuild race with writing to a single console and MSBuild might not be quick enough to teporarily pause it's updates.
It looks workable for simple solutions - sample just for reference:

Skip TerminalLogger in context of dotnet test

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

When passed an invalid value, like "off", we were crashing instead of emitting an
error, because the resource hadn't been created.
```sh-session
$ .dotnet/dotnet ./artifacts/bin/MSBuild.Bootstrap/Debug/net8.0/MSBuild.dll -tl:off
MSBuild version 17.8.0-dev-23377-01+fd4d0e5ca for .NET
MSBUILD : error MSB1065: Terminal logger value is not valid. It should be one of 'auto', 'true', or 'false'. 
Switch: off
```

Resource for invalid -tl value

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

the dev rule is incorrect.
The addition was:
```
<data name="NameInvalid" Visibility="Public">
<value>MSBUILD: error MSB5016: The name "{0}" contains an invalid character "{1}".</value>
<comment>
{StrBegin="MSBUILD : error MSB5016: "}
</comment>
</data>
```
The source string does not have the same spaces as the rule asks for.
It should be like this:
```
<data name="NameInvalid" Visibility="Public">
<value>MSBUILD : error MSB5016: The name "{0}" contains an invalid character "{1}".</value>
<comment>
{StrBegin=" MSBUILD : error MSB5016: "}
</comment>
</data>
```

Update invalid localized string

---

src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_SucceededWithWarnings.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_SucceededWithWarnings.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_SucceededWithWarnings.Windows.verified.txt
src/MSBuild.UnitTests/TerminalLogger_Tests.cs
src/MSBuild/TerminalLogger/AnsiCodes.cs
src/MSBuild/TerminalLogger/TerminalLogger.cs

We would like to adjust the warning and error output to make it easier on the eye and draw attention to the most important parts.
- Removed the ❌ and ⚠ symbols
- Made the lines use multiple colors: red/yellow for the text `error`/`warning` and the code, bold for file name, and default for everything else
Before (Windows "Campbell"):
Before (Windows "Solarized Dark"):
After (Windows "Campbell"):
After (Windows "Solarized Dark"):
Existing unit tests.

Terminal logger: Remove emojis and tweak warning/error colors

---

src/Tasks/ComReferenceInfo.cs

Fixes #8980
Analysis in #8980 seems to be correct. Have not found any evidence otherwise.
As recommended.
Unit tests coverage.
In theory something might be dependent on this erroneous  typelib registration, but I deem it very improbable, and if it still would be an bug on their side.

Do not register typelib in ComReferenceInfo

---

src/Build/CompatibilitySuppressions.xml

Suppressions were added due to APICompat limitation https://github.com/dotnet/sdk/issues/32922
That limitation was fixed - so suppressions are not needed anymore

Remove unneeded supressions

---

eng/Versions.props
global.json

Fixes #
N/A
CG alerts for vs17.7 recommends the following upgrade from 7.0.7 to 7.0.9.
- Microsoft.AspNetCore.App.Runtime.win-x64
- Microsoft.AspNetCore.App.Runtime.win-x86
- Microsoft.WindowsDesktop.App.Runtime.win-x64
- Microsoft.WindowsDesktop.App.Runtime.win-x86
Bump up dotnet version to 7.0.306 that has runtime 7.0.9.

Bump up dotnet version to fix CG alerts

---

src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
src/Build/Graph/GraphBuilder.cs

Fixes #9103
Tested using repro from linked bug.
Only single build for Project2:
And it uses the normalized platform value:

Fix project configuration case-mismatch issue for solution-based graph builds

---

NuGet.config

Fixes one of subitems from #8896
Remove the temporarily added [build feed from nuget.config](https://github.com/dotnet/msbuild/blob/29397b577e3ec0fe0c7650c3ab0400909655dc88/NuGet.config#L9) if it was added in the Update the PackageValidationBaselineVersion step

Remove the temporarily added build feed to 17.7

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

`SuggestedBindingRedirectsCacheFile` is enough for the target to support building incrementally. The RAR cache file is an implementation detail and should not be used as an input because it leads to executing the target unnecessarily when it changes for reasons unrelated to binding redirects.
Also, there does not seem to be a reason for running this target as part of design-time builds.
- Removed `ResolveAssemblyReferencesStateFile` from `GenerateBindingRedirects` inputs.
- Added a design-time build condition to the target, same as what `_GenerateSuggestedBindingRedirectsCache` uses.
- Verified that incremental and full build work as expected.
- Experimentally inserted the change into VS.

Remove ResolveAssemblyReferencesStateFile from GenerateBindingRedirects inputs

---

src/Build.UnitTests/BackEnd/LoggingConfigurationTelemetry_Tests.cs
src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/ConsoleLogger.cs
src/Build/Logging/FileLogger.cs
src/Framework/Telemetry/KnownTelemetry.cs
src/Framework/Telemetry/LoggingConfigurationTelemetry.cs
src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
src/MSBuild/CommandLineSwitches.cs
src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs
src/Shared/UnitTests/MockLogger.cs

Fixes part of #9063
See #9063 for requirements.
This PR address changes in msbuild only. SDK changes will be in different PR. This PRs are independent and could be merged in any order.
- introduce /tlp:default={true|false|auto} to signalize what is SDK intent of default behavior. Such default will achieve requirements of overriding default by user intent (arguments, env vars, rsp files)
- introduced `LoggingConfigurationTelemetry` containing info about logger settings
- locally
- existing and new unit tests

Terminal logger enablement by /tlp:default and related telemetry

---

src/Build/BackEnd/Components/Logging/LoggingService.cs

Fixes #9133
`NoWarn` has become flaky in all build configurations and frequently not suppresing  given warnings as errors.
During analysis I have found out our `LoggingService` is storing suppressed warning codes list by key which was weakly hashed with lots of possible collisions in expected input ranges.
When any project finishes its Warning configuration is removed from `LogginService warnign configs dictionary`, if just finished project have had collision key it removed the "other-guy" data.
Changed to compound key as `readonly record struct`. 
Since we have smallish numbers of warnings during build I do not believe it have measurable perf degradation.
- I have manually replied captured failing /bl to verify that there was indeed hash collision for this particular project warnings …

Fixing nowarn flakiness - warnings config is stored by compound key

---

eng/Version.Details.xml

When .NET is source-built with the mono runtime, there can be scenarios where MSBuild is made to attempt to load a reference assembly for System.Security.Permissions. See https://github.com/dotnet/source-build/issues/3571#issuecomment-1687979644 for such a scenario.
The reason a reference assembly exists in this case is because MSBuild has a reference to the 7.0.0 version of System.Security.Permissions. When building with source-build, it loads that reference from SBRP (which only contains reference assemblies) in order to fulfill compile time references. The problem is that the assembly is also getting included in the output. This should have been detected by poison leak detection [but that doesn't yet handle reference assemblies](https://github.com/dotnet/source-build/issues/2817).
The …

Flow live version of System.Security.Permissions for source-build

---

src/Build/BackEnd/Components/SdkResolution/SdkResolverManifest.cs

Contributes to [AB#1811625](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1811625)
Compiled regular expressions tend to run slower than interpreted ones on .NET Framework. Additionally, the cost of compiling is significant, especially on 64-bit.
Here's a benchmark running `IsMatch("Microsoft.NET.Sdk")` against the only SDK regex we ship inbox: `^(?i)vcpkg:.*`. Note that it does not include the compilation, which is an additional one-time cost.
Interpret `ResolvableSdkRegex` on .NET Framework. We made an analogous change to globbing some time ago in #6632.
Existing unit tests, targeted micro benchmark.
In the trace attached to the AzDO bug, this change eliminates 1/3 of the SDK resolution cost.

Don't compile SDK pattern regexes on .NET Framework

---

src/Utilities.UnitTests/ToolTask_Tests.cs
src/Utilities/Resources/Strings.resx
src/Utilities/Resources/xlf/Strings.cs.xlf
src/Utilities/Resources/xlf/Strings.de.xlf
src/Utilities/Resources/xlf/Strings.es.xlf
src/Utilities/Resources/xlf/Strings.fr.xlf
src/Utilities/Resources/xlf/Strings.it.xlf
src/Utilities/Resources/xlf/Strings.ja.xlf
src/Utilities/Resources/xlf/Strings.ko.xlf
src/Utilities/Resources/xlf/Strings.pl.xlf
src/Utilities/Resources/xlf/Strings.pt-BR.xlf
src/Utilities/Resources/xlf/Strings.ru.xlf
src/Utilities/Resources/xlf/Strings.tr.xlf
src/Utilities/Resources/xlf/Strings.zh-Hans.xlf
src/Utilities/Resources/xlf/Strings.zh-Hant.xlf
src/Utilities/ToolTask.cs

Use `ToolTask.TaskProcessTerminationTimeout` as termination time-out to kill external tool when it was cancelled or timed out.
Fixes #8545 
The protected property `ToolTask.TaskProcessTerminationTimeout` has been initialized but never used. Looks like it should be used as `timeout` on the following line when killing external tool on time-out or cancellation:
https://github.com/dotnet/msbuild/blob/main/src/Utilities/ToolTask.cs#L940
Use `ToolTask.TaskProcessTerminationTimeout` as termination time-out to kill external tool when it was cancelled or timed out.
All `ToolTask` unit test passed.
No new unit test created.

Use ToolTask.TaskProcessTerminationTimeout correctly

---

global.json

Fix the CVE-2023-35390  CVE-2023-38178  CVE-2023-38180   security issues. 
The effected packages are as follows:
Package name | Affected version | Patched version
-- | -- | --
Microsoft.NET.Build.Containers | <= 7.0.306 | 7.0.307, 7.0.400
Microsoft.AspNetCore.App.Runtime.win-arm64 | >= 7.0.0, <= 7.0.9 | 7.0.10
Microsoft.AspNetCore.App.Runtime.win-arm | >= 7.0.0, <= 7.0.9 | 7.0.10
Microsoft.AspNetCore.App.Runtime.win-x64 | >= 7.0.0, <= 7.0.9 | 7.0.10
Microsoft.AspNetCore.App.Runtime.win-x86 | >= 7.0.0, <= 7.0.9 | 7.0.10
[Microsoft.NetCore.App.Runtime.win-arm](https://www.nuget.org/packages/ Microsoft.NetCore.App.Runtime.win-arm) | >= 7.0.0, <= 7.0.9 | 7.0.10
Microsoft.NetCore.App.Runtime.win-arm | >= 7.0.0,<
Upgrade dotnet from 7.0.306 to 7.0.307 to fix the vulnerability.

Update dotnet runtime version

---

eng/Version.Details.xml

This fixes a portion of the assemblies described in https://github.com/dotnet/source-build/issues/3599 that are showing up as reference assemblies in the source-built SDK. The reason they're showing up as ref assemblies is the same reason that's described in https://github.com/dotnet/msbuild/pull/9158, which is a related issue.
It's not known whether the existence of these ref assemblies causes a functional issue as it does with https://github.com/dotnet/msbuild/pull/9158. But we do know that the source-built 7.0 SDK doesn't define these as ref assemblies but rather implementation assemblies. So to maintain parity with 7.0 and avoid potential risk, it's best to ensure these are represented as implementation assemblies in the output.
These are the assemblies that are fixed by these …

Add packages to Version.Details for source-build

---

src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs

Tests are failing for users who have `MSBUILDLIVELOGGER` or `MSBUILDTERMINALLOGGER` set.
Explicitly deleted these variables as part of test setup.
Unit tests.

Ignore pre-set env variables in TerminalLoggerConfiguration_Tests

---

eng/Signing.props
src/Build/Microsoft.Build.csproj
src/MSBuild/MSBuild.csproj
src/MSBuild/app.amd64.config
src/Package/MSBuild.VSSetup/files.swr

New dependencies added in #8726 weren't being deployed to VS. Ship them once (rooted in `MSBuild\bin`) and add binding redirects for the 64-bit versions to use it from there.

Ship BuildXL assemblies in our VSIX

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes #
[AB#1883274](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1883274)
Selenium.WebDriver Nuget pkg includes some of its publishable (copylocal) content in the None group. ClickOnce does not include items from this group currently for publishing.
Include copy-local items from the None group for ClickOnce publishing.
Ongoing.

[ClickOnce] Include content from None group for ClickOnce publishing

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

[AB#1846089](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1846089)
ClickOnce is not publishing copy-local content items from child projects. 
GetCopyToOutputDirectoryItems target gets the content items of transitive project dependencies. The itemgroup with these contents is however getting cleared. 
With this change, the content item group is being preserved and ClickOnce publishing target is now adding the TransitiveItemsToCopyToOutputDirectory itemgroup to its publish output.
Manual testing + Validation from CTI team of both customer repro and functional testing.

[ClickOnce] Fix publishing of content items from child projects.

---

.editorconfig
src/MSBuild/MSBuild.csproj
src/MSBuildTaskHost/MSBuildTaskHost.csproj

RC1 introduced a [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph) related to RID graph. It also appears to have enabled new analyzers by default, which results in a large number of warnings in our tree.
- Add `<UseRidGraph>true</UseRidGraph>` to opt into the old RID behavior.
- Make IDE0290, IDE0300, and IDE0301 suggestions.
Build MSBuild.sln with a recent version of VS 2022.
I've tried switching the projects to `<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>` but I haven't figured out how to do it properly as `win7-x86` and `win7-x64` are still hard-coded in [the SDK](https://github.com/dotnet/sdk/blob/2eadc6e7fec180f6dc4d13b0d1f9597ef676fd2d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targe …

Make the repo buildable with .NET 8 RC1

---

src/Build.UnitTests/BackEnd/BuildManager_Logging_Tests.cs
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build.UnitTests/BackEnd/SdkResultOutOfProc_Tests.cs
src/Build.UnitTests/EvaluationProfiler_Tests.cs

Trying to figure out the failing PR builds.
- Restore the environment (notably environment variables) even if a product component failed to shut down.
- Disable the first failing test: `IdenticalSubmissionsShouldCompleteAndNotHangTheBuildOnMissingTargetExceptions`

Disable failing test and always dispose of TestEnvironment

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Esprojs may be referenced by ASP.Net projects (or others). When this happens, the .net project will have to not reference output assembly on the esproj, because there is no output assembly. This targets provides that behavior. There was an argument for putting this in this file instead of in the sdk. The discussion can be found here: https://github.com/dotnet/sdk/pull/34983

Setting ReferenceOutputAssembly to falso on references to esproj

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fail with clear error message when reporting file accesses with unsupported arch
Follow-up change from #9214.

Fail with clear error message when reporting file accesses with unsupported arch

---

src/Tasks/Copy.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Fixes #9210 
Copy task implement `LogDiagnostics` as warnings. This is causing issues for `/WarnAsError` use cases.
Change Copy task `LogDiagnostics` from Warning to low importance Message.
``` C#
/// <summary>
/// If MSBUILDALWAYSRETRY is set, also log useful diagnostic information -- as 
/// a warning, so it's easily visible. 
/// </summary>
private void LogDiagnostic(string message, params object[] messageArgs)
{
if (s_alwaysRetryCopy)
{
Log.LogMessage(MessageImportance.Low, message, messageArgs);
}
}
```
The reasoning for Warning level "so it's easily visible" is, IMO, not strong enough.
Unit tests.
Locally.
@rainersigwald  Since we see increasing number of people reporting issues with Copy conflicts, I believe it is candidate for 17.8

Change Copy task LogDiagnostics Warning so it is suppressible

---

src/Framework/Traits.cs
src/Tasks/Copy.cs

Work item (Internal use): N/A
This allows an opt-in workaround for #9250 that affected deployment processes can use, mitigating the risk of entirely reverting #8685.
Automated deployment of new versions of apps failed in some environments.
Yes, from #8685 (in 7.0.400/MSBuild 17.7).
Tests in the affected environment using the more-broadly-scoped `MSBUILDDISABLEFEATURESFROMVERSION=17.8` pass.
Minimal--adds new scoped opt-out that is redundant with known successful opt-out, using established mechanisms.

Add escape hatch MSBUILDCOPYWITHOUTDELETE

---

.exp-insertions.yml
scripts/Deploy-MSBuild.ps1

Adding a pipeline that creates dotnet with experimental MSBuild bits. 
- Create pipeline for exp insertions.
- Modify the Deploy script: add option to specify MSBuild bootstrap folder, make backup optional
Manual testing of the resulting pipeline

Create pipeline for exp insertions

---

.vsts-dotnet.yml
eng/policheck_exclusions.xml

Fixes #6021
Enable SDL (PoliCheck, Credscan) in official builds.
Enable SDL run as part of Post-Build Validation Stage.

Enable SDL (PoliCheck, Credscan) in official builds

---

documentation/wiki/ChangeWaves.md
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Framework/BinaryTranslator.cs
src/Framework/Traits.cs

Fixes #9258 
Opting out of 17.8 features (via changewaves env variable) while `EnableUnsafeBinaryFormatterSerialization` is not allowed by the runtime can lead to MSBuild crashing ungracefully.
This is because BinaryFormatter serialization usage in core now leads to runtime failures (as of 8.0) unless explicitly opted-in by user. So MSBuild moved to alternative (secure) serialization. MSBuild normally allows users to opt out of the last batch of changes - with changewaves. In this specific case it can mean shooting self into foot without realizing.
Resolution: Ignoring the opt-out of the new secure serialization unless the BinaryFormatter is explicitly allowed by user in runtime (by editing `MSBuild.runtimeconfig.json` in the SDK).
If users have encountered a problem in the latest MSBuild …

Make BinFmt changewave dependent on BinFmt runtime enablement

---

src/Build/Instance/TaskFactories/TaskHostTask.cs
src/Shared/TaskHostTaskComplete.cs

Fix a reported regression that causes MSBuild to crash in net35-targeting projects.
Projects that use the .NET 3.5 taskhost (like projects that target .NET 3.5 and have `.resx` files) fail with `error MSB4217: Task host node exited prematurely.`
Yes, from 17.7. Introduced in #9214.
Repro case from VSUnitTesting repo manually validated, automated tests.
Low, adds a bool to the translation only in the known-broken case.
TaskHostTaskComplete packets can be sent between nodes that differ in
FEATURE_REPORTFILEACCESS, causing confusion when the sending side (for
example a net35 taskhost) does not send the FileAccessData field, but
the receiving side (net48) expects it.
Unify this by explicitly sending a bool `false` (no data) in the
!FEATURE_REPORTFILEACCESS case, so there's no difference on …

Translate FileAccessData in TaskHostTaskComplete

---

src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
src/Tasks/GenerateResource.cs

Fixes [#9199](https://github.com/dotnet/msbuild/issues/9199)
The unhandled exception is from https://github.com/dotnet/msbuild/blob/3c910ba83fc9dbd8e12f50dddc8c381404f928c4/src/Tasks/GenerateResource.cs#L1132C13-L1133.  But when source is not found and has errors, it should return false in Execute function.
Return false if there are no valid sources found.
Add a unit test case.

Return false if there are no sources

---

src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

These strings were introduced in #9217 but caused loc breaks.
Fixes #9283.
Bad translations in non-English locales.
No, new strings with bad contents.
N/A (build + XLF stuff passes)
None AFAIK--only risk is not getting new translations which we already aren't.

Remove unnecessary quotes in loc strings

---

src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/BinaryLogger/BuildEventArgsFieldFlags.cs
src/Build/Logging/BinaryLogger/BuildEventArgsFields.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
src/Build/Logging/BinaryLogger/ExtendedDataFields.cs
src/Build/Microsoft.Build.csproj
src/Framework/ExtendedBuildErrorEventArgs.cs
src/Framework/ExtendedBuildMessageEventArgs.cs
src/Framework/ExtendedBuildWarningEventArgs.cs
src/Framework/ExtendedCustomBuildEventArgs.cs
src/Framework/IExtendedBuildEventArgs.cs
src/Shared/BinaryReaderExtensions.cs

Fixes #9091
We have introducing new extended event args (error, warn, message, custom) so time ago. 
This PR is about logging extended data into binary log and will serve for modifying bin log viewer as well.
Add `BuildEventArgsFieldFlags.Extended` and implement related code.
Unit tests

Add Extended messages data to binary log

---

src/Shared/TempFileUtilities.cs

Having a Username containing unicode chars, and tools that does not handle that well, makes it difficult when ToolTask are defined from NuGet Packages.
Fixes https://github.com/dotnet/msbuild/issues/9229
Tmp folder can be changed by updating the User env vars, but Username are not possible. Not prepending the Username makes it possible for Users to handle these rare cases.
Changed to not append Username on Windows to tmp rsp file location.
Tests already for ToolTasks using this.

On windows there can be problems with Tools that do not support Unicode

---

.vsts-dotnet.yml

The insertion release definition extends this when we try to insert, and
the VS release will extend it indefinitely for public builds.
Fixes a build warning in our official builds
##[warning]DropRetentionDays not set. Defaulting to 10 years (3650
days). Please reduce drop retention period to 30 days if possible.

Reduce VS drop retention time for builds

---

global.json

Fixes #
RoslynTools.MSBuild 17.7.2 caused two CG alerts when doing signing validation. https://github.com/dotnet/arcade/issues/14055 and its linked PRs have more context.
Following dotnet/arcade update xcopy-msbuild to 17.7.4.
I used this experimental branch to verify and no CG alerts were detected.

Fix CG alerts caused by RoslynTools.MSBuild 17.7.2

---

eng/policheck_exclusions.xml
src/Tasks/AssemblyDependency/GenerateBindingRedirects.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs

Fixes policheck:Error
1. Skip the non en-us locale resource files.
2. Skip the file that contains the specified entity names in the deprecated folder
3. Change country to country/region based on https://policheck.microsoft.com/Pages/TermInfo.aspx?LCID=9&TermID=79570
Test with MSBuild pipeline build https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8509007&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=c5a86041-9185-53e8-42a2-1cadc4486f0d&l=5251. There are no active results now.

Fix policheck error

---

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Consider a message like
```
warning MSB3277: Found conflicts between different versions of "System.Runtime.InteropServices.RuntimeInformation" that could not be resolved.
There was a conflict between "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
"System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
References which depend on …
```

Mention unification in RAR found-conflicts message

---

src/Build.OM.UnitTests/Definition/ProjectItem_Tests.cs
src/Build.OM.UnitTests/Instance/ProjectItemInstance_Tests.cs
src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/Shared/UnitTests/FileMatcher_Tests.cs
src/Tasks.UnitTests/CreateItem_Tests.cs
src/Tasks.UnitTests/Microsoft.Build.Tasks.UnitTests.csproj
src/UnitTests.Shared/DummyMappedDriveUtils.cs

Fixes https://github.com/dotnet/msbuild/issues/7330
(plus one subtask of https://github.com/dotnet/msbuild/issues/8329)
1. Based on https://github.com/dotnet/msbuild/pull/8366 fixes to enable other Drive enumeration integration tests with a dummy folder in windows
2. Remove one test data https://github.com/dotnet/msbuild/blob/fecef0fdffe59ba8b0251701a23be48bbd552726/src/Build.OM.UnitTests/Instance/ProjectItemInstance_Tests.cs#L1010-L1012C45 since there is no warning when inlude is not null and exclude with enumerating wildcards. The related logical code is https://github.com/dotnet/msbuild/blob/fecef0fdffe59ba8b0251701a23be48bbd552726/src/Build/Utilities/EngineFileUtilities.cs#L339. There is no condition satisfied.
3. Associate unix Enumeration Tests long time run with issue …

Enable Windows Disabled Drive Enumeration Tests

---

src/Build.UnitTests/Evaluation/ImportFromMSBuildExtensionsPath_Tests.cs
src/Build/Evaluation/Evaluator.cs

Fixes [#8762 ](https://github.com/dotnet/msbuild/issues/8762)
Catch the exceptions when extensionsPathPropValue is null or importExpandedWithDefaultPath is empty.
In NET Framework, Path.* function also throws exceptions if the path contains invalid characters
Catch the exception.
FallbackImportWithInvalidProjectValue

Catch the illegal argument exception in Net Framework!

---

.vsconfig

.NET (Core) stuff is implied by ManagedDesktop now, and we require only "some .NET Framework SDK", so no need to specify explicitly as one will be delivered by ManagedDesktop.
We do still target .NET Framework 3.5, though . . .

Remove stale .vsconfig components

---

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs

Fixes #9245
The test was disabled to unblock PR CI.
Increased the relevant timeout.
The test is reliably passing now.
This turned out to be an issue with [the sleep command](https://github.com/dotnet/msbuild/blob/914c3e867444ac178bdc4dca78431871bebb415f/src/Shared/UnitTests/ObjectModelHelpers.cs#L1982) we use on Windows. In some cases PowerShell can take a super long time to start. I have been able to reproduce locally by enabling Fusion logging. Thread times of the `powershell` process:
We spend almost 10 seconds just loading assemblies, so the timeout of 10 seconds for the entire build was not enough.
I don't have a full understanding of the mechanism that slows down PowerShell this much. At this point I'm happy we were able to confirm it's not a product issue, although I'm wondering if …

Re-enable IdenticalSubmissionsShouldCompleteAndNotHangTheBuildOnMissingTargetExceptions

---

.exp-insertions.yml
scripts/Deploy-MSBuild.ps1

We need to add an extra job to .exp-insertions.yml pipeline for creating experimental Framework MSBuild.
- Pipeline refactored, a job added
- Fixed bug in deploy script code path for Framework MSBuild
Manual run of the pipeline

Add a job for experimental Framework MSBuild insertion to a pipeline

---

eng/dependabot/Packages.props

Update Microsoft.BuildXL.Processes to 0.1.0-20230929.2
This version of the package includes some (dead) code removal which was triggering APIScan bugs.

Update Microsoft.BuildXL.Processes to 0.1.0-20230929.2

---

src/Build.UnitTests/BackEnd/Scheduler_Tests.cs
src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/ProjectCache/ProxyTargets.cs
src/Build/BackEnd/Shared/BuildRequest.cs
src/Build/BackEnd/Shared/BuildRequestConfiguration.cs

Fixes #9117
For project cache plugins to only partially handle a build request, it makes sense for it to only proxy some targets and not others. For example, in VS the build request has:
```
"Build"
"BuiltProjectOutputGroup"
"BuiltProjectOutputGroupDependencies"
"DebugSymbolsProjectOutputGroup"
"DebugSymbolsProjectOutputGroupDependencies"
"DocumentationProjectOutputGroup"
"DocumentationProjectOutputGroupDependencies"
"SatelliteDllsProjectOutputGroup"
"SatelliteDllsProjectOutputGroupDependencies"
"SGenFilesOutputGroup"
"SGenFilesOutputGroupDependencies"
```
"Build" is the only relevant one that a plugin would want to handle, and would likely redirect to "GetTargetPath", while the rest are "information gathering" targets which should just be "passed through" and allowed to execute as-is. …

Populate unproxied targets to avoid dropping requested targets

---

.exp-insertions.yml

Fixes [#1897030](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1897030)
1. Checkout of CloudBuildConfig repo in [Pipelines - Runs for MSBuild-prepare-exp-bits (azure.com)](https://dev.azure.com/devdiv/DevDiv/_build?definitionId=19368&_a=summary) takes 10 minutes and we need only 1 file. We might research a solution to get this one file only (a web request with authorization maybe).
2. https://github.com/dotnet/msbuild/pull/9309#discussion_r1355814361
1. Use the https://learn.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-4.1&tabs=HTTP 
2. Filter the artifacts 
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=8547869&view=results

Get Retail MSBuild Drop Path with Restful API

---

src/Package/Microsoft.Build.UnGAC/exe.swr

One of the top VS Setup failures is a 259 from our UnGAC,
even though we have a big try/catch that should make it
never fail. Tell the Setup engine that 259 is another
kind of success to keep this nonblocking.
Fixes [AB#1899796](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1899796).

Setup UnGAC: treat 259 as success

---

src/Tasks.UnitTests/GenerateBindingRedirects_Tests.cs
src/Tasks/AssemblyDependency/GenerateBindingRedirects.cs

Work item (Internal use): [AB#1875355](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1875355)
Revert a behavior change in `GenerateBindingRedirects` that results in overwriting `app-under-development.exe.config` in situations where we didn't before 17.7, causing dev suprise.
Broken inner build loop because customizations stored in .exe.config file 
Yes, in 17.7. Introduced in 0aa8c5fc.
Manual testing of repro scenario, automated tests.
Low. Reverts to previous behavior in a .NET Framework-only codepath.

Stop touching GenerateBindingRedirects output

---

src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs

Fixes #9298
Waiting using `Thread.Sleep(500)` in the test is unreliable.
Wait until the specified log appears rather than `Thread.Sleep(500)`.

Use distinct signal to wait to cancel the submission

---

src/Build.UnitTests/BackEnd/Scheduler_Tests.cs
src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/ProjectCache/ProxyTargets.cs
src/Build/BackEnd/Shared/BuildRequest.cs
src/Build/BackEnd/Shared/BuildRequestConfiguration.cs

Revert ["Populate unproxied targets to avoid dropping requested targets (#9130)"](https://github.com/dotnet/msbuild/pull/9130)
This reverts commit 4256aed414cfbb6b32dc072c763145beb8fe0c0b.
Fixes [AB#1906434](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1906434).

Revert #9130

---

eng/Version.Details.xml
eng/Versions.props
eng/common/sdk-task.ps1
eng/common/tools.ps1
global.json

This reverts commit 3a2f9ba61cbe0dc51ffe12e9a027cfbb26643a36, which broke some official build steps because Arcade now depends on an RTM runtime.

Revert "Update dependencies from dotnet/arcade (#9315)"

---

src/Framework/CustomBuildEventArgs.cs

Fixes #9220 
CustomBuildEventArgs is deprecated. Users are advised to use ExtendedCustomBuildEventArgs instead.
See https://github.com/dotnet/msbuild/pull/8917
The comment change results in a public-facing doc change at
https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.custombuildeventargs?view=msbuild-17-netcore
The new Remarks section includes a link to a public-facing doc that explains the change:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/custombuildeventargs
Comment only change. 
I added the Remarks tag to be explicit. Previously, the double-slash comment was being implicitly treated as the Remarks section. The tag makes this explicit (not necessary but helpful to avoid ambiguity).
I left the existing warning in place in the Remarks …

Add deprecation notice and links

---

src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactoryCompilers.cs
src/UnitTests.Shared/RunnerUtilities.cs

Fixes #9052
For RoslynCodeTaskFactory, dotnet path is wrongly set using the path of the application when running the application via application.exe.
Get dotnet path through the following in order.
1. Honor the environment variable DOTNET_HOST_PATH for tools and MSBuild tasks within the SDK to ensure a consistent experience.
2. Fallback to get dotnet path from current process which might be dotnet executable.
3. If the path resolved above is not dotnet executable, rely on dotnet via the system's PATH.
Add a test that verifies build the task of RoslynCodeTaskFactory using API.

Fix dotnet path for RoslynCodeTaskFactory

---

src/Build.UnitTests/BinaryLogger_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Framework/AssemblyLoadBuildEventArgs.cs
src/Shared/UnitTests/TypeLoader_Dependencies_Tests.cs

Fixes #9348
When MSBuild was updated to isolate tasks into a custom `AssemblyLoadContext`, `AssemblyLoadsTracker` was not updated to be aware of this change. This means that the log messages always say `AppDomain: [Default]` and don't show any information about which `AssemblyLoadContext` was used to load the assembly.
When `FEATURE_ASSEMBLYLOADCONTEXT` is defined:
- `AssemblyLoadsTracker` now populates `AssemblyLoadBuildEventArgs` with the name of the `AssemblyLoadContext` used to load the assembly . The `appDomainDescriptor` parameter is re-used to do this.
- A new string resource has been added to update the text of `AssemblyLoadBuildEventArgs.Message` to use label the `AppDomainDescriptor` value as "AssemblyLoadContext" instead of "AppDomain".
~~I couldn't find any existing tests that …

Use AssemblyLoadContext Name instead of AppDomain

---

src/Build/Graph/GraphBuilder.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1834963
PR  https://github.com/dotnet/msbuild/pull/7699 caused perf regression when running large-graphs-with-platform-negotiation kind of build.
Changes:
https://github.com/dotnet/msbuild/blob/867e26043663966e3fa29450476179aea148cd9e/src/Build/Graph/ProjectInterpretation.cs#L182-L184
have caused that dependency projects were evaluated for Platform Negotiation purpose (with null global properties) for each incoming dependency.
Caching "evaluation for Platform Negotiation purpose".
Unit tests.
Local.
Without changes it was running 6K evaluations (for VS/VC build) and it took 132 s.
After changes only 1.5K evaluations with duration of 33 s.
The fact that every dependency has to be specially evaluated for Platform Negotiation …

Cache Platform Negotiation in graph build

---

src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Framework.UnitTests/ExtendedBuildEventArgs_Tests.cs
src/Framework/ExtendedCriticalBuildMessageEventArgs.cs
src/Shared/LogMessagePacketBase.cs

Fixes #9355
During 1st phase of creating Extended events we I have missed CriticalBuildMessageEventArgs
ExtendedCriticalBuildMessageEventArgs 
Related unit tests
Local
Uni tests
This change does not break logviewer - tested - however another small PR in log viewer will be done to better support it.
Old log viewer:
Future log viewer:

Add ExtendedCriticalBuildMessageEventArgs and related tests

---

eng/dependabot/Packages.props
src/Build.UnitTests/BinaryLogger_Tests.cs
src/Build.UnitTests/Collections/CopyOnWritePropertyDictionary_Tests.cs
src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
src/Build.UnitTests/Utilities_Tests.cs
src/MSBuild.UnitTests/XMake_Tests.cs
src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
src/Shared/UnitTests/ObjectModelHelpers.cs
src/Shared/UnitTests/TestEnvironment.cs
src/Tasks.UnitTests/DownloadFile_Tests.cs
src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs
src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
src/Tasks.UnitTests/Unzip_Tests.cs
src/Tasks.UnitTests/VerifyFileHash_Tests.cs
src/Tasks.UnitTests/ZipDirectory_Tests.cs

Almost all changes are fallout from https://docs.shouldly.org/documentation/3to4#func-less-than-string-greater-than-custommessage-removed.
Fixes were: always materialize the string up front, and sometimes
explicitly specify `customMessage:` to disambiguate methods.

Shouldly 4.2.1

---

src/Framework/CustomBuildEventArgs.cs

Improving the CustomBuildEventArgs deprecation notice

Update CustomBuildEventArgs deprecation info

---

src/Build.UnitTests/BackEnd/BuildRequestEngine_Tests.cs

Fixes #9100 #9277
In BuildRequestEngine_Tests the tests rely on `Thread.Sleep(250)` to wait for the engine status changes. It may cause the tests unstable.
In addition, because the status changed AutoResetEvent is not reset after the status change at some places, `WaitForEvent(_engineStatusChangedEvent, "EngineStatusChanged")` inside `VerifyEngineStatus(BuildRequestEngineStatus expectedStatus)` couldn't work correctly to wait for the expected status.
Instead of `Thread.Sleep(250)`, rely on `VerifyEngineStatus(BuildRequestEngineStatus expectedStatus)` to wait. And after the operation that triggers the status change event, make sure the following in order.
1. the status change finishes.
2. the status changed AutoResetEvent is reset.
N/A

Stabilize BuildRequest Engine tests

---

src/Tasks/Exec.cs

The en_US locale can't be used on systems where it is not installed. This is common in container images.
On such systems, setting the locale to en_US.UTF-8 causes unexpected warnings to be written to standard error.
When Exec.LogStandardErrorAsError is set, these warnings cause the Task to fail due to logging errors.
This changes to use the 'Computer English' C.UTF-8 locale, which is always available.
Fixes https://github.com/dotnet/msbuild/issues/4194
@rainersigwald @wfurt @janvorli ptal
cc @mthalman @omajid

Exec: use C instead of en_US.UTF-8 to set the Exec locale.

---

src/Framework/EncodingUtilities.cs
src/Tasks.UnitTests/Exec_Tests.cs
src/Utilities.UnitTests/EncodingUtilities_Tests.cs

Fixes #9254
DOTNET_CLI_UI_LANGUAGE enviroment variable was not respected when TwoLetterISOLanguageName of CultureInfo was equal to en. 
Removed the additional check for described in the context case
Case covered by unit test of the method additionally to testing in debug mode.

Fix the ui language override helper method for input language "en" 

---

src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs
src/MSBuild/TerminalLogger/TerminalLogger.cs

Fixes #9322
In an attempt to build an invalid project with MSBUILDNOINPROCNODE=1, the exception "Out of boundary" was thrown.
Add a check before accessing the array element by index.
UTs are added

Fix TL failure on MSBUILDNOINPROCNODE env variable

---

src/Tasks/Exec.cs

Reverts dotnet/msbuild#9391, which was merged before it was fully agreed on.

Revert "Exec: use C instead of en_US.UTF-8 to set the Exec locale."

---

documentation/wiki/Providing-Binary-Logs.md

This isn't quite correct anymore - updating the wording here.

Fix language about binlog environment variable use

---

documentation/wiki/MSBuild-Tips-&-Tricks.md

~Fixes #~ (not applicable)
Documentation change only.
- I extended the section about extending the builds a bit
- Also moved it to the bottom, because it is now the largest section

Extended the section about extending builds

---

src/Shared/EnvironmentUtilities.cs

I was recently investigating a problem (https://github.com/jaredpar/complog/pull/73) where the issue was that `MSBuildSdksPath` was set incorrectly, so an SDK was being resolved incorrectly. I had initially ruled that out, because I knew that we should be logging environment variables that start with `MSBUILD`.
We were, but case-sensitively. Since the canonical case for some of our config environment variables is not all caps, we should change that.

Log allowed environment vars case-insensitively

---

eng/dependabot/Packages.props
src/Build/Microsoft.Build.csproj
src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
src/Framework/Microsoft.Build.Framework.csproj
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj

In the switch to Central Package Management (#8317), I missed that PrivateAssets doesn't apply to PackageVersion items, which caused us to have an extraneous dependency from some of our packages to `Microsoft.VisualStudio.Setup.Configuration.Interop` for 17.6, 17.7, and 17.8.

Don't expose VisualStudio.Setup to NuGet

---

eng/dependabot/Packages.props

While upgrading the version in this PR: https://github.com/dotnet/msbuild/pull/9426
It was identified that there are multiple references that could be upgraded. This PR contains only upgrades minor and patches versions not to include possible breaking changes. 
PR for upgrading major versions will be created separately. 
Upgraded BenchmarkDotNet and FluentAssertions versions
Existing tests should pass

Upgrade BenchmarkDotNet , FluentAssertions versions

---

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Construction/Solution/SolutionProjectGenerator.cs
src/Build/Graph/GraphBuilder.cs

Fixes #9375
Previously, only projects which were `SolutionProjectType.KnownToBeMSBuildFormat` (handful of project type guids) would be considered. This would cause some projects in a sln to not be in the graph at all.
This change removes that check and in general brings solution-based graph construction slightly more aligned with how non-graph builds construct the metaproj (`SolutionProjectGenerator`). My ideal scenario would be that the graph would just directly call into `SolutionProjectGenerator` to create a metaproj and then use that as the entry point into the graph construction, but we would need to teach the metaproj the p2p protocol used for graph which is a bit more work. Maybe one day though :)
Change details:
* Removed the check for `SolutionProjectType.KnownToBeMSBuildFormat` …

Fix solution-based graph builds when non 'well-known' project types are used

---

documentation/wiki/Contributing-Code.md

Fixes #9399
From the [PR ](https://github.com/dotnet/msbuild/pull/9392)review there were a mention of using the Shouldly for assertions, however it was not documented at that time.
Update contributing code file with mentioning preference of using Shouldly in tests

Mention preference of using Shouldly in tests

---

src/MSBuild/TerminalLogger/TerminalLogger.cs

Fixes #9323
There are 4 related problems that occur in the issue #9323:
1. The logger fails and throws an internal logger exception because of the wrong assumptions about restore target appearance in the build. 
2. The internal logger exception is caught and causes the build to shut down all loggers, including terminal logger. Because it happens before the build finished event is produced or processed by terminal logger, the rendering thread is not finished, and it leads to an infinite hang.
3. The errors during restore are not logged.
4. There is inconsistency with showing the message error MSB4017. If the internal logger exception is thrown from one place it shows, from another - not. In the current situation the build and logger are shut downed, but the message did not appear, which is …

Fix restore handling in Terminal Logger

---

src/Build/BackEnd/Client/MSBuildClient.cs
src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs
src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverService.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs
src/Framework/MSBuildEventSource.cs

`EventSource.WriteEvent()` can, instead of writing the specified event, instead create `Microsoft-Build/EventSourceMessage` events that look like
EventSourceException while processing event "SdkResolverResolveSdkStop": Null passed as a event argument.
EventSourceException while processing event "CachedSdkResolverServiceResolveSdkStop": Null passed as a event argument.
Fix instances of this by enabling nullable analysis in `MSBuildEventSource.cs` and then fixing the errors that arose.
Fixes #8519.
While investigating this I noticed one event that had had a field added but no version bump, so I fixed that too.
~With this change I see events:~

Log ETW for SDK resolution again

---

src/MSBuild/CommandLineSwitches.cs

origin PR: https://github.com/dotnet/msbuild/pull/9453
The methods: IsParameterlessSwitch and IsParameterizedSwitch are desgined to identify if the switch is exist or not, iterates the switches map and assignes the found values to the output variables, however after finding the needed parameter (name comparison) it continues to search till the end of the map, which makes it unnecessary since the name is unique across the all presented switches
Exit the method as soon the parameter name is find and the values are assigned.
Existing tests should pass

Exit the loop after finding the switch name in the map

---

src/Tasks.UnitTests/Exec_Tests.cs
src/Tasks/Exec.cs

The en_US locale can't be used on systems where it is not installed. This is common in container images.
On such systems, setting the locale to en_US.UTF-8 causes bash to print unexpected warnings to standard error.
When Exec.LogStandardErrorAsError is set, these warnings cause the Task to fail due to logging errors.
This changes to no longer set the locale explicitly. The Exec command will now run under the system locale instead of US English. Most tools should functionally behave the same under any locale.
Users may still set the locale environment variables themselves through Exec.EnvironmentVariables.
The previous behavior can also be restored as it is under a changewave.
@KalleOlaviNiemitalo @rainersigwald @wfurt @danmoseley ptal.
cc @mthalman @omajid 
Fixes …

Exec: stop setting a locale on Unix.

---

src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/XMake.cs

Fixes https://github.com/dotnet/msbuild/issues/9443
When the `/graph` and `/restore` are used within the same command, the build exit code will always be 0. This is because of the variable used to define success of the restore action overrides the success of the graph build.
Added an extra condition when defining the success of the build to account for this case.
Made sure existing tests passed and added a unit test for this case, an some manual testing.

Fixed /restore and /graph conjunction error on exit code

---

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
src/Build/Evaluation/Evaluator.cs

Fixes #9385
During the Evaluation phase, property reassignment was logged as a plain message.
convert plain message to -> PropertyReassignmentEventArgs
UT is added

Сhange ProperyReassignment logged message type

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes #9120
In the target AssignLinkMetadata Link is added to Page and ApplicationDefinition items, but not for Resource items., causing issues with WPF projects.
Adding Link metadata to Resource items under a ChangeWave.
unit tests and experimental insertion

Add Link metadata to Resources in AssignLinkMetadata target

---

.vsts-dotnet.yml

The devdiv build machine images appear to have started setting the
environment variable `NUGET_PACKAGES`, which caused a mismatch between
the location where `drop.app` was restored (repo-local location) and
where it was used from (environment-variable defined machine location),
causing build failures.
Co-authored-by: AR-May <67507805+AR-May@users.noreply.github.com>

Unset NUGET_PACKAGES in official build only

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Fixes VS feedback ticket https://developercommunity.visualstudio.com/t/Code-Completion-for-Nuget-Package-Refere/10525616
NuGet's Central Package Management (CPM) allows users to specify package versions in a central location.  However, sometimes you may need to override the centrally defined version for a particular package so you specify the `VersionOverride` attribute documented [here](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#overriding-package-versions).
Added `VersionOverride` to the XSD for auto-completion in Visual Studio.
Unsure how to test this.

Add VersionOverride to XSD for PackageReference elements

---

documentation/wiki/ChangeWaves.md
src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/XMake.cs

Fixes #9482
The -version switch doesn't terminate its output with a newline which some shells don't like.
- Added a unit test.
- Changed `ShowVersion()`.
Tested on Windows 10 and macOS 14.
Tested by running the full unit test suite and by manually running the `-version` switch under cmd (Windows), pwsh (Windows and macOS), and zsh (macOS).

Change Version switch output to finish with a newline

---

eng/Versions.props
src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes: 1P issue
#9387 intorduced Up2Date check marekr file shortening - but this was leveraging `ProjectGuid` property (if present). That property can be user altered and lead to invalid path issues.
Let's simplify and solidify the marker file shortening via relying on the filename hash only.
Removed the usage of `ProjectGuid`

Remove U2D marker dependency on ProjectGuid property

---

documentation/wiki/ChangeWaves.md
src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
src/Build/Microsoft.Build.pkgdef
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Fixes #9303
After a new version of `VS.Redist.Common.Net.Core.SDK.MSBuildExtensions` is inserted into VS, a native image for `Microsoft.DotNet.MSBuildSdkResolver` will be generated, both for devenv.exe and MSBuild.exe (see https://github.com/dotnet/installer/pull/17732).
We currently load SDK resolvers using `Assembly.LoadFrom` on .NET Framework, which disqualifies it from using native images even if they existed. This PR makes us use the native image.
Added a code path to use `Assembly.Load` to load resolver assemblies. The call is made such that if the assembly cannot be found by simple name, it falls back to loading by path into the load-from context, just like today. The new code path is enabled only for `Microsoft.DotNet.MSBuildSdkResolver` under a change-wave check.
Experimental …

Load Microsoft.DotNet.MSBuildSdkResolver into default load context (MSBuild.exe only)

---

.vsts-dotnet.yml

This reverts commit 67d742f0a7a0de2d770909319bc334d0338b1fbd.
This workaround no more needed.

Revert "Unset NUGET_PACKAGES in official build only (#9523)"

---

src/Framework/ChangeWaves.cs
src/Tasks/Microsoft.Common.CurrentVersion.targets

We still have checks for a change wave that's already out of rotation.
`[MSBuild]::AreFeaturesEnabled('17.0')` is now unconditionally true, let's remove the checks from `Microsoft.Common.CurrentVersion.targets`.

Delete checks for retired change waves

---

src/Tasks/Microsoft.Common.CrossTargeting.targets

Fixes #9131
As described on the issue, muti-targeted builds did not import the .user file on the outer build. This change makes the outer build import the .user file.
Added import reference to .user file in  Microsoft.Common.CrossTargeting.targets .
Test is in SDK repo (dotnet/sdk#37192)
This is cherry-picked from main branch

Added import of .user file for multi-targeted builds

---

src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/GraphBuilder.cs

Fixes #9500
Previously the code was considering all projects when building up the solution dependencies and later that was blowing up due to including projects which weren't built. This moves the logic to the same loop that already filters projects which don't build so should be (trivially) more efficient anyway.

Fix sln-based graph builds with non-built projects with solution dependencies

---

src/Build/Logging/SimpleErrorLogger.cs
src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/XMake.cs

Fixes #9394
InvalidProjectFileExceptions thrown by attempting to get the properties or items from an invalid project are not handled specially in XMake's big try/catch, which means they are caught as a generic "exception" and thrown as an unexpected internal error when in fact this should be an expected user error. This resolves that problem.
While poking at this, I happened to notice that if an error is logged, the next message is on the same line. I think it's better UI to move it to its own line, so that's the second commit.
Handle InvalidProjectFileExceptions as expected/user errors.
Add \n to errors logged by SimpleErrorLogger.
I tried the repro in 9394 and successfully reproduced the problem. I tried with this change, and it instead printed this:
[path]\invalid.proj(1,1): error …

Catch InvalidProjectFileException Fixes #9394

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/Instance/ProjectInstance.cs

When evaluating the generated .sln.metaproj, we do pass a valid submissionId, but then we don't use it when creating the BuildEventContext used by the ProjectInstance to log evaluation events. So evaluation logging events end up having SubmissionId == -1, and thus the loggers registered with the MuxLogger in the IDE do not get the evaluation events.
Fixes #9469
I've built a bootstrap MSBuild and validated that the events show up in the log now:
Before:
After:

Pass submissionId to the BuildEventContext used by SolutionProjectGenerator

---

eng/Packages.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config
src/Tasks/System.Resources.Extensions.pkgdef

Update `dotnet/runtime` dependencies to the 8.0 versions.
- darc update-dependencies --id 199769
- Add Tasks.Dataflow and Channels deps
- Binding redirect updates to 8.0 versions

Bump to .NET 8 GA package refs

---

src/Build.UnitTests/BinaryLogger_Tests.cs
src/Build/Logging/DistributedLoggers/DistributedFileLogger.cs
src/MSBuild.UnitTests/TerminalLogger_Tests.cs
src/MSBuild/CommandLineSwitches.cs

During working on #9568 some chore was done. 
In order to keep original PR as small as possible and not to include unrelated changes creating this PR with only small fixes to the code base. To make it easier for reviewers 
code warnings, styling
All current tests should pass

Chore: remove unused code, clear warnings

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/ProjectCache/CacheContext.cs
src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs

Fixes #9554
As usual, the Visual Studio code path is a bit icky. It basically just uses the target names of whatever the first request it receives which uses a given plugin. In practice this is fine since VS uses the same target across all projects depending on scenario (Build, Rebuild, Clean, etc.).

Add requested targets to CacheContext

---

eng/Build.props
src/Directory.Build.props

MSBuild's build ifnrastructure overwrites the `CustomBeforeMicrosoftCommonTargets` property which results in Arcade's entry to get dropped.
Arcade adds to that property to import common files.
This fixes static graph restore not working in this repository when using Arcade's `ExcludeFromBuild` properties.

Fix Arcade's BeforeCommon imports not being respected

---

eng/Versions.props
src/Tasks/ManifestUtil/Manifest.cs
src/Tasks/ResolveManifestFiles.cs

Fixes #
[AB#1921068](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1921068)
PR [9299](https://github.com/dotnet/msbuild/pull/9299) added support for publishing content artifacts from P2P references. After this change, there is an installation failure that has been reported for a scenario where an EXE project has a P2P reference to another EXE project. For such a scenario, there are 2 apphost.exe's that are present in the list of artifacts to be published - one from the main project and the other from the referenced EXE project.
ClickOnce does not expect 2 apphost.exe's to be published together and both of the apphost.exe's get published as the assembly name of the main project. This leads to a duplicate entry in the ClickOnce application manifest and …

[ClickOnce] Handle multiple apphost.exe files that could be published with an EXE to EXE P2P reference

---

src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
src/Framework/IEventSource.cs

Random find - `ConfigurableForwardingLogger` is checking a string dictionary for each build event, while a simple events (un)subscriptions can achieve same job with less efforts (coding and CPU)
Existing tests ([`ConfigureableForwardingLogger_Tests`](https://github.com/dotnet/msbuild/blob/main/src/Build.UnitTests/ConfigureableForwardingLogger_Tests.cs))

Improve ConfigurableForwardingLogger

---

src/MSBuild/TerminalLogger/TerminalLogger.cs

Fixes #9602 by emitting NETSDK1057 as an immediate message at most once in the TerminalLogger.
```sh-session
❯ dotnet build
MSBuild version 17.10.0-dev-24055-01+3500455af for .NET
Restore complete (1.1s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
Lib1 succeeded (3.1s) → Lib1\bin\Debug\net9.0\Lib1.dll
Lib2 succeeded (3.1s) → Lib2\bin\Debug\net9.0\Lib2.dll
App succeeded (3.2s) → App\bin\Debug\net9.0\App.dll
Build succeeded in 4.5s
```
It is slightly ugly to do this deduplication at the logger level, but it cleans up a customer annoyance so I think it's worth it.

Emit NETSDK1057 at most once in -tl

---

src/Tasks/Copy.cs
src/Tasks/GenerateManifestBase.cs
src/Tasks/LockCheck.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Fixes [#9465](https://github.com/dotnet/msbuild/issues/9465)
Unable to write manifest ‘obj\Debug\bc.exe.manifest’. The process cannot access the file ‘C:\Source\bc\bc\obj\Debug\bc.exe.manifest’ because it is being used by another process.
With limited error message, can't tell which process exactly hold the lock for the file. 
use original the Copy task's "name the process that holds the lock" approach for the task GenerateManifestBase

Add message to  to indicate which process exactly hold the lock for the file for task Generate*Manifest

---

src/BannedSymbols.txt
src/Shared/UnitTests/TestAssemblyInfo.cs
src/Tasks.UnitTests/GenerateBindingRedirects_Tests.cs
src/Tasks/AssemblyDependency/GenerateBindingRedirects.cs

[1921343](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1921343/)
XDocument.Load doesn't handle parsing GB18030 symbols and returns path like 𬴂龨苘爫麤υ㏑%EE%80%B8䡫3\𬴂龨苘爫麤υ㏑%EE%80%B8䡫3 instead of 𬴂龨苘爫麤υ㏑䡫3\𬴂龨苘爫麤υ㏑䡫3. It causes System.IO.DirectoryNotFoundException.
Using XmlReader for handling encoding issues.
UT + manual

Fix parsing GB18030

---

src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes #9413
We currently log [when we are starting to resolve SDK](https://github.com/dotnet/msbuild/blob/9a0cef6f75bf13ffbbde956b8f7d7ad7d6e0d996/src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs#L315) and [when we failed to resolve SDK](https://github.com/dotnet/msbuild/blob/9a0cef6f75bf13ffbbde956b8f7d7ad7d6e0d996/src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs#L134) but not when we succeeded or any resolvers' attempts.
Currently we log:
- If any of the resolvers succeeded, we log warnings only from its result
- If all the resolvers fail, we accumulate the warnings and errors from each of them. In the end, depending on the log flag, we either log one error containing all the errors or do not to log any errors, while logging all warnings.
1. Log each …

Log SDK resolution result

---

src/Tasks/ManifestUtil/mansign2.cs

Fixes
#9505 
SecurityUtilities.SignFile function to sign ClickOnce manifest can fail occasionally during timestamping because the random bytes generated for the nonce can be invalid DER encodings for integer values
To ensure the encoding is not invalid, clear the nonce MSB's most significant bit and set the MSB's least significant bit.
This is a port of the fix made for the same issue in the NuGet client:
https://github.com/NuGet/NuGet.Client/pull/2041/commits/3e55190496b44811c4b5240bdb8ec65521e39161
Customers calling SignFile API through the Microsoft.Build.Tasks.Core NuGet package encounter occasional failures because the Nonce generated is invalid per DER encoding. The fix will address this issue of the SignFile API failing intermittently.
No
Failing scenario validated + signing …

[ClickOnce] Fix nonce generation in timestamping of signed manifest.

---

src/Build/BackEnd/Components/Logging/EventSourceSink.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes #9455
If we crash very early—like in the midst of setting up the ProjectLoggingContext—we have all the machinery set up to log information like that the build started, but then we unregister the relevant handlers before we actually log that we'd failed.
Do not unregister handlers until shutdown
I tested with the repro from #9455, and it now looks like this:
```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
MSBUILD : error MSB4017:     Exception of type 'System.Exception' was thrown.
MSBUILD : error MSB4017:        at Microsoft.Build.BackEnd.Logging.ParallelConsoleLogger.ProjectStartedHandler(Object s
ender, ProjectStartedEventArgs e) in C:\GitHub\msbuild\src\Build\Logging\ParallelLogger\ParallelConsoleLogger.cs:line 5
86
MSBUILD : …
```

Log before unregistering Fixes #9455

---

eng/dependabot/Packages.props

This version should fix the issue which keeps APIScan from being able to run.

Update Microsoft.BuildXL.Processes to 0.1.0-20240113.1

---

src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs

Fixes https://github.com/dotnet/msbuild/pull/9578#issuecomment-1893514072
Forwarding logger might be configured to forward messages of particular importance regardless of the verbosity level of said logger.
`GetMinimumMessageImportance` should properly reflect that
Manual testing with the repro case (building msbuild with terminal logger)

Bugfix forwarding logger

---

eng/Versions.props

Fixes - broken VS 17.9 insertion due to forgotten version bump
I forgot to add a version bump for the following merges
* https://github.com/dotnet/msbuild/pull/9615
* https://github.com/dotnet/msbuild/pull/9486

[17.9] Bump version after recent vs17.9 merges

---

eng/Versions.props

We intentionally have `DotNetFinalVersionKind` on aa same line as `VersionPrefix` so that codeflow to main causes conflict that needs to be manually resolved and hence we do not end up with unnoticed uninteded version prefix revert in main due to merged codeflow.
Recent arcade update reformatted our Version.props: https://github.com/dotnet/msbuild/pull/9574 - so fixing it back

[17.9] Formatting changes to prevent unnoticed version merges into main

---

documentation/NETFramework-NGEN.md
src/Build/Microsoft.Build.csproj
src/Build/Utilities/NuGetFrameworkWrapper.cs
src/MSBuild/XMake.cs

The secondary AppDomain hosting `NuGet.Frameworks` was set up with a binding redirect for `Microsoft.Build` but not its dependencies. Additionally, `MSBuild.exe` loader policy was set to `MultiDomainHost`, making it possible to share only Framework assemblies between AppDomains, but still loading MSBuild assemblies domain specific. These issues were resulting in NGEN rejections at run-time.
Made the `GenerateAppDomainConfig` target use all binding redirects from `MSBuild.exe.config` and switched to `MultiDomain` loader policy. Also pluralized the relevant identifiers (redirect -> redirects).
Experimental VS insertion with PerfDDRITs & Speedometer runs.

Use all MSBuild binding redirects in NuGet.Frameworks AppDomain

---

src/Utilities/ToolTask.cs

Fix for https://github.com/dotnet/msbuild/issues/9404
We currently do not send the cancelation event to tasks being run by `ToolTask`, as such, many children task take a long time to cancel, and sometimes they finish executing before said cancelation. 
This change makes it possible for inherited classes to access the process and check the cancelation event during execution.
Separated the start of the process to another function that is overridable, as well as exposing the process information.
Issue will only be closed once C++ team has incorporated this change into the `CustomBuild` task.

ToolTask process start separated to another function

---

src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj

Add Microsoft.BuildXL.Processes PackageReference in Bootstrap project
This an existing issue exposed (somehow) by #9634. In particular, `System.Threading.Channels.dll`, an indirect dependency, is missing from the bootstrap output.

Add Microsoft.BuildXL.Processes PackageReference in Bootstrap project

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes https://github.com/dotnet/roslyn/issues/71678
Building with `dotnet build -p:langversion=X` then with `dotnet build -p:langversion=Y` considers the build up to date.
Include LangVersion as `CoreCompileCache`
-

Add LangVersion to `_GenerateCompileDependencyCache`

---

eng/Build.props
eng/SourceBuild.props

Contributes to VMR work: https://github.com/dotnet/source-build/issues/3926
Changes are from https://github.com/dotnet/dotnet/pull/46
No functional changes introduced.

Condition source-build specific configurations on DotNetBuildFromSouce

---

src/MSBuild.UnitTests/XMake_Tests.cs

PR review of #9677 revealed some of the tests that are not using the test environment functionality which will help to reduce the code.  
Align the usage of the tests to use the functionality of test environment. 
Changed tests should pass

Align the tests usage of test environment

---

eng/Versions.props
src/Tasks/ManifestUtil/PathUtil.cs

Fixes #
AB#1939151
Uri class when passed a GB18030 string with chars in the PUA range incorrectly encodes the PUA chars.
For e.g. if the PUA char is u+e038, Uri encodes it in UTF-8 as %25EE%2580%25B8 instead of %EE%80%B8 by double encoding the %.
The ClickOnce scenario that is failing is when an app's Installation Uri is set to a UNC path that has PUA chars. In this case, the UNC path is written to the Clickonce manifest. When the app is being installed, ClickOnce Runtime will attempt to download the deployment manifest from the UNC path. Since the Uri is incorrectly encoded, this download will fail.
The FormatUrl function is being updated to resolve this issue. This function takes input path as string and return a canonicalized path by constructing a Uri class with the input path and …

[vs17.9] [ClickOnce] [GB18030] Workaround for incorrect encoding of chars in the PUA range of file paths

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Fixes #9676
Autocomplete list when editing a Directory.Build.props file in VS doesn't include the properties `UseArtifactsOutput` and `ArtifactsPath`.
Add the properties to XSD file for the autocomplete list.
N/A

Add UseArtifactsOutput and ArtifactsPath to XSD

---

Directory.Build.props
eng/AfterSigning.targets
eng/Packages.props
eng/SourceBuild.props
eng/Versions.props
src/Build/Microsoft.Build.csproj
src/Deprecated/Engine/Microsoft.Build.Engine.csproj
src/Directory.Build.targets
src/Framework/Microsoft.Build.Framework.csproj
src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
src/MSBuild/MSBuild.csproj
src/Package/DevDivPackage/DevDivPackage.csproj
src/Tasks/Microsoft.Build.Tasks.csproj

This enables building msbuild from within the VMR in non source-only modes.
- Disable building type libraries when building on Core, and looking to package them up.
- Bootstrap build should look for DotNetRoot, not RepoRoot. This will correctly pick up the global SDK from the VMR.
- Exclude a couple projects that are VS specific and cause issues (typically packaging TLBs)
- Don't look to copy net3.5 targeted PDBs when building on Core.

Changes to enable building msbuild with Unified Build

---

src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs

@jeffkl has a case with potentially thousands of items that would all go into one bucket in the Returns. MSBuild is deduplicating it, but so is NuGet, which is wasteful, so he will likely stop using Returns. This change will save him a small amount of allocations, but it would save a ton of allocations if he were to keep using it, since it will no longer need to repeatedly reallocate the HashSet, and it won't need to allocate as many Lists. It will still save one List's worth of allocations on every single Target that doesn't have a Returns.
Effectively making List allocations lazier and taking advantage of ToList to avoid doing as many (duplicated) collection operations.

TargetEntry optimizations for Results

---

src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/XMake.cs

Fixes #9507
The ignoreProjectExtensions are not respected if specidified in response file on project level. 
The exception will be thrown in case there are ambiguous files identified in provided directory. Example:
Directiory contains: 
>     1.sln 
>     2.csproj 
The build fails since there are multiple files identified to build. 
IgnoreProjectExtensions: .sln solves the situation but when specified in response file on project level the error will raise before the usage of the response file. 
Identifying projectFile was extracted from CheckAndGatherProjectAutoResponseFile, and moved to ProcessCommandLineSwitches. 
Added specific to the case test case
All existing tests should pass

Respect response files (ignoreProjectExtensions) property

---

src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs
src/Tasks.UnitTests/AssemblyDependency/ResolveAssemblyReferenceTestFixture.cs
src/Tasks/AssemblyDependency/AssemblyResolution.cs
src/Tasks/AssemblyDependency/DirectoryResolver.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs
src/Tasks/AssemblyDependency/ResolutionSearchLocation.cs
src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs
src/Tasks/AssemblyDependency/Resolver.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Fixes #9408
When building this project from a Developer Command Prompt:
```xml
<TargetFramework>net472</TargetFramework>
<ItemGroup>
<Reference Include="$(DevEnvDir)\..\..\MSBuild\Current\Bin\Microsoft.Build.dll" />
<Reference Include="Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
</ItemGroup>
</Project>
```
That produces this RAR snippet for Framework:
```
Primary reference "Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". (TaskId:59)
Resolved file path is "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Microsoft.Build.Framework.dll". (TaskId:59)
Reference found at search path location "C:\Program …
```

Annotate RAR SearchPaths added because they're "next to a reference"

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes #9703
@jaredpar hit this while investigating a Roslyn build process optimization, and it made him sad. We don't want sad @jaredpar.
The property's existing value is prepended to the default dependency target names, like in #4922.
None

Allow users to influence the value of CreateSatelliteAssembliesDependsOn

---

src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
src/Build.UnitTests/Evaluation/ProjectSdkImplicitImport_Tests.cs
src/Build/BackEnd/Components/SdkResolution/CachingSdkResolverLoader.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
src/Framework/Traits.cs

Fixes #9506
In `dotnet build`, resolving in-box Sdk's has suboptimal performance. Resolver assemblies are loaded into the process even in cases where the project asks for Sdk's like `Microsoft.NET.Sdk`, which can be looked up trivially. And in fact, they are looked up trivially but only after resolver assemblies have been loaded and invoked.
The inefficiency is shown by the recently added logging:
There is also a subtle and confusing functional difference between `MSBuild.exe` and `dotnet build` where a NuGet package may take precedence over an in-box Sdk in `dotnet build`, but the same is not possible in `MSBuild.exe`.
Made the default resolver handle the Sdk resolution first, before external resolvers are consulted. This is better perf-wise and aligns with `MSBuild.exe`, please see the …

Optimize SDK resolution in dotnet build

---

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Directory.BeforeCommon.targets

Fixes https://github.com/dotnet/msbuild/issues/8967
Users sometimes use different distributions to build projects, however some files available in the VS distribution are not available with `dotnet build`. It used to throw a "File not found" error, but now it is switched to "this imported project is in a VS distribution".
An example message is: ` error MSB4278: The imported project $(MSBuildE
xtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\DSLTools\Microsoft.DslTools.settings.targets is from the
Visual Studio distribution of MSBuild. Build with MSBuild.exe in a Developer Command Prompt.`
Before throwing a `invalidProject` error for file not found, check the path of the file if it is within Visual Studio. If it is, throw new error instead.

Checking for VS pathing when import not found

---

src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs
src/Build/Utilities/EngineFileUtilities.cs

Fixes #9736
During the improvement of item evalution #9047, the MsBuildSkipEagerWildCardEvaluationRegexes  variable was skipped for some cases: When the exclude was defined with MsBuildSkipEagerWildCardEvaluationRegexes. It resulted the listing of the non needed file (according to lazyload)
Changed the priority of the lazyLoading regex. Firstly it will compare it and then will check if it is nowildcard file with no exclusions 
Added failed scenario to existing test: LazyWildcardExpansionDoesNotEvaluateWildCardsIfNotReferenced.

Change the priority order of lazyloading

---

documentation/wiki/MSBuild-Environment-Variables.md

Fixes #9739
Please see the description in attached issue
Added the new file in wiki, which will describe the behavior and usage of different environment variables that are being respected and used  in MSBuild. 
Nothing to test
Next steps would be to transfer all environment variables from https://github.com/dotnet/msbuild/blob/main/documentation/wiki/MSBuild-Tips-%26-Tricks.md to have a separate well indexed file for easy search.

Init of msbuild env variables document

---

eng/Versions.props
src/Tasks/ManifestUtil/PathUtil.cs

Fixes [AB#1957157](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1957157)
Uri class when passed a GB18030 string with chars in the PUA range incorrectly encodes the PUA chars.
For e.g. if the PUA char is u+e038, Uri encodes it in UTF-8 as %25EE%2580%25B8 instead of %EE%80%B8 by double encoding the %.
The ClickOnce scenario that is failing is when an app's Installation Uri is set to a UNC path that has PUA chars. In this case, the UNC path is written to the Clickonce manifest. When the app is being installed, ClickOnce Runtime will attempt to download the deployment manifest from the UNC path. Since the Uri is incorrectly encoded, this download will fail.
The FormatUrl function is being updated to resolve this issue. This function takes input path as …

[vs17.8] Workaround for incorrect encoding of PUA range in GB18030 Uri string

---

eng/SourceBuildPrebuiltBaseline.xml
eng/dependabot/Packages.props

While looking at something else, I noticed that these references were stale.
(This should be automated but https://github.com/dependabot/dependabot-core/issues/7206.)

Bump some System.* deps to 8.0.0

---

src/Build.UnitTests/Definition/ProjectEvaluationContext_Tests.cs
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Context/EvaluationContext.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Framework/Features.cs

Contributes to [AB#1811625](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1811625)
`EvaluationContext` is a container for various cached state, improving the performance of project evaluation. Sharing this state between evaluations is currently all-or-nothing, which has been identified as a blocker for wider adoption of `EvaluationContext` in Visual Studio scenarios.
Added a new `SharedSDKCache` sharing policy with the semantics of sharing only SDK resolutions. Specifically, it does not allow sharing of general file system state, which could lead to over-sharing when used during VS background processing.
Extended existing unit tests.
In retrospect, it may have been more appropriate to make `SharingPolicy` bit flags with each piece of cached data …

Add EvaluationContext.SharingPolicy.SharedSDKCache

---

src/Build/Definition/Project.cs

Hey! Looks like the DebuggerDisplayAttribute didn't work since there's no ``_data`` field on ``ProjectLink`` abstract type

Fix [DebuggerDisplay] for Microsoft.Build.Evaluation.Project

---

Directory.Build.targets

Fixes #9720
MSBuild is now using the 201 SDK. This also breaks usage of the dotnet msbuild engine in VMR builds.

Remove api compat workaround

---

Directory.Build.targets

Reverts dotnet/msbuild#9791
Fixes the failing build (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9155329&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=94418e61-6648-5751-f7d4-a14f4e5e2bb7&l=157)

Revert "Remove api compat workaround"

---

src/MSBuild/XMake.cs
src/Shared/Constants.cs
src/Tasks.UnitTests/ProjectExtensionsImportTestBase.cs
src/Tasks/Microsoft.Common.CrossTargeting.targets
src/Tasks/Microsoft.Common.props
src/Tasks/Microsoft.Common.targets

Fixes #9512
During restore, MSBuild needs to evaluate the entry project and during this evaluation if any of the project extension files that NuGet generates (`project.nuget.g.props` and `project.nuget.g.targets`) they are used during the next restore.  Another side effect is the files that exist on disk at the beginning of restore are embedded in the binary log and not the ones that are generated by NuGet.
Introduced a new property `MSBuildIsRestoring` which is set during an implicit restore (`/restore`) or an explicit restore (`/Target:restore`) so that we don't need to take a dependency on `MSBuildRestoreSessionId`.  This is now a property users can key off of to detect if a command-line based restore is running.  
Default `ImportProjectExtensionProps` and …

Do not import project extensions during restore

---

src/Build.UnitTests/Graph/GraphTestingUtilities.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/Graph/GraphBuilder.cs
src/Build/Graph/ProjectGraph.cs
src/Build/Graph/ProjectGraphNode.cs
src/Build/Graph/ProjectInterpretation.cs

Fixes https://github.com/dotnet/msbuild/issues/9769
The calculation of project type during Project Graph construction happens four times per project instance when instead it could be calculated once and the value re-used.
The `ProjectGraphNode` constructor now calculates the value for "project type" and stores it with an internal property that is read when constructing the graph.
Updated unit tests which were checking this value.
I got rid of all the helper methods and replaced them with simple checks like `ProjectType == ProjectType.OuterBuild` because these helpers aren't really necessary for simple checks like the value of an enum.

Determine ProjectGraphNode ProjectType once

---

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/UnitTests.Shared/ObjectModelHelpers.cs

Fixes #9502
This change checks the entry point nodes in a graph to see if any targets are specified. This will error similarly to non-graph builds when the project has no targets.
Tested using a project with the content: `<Project />`.
Non-graph behavior:
Current graph behavior (incorrect):
New graph behavior (corrected):
Note: Non-entry points without targets actually are not a problem. In the non-graph scenario, the (valid) referencing project will execute `_GetProjectReferenceTargetFrameworkProperties` which calls `GetTargetFrameworks` on the referenced project. If the target doesn't exist (or in this case, *no* targets exist), then the call no-ops (due to `SkipNonexistentTargets="true"` being set) and the `ProjectReference` is essentially filtered out.

[Graph] Emit NoTargetSpecified when an entry point project doesn't have any targets

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

This is one part of https://github.com/dotnet/sdk/issues/16325, identifying two areas where inputs to the CoreCompile Target (via the Csc/Fsc/etc Tasks) aren't tracked consistently.
Fixes part of https://github.com/dotnet/sdk/issues/16325
Adds Deterministic and PathMap properties, neither of which are Paths and so cannot be coerced into an Item for use in the Target Inputs, to the tracking cache property file.

Add Determinism/SourceLink related Properties to Corecompile dependency checks

---

eng/Packages.props
eng/Versions.props
src/Directory.Build.targets
src/Tasks/Microsoft.Build.Tasks.csproj

Contributes to https://github.com/dotnet/source-build/issues/4175
GenAPI isn't used anymore in msbuild so remove the property that still existed for it. Stop using the toolset compiler in msbuild which isn't necessary given that the SDK compiler is recent enough.

Remove genapi mentions and stop using toolset compiler

---

src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/Build.UnitTests/Utilities_Tests.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/MSBuild/OutOfProcTaskHostNode.cs
src/Shared/CommunicationsUtilities.cs
src/Shared/UnitTests/CommunicationUtilities_Tests.cs

Fixes [AB#1527557](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1527557)
The .NET Framework implementation of `Environment.SetEnvironmentVariable` has a hard-coded check for the 32,767 character limit and exceeding it fails the call with `ArgumentException`. The limit does not exist anymore on modern Windows and we've started seeing users run MSBuild in environments with very long variables. This is problematic because MSBuild contains logic to restore the environment, so even if the particular variable is not really used, we may end up trying to set it to an excessively long value.
- Made `CommunicationUtilities.SetEnvironment` use a P/Invoke to `kernel32!SetEnvironmentVariable` on .NET Framework, to work around the problematic BCL implementation. …

Support environments with long variable values

---

src/Build.UnitTests/BackEnd/EventSourceTestHelper.cs
src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs

Related #9793
In case there are logical changes in usage of eventsource logs which is one of the logging part of the application the coverage by tests of the changed code is missing.
In order to cover this part with minimum testing against braking by accident adding the eventListener for the "Microsoft-Build" event source with an example test. 
EventSourceTestHelper will subscribe to the events from "Microsoft-Build". 
will save the events in-memory store and once GetEvents is called, the in-momory store cleared. 
Testing functionality added and test using newly introduced class

Test for eventsource logs

---

.github/ISSUE_TEMPLATE/01_bugreport.yml
.github/ISSUE_TEMPLATE/02_performanceissue.yml
.github/ISSUE_TEMPLATE/03_mybuildisbroken.yml
.github/ISSUE_TEMPLATE/05_unhandledexception.yml
.github/ISSUE_TEMPLATE/06_feature_request.yml
documentation/wiki/Labels.md

We do not use `needs-triage` label anymore. Instead, we started to use label `triaged` during the triage meetings.

Remove needs-triage label from templates

---

src/MSBuild.UnitTests/XMake_Tests.cs
src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Fixes [#9834 ](https://github.com/dotnet/msbuild/issues/9834)
Internal MSBuild Error: Missing resource 'MissingGetResultFileError"
Add the resource MissingGetItemError in the resource file

Add MissingGetResultFileError in resource file

---

eng/config/OptProf.runsettings

Pipeline failures when `Data collector 'Lingering Process Collector' message: [2024-03-08T14:24:03] The shutdown command 'C:\Test\VisualStudio\MSBuild\Current\bin\Roslyn\VBCSCompiler.exe' for 'VBCSCompiler' failed to close the process. StdOut: , StdError: , Exit code: 0.` occures.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9211811&view=results
According to guideline https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/890/LingeringProcessCollector ,
handling for LingeringProcessCollector was extended.

Fix LingeringProcessCollector pipeline failure

---

.opt-prof.yml

Adding Production tags for OptProf CI pipeline to force pipeline to pick the build/commits marked as 'production' for improved reliability.
Existing optprof failures.
Inspired by @mtylerMSFT work for VS.

Add production tags for OptProf CI

---

documentation/wiki/ChangeWaves.md
eng/Versions.props
src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
src/MSBuild/app.amd64.config
src/MSBuild/app.config

This reverts commit 6257b8ee53833e060efd7b7c4cdbda5789ab17b5 (#9439)
Fixes [AB#1974814](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1974814/) / [AB#1993507](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1993507)
The change added a binding entry for `Newtonsoft.Json` to `msbuild.exe.config`. It turned out that `Microsoft.DotNet.MSBuildSdkResolver` may not be installed (it is not an always-present component like MSBuild itself). The dangling entry makes `Newtonsoft.Json` fail to load into the MSBuild process. The assembly may be needed as a dependency of a task or another SDK resolver, for example.
The change is reverted.
Verified that the failing scenarios work without the problematic entry in `MSBuild.exe.config`.

Revert "Load Microsoft.DotNet.MSBuildSdkResolver into default load context"

---

.vsts-dotnet.yml

We need to adapt official templates for production pipelines
There is a warning on sbom generation - it will be resolved on the servicing side in scope of 
https://github.com/dotnet/arcade/issues/14560
Yes, by using exp branch: https://tfsprodwus2su6.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/DevDiv/_build/results?buildId=9236625&view=results

Use templates-official for production pipeline + @self

---

.config/1espt/PipelineAutobaseliningConfig.yml
.config/guardian/.gdnbaselines

This pull request includes baselines **with an expiration date of 180 days from now** automatically generated for your 1ES PT-based pipelines. Complete this pull request as soon as possible to make sure that your pipeline becomes compliant. Longer delays in completing this PR can trigger additional emails or S360 alerts in the future.
1ES PT Auto-baselining feature helps capture existing violations in your repo and ensures to break your pipeline only for newly introduced SDL violations after baselining. Running SDL tools in break mode is required for your pipeline to be compliant. Go to https://aka.ms/1espt-autobaselining for more details. **Please do not Abandon this PR.** Please reach out to 1ES PT for support. More details: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-sy …

Port auto-generated baselines by 1ES Pipeline Templates from ADO mirror repo

---

.vsts-dotnet.yml

Enables 1ES checks and disables excessive SBOM generation.
+ enableSymbolValidation=true, since https://github.com/dotnet/arcade/issues/2871 was resolved
Validated in scope of https://tfsprodwus2su6.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/DevDiv/_build/results?buildId=9243447&view=results

Fix 1es warnings + enableSymbolValidation

---

src/MSBuild/XMake.cs

Fixes #9694
For console logger, the message is not readable for some languages such as Korean if the system code page is not UTF-8.
Set console output encoding to UTF-8 to support all languages on OSes that support UTF-8.
- On Core unconditionally set the encoding
- On Full framework set the encoding if the OS system locale is non-English. 
Test the fix with msbuild task `Message`/`Warning` that contains Chinese/Korean/Japanese using the following cases.
- `dotnet build` on OS with English locale
-  msbuild.exe on OS with English locale (this requires set the env var `DOTNET_CLI_UI_LANGUAGE`)
- `dotnet build` on OS with Chinese locale
-  msbuild.exe on OS with Chinese locale

Make console output encoding support all languages

---

src/Framework/Features.cs
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_SucceededWithWarnings.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_SucceededWithWarnings.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummary_SucceededWithWarnings.Windows.verified.txt
src/MSBuild.UnitTests/TerminalLogger_Tests.cs
src/MSBuild/TerminalLogger/TerminalLogger.cs
src/StringTools/SpanBasedStringBuilder.cs

Fixes #9666
Adding proper support for multiline messages (with indentation). 
Removed project name from message line.
Terminal logger uses different parsing and rendering.
Unit tests were updated + manual testing (Windows)
New output:
```console
MSBuild version 17.10.0-dev-24101-01+36ab632fa for .NET Framework
XUnitTestProject succeeded with warnings (0,2s)
C:\TestProjects\XUnitTestProject\XUnitTestProject\XUnitTestProject.csproj(26,0): warning : 
A
Multi
Line
Warning.
```

Proper support for multiline messages

---

.vsts-dotnet.yml

In scope 1es migration effort, set of required params was missed.
This pr returns the required part.
The comparison is better here: https://tfsprodwus2su6.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/DevDiv/_git/DotNet-msbuild-Trusted/commit/5977c9ba0241aa60751cd92e37c02120a368f3f5?refName=refs%2Fheads%2Fvs17.9&path=%2F.vsts-dotnet.yml&_a=compare
Unfortunately, the experimental run didn't catch it in time due to different env variables https://tfsprodwus2su6.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/DevDiv/_build/results?buildId=9281418&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=94418e61-6648-5751-f7d4-a14f4e5e2bb7&l=41

[release/vs17.9] Return params for CIBuild run

---

.github/policies/resourceManagement.yml

Fixes #9425
Add a reminder feature to run VS Perf DDRITs when deployed assemblies change. Double-check that we run perf ddrits early when we change the assemblies we ship with (or the .swr in general).
Use resourceManagement policy to add a comment to remind the author of pull request that has the change to *.swr file.

Add the reminder to run VS Perf DDRITs when deployed assemblies change

---

src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
src/Framework/GeneratedFileUsedEventArgs.cs

`GeneratedFileUsedEventArgs` do not need to be written to binlog. It's important to have the generated file being embedded into the binlog files, other than that the event doesn't bring additional value.
While forward compatibility of binlog allows us to introduce new events (or events additions) without breaking the viewer - there is still a minor impact that can confuse some users:
So it's safer to not to write the event now.
Mid-term, we should think about generalizing the event - so that it can be used for other scenarios (e.g. response file, .editorconfig file etc.), with the same structured format - https://github.com/dotnet/msbuild/issues/9906
Made `GeneratedFileUsedEventArgs` internal and dismounting sending it to the binlog (but kept the pushing of the generated file content …

Make GeneratedFileUsedEventArgs internal

---

.vsts-dotnet.yml

Pipeline fails due to  SourceBranch value. 
IbcBranchName seems to be applicable for main only, get back to IbcSourceBranchName
Build log:
https://tfsprodwus2su6.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/DevDiv/_build/results?buildId=9290067&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=94418e61-6648-5751-f7d4-a14f4e5e2bb7&l=41

Change the SourceBranch to IbcSourceBranchName

---

src/Shared/Resources/Strings.shared.resx
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

I have a PR out to make use of the environment variable that leads to this message when you try to enumerate your drive.
From the SDK's perspective, however, this message is a bit confusing because it talks about some specific ItemGroup, whereas the reality is probably that it came from some MSBuild code you didn't write, and the real problem is that you're building at the root of your drive.
I think this wording is an improvement but not perfect. For instance, it isn't a problem if your current working directory is the drive root as long as you specify a project that isn't there, but I don't just want to say 'that your project isn't at the drive root' because if you try to build without specifying a project while at the drive root (as with `dotnet new`), it'll fail, and you'll be …

Proposed rewording for error message when enumerating drive

---

src/Build/Logging/SimpleErrorLogger.cs
src/Framework/ILogger.cs
src/MSBuild/TerminalLogger/TerminalLogger.cs

`ILogger.Parameters` is documented as allowing a `null` value. This change updates the annotation accordingly.
CPS explicitly returns null from its implementation of this interface.

Null annotate ILogger.cs

---

.vsts-dotnet.yml

Disable localization vs17.9

---

src/Build/Construction/ProjectRootElement.cs
src/Framework/BuildEventArgs.cs
src/Framework/CustomBuildEventArgs.cs
src/Framework/XamlTypes/BaseProperty.cs

Fixes [#9766](https://github.com/dotnet/msbuild/issues/9766)
There are some documentation issues we should fix: https://github.com/dotnet/msbuild-api-docs/pull/39#issuecomment-1953148132
[msbuild-api-docs/xml/Microsoft.Build.Construction/ProjectRootElement.xml](https://github.com/dotnet/msbuild-api-docs/blob/smoke-test/msbuild-api-docs/xml/Microsoft.Build.Construction/ProjectRootElement.xml)
Line 0, Column 0: [Warning: xref-not-found - [See documentation](https://review.learn.microsoft.com/en-us/help/platform/validation-ref/xref-not-found?branch=main)] Cross reference not found: 'Microsoft.Build.Construction.ProjectRootElement.MarkDirty(System.String,System.String)'.
[msbuild-api-docs/xml/Microsoft.Build.Framework.XamlTypes/BaseProperty.xml](https://github.com/dotnet/msbuild-api-docs/blob/ …

Fix api doc warning

---

documentation/wiki/ChangeWaves.md
src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
src/Build.UnitTests/BackEnd/TaskThatReturnsDictionaryTaskItem.cs
src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
src/Framework/ChangeWaves.cs
src/UnitTests.Shared/MockLogger.cs

Fixes #9827
`TaskParameterEvent` with `TaskParameterMessageKind.TaskInput` is currently used only for parameters that are lists. Parameters that are simple strings are logged as a specially formatted low-importance message.
The binlog viewer contains logic to recognize this special message and recover the Name and Value to be rendered in the viewer UI. Since we will use this event for analyzers, it would be unfortunate to add one more place with this suboptimal processing.
Unified the logic in `TaskExecutionHost` to log all parameters as `TaskParameterEvent` with `TaskParameterMessageKind.TaskInput`. The change is under a change wave check.
- Added a new unit test.
- Compared diagnostic-level output with task parameter logging enabled with and without the change. No differences were found …

Log TaskParameterEvent for scalar parameters

---

documentation/wiki/ChangeWaves.md
src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs

Change https://github.com/dotnet/msbuild/pull/9874 was put behind the change wave 17.10. 
However the version of the change wave should be 17.12 based on https://github.com/dotnet/msbuild/blob/main/documentation/wiki/ChangeWaves-Dev.md#change-wave-versioning
Move the fix behind different change wave version
Existing test was updated to respect new change wave

Move the ConvertToString invariant culture changes under 17.12 changewave

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs

Fixes #9967
The GetType method is still available if called like "gettype" 
Compare the method name ignoring the case
Added two tests
- Cover when it is not allowed
- Cover when GetType is enabled using env variable "MSBUILDENABLEALLPROPERTYFUNCTIONS"

Do not allow GetType and compare ignoring case

---

src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
src/Build.UnitTests/BackEnd/TaskThatThrows.cs
src/Build/BackEnd/Components/Communications/SerializationContractInitializer.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
src/Framework/CriticalTaskException.cs
src/Shared/Debugging/DebugUtils.cs
src/Shared/ExceptionHandling.cs

Fixes #9928
OOM in custom tasks is rethrown to RequestBuilder, where it is logged as an MSBuild bug.
We might try - on best effort basis - to log an error for the task little more up the stack and then continue in unrolling as before. If we succeed - we get better logging experience for the case; if we fail - we get the same experience as before.
* The exception is attempted to be logged in `TaskBuilder`
* `RequestThreadProc` and `BuildAndReport` methods merged into single one - so that writing the 'error dump' file (MSBuild***.failure.txt) is deterministically written before reporting the result back
* Exposing an internal option to re-initialize `DebugUtils.DebugPath` - as this was set before any unit test was given chance to start, so injecting altering env var was not possible.
Added …

Attribute custom task OOM (and other critical exceptions) to the task

---

eng/Versions.props
src/Tasks/GetAssembliesMetadata.cs

fwdport of https://github.com/dotnet/msbuild/pull/9973
The issue is related to the presence of disposable resource that wasn't cleaned up in time.
Absence of dispose causes "warning MSB3026: Could not copy "*.dll". Beginning retry 1 in 1000ms. The process cannot access the file '*.dll' because it is being used by another process. The file is locked by: "MSBuild.exe" and it's presence breaks project building.
Yes, was introduced in scope of https://github.com/dotnet/msbuild/pull/9313/files#diff-0c7ff4eddab39e683e61e6f11011eac73dae76d2574999184b3c0e74f9c2fa10
Manual -the problem wasn't caught locally, but manual testing doesn't expose any side effects.
Low, doesn't contain any changes in logic.

[release/vs17.10] Fix issue with assemblies locking

---

eng/Versions.props

Insertion for VS was generated for the wrong target branch.
The attempt to run it manually for the proper target fails due to package conflicts:
https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=1522691&_a=release-pipeline-progress
We need to generate a new package for VS rel/d17.10

Bump version to 17.10.2

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/543265?_a=files

Manually Update System.Text.Json from 8.0.0 to 8.0.3

---

src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr

This file is missing, leading to errors in the Arm64 flavor of VS
```
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\arm64\Microsoft.Common.CurrentVersion.targets
(6824,3): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bi
n\arm64\Microsoft.Common.Test.targets" was not found. Confirm that the expression in the Import declaration "C:\Program
Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\arm64\Microsoft.Common.Test.targets" is correct, and th
at the file exists on disk.
```
See: https://developercommunity.visualstudio.com/t/Arm64-Unable-to-use-MicrosoftBuildRu/10632924?ref=native&refTime=1712530347328&refUserId=ba1eecbf-9f1b-431b-ba02-0503abd8762c

Include Microsoft.Common.Test.targets in Arm64

---

src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs
src/MSBuild.UnitTests/MSBuildServer_Tests.cs
src/UnitTests.Shared/TestEnvironment.cs

Fixes #9796
With terminal logger enabled by `SET MSBUILDLIVELOGGER=auto`, current tests has the following problems.
- `Message` is ignored by terminal logger currently and this causes tests depending on the message fail. Though #9667 could get messages ptinted in terminal logger, it is a way to opt. To make messages output in console logger and terminal logger both, we need the workaround for printing messages in terminal logger. Affected tests: Microsoft.Build.Engine.UnitTests.MSBuildServer_Tests.
- The environment variable `MSBUILDLIVELOGGER`/`MSBUILDTERMINALLOGGER` affects tests for these two environment variables. Affected tests: Microsoft.Build.UnitTests.TerminalLoggerConfiguration_Tests.TerminalLoggerOnByEnv.
- Enabling terminal logger by the environment variable gets extra more …

Adjust tests with terminal logger enabled

---

src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryDetailedVerbosity_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryDetailedVerbosity_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryDetailedVerbosity_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryDiagnosticVerbosity_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryDiagnosticVerbosity_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryDiagnosticVerbosity_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryMinimalVerbosity_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryMinimalVerbosity_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryMinimalVerbosity_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryNormalVerbosity_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryNormalVerbosity_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryNormalVerbosity_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryQuietVerbosity_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryQuietVerbosity_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintBuildSummaryQuietVerbosity_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintSummaryWithOverwrittenVerbosity_FailedWithErrors.Linux.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintSummaryWithOverwrittenVerbosity_FailedWithErrors.OSX.verified.txt
src/MSBuild.UnitTests/Snapshots/TerminalLogger_Tests.PrintSummaryWithOverwrittenVerbosity_FailedWithErrors.Windows.verified.txt
src/MSBuild.UnitTests/TerminalLogger_Tests.cs
src/MSBuild/TerminalLogger/TerminalLogger.cs

Fixes #9996
The multiline messages indentation processing implies that the message will appear in the structured view under the related project. That is not correct for the Quiet verbosity and for couple of other places, such as rendering the immediate message and cases when the project is not determined.
Make the indentation dependent on where the message would be shown.
Unit tests

Fix indentation of multiline messages in Terminal Logger.

---

src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build.UnitTests/Graph/ProjectGraph_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/Graph/GraphBuilder.cs
src/Build/Graph/ProjectGraph.cs

Fixes #9952
This change adds understanding of "solution traversal" targets to graph builds. The special targets are like "ProjectName" or "ProjectName:TargetName" and can be used to build specific projects in a sln or specific targets on specific projects in a sln.
Also added some missing UTs for `SolutionProjectGenerator` to help my understanding for how these kinds of targets work.

Handle solution traversal targets in graph builds

---

.vsts-dotnet-ci.yml

Fixes #9960
`VersionPrefix` should be updated on each commit to our service branches (vsXX.YY) to prevent clashes of the produced packages with same version that would cause issues later down the VS insertion pipeline.
Though currently we use GH polices to inform us about this, it still requires user action and can be prone to errors.
Add a build step checking version bump on release branches' update. If it's not updated, fail the run with the message asking to update the version.
Need to backport to active release branches.
Tested with test PR #10017.

Check version bump on release branches' update

---

.editorconfig
documentation/wiki/ChangeWaves.md
src/Build.UnitTests/BackEnd/RequestedProjectState_Tests.cs
src/Build.UnitTests/BackEnd/ResultsCache_Tests.cs
src/Build/BackEnd/BuildManager/RequestedProjectState.cs
src/Build/BackEnd/Components/Caching/ResultsCache.cs
src/Build/BackEnd/Shared/BuildRequest.cs
src/Build/BackEnd/Shared/BuildResult.cs
src/Build/Instance/ProjectInstance.cs

Fixes #9458
#9565 had to be reverted because the assumption that results with `BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild` don't have to be cached broke design-time builds in Visual Studio.
Re-did the change, now with full handling of `BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild`.
New and existing unit tests, experimental insertion, manual testing with the problematic design-time build scenario.
Compared to #9565, we now:
- Copy the flags from the original `BuildResult` in the `BuildResult` copy constructor.
- Have `ProjectInstance` remember the project state filter it was created from.
- Implement `IsSubsetOf` operator on `RequestedProjectState`.
- Use the `IsSubsetOf` to determine if a request with `ProvideSubsetOfStateAfterBuild` can be satisfied by the cache.
- …

Fix oversharing of build results in ResultsCache

---

README.md

Three leading spaces will show the bullet nested under the prior numbered item, rather than as a sibling.

Fix bullet point indentation in README

---

src/Build/BuildCheck/Infrastructure/BuildCheckConnectorLogger.cs

In some cases when running BuildCheck during build (non restore phase), the analyzers will not receive any property information and therefore will not trigger correctly.
This is caused by backwards compatibility logger stuff, so " subscribing"  the logger to a newer data format lets the analyzer receive all necessary information to run correctly.
Subscribed logger to newer eventSource version during initialization.

Added eventSource to BuildCheck logger

---

src/BuildCheck.UnitTests/EndToEndTests.cs
src/UnitTests.Shared/RunnerUtilities.cs

Simplifies troubleshooting of timeouting integration tests (like e.g. https://github.com/dotnet/msbuild/issues/10036)

Get life proc output in integration tests

---

src/Framework/CustomBuildEventArgs.cs

Fixes badly formatted caution/warning note and links.
An XML doc comment was not rendering properly due to badly formatted Markdown in a CDATA section.
Add proper formatting for warning note.
Change severity level from Caution to Warning (more appropriate for this situation)
Remove redundant third link 
Tested the equivalent fix in the MSBuild API docs repo:
https://github.com/dotnet/msbuild-api-docs/pull/42
The fix in the API docs repo can be promoted live right away.
The fix here in MSBuild source will take effect once we rebuild the MSBuild API docs XML from source after the next dot release when the NuGet packages are republished.

Fix warning in CustomBuildEventArgs

---

src/MSBuildTaskHost/MSBuildTaskHost.csproj

This fixes incremental build for the MSBuildTaskHost project inside Visual Studio.
Previously, the VS FUTDC would find this input file missing and schedule a call to MSBuild:
> FastUpToDate: Input UpToDateCheckInput item 'D:\repos\msbuild\src\MSBuild.ico' does not exist and is required, not up-to-date.

Fix item spec in project file

---

src/Package/GetBinPaths.Arm64.targets
src/Package/MSBuild.VSSetup.Arm64/MSBuild.VSSetup.Arm64.csproj
src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr

Fixes [#1806513](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1806513)
On the arm64, the build output is not localized as amd64 results.
amd64
arm64
copy all of our loc .resources assemblies to the arm64 .swr file. Same with amd64
Download the experimental VS insertion https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9429933&view=ms.vss-build-web.run-extensions-tab to install the VS.  Set the language as Chinese and find translated.

Fix Arm64 VS not localization

---

src/Build/Microsoft.Build.csproj

S.Security.Principal.Windows moved inbox with .NET 6 and doesn't need to be referenced anymore.
This helps with keeping the dependency graph fresh:

Don't reference S.S.Principal.Windows on .NETCoreApp

---

src/Tasks/BootstrapperUtil/BootstrapperBuilder.cs

Fixes AB#2046752
#9983 introduced a regression in ClickOnce's bootstrapper packages builder code by disposing an XmlReader object while it's still in use.
Fix the bootstrapper builder code that validates package/product XML against a schema file to use the XmlReaderSettings instead of the deprecated XmlValidatingReader class.
Updated code has been verified against valid and invalid schema file. In addition, the ClickOnce publish with bootstrapper products included has been verified.

[ClickOnce] Fix BootstrapperBuilder code to correctly return the list of products available in the packages folder

---

src/MSBuild/TerminalLogger/TerminalLogger.cs

This is a minor perf improvement.
In particular when using the project cache with a high cache rate (thus spamming ProjectFinished events), this lock is taking ~6% of the CPU for the process due to contention. That's a lower bound though because I'm seeing other methods which do take the lock also suffer from high contention (eg `ThreadProc` also takes ~6% CPU), so removing the lock from `UpdateNodeStatus` is likely to reduce contention there as well.
This lock isn't necessary since this operation is a simple object replacement in an array. Other similar operations also don't take a lock, (See the write in `ProjectStarted` and the read in `MessageRaised`) which proves that it's not required.

Remove unnecessary lock in TerminalLogger.UpdateNodeStatus

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BuildCheck/Infrastructure/BuildCheckForwardingLogger.cs
src/Build/Microsoft.Build.csproj
src/MSBuild.UnitTests/XMake_Tests.cs

Contributes to #10068
https://github.com/dotnet/msbuild/issues/9988#issuecomment-2074423550 uncovered a perf regression with BuildCheck.
Portion of the regression was tracked to excessivbe logging of tasks (credit to @ladipro for the initial idea). This PR is trying to address the case.
BuildCheck is bringing in it's own forwarding logger - so that it can properly self-declare the minimum needed tasks verbosity (and in the future influence what events need to be transfered)
The verbosity integrations test
Pre-existing tests on BuildCheck

Create explicit logger forwarder for buildcheck

---

src/Build/Collections/PropertyDictionary.cs

may or may not fix https://github.com/dotnet/installer/pull/19667#issuecomment-2093639748 and may or may not unblock the next one https://github.com/dotnet/installer/pull/19669
@ViktorHofer @MichaelSimons @rainersigwald

cleanup duplicate property implementation

---

eng/BootStrapMsBuild.targets

This has been long done for .NET (core); extend it to the location that the .NET Framework copy of the SDK resolver looks for it too.
Closes #7988.

Disable workload resolver for net472 boostrap too

---

documentation/specs/proposed/BuildCheck-Architecture.md

Add documentation about custom acquisition experience.
Depends on: https://github.com/dotnet/msbuild/pull/10076

Add documentation about custom acquisition 

---

eng/BootStrapMsBuild.targets

Fixes #7988 
Follow-up for https://github.com/dotnet/msbuild/pull/10112

Disable workload resolver for amd64 too

---

src/BuildCheck.UnitTests/EndToEndTests.cs
src/UnitTests.Shared/RunnerUtilities.cs

Investigation #10036
It's puzzling that the process runs for over 30 seconds. We need to observe further after increasing the timeout to see if still fails.
Increase the timeout of running process for observing the tests furhter.
N/A

Increase the timeout of running process for investigating buildcheck tests

---

src/Utilities.UnitTests/ToolTask_Tests.cs
src/Utilities/ToolTask.cs

The `StartToolProcess` method added in #9649 does not allow subclasses to create and return equivalent processes because it does not have access to the exit, stdout, and stderr event handlers subscribed in the incoming `Process` object. In C# it is not possible to get the invocation list of an event outside of its declaring class.
Made `ReceiveExitNotification`, `ReceiveStandardErrorData`, and `ReceiveStandardOutputData` protected to expose them to subclasses.
A new unit test exercising the scenario.

Expose ToolTask exit, stdout, and stderr handlers

---

src/Build/Evaluation/ProjectRootElementCache.cs

The method `GetOrAdd` has two overloads with two arguments:
```csharp
GetOrAdd(string key, object value);
GetOrAdd(string key, Func<string, object> valueFactory);
```
The lambda here does not take an argument hence it's not compatible with `Func<string, object>`. It is compatible with `object` though because a delegate can convert to `object`.
This is problematic because there is no guarantee the delegate here is unqiue. The compiler is free to cache instantiations of delegates, particularly ones like this which capture no state. That means different keys could very well be sharing the same value.
Fixes #

Fix incorrect use of GetOrAdd

---

src/UnitTests.Shared/RunnerUtilities.cs

https://github.com/dotnet/msbuild/pull/10133 added option to increase test timeout - but the error message reamins same - which can be confusing.

Fix test utils wording

---

src/Framework/Logging/AnsiDetector.cs
src/Framework/NativeMethods.cs
src/MSBuildTaskHost/MSBuildTaskHost.csproj

Fixes #9950
Improved detection of ansi support using the "TERM" environment variable.
Added the list of supported terminal types.
Manual tests

Improve the detection from TERM value

---

src/Build/Evaluation/Conditionals/OperatorExpressionNode.cs

Fixes - insertion issue
Dereferencing null can happen
```
D:\VS\src\ConfigData\BuildTargets\Microsoft.DevDiv.Common.Targets(800,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [D:\VS\src\edev\diagnostics\intellitrace\Tests\Functional\ProfilerTypeSpecTestsCodeGen\ProfilerTypeSpecTestsCodeGen.csproj]
D:\VS\src\ConfigData\BuildTargets\Microsoft.DevDiv.Common.Targets(800,5): error MSB4018:    at Microsoft.Build.Evaluation.OperatorExpressionNode.IsUnexpandedValueEmpty() [D:\VS\src\edev\diagnostics\intellitrace\Tests\Functional\ProfilerTypeSpecTestsCodeGen\ProfilerTypeSpecTestsCodeGen.csproj]
```
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9615450&view=logs&j=018464ba-1ca1-5561-2761-cd93078ac78a&t=3574efd9-071a-5092-469d-6 …

Fix nullref exception in expander refactoring

---

src/Build/BuildCheck/Acquisition/BuildCheckAcquisitionModule.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj
src/BuildCheck.UnitTests/TestAssets/AnalysisCandidate/nugetTemplate.config
src/BuildCheck.UnitTests/TestAssets/AnalysisCandidateWithMultipleAnalyzersInjected/AnalysisCandidateWithMultipleAnalyzersInjected.csproj
src/BuildCheck.UnitTests/TestAssets/AnalysisCandidateWithMultipleAnalyzersInjected/nugetTemplate.config
src/BuildCheck.UnitTests/TestAssets/Common/CommonTest.props
src/BuildCheck.UnitTests/TestAssets/Common/CommonTest.targets
src/BuildCheck.UnitTests/TestAssets/CustomAnalyzer/CustomAnalyzer.csproj
src/BuildCheck.UnitTests/TestAssets/CustomAnalyzer/README.md
src/BuildCheck.UnitTests/TestAssets/CustomAnalyzer2/CustomAnalyzer2.csproj
src/BuildCheck.UnitTests/TestAssets/CustomAnalyzer2/README.md
src/BuildCheck.UnitTests/TestAssets/InvalidCustomAnalyzer/InvalidAnalyzer.cs
src/BuildCheck.UnitTests/TestAssets/InvalidCustomAnalyzer/InvalidCustomAnalyzer.csproj
src/BuildCheck.UnitTests/TestAssets/InvalidCustomAnalyzer/InvalidCustomAnalyzer.props
src/BuildCheck.UnitTests/TestAssets/InvalidCustomAnalyzer/README.md

The case, mentioned in documentation: https://github.com/dotnet/msbuild/pull/10078#discussion_r1581121235 and build CustomAnalyzer test assets during the build to reduce the test running time.

Handle the case for unsuccessful custom analyzer registration + change e2e tests

---

src/MSBuild/TerminalLogger/Terminal.cs

Fixes #9662
When we use TL, we save the console output encoding to a variable, change the encoding
to UTF8 for the logging duration and attempt to set it back to the previous value during the Terminal Logger shutdown. It fails in some terminal emulators. It seems to be either a bug of the terminal emulator or Console.OutputEncoding property.
Wrapped the setting of the console output in try-catch block.
Unit tests

Fix the crash in the Terminal Logger during shutdown.

---

src/Shared/ExceptionHandling.cs

Fixes #
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748184
Some customers catch out of memory on our attempt to dump errors to local file.
This change prevents a crash from that.

Wrap DumpExceptionToFile with try/catch for outofmemory

---

src/Build.UnitTests/BackEnd/BatchingEngine_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs

Fixes #10180
#10102 made certain batching scenarios fail with a null-ref exception.
Moved the call to `LogTargetBatchFinished` to make sure that the loop doesn't exit with null `targetLoggingContext`.
New unit test with a repro project.

Fix NRE in target batching

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
src/Build/Logging/LoggerDescription.cs

Random discovery - we create NullLogger even when we have other logger(s) registered (e.g. ConsoleLogger, TerminalLogger ...).
We need to make sure that Projcet started and finished events are being transfered - we can 'hijack' the existing registration of ConfigurableLForwardingLogger for that - we just need to inspect and adjust existing registration
Build with just the built-in loggers (TerminalLogger, ConsoleLogger, FileLogger) is probably the most common configuration - and we are injecting extra forwarder to each such a build - so while it's likely very small savings (as only couple events was redundantly de/serialized, rest was quickly skipped) - it applies very broadly.
Following measurements were done using the OrchardCore and bootstrapped release MSBuild.exe with following 3 …

Remove redundant creation of Forwarding logger with NullLogger

---

.exp-insertions.yml

In order to unblock perf-star for .net core scenarios, we agreed to attempt using System.AccessToken to access msbuild.exe drops

Use System.AccessToken to access drops

---

documentation/wiki/UnGAC.md
src/Package/Microsoft.Build.UnGAC/Program.cs

Fixes [AB#2065921
](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2065921)
There was a customer case where StringTools turned out to be GACed. Since they are of a fixed version they are unsuitable for GAC-ing. So let's proactively clear in case anybody GACed them manually.
Same applies for BuildXL binaries.

unGAC stringtools

---

src/Build/BuildCheck/Analyzers/DoubleWritesAnalyzer.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/BuildCheck/Infrastructure/BuildEventsProcessor.cs
src/Build/BuildCheck/OM/BuildCheckDataContext.cs
src/Build/BuildCheck/OM/ParsedItemsAnalysisData.cs
src/Build/Microsoft.Build.csproj
src/BuildCheck.UnitTests/DoubleWritesAnalyzer_Tests.cs
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/TaskInvocationAnalysisDataTests.cs

Fixes #9881
We believe there is value in flagging cases where the same file is written by more than one task during a build. https://github.com/dotnet/source-build/issues/4390 is an example of a recent hard-to-diagnose build issue that could have been prevented by this analyzer.
This PR adds a new built-in analyzer and makes a few supporting changes.
- Existing and new unit tests.
- Built a few larger repos with the analyzer enabled.
The changes contain a fix/workaround for #10176.

[BuildCheck] Implement double writes analyzer

---

src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes partially #9537
Customer reported error caused by SDK resolver returning null in list of message. This can be caused by customer or 3rd party SDK resolver, so additional diagnostics and robustness can help here.
- diagnostic message when this happens
- ignoring null or empty warnings
locally

Null in list of warnings or errors in SDK result

---

src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes #9450
in #9307 an empty catch was added in ProjectImportsCollector.cs
create an event that adds a low priority message if an exception occurs there
an exception in that place occurs only if weird things are happening with the files (e.g. they are edited while read)
did not manage to create an end-to-end test
looking for ideas to make an unit test

Add binlog message in case of failure to add embedded file

---

src/MSBuild/TerminalLogger/TerminalLogger.cs

Both VSTest and testing frameworks (especially xunit) write additional information to screen. Either by writing to console, or by sending Test messages. 
Until now users cannot see the messages on screen which degrades the experience to them. 
This includes not being able to see discovered tests when `--list-tests` is used, or not being able to see output written by tests. 
Adds a test specific message type that we can use to write an immediate message. This is probably not the best fit, but it is the most unified with what is existing on TL right now.
No new tests, I am leaning on what is already there.
This is how it looks like when someone has few tests written in MSTest and Xunit.

Write output from tests

---

src/Build/BuildCheck/Analyzers/SharedOutputPathAnalyzer.cs

Fixes #10235
The analyzer didn't contain proper path normalization - so up directory referencing in a prop definition (e.g. `../someFolder`) could lead to 2 absolute paths perceived as different (e.g. `C:\myproj\lib1\..\common` and `C:\myproj\lib2\..\common`)
Normalizing the path properly
Just a quickfix

Bugfix SharedOutputPath analyzer

---

src/Deprecated/Conversion/ProjectFileConverter.cs
src/Deprecated/Engine/Engine/BuildTask.cs
src/Deprecated/Engine/Engine/Import.cs
src/Deprecated/Engine/Engine/ImportCollection.cs
src/Deprecated/Engine/Engine/Target.cs
src/Deprecated/Engine/Engine/TargetCollection.cs
src/Deprecated/Engine/Engine/Toolset.cs
src/Deprecated/Engine/Engine/ToolsetCollection.cs
src/Deprecated/Engine/Engine/UsingTask.cs
src/Deprecated/Engine/Engine/UsingTaskCollection.cs
src/Deprecated/Engine/Engine/Utilities.cs
src/Deprecated/Engine/Errors/InternalLoggerException.cs
src/Deprecated/Engine/Errors/InvalidProjectFileException.cs
src/Deprecated/Engine/Errors/InvalidToolsetDefinitionException.cs
src/Deprecated/Engine/Errors/RemoteErrorException.cs
src/Deprecated/Engine/Items/BuildItem.cs
src/Deprecated/Engine/Items/BuildItemGroup.cs
src/Deprecated/Engine/Items/BuildItemGroupCollection.cs
src/Deprecated/Engine/LocalProvider/LocalNode.cs
src/Deprecated/Engine/Logging/ConsoleLogger.cs
src/Deprecated/Engine/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
src/Deprecated/Engine/Logging/DistributedLoggers/DistributedFileLogger.cs
src/Deprecated/Engine/Logging/FileLogger.cs
src/Deprecated/Engine/Logging/LoggerDescription.cs
src/Deprecated/Engine/Properties/BuildProperty.cs
src/Deprecated/Engine/Properties/BuildPropertyGroup.cs
src/Deprecated/Engine/Properties/BuildPropertyGroupCollection.cs
src/Deprecated/Engine/Solution/SolutionWrapperProject.cs

Fixes https://github.com/orgs/dotnet/projects/117/views/21?pane=issue&itemId=67244195
The deprecation messages have `<xref>` tag within `<summary>` tag - this is invalid. A CDATA or `<see>` tag should have been used instead
Bulk replaced the invalid xmls in `<summary>` sections:
```
/// <xref:Microsoft.Build.Construction>
/// <xref:Microsoft.Build.Evaluation>
/// <xref:Microsoft.Build.Execution>
```
with 
```
<see href="/dotnet/api/microsoft.build.construction">Microsoft.Build.Construction</see>
...
```

Fix badly formed deprecation xml comments

---

src/Package/GetBinPaths.Arm64.targets
src/Package/MSBuild.VSSetup.Arm64/MSBuild.VSSetup.Arm64.csproj
src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr

These resources were added to the ARM64 subfolder in #10023, but I don't think they're needed: there's no .NET Framework 3.5
for ARM64 and `MSBuildTaskHost.exe` isn't in the ARM64 folder itself, so I think we can remove these files.
There was also a build race condition involving the .resources.dll files, which is how I found this. The `Arm64ProjectReference` wasn't enough to get them built.

Drop MSBuildTaskHost resources from ARM64

---

src/Build.UnitTests/BackEnd/RedirectConsoleWriter_Tests.cs
src/Build/BackEnd/Node/OutOfProcServerNode.cs

This was the intention of the prior call, but `_syncWriter.Flush()` is
a noop because it's a wrapper around a `TextWriter`; instead we need to
flush the `RedirectConsoleWriter` itself, an operation which sends the
accumulated text to the client.

Server: Flush console output periodically

---

eng/dependabot/Packages.props

Update Microsoft.BuildXL.Processes to 0.1.0-20240606.3
This package should now have publicly available symbols as well as being BinSkim clean.

Update Microsoft.BuildXL.Processes to 0.1.0-20240606.3

---

.config/guardian/.gdnbaselines

These results are uninteresting since drop.app is not something MSBuild ships or redistributes, and BinSkim is currently breaking the build. Add to the baseline to get the build working while Arcade is working to update to a new drop.app.
Working build (internal link): https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=9753796&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=f1d06f58-f2d3-5073-fdb4-52901bc804c1&l=222

Additional Guardian baselining

---

.config/git-merge-flow-config.jsonc

Onboarding new merge flow based on the github actions
Added configuration file the flow was copied from: https://github.com/dotnet/versions/blob/main/Maestro/subscriptions.json. Currently it will not be read or change any behaviour of the merge flow but will be used by the new workflow. 
- Documentation https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md
- One pager: https://github.com/dotnet/dnceng/blob/main/Documentation/OnePagers/github-action-inter-branch-merge.md
None -> it is not functionality related changes
The flow from vs17.7 to vs17.8 was not added to the new configuration since the sdk 7 release has reached end of life.
FYI: @pavelsavara , @mmitche

Add the configuration file for merge flow

---

MSBuild.Dev.slnf
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
src/BuildCheck.UnitTests/EndToEndTests.cs
src/Framework/BuildCheck/BuildCheckEventArgs.cs

Fixes #10264
The problem was that here in  `BuildEventArgsWriter.cs` the `RawMessage` is written. And we set `Message` for BuildCheck results not the `RawMessage`.
https://github.com/dotnet/msbuild/blob/4a45d56330882a5e596e97d05ba568ec32e0603c/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L596-L601
Added test

Fix bug: No visible message when replaying analyzed build

---

src/Framework/ErrorUtilities.cs
src/MSBuildTaskHost/MSBuildTaskHost.csproj
src/Shared/ErrorUtilities.cs
src/Shared/UnitTests/ErrorUtilities_Tests.cs

This will help with using these from new code that's nullable-
aware. The biggest helpful bit is the `[NotNull]` ones that let the
compiler know to assume that parameter is non-null in the rest
of the method, which should eliminate the need for some `!`s
after calling `VerifyThrowArgumentNull(whatever)`.

Nullable annotations for ErrorUtilities

---

documentation/specs/proposed/BuildCheck/Codes.md
src/Build/BuildCheck/API/BuildCheckResult.cs

Contributes to #10240
Customer requested to have understandable documentation of individual imposed rules.
Let's follow similar practice we introduced in template engine - with adding short hyperlinks to the outputs, that can then include rich information, that can freely evolve off-cycle.
Added initial document
Added initial code adding the hyperlink

Add initial Buildcheck codes

---

.vsts-dotnet.yml

Adding a comment about localization in order to cause a merge conflict in the next release branch, when we will be disabling the localization in the previous release branch and the change flows automatically to later releases and main. 
See https://github.com/dotnet/msbuild/pull/10269#discussion_r1646558936

Add comment about localization

---

.vsts-dotnet.yml
eng/Signing.props

Fixes #10229 
The builds started to receive warnings. 
Update the build and what we are publishing in artifacts: 
- Removed the bin folder completely. 
- Removed the file that is not generated by msbuild steps, however was not signed.
- Add item to sign after build. 
Tested on experimental branch: exp/f-alizada/code-sign-validation

Update the build template

---

documentation/specs/proposed/BuildCheck-Architecture.md

In the docs we state that we can analyze binlogs of older versions of MSBuild, which is not true.
Removed that part from the doc.

[BuildCheck] Fix docs

---

src/Build/BuildCheck/Infrastructure/BuildCheckCentralContext.cs

BuildCheck E2E tests
##Context
The tests from this class were handing on the CI build periodically
https://github.com/dotnet/msbuild/blob/c2f9b76bb511c2ef4419abe468e81855781c40a1/src/BuildCheck.UnitTests/EndToEndTests.cs#L16
But after adding another build-in analyzer, I was able to spot (thanks to @JanKrivanek !) the deadlock in the Parallel invocation.

Remove blocking parallelization

---

src/Build/BackEnd/Components/Logging/BuildLoggingContext.cs
src/Build/BackEnd/Components/Logging/LoggingContext.cs
src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs

Adds diagnostics for #10342
Attempted logging with invalid context had cryptic error message. It could happen on AssemblyLoadTracker which should be just a transient error.
The exception can be found in the telemetry even in the past - the recent changes only increased likelyhood.
* Improved logging
* Added resiliency to AssemblyLoadTracker

Fix logging context validity check

---

documentation/wiki/ChangeWaves.md
src/Utilities/ToolTask.cs

Fixes #2981
and probably #10286
`ToolTask` can hang when child process spawns a grandchild process that doesn't exit.
Using different overload of `WaitForExit` to avoid situation when grandchild process is keeping the MSBuild waiting.
See https://github.com/dotnet/runtime/issues/51277 and https://github.com/dotnet/msbuild/issues/2981#issuecomment-818581362
Manual testing with custom `ToolTask` implementation. This tasks starts process that starts another process with longer lifetime.

Fix possible ToolTask hang

---

.config/git-merge-flow-config.jsonc

The branches: 
- `vs17.4` is [out of support](https://learn.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#long-term-servicing-channel-ltsc-support). 
- `vs17.9`  is [out of support](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs)
Once the release branch is out of support there is no need to keep it in the merge flow chain of the supported branches.
```mermaid
graph LR;
vs..-->vs17.3;
vs17.3-->vs17.4;
vs17.4-->vs17.6;
vs17.6-->vs17.8;
vs17.8-->vs17.9;
vs17.9-->vs17.10;
vs17.10-->vs...;
```
Removing the `vs17.4` and `vs17.9` from the merge flow chain.
```mermaid
graph LR;
vs..-->vs17.3;
vs17.3-->vs17.6;
vs17.6-->vs17.8;
vs17.8-->vs17.10;
vs17.10-->vs...;
```
No testing, its configuration file

Update the merge-flow configuration

---

src/Build/BackEnd/BuildManager/BuildSubmission.cs
src/Build/Graph/GraphBuildSubmission.cs

Fixes [#AB2134191](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2134191/?view=edit), [#AB2134571](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2134571)
The OM unification (https://github.com/dotnet/msbuild/pull/10172) unified check for validity of the result. However result created from exception has slightly different propertis on GraphBuild and standard build - so the check should not have been unified
Split the result validity check
Will be done through exp VS insertion - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/564498

OM unification Bugfix - Fix result validity check

---

.exp-insertions.yml

Issues with access to msbuild.exe bit for perfstar run.
In order to secure that, a new SP was created and added to the corresponding organization.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9874247&view=logs&j=063f674e-38db-59b9-8dc6-bda499493784&t=d2d8d882-24a4-5280-d5d8-e137cda2c3ba

Handle access to vssps for PerfStar

---

eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

VS would like to consume this updated version and we need to coordinate.

Microsoft.IO.Redist 6.0.1

---

documentation/wiki/ChangeWaves.md
src/Utilities/ToolTask.cs

Fixes #10378
The original modification resulted in an incorrect exit code being returned in certain situations.
Reverting back to original state.

Reverting PR #10297

---

src/Build.UnitTests/BackEnd/BuildOMCompatibility_Tests.cs
src/Build/BackEnd/BuildManager/BuildRequestData.cs
src/Build/BackEnd/BuildManager/BuildSubmission.cs
src/Build/Graph/GraphBuildRequestData.cs
src/Build/Graph/GraphBuildSubmission.cs

Fixes #10349
The OM unification work https://github.com/dotnet/msbuild/pull/10345 introduced backwards compatible unified OM (code compiled against old MSBuild binaries can be run against new MSBuild binaries), but it was not forward compatible (code compiled against new MSBuild binaries could not be run against old MSBuild binaries). This change is bridging such gap.
Adding 'proxy' properties for those that have been pulled to base classes - so that the compiled code is not trying to reference base classes, that do not exist in the old version of MSBuild code.
Manual testing of x-compatibility of the OM.
1. Add a binary (e.g. console app) with code that is using the OM and it's properties - e.g.:
```csharp
Microsoft.Build.Graph.GraphBuildRequestData data =
new(
projectFullPath: "a/b/c", …
```

Add BuildOM forward compatibility

---

src/Build/BackEnd/Components/Logging/TargetLoggingContext.cs
src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs

Fixes #10342
This change workarounds the attempts to log assembly loads via LoggingContext that was invalidated
The `AssemblyLoad` is AppDomain wide - and doesn't 'respect' current thread nor async context. So if we mount it in one execution context and concurrently executing code leads to assembly loading - it'll still be reported. The handler is executed synchronously - meaning the originally mounting code can be continuing execution and eventually invalidating the passed LoggingContext.
The added diagnostic showed the context tha was invalid was `TaskLoggingContext`, it as well showed that it was happening in msbuild within sdk (hence core version).
The `TaskLoggingContext` is passed to Tracker in 2 locations:
https://github.com/dotnet/msbuild/blob/486dbb4a9a7885b8fdcb1f8affd4d63444d8d8 …

Bypass logcontext validity check

---

src/Build.UnitTests/Evaluation/Evaluator_Tests.cs
src/Build/Evaluation/Evaluator.cs

Fixes #10113
Evaluating a project is supposed to send a ProjectEvaluationFinished event. If it fails, however, it doesn't.
Wrap Evaluate in a try/finally block to ensure ProjectEvaluationFinished is always sent
Created a unit test

Always send project evaluation finished Fixes #10113

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs
src/Build/Microsoft.Build.csproj

Fixes #10398
Is fastpath isn't added for the method, it gets resoled by using reflection that is an expensive operation.
Since the covered methods are actively used by the main customers, they were added to MSBuild.
Add the method from the linked tickets.
Covered with unit tests.

Add Expander fast paths for expressions used in .NET SDK 9

---

src/Framework/BuildMessageEventArgs.cs
src/Framework/EnvironmentVariableReadEventArgs.cs

Fixes:
sdk insertion
https://github.com/dotnet/sdk/pull/42215
If importance isn't specified forEnvironmentVariableReadEventArgs , the extra message is emitted.
Return setup the default message severity
Local manual testing

Fix excessive reporting about used environment variable

---

eng/Packages.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props

Fixes https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9977351?typeId=6797870&pipelinesTrackingFilter=0
Lets pin System.Formats.Asn, till the System.Security.Cryptography.Pkcs is available and updated

Pin System.Formats.Asn

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes #
This is to permit users to use functions with out parameters and ref parameters as long as they don't care about the values that come out of them. Specifically, if a parameter is specified by '_', it will look for any method with the right name from the right assembly and try to match based on number of parameters. If there are multiple options, it will throw; if there is only one, it will execute it after tweaking all the _ to have the right type.
I used this project file:
```
<OutputType>Exe</OutputType>
<TargetFramework>net9.0</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable>
<FooProp>$([System.Int32]::TryParse("bah", _))</FooProp>
<Target …
```

Permit throwaway parameters

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

**8.0.3 is marked as vulnerable**
This is needed for https://github.com/dotnet/sdk/pull/42225:
> src\Resolvers\Microsoft.DotNet.MSBuildSdkResolver\Microsoft.DotNet.MSBuildSdkResolver.csproj(160,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Microsoft.DotNet.MSBuildSdkResolver is expected to depend on System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51. This may have consequences for MSBuild.exe binding redirects, please get signoff from the MSBuild team.

Manually update System.Text.Json to 8.0.4

---

eng/Packages.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props

Fixes - some minor whitespaces/ordering mess introduced by https://github.com/dotnet/msbuild/pull/10396
* Extra whitespace removed
* Reordered SourceBuildPrebuiltBaseline.xml and Versions.props to stay alpha-ordered

Declarations cleanup

---

.config/guardian/.gdnbaselines
.vsts-dotnet.yml

This allows us to remove the corresponding entries from .gdnbaselines.

Pass CredScanSuppressions.json to 1ES template

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

This reverts commit 9f69926a2c4347dd7bc98ca636198ece35860b37, to fix #10435.

Revert "Permit throwaway parameters (#10209)"

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes #7528
If a project reference does not exist, we currently throw a warning. It was requested in #7528 that there should at least be an option to make it an error.
Throws a warning or an error, depending on the ErrorOnMissingProjectReference property, if a ProjectReference does not exist.
Tried building a project with a nonexistent project reference with and without that property set to True.
I don't think the discussion on the issue had fully resolved, but I suspect it won't resolve any time soon. Regardless, if you think this is hurtful in any way, feel free to just close it.

Permit erroring on missing project reference Fixes #7528

---

documentation/wiki/ChangeWaves.md
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build.UnitTests/BackEnd/MockLoggingService.cs
src/Build.UnitTests/ConsoleLogger_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/Logging/ILoggingService.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
src/Build/BackEnd/Node/LoggingNodeConfiguration.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Build/Evaluation/Evaluator.cs
src/Framework.UnitTests/ProjectStartedEventArgs_Tests.cs
src/Framework/ProjectStartedEventArgs.cs
src/Shared/UnitTests/TestAssemblyInfo.cs
src/UnitTests.Shared/MockLogger.cs

Fixes #10225, ~~#1976~~
The eval props/items were not attached to `ProjectEvaluationFinishedEventargs` if any logger didn't request `IncludeEvaluationPropertiesAndItems`
In case of VS - the `MuxLogger` is attached as well. So in case that one doesn't set the property (it might be a recent change in VS - I'm not sure) - the values are not being sent neither to binary logger.
Make sure the values are emitted and attached if any logger requests them
Manual (VS with injected Msbuild)
**Experimental VS insertion:** https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/558711
**Experimental VS insertion for the version which can add properties on both event types:** https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/565788 (yet another: …

Emit eval props if requested by any sink

---

src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs

Fixes - binlog reading issue introduced in https://github.com/dotnet/msbuild/pull/10307
When changing readers/writers of BinaryLog format, we need to keep the old formats operatable.
Intoroduced back-compat reading of EnvironmentVariableReadEventArgs

Fix backward compat of EnvironmentVariableReadEventArgs reading

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes https://task.ms/52765087
This PR makes it possible to leverage the built-in APPX tooling for UWP class libraries using modern .NET (for .pri generation).
Previously, `src/Tasks/Microsoft.Common.CurrentVersion.targets` would only import `Microsoft.AppXPackage.Targets` when `WindowsAppContainer` is set. This property is not used on modern .NET (as it also breaks a bunch of other tools that were only meant to work with the previous .NET and infrastructure for UWP). This PR updates the logic to also import the APPX targets for UWP class libraries using modern .NET, and includes an opt-out switch to allow developers to disable this updated functionality if needed (eg. if they wanted to skip .pri generation, or if they wanted to use the lifted toolset from WinAppSDK instead).
This is …

Enable importing 'AppxPackage' tools for modern UWP class libraries

---

src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs

Context for the in-node events were set incorrectly.
This wasn't yet used in any actual processing - so no issue was encountered with this yet

Fix BuildRequest in in-node BuildCheck

---

src/Build/BuildCheck/Infrastructure/BuildCheckConnectorLogger.cs
src/Build/BuildCheck/Infrastructure/BuildCheckForwardingLogger.cs

Fixes #10068
Currently BuildCheckForwardingLogger does not filter out any of the events, which results in extra perf owerhead.
Made BuildCheckForwardingLogger filter out the events that are not used in BuildCheckConnectorLogger.
Unit tests & manual runs

Make BuildCheckForwardingLogger filter the events 

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2173517/
Add validation for the specified value for defined bool props that extends xsd intellisense . It can help some VS customers.
For now, MSBuild doesn't do any check for the property type/content and it's not planned to be implemented.

Change the defined props type from string -> bool

---

src/Build/BuildCheck/Infrastructure/BuildCheckForwardingLogger.cs

Fixes #10471
BuildCheckForwardingLogger events lacks the type of EnvironmentVariableReadEventArgs for used environment variable check and causes test failures https://dev.azure.com/dnceng-public/public/_build/results?buildId=761438&view=ms.vss-test-web.build-test-results-tab.
Add the missing type.
Existing tests.

Add missing type of EnvironmentVariableReadEventArgs to BuildCheckForwardingLogger events

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Today, `GetReferenceTargetPlatformMonikers` and `FindInvalidProjectReferences` use `TargetPathWithTargetPlatformMoniker` instead of the documented `_ProjectReferenceTargetPlatformMonikers` item group for the project reference gathering/validation.
This causes a violation in the ProjectReference protocol, leading to multiple items being returned from `GetTargetPath` and the default (`Build`) target. Returning multiple items from these targets can cause usability problems and unexpected behaviors.
Below is a simplified use case of the one that hit this bug:
A/A.csproj:
```xml
<TargetFramework>net8.0</TargetFramework>
</Project>
```
B/B.csproj:
```xml …
```

Use documented item group in FindInvalidProjectReferences

---

src/Build/BuildCheck/Analyzers/SharedOutputPathAnalyzer.cs
src/BuildCheck.UnitTests/DoubleWritesAnalyzer_Tests.cs
src/BuildCheck.UnitTests/MockBuildCheckRegistrationContext.cs
src/BuildCheck.UnitTests/SharedOutputPathAnalyzer_Tests.cs
src/Shared/FileUtilities.cs

Related to #10414
PR #10238 added normalization of the path (which includes getting full path) before [the project directory path is added to it](https://github.com/dotnet/msbuild/blob/b381fcd79588b14ab2b6ab09cb57035d0336852f/src/Build/BuildCheck/Analyzers/SharedOutputPathAnalyzer.cs#L75). This led to the relative path being turned into a full path using CurrentDirectory instead of the project directory. This leads to enormous amount of false-positive analyzer's warnings (400 instead of 3) that cause the hang. This PR fixes the bug with paths and does not fix actual cause of a hang.
Reverted the PR #10238 and instead added normalization of the path later in the code when the project path is already combined with the relative path.
unit tests and local runs

Fix wrong paths in SharedOutputPathAnalyzer.

---

eng/Versions.props
src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Framework.UnitTests/CustomEventArgSerialization_Tests.cs
src/Framework/TelemetryEventArgs.cs

Fixes [azdo#2174440](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174440)
The serialization of telemetry events assumed that telemetry properties would always have a value - it seems like it's possible for callers to send null values, so we need to be able to handle that. This was triggered with the addition of containers telemetry added in 8.0.400.
Optionally write and read the value string for the telemetry event payload.
Added previously-nonexistent round-tripping tests for this event type.
We'll want to take this to SDK Tactics for servicing, but then to VS QB to see if they want to align releases or let the VS side drift a bit.

[8.0.4xx] Fix serialization of TelemetryEventArgs data packets across MSBuild worker nodes

---

documentation/specs/BuildCheck/BuildCheck.md
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BuildCheck/API/BuildAnalyzerConfiguration.cs
src/Build/BuildCheck/API/EvaluationAnalysisScope.cs
src/Build/BuildCheck/Infrastructure/AnalysisScopeClassifier.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/BuildCheck/Infrastructure/BuildEventsProcessor.cs
src/Build/CompatibilitySuppressions.xml
src/Build/Definition/ToolsetReader.cs
src/BuildCheck.UnitTests/BuildAnalyzerConfigurationEffectiveTests.cs
src/BuildCheck.UnitTests/BuildAnalyzerConfiguration_Test.cs
src/BuildCheck.UnitTests/ConfigurationProvider_Tests.cs
src/Framework/FileClassifier.cs

Contributes to #10469
This is a V1 simplistic implementation of BuildChecks evaluation scoping.
The description of the idea was addedd to the the design PR: https://github.com/dotnet/msbuild/pull/10139/files#diff-c490522e63a226575c540f316cf74f081452a701f25f46093e1781aef22a17adR49-R57
* FileClassifier recognizes nuget cache
* FileClassifier is now responsible to know which properties conatin immutable locations (so that we can set them from EventArgs as well)
* BuildCheck makes sure to initialize FileClassifier if SchedulerNode doesn have an implicit in-proc WorkerNode
* FileClassifier is being leveraged to perform the classificaion
Existing tests

Add initial scoping implementation

---

src/Build/BuildCheck/API/BuildCheckResult.cs
src/Build/BuildCheck/Checks/PropertiesUsageCheck.cs
src/Build/BuildCheck/Infrastructure/CheckScopeClassifier.cs
src/Build/BuildCheck/Infrastructure/InternalOM/PropertyReadInfo.cs
src/Build/BuildCheck/Infrastructure/InternalOM/PropertyWriteInfo.cs
src/Build/BuildCheck/OM/PropertyReadData.cs
src/Build/BuildCheck/OM/PropertyWriteData.cs
src/Shared/IElementLocation.cs

Fixes https://github.com/dotnet/msbuild/pull/10457#discussion_r1696497647
Renaming only change.
Casing of `IMSBuildElementLocation` was incorrect (`IMsBuildElementLocation`)
FYI @Nirmal4G (thx for bringing this up)

Rename - fix casing of IMSBuildElementLocation

---

src/Build/BackEnd/BuildManager/BuildSubmission.cs
src/Build/BackEnd/BuildManager/BuildSubmissionBase.cs
src/Build/Graph/GraphBuildSubmission.cs

Fixes [AB#2172446](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2172446)
The OM unification (https://github.com/dotnet/msbuild/pull/10172) unified check for readiness of BuildSubmission - it newly skipped checking of `BuiltRequest` not being null - expecting that during submitting the submission the `BuiltResult` is eventaully set.
This was covering the happy path, however result created from exception might be requested too early - before `BuiltRequest` is attached (but afet `IsStarted` was set). So we reintroduced the nun-null check
The removed  `BuiltRequest` null check was reintroduced - it was just pulled to the internals of the `BuildSubmission` type.

Fix the possible nullref on completing failed results

---

documentation/wiki/Binary-Log.md

Fixes #10454
Some of the ids on `BuildEventArgs` are bit misterious, with unclear relations. Let's have those be better documented.
Documentation only

Add structured log event ids documentation

---

documentation/wiki/ChangeWaves.md
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build.UnitTests/BackEnd/MockLoggingService.cs
src/Build.UnitTests/ConsoleLogger_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/Logging/ILoggingService.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/Logging/ProjectLoggingContext.cs
src/Build/BackEnd/Node/LoggingNodeConfiguration.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Build/Evaluation/Evaluator.cs
src/Framework.UnitTests/ProjectStartedEventArgs_Tests.cs
src/Framework/ProjectStartedEventArgs.cs
src/Shared/UnitTests/TestAssemblyInfo.cs
src/UnitTests.Shared/MockLogger.cs

Reverts dotnet/msbuild#10447
Reintroduces changes from #10243
Fixes #10225
#10243 introduced fix that ensured props/items attached to `ProjectEvaluationFinishedEventargs` if requested by any logger.
This however caused perf regression (https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/2173921) - as previously props/items were attached only when requested by ALL loggers. Such behavior would however break loggers requiring the props for correct functionality (e.g. BuildCheck logger).
* Of the original fix (pure revert of revert): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/571491 (still has the perf regression)
* Of the current fix (with NullLogger adjustment): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/571724 - Speedometer shows no …

Revert "Revert Emit eval props if requested by any sink (#10243)"

---

documentation/specs/BuildCheck/BuildCheck.md
documentation/specs/BuildCheck/Codes.md
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs

We support different scopes for different rules within single check. In fact - this is at the discretion of the individual check.
This PR is explicitly describing the behavior in the document - so that there is no confusion.
It as well removes the redundand guard check which is preventing the behavior.

Fix the scope setting doc and guard

---

documentation/wiki/ChangeWaves.md
src/Framework/BinaryTranslator.cs
src/Tasks/ManifestUtil/Util.cs
src/Tasks/ManifestUtil/mansign2.cs

SHA1 usages:
* https://codeql.microsoft.com/issues/bce484cd-3c70-4d18-b8b0-e012e3e20352
* https://codeql.microsoft.com/issues/392f55c0-2f68-44a4-b613-7939d4d753bc
* https://codeql.microsoft.com/issues/08a5b43e-ef73-4c07-99d4-585bd7381d12
BinFmt usage:
* https://codeql.microsoft.com/issues/615edc07-6d74-4047-8fae-2d34699c7d63
BinFmt usage - this is an explicit opt-in for legacy scenarios
SHA1 - this is a compat scenario

CodeQL suppressions

---

.github/workflows/SyncAnalyzerTemplateMSBuildVersion.yml

Fixes [#Error](https://github.com/dotnet/msbuild/actions/runs/10482498147/job/29033707386)  Since https://github.com/dotnet/msbuild/pull/10491

Update the template file path since the template project changed

---

template_feed/content/Microsoft.CheckTemplate/Check1.cs

Fixes https://github.com/dotnet/msbuild/issues/10537
Change classes to match the new naming convention for BuildCheck , otherwise the template won't be working.
When a customer instantiates a template, it's not buildable due to the changed naming in MSBuild API.
Yes, was introduced in scope of renaming: https://github.com/dotnet/msbuild/pull/10491
Locally, the template isn't covered by MSBuild yet.
No risks, doesn't contain any changes in logic.

Renamed fix to Check Template

---

src/Deprecated/Engine/Engine/NodeLoggingEvent.cs
src/Deprecated/Engine/Introspector/NodeStatus.cs
src/Deprecated/Engine/LocalProvider/LocalCallDescriptor.cs
src/Deprecated/Engine/LocalProvider/SharedMemory.cs

We are actively working on removing the whole 'src/Deprecated' code in scope of https://github.com/dotnet/msbuild/issues/8826
That work however must conform to VS deprecation mandate - so we'll need to wait 2 more months. Adding the CQ suppressions for the meantime

Add CQ suppression for Deprecated code

---

src/Build/Evaluation/Evaluator.cs

Followup and extension to #9625.
This changes the experience for trying to `dotnet msbuild` vcxproj from
```
ConsoleApplication3.vcxproj(28,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```
to
```
ConsoleApplication3.vcxproj(28,3): error MSB4278: The imported file "$(VCTargetsPath)\Microsoft.Cpp.Default.props" does not exist and appears to be part of a Visual Studio component. This file may require MSBuild.exe in order to be imported successfully, and so may fail to build in the dotnet CLI.
```

Add VCTargetsPath to VerifyVSDistributionPath

---

src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs

Change handling of BuildCheckError/BuildCheckWarning because it introduced issues with mapping in BinLogViewer.
Just reporting them as a part of BuildError/BuildWarning is enough.

Fix bin log population + emitting extra event on custom check registration

---

src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Now that BinaryFormatter is being removed in .NET 9, update `GenerateResource.BinaryFormatterUse` resource string to be more accurate

Update GenerateResource.BinaryFormatterUse string

---

src/Tasks.UnitTests/XmlPeek_Tests.cs
src/Tasks/XmlPeek.cs

Fixes #10313
TaskItem constructor assumes item spec to be escaped, but it was not.
https://github.com/dotnet/msbuild/blob/049835be350eb60f66b63e2e9adbd89094b4b127/src/Utilities/TaskItem.cs#L73-L76

XmlPeek: escape items correctly

---

src/Tasks/GenerateResource.cs

Suppress CodeQL for BinaryFormatter in .resx
The default .NET Framework build process deserializes resources in MSBuild, then reserializes them in an expected format for use at runtime. This is still supported, even though the dominant serialization mechanism in these projects is `BinaryFormatter`, to maintain build compatibility with older projects. The need to trust resources embedded in your application is documented in the MSBuild documentation.
Related (internal): https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/12924.
Closes #10528.

Suppress CodeQL for BinaryFormatter in .resx

---

.editorconfig
eng/Common.globalconfig
eng/Version.Details.xml
eng/Versions.props
eng/common/SetupNugetSources.ps1
eng/common/SetupNugetSources.sh
eng/common/core-templates/job/job.yml
eng/common/darc-init.ps1
eng/common/darc-init.sh
eng/common/internal/Tools.csproj
eng/common/templates-official/job/job.yml
eng/common/templates/job/job.yml
global.json
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build.UnitTests/Evaluation/Evaluator_Tests.cs

After merging the retargeting to dotnet 9 PR the build failed:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10122195&view=results
Additionally automated updates: https://github.com/dotnet/msbuild/pull/10575
Also failing due to the version conflicts of Xunit.
Commands: 
- `darc update-dependencies --channel ".NET Eng - Latest" --name "Microsoft.DotNet.Arcade.Sdk"`
- `darc update-dependencies --channel ".NET Eng - Latest" --name "Microsoft.SourceBuild.Intermediate.arcade"`
- `darc update-dependencies --channel ".NET Eng - Latest" --name "Microsoft.DotNet.XUnitExtensions"`
Temproary disabling the rules of xUnit. and will be solved as part of the: https://github.com/dotnet/msbuild/issues/10557
- Existing tests should pass
- Build was tested on the exp insertion …

Manual update dependencies from dotnet/arcade

---

eng/Version.Details.xml

Fixes #9366
The xliff tasks now live in arcade. 
Consume the xliff-tasks from arcade 
Build should pass

Update XliffTasks source to Arcade

---

.editorconfig
src/Build.UnitTests/BackEnd/NodeConfiguration_Tests.cs
src/BuildCheck.UnitTests/EndToEndTests.cs
src/Tasks.UnitTests/AddToWin32Manifest_Tests.cs
src/Tasks.UnitTests/CombineTargetFrameworkInfoProperties_Tests.cs

Fixes #10589 
During the retargeting work from net8 to net9 new tools brought new rules and warnings to the build. Not to introduce a lot of changes in one PR the rules were disabled.
This PR enables one of them xunit1012 https://xunit.net/xunit.analyzers/rules/xunit1012 and addresses the warnings
All tests should pass

Enable xUnit1012 rule 

---

.editorconfig
src/Tasks.UnitTests/GetSDKReference_Tests.cs

Fixes #10599
During the retargeting work from net8 to net9 new tools brought new rules and warnings to the build. Not to introduce a lot of changes in one PR the rules were disabled.
This PR enables one of them xUnit2029 https://xunit.net/xunit.analyzers/rules/xUnit2029 and addresses the warnings
All tests should pass

Enable xUnit2029 rule

---

src/Build/BuildCheck/API/CheckConfiguration.cs

Currently the Severity and Scope settings initializers are internal - making them inaccessible to check authors. This prevents check authors to be able to set sensible defaults - instead global defaults (Severity = Suggestion, Scope=ProjectFile) are allways used and this can be only overwritten via editorconfig.

Improve custom Check authoring - enable setting defaults for Severity and Scope

---

template_feed/README.md

The Table rendering on the NuGet Gallery needed some more whitespace to render HTML instead of raw text.
Fixes #10613
I tested this with a sample FSI script that mimics the NuGet Gallery markdown rendering:
<details>
<summary>F# Script for testing</summary>
```fsharp
#r "nuget: Markdig"
open Markdig
open Markdig.Renderers
open Markdig.Syntax
open System.IO
open Markdig.Extensions.EmphasisExtras
let text1 =
"""## MSBuild Custom Check Template Package
The package contains the template designed to streamline the creation of MSBuild check libraries.
| Template name | Short name | Description|
|---|---|---|
|MSBuild Custom Check Template|`msbuildcheck`|A project for creating a MSBuild check library that targets .NET Standard.|
The package is available for download from nuget.org.
Please feel …
```

Update README.md to render on NuGet.org

---

.vsts-dotnet.yml
eng/Packages.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Fixes ~~CVE-2024-38081~~, CVE-2024-38095
Some of our dependencies contains vulnerabilities. 
I backported changes we already have in `main` branch - updated ~~`Microsoft.IO.Redist`~~ package version and pinned `System.Formats.Asn1` package version.
Existing unit test.
VS 17.11 still uses `Microsoft.IO.Redist` version 6.0.0, so we need to stick with this version.

[17.11] Fix component governance alerts

---

src/Build/BackEnd/Components/Logging/EventSourceSink.cs
src/Build/BackEnd/Shared/EventsCreatorHelper.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/BuildCheck/Infrastructure/CheckContext/CheckDispatchingContext.cs
src/Build/BuildCheck/Infrastructure/CheckContext/CheckLoggingContext.cs
src/Build/BuildCheck/Infrastructure/CheckContext/ICheckContext.cs
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj
src/BuildCheck.UnitTests/TestAssets/CheckCandidateWithMultipleChecksInjected/.editorconfigtest
src/BuildCheck.UnitTests/TestAssets/CheckCandidateWithMultipleChecksInjected/CheckCandidateWithMultipleChecksInjected.csproj
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorCustomCheck.csproj
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorCustomCheck.props
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorOnInitializeCheck.cs
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorOnRegisteredAction.cs
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorWhenRegisteringActions.cs
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/README.md

Partial fix of https://github.com/dotnet/msbuild/issues/10522
When a Check throws an exception it falls with an internal logger exception and crashes the build. This is not ideal. It decided that when a Check fails, we do not fail the build, just give a warning and deregister the check.
Changed the BuildCheck logger to catch initialization exceptions, and dispatch them as warnings and not errors.
Added end to end test with a sample custom check that throws an exception. 
This is just a catch for exception on Check initialization. There are tests added for other cases but the fix will be different for them, so it will be done in another PR.

BuildCheck has better message when Check fails on Initialize

---

eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Fixes #10520
Original PR didn't allow to use newer version of MS.IO.Redirect even when it would be possible.
Fix the redirect in a way that we haven't a range of the binding redirect beyond what we distribute.
@maridematte I'm expecting "I told you so" message, but the original value before my change wasn't valid too 😄

Assembly redirect fix

---

template_feed/content/Microsoft.CheckTemplate/Directory.Packages.props

We are having Microsoft.Build package version managed centrally - but we do not opt-in to the feature - as a result restore will not respect our setting in Directory.Build.props.
Manual runs
Before:
```
C:\repro\Contoso.BuildChecks.csproj : warning NU1604: Project dependency Microsoft.Build does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
(...)
C:\repro\Contoso.BuildChecks\Check1.cs(2,23): error CS0234: The type or namespace name 'Experimental' does not exist in the namespace 'Microsoft.Build' (are you missing an assembly reference?)
(...)
Build failed with 8 error(s) and 2 warning(s) in 1.6s
```
After:
```
(...)
Build succeeded with 12 warning(s) in 3.0s
```
**Note:** The warnings in the sample above are …

Opt-in CPM for buildcheck template

---

src/Build/BackEnd/Components/Scheduler/Scheduler.cs

Swallow any noncritical exception on the MSBUILDDEBUGSCHEDULER codepath.
Avoids problems like #10628.

Make scheduler dumps best-effort

---

documentation/wiki/ChangeWaves.md
src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Now that https://github.com/dotnet/sdk/pull/39573 has made it into VS, we can finally enable loading `Microsoft.DotNet.MSBuildSdkResolver` by assembly name, as opposed to file path, which makes it possible to use its NGEN image.
Re-did #9439 which had to be reverted because of the problematic dependency on `Newtonsoft.Json`. The .NET SDK resolver does not depend on `Newtonsoft.Json` anymore. All the other pieces are already in place:
- `Microsoft.DotNet.MSBuildSdkResolver` is NGENed, both for MSBuild.exe and for devenv.exe.
- `devenv.exe.config` contains binding redirects analogous to what's added in this PR.
Experimentally inserted into VS and verified that `Microsoft.DotNet.MSBuildSdkResolver` is no longer JITted, saving ~50-100 ms of MSBuild.exe startup time.

Reapply "Load Microsoft.DotNet.MSBuildSdkResolver into default load context"

---

src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/BuildCheck.UnitTests/EndToEndTests.cs

Fixes #10317
BuildCheckManager was accessed as a singleton in some cases - this could lead to reusal of configuration and opt-in
* Got rid of the singleton
* Ensured that the component is cleared upon build end
End-2-end test verifying the proper picking of opt-in and editorconfig changes (the test is failing without the fix)
MSBuild server scenario might need a closer look - more details in the issue

Ensure buildcheck lifetime per build

---

global.json

Fixes #
CG alerts [CVE-2024-29415](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9734236?typeId=10653271), [CVE-2024-28863](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9495273?typeId=10653271), [CVE-2023-42282](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9296415?typeId=10653271) which are resulted from xcopy-msbuild 17.8.5. 
 
xcopy-msbuild ([Microsoft.DotNet.Arcade.MSBuild.Xcopy](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1074/Updating-Microsoft.DotNet.Arcade.MSBuild.Xcopy-WAS-RoslynTools.MSBuild-(xcopy-msbuild)-generation?anchor=troubleshooting)) higher version > 17.9.6 removed NodeJs modules under …

Bump to Microsoft.DotNet.Arcade.MSBuild.Xcopy 17.10.0-pre4.0

---

.vsts-dotnet-ci.yml
.vsts-dotnet.yml
eng/Versions.props
eng/build.ps1

This PR enables MSBuild to take security fixes from MSBuild dependencies.

Enable private feeds for release branch

---

documentation/wiki/Tasks.md

We had some broken mermaid makup:
Before:
After:

Fix mermaid markup

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Work item (Internal use): DevDiv2239615
Upgrading System.Text.Json to 8.0.4 due a project build error when using SDK 9.0 and VS17.11.
Unable to build / run projects within Visual Studio using the specified versions. Customer reported at https://github.com/dotnet/sdk/issues/43339.
Yes, from .NET SDK 9.0.100-preview.7, caused by https://github.com/NuGet/NuGet.Client/pull/5939 which updated the NuGet reference to `System.Text.Json` _on .NET Framework 4.7.2_ to a version between what VS 17.11 provides (8.0.0.3) and what the SDK provides (9.0.0.0).
Existing tests; VS automated tests and a manual scenario test will be done before final VS merge.
Low, package upgrade should not change any behavior within MSBuild but requires coordination with VS.

Upgrade system.text.json to 8.0.4

---

src/Build/BuildCheck/Checks/DoubleWritesCheck.cs
src/Build/BuildCheck/Checks/NoEnvironmentVariablePropertyCheck.cs
src/Build/BuildCheck/Checks/PropertiesUsageCheck.cs
src/Build/BuildCheck/Checks/SharedOutputPathCheck.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/BuildCheck.UnitTests/EndToEndTests.cs

Fixes #10630
* Adjusting confusing property check diagnostic wording.
`[PropertyName]` --> `'PropertyName'`
* Localizing Checks messages and titles

Update property check diagnostic wording + localize Check messages and titles

---

src/Build/BuildCheck/Infrastructure/BuildCheckCentralContext.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/BuildCheck/Infrastructure/BuildEventsProcessor.cs
src/Build/BuildCheck/Infrastructure/CheckWrapper.cs
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/TestAssets/SampleCheckIntegrationTest/PropsCheckTestWithLimit.csproj
src/Framework/Traits.cs
src/MSBuild/XMake.cs

Temporary fixes #10414
If BuildCheck emits a lot of messages, it is possible that the build will hang. Since the real reason of the hang is yet unclear, we have decided to limit number of messages emitted by build-in checks.
- Enhanced a wrapper class `CheckWrapper` so that we can limit number of messages per check. 
- Added unit test.
unit tests + manual testing

[BuildCheck] Limit number of emitted messages per rule.

---

src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BuildCheck/Infrastructure/InternalOM/PropertyReadInfo.cs
src/Build/Graph/ProjectInterpretation.cs
src/Build/Instance/ProjectInstance.cs
src/BuildCheck.UnitTests/TestAssets/SampleCheckIntegrationTest/PropsCheckTest.csproj

Fixes #10604
`MSBuildTreatWarningsAsErrors` access was not recognized by PropertiesCheck - since it was bypassing Expander.
Added routing of properties access to `ProjectInstance`
Added unit test case specifically for `MSBuildTreatWarningsAsErrors` (fails without fix)
Not handling accesses via `Project` - as that would get much more involved and is specific for API calls and VS - which are both currently unsupported scenarios

Recognize direct properties access in ProjectInstance

---

.editorconfig

Part of the issue: https://github.com/dotnet/msbuild/issues/10557
Update the justification of disabling the rule xunit1031

Update xunit1031 justification

---

.editorconfig

Update the justification why we are disabling the rule of xUnit2013. 
Nothing changes, only comments

xUnit2013 Justifications update

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Recently we added the help message for `-check`. The localization tags did not work as expected and we need to fix for it be able to be translated.

Fix the comments for localization

---

eng/Versions.props
src/MSBuild/TerminalLogger/TerminalLogger.cs

Fixes #10579
Command `dotnet run` creates `TerminalLogger` instance and bypasses code that enables VIRTUAL_TERMINAL_PROCESSING on Windows. This can cause rendering of unwanted VT100 control codes in the console.
Customer see "weird" characters on terminal that doesn't have enabled VT100 support by default - mostly conhost. Reproduces in `dotnet new console && dotnet run` scenario.
Yes, in RC2 from enhanced console output in `dotnet run` in https://github.com/dotnet/sdk/pull/42240.
Manual testing. Before and after the fix:
Low. The same logic is used when MSBuild is started via entry point.

Fixes writing unwanted characters to console when TerminalLogger is created directly

---

src/Tasks/Microsoft.CSharp.CurrentVersion.targets

Fixes #
issue with build acceleration 
The separate design time targets file is needed for the case when .net workload was not installed, so these targets are missed for build acceleration feature.
The main change is made in internal repo that comes with VS installation on empty workload selection
https://devdiv.visualstudio.com/DevDiv/_git/ProjectServices/pullrequest/580503
Tested locally

Add Design Time target import

---

src/Tasks/Microsoft.CSharp.CurrentVersion.targets

It's related to adding a new target import: https://github.com/dotnet/msbuild/pull/10698
VS doesn't always emit "DesignTimeBuild" flag that cause an issue with importing for some cases (e.g. project load from UI).

Remove DesignTimeBuild restriction

---

src/Framework/NativeMethods.cs

This should be slightly more efficient since it's vectorizable.

Use SequenceEqual in win32 GetFullPath

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs

Fixes [#10583](https://github.com/dotnet/msbuild/issues/10583)
Can't evaluate 
```
<Foo>Foo</Foo>
<Bar>1234</Bar>
<Good>$([System.String]::Equals($(Foo), $(Bar)))</Good>
<Bad>$(Foo.Equals($(Bar)))</Bad>
```
Use the double.TryParse instead of the convert method
Add the test cases in the test method Medley()

Fix property expander when comparing between non-numeric and numeric properties

---

src/Utilities/TaskItem.cs

The doc comment mentioned that the parameterless constructor existed only for COM but it was still easy to find, causing problems like #10660. Hide it from IDE completion and extend the comment.

Hide and warn about TaskItem ctor

---

documentation/release-checklist.md

This is just an adjustment of the checklist. I separated it into sections so it is easier to read and follow, as well as having certain steps together instead of having everything all over the place.
Also added the contents of this PR: https://github.com/dotnet/msbuild/pull/10655 to consolidate.

Update release checklist doc

---

eng/Versions.props
src/Build/BuildCheck/Infrastructure/EditorConfig/EditorConfigFile.cs
src/BuildCheck.UnitTests/EditorConfigParser_Tests.cs

Fixes #10684 
.editorconfig is ignored when it's EOLs don't match the system, because it's lines are parsed according to the local environment (`\n` vs `\r\n`). This fix splits lines in both locales.
Multiplatform usability. Example of a silent failure this fix addresses: a Windows user copying .editorconfig from unix or from some configurations of git.
No
Manual +
Unit test
Low, fixes edge case of intended behavior in BuildCheck feature.

Fix parsing .editorconfig EOL

---

documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md

Fixes [#10717](https://github.com/dotnet/msbuild/issues/10717)
Adjust document after changes in bootstrap: https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Bootstrap.md#current-implementation-for-net

Update the doc according to changes in bootstrap

---

NuGet.config
eng/Versions.props
template_feed/content/Microsoft.CheckTemplate/.template.config/template.json

Bump baseline and default MicrosoftBuildVersion in template

Bump baseline and default MicrosoftBuildVersion in template

---

eng/Versions.props
src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs

Fixes #10709
VS hangs during solution close - turns out to be caused by hang in `BuildManager.EndBuild`
There are ~~almost 3k~~ over 4k (and counting) cases hit in wild on 17.11 ([details](https://prism.vsdata.io/failure/?query=ch%3Drelease%20r%3D17.11&eventType=hang&failureHash=c55b4080-fb88-4cbf-a2d0-80cd4f311554&showFG=false))
It turns out to be a contention between `CancelAllSubmissions` and `EndBuild` (for the state of `_buildManagerState`) - more details in the bug: https://github.com/dotnet/msbuild/issues/10709#issuecomment-2388676868
High rate of hangs during solution closes (either during VS closing or opening different solution from VS with already opened solution)
No, but some other recent timing changes (possibly speedups) made this much more prelevant.
Tailored unit test …

[17.12] Prevent contention between CancelAllSubmissions and EndBuild

---

src/Build/Construction/ProjectChooseElement.cs
src/Build/Construction/ProjectElement.cs
src/Build/Construction/ProjectElementContainer.cs
src/Build/Construction/ProjectRootElement.cs
src/Build/Construction/ProjectTaskElement.cs

Fixes #10695
A confusing assertion wording was used - it might not be immediately helpful when hit.
Fixed the wording.
No actual code changes

[Wording only] Clarify wording of verifying local backing document exist case

---

src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj
src/BuildCheck.UnitTests/TestAssets/Common/CommonTest.props

Fixes #[10702](https://github.com/dotnet/msbuild/issues/10702)
The issue stemmed from a missing Microsoft.Build package during the test execution. CustomCheck is compiled using a specific version of Microsoft.Build, but during the CheckCandidate run, this package couldn't be restored. This mismatch led to the problem.
`
Build FAILED. "/Users/runner/work/1/s/artifacts/bin/Microsoft.Build.BuildCheck.UnitTests/Debug/net9.0/TestAssets/CheckCandidate/CheckCandidate.csproj" (Restore target) (1) -> (Restore target) -> /Users/runner/work/1/s/artifacts/bin/Microsoft.Build.BuildCheck.UnitTests/Debug/net9.0/TestAssets/CheckCandidate/CheckCandidate.csproj : warning NU1701: Package 'Microsoft.IO.Redist 6.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, …

Fix tests running on version freeze

---

documentation/Deploy-MSBuild.md
documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md
eng/cibuild_bootstrapped_msbuild.ps1
eng/cibuild_bootstrapped_msbuild.sh

Fixes #10751
Bootstrap is on by default, opt-in with arg `/p:CreateBootstrap=true` is unnecessary
docs, CI: remove instances of `CreateBootstrap=true`

remove CreateBootstrap opting-in 

---

src/Build/BackEnd/BuildManager/BuildManager.cs

Fixes #10260
The `BuildManager.Dispose` was idempotent, but it wasn't very clear - needed code archeology, plus was easy to break.
Let's make it more clear.
Changed just 2 lines:
* Consolidated `disposing` and `_disposed` check before lock (performing first the cheaper one on local parameter)
* Added explicit short circuit check of `_disposed` after entering the lock
Rest of the displayed diff is caused by changed indention due to consolidating the 2 checks before locking.

Short circuit repetitive BuildManager.Dispose calls

---

src/Build/BackEnd/Node/NodeConfiguration.cs
src/Framework/Traits.cs
src/Shared/TaskHostConfiguration.cs

Fixes [#AB2263324](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2263324)
Opting out of 17.10 changewave might lead to opting out of BinaryFormatter deprecation. This can unintentionally break ppl builds by breaking NodeConfig or TaskHost config de/serialization.
Both of the types and their data transfer is internal to MSBuild - there is no need to opt out from the safer, proprietary de/serialization. Hence let's prevent the opt out altogether.
Removed the opt-out option for NodeConfig and TaskHost config de/serialization
Existing tests

Remove BinFmt opt-in for un-exposed data transfers

---

src/Build.UnitTests/BackEnd/NodePackets_Tests.cs
src/Build.UnitTests/BuildEventArgsSerialization_Tests.cs
src/Build/Logging/BinaryLogger/BinaryLogRecordKind.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs
src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs
src/Framework.UnitTests/BuildCanceledEventArgs_Tests.cs
src/Framework.UnitTests/BuildSubmissionStartedEventArgs_Tests.cs
src/Shared/LogMessagePacketBase.cs

Fixes #10244
BuildCanceledEventArgs was added in https://github.com/dotnet/msbuild/pull/10055 but the serialization was missing, this PR adds it
implement the serialization in the same manner as for BuildSubmissionStarted event in https://github.com/dotnet/msbuild/pull/10424 
Unit tests
Adding support for this to MSBuild Structured Log Viewer PR https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/824
also fixed a typo in BuildSubmissionStartedEventArgs_Tests

add binlog serialization for BuildCanceledEventArgs

---

NuGet.config

BuildXL feed is going to be moved . To shield devs from future feed changes - we have had the BuildXL packages pushed to dotnet-tools feed.
No testing - successful build on clean build machine without cache is enough
FYI @dfederm

Remove BuildXL feed

---

src/Build/BackEnd/Components/Logging/EventSourceSink.cs

Fixes #10245
EventSourceSink.cs
removed RaiseSomeEvent handlers and replaced them by generic one.

EventSourceSink refactor [testing needed, do not merge]

---

src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj
src/BuildCheck.UnitTests/TestAssets/Common/CommonTest.props

It causes issues on CI, need to revise solution

Revert "Fix tests running on version freeze"

---

documentation/wiki/Adding-Events.md

Fixes #10146
The process of making an event work with BinaryLogger and https://github.com/KirillOsenkov/MSBuildStructuredLog has many steps, this pr documents them
docs only

[docs] description of changes for the binary logger to work with a new event

---

.config/tsaoptions.json
.vsts-dotnet.yml
eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

These changes onboard tsa and policheck to the repo
previously was done for https://github.com/microsoft/MSBuildLocator/pull/312
bump System.Text.Json version

Enable tsa and policheck

---

src/Build.UnitTests/Evaluation/Expander_Tests.cs
src/Build/Evaluation/Expander.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes #10435
#10209 was generous with what it interpreted as a throwaway parameter: underscores were often misinterpreted as throwaway parameters. This changes it to require `out _` instead of just `_`, which should resolve the problem.
Look for `out _` instead of just `_`
Created a new unit test to distinguish between _ and out _
Alternative to #10435
I searched github for all instances of `out _` in .props, .targets, and .*proj files and found none that seemed problematic, giving me some confidence in this change. I also looked for instances of _ in .targets files and found plenty of examples that were broken with #10209, indicating that that search would've prevented this problem.
@rainersigwald, leaving this as a draft until you've had a chance to try to think of potential problems …

Change throwaway parameter to include out and add test

---

src/Build/Logging/ProfilerLogger.cs
src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs
src/MSBuild/XMake.cs

This will fix #10540--it looks like M.IO.Redist has the same fix that .NET 9 has that avoids the failed root enumeration. As a bonus it's generally higher performance/less allocatey (but I don't _know_ that that has a specific positive impact in this file).

Use Microsoft.IO.Redist in XMake.cs

---

.vsts-dotnet.yml

Fixes #
[Queries - Boards (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_queries/query/?_a=query&wiql=%20SELECT%20ID%2CSeverity%2CState%2C%5BAssigned%20To%5D%2CTitle%20FROM%20WorkItem%20WHERE%20Tags%20Contains%27TSA-MSBuild-PoliCheckSARIF-Official%27%20)
For PoliCheck errors in the query, we have PoliCheck exclusions to skip the check on them. After adapting 1ES PT and enabling PoliCheck in it, we need to pass the PoliCheck exclusion file to 1ES PT.
Pass PoliCheck exclusion file to 1ES PT and remove the PoliCheck & Credscan from eng\common template.
Verified with the run on this experimental branch.

Pass PoliCheck exclusion file to 1ES PT

---

src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
src/Build/Logging/BinaryLogger/Postprocessing/StreamExtensions.cs
src/Build/Logging/BinaryLogger/Postprocessing/SubStream.cs
src/Build/Logging/BinaryLogger/Postprocessing/TransparentReadStream.cs
src/Shared/ResourceUtilities.cs

Fixes #10674 #10675
https://github.com/dotutils/streamutils/pull/2 makes more performant custom implementations of streams which can be copied here
https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/821 indroduced changes to BuildEventArgsReader which should be the same in MSBuildStructuredLog, this PR copies these changes.
3 commits
1. override custom stream methods
2. adopt changes to BuildEventArgsReader
3. make non-params versions of resource methods
perf improvement validation setup:
1. get validation .binlog from msbuild's own build on this branch `.\build /bl /p:Configuration=Release, 
4. also do this for a baseline from main [94941d9](https://github.com/dotnet/msbuild/commit/94941d9cb26bb86045452b4a174a357b65a30c99)
5. measurement of replay speed in powershell script: run …

perf fixes copy from dotutils and MSBuildStructuredLog

---

eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Fixes
[CVE-2024-38081](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9977344?typeId=22822795&pipelinesTrackingFilter=1)
MSBuild 17.11 uses dependency with known vulnerabilities.
Using software without known vulnerabilities.
No.
Existing automated tests.
Low - there are no functional changes.
Upgrade `Microsoft.IO.Redist` from 6.0.0 to 6.0.1 to fix the vulnerability.

CG alert cleaning on VS17.11

---

eng/Packages.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Fixes #
[CVE-2024-38081](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9977344?typeId=17273272), [CVE-2024-38095](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9977346?typeId=17273272), [CVE-2024-30105](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/9977347?typeId=17273272)
MSBuild 17.8 uses dependencies with known vulnerabilities.
Using software without known vulnerabilities.
No.
Existing automated tests.
Low - there are no functional changes.
Upgrade `Microsoft.IO.Redist` from 6.0.0 to 6.0.1, `System.Formats.Asn1` from 7.0.0 to 8.0.1, and `System.Text.Json` from 7.0.3 to 8.0.4. `System.Collections.Immutable` was upgraded to `8.0.0` to fix the CI build. …

CG alert cleaning on VS17.8

---

src/Build/Definition/ToolsetRegistryReader.cs
src/Build/Evaluation/Profiler/EvaluationLocationPrettyPrinterBase.cs

> /vmr/src/msbuild/src/Build/Evaluation/Profiler/EvaluationLocationPrettyPrinterBase.cs(78,24): error CS0121: The call is ambiguous between the following methods or properties: 'string.Join(string?, params ReadOnlySpan<object?>)' and 'string.Join(string?, params ReadOnlySpan<string?>)' [/vmr/src/msbuild/src/Build/Microsoft.Build.csproj::TargetFramework=net9.0]
pr https://github.com/dotnet/sdk/pull/44011/checks?check_run_id=31628922599
build https://dev.azure.com/dnceng-public/public/_build/results?buildId=844822&view=logs&jobId=f0f4e1eb-2872-579b-17f7-75dc26fbb285&j=f0f4e1eb-2872-579b-17f7-75dc26fbb285&t=e5ca527a-fe4f-597c-4330-d9b726220892

Fix build with langversion preview

---

src/Deprecated/Conversion/Microsoft.Build.Conversion.Core.pkgdef
src/Package/DevDivPackage/DevDivPackage.csproj
src/Package/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
src/Package/GetBinPaths.targets
src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
src/Package/MSBuild.VSSetup/MSBuild.clientenabledpkg
src/Package/MSBuild.VSSetup/files.swr

Contributes to #8826
Microsoft.Build.Conversion.Core was removed in VS codebase by https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/583701 However Microsoft.Build component still keeps dragging the binary to the VS install. Let's make sure Microsoft.Build.Conversion.Core.dll is not part of the VS install before we remove the code alltogether
Removing the registrations of Microsoft.Build.Conversion.Core, that contributes to VS install

Remove Conversion.Core registrations

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

https://github.com/advisories/GHSA-8g4q-xg66-9fp4
System.Text.Json 8.0.4 is vulnerable to a Denial of Service attack.
The risk of potential Denial of Service attacks on applications using System.Text.Json.
No.
Upgrade System.Text.Json from 8.0.4 to 8.0.5 to patch the Denial of Service vulnerability.

[vs17.12] Bump STJ to 8.0.5

---

documentation/wiki/CollectedTelemetry.md

Fixes #10799
Document telemetry collected by msbuild to be transparent with our users about the data we collect.
This is documenting datapoints added in NET9, but also filling gap of missing documentation of pre-existing telemetry datapoints
Documentation only, no code changes

Document msbuild telemetry datapoints

---

src/Deprecated/Conversion/Microsoft.Build.Conversion.Core.pkgdef
src/Package/DevDivPackage/DevDivPackage.csproj
src/Package/DevDivPackage/VS.ExternalAPIs.MSBuild.nuspec
src/Package/GetBinPaths.targets
src/Package/MSBuild.VSSetup/MSBuild.VSSetup.csproj
src/Package/MSBuild.VSSetup/MSBuild.clientenabledpkg
src/Package/MSBuild.VSSetup/files.swr

Return https://github.com/dotnet/msbuild/pull/10817 so now it will be a separate insertion.

Return Conversion.Core registrations (#10817)

---

src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

After removing the deprecated msbuild engine, the message in VS should be adjusted on the attempt to open pre-msbuild message.
The message contains the help link for the customer.

Adjust conversion message

---

eng/Versions.props

This was needed long ago but Arcade bumped past this in https://github.com/dotnet/arcade/pull/7056.

Stop overriding Arcade VSSDK

---

src/BuildCheck.UnitTests/BuildCheckManagerProviderTests.cs
src/BuildCheck.UnitTests/TaskInvocationAnalysisDataTests.cs
src/UnitTests.Shared/MockLogger.cs

This should help identify failures like https://github.com/dotnet/msbuild/pull/10836#issuecomment-2436159216.

Capture output in some BuildCheck tests

---

scripts/Deploy-MSBuild.ps1

Fix  Deploy-MSBuild script since PR [#10817](https://github.com/dotnet/msbuild/pull/10817) and [#10352 ](https://github.com/dotnet/msbuild/pull/10352)

Remove derecated assemblies in the Deploy-MSBuild script

---

documentation/wiki/MSBuild-Environment-Variables.md
src/Framework/Traits.cs

Fixes https://github.com/dotnet/msbuild/issues/10639
There was an [internal ticket](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2253774/) that seems to originate from the scheduler logger. The team uses the engine debugger variable to keep track of their builds. However, it seems that the scheduler logger does not always work as expected and it is turned on when using `MSBuildDebugEngine`. Since we think there isn't a lot of information that is necessary from scheduler logger, we are trying to disable it when using the `MSBuildDebugEngine` variable, and leaving it on when explicitly turned on.
Does not turn on scheduler debugger when using `MSBuildDebugEngine`

Removed scheduler debugger from MSBuildDebugEngine

---

eng/cibuild_bootstrapped_msbuild.ps1
eng/cibuild_bootstrapped_msbuild.sh

Bootstrap improvements. Now we should update the version in 3 places, this change allows to update `BootstrapSdkVersion `property only in Version.props. The scripts read the value from this file.
The initial idea was to get rid on the logic that points to a specific MSBuild.dll, but it isn't not realistic for the local development, when in core/sdk folders might be several different versions.

Remove hardcoded values from bootstrap scripts

---

azure-pipelines/WIFtoPATauth.yml
azure-pipelines/vs-insertion-experimental.yml
azure-pipelines/vs-insertion.yml

our VS insertion pipelines should use 1ES template
new pipelines vs-insertion.yml, vs-insertion-experimental.yml - they will replace Release pipelines - main/ vs1x.y/ experimental
manual in AzDO, but the final usability has to be tested in merged state

migrate VS insertion release pipelines

---

src/Build.UnitTests/Evaluation/ItemEvaluation_Tests.cs
src/Build/Evaluation/LazyItemEvaluator.cs

An Item `Update` operation may apply to items that are defined via
wildcard. In normal operation, the wildcard will have been expanded by
the time Update applies, and it's fine for Update to assume that
everything is a valid file path. But in
`MSBuildSkipEagerWildCardEvaluationRegexes` mode, wildcards may not be
expanded.
Fixes #9405 by using a more appropriate method to normalize
probably-but-not-necessarily paths for comparisons.

Don't throw on lazy item updating unexpanded globs

---

src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Framework/ProjectStartedEventArgs.cs

Remote (built in another node) projects were not respecting MSBuildWarningsNotAsErrors configured  in the projects, when the API or CLI `-warnaserror` option was enabled.
Fixes #10874.

Always respect warning-as-error properties

---

src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs

Fixes #10956 by moving to a thread-safe dictionary.

Allow concurrent evaluation BuildCheck processing

---

src/Tasks.UnitTests/CodeTaskFactoryTests.cs
src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs
src/Tasks/CodeTaskFactory.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs

Fixes #10343
When the attribute `Include` of the element `Reference` in `UsingTask` is empty, the error message is a little repetitive and it doesn't point out the task name.
Re-phrase the error message with task name.
Modified existing tests.

Improve the message when UsingTask Reference Include is empty

---

src/Build/BuildCheck/Infrastructure/BuildCheckCentralContext.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorOnRegisteredAction.cs
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorWhenRegisteringActions.cs

Fixes https://github.com/dotnet/msbuild/issues/10522
Second PR for that issue. This PR covers the cases in a Custom Check where there is an exception while registering actions, and when running said actions.
Since actions are individuals, we do not deregister the whole analyzer when one fails.
It has been decided to expose these errors are warnings instead to not break the build where they show up.
Added some try catch statements so errors do not break builds. Messages have been added to each case for more detail as we do not preserve anything else from the exception.
Reenabled unit test and added the previously commented out cases.

Error handling for failures on registered actions for Custom Checks

---

src/Build/Utilities/EngineFileUtilities.cs

I ran across this while looking at a unit test, hovered
over it, and was annoyed that I didn't get the description.

Doc comment for CaptureLazyWildcardRegexes

---

src/Build/BuildCheck/API/IBuildCheckRegistrationContext.cs
src/Build/BuildCheck/Infrastructure/BuildCheckCentralContext.cs
src/Build/BuildCheck/Infrastructure/BuildEventsProcessor.cs
src/Build/BuildCheck/Infrastructure/CheckRegistrationContext.cs
src/Build/BuildCheck/OM/ParsedItemsCheckData.cs
src/Build/CompatibilitySuppressions.xml
src/BuildCheck.UnitTests/MockBuildCheckRegistrationContext.cs

Adding EvaluatedItemCheckData to BuildCheck OM - to prepare for some sample Item data/metadata Checks implementation
The leveraging checks:
* https://github.com/dotnet/msbuild/pull/10955
* (TBD - EmbeddedResource should have Culture)

Add EvaluatedItemCheckData

---

src/Framework/EncodingUtilities.cs
src/Utilities.UnitTests/EncodingUtilities_Tests.cs

Fixes #10907
The `UseUtf8Encoding` property of the `Exec` task and other `ToolTask` derived tasks should accept `true` and equivalent to `always`.
`ToolTask` doesn't validate or interpret the `UseUtf8Encoding` property. The value of the property is passed to and interpreted by `EncodingUtilities.BatchFileEncoding()`.
`EncodingUtilities` was modified to add a const string for `TRUE` and the `BatchFileEncoding()` method was modified to handle `TRUE` and `ALWAYS` the same.
Created a unit test that compares the returns for `ALWAYS` and `TRUE`, confirmed that the unit test failed, modified the code, and confirmed the unit test passes.
Tested on Windows.
On non-Windows platforms the `UseUtf8Encoding` property has no effect.

ToolTask UseUtf8Encoding value of 'true' is equal to 'always'

---

documentation/wiki/ChangeWaves.md
eng/Versions.props
src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Framework/ChangeWaves.cs
src/Shared/Constants.cs
src/UnitTests.Shared/ObjectModelHelpers.cs

Backport of  https://github.com/dotnet/msbuild/pull/10942.
Fixes https://github.com/dotnet/msbuild/issues/10877 and #10873.
Work item (Internal use): 
Respect `WarningsAsMessages`, `WarningsAsErrors`, `WarningsNotAsErrors`, and `TreatWarningsAsErrors` in addition to their `MSBuild`-prefixed versions in all projects, not just ones that import `Microsoft.Common.CurrentVersion.targets`.
Reduced complexity in opting to keep warnings as warnings, making it easier to configure warnings how you expect.
No, this behavior is longstanding. It's higher severity now due to the NuGet Audit warnings, which are often created in one project (where a package is referenced) but raised in another (where the restore actually happened), which may have the easy-to-type form of the property but not the …

[vs17.12] Consistently respect unprefixed Warning-as-error/message/warning properties

---

documentation/wiki/ChangeWaves.md
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/TestAssets/EmbeddedResourceTest/ReferencedProject/ReferencedProject.csproj
src/Framework/StringUtils.cs
src/Tasks/AssemblyDependency/ReferenceTable.cs
src/Tasks/AssignCulture.cs
src/Tasks/CreateCSharpManifestResourceName.cs
src/Tasks/CreateVisualBasicManifestResourceName.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Fixes #10536
Contributes to https://github.com/dotnet/msbuild/issues/10996
Custom culture on EmbeddedResource items is supported by `AssignTask` (from https://github.com/dotnet/msbuild/pull/10026), but it's then ignored by RAR task (and CreateManifestResourceName as well) 
We are no more checking the recoginzed culture against the known list. Putting this behind changewave - as it has pottential to break esoteric scenarios of binaries with .resource.dll existing in subdirs, but actually not being a satelite assemblies
Manual testing on a scenario from the bug
Tailored tests added in https://github.com/dotnet/msbuild/pull/11023 (will be uncommented after merging this PR)

Support custom culture in RAR

---

src/BuildCheck.UnitTests/TestAssets/Common/CommonTest.targets
src/BuildCheck.UnitTests/TestAssets/CustomCheck/CustomCheck.csproj
src/BuildCheck.UnitTests/TestAssets/CustomCheck2/CustomCheck2.csproj
src/BuildCheck.UnitTests/TestAssets/ErrorCustomCheck/ErrorCustomCheck.csproj
src/BuildCheck.UnitTests/TestAssets/InvalidCustomCheck/InvalidCustomCheck.csproj
template_feed/content/Microsoft.CheckTemplate/Company.CheckTemplate.csproj

Fixes https://github.com/dotnet/msbuild/issues/10900
We mistakenly redistributed Microsoft.Build.dll and Readme.md in the custom build check package (both test/original one).
Exclude Microsoft.Build.dll from the package and remove the redundant Readme.md files.
Covered by existing tests.

Update build check custom template and tests

---

azure-pipelines/vs-insertion.yml
documentation/release-checklist.md

https://github.com/dotnet/msbuild/pull/10966
https://github.com/dotnet/msbuild/pull/10919
https://github.com/dotnet/msbuild/pull/10920
Without this change the scheduled runs on main inputs CI from any branch that had the last successful run which is wrong. 
Desired functionality:
1. Manually trigger from AzDO UI, ability to select as input resource pipeline a specific MSBuild CI run and specify to which branch to insert.
2. Scheduled run on main every weekday inputting the last successful CI on main.
3. Triggered runs after CI run finished in release branches (vs*)
4. Ability to disable 2.,3. via AzDO UI by setting custom triggers and schedule.
Set schedules and triggers.
Changes logic to trigger servicing insertion on each commit to release branch.
Manually tested scenarios in a …

Update triggers in VS insertion pipelines

---

documentation/wiki/ChangeWaves.md
src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Shared/Constants.cs
src/UnitTests.Shared/ObjectModelHelpers.cs

Reverts dotnet/msbuild#10942
Due to the issue with sdk merge, I'm temporarily withdrawing this PR.
https://github.com/dotnet/sdk/pull/44977

Revert "add WarningsAsMessages, WarningsAsErrors, WarningsNotAsErrors and Tre…"

---

azure-pipelines/WIFtoPATauth.yml
azure-pipelines/vs-insertion.yml
eng/Versions.props

Backporting VS insertion pipelines
https://github.com/dotnet/msbuild/pull/10966
https://github.com/dotnet/msbuild/pull/10920
https://github.com/dotnet/msbuild/pull/11037
add pipeline
addressed in https://github.com/dotnet/msbuild/pull/11037
manually testing in azdo org for expected scenarios
backporting to vs17.8, vs17.10, vs17.11, vs17.12. Other branches are "out of regular support" and if insertion is needed they can be triggered from main

[vs17.12] Backport VS insertion pipeline YMLs

---

src/BuildCheck.UnitTests/EndToEndTests.cs

Fixes #10702
The PR reenables the CustomCheck tests that were disabled due to failing on version bump.

Reenable customcheck tests

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes #8743
`CopyToOutputDirectory` currently has only `PreserveNewest` and `Always` (and `Never` - not considered here).
`Always` is unnecessery perf hit, but is only workaround for situations where destination file can change between builds (e.g. someone is copying DB, storage file, config file etc. - that can be altered during test runs).
So let's support a mode that allows copying if the file is different - doesn't have to be newer.
At the same time - `Always` should actually be only used in those cases - so let's make it possible to glabaly opt-in for such change in behavior.
* Added 'IfDifferent' metadata and it's recognition
* Added $(SkipUnchangedFilesOnCopyAlways) property that changes behavior of `Always` to `IfDifferent`
Tailored tests added in #11054

Support 'IfDifferent' for CopyToOutputDirectory

---

documentation/specs/BuildCheck/Codes.md
src/Build/BuildCheck/Checks/TargetFrameworkConfusionCheck.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/BuildCheck/Infrastructure/BuildEventsProcessor.cs
src/Build/BuildCheck/OM/EvaluatedPropertiesCheckData.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/BuildCheck.UnitTests/EndToEndTests.cs
src/BuildCheck.UnitTests/SharedOutputPathCheck_Tests.cs
src/BuildCheck.UnitTests/TestAssets/TFMConfusionCheck/TFMConfusionCheck.csproj
src/Shared/Constants.cs

Fixes #9880 
`TargetFramework` and `TargetFrameworks` properties should not be specified in the build script at the same time.
Tailored unit tests added
This calls to be unified with the #10635 Check. Let's do that in the separate PR, once this one is merged

TargetFramework(s) confusion Check

---

eng/Versions.props

Similar to https://github.com/dotnet/roslyn/pull/76076
Needed to unblock https://github.com/dotnet/sdk/pull/45042
Should solve error:
```
/vmr/src/msbuild/src/Utilities/Microsoft.Build.Utilities.csproj(0,0): error NU1109: (NETCORE_ENGINEERING_TELEMETRY=Restore) Detected package downgrade: System.Memory from 4.6.0 to centrally defined 4.5.5. Update the centrally managed package version to a higher version. 
Microsoft.Build.Utilities.Core -> System.Collections.Immutable 10.0.0-alpha.1.24603.1 -> System.Memory (>= 4.6.0) 
Microsoft.Build.Utilities.Core -> System.Memory (>= 4.5.5)
```
Will also create a patch containing these changes for the sdk PR.

Bump maintenance-package dependency versions to latest conditioned to source build only

---

documentation/specs/BuildCheck/Codes.md
src/Build/BuildCheck/Checks/PropertiesUsageCheck.cs

Unused property check is a runtime check and hence can have false positives in many common scenarios (mutlitargeted build etc.) - for this reason it's better to have it completely disabled by default and advanced user can enable it once understanding the behavior and downsides of the check

Demote unused property check

---

azure-pipelines/vs-insertion.yml

Fixes #11092 
a "refactor" in prior VS insertion pipeline PR introduced a bug where package properties would be set to empty string resulting in no update of them in VS PR
fix setting properties in the embedded PowerShell
(internal) https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/596781?_a=files 
(internal) https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10665100&view=results
to be backported to vs17.8,10,11,12

Fix setting package versions in VS insertion

---

.opt-prof.yml

OptProf pipeline is blocked since older os images have been removed from the test lab.

[17.8] Unblock opt-prof in release branches

---

global.json

Fixes #
After updating dotnet to 9.0.100, internal run has the following issues:
1. Targeting .NET 9.0 or higher in Visual Studio 2022 17.11 is not supported. See https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10668003&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=94418e61-6648-5751-f7d4-a14f4e5e2bb7.
```
D:\a\_work\1\s\.dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(135,5): error NETSDK1223: Targeting .NET 9.0 or higher in Visual Studio 2022 17.11 is not supported. [D:\a\_work\1\s\src\Build.UnitTests\Microsoft.Build.Engine.UnitTests.csproj::TargetFramework=net9.0]
```
2. Version 9.0.100 of the .NET SDK requires at least version 17.11.0 of MSBuild. The current available version of MSBuild is 17.10.2.21103. Change the .NET SDK …

Bump VS and xcopy-msbuild version to 17.12.0

---

src/Build/BuildCheck/Infrastructure/BuildCheckBuildEventHandler.cs
src/Build/BuildCheck/Infrastructure/BuildCheckForwardingLogger.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/BuildCheck/Infrastructure/IBuildCheckManager.cs
src/Build/BuildCheck/Infrastructure/NullBuildCheckManager.cs

Fixes #10960, #10935
* ProjectImported OM wasn't properly propagated if binlog wasn't specified
* ProjectImported OM should only be handled in single threaded context of main node logger
Preexisting tests

Buildcheck - ProjectImported OM fixes

---

eng/Versions.props
global.json

Fixes - failing internal build
Bumping vs/msbuild version in global.json to 17.8
```
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.24570.5\tools\SdkTasks\SigningValidation.proj : error : Could not resolve SDK "Microsoft.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.24570.5\tools\SdkTasks\SigningValidation.proj : error :   Version 8.0.110 of the .NET SDK requires at least version 17.7.0 of MSBuild. The current available version of MSBuild is 17.6.3.22601. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available. …
```

Update vs/msbuild version

---

global.json

Fixes #internal build failure
Internal build could not find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0'.
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10681391&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=fb192a8b-e433-5fc8-e2b0-276ab015e7d5&l=14
```
Downloading RoslynTools.MSBuild 17.8.0
##[error](NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) {"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000} …
```

Update xcopy-msbuild version to 17.8.5

---

src/Build/BackEnd/BuildManager/BuildManager.cs

Fixes ObjectDisposedException occuring during investigation of #11091
Fixes #10753
We were blindly disposing a handle in synchronous scope while asynchronous code could heve been still running.
During the errors during GraphBuild this can lead to unhandled exceptions and unfinished logs

Prevent ObjectDisposedException in BuildManager

---

.github/workflows/inter-branch-merge-flow.yml

Fixes # auto merge flow doesn't  run for vs17.8
According to https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md#onboarding, the workflow file accordingly should be created in branches where the inter-merge should be available.
Add inter-branch merge flow file
N/A

Add inter-branch merge flow file

---

documentation/Logging-behavior.md
documentation/Logging-behaviour.md

Fixes https://github.com/dotnet/msbuild/issues/10676
There has some confusion about which logs display what type of message. This is to clarify what is to be expected from each logger and verbosity.

Logging behavior doc

---

.opt-prof.yml

Transfor of work by @mtylerMSFT from https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted/pullrequest/597532
Recent changes to OptProf pipeline were not backported to vs17.8 - this is causing that pipeline to not work properly

[vs17.8] Unblock OptProf build

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Fixes # CG alert [CVE-2024-43485](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/DotNet-msbuild-Trusted/alert/10506482?typeId=17275150&pipelinesTrackingFilter=0) 
It requires System.Text.Json version 8.0.5 to fix the vulnerability detected by CG.
Since System.Text.Json is conditionally updated for .NET core (avoid unwanted update to VS), it's OK to bump up System.Text.Json version.
Bump up version to 8.0.5.
N/A
This change will flow into 17.10->17.11 to eliminate the same CG alert.

Bump up System.Text.Json to 8.0.5

---

src/Utilities/TaskItem.cs

Fixes https://github.com/dotnet/msbuild/issues/11083
Sometimes `TaskItems` are not file paths, and we currently treat all of them as file paths and try to fix backslashes into slashes. 
Added an option where `TaskItems` can be created without a reference to a path, and it will not try to fix it.

Option to avoid "fixing" \ in new TaskItem() 

---

eng/TestAssets.targets
src/BuildCheck.UnitTests/EndToEndTests.cs

Unblocks #11090
Temporary quickfix untill we're able to get to the rootcause and fix it

Disable packing in bootstrap build

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs

The latest daily build of the .NET 10 SDK fails to build the msbuild repo due to the following build error:
```
/repos/dotnet/src/msbuild/src/Build/BackEnd/BuildManager/BuildManager.cs(1330,41): error CS0104: 'ExceptionHandling' is an ambiguous reference between 'Microsoft.Build.Shared.ExceptionHandling' and 'System.Runtime.ExceptionServices.ExceptionHandling' [/repos/dotnet/src/msbuild/src/Build/Microsoft.Build.csproj]
/repos/dotnet/src/msbuild/src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs(875,17): error CS0104: 'ExceptionHandling' is an ambiguous reference between 'Microsoft.Build.Shared.ExceptionHandling' and 'System.Runtime.ExceptionServices.ExceptionHandling' [/repos/dotnet/src/msbuild/src/Build/Microsoft.Build.csproj] …
```

Fix ambiguous reference for ExceptionHandling class

---

.config/git-merge-flow-config.jsonc

The merge-flow does not work at the moment due to the syntax error in config file. 
Example run: https://github.com/dotnet/msbuild/actions/runs/12409721811/job/34643898223
Add the missing comma
VS Code manual check of valid json

fix: Update json syntax of merge-flow config

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

A quick search of the SDK installation shows that all usages of this property use the 'Output' form, not 'OutPut'. This doesn't matter from a functionality perspective, but for consistency we should clean it up.
A community member noticed this, so why not fix it up?

Fix casing for UTF8Output propery

---

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs
src/MSBuild/XMake.cs

Sometimes Windows Defender blocks on `MSBuild.rsp` file reading operation (e.g. https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2308633). 
Since response file content isn't needed for worker nodes, we can skip reading from t.
Add a check for `nodemode:` arg in command like
Local testing when rsp file is manually locked.

Prevent reading from .rsp file for worker nodes

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes https://github.com/dotnet/msbuild/issues/9773
When a project's references are modified in a way that eliminates version conflicts, the existing binding redirects in the `exe.config` file in `bin `folder are not automatically removed during the next build. This PR ensures that binding redirects are properly removed when they are no longer needed.
Prevent `.exe.config` removal from obj folder by incremental clean by changing it's content with the original App.config when RAR returns empty `SuggestedBindingRedirects`.
Manual.

Handle the case for updated binding redirects

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props

Contributes to #11156
New solution parser is too strict when it goes to solution files guids duplication.
This new version is relaxing strictness for .sln files (it stays for .slnx - which is wanted)

Update SolutionPersistence version

---

azure-pipelines/vs-insertion-experimental.yml
documentation/release-checklist.md

from internal discussion that this would be nice
now this is possible by editing the yml, also enable it from UI
add insertion parameter

enable experimentally inserting to release branches from UI

---

src/Build/BackEnd/BuildManager/BuildManager.cs

Fixes #11051
For various hangs detection we need worker processes dumps. Let's unblock VS perf team in enabling automatic collection of worker processes dumps.
No tests provided.
This is best effort, point in time functionality, that should be used so
FYI @davkean

Expose processes leveraged by BuildManager

---

src/Build/Evaluation/Expander.cs

to use code generated version instead of compiled one where applicable according to this[ .NET article.](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators)
This nets a small but visible performance gain with only a minor code update.

changing expander regex 

---

src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
src/Framework/MSBuildEventSource.cs

Fixes [#10975](https://github.com/dotnet/msbuild/issues/10975)
The stop events didn't report success or failure.
Pass parameter currentTargetEntry.Result.ResultCode.ToString() to the event log

Add result for target stop event trace

---

eng/Version.Details.xml
eng/Versions.props
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Build/Utilities/EngineFileUtilities.cs
src/Shared/FileMatcher.cs
src/Shared/UnitTests/FileMatcher_Tests.cs
src/Tasks/Copy.cs
src/Tasks/CreateItem.cs
src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs
src/Utilities/TrackedDependencies/CanonicalTrackedOutputFiles.cs
src/Utilities/TrackedDependencies/FlatTrackingData.cs
src/Utilities/TrackedDependencies/TrackedDependencies.cs

Fixes #9609
Logging when glob expansions fail is useful for debugging.
Log it quietly (as a message with low priority).
FileMatcher.GetFiles returns a message if an exception occurs when matching files, it's callers log it.
Covered by existing tests.
Failures which would be logged are rare.
Tested manually triggering an exception in the critical section and the message displays in binlog:
Figuring out how to log is a bit tricky with some of the code being in static, some in singleton contexts and there are multiple logging mechanisms.

Log glob failures

---

src/Build/Construction/Solution/SolutionFile.cs

Fixes #https://github.com/dotnet/msbuild/issues/11156
Due to serializer.OpenAsync(FullPath, CancellationToken.None).**Result**; usage, AggregateException was thrown with full callstack attached **without** location information:
Switch to .GetAwaiter().GetResult(); to preserve original SolutionException that contains ElementLocation data.
Manual.

Add line/column information to invalid project exception

---

src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs
src/Build/BackEnd/Shared/TargetResult.cs

We recently merged https://github.com/dotnet/msbuild/pull/11202
While profiling, the VS profiler started complaining about the Enum.ToString() with a perf cost 0.14%
See also here:
https://learn.microsoft.com/en-us/visualstudio/profiling/performance-insights-enum-tostring?view=vs-2022
Introduced a function to do the conversion in a Reflection-less way.

Enum.ToString method is resulting in slow performance. Fix it.

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props

This version needs to match what is referenced in the sdk repo in order to avoid prebuilts in source build: https://github.com/dotnet/dotnet/blob/bcd01151a1cdde7d885b4fa1b157722fe4c0d3b4/src/sdk/Directory.Packages.props#L72

Upgrade Microsoft.VisualStudio.SolutionPersistence to 1.0.28

---

azure-pipelines/vs-insertion.yml

Fixes #11136
will propagate via mergeflow
This prevents wrong behavior of the VS insertion with an override for edge cases.
Fail on package conflicts when pushing them to feeds and add an override parameter which skips the pushing stage 
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=10716305&view=results

[vs17.8] disallow inserting pkgs twice in VS insertion

---

src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf

Contributes to #11185
As agreed in https://github.com/dotnet/msbuild/issues/11185 - the warning wording needs to be more explicit.
Adjusting the wording based on agreed guidance

[Wording only] Adjust MSB3825 wording

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Contributes to #11057
`OutputPath` is not guaranteed to end with slash when specified as a global property. So making sure the path composition using it is correct

Ensure slash in PublishDir

---

eng/Versions.props
src/Shared/FrameworkLocationHelper.cs
src/Utilities/ToolLocationHelper.cs

Fixes https://developercommunity.visualstudio.com/t/Unable-to-locate-MSBuild-path-with-Lates/10824132
Work item (Internal use): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2343019
Related to:
https://github.com/microsoft/azure-pipelines-tasks/issues/20734?reload=1?reload=1
The `Get-MsBuildPath` function used by the Azure Devops `MSBuild@1` task [uses reflection to load a MSBuild function](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/f0e3508423ce927594a945f714b0e07be4bdb2fa/common-npm-packages/msbuildhelpers/PathFunctions.ps1#L29-L32) and then call it. 
MSBuild recently introduced (#9223) a dependency on `Microsoft.IO.Redist` in this codepath (it was used elsewhere in the assembly before). `Microsoft.IO.Redist` depends on `System.Memory`, which is in …

removing the dependency on IO.Redist from MSBuild GetPathToBuildToolsFile

---

src/Package/MSBuild.VSSetup/files.swr

Fixes https://github.com/dotnet/msbuild/issues/10847
NGen is a tool that precompiles managed assemblies (e.g., .NET DLLs) into native machine code to improve runtime performance.
It creates "native images" stored in a system-wide cache, enabling faster application startup by skipping Just-In-Time (JIT) compilation.

Ngen Microsoft.VisualStudio.SolutionPersistence.dll for msbuild.exe

---

src/Package/MSBuild.VSSetup/files.swr

IO.Redist is a core part of VS now, so we shouldn't ngen it for the VS context--best case that's redundant work, worst case if we mismatch versions it might cause further confusion.
Internal PR: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/602240
Validate:

Don't ngen Microsoft.IO.Redist for VS

---

documentation/specs/BuildCheck/Codes.md
src/Build/BuildCheck/Checks/UntrustedLocationCheck.cs
src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes https://github.com/dotnet/sdk/issues/45342
Building (or just executing targets) under the Downloads folder is not recomended, as uninteded injection of unrelated msbuild logic can happen.
This checks emits error in such case.
Manual testing
```
PS C:\Users\jankrivanek\Downloads\mytest\console> C:\src\msbuild-2\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe -check -v:m -restore
MSBuild version 17.14.0-dev-25064-01+a273f56ac for .NET Framework
Determining projects to restore...
Restored C:\Users\jankrivanek\Downloads\mytest\console\console.csproj (in 205 ms).
MSBUILD : error BC0301: Location: 'C:\Users\jankrivanek\Downloads\mytest\console' cannot be fully trusted, place your proje
cts outside of that folder (Project: console.csproj).
console -> …
```

Add UntrustedLocation check

---

src/Build/BackEnd/Components/Logging/LoggingService.cs

Fixes #11095
AssemblyLoadBuildEventArgs are logged asynchronously, and build doesn't wait for those, so it can happen that ProjectFinishedEventArgs occurred first - removing the id->file mapping from the map, but AssemblyLoadsTracker still uses the BuildEventContext for that project.
This would previously lead to a build crash. Since this is very benign scenario - let's add a grace handle for it.

Harden the ID-to-project file map misses

---

src/Tasks.UnitTests/DownloadFile_Tests.cs

Fixes #11018
Test result `Shouldly.ShouldAssertException : task.Result\r\n    should be\r\nFalse\r\n    but was\r\nTrue` indicates that the task is done quickly before the cancelation is executed, though the test cancels it right after it is started. 
Make a fake stream that provides a single character A~Z per a couple of milliseconds infinitely without high memory cost as the content of http response message and increase the task timeout a little so that the cancellation can be executed.
N/A

Make the cancelation can be executed before the task is done

---

eng/Versions.props
src/BuildCheck.UnitTests/EndToEndTests.cs
src/Tasks/AssignCulture.cs
src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes  #11313
The newly added `MSB3002` has a breaking potential (while it's very correct). So making it an opt-in behavior
("MSB3002: Explicitly set culture "{0}" for item "{1}" was overwritten with inferred culture "{2}", because 'RespectAlreadyAssignedItemCulture' property was not set.")
If user took behavior on old incorrect behavior (explicitly set `Culture` metadata on EmbeddedResource were overwritten with culture inferred from the file extension) or they just don't care - they might be broken by the new warning that they might not appreciate.
Yes.
The warning was newly added (in 17.13)
Targetted test is testing the scenarios with explicit and implicit culture.
Minimal (making the new warning opt-in).

[vs17.13] Adjust embeddedresource culture warning

---

src/Package/MSBuild.VSSetup.Arm64/files.arm64.swr
src/Package/MSBuild.VSSetup/files.swr

This reverts commit 6bed355f6bb313c1f6e7b887da460f9b49ec8f6b.
#11182  likely caused images loaded regression in VS insertion https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/606630
experimental insertion perf passed
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/606667

Revert "Specify ngen configs for exes (#11182)"

---

src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs

Fixes #11326
BuildCheck can still emit some LogBuildEvent(s) after `ProjectFinishedEventArgs` was reported and entries from `_projectFileMap` were cleaned up.
Due to `GetAndVerifyProjectFileFromContext` validation, these checks break the build.
If `BuildCheck` is enabled, `_projectFileMap` won't be cleaned up. If it brings significant perf overhead , this approach will be reconsidered.
n/a

Workaround for "MSB4166: Child node "1" exited prematurely"

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Reverts dotnet/msbuild#11012, which should fix #11362.

Revert "Handle the case for updated binding redirects"

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Reverts https://github.com/dotnet/msbuild/pull/11012, which should fix https://github.com/dotnet/msbuild/issues/11362.
Need to remove this change due to unforeseen consequents for DTB in VS:
https://github.com/dotnet/msbuild/issues/11362#issuecomment-2628406941

Revert changes in common targets for binding redirect

---

azure-pipelines/vs-insertion.yml

Prior version caused a failure on run:
```
/azure-pipelines/vs-insertion.yml (Line: 85, Col: 7): 'value' is already defined
```

Update YAML conditions

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

dotnet/msbuild#11248 broke ClickOnce publishing - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2359773
The breakage is caused by the 'NormalizePath' part - as it can change relative path to absolute.
- reverted
- added the original change, which just ensures the slash

Revert + adjust "Ensure slash in PublishDir"

---

src/Build/BackEnd/Components/Caching/ResultsCache.cs
src/Build/BackEnd/Components/Caching/ResultsCacheResponse.cs

Avoid creating a HashSet object on each ResultsCacheResponse

---

eng/dependabot/Packages.props

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.2.0-beta.556

Bump `StyleCop.Analyzers` to `1.2.0-beta.556`

---

src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
src/Tasks/SystemState.cs

Avoid creation of temporary strings where possible

---

eng/Versions.props
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Components/Logging/LoggingServiceLogMethods.cs

Backporting of https://github.com/dotnet/msbuild/pull/11353
BuildCheck can still emit some LogBuildEvent(s) after ProjectFinishedEventArgs was reported and entries from _projectFileMap were cleaned up.
Due to GetAndVerifyProjectFileFromContext validation, these checks break the build for the middle/large size projects.
It was discovered on the attempt to dogfood BuildCheck. 
If BuildCheck is enabled, _projectFileMap won't be cleaned up.
Failure of the build in buildcheck is enabled (for middle and large project sizes).
Local testing with the patched msbuild.
low: the feature is disabled by default and we need this fix to drive adaptation across dotnet org.

[9.0.1xx] Workaround for "MSB4166: Child node "1" exited prematurely for build check

---

src/Build.UnitTests/BackEnd/BuildManager_Logging_Tests.cs
src/Build/BackEnd/Components/Logging/LoggingService.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Framework/BinaryTranslator.cs
src/Framework/ITranslator.cs
src/Framework/Traits.cs
src/Shared/LogMessagePacketBase.cs
src/Shared/Resources/Strings.shared.resx
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

Fixes #11323
We used `BinaryFormatter` in the serialization logic to support build custom events. With the VS 17.14, we can remove the last instances of the `BinaryFormatter` in our codebase.
`TranslateDotNet` implementation was removed and `OutOfProcNode` now unconditionally emits build error instead of sending packets with the custom event. 
Modified existing unit test.

Removing last instances of the BinaryFormatter

---

.vsts-dotnet.yml

Try disabling AV in the official build script to avoid build breaks that manifest as
```
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\9.0.0-beta.24516.2\tools\Sign.proj(72,5): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
System.Runtime.Serialization.SerializationException: Type 'System.AssemblyLoadEventArgs' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
at System.AppDomain.OnAssemblyLoadEvent(RuntimeAssembly LoadedAssembly)
at Microsoft.Build.Framework.ITask.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
at …
```

Official Build MpPreference workaround

---

src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs

Fixes https://github.com/dotnet/msbuild/issues/11439 and https://github.com/dotnet/msbuild/issues/11319
`_checkRegistry` and `_ruleTelemetryData` can be accessed in multithreaded environment (from logger and nodes).
List -> ConcurrentBag
Since it fails on CI, we need to merge the change and check it on preview.

Change list -> ConcurrentBag in BuildCheckContext

---

src/Build.UnitTests/BackEnd/MockHost.cs
src/Build/BackEnd/Components/BuildComponentFactoryCollection.cs
src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/Microsoft.Build.csproj
src/Build/TelemetryInfra/ITelemetryForwarder.cs
src/Build/TelemetryInfra/TelemetryForwarderProvider.cs

Fixes failing VS insertion https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/612802
The https://github.com/dotnet/msbuild/pull/11359 introduced `Microsoft.Build.Telemetry` namespace, but there was preexisting public type with the same name - extrnal consumers could get broken
Renamed

Fix namespace and public typename conflict

---

src/Framework/Traits.cs

This was mistakenly duplicated from another trait.

LogAllAssemblyLoads doc comment

---

documentation/wiki/ChangeWaves.md
eng/BootStrapMsBuild.targets
eng/Versions.props
src/Build.OM.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionFile_Tests.cs
src/Build.UnitTests/Construction/SolutionFilter_Tests.cs
src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs
src/Build/Construction/Solution/SolutionFile.cs

Don't use the new parser from `Microsoft.VisualStudio.SolutionPersistence` to parse `.sln` files.
Fixes #11463
Work item (Internal use): AB#2397817
Revert #10836 to return to the longstanding MSBuild private `.sln` parser (but keep using the SolutionPersistence library for `.slnx`).
Three categories of problem:
* Some older `NuGet.exe` restores failed because they couldn't find the library (fixed in newer versions but reported via VS Feedback and https://github.com/microsoft/dotnet-framework-docker/issues/1213.
* Current `NuGet.exe` restores can fail if the path to 64-bit MSBuild is specified explicitly
* Various bugs in the solution parser (e.g. https://github.com/microsoft/vs-solutionpersistence/issues/96) that don't hit in the legacy MSBuild parser.
All manifest as build or NuGet …

Revert ".slnx support - use the new parser for .sln and .slnx (#10836)"

---

eng/Versions.props

Workaround #11492
we pushed 17.13.15 during development mistakenly, so we can't insert it
bump version

update version to 17.13.16

---

src/Build/Utilities/Utilities.cs

Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1980399/
MSBuild has custom xml parsing logic that is trying to distinguish whether the element content should be treated as regular xml element content (`XmlNode.InnerText`) or whether we want to allow users to pass in the actual unescaped xml (`XmlNode.InnerXml`)
The second option feels as not very good choice (allowing to specify xml recognized sequences within xml script, without properly escaping them) - but since it is already preexisting behavior, let's keep it.
The recgnition of CData section was inefficient and defective - not allowing leading whitespaces - so I've fixed at least that one
CData recognition now skips the leading whitespaces.
Manual testing - loaded the repro project from the case into VS with and without …

Fix CData recognition

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf
src/MSBuild/XMake.cs

Fixes first part of #11494
We have resources with same name but different content in different projects. It prevents merging our resources to single project and proceed with #11494.
A prefix was added to the resource names to avoid conflicts.
Existing unit tests.
This is a minimal change to keep existing behavior.

Renaming conflicting resources

---

eng/Versions.props
src/Build.UnitTests/Evaluation/Preprocessor_Tests.cs
src/Build/Construction/ProjectRootElement.cs
src/Build/Definition/Project.cs

Work item (Internal use): AB#2381505
Hides the in-memory-only `.props` file synthesized to support properties returned from an SDK resolver.
All C++/CLI builds in Visual Studio are marked as "not up to date", slowing customer builds.
Yes. Experience regressed in 17.13 after https://github.com/dotnet/sdk/pull/45364, which revealed this latent MSBuild bug (introduced in #5269 in 2020).
Automated tests and manual C++/CLI VS scenario testing.
Low: changes behavior only for elements that use the new flag adopted in #11478.

Hide ephemeral ProjectRootElements from import enumerations

---

src/Shared/BufferedReadStream.cs
src/Shared/NodeEndpointOutOfProcBase.cs

Avoid synchronous I/O in BufferedReadStream

---

.github/workflows/SyncAnalyzerTemplateMSBuildVersion.yml

The job "Sync Microsoft.Build version in analyzer template with Version.props" https://github.com/dotnet/msbuild/actions/runs/13499671367/job/37714757956 failed to push commit since the permissions. Add permissions settings

Fix the job "Sync Microsoft.Build version in analyzer template with Version.props"

---

src/Build/Utilities/EngineFileUtilities.cs

Fixes #11528
We added logging for intermittent glob failures in https://github.com/dotnet/msbuild/pull/11211. For that a logging mechanism is needed. But it is possible to pass null logging mechanism to the GetFileList method, which is what happens in the bug. 
add a null check for logging mechanism to skip logging in case of null
this occurs intermittently :(

null check logging mechanism before logging glob failure

---

src/Tasks/ManifestUtil/CngLightup.cs

Fixes #
CodeQL SM03800 issue
CodeQL is flagging unapproved usage of DSACryptoServiceProvider
The flagged code is not required in ClickOnce so deleting it.
ClickOnce signing scenarios validated from .NET Fx 3.5 through .NET 9.

[CodeQL][SM03800] Remove unapproved usage of DSACryptoServiceProvider

---

src/Build.UnitTests/Construction/SolutionFile_NewParser_Tests.cs
src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs
src/Build/Construction/Solution/SolutionProjectGenerator.cs

Fixes #11288
see the issue description #11288
1. Load `before/after.{solutionName}.sln.targets` for .`slnx`
2. Added test checking that targets from these files are included in the project for `.sln` and `.slnx`
Added tests, tested manually

Load `before/after.{solutionName}.sln.targets` for .`slnx`

---

.vsts-dotnet-ci.yml
azure-pipelines/vs-insertion-experimental.yml
azure-pipelines/vs-insertion.yml

Our branch versioning currently differs from VS's. This will adjust so our 17.14 insertions go to main, but keeping main branch with experimental insertions scheduled so we do not have one big PR when versions align again.

Update VS insertions for 17.14

---

eng/Packages.props
eng/Versions.props
eng/dependabot/Packages.props
src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/Build/Microsoft.Build.csproj
src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj
src/Directory.Build.targets
src/Framework.UnitTests/Microsoft.Build.Framework.UnitTests.csproj
src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
src/MSBuild.UnitTests/Microsoft.Build.CommandLine.UnitTests.csproj
src/MSBuild/MSBuild.csproj
src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj
src/StringTools.Benchmark/StringTools.Benchmark.csproj
src/StringTools.UnitTests/StringTools.UnitTests.csproj
src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj

Both "System.Runtime" and "System.Private.Uri" are inbox in .NETCoreApp since ~2017 and don't need to be referenced explicitly anymore.
They were referenced here as external dependencies brought vulnerable netstandard1.x dependencies in which were then flagged by CG.
That isn't the case anymore. xunit, shouldly and other packages with their corresponding versions used in this repo don't bring netstandard1.x in anymore.
Don't reference "System.Net.Http" for the same reason. It is inbox on .NET Framework, .NETCoreApp and .NET Standard. On .NET Framework a `<Reference Include="System.Net.Http" />` item is needed as it isn't part of the default referenced assemblies.
Note that this change will help when starting to consume a .NET 10 SDK as those would get flagged by NuGet Prune Package …

Remove deprecated 4.3.* System package references

---

NuGet.config
eng/Packages.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
eng/dependabot/Packages.props

Follow-up to https://github.com/dotnet/msbuild/pull/11145.
We were missing the entry for System.Text.Encoding.CodePages and the source-build-externals intermediate for vs-solutionpersistence in Version.Details.xml which caused a prebuild in https://github.com/dotnet/sdk/pull/47377 and version mismatches in https://github.com/dotnet/sdk/pull/47376.
Also simplified the way we reference the different package versions a bit to make it clearer and synced the list of packages between Version.Details.xml/Versions.props/Packages.props.
Depends on https://github.com/dotnet/msbuild/pull/11555

Fix entries in Version.Details.xml and make version overriding clearer

---

src/Package/MSBuild.VSSetup/files.swr

This assembly shouldn't ever be loaded in the net4x context so don't spend the install time ngening it.

Don't ngen StringTools.net35

---

src/Build/Logging/TerminalLogger/TerminalLogger.cs

Part of #11160
While profiling some of Eric's PRs and one of my experiments, I've noticed following:
Terminal width/height are behind a lock and repeated access is quite expensive.
I've set it so that the update is happening only once every ~second or so. This makes the cost negligible.
Note that this appears to be ~1.5% CPU time saved on the main node, which is the one under heaviest load due to IPC with all the other nodes.
None, this should be non-disruptive change.
Refresh frequency is up to discussion. Making it twice a second should be fine as well.

asking terminal for dimensions during every frame is expensive

---

.github/workflows/SyncAnalyzerTemplateMSBuildVersion.yml

Fix the issue https://github.com/dotnet/msbuild/actions/runs/13778304840/job/38531781822 that failed to create the PR since the head parameter doesn't include the owner

Fix the head parameter when search the created PRs

---

src/Tasks.UnitTests/Exec_Tests.cs

Fixes [#9176](https://github.com/dotnet/msbuild/issues/9176)
Occasionally temp files fail to delete because of virus checkers, so generate MSB5018 warning.
The commit https://github.com/dotnet/msbuild/commit/d7788d644e1b463b996107e7dcce358b8eaeccaa#diff-3abd8382aac3bdfa59d5c1ca41dd089795d6ca539a00b3c50eab4fd6a0996314 including string lockedFileMessage = LockCheck.GetLockedFileMessage(fileName); doesn't output the related process.
Add the warning MSB5018

Fix test to take warning MSB5018

---

src/Framework/BuildEventArgs.cs
src/Shared/LogMessagePacketBase.cs

###Part of #11160
Building on top of Eric's IPC pr - his work allowed for other bottlenecks to reveal themselves.
Currently, the ReadFromStream function uses 
```
ArgsReaderDelegate readerMethod = (ArgsReaderDelegate)CreateDelegateRobust(typeof(ArgsReaderDelegate), _buildEvent, methodInfo);
```
for a large portion of it's packet deserialization. This is large enough to be seen in the performance profiler as shown above more than 3% of CPU an it's on a critical path.
When I checked, the function was already virtual so the change is minimal. Unfortunately I had to make an allowance to the task host since it wasn't compatible.
Exposed a convenience public endpoint for the CreateFromStream function, that calls the virtual method Create from stream.
Used this endpoint instead of delegate …

using virtual fuction instead of reflection

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

When [GetCopyToPublishDirectoryItems from Microsoft.NET.Publish.targets](https://github.com/dotnet/sdk/blob/124be385f90f2c305dde2b817cb470e4d11d2d6b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L788) is called on its own, the depends tree terminates at _SplitProjectReferencesByFileExistence
[_SplitProjectReferencesByFileExistence tries to use @(ProjectReferenceWithConfiguration) ](https://github.com/dotnet/msbuild/blob/main/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1642), which is empty, because it is emitted by AssignProjectConfiguration, which isn't actually called.
This causes the Publish action to not pick up output of project's ProjectReferences, since they are completely ignored.
Add the target to the dependson list to ensure that …

Microsoft.Common.CurrentVersion.targets: _SplitProjectReferencesByFileExistence DependsOn AssignProjectConfiguration

---

src/Build.OM.UnitTests/Microsoft.Build.Engine.OM.UnitTests.csproj
src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj
src/Build/Microsoft.Build.csproj

The VS insertion is currently failing due to the `SolutionParser` version being upgraded beyond the version used by VS. Made the change so this reference is not exposed and so the insertions do not fail.
[Experimental Insertion](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/619214)

Make SolutionParser package reference private 

---

src/Build/Logging/TerminalLogger/TerminalLogger.cs

Fixes #11605
Internal logger exception is thrown when executing `msbuild /tl` or `dotnet build` with the cache plugin enabled. This is because the `TargetOutputs` is null for cache plugin projects which result in a cache hit. 
It is unclear why `TargetOutputs` is null for cache plugin projects and whether a change from #11318 introduced this issue, but this change simply performs a null check to ensure the build can continue with the cache plugin and terminal logger enabled.
Sample output from local test with cache plugin enabled:
```
Restore complete (1.3s)
MSBUILD : warning : Project cache plugin initialization failed. There will be no cache hits. See QuickBuild.log for more details.
X succeeded (15.3s) → c:\src\<path>\X.exe
Build succeeded with 1 warning(s) in 26.2s
```

Add null check when iterating through TargetOutputs in terminal logger

---

src/Build/Utilities/EngineFileUtilities.cs

Assert instead of ! for nullable

---

src/Samples/ProjectCachePlugin/ProjectCachePlugin.csproj

This will ensure that we're testing compatibility, and avoid requiring updating the dependencies of the ProjectCachePlugin.
It's needed for #11038.

Pin samples/ProjectCachePlugin to released MSBuild

---

eng/Versions.props

Fixes failures like https://dev.azure.com/dnceng-public/public/_build/results?buildId=991991&view=results
When MSBuild is being built in the VMR, sometimes later-built packages can end up with different versions than earlier-built packages. That's not good, but it doesn't cause failures.
However, these later-built packages can have different (higher) versions of dependency projects that had already been built with the lower versions. This causes downgrade failures like the following intermittently for any VMR jobs triggered around the end of the PST workday:
> Detected package downgrade: Microsoft.Build.Tasks.Core from 17.15.0-ci-25175-01 to centrally defined 17.15.0-ci-25174-01. Update the centrally managed package version to a higher version. 
> Msbuild.Tests.Utilities -> …

Don't force shipping versions to be used in VMR builds

---

documentation/specs/BuildCheck/Codes.md

Fix url formatting  in BuildCheck/Codes.md

---

src/Build.UnitTests/Evaluation/SdkResultEvaluation_Tests.cs
src/Build/Evaluation/Evaluator.cs

Fixes #11550
This is a regression caused by changes in `MSBuildSdkResolver` that were introduced in https://github.com/dotnet/sdk/pull/45364. Specifically by adding 2 new properties. 
This results in hitting the path that was not hit before - handling properties and items of `SdkResult`:
https://github.com/dotnet/msbuild/blob/6aeb262fe5570316ede42dc69788908b548972c5/src/Build/Evaluation/Evaluator.cs#L1867-L1875
When `Project` is created from `XmlReader` and not from `ProjectRootElement`, it results in null `ProjectRootElement` during Evaluation. Which results in internal exception like ` InternalErrorException: MSB0001: Internal MSBuild Error: .SdkResolver.1981936763.proj unexpectedly not a rooted path` here:
https://github.com/dotnet/msbuild/blob/6aeb262fe5570316ede42dc69788908b548972c5/s …

[vs17.14] Fix SdkResult Evalution when ProjectRootElement is null

---

documentation/specs/event-source.md
documentation/specs/low-priority-switch.md
documentation/specs/project-cache.md
documentation/specs/question.md
documentation/specs/rar-core-scenarios.md
documentation/specs/remote-host-object.md
documentation/specs/sdk-resolvers-algorithm.md
documentation/specs/single-project-isolated-builds.md
documentation/specs/static-graph.md
documentation/specs/task-isolation-and-dependencies.md
documentation/specs/test-target.md

I noticed some easy-to-fix inconsistencies in some markdown files that I was viewing.
Fix spacing around headers, unordered list style, declare a language on fenced code blocks, and similar issues.
N/A

`/documentation/specs/*.md` formatting/linting/cleanup

---

.vsts-dotnet-ci.yml

The service is not coming back, remove the commented out code.

Remove RichCodeNavIndexer from .vsts-dotnet-ci.yml

---

eng/Packages.props
eng/Versions.props
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Reverts dotnet/msbuild#11038
It causes versioning issues.

Revert "Update assembly versions to latest for packages that recently shipped"

---

eng/Packages.props
eng/Versions.props
src/Directory.Build.targets
src/MSBuild.Bootstrap/MSBuild.Bootstrap.csproj
src/MSBuild/app.amd64.config
src/MSBuild/app.config
src/Package/DevDivPackage/DevDivPackage.csproj
src/Samples/Directory.Build.props

Visual Studio 17.14 updated to newer versions of the assemblies built in https://github.com/dotnet/maintenance-packages, which caused some performance regressions related to the mismatch between MSBuild.exe and devenv.exe dependencies (AB#2359731).
We hoped to fix this by taking the same update (#11038), but that caused functional problems: applications that use MSBuildLocator to build or manipulate projects using the MSBuild API are broken by updates to some dependencies (`System.Memory`, as in https://github.com/dotnet/msbuild/issues/7873#issuecomment-1227332842, and now `System.Threading.Task.Extensions`). This means that a straightforward update to those packages breaks all API consumers _including_ users of Roslyn's `MSBuildWorkspace`, since the …

Use newer maintenance-packages at runtime

---

eng/SourceBuildPrebuiltBaseline.xml
src/Build.UnitTests/BackEnd/NodeEndpointInProc_Tests.cs
src/Build/BackEnd/Client/MSBuildClientPacketPump.cs
src/Build/BackEnd/Components/Communications/NodeManager.cs
src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs
src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs
src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs
src/Build/BackEnd/Node/InProcNode.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Build/BackEnd/Node/OutOfProcServerNode.cs
src/Build/Instance/TaskFactories/TaskHostTask.cs
src/MSBuild/OutOfProcTaskHostNode.cs
src/Shared/INodePacketFactory.cs
src/Shared/NodePacketFactory.cs
src/Shared/NodePipeBase.cs
src/Shared/NodePipeClient.cs
src/Shared/NodePipeServer.cs

Minimum change to get shared IPC added in #11546 recompiling again for #11383 (since the original PR was reverted).
- Splits up `DeserializeAndRoutePacket()` in `PacketFactoryRecord` (private class)
- Adds `DeserializePacket()` to `INodePacketFactory` and all implementations. Does not remove old method.
- Adds ifdef's to shared pipe classes for compilation purposes
No behavior changes to MSBuild.

Add separate DeserializePacket() to INodePacketFactory

---

documentation/specs/BuildCheck/Codes.md
src/Build/BuildCheck/Checks/ExecCliBuildCheck.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/BuildCheck.UnitTests/ExecCliBuildCheck_Tests.cs

Fixes #https://github.com/dotnet/msbuild/pull/11523#issuecomment-2777871126

Update BuildCheck code BC0109 -> BC0302

---

src/Build/BuildCheck/Infrastructure/EditorConfig/EditorConfigParser.cs
src/Build/Logging/BinaryLogger/BinaryLogger.cs

Fixes [#10866](https://github.com/dotnet/msbuild/issues/10866)
Binary log (.binlog file) contains embedded files. For improved diagnostics, we should also embed BuildCheck .editorconfig file to the binary log.
Use the static property to store all the .editorconfig file and call that in the BinaryLogger.cs Shutdown method.

Embed .editorconfig in binary log

---

Directory.Build.targets
eng/Build.props
eng/DotNetBuild.props

This minimizes the differences between a DotNetBuild and repo build. This will eventually allow to converge the entry point paths.
Fixes #

Move DotNetBuild properties into the repo

---

src/MSBuild.UnitTests/XMake_Tests.cs

Fixes [#11579](https://github.com/dotnet/msbuild/issues/11576)
MSBUILD : Logger error MSB4104: Failed to write to log file "S:\work\msb2\artifacts\bin\Microsoft.Build.CommandLine.UnitTests\Debug\net9.0\msbuild.binlog". The process cannot access the file 'S:\work\msb2\artifacts\bin\Microsoft.Build.CommandLine.UnitTests\Debug\net9.0\msbuild.binlog' because it is being used by another process.
Specify a path for the binlog that is defined by the test environment, so it doesn't conflict.

Fix parallelism in test case EndToEndMinimumMessageImportance

---

.github/workflows/perfstar-branch.yml

workflow to speed up running perfstar on a PR, creates a new perf/ prefixed branch on comment by insiders. which has the PRs changes + merged main into it.
https://github.com/JanProvaznik/actiontesting - this workflow successfully creates a new perf prefixed branch on /perfstar comment
1. Someone  (external/internal) creates a PR
2. member of the dotnet org or collaborator [see gh docs](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) on this repo can comment `/perfstar` on the PR
3. the action runs, creates a branch in the repo `perf/original-pr-branch-name`
4. on this new branch prefixed with perf, the internal perfstar infrastructure runs and members of the team can look at the report

perfstar branch creation gh action

---

src/Build/BackEnd/Components/Scheduler/SchedulingPlan.cs

Fixes #11705
buildplan file written to disk by setting MSBUILDENABLEBUILDPLAN can't be read on the next build because the written file seperates datw with spaces while the reading expected semicolons
Fixes bug introduced here: https://github.com/dotnet/msbuild/pull/4079/files#diff-8d669fb4d66fce73a89f3e6d364202f6095860780cacce11fa3561a6ab79a9fbR507
Space character was replaced with semicolon by accident.

Use correct separator character when parsing buildplan file

---

src/Build/Collections/RetrievableEntryHashSet/RetrievableEntryHashSet.cs
src/Build/Errors/InvalidToolsetDefinitionException.cs
src/MSBuild/CommandLineSwitchException.cs
src/MSBuild/InitializationException.cs

Fixes - CodeQL isssue dangerous deserialization
CodeQL issue dangerous deserialization below only happens in debug build by checking the code flows. It's safe for release build. 
[src/MSBuild/CommandLineSwitchException.cs : 20](https://codeql.microsoft.com/issues/65c9b22f-93ab-42b1-9e95-4542cc643038?Context=sdl)
[src/MSBuild/InitializationException.cs : 25](https://codeql.microsoft.com/issues/679d318f-89cf-4261-9171-db10ec4ab3bf?Context=sdl)
[src/Build/Collections/RetrievableEntryHashSet/RetrievableEntryHashSet.cs : 85](https://codeql.microsoft.com/issues/6debd16f-8bc8-42ef-82b6-9b65fb379850?Context=sdl)
[src/Build/Errors/InvalidToolsetDefinitionException.cs : 21](https://codeql.microsoft.com/issues/d634837c-340f-4981-a54c-325722834832?Context=sdl)
Add the comment to suppress the warning.

Suppress CodeQL warning dangerous deserialization that only happens in debug build

---

src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Framework/MSBuildEventSource.cs

Add these info to etl traces:
- Add a cancellation started event to better track the timeline of cancellation (when a customer attempts to cancel a build)
- Add Target List to build project start event ((now it's only on build stop event)
**Note :** [note: this PR changes the order of
_requestEntry.RequestConfiguration.RetrieveFromCache();
(string name, TargetBuiltReason reason)[] allTargets = _requestEntry.RequestConfiguration .GetTargetsUsedToBuildRequest(_requestEntry.Request).ToArray();
from looking at the code I'm pretty sure these don't interact in any way, but logging this if we eventually run into some side effect downstream of this](https://github.com/dotnet/msbuild/pull/11743/files#r2053726738)

Add more info to ETL traces

---

eng/Versions.props
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Tasks/GenerateResource.cs

Fixes #11678
Work item (Internal use): 
Regression in Visual Studio 17.13 (worked in 17.12). 
Binlog is not created for C++ project on Visual Studio load.
Harder to diagnose build failures/perf issues for vcxproj in VS.
Yes, from 17.12 to 17.13.
Manual testing:
1. Get any C++ projec. I got it from the feedback ticket
2. In the terminal set `MSBUILDDEBUGENGINE` and `MSBUILDDEBUGPATH`
3. in the same terminal open the C++ project with devenv
4. Check the `MSBUILDDEBUGPATH` for the binlogs
For using the correct msbuild
1. Use `build.cmd` script 
2. Use `~\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current` instead of `{Visual Studio path }\MSBuild\Current`
Low--spot fixes of refactorings.
The bug is on this line:
https://github.com/dotnet/msbuild/blob/7ad4e1c76585d0ed6e438da2d4f93943269343 …

[vs17.14] Binlog not produced for C++ project on Visual Studio Load Fix

---

src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

This change addresses the handling of SDK resolution errors in the `SdkResolverService`. It improves the error logging mechanism by distinguishing between single and multiple resolver scenarios, providing clearer and more informative error messages when SDK resolution fails caters to #10191 
- Updated error logging in `SdkResolverService` to differentiate between single and multiple resolver failures.
- Added a new resource string `SingleResolverFailedToResolveSDK` for clearer error messaging related to single resolver failures.
- Introduced a test `AssertSingleResolverErrorLoggedWhenSdkNotResolved` to verify that errors are correctly logged when SDK resolution fails with a single resolver.
- Enhanced `MockLoaderStrategy` to support initialization with only one resolver, making it easier …

Add single resolver error logging and related tests

---

src/Build/Instance/TaskRegistry.cs

Use GetTotalAllocatedBytes instead of GetTotalMemory.
This causes objects that were allocated to the heap but have since been collected to be accounted as well.
@JanKrivanek @rainersigwald ptal

TotalMemoryConsumption: include GC'd memory.

---

src/Build.UnitTests/BackEnd/BinaryTranslator_Tests.cs
src/Framework/BinaryTranslator.cs
src/Framework/ITranslator.cs
src/Framework/InternPathIds.cs
src/Framework/InterningReadTranslator.cs
src/Framework/InterningWriteTranslator.cs
src/MSBuildTaskHost/MSBuildTaskHost.csproj
src/Shared/TranslatorHelpers.cs
src/Tasks/SystemState.cs

When looking at serialization overhead for the RAR node, I found that most of the serialization overhead comes down to reading strings from the payload.
Many strings are shared between task items, such as common metadata values, file names, parent directories.
With the existing translator system, you *can* manually do this - you effectively need to create a temporary buffer, ID mapping, and offset the lookup depending on the direction. But it's difficult to set up, all child objects would need separate constructors, and it breaks the idea of having `ITranslator` be unidirectional since the write patterns have different ordering requirements - which makes it incredibly easy to accidentally break.
This bakes in an opt-in string interning API directly into the `ITranslator` framework. By …

Support string interning / deduplication within packets

---

src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs

Fixes https://github.com/dotnet/msbuild/issues/11791
https://github.com/dotnet/runtime/issues/114389#issuecomment-2851189615
wrap with check that we're using telemetry
existing tests

check telemetry should be collected before collecting mem info

---

src/Build.UnitTests/Telemetry/Telemetry_Tests.cs

Fixes #11676 
CI often fails here, the test case should be less strict for cases when GC doesn't allocate/cleans during task run.
relax condition that allocated memory can also be 0

Fix NodeTelemetryE2E test flakiness

---

src/Build/BackEnd/Components/RequestBuilder/Lookup.cs

In Framework, `List<T>.AddRange()` has a specialization for `ICollection<T>` where it allocates an intermediate array to copy the contents of the collection. It then copies the contents of the intermediate array to the inner list.
public void AddRange(IEnumerable<T> collection)
{
InsertRange(_size, collection);
}
...
public void InsertRange(int index, IEnumerable<T> collection)
{
if (collection == null)
{
ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
}
if ((uint)index > (uint)_size)
{
ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.index, ExceptionResource.ArgumentOutOfRange_Index);
}
if (collection is ICollection<T> { Count: var count } collection2)
{
if (count > 0)
{
EnsureCapacity(_size + count);
if (index < _size)
{
Array.Copy(_items, index, …

Avoid intermediate array allocation when the collection is first created

---

src/Build/Evaluation/Evaluator.cs
src/MSBuild/XMake.cs
src/Shared/FileSystem/WindowsFileSystem.cs
src/Shared/FileUtilities.cs

Fixes [#10201](https://github.com/dotnet/msbuild/issues/10201)
When build with  dotnet sdk 9.0, during evaluation, it can't find the file Program.cs with main function
When build with MSBuild.exe, it has the following error
Throw the PathTooLongException exception in windows when the file path exceeds the maximum length
Catch the exception when evaluation and processing the msbuild.exe command.

OutPut the PathTooLong when when longpath is disabled

---

src/Build/Evaluation/Evaluator.cs

This matches our preferred modern style. Happened to be in this file and was bothered.

Simplify `string` in evaluator

---

src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs

Reduce allocations for SdkResolverService

---

src/Build/Construction/ProjectElementContainer.cs

Reduce enumerator boxing in ProjectElementContainer

---

src/Build/Logging/TerminalLogger/TerminalLogger.cs
src/Framework/BuildException/BuildExceptionBase.cs
src/Framework/LoggerException.cs
src/Shared/ResourceUtilities.cs

And a few other things that fell out while I was doing so.

Nullable annotate ResourceUtilities

---

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs

Reduce allocations in TaskExecutionHost

---

src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Instance/ProjectItemInstance.cs

Avoid some smaller allocations in ItemGroupintrinsicTask

---

src/Build/Collections/CopyOnReadEnumerable.cs

Check for count through IReadOnlyCollection interface

---

eng/Versions.props
src/Tasks/DownloadFile.cs

[vs17.14] Merge tag v17.14.8

---

eng/Versions.props
src/Tasks/DownloadFile.cs

[vs17.12] Merge tag v17.12.36

---

eng/Versions.props
src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

The typo in substitutionGroup in Microsoft.Build.CommonTypes causes VS issues. 
Fix the invalid element in Microsoft.Build.CommonTypes.
Manual.

Fix invalid substitutionGroup in Microsoft.Build.CommonTypes

---

azure-pipelines/vs-insertion-experimental.yml
azure-pipelines/vs-insertion.yml
eng/Versions.props

we should be inserting 17.14 to 17.14 & the schedule should be set for main normal insertion not the experimental one
Pseudo-reverts https://github.com/dotnet/msbuild/pull/11558/
should be merged forward to main

Fix insertion target branches and schedule

---

.vsts-dotnet-ci.yml

Fixes #
In PR pipeline, sometimes the step publishing `Verify` `*.received.*` files fails with files not found error. It happens in the case xUnit runner crashes somehow and causes the test step failure while no `Verify` test fails. The flag to publish `Verify` `*.received.*` files is wrongly set.
Improve the condition setting the flag to publish `*.received.*` files.
N/A

Improve the condition setting the flag to publish *.received.* files

---

src/MSBuild/Resources/Strings.resx
src/MSBuild/Resources/xlf/Strings.cs.xlf
src/MSBuild/Resources/xlf/Strings.de.xlf
src/MSBuild/Resources/xlf/Strings.es.xlf
src/MSBuild/Resources/xlf/Strings.fr.xlf
src/MSBuild/Resources/xlf/Strings.it.xlf
src/MSBuild/Resources/xlf/Strings.ja.xlf
src/MSBuild/Resources/xlf/Strings.ko.xlf
src/MSBuild/Resources/xlf/Strings.pl.xlf
src/MSBuild/Resources/xlf/Strings.pt-BR.xlf
src/MSBuild/Resources/xlf/Strings.ru.xlf
src/MSBuild/Resources/xlf/Strings.tr.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hans.xlf
src/MSBuild/Resources/xlf/Strings.zh-Hant.xlf

Fixes #11468
The new feature uniquifying binary log path was added. But the help description hasn't been updated.
Add the document in the help description.
N/A

Add the document for uniquifying binary log path in the help description

---

src/Build/Instance/ProjectItemInstance.cs

Fixes #
We can avoid some closure object creations by extracting a portion of the existing code.
There are a non-trivial amount of allocations coming from this path, and we can reduce them by creating another method that is only called when we need the closure

Avoid closure object allocations in TaskItem.CopyMetadataTo

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

`csc` task in design-time build does not currently get the list of embedded resources as an input and thus does not include them in the generated command line.
Target `_GenerateCompileInputs` that generates the inputs needs `EmbeddedResource` to have metadata `WithCulture`, `Type` and `OutputResource` set. The former two are set in `SplitResourcesByCulture` target, which is a dependency of `PrepareResourceNames` target. The `OutputResource` is currently set by `GenerateResource` task.
To support updating resources during Hot Reload Roslyn needs to track resource files. To do that `/resource` command line arguments need to be produced by `csc` task at design-time.
This change moves setting of `OutputResource` metadata to a new target `AssignEmbeddedResourceOutputPaths` that is a dependency …

Include resources in command line arguments produced by csc in design-time build

---

src/Build.UnitTests/Evaluation/IntrinsicFunctionOverload_Tests.cs
src/Build/Evaluation/Expander/WellKnownFunctions.cs
src/Build/Evaluation/IntrinsicFunctions.cs
src/Build/Resources/Constants.cs

Fixes #
Fix the issue 11820, add two function DirectoryExists() and FileExists() https://github.com/dotnet/msbuild/issues/11820
Currently, doesn't have any goodway to check the File or the Directory is exist or not, and the [System.IO.Directory]::Exists() is not allowed.
Add two function DirectoryExists() and FileExists() in the msbuild, now we can use [MSBuild]::FileExist() or [MSBuild]::DirectoryExists() in the project files
I have performed testing for various exception to validate the changes. Tested two case FileExists and DirectoryExist

Fix issue 11820 Add DirectoryExists() and FileExists() function

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Reverts dotnet/msbuild#11893 because it causes issues in VMR https://github.com/dotnet/dotnet/pull/918#issuecomment-2934835328

Revert "Include resources in command line arguments produced by csc in design-time build"

---

src/Tasks/ManifestUtil/ComImporter.cs

Fixes #
AB#2495104
ClickOnce users report an intermittent build failure in Forms projects where the ClickOnce manifest creation task is running.
I was able to reproduce the issue on one of my machines intermittently where the call to System.Runtime.InteropServices.UCOMITypeInfo.ReleaseTypeAttr(...) throws a ComException with random unknown hr values.
From the documenation this type has been deprecated and replaced by System.Runtime.InteropServices.ComTypes.ITypeInfo since .NET 2.0.
Replacing the obsolete type with the recommended type fixes the issue of the random failure while calling ReleaseTypeAttr.
- Replace the obsolete type UCOMITypeInfo with the recommended type ITypeInfo.
- Ignore ComExceptions from ReleaseTypeAttr call.
- Fix memory leak where TypeLib COM object was not being …

Replace obsolete UCOMITypeInfo with recommended System.Runtime.InteropServices.ComTypes.ITypeInfo

---

src/Build/BackEnd/Components/Communications/CurrentHost.cs

Some tests were failing when run from Visual Studio because they were running in a .NET 9 process launched as `TestHost.exe`, not in a `dotnet.exe` host. That caused TaskHost launching to try to run `TestHost.exe MSBuild.dll` which failed, as TestHost isn't a general-purpose launcher.
Add another fallback to `GetCurrentHost()` to fall back to the current shared framework's parent `dotnet.exe`, if we can find it.

Support testhost.exe in TaskHost-launching tests

---

src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs

Fixes : Allocation issue.
Looking at a trace of allocations. It was shown that some of the allocations were coming from closures. This pr addresses the closures found.
* Removed lazy from exclude tester function since it was not needed since lifetime of lazy object was within the method itself.
* switched from linq clause for add range to manually adding items, because the linq version caused a closure from a method it did not have context with.
Used ILSpy to verify that the closures disappeared. (DisplayClass represents a closure)
Before
Afterwards

update to stop closures from lazy functions and linq

---

.config/git-merge-flow-config.jsonc

Sdk 9.0.200 and vs17.13 are out of support.

Retire 17.13 branch

---

src/Build/BackEnd/Components/RequestBuilder/Lookup.cs

Fixes # Captures that lead to allocations.
Based on a trace was able to see that allocations from captures that were from using linq without the correct context.
Manually created a list instead of using the where clause to create one.
Also moved over to grabbing the underlying struct enumerator when possible to avoid boxing.
Looked at the dll in ILSPY to verify change in closures.
Before. (Display Class shows a capture)
After (no more DisplayClass)

remove some closures as well as boxing from enumerator

---

src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs

Fixes #
Based on some traces there were some closures from a linq call without the right context. This caused extra allocations and this addresses it.
Instead of using linq to filter ites, just used a for loop to create a filtered list
Compared with ILSpy that there were less closures and allocations (DisplayName)
Before
After

Remove closures from ExpandItemIntoItems

---

src/Framework/IItemData.cs

Many allocations due to implicit object creation to capture function pointer + instance.
Here's 72MB / 1.19M `Func<IEnumerable<KeyValuePair<string, string>>` objects being supposedly allocated by `Utilities.CastItemsOnByOne`:
In reality, the allocation is actually happening in the `ItemData` constructor:
```cs
public readonly struct ItemData
{
private readonly Func<IEnumerable<KeyValuePair<string, string>>> _enumerateMetadata;
public ItemData(string type, object value)
{
Type = type;
Value = value;
if (value is IItemData dt)
{
EvaluatedInclude = dt.EvaluatedInclude;
_enumerateMetadata = dt.EnumerateMetadata;
}
else if (value is ITaskItem ti)
{
EvaluatedInclude = ti.ItemSpec;
_enumerateMetadata = ti.EnumerateMetadata;
}
else
{
EvaluatedInclude = value.ToString() ?? string.Empty; …
```

Perf: Don't cache ItemData.EnumerateMetadata pointer

---

src/Tasks.UnitTests/CodeTaskFactoryTests.cs
src/Tasks/CodeTaskFactory.cs

Fixes #
Fix the issue: Don't emit duplicate generated files into the binlog https://github.com/dotnet/msbuild/issues/11884
The CodeTaskFactory was generating multiple .tmp files in the binlog for each invocation of a task, even when the task used the same source code. The goal is to emit only one .tmp file per unique task source code after its first successful compilation.
Added a HashSet<FullTaskSpecification> _loggedCodeFiles to track task specifications already logged to the binlog.
Updated the logic to check _loggedCodeFiles before emitting a .tmp file, ensuring only one file is logged per unique FullTaskSpecification
Created a test project that invokes CustomTask multiple times with  parameters (InputParameter="Foo" and InputParameter="Bar") via Another.proj and directly.
Verified …

Don't emit duplicate src files to binlog in CodeTaskFactory

---

src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd
src/Tasks.UnitTests/ZipDirectory_Tests.cs
src/Tasks/Resources/Strings.resx
src/Tasks/Resources/xlf/Strings.cs.xlf
src/Tasks/Resources/xlf/Strings.de.xlf
src/Tasks/Resources/xlf/Strings.es.xlf
src/Tasks/Resources/xlf/Strings.fr.xlf
src/Tasks/Resources/xlf/Strings.it.xlf
src/Tasks/Resources/xlf/Strings.ja.xlf
src/Tasks/Resources/xlf/Strings.ko.xlf
src/Tasks/Resources/xlf/Strings.pl.xlf
src/Tasks/Resources/xlf/Strings.pt-BR.xlf
src/Tasks/Resources/xlf/Strings.ru.xlf
src/Tasks/Resources/xlf/Strings.tr.xlf
src/Tasks/Resources/xlf/Strings.zh-Hans.xlf
src/Tasks/Resources/xlf/Strings.zh-Hant.xlf
src/Tasks/ZipDirectory.cs

Fixes #11963
Compression can be parameterized by "level", which allows trading off time for compression ratio. This option was not available on the `ZipDirectory` task
Add a `CompressionLevel` parameter to the `ZipDirectory` task.
Also enabled null annotations in the task and its test.
Extend unit test.
A potential issue here is different `CompressionLevel` enum options between .NET Framework and .NET. A user could write a build script that uses `SmallestSize` and have their build work in one environment, then fail in another. I suspect this might cause issues in Visual Studio, for example.
I doubt this is a new issue for MSBuild tasks, so let me know what the standard way of handling this is. It would be a shame to disallow the `SmallestSize` value, as it's my original motivation for …

ZipDirectory task supports CompressionLevel

---

src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs
src/Build/Instance/ProjectTaskInstance.cs

Fixes #
Allocations due to boxing of enumerators in TaskBuilder
On some traces we're seeing some allocations due to boxing of enumerators in TaskBuilder.cs
If possible we want to avoid that.
* Changed an internal getter to return the actual type instead of the interface since it was used only once and would allow for using the underlying struct enumerator vs being boxed from the interface during a foreach loop.
* Saw another foreach loop that would end up being boxed from using IList. So changed it to use the indexed for loop to avoid using the enumerator all together.

Avoid boxing with enumerators in TaskBuilder.cs -> CreateListOfParameterValues

---

src/Shared/Modifiers.cs

This should be as high-performance as the current custom code and easier
to understand and maintain.
I tried a few options and this is slightly better than the existing code. This method is called 11729495 times in an OrchardCore build.
| Method                             | Job                  | Runtime              | Mean      | Error     | StdDev    | Ratio | RatioSD |
|----------------------------------- |--------------------- |--------------------- |----------:|----------:|----------:|------:|--------:|
| RegularSet                         | .NET 9.0             | .NET 9.0             | 0.5534 ns | 0.0097 ns | 0.0086 ns |  1.19 |    0.03 |
| Old                                | .NET 9.0             | .NET 9.0             | 0.4639 ns | 0.0087 ns | 0.0086 ns |  1.00 |    0.03 |
| …

Use FrozenSet to identify Modifiers

---

src/Build/BackEnd/BuildManager/BuildParameters.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BackEnd/Node/InProcNode.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
src/Build/BackEnd/Shared/BuildResult.cs
src/Build/BackEnd/Shared/IBuildResults.cs
src/Framework/BinaryTranslator.cs
src/Framework/ITranslator.cs
src/Shared/CommunicationsUtilities.cs
src/Shared/TranslatorHelpers.cs

CPU + allocations + memory usage by repeated construction of environment variables by returning a cached `FrozenDictionary` instance when no changes exist.
These are also currently held onto by `ConfigCache -> BuildRequestConfiguration`, so these will actually stay in the working set for the entire build if not de-duped.
*Before:*
*After:*
On .NET Core, `Environment.GetEnvironmentVariables()` internally creates a new Hashtable instance and string allocations for each key-value pair. Since the rest of MSBuild expects a typed `Dictionary<string, string>` instance, we need to allocate yet another dictionary and copy all the results.
```cs
IDictionary vars = Environment.GetEnvironmentVariables();
Dictionary<string, string> table = new Dictionary<string, string>(vars.Count, …
```

Perf: Frozen environment variable caching

---

src/Build/BackEnd/Components/Scheduler/Scheduler.cs

Directly enumerate requests when scheduling one.

---

src/MSBuild/XMake.cs

Fixes #11244
When using Binary Logger (`/bl`), it also enables Detail Summary (`/ds`).  It adds 3-5% additional size to the binlog itself.  
BL requires diagnostic verbosity that indirectly enables DS.
This change will specifically not enable DS from BL by evaluating the verbosity state before upping the verbosity level.  Users can still enable add `/ds` or `/v:diag`.
There isn't a unit test for this area, so manually test it.
**Is Detail Summary Shown**
| Arguments | Before | After |
|-|-|-|
|` `|no|no|
|`/bl`|yes|no|
|`/bl /ds`|yes|yes|
|`/bl /v:d`|yes|no|
|`/bl /v:diag`|yes|yes|
|`/fl`|no|no|
|`/fl /ds`|yes|yes|
|`/fl /v:d`|no|no|
|`/fl /v:diag`|yes|yes|
|`/bl /fl`|yes|no|

Change BinLog (/bl) to no longer enable Detail Summary (/ds).

---

src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs

We can avoid allocating an intermediate string inside of EnsureParameterInitialized()
Before:
After:

Avoid allocating intermediate string.

---

src/Build/BackEnd/Components/RequestBuilder/Lookup.cs

Reduces `LinkedList` related allocations in `Lookup`.
Before
After (- ~235MB)
`Lookup` uses `LinkedList<Scope>` to implement a stack with the ability to peek into the next item. Given how many of these are created, this is a large source of allocations since every element requires an overhead of 48 bytes per `LinkedListNode<T>`.
This isn't necessary since we already have an object which represents a unidirectional node... the `Scope` itself.
 
This adds a `Next` property to `Lookup.Scope` which allows `Lookup` to use it as an implicit stack, avoiding the need for any intermediate collections.

Perf: Implicit Lookup.Scope stacks

---

documentation/release-checklist.md

We need to preserve one opt-prof data for every release branch that is in support. We should always have some opt-prof in VS Drop that we can use for the servicing if needed. Add an action to the release check list for preserving the opt-prof data.

Add opt-prof expiration data extension step to the release checklist

---

.vsts-dotnet.yml
eng/Versions.props

In the case there isn't available VS manifest files from VSDrop, internal build is blocked by OptProf tasks. This needs another  mode that opts out of all OptProf tasks. Then add the switch running OptProf tasks or not.

Add the switch running OptProf tasks

---

src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs
src/Build.UnitTests/Evaluation/SdkResultEvaluation_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs
src/Build/BackEnd/Components/SdkResolution/SdkResult.cs
src/Build/BackEnd/Components/SdkResolution/SdkResultFactory.cs
src/Build/BackEnd/Shared/BuildRequestConfiguration.cs
src/Build/Definition/Project.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Evaluation/IEvaluatorData.cs
src/Build/Evaluation/LazyItemEvaluator.EvaluatorData.cs
src/Build/Evaluation/PropertyTrackingEvaluatorDataWrapper.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Instance/ProjectPropertyInstance.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Framework/Sdk/SdkResult.cs
src/Framework/Sdk/SdkResultFactory.cs
src/Tasks.UnitTests/ResolveAssemblyReference_CustomCultureTests.cs

Enable https://github.com/dotnet/roslyn/issues/78939 by adding the ability for SDK resolvers to return environment variables.
The environment variables are set during _execution_, because they cannot be reliably set during evaluation, which may be happening concurrently within a process. The value is also set as a regular property for ease of access during evaluation time.

Add environment variable support to SDK resolvers

---

src/Build/Collections/CopyOnWritePropertyDictionary.cs

Usage of `yield return` causes the compiler to create a state machine to handle the enumeration. For `ImportProperties()`, this amounts to ~130MB of allocations of the state machine.
We used this state machine to transform the incoming `IEnumerable<T>` to a KVP to be consumed by `ImmutableDictionary<TKey, TValue>.SetItems()`.  We can avoid this by using an `ImmutableDictionary<TKey, TValue>.Builder` to avoid the need for a state machine.
After:
Using a builder rather than repeatedly calling `Add()` has two main advantages. `SetItems()` overwrites values if the key already exists while `Add()` will throw, and using a builder is more efficient.

Avoid creation of enumerator state machines

---

src/Build.UnitTests/BackEnd/BuildManager_Tests.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf

Fixes #11166
Log message added
One test was updated to reflect the change

Log the start of Static Graph construction

---

src/Build/BackEnd/Components/SdkResolution/SdkResultFactory.cs
src/Framework/Sdk/SdkResultFactory.cs

The recent change causes issues in VMR
https://dev.azure.com/dnceng-public/public/_build/results?buildId=1084638&view=results
`Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs(89,40): error CS0121: (NETCORE_ENGINEERING_TELEMETRY=Build) The call is ambiguous between the following methods or properties: 'SdkResultFactory.IndicateSuccess(IEnumerable<string>, string, IDictionary<string, string>, IDictionary<string, SdkResultItem>, IEnumerable<string>)' and
'SdkResultFactory.IndicateSuccess(IEnumerable<string>, string, IDictionary<string, string>, IDictionary<string, SdkResultItem>, IEnumerable<string>, IDictionary<string, string>)'`
this proves to resolve the issue
https://github.com/dotnet/dotnet/pull/1389/checks?check_run_id=45276701182

Fix SdkResultFactory conflicting parameters

---

.vsts-dotnet.yml
eng/Versions.props

When disabling OptProf data collection, build should skip apply optimization data.

Override SkipApplyOptimizationData to true when disabling OptProf data collection

---

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs

Fixes #
In a previous PR (https://github.com/dotnet/msbuild/pull/11918), I made a switch to using a dedicated thread to process the queued packets rather than chaining tasks together by calling `ContinueWith()` to avoid some async overhead. I had a misunderstanding about the lifetime of the `NodeContext` and a new thread was created *each* time a new context was created and never cleaned up. This causes a large number of threads to be created. This PR switches back to processing the queue using the threadpool, and cleans up the previous approach to avoid chaining tasks.

Switch back to using thread pool to process packet queue

---

src/Build.OM.UnitTests/Construction/ProjectItemGroupElement_tests.cs
src/Build/Construction/ProjectElementContainer.cs

Fixes [#11933 ](https://github.com/dotnet/msbuild/issues/11933)
```
<ItemGroup>
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
</ItemGroup>
```
**dotnet add package Serilog --version 4.3.0
The trailing comment on the Newtonsoft.Json line is moved to the newly added package.**
```
<ItemGroup>
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
<PackageReference Include="Serilog" Version="4.3.0" />
</ItemGroup>
```
If the reference element is immediately followed by a series of XML nodes, each of which does not contain any line breaks and is whitespace, a comment, or a processing instruction, then insert the new element after those nodes.
AddPackageReference_PreservesTrailingCommentOnSameLine

Fix the addxml  when add node after comment xml node

---

eng/Packages.props
eng/Versions.props

This is the latest GA version for this release and should resolve some CG alerts.

Bump to NuGet 5.11.6

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Reverts dotnet/msbuild#11949
it causes perf regressions, need to discuss the change separately. 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2528565

Revert "Include resources in command line arguments produced by csc in design-time build (take 2)"

---

eng/Packages.props
eng/Versions.props

https://github.com/dotnet/msbuild/pull/12161 broke in the VMR dependency flow PR https://github.com/dotnet/dotnet/pull/1490 because this version isn't in source-build-reference-packages.
Add a comment so this is clearer when updating next time.

Add comment for updating MicrosoftCodeAnalysisCollectionsVersion

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

There are tests in the SDK that verify clean works in various scenarios:
```csharp
[Fact]
public void It_cleans_the_project_successfully_with_static_graph_and_isolation()
{
var (testAsset, outputDirectories) = BuildAppWithTransitiveDependenciesAndTransitiveCompileReference(new[] { "/graph", "/bl:build-{}.binlog" });
var cleanCommand = new DotnetCommand(
Log,
"msbuild",
Path.Combine(testAsset.TestRoot, "1", "1.csproj"),
"/t:clean",
"/graph",
"/bl:clean-{}.binlog");
cleanCommand
.Execute()
.Should()
.Pass();
foreach (var outputDirectory in outputDirectories)
{
outputDirectory.Value.GetFileSystemInfos()
.Should()
.BeEmpty();
}
}
```
This one and several others started failing when VMR codeflow with https://github.com/dotnet/msbuild/pull/12096 in it flowed to SDK.
The root of the problem is …

Track FileWritesShareable that occur underneath the project directory

---

src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs

There is a concurrency issue with `NodeProviderInProc._nodeContexts`. It should be `ConcurrentDictionary`
https://dev.azure.com/dnceng-public/public/_build/results?buildId=1098853&view=ms.vss-test-web.build-test-results-tab&runId=30052564&resultId=101712&paneView=debug
```
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
at Microsoft.Build.BackEnd.NodeProviderInProc.ShutdownConnectedNodes(Boolean enableReuse) in /_/src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs:line 160
at Microsoft.Build.BackEnd.NodeManager.ShutdownConnectedNodes(Boolean enableReuse) in /_/src/Build/BackEnd/Components/Communications/NodeManager.cs:line 148
at …
```

Make node contexts managed by NodeProviderInProc concurrent

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

The rootcause is tracked internally: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2533238/

Revert "Track FileWritesShareable that occur underneath the project directory"

---

src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs
src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs

This came up in investigating devdiv2535034, which was a regression in exception count caused by a property function within a condition throwing an exception when fully stringified (but not on normal expansion due to short-circuiting condition evaluation).
But the problem is more broad--during a design-time build or even a regular build at low verbosity, these low-pri events would just be thrown away.
Extend the `OnlyLogCriticalEvents` check to include verbosity for the logging-only expansion of a false condition.
With this change I don't see any `FormatException`s or `TruncateString` calls loading OrchardCore or Roslyn solutions.

Don't log false-condition expansion unnecessarily

---

eng/Versions.props
src/Build.UnitTests/BackEnd/MockSdkResolverService.cs
src/Build/BackEnd/BuildManager/BuildManager.cs
src/Build/BackEnd/Components/Communications/SerializationContractInitializer.cs
src/Build/BackEnd/Components/SdkResolution/HostedSdkResolverServiceBase.cs
src/Build/BackEnd/Components/SdkResolution/ISdkResolverService.cs
src/Build/BackEnd/Components/SdkResolution/OutOfProcNodeSdkResolverService.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs
src/Build/BackEnd/Components/SdkResolution/SdkResolverServiceException.cs
src/Build/BackEnd/Node/OutOfProcNode.cs
src/Build/Evaluation/Evaluator.cs
src/Build/Microsoft.Build.csproj
src/Framework/MSBuildEventSource.cs

Backports https://github.com/dotnet/msbuild/pull/12194 in vs17.14
In VS it's a long standing issue when a customer opens a large solution and attempts to close VS instance in the middle of DTB (design time build) or build process it can hang.
The rootcause is the race condition between 
Undergoing shutdown operation in OutOfProc node and parallel invocation of SdkResolver from Evaluation
The issue was fixed for 2 potential scenarios:
1) When SDK resolution requested AFTER Cancellation happens ;
- Setup a guard flag `IsNodeShutDown` and checking it's value on request;
2) Cancellation happens AFTER  SDK resolution requested but BEFORE the response was received 
- Trigger `ShutdownComponent()` from SdkResolutionService BEFORE cleaning up engine caches (the prevent the deadlock in the …

[vs17.14] Add check for node shut down event and reorder the sequence of shutdown in OutOfProcNode

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Fixes https://github.com/dotnet/sdk/issues/49582
Reverts the original revert of #12192 in #12233
The previous version of this change created a new itemlist made from FileWrites and FileWritesShareable and used that in subsequent operations. This version doesn't create a new item list.
Use conditions to determine which set of items should be considered for cleaning - only FileWrites, or FileWrites + FileWritesShareable
Currently doing manual testing

Redo filewritessharable change with hopefully higher performance

---

src/Build/Instance/TaskRegistry.cs

Fixes #12123
Currently when using the new `-mt` switch to enable multi-threaded behavior, we sometimes get this concurrency error:
```
dotnet build SimpleMultiProcTest.sln -mt
Restore complete (0,8s)
info NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
ProjectC failed with 1 error(s) (0,3s)
MSBUILD : error : 
This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISS
UE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled
System.InvalidOperationException: Operations that change non-concurren
t collections must have exclusive access. A concurrent update was performe
d on this collection and corrupted its state. The collection's state is no
longer correct.
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue v …
```

Fix race condition in TaskRegistry for multi-threaded MSBuild

---

src/Tasks/Microsoft.Common.CurrentVersion.targets

Reverts dotnet/msbuild#12096
The rootcause is tracked internally: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2533238/

Revert "Allow FileWritesShared to be tracked and cleaned with an opt-in flag"

---

src/Build.UnitTests/TerminalLogger_Tests.cs
src/Build/Logging/TerminalLogger/TerminalLogger.cs

Fixes #12237 
The API for making terminallogger or consolelogger instances didn't apply the same precedence ordering as msbuild.exe itself did - making it hard to test in API-based consumers of terminallogger.
* Added a forced-enablement semantic to the API to align with MSBuild.exe
* ensures that CLI flags passed to the API supersede env var flags with the same behavior as MSBuild.exe
Automated testing to assert that expected logger types are created in the various newly-enforced scenarios
Thanks to copilot chat for doing this for me :)

Align TL creation API with msbuild.exe forcing behavior

---

src/Build.UnitTests/Instance/TaskItem_Tests.cs
src/Build/BackEnd/Components/RequestBuilder/Lookup.cs
src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
src/Build/Instance/ProjectInstance.cs
src/Build/Instance/ProjectItemDefinitionInstance.cs
src/Build/Instance/ProjectItemInstance.cs
src/Build/Instance/ProjectMetadataInstance.cs
src/Build/Microsoft.Build.csproj
src/Framework/IConstrainedEqualityComparer.cs
src/Framework/IMetadataContainer.cs
src/Framework/ImmutableDictionaryExtensions.cs
src/Framework/MSBuildNameIgnoreCaseComparer.cs
src/Framework/SerializableMetadata.cs
src/Framework/TaskItemData.cs
src/MSBuild/MSBuild.csproj
src/MSBuildTaskHost/MSBuildTaskHost.csproj
src/Shared/CopyOnWriteDictionary.cs
src/Shared/TaskParameter.cs
src/Shared/TranslatorHelpers.cs
src/Shared/XMakeElements.cs
src/Tasks/Microsoft.Build.Tasks.csproj
src/Utilities/Microsoft.Build.Utilities.csproj
src/Utilities/TaskItem.cs

Fairly complex refactor to replace `TaskItem` metadata wrapper classes with direct use of `ImmutableDictionary<string, string>`. This eliminates multiple categories of allocations and significantly reduces known hot paths such as `GatherTaskItemOutputs` and `CopyMetadataTo`.
On OrchardCore, this change alone cuts RAR by ~40% + many other tasks, reduces allocations by ~1.4GB, and has a noticeable impact on E2E build time.
Also fixes #11895
**GatherTaskItemOutputs - Before**
**GatherTaskItemOutputs - After**
**/m:1 Total Allocations - Before**
**/m:1 Total Allocations - After**
**/m:1 Working Set - Before**
**/m:1 Working Set - After**
**/m cold incremental build (no nodes) - Before**
```
...
2771 ms  ResolvePackageAssets                     436 calls
3057 ms  ProcessFrameworkReferences …
```

Perf: Directly use ImmutableDictionary for TaskItem metadata

---

src/Build/Collections/PropertyDictionary.cs

Fixes #12234
Fixed a race condition in `PropertyDictionary<T>` that was causing `InvalidOperationException: Operation is not valid due to the current state of the object` during MSBuild's multi-threaded serialization process.
**Root Cause**: The `GetEnumerator()` methods in `PropertyDictionary<T>` had a lock inconsistency issue:
1. They would acquire a lock on `_properties`
2. Get an enumerator from the underlying collection
3. **Immediately release the lock**
4. Return the enumerator for use outside the lock
This meant that while one thread was enumerating the collection (e.g., during serialization in `TranslateProjectPropertyInstanceDictionary`), another thread could modify the collection, causing the `RetrievableEntryHashSet<T>.Enumerator` to detect concurrent modification and throw an …

Fix concurrency issue in PropertyDictionary

---

src/Build/CompatibilitySuppressions.xml
src/Build/Definition/ProjectCollection.cs

https://github.com/dotnet/msbuild/pull/12082 introduced a binary-breaking change to the ProjectCollection constructors, which is breaking VMR codeflow at https://github.com/dotnet/dotnet/pull/1764.
Made the new change in a binary-compatible way by adding the old constructor signature and forwarding to the new constructor with a default value set for the new parameter. This also meant that we get to remove the CompatibilitySuppression, which should have been a red flag in the first place.

Add overload for ProjectCollection constructor to prevent binary breaking change

---

src/Build/BackEnd/Components/Scheduler/Scheduler.cs

Related to: https://github.com/dotnet/msbuild/pull/12179
The return type has changed because it conflicts with RentPooledBuffer method signature.

Fix the build after moving to UnscheduledRequestsWhichCanBeScheduled

---

src/MSBuild.UnitTests/MSBuildServer_Tests.cs
src/MSBuild/XMake.cs

Fixes #12225
There were issues with interactive mode and MSBuild server so the server was silently disabled when running in interactive mode.
Ignore the interactive switch and launch MSBuild server anyways.
Modified the old test that checked for the MSBuild server not starting to instead check we started anyways.

we can now ignore the interactive switch in msbuild server and launch

---

src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Shared/FileMatcher.cs
src/Shared/Resources/Strings.shared.resx
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

Fixes #12334 
#11211 introduced logging the exception when globbing fails to improve debuggability.
This leads to error that some codepaths can't find a string resource because the resource is only in the assembly Microsoft.Build, but the code using it is in multiple assemblies (Microsoft.Build, Microsoft.Build.Tasks.Core, Microsoft.Build.Utiliities.Core)
Move the resource string from Microsoft.Build's resources to Shared resources.
manual validation: 
created a test build using the resource in code in Microsoft.Build.dll and in Microsoft.Build.Tasks.Core.dll at the place where the issue was reported. 
I didn't find a way to make a unit test for it because the behavior leading to this log message is not reliably reproducible, and test for "grab this one resource and check for no …

Move GlobExpansionFailed resource from Build to Shared

---

.github/copilot-instructions.md

Just noticed that a recent change duplicates this instruction, so removing the duplicate.

Remove duplicate copilot instruction

---

src/Build/Evaluation/ConditionEvaluator.cs

Fixes #
The implementation of `ConcurrentStack<T>` creates a new wrapper node each time an item is pushed onto the stack
public void Push(T item)
{
Node node = new Node(item);
node.m_next = m_head;
if (Interlocked.CompareExchange(ref m_head, node, node.m_next) != node.m_next)
{
PushCore(node, node);
}
}
The creates an appreciable amount of allocations during build:
These allocations can almost entirely be eliminated by using a vanilla generic `Stack<T>` with a lock.

Avoid allocations due to ConcurrentStack usage

---

src/Build/Instance/ProjectInstance.cs

Work item (Internal use): devdiv2542861 (web), devdiv2522896 (MAUI)
Fix an issue that caused `DOTNET_HOST_PATH` to not be set as expected for .NET SDK tasks in some build situations, including VS Publish and build-with-restore-from-`MSBuild.exe`.
Publish for web projects and ILMerge failed with unfixable and hard-to-diagnose errors.
Yes, introduced with #12077 (enabling setting `DOTNET_HOST_PATH` in .NET Framework-driven builds like through VS).
Automated testing, scenario testing for Web Publish through VS and on the command line.
Medium: changes a codepath that is important for .NET SDK projects where test coverage (finding this issue and getting it to us) is suboptimal. Change is scoped to .NET SDK projects but affects all of them.
In many of the constructor codepaths that create …

Don't leak SDK-resolver environment to global env

---

azure-pipelines/vs-insertion.yml
src/MSBuild/app.amd64.config
src/MSBuild/app.config

Updating binding redirects for workflow editor tools in VS. This allows
building of workflow projects in VS.
Workflow editor is non-functional.
Yes, from 17.14.
Applied fix locally and verified WF projects could build.
Low--assembly binding redirect is isolated to this scenario.
add change to insert to main

[vs17.15] redirects for workflow editor tools in VS (#12372)

---

eng/Versions.props
src/Build/Resources/Strings.resx
src/Build/Resources/xlf/Strings.cs.xlf
src/Build/Resources/xlf/Strings.de.xlf
src/Build/Resources/xlf/Strings.es.xlf
src/Build/Resources/xlf/Strings.fr.xlf
src/Build/Resources/xlf/Strings.it.xlf
src/Build/Resources/xlf/Strings.ja.xlf
src/Build/Resources/xlf/Strings.ko.xlf
src/Build/Resources/xlf/Strings.pl.xlf
src/Build/Resources/xlf/Strings.pt-BR.xlf
src/Build/Resources/xlf/Strings.ru.xlf
src/Build/Resources/xlf/Strings.tr.xlf
src/Build/Resources/xlf/Strings.zh-Hans.xlf
src/Build/Resources/xlf/Strings.zh-Hant.xlf
src/Shared/FileMatcher.cs
src/Shared/Resources/Strings.shared.resx
src/Shared/Resources/xlf/Strings.shared.cs.xlf
src/Shared/Resources/xlf/Strings.shared.de.xlf
src/Shared/Resources/xlf/Strings.shared.es.xlf
src/Shared/Resources/xlf/Strings.shared.fr.xlf
src/Shared/Resources/xlf/Strings.shared.it.xlf
src/Shared/Resources/xlf/Strings.shared.ja.xlf
src/Shared/Resources/xlf/Strings.shared.ko.xlf
src/Shared/Resources/xlf/Strings.shared.pl.xlf
src/Shared/Resources/xlf/Strings.shared.pt-BR.xlf
src/Shared/Resources/xlf/Strings.shared.ru.xlf
src/Shared/Resources/xlf/Strings.shared.tr.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hans.xlf
src/Shared/Resources/xlf/Strings.shared.zh-Hant.xlf

A string resource placed to a wrong resource file leads to a "resource not found" exception instead of logging the string.
The logging was introduced to flag suspicious intermittent behavior, but is not supposed to fail the build.
The class `FileMatcher` is compiled in `Microsoft.Build.dll` and `Microsoft.Build.Tasks.Core.dll` and `Microsoft.Build.Utilities.Core.dll`.
The message takes it's content from a localized string resource. This resource is present only for `Microsoft.Build.dll`, so when the issue is hit in the `CreateItem` task from `Microsoft.Build.Tasks.Core.dll` an uninformative exception about the resource being missing occurs instead.
The fix is to move it to resource files shared between all MSBuild assemblies.
Reported by internal customer that an MSBuild exception …

[vs17.14]Move GlobExpansionFailed resource from Build to Shared

---

.vsts-dotnet.yml
Directory.Build.targets
azure-pipelines/.vsts-dotnet-build-jobs.yml
azure-pipelines/.vsts-dotnet-exp-perf.yml
azure-pipelines/vs-insertion-experimental.yml

Attempt 2 for https://github.com/dotnet/msbuild/pull/12126
The previous one was reverted due to problems with exp pipelines.
Now it got resolved with some tweaks around package validation in VS tests.
validated in scope of https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/663724

Split internal pipeline on exp and prod

---

.vsts-dotnet.yml
azure-pipelines/.vsts-dotnet-build-jobs.yml
azure-pipelines/.vsts-dotnet-exp-perf.yml

- Changed the templates from having stages: at the top level to jobs:. This is because it's being included as a job template, not a stage template.
- Post-build Template Location: Moved the post-build template from inside the job template (where it doesn't belong) to the main pipelines at the stage level where it should be.

Move post-build to main ymls

---

src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs

Fixes #12415
During one of our recent optimization runs we reduced stack size of the DrainPacketQueue times.
While this is fine in a normal scenario, it sometimes results in a StackOverflow during debugging or performance runs.
Increased the stack size.
@Erarndt is planning to refactor this away in the near future so I hope this is a sufficient hotfix for the interim.
This doesn't affect production, only custom builds.

issue-12415 increase stack size

---

eng/Versions.props
src/Framework/Telemetry/TelemetryConstants.cs
src/Shared/Constants.cs
src/Utilities/CompatibilitySuppressions.xml
src/Utilities/ToolLocationHelper.cs

* Bump version number to 18.0
* Compat suppression for VersionLatest change

Version 18.0

---

documentation/wiki/CollectedTelemetry.md

Just a quick change to sync this now that https://github.com/dotnet/msbuild/pull/12508 is merged.

Add multithreaded mode indication to telemetry documentation

---

src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2421790/?view=edit
The Retail Build Validation (DartLab) CI pipeline has been experiencing intermittent MSB4017 logger failures with ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection in BuildEventArgsWriter.WriteArguments(). The error occurs when Convert.ToString() is called on objects with corrupted internal state, particularly StringBuilder instances with inconsistent internal fields (m_ChunkLength, m_ChunkOffset) due to race conditions, memory corruption, or unsafe code in build tasks.
Added defensive exception handling in WriteArguments() method to catch ArgumentOutOfRangeException and InvalidOperationException when converting arguments to strings. When corruption is …

Add try/catch to prevent ArgumentOutOfRangeException in BuildEventArgsWriter.WriteArguments

---

src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEntry.cs

Fixes #
With the current way the code is constructed, the parameters for the error message in `ReportResult()` end up getting boxed even if they never end up getting used. By expanding this a little and guarding the call based on the error condition, we only pay the allocation cost in the error state.
There are ~11MB of allocations due to the types being boxed.

Avoid boxing allocations for creation of error message in non-error cases

---

src/MSBuild/ValidateMSBuildPackageDependencyVersions.cs

Example outputs with two intentionally misaligned versions:
```
S:\msbuild\src\MSBuild\app.config(36): error : Binding redirect for 'Microsoft.Bcl.AsyncInterfaces' redirects to a different version (9.0.0.123) than MSBuild ships (9.0.0.9). [S:\msbuild\src\MSBuild\MSBuild.csproj::TargetFramework=net472]
S:\msbuild\src\MSBuild\app.amd64.config(203): error : Binding redirect for 'System.Reflection.Metadata' redirects to a different version (9.0.0.18) than MSBuild ships (9.0.0.9). [S:\msbuild\src\MSBuild\MSBuild.csproj::TargetFramework=net472]
```
This came up when working on a runtime-library version bump; the errors nicely broke the build but the fix could have been easier.

Report line number in app.config error

---

azure-pipelines/vs-insertion.yml

Fixes an error
/azure-pipelines/vs-insertion.yml (Line: 94, Col: 7): 'value' is already defined
That arose because we needed an elseif after the new clause.

Avoid redefining AutoInsertTargetBranch

---

eng/Versions.props

Moving version label near to version prefix hoping that we will introduce merge conflicts on version label when merging release branch to main. 
See https://github.com/dotnet/msbuild/pull/12592#discussion_r2406653561

Move version label next to version prefix
